### ISSUE TITLE
Component field as required doesn't work

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#10030]
## Bug report / description
Strapi doesn't show any reaction if component fields (in my case a repeatable one) are set as required field, but were not filled with data or were not add/created at all.

### Steps to reproduce the behavior
1. Create collection type with a component, which in my case contains a text field and a relation field
2. Click on the created comonent inside your collection type -> advanced settings -> required field
3. create your collection type entry and do NOT create a component or add values to it.

Nothing will happen if you click on save!

A workaround in my case would be to set the relational field inside the component as required, but this doesn't work either, because there has been an issue for a long time with this too https://github.com/strapi/strapi/issues/557

### Expected behavior
Some working input validation, which highlights the component/field and/or shows a message, that it is required.

### System

- Node.js version: 14.15.4
- NPM version: 6.14.10
- Strapi version: 3.2.5
- Database: SQLite
- Operating system: Ubuntu 20.04

**Comment by soupette** [comment]
Hello @baermathias thanks for reporting this issue.

In fact the required constraint for the components is the following:

- Required single component:
The value cannot be `null` or `undefined`, if you are using the admin panel you can see that the value is initiated with an empty object `{}`. If your component has required fields then the validations checks that the value is not an empty object.

- Required Repeatable component:
Similarly to the single component the value cannot be `null` or `undefined` so when using the admin panel you can see that the value is initiated with an empty array `[]`. Then, if your component has some required fields the validations checks that the fields are not empty.

Also, for the repeatable components, if you apply the `required` and the `min=2` constraints the admin panel will initiate your components with an array of 2 empty objects: `[{}, {}]`.

Here is some practical exemple:

Let's say you have the following structure:



**Path: components/default/dummy_compo_with_required_field**
```
{
  "collectionName": "components_default_dummy_compo_with_required_fields",
  "info": {
    "name": "dummy_compo_with_required_field",
    "icon": "arrows-alt-h"
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    }
  }
}
```

**Path: components/default/dummy_compo**
```
{
  "collectionName": "components_default_dummy_compo_with_required_fields",
  "info": {
    "name": "dummy_compo_with_required_field",
    "icon": "arrows-alt-h"
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string",
    }
  }
}
```

**Path api/dummy/models/dummy.settings.json**

```
{
  "kind": "collectionType",
  "collectionName": "dummies",
  "info": {
    "name": "dummy"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "dummy_compo": {
      "type": "component",
      "repeatable": false,
      "component": "default.dummy-compo",
      "required": true
    },
    "dummy_compo_with_required_field": {
      "type": "component",
      "repeatable": false,
      "component": "default.dummy-compo-with-required-field",
      "required": true
    },
    "repeatable": {
      "type": "component",
      "repeatable": true,
      "required": true,
      "component": "default.dummy-compo"
    },
    "repeatables_with_fields": {
      "type": "component",
      "repeatable": true,
      "component": "default.dummy-compo-with-required-field",
      "required": true
    },
    "repeatable_with_min": {
      "type": "component",
      "repeatable": true,
      "required": true,
      "min": 2,
      "component": "default.dummy-compo"
    },
   "repeatable_with_fields_and_min": {
      "type": "component",
      "repeatable": true,
      "required": true,
      "min": 2,
      "component": "default.dummy-compo-with-required-field"
    }
  }
}
```

In order to pass the validations for creating an entry you will need to POST the following data:

```
{
  dummy_compo: {},
  dummy_compo_with_required_field: {name: "name"},
  repeatable: [],
  repeatable_with_fields_and_min: [{name: "name"}, {name: "name"}],
  repeatable_with_min: [{}, {}],
  repeatables_with_fields: [],
}
```

I hope this helps.

**Comment by baermathias** [comment]
OK I have just created a new dummy project and it has a component with two fields `name` and `email`. I use it inside the user collection type:

![Screenshot from 2021-04-26 15-51-10](https://user-images.githubusercontent.com/45003352/116099166-faaa1100-a6ab-11eb-80b7-a9d5353be05f.png)

It is set to `required`

![Screenshot from 2021-04-26 15-51-23](https://user-images.githubusercontent.com/45003352/116101094-d5b69d80-a6ad-11eb-8f83-9e855d6e91da.png)

But I still was able to create a record without adding a component:

![Screenshot from 2021-04-26 15-50-44](https://user-images.githubusercontent.com/45003352/116101177-e8c96d80-a6ad-11eb-8402-6464a9a03454.png)

**Comment by kasonde** [comment]
Hi @baermathias to reiterate your description. When you set the relation to a repeatable component as "required", you don't expect the parent collection to be able to create any data. Especially since right under the checkbox for "Required Field" it says:
> You won't be able to create any entry if the field is empty. 

But currently it is possible to create an entry. 

Cc: @JabStrapi @maevalienard @sam-pires

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/component-field-as-required-doesnt-work

Thanks!
