### ISSUE TITLE
Field label is not respected in the list view of the Content Type

### ISSUE THREAD

**Issue by chirdeeptomar** [strapi/strapi#10053]
### Describe the bug

Field label is not respected in the list view of the Content Type

### Steps to reproduce the behavior

1. Go to 'Content Type'
![image](https://user-images.githubusercontent.com/77834/114937334-8f537a00-9e35-11eb-8dff-4b2c87a8c7b3.png)

### Expected behavior

I would expect it to respect the label as below

### Screenshots

![image](https://user-images.githubusercontent.com/77834/114937431-b3af5680-9e35-11eb-9bad-462a64974d8b.png)

### Code snippets

Not Applicable 

### System

- Node.js version: 15.13.0
- NPM version: 7.7.6
- Strapi version: v3.5.4
- Database:  SQLITE
- Operating system: WSL Ubuntu

**Comment by soupette** [comment]
Hello @chirdeeptomar there is two setting views in the content manager, one for the edit view and one for. the list view. According to your screenshot, you are configuring the label for the edit view. In order to access the list view settings, you need to click on the configure the view link that is located here:

<img width="1418" alt="Screenshot 2021-04-14 at 15 55 13" src="https://user-images.githubusercontent.com/13311463/114989807-176a6b80-9e98-11eb-963a-b4a31f6d10e3.png">

I am closing this issue
