### ISSUE TITLE
contentType metadatas i18n

### ISSUE THREAD

**Issue by halisyalcinkaya** [strapi/strapi#10110]
Hi, thank you for i18n :)
i need i18n for contentType metadatas. like label, description and placeholder

### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Quick summary what's this feature request about.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/i18n-for-content-manager-metadata
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
