### ISSUE TITLE
Prisma ORM as DB connector

### ISSUE THREAD

**Issue by joelbqz** [strapi/strapi#10129]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary
Prisma ORM connector

### Why is it needed?
I built a full-stack web application a couple of months ago using Strapi as my Nodejs framework, it did work very well until I had to build custom queries, the experience with bookshelf ORM wasn't good.

### Suggested solution(s)
Prisma Client and Prisma Migrations are production-ready, I think it is a very superior ORM than Bookshelf with strong typing out of the box.

**Comment by d2kx** [comment]
They are building a new DB foundation for v4, but details are sparse. This would be an obvious choice and I'd love to give my +1 for this idea.

# Offtopic

I have also wondered about some of the technological decisions they've made, including bookshelf/knex in a world where Prisma exists, using passport.js which has been hardly maintained for years, using weird community packages like node-ses instead of the offical AWS SDK for mail, using lots of duplicate stuff like both FontAwesome 4 and 5 for the admin panel at the same time, using multiple HTTP clients (axios, node-fetch), etc. I hope they'll find some time to clean up these things before it comes back to bite them.

**Comment by derrickmehaffy** [comment]
I will let @strapi/maintainers comment about the Prisma part but it's unlikely we will switch

---

>I have also wondered about some of the technological decisions they've made, including bookshelf/knex in a world where Prisma exists

See above comment, but there is also a cost to making large shifts like that and it has to be done for a good reason. There is really nothing that Prisma offers that Bookshelf/Knex doesn't (if anything the reverse is true). I do agree that bookshelf's documentation is fairly poor.

> using passport.js which has been hardly maintained for years

The passport parent library sure, but they haven't needed to make updates to it. Passport's strengths are with the providers, of which many are very well maintained and new packages are offered all the time. 
https://www.npmjs.com/search?q=passport&ranking=maintenance

> using weird community packages like node-ses instead of the offical AWS SDK for mail

![image](https://user-images.githubusercontent.com/8593673/116616425-911b4400-a8f1-11eb-8cc9-e8e5529f4b3d.png)

![image](https://user-images.githubusercontent.com/8593673/116616485-a001f680-a8f1-11eb-84e2-e82c020b2592.png)

Same features for 0.081% of the size

> using lots of duplicate stuff like both FontAwesome 4 and 5 for the admin panel at the same time

This will be fixed in Strapi v4 as we are completely redesigning the Strapi admin panel and are likely going to remove FontAwesome entirely

> using multiple HTTP clients (axios, node-fetch), etc. 

Legacy code mainly, will most likely be fixed in Strapi v4

> I hope they'll find some time to clean up these things before it comes back to bite them.

Strapi v4 will certainly change quite a bit considering we are stopping all feature development to just refactor large parts of the code-base.

**Comment by d2kx** [comment]
That is a useful answer, thank you @derrickmehaffy!

Although on SES, the point is not entirely fair. Your other official package (strapi-provider-upload-aws-s3) is pulling in aws-sdk anyway, and most people that are using SES (AWS customers) will likely use S3 also, so that's included anyway.

And it should not have to be this way, since aws-sdk is the old v2 SDK from AWS. The current version is modularized, so a fair comparison would be against [@aws-sdk/client-ses](https://www.npmjs.com/package/@aws-sdk/client-ses) which is much smaller. Similarly, strapi-provider-upload-aws-s3 should switch from aws-sdk to [@aws-sdk/client-s3](https://www.npmjs.com/package/@aws-sdk/client-s3).

**Comment by derrickmehaffy** [comment]
I don't disagree there and you make a good point. Most likely not something we would set a high priority on but if anyone wanted to contribute a PR we certainly wouldn't mind :wink:

**Comment by alexandrebodin** [comment]
Hi, the thread went a bit off topic but I want to comment on Prisma :) 

For a bit of context I want to highlight a few thigns before answering :)
We are providing more and more higher level abstractions on top of the database. Components, Medias, Dynamic zones and we are adding more Content management features that require a more complex database structure. 

This goes beyond simple tables & relations in the DB. We may have intermediate tables / revision tables and so on. This makes interacting directly with the database schema more complex and honestly not super developer friendly.

There are actually multiple layers we see:

ContentType  -> Strapi Data layer (knows avout components, dynamic zones ...) -> Lower level Data layer (ORM or no ORM) -> the Database itself

What we want developers to spend most of their time using is the Strapi Data layer and not so much the underlying ORM or Query builder. This could still be very usefull for lower level customization or plugin development.

Currently our main focus is to provide a better experience with the Strapi Data layer and this one needs to be developped by us.

That being said we could still expose as we currently do a different underlying ORM than bookshelf. We will certainly drop bookshelf in v4 but the question is still open between using another ORM or working at a lower level with a Query builder instead. They both have pros and cons and if you want to give your ideas please do :) 

What about Prisma ? 

Prisma has so good pros
- Very good developer experience (but with the database schema becoming more complex this wouldn't last)
- Support for migrations (but woulnd't support higher level abstraction, e.g migrating components)

Some cons too
- Prisma doesn't support all the relation types we need (polymorphic relations a.k.a union types)
- No programmatic way to create a schema we would need to convert the content types to a Prisma schema. write the file to disk or a virtual FS and then generate the Prisma client with it. Some do it but this doesn't fit well with where we want to go (e.g not having to dump files to disk until a developer wants to do custom code)

Those cons sadly would be roadblocks with the features we already support or want to develop.

However this could change in the future and a Prisma connector might be built some day :)

I hope this gives you some insights for your question :)

**Comment by nmitra6** [comment]
It's very difficult to work with strapi data layer. It's very inefficient too. Imagine, their graphql support, it's laughable. Pulling entire data and relations and then filtering, violating all the specs of graphql. Working with Bookshelf and Knex are nightmare. Sequelize and typeORM - far better but they have cons too.  Bookshelf can't even fetch distinct values on column. Knex support migration. Where is that in Strapi? Prisma lot better with migration. If you are planning to rewrite datalayer, make graphql the first class citizen and try to overcome cache and other well known shortcomings of graphql.

**Comment by derrickmehaffy** [comment]
I believe @alexandrebodin gave quite a bit of information on the topic but I wanted to clarify a few things regarding v4 and finally I will close and lock this issue because at this time **we do not plan to implement PrismaORM (or any ORM) for now**.

- With the launch of the v4 we have completely removed Bookshelf.js as a dependency and will only be using Knex.js
- We have basically constructed our own ORM from scratch that better fits the needs and complexity that Strapi requires and to date no other ORM has been able to provide us. At the moment we aren't planning to release this as an "ORM" for other projects to use but functionally that is exactly what it is.

For more information, I invite you to review the package that is basically functioning as our ORM: https://github.com/strapi/strapi/tree/releases/v4/packages/core/database/lib

Likewise I would suggest you review our Query layer RFC for the v4: https://github.com/strapi/rfcs/blob/v4/query-engine/rfcs/xxx-v4-query-engine.md

As for the connection layer to the database, we will use Knex.js and utilize it's migration system in the v4 as well.
