### ISSUE TITLE
Strapi doesn't support Node 16

### ISSUE THREAD

**Issue by DCStudioProjects** [strapi/strapi#10149]
### Describe the bug

Strapi doesn't support Node 16

### Steps to reproduce the behavior

1. Try to install it

### Expected behavior

Successful installation

### System

- Node.js version: 16

**Comment by derrickmehaffy** [comment]
We will not support Node 16 until October when it becomes LTS.
See: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#general-guidelines

> Node LTS (v12 or V14) Note that odd-number releases of Node will never be supported (e.g. v13, v15).

https://nodejs.org/en/about/releases/

![image](https://user-images.githubusercontent.com/8593673/116130631-4fd02d80-a680-11eb-9537-9ed99bf6e989.png)

Duplicate:
https://github.com/strapi/strapi/issues/10134
https://github.com/strapi/strapi/issues/10051

**Comment by jonathanstanley** [comment]
I suspect part of the reason this appears more frequently now is that [node 14.x.x does not support apple silicon natively](https://github.com/nodejs/node/issues/36161#issuecomment-730648429).  if a developer is only working with strapi, then it is easy enough to get it working now.  but for those with other projects that are updated to accommodate apple m1 chip, it is quite a pain to set a [compatible version of node + vips/sharp](https://github.com/strapi/strapi/pull/9866).  

in my testing, [brew](https://brew.sh/) and even [volta](https://volta.sh/) were unable to switch both node+vips in one command.  other than writing another script, the only option i can see until then is to uninstall/reinstall node+vips each time you change packages.  or perhaps just go back to docker.  but would love to know alternatives or earlier adoption of node 16.x.x with strapi

**Comment by derrickmehaffy** [comment]
> I suspect part of the reason this appears more frequently now is that [node 14.x.x does not support apple silicon natively](https://github.com/nodejs/node/issues/36161#issuecomment-730648429). if a developer is only working with strapi, then it is easy enough to get it working now. but for devs with other projects that work with apple m1 chip, it is quite a pain to set a [compatible version of node + vips/sharp](https://github.com/strapi/strapi/pull/9866).
> 
> in my testing, [brew](https://brew.sh/) and even [volta](https://volta.sh/) were unable to switch both node+vips in one command. other than writing another script, the only option i can see until then is to uninstall/reinstall node+vips each time you change packages. or perhaps just go back to docker. but would love to know alternatives or earlier adoption of node 16.x.x with strapi

It's the common case with bleeding edge, early adopters generally are aware that for a while they will have to run through some painful steps. I had similiar issues with various compatibility in Linux when I bought my Ryzen 1950x or my Vega 64. It takes time to build in better compatibility, less time in my case since AMD openly contributes to the Linux kernel but Apple released no information and so the Node devs did not have time to roll out support in Node 14.

We ourselves don't want to be chasing bugs from users using Node 16 if those bugs will just get patched before it goes LTS, much for the same reason an enterprise wouldn't use Node 16 just like they wouldn't run an Ubuntu 20.10 server since it's not an LTS release.

However, that being said we have various employees at Strapi running M1 Macs with very little issue using Node 14.

**Comment by z1haze** [comment]
well its passed October, now what?

**Comment by derrickmehaffy** [comment]
Strapi support for Node v16 will be in our v4 (it's already in the current beta release.

We won't be backporting Node v16 to Strapi v3.
