### ISSUE TITLE
Automatic update for existing projects

### ISSUE THREAD

**Issue by imjustd** [strapi/strapi#1018]
It would be nice to be able to update existing project with the latest Strapi release. Something like `strapi update` in the project's folder would be handy. I don't know if this is possible/simple to achieve, but it's a nice to have feature instead of manually updating the project files/folders.

**Comment by derrickmehaffy** [comment]
Absolutely have a +1 from me on this. Especially with some of the previous FR for migrating from dev -> staging -> beta -> prod. This would make development stage updates so much easier and user friendly.

Might be a ways out, especially with the focus on stability instead of features but this should certainly be added the strapi vote page.

**Comment by msgeissler** [comment]
I agree this would be nice. Maybe something worth looking into towards the end of the alpha, when the architecture and API has been ironed out more. Especially for minor and patch level updates this would be a great win and time saver. If a major update needs some manual steps that is totally fine, not everything can be automated especially with the flexibility that strapi provides under the hood.

**Comment by Aurelsicoko** [comment]
I created a new card on our public portal. I just noticed the number of upvotes on this issue. Please go upvote the feature on Product Board as well (https://portal.productboard.com/strapi/c/41-automatic-project-update).

Since we're considering to implement this feature, I'm closing this issue. We are moving all the features requests on Product Board.
