### ISSUE TITLE
i18n for media alternativeText

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#10220]
## Feature request

I would need a way to set alternativeTexts per language on files in the upload plugin.

For now I just built a custom collection, which contains a file and localized alt text.
However, I think this is a very common use case and related to i18n plugin, so I just opened as an issue.

### Please describe your feature request

It is not on the public board, for I believe its part of the i18n plugin, but I could be wrong.

### Summary

Alternative texts on media files for different languages.

### Why is it needed?

It is needed for SEO.

### Suggested solution(s)

Add i18n for `alternativeText`.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/i18n-for-media-alternativetext
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
