### ISSUE TITLE
Save and publish?

### ISSUE THREAD

**Issue by AregGhazaryan** [strapi/strapi#10243]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I think it will be cool to add a third button when adding content which will be `save and publish` which as you guessed it just saves and publishes, just for a better UX. 

### Why is it needed?

It gets tiresome from time to time to wait for it to save then publish. And i think that will be a great addition.

**Comment by derrickmehaffy** [comment]
CC: @maevalienard

**Comment by maevalienard** [comment]
Thanks for the idea! We'll look at this :D

**Comment by Kinbaum** [comment]
Hi @maevalienard to take this idea even further, how can I have a live published page, while also saving draft content to view on a preview url (using something like Next.js preview mode)? If everything looks good in the preview, I want to replace the live content at a later date.

**Comment by maevalienard** [comment]
Hi @Kinbaum, unfortunately it's not possible to do so now, but it's a topic we have on our roadmap :)

**Comment by Kinbaum** [comment]
Thanks for the quick response @maevalienard glad to hear it’s on the roadmap 👍🏻

**Comment by Kinbaum** [comment]
Hi @maevalienard has there been any progress on this topic?

**Comment by maevalienard** [comment]
Hi @Kinbaum, thanks for following up! As for the answer: Yes and no. The good news is that with v4 out, we have more flexibility to rework that feature and do something more suited for the app. We plan to have a look at that around Q2. I'm very sorry for the time it takes

(cc @yanniskadiri)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/add-a-button-to-save-and-publish-at-the-same-time
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
