### ISSUE TITLE
Content created by content api and its state is set to published by default.

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#10246]
### Describe the bug

Create content by content api and state is set to published

### Steps to reproduce the behavior

1. POST /{content-type}
2. In Admin panel, the inserted content's state is "Published"

### Expected behavior

I add a content in Admin panel, and content's state is "Draft",
I insert a content using content api and content's state is "Published", I think it should be "Draft" by default.
These two method should have same behavior and same result.

**Comment by kasonde** [comment]
Hi, @smoothdvd that's the intended way the Content API works. I believe that it's that way because this feature was added to the core of Strapi as an update and the sudden change would've 'broken' the functionality of the Content API for existing apps. You can create drafts by adding `published_at` to your request body and set it as `null`.
