### ISSUE TITLE
Core Store Data Loss Issue

### ISSUE THREAD

**Issue by nunosilvamourao** [strapi/strapi#10260]
### Bug Description
On our current Strapi setup, everyday, overnight the core_store is losing some entities. Since one of our latest releases the latest entities/models that we've added are not regenerated, leading to a loss on permissions related with those same entities.

### Steps to Reproduce

1. Some entities on core store are loss overnight
2. If I restart the webapp service it regenerates the core_store appropriately with all the entities
3. But, the permissions related with those entities are lost and need to be recreated
4. Logs don't show any crash on Strapi
5. Staging environment doesn't show same behavior. Possibly related with multi container setup in production?

### Expected Behavior
Core Store to not lose the entities

### System

NodeJS version: 10.21.0
Strapi Version: beta.17.8
Database: Pgres
Strapi Environment Setup: Azure AppServices with multiple Containers

### Additional context

I know we should upgrade our strapi version but due to breaking changes and being a huge application we can't prioritize this at the moment. So trying my luck to understand if someone faced this or might know the root cause or a workaround until we are able to migrate.

**Comment by derrickmehaffy** [comment]
> Strapi Version: beta.17.8

> I know we should upgrade our strapi version but due to breaking changes and being a huge application we can't prioritize this at the moment. So trying my luck to understand if someone faced this or might know the root cause or a workaround until we are able to migrate.

I understand why you can't upgrade right now but I'm sorry we don't support that version anymore per our: https://github.com/strapi/strapi/security/policy

I have to mark the issue as closed because if allow you to do it then I have to allow others. I would recommend you open a thread on our community forum: https://forum.strapi.io. We try to keep the GitHub issues clean and relevant only to changes we need to make on the existing code, not for general help and support.
