### ISSUE TITLE
Strapi admin page will not load when using a non-default URL behind a reverse proxy

### ISSUE THREAD

**Issue by AugustZellmer** [strapi/strapi#10286]
### Describe the bug

Strapi admin page will not load when using a non-default URL behind a reverse proxy. The spinner just spins forever. There are no errors.

### Steps to reproduce the behavior

Add a relative URL to the server.js file, kinda like this:

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('URL', '/cms'),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '2380253secretKey23505901'),
    },
  },
});
```
Build Strapi and deploy to Google Cloud Platform, as per the Strapi documentation.
Configure a GCP load balancer (which I understand to be a reverse proxy) to direct all traffic going to `mywebsite.com/cms/*` to the Node environment running Strapi.
![image](https://user-images.githubusercontent.com/1058866/117768938-b6188c80-b1f8-11eb-8d90-a6c5559fefa1.png)
Navigate to `mywebsite.com/cms/admin`.

### Expected behavior

The admin page loads.

### Actual Behavior

The page loads, but the spinner spins forever and the login form never shows. The logs have no errors:
![image](https://user-images.githubusercontent.com/1058866/117770040-10feb380-b1fa-11eb-917d-a9a43920787a.png)

### System

- Node.js version: 14.16.1
- NPM version: 6.4.12
- Strapi version: 3.6.1
- Database: postgres
- Operating system: GCP

**Comment by AugustZellmer** [comment]
The only warning in the console is
`DevTools failed to load SourceMap: Could not load content for chrome-extension://bfogiafebfohielmmehodmfbbebbbpei/javascript/sandblaster.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`
which doesn't seem relavent???

**Comment by cschweda** [comment]
Have you tried loading the admin page in Chrome's incognito mode -- i.e., all extensions off?

**Comment by AugustZellmer** [comment]
Good idea, but no change.

**Comment by AugustZellmer** [comment]
I've tried this with Strapi 3.6.x, 3.4.x, and 3.0.x, all of which exhibited the same issue. Maybe I've just set something up wrong, but I can't imagine what. And the lack of an error message doesn't make things easy.

**Comment by AugustZellmer** [comment]
I had missed this earlier, but the call to init is 404ing.
![image](https://user-images.githubusercontent.com/1058866/117830040-e4b65780-b238-11eb-84fc-6f55da5f91f7.png)

I don't know how to fix that though.

**Comment by derrickmehaffy** [comment]
Can you please try with a absolute url in the server.js and not a relative.

**Comment by AugustZellmer** [comment]
If I change the URL property to `https://mywebsite.com/cms`, the admin page simply 404s.

**Comment by cschweda** [comment]
Are you using Nginx for the reverse proxy? If so -- what's your ```/cms``` config?

**Comment by AugustZellmer** [comment]
That's the difficult thing, and *could* be the source of my problem, but I'm not sure.

I am using Google Cloud Platform's load balances. I think these are implemented using a Nginx reverse proxy (probably?), but I do not have access to the .conf (afaik) because Google abstracts that away.

**Comment by derrickmehaffy** [comment]
> I am using Google Cloud Platform's load balancers. I think these are (probably?) implemented using a Nginx reverse proxy under the hood, but I do not have access to the .conf (afaik) because Google abstracts that away.

They are not, just like AWS ELB does not. 

Load balancer !== Proxy
Proxy !== Load Balancer

Nginx = Webserver + LB + Proxy.

---

In a typical system like this you would use the load balancer to direct traffic to multiple proxy applications (fail-over / LB) and those proxy applications can LB certain applications. Specifically you need a proxy application that can do rewrite rules and the google one cannot. See the references in our documentation:

Nginx: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/nginx-proxy.html#sub-folder-unified

```
location /api/ {
        rewrite ^/api/?(.*)$ /$1 break;
```

HAProxy: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/haproxy-proxy.html#sub-folder-unified

```
backend strapi-backend
        http-request set-path "%[path,regsub(^/api/?,/)]"
```

Caddy (not needed it does the rewrite automatically)
Apache (you would do this in .htaccess files, we don't have a guide due to the poor performance of Apache at proxying)

**Comment by maxisam** [comment]
I have the same problem. I set my url like https://strapi.xxx.com that points to my reverse proxy. However, it tried to access http://0.0.0.0/admin/init, which causes an issue. I build my custom docker image, so it is a clean build every time. (I add build and cache into dockerignore).

When I don't set url. the problem goes away. It uses relative url instead of absolute url.

**Comment by AugustZellmer** [comment]
@derrickmehaffy
I didn't realize that they, like, weren't reverse proxies. Maybe there is no bug, and it was just my mistake. Thanks for the help!

**Comment by derrickmehaffy** [comment]
No problem @AugustZellmer we plan to adjust the proxying layer most likely in v4 by auto-prefixing all endpoints with a /api to make it easier and may also convert the `api/*/config/routes.json` to just a standard .js file instead.

For now marking this as closed since a proxy layer that support rewrites is needed.

**Comment by ccqgithub** [comment]
same problem
