### ISSUE TITLE
Provide a way to add collaborators to a Strapi app and other improvements

### ISSUE THREAD

**Issue by SebastianBogado** [strapi/strapi#104]
Hi, and thanks for this framework!

I'd like to share my experience and some features/fixes I thought of.

Today after creating my Strapi app and playing around a bit, I decided to share the code with a teammate so we could both work on this new project.

The `.gitignore` file looked good, so I just created a repo and `git add`'ed the whole folder.

When the other dev cloned the repo, running `strapi start` wouldn't work because `config/studio.json` was not present. On the other had, running `strapi new` wouldn't work because it needs an empty folder. 
Back to the json file, it's ignored because it has the secret key that connects my local Strapi server to the Studio, I get it. So we versioned a `config/studio.json.example` without the secret key but with the actual app id, and shared the secret key privately.

At that point, running `strapi start` would almost work, except that there were some dependencies missing. Of course, run `npm install` and it should work. Except it didn't. There were some libs that I had on my `node_modules` that were not at the `package.json`, so I added `"fs-extra": "~0.26.2"` and
`"pluralize": "~1.2.1"`.

Back to `strapi start`, it got up and running but it wouldn't connect to the Studio. We tried running `strapi link`, but it deleted my app, and created a new one, which belonged to his account. 

We went some steps back (created another app, gave him the id and secret), and still `strapi start` wouldn't connect to the Studio. Of course, his account had nothing to do with the app I created, it makes sense that he wasn't able to connect. So I just shared my credentials with him.

Finally, he was able to get the local Strapi server running, and connected to the Studio but it started behaving buggy when we were both connected.

From this experience, I gathered some tasks that needs to be done, along other nice to have features:
- add to `package.json` every dependency needed; currently missing `fs-extra` and `pluralize`
- state in the docs that `strapi link` will delete your current app
- provide a way to link the current project folder with an existent app, given its app id and secret key
- provide a way to add collaborators to an app, so there's no need to share the same credentials

First and third would also help those that have more than one dev environment, for instance, desktop and laptop.

Sorry for the long post, and thanks again :)

**Comment by loicsaintroch** [comment]
Hi @SebastianBogado, thank you very much for your interesting feedback, we appreciate it.

> When the other dev cloned the repo, running `strapi start` wouldn't work because `config/studio.json` was not present. On the other had, running `strapi new` wouldn't work because it needs an empty folder.

Very good point you're right. What solution do you suggest to easily make it work without sharing the key?

> At that point, running `strapi start` would almost work, except that there were some dependencies missing. Of course, run `npm install` and it should work. Except it didn't. There were some libs that I had on my `node_modules` that were not at the `package.json`, so I added `"fs-extra": "~0.26.2"` and `"pluralize": "~1.2.1"`.

npm >= v3.0.0 no longer supports symbolic links in the `node_modules` directory. This is fixed and will be released for the v2. We simply copy/paste every dependency from the `node_modules` directory of the global installation to the local one. This is the best work around we've found. Regarding the missing dependencies: I'll definitely make some tests and adjustments before releasing the v2.

> We went some steps back (created another app, gave him the id and secret), and still `strapi start` wouldn't connect to the Studio. Of course, his account had nothing to do with the app I created, it makes sense that he wasn't able to connect. So I just shared my credentials with him.

Collaboration is a feature we really need and want on the Studio. Agreed. Unfortunately this is not a priority for us right now but this is definitely in our todo list for a next version.

As you may know, we have decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

Please join us [on Slack](http://slack.strapi.io) to have more details about the v2.

Thanks again for your message, it means a lot to us.

**Comment by Aurelsicoko** [comment]
This feedback concerned the v2. Please take a look at [our latest blog post](http://blog.strapi.io/inside-the-box-july-2016/) to understand how we deal with this version. The Studio will still be alive during the next month but all the features in the Studio will be open-sourced so the use case you described will not be possible anymore.

I don't close this issue because some things are still useful for the v3.0. Thanks again!
