### ISSUE TITLE
To set a default value for JSON type

### ISSUE THREAD

**Issue by VivianSolide** [strapi/strapi#10409]
### Summary

To set a default value for JSON type

### Why is it needed?

The current default value is undefined which isn't very handy in my case.

### Suggested solution

It would have been great to set these kind of default variables, directly from the admin panel:

- `[ ]`
- `{}`
- `null`
- `undefined`

### Related issue

#5781

cc @derrickmehaffy

**Comment by georgeiliadis91** [comment]
Hello so the issue I am finding with this approach is that when i add it on a component that is assigned to a user. 
I cant register a user. afterward since the login fails saying something about invalid credentials. 

The moment i removed the default from the compoent I was able to register the user. This seems very poorly thought out. Since there are many issue up regarding how the users content type work with other types and what not. (not being able to add images without extending endpoints etc)
