### ISSUE TITLE
ENOENT: no such file or directory, mkdir '/workspace/api/test' error when deployed to Google App Engine

### ISSUE THREAD

**Issue by mikhail-tokarev** [strapi/strapi#10410]
strapi returns `ENOENT: no such file or directory, mkdir '/workspace/api/test'` when we try to create a collection type.

### Steps to reproduce the behavior

1. Deploy strapi to Google App Engine as described here https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html
2. Go to 'Content-Types Builder'
2. Click on 'Create new collection type'
3. Add 'Test' to Display Name > Continue > Text > Add 'name' to Name > Finish
4. Click on 'Save'
5. See error "An error occurred"

### Code snippets

from browser console

```
main.2e79059e.chunk.js:1 POST https://strapi.[domain].io/content-type-builder/content-types 400
main.2e79059e.chunk.js:1 
{err: Response}
err: Response
body: (...)
bodyUsed: true
headers: Headers {}
ok: false
payload: {error: "ENOENT: no such file or directory, mkdir '/workspace/api/test'"}
redirected: false
status: 400
```

### System

- Node.js version: v14.16.1
- Strapi version: 3.6.2 Community Edition
- Database: Postgres 13
- Operating system: GAE
- Environment: production
- Command: strapi develop

**Comment by kasonde** [comment]
Hi @mikhail-tokarev. The reason you're facing this issue is that Strapi needs to make changes to the file system when you create/update/delete content types. Google Cloud doesn't provide persistent write access to apps deployed on GAE. Typically, we recommend that your Strapi app be stateless in IAAS environments like GAE. Take a look at [this post by the Google Cloud team (Bullet points towards the end of the article)](https://cloud.google.com/appengine/docs/standard/nodejs/configuration-files). This is also why we provide a guide for you to [set up file uploading using Google Cloud Storage](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html#file-uploading-to-google-cloud-storage) buckets.
