### ISSUE TITLE
Add webp and avif conversion to strapi-plugin-upload

### ISSUE THREAD

**Issue by devgar** [strapi/strapi#10420]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**

- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Add option to create copies for uploaded images in webp and avif.
By default the plugin should keep it's behaviour and not convert uploads. But if its configuration is enabled to convert, it should save an additional copy for each breakpoint in every enabled image type.

### Why is it needed?

This two image type formats are very useful to improve web loading time.

### Suggested solution(s)

I have implemented this feature, the unique modified file is `image-manipulation.js`, no additional dependencies are needed.
https://github.com/devgar/strapi/blob/243d914efeebfdb44b236af76689c30b73fed646/packages/strapi-plugin-upload/services/image-manipulation.js

### Related issue(s)/PR(s)

No pull request created yet. Working on tests.

**Comment by dirq** [comment]
This would be awesome.

**Comment by wedelgaard** [comment]
Would love to see this feature as well, `webp` is well supported by browsers these days

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/add-webp-and-avif-conversion-to-strapi-plugin-upload
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
