### ISSUE TITLE
i18n integration with GitHub

### ISSUE THREAD

**Issue by maggie0002** [strapi/strapi#10426]
The new i18n feature is a real godsend, thanks for the integration. 

A feature that would really help would be the ability to integrate the strings from i18n with a GitHub repo. This would allow translation tools such as Weblate, CrowdIn and so on to be able to read the required translations and facilitate the translated fields. At the moment, doing it manually is limited by the number of languages I speak, and the man hours it is taking to input all the strings by myself (this is due to me not being able to provide database access to volunteer translators for data integrity reasons). 

I imagine it is only the roadmap somewhere, if so I will close off the request, but couldn't find it elsewhere.

**Comment by derrickmehaffy** [comment]
Due to the way i18n functions but in the future we could allow for integration with other translation services to help do it automatically. For that I would advise opening a new feature on https://feedback.strapi.io

Going to mark this issue as closed as we don't plan to do this type of translation support for now.
