### ISSUE TITLE
There is no way to determine a multi-media vs single-media field

### ISSUE THREAD

**Issue by Drarok** [strapi/strapi#10525]
### Describe the bug

It is impossible to identify which media fields are multi-media;

When looking at the fields in the content-type builder:
![Strapi Media Example](https://user-images.githubusercontent.com/55830/122983531-00faf780-d394-11eb-962c-5af724672cc1.png)

And also when editing the entity itself:
![Screenshot 2021-06-22 at 19 56 46](https://user-images.githubusercontent.com/55830/122983552-08220580-d394-11eb-8033-86987ca5d7ad.png)

### Steps to reproduce the behavior

1. View a content-type that has both single- and multi-media fields
2. Attempt to identify which is which

### Expected behavior

There should be some way to differentiate between the single- and multi- variants of the media field.

### Screenshots

Inline, above.

### Code snippets

N/A

### System

- Strapi version: 3.6.3

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/there-is-no-way-to-determine-a-multi-media-vs-single-media-field

Thanks!
