### ISSUE TITLE
Tables are poorly-designed for even small scale, resulting in poor performance

### ISSUE THREAD

**Issue by Drarok** [strapi/strapi#10571]
### Describe the bug

We've been experiencing saves to localized entities taking around of 7-10 seconds in the UI and via the REST API. Having dug into the database, I have found and fixed several issues which have improved the speed, but it's still incredibly slow for such low data volume.

These issues were picked up by enabling the MySQL slow query log:

1. There is no index on `upload_file_morph`.`related_id` which is queried a lot
2. There are _no_ usable indexes on an entity's components table
3. There are _no_ usable indexes on localization tables created by the i18n plugin

I also spotted that  the `*_id` fields in the localization tables aren't created `UNSIGNED` which I'm sure used to be a problem in some RDBMS, but I can't find a source on that. It certainly _will_ cause problems trying to insert a large enough value into the signed field.

5. 
### Steps to reproduce the behavior

1. Add \~40 entities and \~10 locales, fill in each one
2. Modify one of the entities via the admin panel or REST API
3. See how long it takes

### Expected behavior

Updating one entity out of 40-400 (depending if you count the localized entities or not) should not take more than _one_ second, let alone several.

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.3
- Database: MySQL 5.7 / MariaDB 10.4

**Comment by Drarok** [comment]
Follow-up: I added these indexes and reduced update time from around 8s to just under 4s:

```sql
ALTER TABLE `upload_file_morph` ADD INDEX `related_id` (`related_id`);

ALTER TABLE `ENTITIES__localizations`
	ADD INDEX `related:ENTITY` (`related_ENTITY_id`, `ENTITY_id`),
	ADD INDEX `ENTITY_id` (`ENTITY_id`);

ALTER TABLE `ENTITIES_components`
	ADD INDEX `component_id:field` (`component_id`, `field`),
	ADD INDEX `order` (`order`);
```

I've also noticed that loads and loads _and loads_ of queries are issued, each targeting some individual piece of data. These could (and _should_, IMO) be written in a way to reduce the overall number of queries with a little more client-side processing, but I don't know enough about Strapi internals to tackle that.

**Comment by Drarok** [comment]
I'm also looking into why only _some_ of our entities are suffering from this for similar volumes of records. My current hunch is that a combination of many components and localizations _together_ are exponentially increasing the workload on the back-end or database.

**Comment by derrickmehaffy** [comment]
Hi @Drarok yes you are correct there is quite a bit of inefficiency at the database layer for complex features like that, most is largely due to technical debt happening in the v3. We are entirely rebuilding the database layer in our v4 and just recently released our RFC on the query layer for the v4: https://github.com/strapi/rfcs/pull/31

**Comment by Drarok** [comment]
That's all well and good for the future, but the missing indexes are something that could be fixed _now_ and save a lot of time for all users with even a moderate amount of data, no?

**Comment by derrickmehaffy** [comment]
> That's all well and good for the future, but the missing indexes are something that could be fixed _now_ and save a lot of time for all users with even a moderate amount of data, no?

Our efforts are focused on rebuilding the **entire database layer** in our v4, it would be counter productive to start making massive changes to the v3 when all that effort will go to waste once we get to the v4 which will support the indexes.

**Comment by Drarok** [comment]
I'd hardly describe a couple of indexes on a type of table as "massive". A nice quality-of-life improvement for all users now, rather than an _unusably_ slow system in an easily-uncovered case.

What's the roadmap for v4 being released? How long are you happy for the platform to run even slower than _WordPress?_

**Comment by derrickmehaffy** [comment]
> I'd hardly describe a couple of indexes on a type of table as "massive". A nice quality-of-life improvement for all users now, rather than an _unusably_ slow system in an easily-uncovered case.
> 
> What's the roadmap for v4 being released? How long are you happy for the platform to run even slower than _WordPress?_

- Internal Alpha will likely run from the end of July through August (private alpha)
- Public beta will likely run from August through September
- Stable release early/mid September

Regarding the changes required, we do not have the proper logic structure in the v3 to add support for something like that. It's far easier for the user themselves to just add the indexes manually that it would be to pull engineers off of the v4 (increasing the time to release) to work on a code-base that will be entirely and functionally rewritten (that process is already going on right now).

As an analogy for that, it would be like adding a new bathroom to a house that is about to be torn down and rebuilt in 3 months.

---

As a side point I have had trouble replicating your results, in the various test cases I have ran on this (~25 different projects / model structures / each with ~50,000 simulated records).

The only case where I saw a major decrease in performance are areas we have already identified (such as manyToMany relations). But in most cases, adding an index results in less than ~0.01% improvements.

**Comment by Drarok** [comment]
In your analogy, would the family living there have to put up with water pouring non-stop from the ceilings for around 3 months?

---

I've tinkered around and produced a relatively small test case. I can't tell for sure what it is that's taking ages, but you can see it gets slower and slower as each locale is added to an entity:
```
[2021-07-14T15:55:07.364Z] debug POST /example-collections (104 ms) 200
[2021-07-14T15:55:07.524Z] debug POST /example-collections/22/localizations (158 ms) 200
[2021-07-14T15:55:07.775Z] debug POST /example-collections/22/localizations (249 ms) 200
[2021-07-14T15:55:08.115Z] debug POST /example-collections/22/localizations (338 ms) 200
[2021-07-14T15:55:08.574Z] debug POST /example-collections/22/localizations (456 ms) 200
[2021-07-14T15:55:09.171Z] debug POST /example-collections/22/localizations (595 ms) 200
[2021-07-14T15:55:09.915Z] debug POST /example-collections/22/localizations (742 ms) 200
[2021-07-14T15:55:11.926Z] debug POST /example-collections/22/localizations (2009 ms) 200
[2021-07-14T15:55:14.106Z] debug POST /example-collections/22/localizations (2178 ms) 200
[2021-07-14T15:55:15.576Z] debug POST /example-collections/22/localizations (1467 ms) 200
```

In order to get the above, I used [this script][script], with these [content types][content types].

If you want to run the script, you'll need to create 10 locales: `['en', 'nl', 'fr', 'de', 'it', 'pt', 'es', 'bg', 'hu', 'ar']` and grant the public user full access to the example content-type.

The example content-type with a single component and also a repeating component. I don't know how much those contribute to the performance drain right now, but as they're present on the production model I included them in this test.

For reference, this test was performed as close to bare metal as possible, no containers or anything:
* mysqld  Ver 10.6.3-MariaDB for osx10.16 on arm64 (Homebrew)
* Node v14.17.0
* M1 MacBook Pro, 16GB RAM, macOS 11.4

[script]: https://gist.github.com/Drarok/31cb69072e06e9107f60d34b74ce6569
[content types]: https://gist.github.com/Drarok/c3f1856f1bc683f7189e01b38040a161

**Comment by derrickmehaffy** [comment]
The largest contributor (besides i18n) is the nested components and it's due to how we populate the response payload. Indexes largely don't help here (as I was just testing them in an isolated DigitalOcean droplet 4 core/8gb ram using a PM2 cluster of 4 nodes).

This is the part that we are completely refactoring in the v4, adding an index is a bandaid to the problem and isn't fixing anything, the issue comes from our simplistic population code. In the v4 we are doing away with default nested population by default (not sure if that will also include components or not yet) but the entire rewrite of query layer is changing to be more efficient in how we construct the queries (instead of just doing a `select * from xyz` and using javascript to trim out the stuff we don't want to send; which is exactly what we are doing) we will actually select the fields needed and do proper relational joins for nested data.

You can see an example of the new population structure in this part of the query RFC:  https://github.com/strapi/rfcs/blob/v4/query-engine/rfcs/xxx-v4-query-engine.md#populating

Specifically:

```js
db.query("article").findMany({
  populate: {
    tags: {
      select: ["id", "name"], // <---- Here, we are selecting specific fields from a related collectionType not all of them.
      where: {
        name: {
          $not: {
            $startsWith: "internal::",
          },
        },
      },
      orderBy: { name: "DESC" },
      populate: {
        tagCategory: true, // <---- Here we are just selecting all normal fields and no relational fields
      },
    },
    // NOTE: We can't do the same on dynamic zones as their polymorphic nature prevents it for now.
    // We will explore some concepts like graphQL fragments to allow this later on
    dynamiczoneA: true,
  },
});
```

**Comment by derrickmehaffy** [comment]
> In your analogy, would the family living there have to put up with water pouring non-stop from the ceilings for around 3 months?

I'm sorry to say but yes, we never intended to even build i18n on the v3. It was slated to be built in the v4, but we were able to cut enough features to "make it work" and built it in the v3 fully with the intention of spending basically the rest of the year working on v4 to increase performance.

There are many other issues we are looking to solve and many other users who have been impacted for years. This isn't even all the issues, just the ones that I've tagged thus far that are slated to be "fixed" in the v4: https://github.com/strapi/strapi/milestone/117

Specifically one which has existed for many years (heck before I worked for Strapi but was a member of the community)
#1114 

Or the performance issues on GraphQL: #8552 

We understand the performance in the v3 is not great and we are doing our best to get v4 out the door as quickly as possible. The lead backend engineer has been working non-stop for weeks entirely rebuilding the query layer from the ground up on his own. We are a very small team with hundreds of thousands of users, the solution is not to just drop everything to try and make small patches that in the long run won't help if we have to keep coming back to make the larger changes (and in many cases basically just deleting the small patch).

So yes, it will take 3 months to get a fix out the door, but in the medium to long term future this is the best course of action because we are helping everyone at the same time while also building a much more performant version of Strapi that we can start really working on some of the highly requested features.

**Comment by wintercounter** [comment]
@Drarok
I started with Strapi as well for a project that now has millions of records. Even after a few thousand, I faced performance issues. I fixed all my problems with an Elasticsearch layer. Strapi for me is simply feeding and syncing ES Indexes, and I also managed to use it through Strapi's Graphql layer. It opened up a lot of new possibilities, queries that are unimaginable with Strapi, and my response times (even with complex queries) are basically O(0).

An example query:
```
query GET_POSTS($limit: Int = 1, $where: JSON, $start: Int = 0) {
        posts(
            limit: $limit,
            where: $where,
            start: $start
        ) {
            id,
            Title
            Slug,
            MediaItems {
                Purpose
                URL
                File {
                    id
                    formats
                    width
                    height
                }
            },
            Author
            SourceURL
            Description
            Body
            PublishedAt
            Keywords {
                Slug
            }
            Categories {
                Slug
            }
        }
    }
```

The `where` variable is simply an ES query and I send it to the server JSON stringified, where I parse, feed it to an ES search request, and pass the returned data to Strapi to serialize.

I know this is not a solution, but might be helpful and a workaround for you as well.

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
