### ISSUE TITLE
Decoupling between Admin UI and GraphQL for consistent performance

### ISSUE THREAD

**Issue by gustavpursche** [strapi/strapi#10575]
## Feature request

We recently had a huge traffic spike, which led extremely long response times of the GraphQL API (around 20 seconds / request). This was fine, because the frontend is built with next.js and ISR in mind. However: the admin interface became unusable, because it's requests got queued along with the frontend requests and very often timed out after minutes. The database was very relaxed all the time. I believe the queue got longer and longer, because requests came in faster, than they could be answered by the GraphQL API. At this time the strapi process blocked 4 cores and 8GB of RAM in total.

What we did in order to solve the situation: spin up two processes. One which delivers the GraphQL API and is queried by the frontend. Another one which basically delivered the admin interface. Both talked to the same database. This helped to make the Admin UI responsive again, because the requests didn't get queued.

### Summary

Strapi should make sure, that the Admin UI stays responsive as much as it can.

### Why is it needed?

To be able to edit content on a site, even though the API is busy.

### Suggested solution(s)

Strapi could run the admin UI and the api endpoint on different processes by default. An alternative solution could be, to keep this out of strapi core but allowing to easily disable the Admin UI (because both processes theoretically could render the Admin UI), so that a separate API only process doesn't render it at all.

**Comment by derrickmehaffy** [comment]
@gustavpursche all requests to the Strapi backend (REST/GraphQL/Admin) are all exactly equal. There is no way within Koa to take a prescience for one type or request or another.

The action you took is exactly what we recommend for -any- high load case; either you scale vertically (PM2 Clusters), horizontally (Load balancing proxies such as Nginx, HAProxy, ELB, ect), or both combined.

That being said the v4 will largely increase performance due to the fundamental changes we are making in the query layer
