### ISSUE TITLE
Admin / Users Roles reset for no reason (enterprise licence)

### ISSUE THREAD

**Issue by gramsco** [strapi/strapi#10573]
### Describe the bug

Yesterday our front end app could not build because user roles were not working anymore (even though no one touched anything). On a collection, the find method was not public anymore and NextJS obviously failed.

This morning, our ADMIN roles were not behaving normally as half of the collections did not appear anymore in the menu. The only way for to changes things was to go in the local version of strapi and it somehow, for mysterious reasons, made it work again on the deployed version.

This is really frustrating as it's a paid version ; this and the fact that mongoDB support was dropped really makes me consider using another CMS for our company. Strapi is not expansive, but it can not be that inconsistent for production usage.

### Steps to reproduce the behavior

This is going to be deceiving but:

1. Create a prod DB (mongo atlas)
2. Create a dev DB (mongo atlas)
3. Create a strapi app (mongodb)
3. Pay a license
4. deploy a prod version on heroku
5. deploy a dev version on heroku
4. have your roles behave strangely 

### Expected behavior

Users and Admin roles should not change randomly

### Screenshots

This is a super admin view...

<img width="902" alt="collections greyed out" src="https://user-images.githubusercontent.com/45275394/124244123-e4db2100-db1e-11eb-96d3-5866a4117be7.png">

### System

- Node.js version: LTS 14.15.3
- Strapi version: 3.6.1
- Database: MongoDB (Atlas)
- Operating system: Linux (heroku)

**Comment by derrickmehaffy** [comment]
Hi @gramsco 

Can you please confirm which of your environments is having this issue? Specifically if this is your development environment, it is not possible to use the content-type builder due to Heroku's ephemeral file system. Since we save the model settings file to the file system these would be reset every time the dyno goes to sleep or is restarted due to a code push.

I am however curious to know if you have SQLite setup for local development as we do generally see errors sometimes when the Heroku deployment isn't configured properly and accidentally uses SQLite instead of MongoDB when deploying. Since SQLite is stored on the file system it would suffer the same fate as the model settings during a dyno sleep or restart.

For more information on the limitations of Strapi on PaaS services we have an entry in our FAQ here: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-paas

Since you are an enterprise user, I'm happy to talk more specifics with your code/deployment in a support ticket: https://support.strapi.io

**Comment by gramsco** [comment]
Prod environment (deployed, so yes there's no content type builder I've been using strapi for a year now... :))

but
 
dev DATABASE

and 

prod DATABASE

have the same issue once deployed, which is: roles behaving randomly.

Locally (what you call dev environment), strapi works fine.


There is no sqlite file. I checked !

Thanks for your quick answer I will submit a ticket a bit later.

**Comment by derrickmehaffy** [comment]
Yeah once you get that ticket placed, I'd like to schedule a call so we can confirm a few things. Will keep an eye out for the EE ticket.

Thank you :)

**Comment by derrickmehaffy** [comment]
hi @gramsco as we haven't heard from on the support ticket I'm going to close this and the enterprise ticket. If you are still having the issue please let us know through the support portal and we can address it.

Thanks!
