### ISSUE TITLE
 The autoReload feature is required to use this plugin. Start your server with `strapi develop`

### ISSUE THREAD

**Issue by alissonar7** [strapi/strapi#10590]
Helo!

I am new with Strapi and created an application directly in Heroku. But this error is appearing and I don't know how to solve it.

_**The autoReload feature is required to use this plugin. Start your server with strapi develop**_

Could someone help me please?

Thanks

**Comment by gustavpursche** [comment]
@alissonar7 When you deploy strapi to a production instance, the autoReload feature will be disabled, because you shouldn't be able to make any changes, which are reflected in files. You need to setup your content types while running `strapi develop` and commit the generated code along with the rest. In production you can't change these things - you basically execute what you have defined in develop.

**Comment by kasonde** [comment]
Hi {{user}} thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas. Once you post it there, you can reference the issue number in your post and both myself and @gustavpursche will be notified and continue the conversation from there.
