### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by ferrettinico** [strapi/strapi#10660]
### System
After a clean installation using "create-strapi-app" everything installs smoothly, but when running "strapi develop" the following output occurs:

> 
> Something went wrong installing the "sharp" module
> 
> libImath-3_0.so.28: cannot open shared object file: No such file or directory
> 
> Remove the "node_modules/sharp" directory then run
> "npm install --ignore-scripts=false --verbose sharp" and look for errors
> Consult the installation documentation at https://sharp.pixelplumbing.com/install
> Search for this error at https://github.com/lovell/sharp/issues

### System

- Node.js version: 12.22.1
- NPM version: 6.14.12 
- Strapi version: 3.6.5
- Database: default 
- Operating system: Manjaro Linux 64 bits

### Additional notes
If I remove "strapi-plugin-upload" from package.json then everything works fine, except of course that I cannot create collections with File Upload fields

**Comment by gustave-ploix** [comment]
Hi ! It's the first time I contribute, i'll be glad to take a look !
(it may take some time, but I'll do my best, if someone wants to take the issue, there's no problem !).
And of course, tell me if it's not like this

**Comment by ferrettinico** [comment]
Thank you Gustave! let me know if you need any more info about it

**Comment by kasonde** [comment]
Hi @ferrettinico thanks for this. I'll close this issue though as it seems to be an issue with the sharp module and not Strapi itself. Please post this question on either our [Discord](https://discord.gg/5YDC6wt9Rt) or [Community Forum](https://forum.strapi.io) and reference this issue so that anyone who does come to this issue is able to continue the conversation over there.
