### ISSUE TITLE
strapi-plugin-graphql and strapi-provider-upload-cloudinary not working together

### ISSUE THREAD

**Issue by ghost** [strapi/strapi#10803]
### Describe the bug

When installing both plugins (strapi-plugin-graphql and strapi-provider-upload-cloudinary) you will get an error as `strapi-provider-upload-cloudinary`  requires to have `graphql` installed as well.

### Steps to reproduce the behavior

1. Install `strapi`
2. Add `strapi-plugin-graphql`
3. Add `strapi-provider-upload-cloudinary`
4. At last we add `graphql`

### Expected behavior

The expected behavior is to have both plugins work alongside.
I can uninstall `strapi-plugin-graphql` but then the endpoint http://localhost:1337/graphql won't work

### Code snippets

Error you will get:
```
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

Upon reading another topic I tried `npm list graphql` which gave me this error
```
+-- graphql@15.5.1 
`-- strapi-plugin-graphql@3.6.8
  `-- UNMET PEER DEPENDENCY graphql@15.5.0
```
But even after correction the version it still gave the same error
```
+-- graphql@15.5.0
`-- strapi-plugin-graphql@3.6.8
  `-- UNMET PEER DEPENDENCY graphql@15.5.0
```
And `npm run develop` gave this error:
```
[2021-08-26T04:13:04.748Z] debug ⛔️ Server wasn't able to start properly.
[2021-08-26T04:13:04.749Z] error Error: Cannot use GraphQLInputObjectType "FileInfoInput" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

### System

- Node.js version: v14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.8
- graphql version: 15.5.1
- strapi-plugin-graphql version: 3.6.8
- strapi-provider-upload-cloudinary version: 3.6.8
- Database: MongoDB
- Operating system: Windows 10

### Additional context

The problem that remains is that I can make it work with uninstalling `strapi-plugin-graphql` but then the GraphQL IDE http://localhost:1337/graphql does not work.

**Comment by t1tdev** [comment]
Oh man I'm dealing with this same exact issue now - Doing the uninstall of the two plugins now ....(nope) it didn't work for me. 

Node.js version: v12.22.12
NPM version: 6.14.16
Strapi version: 3.6.9
graphql version: 15.5.0
strapi-plugin-graphql version: 3.6.9
strapi-provider-upload-cloudinary version: 3.6.9
Database: Postgres
Operating system: MacOS (latest)

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports for v3 unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You
