### ISSUE TITLE
Multiple-Nested Components

### ISSUE THREAD

**Issue by Njoodd** [strapi/strapi#10824]
### Adding more levels for nesting components

- [✔️] **I have created my request on the Product Board before I submitted this issue**
- [✔️ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Adding customized components is a great feature as it allows flexibility, however, since it lacks the ability to nest higher than 2 levels, the result is a major drawback to the whole idea of flexible component structure. 

### Why is it needed?

To reach the ideal level of flexibility, components should achieve a high-level of nestedness, at least 4-6 levels.

### Suggested solution

Removing the limit applied on nesting components further than 2 levels.

**Comment by tfdbloom** [comment]
This is what doesn't make Strapi qualified to be in the run for a solid and flexible CMS in projects at work. Not trying to trash the team or anybody using it, but just as Njoodd expressing the lack of it. It's just a shame because this issue has been brought up numerous times and been shot down. I decided just last week to use Strapi for my upcoming project but already changed my mind because I just can't visualise how to build a non flexible solution with very little if any reusability with the components.

**Comment by davidparys** [comment]
Props to this, I've been using it a while and the reusability just went downhill went I have found out it's not possible to nest components. Though it seems I have found a hacky way to do it by actually adding the component in the model files rather than through the UI and it seems to work so far.

**Comment by AtticusCMBM** [comment]
@tfdbloom any suggestions on an alternate cms that has the authentication and users features like Strapi does?

**Comment by tilman** [comment]
I have described a possible solution in: https://github.com/strapi/strapi/issues/12126#issuecomment-1006805837

**Comment by derrickmehaffy** [comment]
closing this in favor of https://github.com/strapi/strapi/issues/11319
