### ISSUE TITLE
Knex connection pool error

### ISSUE THREAD

**Issue by caarloshenrique** [strapi/strapi#10886]
## Bug report

When I open EC2 Public IPv4 URL, it doesn’t work.

## Description

I’m using AWS RDS service and I have selected postgres as my database for this tutorial:
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html

### Steps to reproduce the behavior

1. Create EC2 instance Ubuntu t2.small
2. Create S3 bucket
3. Create AWS RDS PostgresSQL 12.x-R1 free tier and set Public Access to Yes
4. Logged into my EC2 instance and clone Github repo and npm install
5. Run NODE_ENV=production npm run build inside Strapi repo
6. Installed pm2 globally
7. Next, pm2 init
8. Edit ecosystem.config.js file with below contents:
```
apps: [
    {
      name: 'strapi-aws',
      cwd: '/home/ubuntu/strapi-aws',
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        DATABASE_HOST:'<my-database-host>',
        DATABASE_PORT:'5432',
        DATABASE_NAME:'<my-database-name>',
        DATABASE_USERNAME:'postgres',
        DATABASE_PASSWORD:'postgres321',
        AWS_ACCESS_KEY_ID:'<my-access-key-id>',
        AWS_ACCESS_SECRET:'<my-access-secret-key-id> ',
        AWS_REGION:'<region>',
        AWS_BUCKET_NAME:'<my-access-secret-key-id> ',
      },
    },
  ],
};
```
9. Run this command pm2 start ecosystem.config.js

### Error

Error visualized with pm2 logs:
```
[2021-09-05T19:27:20.881Z] debug ⛔️ Server wasn't able to start properly.
[2021-09-05T19:27:20.883Z] error KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_PG.acquireConnection (/home/ubuntu/minhaproducao-api/node_modules/knex/lib/client.js:348:26)
```

### System

- Node.js version: 12.22.6
- NPM version: 6.14.15
- Strapi version: 3.6.5
- Database: PostgreSQL
- Operating system: Ubuntu Server 18.04 LTS (HVM)
- Pg version: 8.5.1
- Knex version: 0.21.18

**Comment by kasonde** [comment]
Hi @caarloshenrique , using #9546 and #10479 as references as to how similar issues have been handled please make sure your environment is configured correctly to support knex as this is a knex issue and not a Strapi one. This also isn't specific to AWS, it can happen in any environment that isn't configured correctly to work with Knex.

**Comment by paulovieira** [comment]
This might related to the combination of the versions of `node.js` and `pg`.  I had this exact error (in a different application, not strapi) after updating `node.js`from v12 to v14. It was solved by simply updating `pg` (from v7 to the latest version).

Your case seems to be a little different as you are already using a recent version of `pg`. I'd suggest you try `pg@7` or `pg@latest` (which is currently 8.7.1).

There's several stack overflow questions about this:

- https://stackoverflow.com/questions/40435315/knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing
- https://github.com/knex/knex/issues/3831
-

**Comment by derrickmehaffy** [comment]
No new information, closing for now unless the author wants to provide more information.

**Comment by moadw** [comment]
The problem is not Knex plugin itself but the VPC security group not allowing external connections.[ check this](https://stackoverflow.com/questions/52324170/aws-rds-for-postgresql-cannot-be-connected-after-several-hours) for more info, as soon as the VPC allows connection the Knex error disappeared.

**Comment by Coddielam** [comment]
Knex Timeout is thrown when it failed to connect to a database. Turns out this is an issue related to the RDS's security settings. This stackoverflow hinted at the issue. https://stackoverflow.com/questions/52324170/aws-rds-for-postgresql-cannot-be-connected-after-several-hours

I was able to fix it by configuring the right security group to my RDS instance. By default, the 'default' security group is attached to your database instance. 

In the guide, in 'Launch an EC2 virtual machine', no.3, step 6 'Configure Security Group', you will create a security group. However, the guide did not tell to add this security group to your DBS instance.

To add this security group to your instance, go to RDS, select your RDS instance, click 'Modify'. Then go under the 'Connectivity' section. Remove the 'default' security group. And add the security group you created when you create your EC2 instance. 

You should now be able to start your strapi app in the EC2 server.
