### ISSUE TITLE
Interpreting /admin as /dmin

### ISSUE THREAD

**Issue by DalerAkhmetov** [strapi/strapi#10936]
### Describe the bug

Let's imagine there are two urls.
API: https://somedomain.com/api
Admin: https://somedomain.com/admin
Strapi will listen to admin routes on /dmin but not /admin as expected.

### Steps to reproduce the behavior

1. Just create config/server.js with the following content:
```
module.exports = ({ env }) => {
  return {
    host: env('BACKEND_APP_HOST', '0.0.0.0'),
    port: env.int('BACKEND_APP_PORT', 1338),

    url: 'http://somedomain.com/api/',

    admin: {
      url: 'http://somedomain.com/admin',
      auth: {
        secret: env('ADMIN_JWT_SECRET', '00c78ec04b3088eda8419c5bdc02e84a'),
      },
    }
  }
};
```

### Expected behavior

Admin should be opened by url http://somedomain.com/admin

### Actual behaviour

Admin is opened by url http://somedomain.com/dmin but urls in admin panel have path /admin

### System

- Node.js version: 12.20
- NPM version:
- Strapi version: 3.6.6
- Database:
- Operating system:

### Additional context

I know we can solve this problem using nginx and now I have solved the problem using nginx. But I spent 2-3 hours to find out why I can't open admin panel by /admin. I think it would be good to mention it in documentation in some warning block.

**Comment by derrickmehaffy** [comment]
> url: 'http://somedomain.com/api/',

This for sure should not have the trailing slash

> I know we can solve this problem using nginx and now I have solved the problem using nginx. But I spent 2-3 hours to find out why I can't open admin panel by /admin. I think it would be good to mention it in documentation in some warning block.

Yes a proxy layer is required to do this type URL structure

Regarding the docs on this page: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#available-options

We do state the following: 

> Public url of the server. Required for many different features (ex: reset password, third login providers etc.). Also enables proxy support such as Apache or Nginx, example: https://mywebsite.com/api.

And we do have guides for a few proxy applications:

- [Caddy](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/caddy-proxy.html)
- [HAProxy](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/haproxy-proxy.html)
- [Nginx](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/nginx-proxy.html)

All of these guides have a config example for splitting /admin and /api.

In the v4 all content APIs (end-user endpoints) will have a built in /api prefix that will be customizable.

**Comment by aquadesk** [comment]
+1 for staging that PROXY is **absolutely required** for this rewrite.

I believe it gives people an impression that they can put the entire strapi under a certain route `/backend` with or without a proxy which is false since the statement starts with `Also enables `

**Comment by luixal** [comment]
Just got involved into this with a deployment I've been doing.

I make a different reading from @aquadesk comment: _"I believe it gives people an impression that they can put the entire strapi under a certain route"_. This is totally true. Also, if everyone interprets this that way... maybe that should be the way it works. I mean... I also waster 2-3 hours like @DalerAkhmetov.

In my case, it drove me crazy because I had to set `server.url` to `https://my.domain.com/api` and in Caddy's config had to make an `uri stripe_prefix /api`. That works perfectly but seems weird because you are understanding that Stripe is actually expecting the `/api` in its url while the `server.url` seems to be used only as the endpoint the admin frontend is using to call Strapi's API.

I think this trouble comes due to the existance of `server.admin.url`. If both fields are called the same way... they should do the same. To my understanding `server.url` is only used to tell the admin front end where to find the API, while the `server.admin.url` does change the route where something is published.

About @derrickmehaffy info _"In the v4 all content APIs (end-user endpoints) will have a built in /api prefix that will be customizable."_, if this is a separate option, I mean, keeping the `server.url` and adding something like ' server.apiPrefix` people will go crazy. I think it's better to unifiy both fields, altough you would loose an easy way to deploy the API in one url and the admin frontend in a different one.

**Comment by derrickmehaffy** [comment]
> altough you would loose an easy way to deploy the API in one url and the admin frontend in a different one.

This is exactly why we won't do this as it's a very common deployment use-case

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
