### ISSUE TITLE
Cannot generating API doc with proper schema

### ISSUE THREAD

**Issue by himphen** [strapi/strapi#11071]
### Describe the bug

According to the doc of Lodash, `_.lowerCase([string=''])` make string to space-separated words. And hence cannot use proper schema while generating API doc.

https://lodash.com/docs/#lowerCase

### Steps to reproduce the behavior

1. Create a collection with the name `case-study-category`
2. Added the following code into `services/Documentation.js` Line 1160

https://github.com/strapi/strapi/blob/d91569c3b6061e51116db367fc25fc6a2881ee04/packages/strapi-plugin-documentation/services/Documentation.js#L1160

```
// Normal way there's no tag object
if (tag === 'case-study-category') {
  console.log(tag)
  console.log(controller)
  console.log(_.lowerCase(controller))
  console.log(strapi.models[tag] !== undefined)
  console.log(tag === _.lowerCase(controller))
}
isModelRelated = strapi.models[tag] !== undefined && tag === _.lowerCase(controller);
```

3. Run `yarn develop` to generate api doc
4. `tag === _.lowerCase(controller)` prints false and hence `isModelRelated` always false

```
case-study-category
case-study-category
case study category
true
false
```
5. Default fallback case will be used for `case-study-categories` API 200 response
```
"properties": {
  "foo": {
    "type": "string"
  }
}
```

### Expected behavior

Consider to user `_.toLower(controller)`

https://lodash.com/docs/#toLower

### System

- Node.js version: 12
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Database: mysql
- Operating system: Centos

**Comment by jackrr** [comment]
I was able to reproduce by creating a new collection type with at least one space character in the name.

1. Install documentation plugin
1. Run strapi in develop mode
1. Create a new collection type with whitespace in the name (e.g. "Marketing Page")
1. Add a simple text field to the collection type (name doesn't matter)
1. Save the collection type
1. Open the swagger docs

*Expected behavior*: Swagger docs for response type of GET /marketing-pages should be an array containing an object with the text field and default strapi fields (like published_at, id, etc):
```json
[
  {
    "id": "string",
    "test": "string",
    "published_at": "2021-12-02T13:38:03.044Z"
  }
]
```

*Actual behavior*: Swagger docs for response type of GET /marketing-pages shows a default single-object shape:
```json
{
  "foo": "string"
}
```

**Comment by derrickmehaffy** [comment]
should be fixed in v4
