### ISSUE TITLE
Support node version 16.x

### ISSUE THREAD

**Issue by PritamSangani** [strapi/strapi#11135]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

You should be able to build a Strapi application with node v16.x

### Why is it needed?

Node v16.x is going to become the new LTS release later this month.

### Suggested solution(s)

Update node version range in package.json to allow installing dependencies using node v16.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Planned for v4 release, we will not back port Node v16 support to Strapi v3

**Comment by aksdevac** [comment]
@derrickmehaffy v4 is not out yet, & not sure about how long it will stay in alpha/beta (after Node 16 is LTS), 
also it won't support Mongo when out, also I don't think v16 support for v3 will take much effort, 
so is there any strong reason for not adding Node 16 support in strapi v3 ?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy v4 is not out yet, & not sure about how long it will stay in alpha/beta (after Node 16 is LTS), also it won't support Mongo when out, also I don't think v16 support for v3 will take much effort, so is there any strong reason for not adding Node 16 support in strapi v3 ?

Because v16 isn't LTS yet and the v4 stable is due towards the end of Oct/start of Nov.

The core engineering team is more or less not even looking at v3 code due to the large scope of v4. Every engineer we pull off of v4 means things aren't being done on v4 and there really isn't anything in node 16 that would provide much benefit to v3 (other than maybe some Apple M1 silicon stuff but there are known good workarounds for this)

**Comment by aksdevac** [comment]
@derrickmehaffy ok but mostly v16 will be LTS before v4 stable is released anyways main reason for asking was mongo users cannot upgrade to v4 after released so at least consider it after v4 work is done.

**Comment by derrickmehaffy** [comment]
After v4 release there will be no further v3 updates except for high or critical security issues.

Our goal is not to promote future usage or maintenance of v3 since 6 months after release the v3 will be considered EOL. We have never intended to offer Node v16 support on v3 due to the many breaking changes of NPM v7 that simply are not worth the effort to fix in v3 since v4 will already solve them.

**Comment by derrickmehaffy** [comment]
Closing as added in v4 beta.8

**Comment by robertherber** [comment]
When is v4 coming out? And what's the recommended route on Apple Silicon at this time - go for the beta (which I can't figure out how to install - nothing seems published on NPM) or ugly-hacking v3 to work somehow?

**Comment by derrickmehaffy** [comment]
> When is v4 coming out? And what's the recommended route on Apple Silicon at this time - go for the beta (which I can't figure out how to install - nothing seems published on NPM) or quirking v3 into working somehow?

It comes out tomorrow
