### ISSUE TITLE
Debug environment setup crashes at building Admin UI

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1113]
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: MySQL
- **Operating system**: Windows 10

**What is the current behavior?**

I'm following the steps at the contributing guide (https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to install my development environment. After cloning the strapi repository and running "npm run setup:build", The setup installs everything until it starts building the admin part of the setup. At this I get the following error:

`📦  Linking strapi-plugin-content-type-builder...
🏗  Building admin...
'APP_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.1.2 prebuild: 'APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.1.2 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

The ultimate goal is to be able to view breakpoints in my application, so I know which payload to send to the api calls. I want to be able to add new relations to a content-type but don't know what to add in the body of the request, thus I could really use the breakpoint option provided in the dev-environment of strapi.

**Steps to reproduce the problem**

1) git clone git@github.com:strapi/strapi.git
2) cd strapi
3) npm run setup:build

**What is the expected behavior?**

Installation of npm run setup:build shouldn't crash at building the Admin part. 

**Suggested solutions**

I think APP_PATH has probably been deprecated in a newer version of strapi and the npm run setup:build still uses this variable

- [ x ] I'm sure that this issue hasn't already been referenced

**Comment by soupette** [comment]
Hi @piere129 the `setup:build` is broken however the `npm run setup` works fine.

You can fix the first one by making those changes (it's not mandatory since the command `npm run setup --plugins` works when ran in a generated app):

**Path -** `./scripts/setup.js`

```js
const buildPlugins = async () => {
  const build = (pckgName) => {
    return new Promise(resolve => {
      const name = pckgName === 'admin' ? pckgName: `plugin-${pckgName}`;
      asyncWatcher(`🏗  Building ${name}...`, `cd ../strapi-${name} && IS_MONOREPO=true npm run build`, false, resolve);
    });
  };

  return Promise.all(pluginsToBuild.map(plugin => build(plugin)));
};

const setup = async () => {
  if (process.env.npm_config_build) {
    if (process.platform === 'darwin') { // Allow async build for darwin platform
      await buildPlugins();
    } else {
      pluginsToBuild.map(name => {
        const pluginName = name === 'admin' ? name : `plugin-${name}`;
        shell.cd(`../strapi-${pluginName}`);

        return watcher(`🏗  Building ${pluginName}...`, 'IS_MONOREPO=true npm run build');
      });
    }
  }

  // Log installation duration.
  const installationEndDate = new Date();
  const duration = (installationEndDate.getTime() - installationStartDate.getTime()) / 1000;
  shell.echo('✅  Strapi has been succesfully installed.');
  shell.echo(`⏳  The installation took ${Math.floor(duration / 60) > 0 ? `${Math.floor(duration / 60)} minutes and ` : ''}${Math.floor(duration % 60)} seconds.`);
};
```

**Path -**: `./strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`

```js
const isSetup = process.env.IS_MONOREPO;
```

Then you need to change the webpack configurations:

**Path -**: `./strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js`

```js
const isSetup = process.env.IS_MONOREPO;
```
**Path -**: `./strapi-helper-plugin/lib/internals/webpack/webpack.dll.babel.js`

```js
const isSetup = process.env.IS_MONOREPO;
```

**Path -**: `./strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js`

```js
const isSetup = process.env.IS_MONOREPO;
```

**Comment by piere129** [comment]
update: I added the code you mentioned in a brand new cloned strapi project, and ran npm run setup:build from the root directory, but now I get the following error:
`🏗  Building admin...
'IS_MONOREPO' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.12.1.2 setup: `npm run clean:all && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.12.1.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

I have the feeling IS_MONOREPO still needs to be implemented, is this possible?

**Comment by soupette** [comment]
@piere129 I think the bug is related with Windows...

Also, regarding your questions:

> does that mean all routes and api calls get checked by using software like postman?

When customizing the `admin` (other than just changing the logo) you have two servers running:
- One that handles your back-end, the **Strapi** one ` strapi start` which runs on `PORT=1337`
- Another that handles your front-end which runs the admin `npm start` launched from the `my-app/admin` folder.

So, you won't need POSTMAN in this case.

> About the building process

This step is not required when working on the **admin panel** since you're running the front-end server.

**However**, once your modifications completed you'll need to rebuild the `admin` panel. Since the build command doesn't seem to work inside the monorepo (***in your specific case***) you'll need to run `npm run setup --plugins` at the root of your created project (and this one will bypass the variable issue since you're not in the monorepo):
```
$ cd my-app
$ npm run setup --plugins
```

**Comment by piere129** [comment]
Apparantly i closed prematurely. @soupette I'm not entirely sure which steps i should take now. You talk about running `npm run setup --plugins` in the generated myApp, but on the contributing guide, npm run setup gets ran on the cloned 'strapi' repository. is it correct that these are the steps to take:

1) Fork the repository to your own GitHub account.
2) Clone it to your computer git clone git@github.com:strapi/strapi.git.
3) Run npm run setup at the root of the strapi directory.
4) Go to a folder on your computer cd /path/to/my/folder.
5) Create a new project strapi new myDevelopmentProject --dev
6) **cd to myDevelopmentProject**
7) **run `npm run setup --plugins`  **
8) Start your app with strapi start.

**Comment by lauriejim** [comment]
Hey @piere129, can you check with `alpha.12.2` please and tell me if you still have this issue.

**Comment by soupette** [comment]
@piere129 are you trying to rebuild the plugins or develop on strapi?

Because you don't need the 7th step if you just want to start your project in dev mode.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
