### ISSUE TITLE
Rich text field entry title

### ISSUE THREAD

**Issue by oriooctopus** [strapi/strapi#11181]
### Please describe your feature request

I have a collection with a rich text field called “text”. Because it is rich text, I can’t use it as the entry title when I configure the view. 

Is it possible to add a sanitized rich text field as an option for entry title?

### Why is it needed?

Right now I either have to not have an entry title, or have to duplicate the data with a normal text field called “InternalLabel”

### Suggested solution(s)

Let's say there is a rich text field called "text". The dropdown could show: "text (raw)" and just show the raw text rather than the formatted text. I am a senior node developer and would be happy to put up a PR with a little guidance

**Comment by ChristianHeimke** [comment]
it would be awesome to have it as plugin (in the marketplace), or? this would keep strapi(-core) slim and increase the plugin count :)

**Comment by derrickmehaffy** [comment]
We have two sets of text fields, the string field has an option for short or long (which doesn't have the rich-text side to it)

We don't plan to allow rich-text as the title because of it's length. I would suggest using lifecycles to automatically fill a trimmed short-string field and simply disable it's input via the view configuration.

Setting as closed as this isn't really a feature request but more a question on how to do something.
