### ISSUE TITLE
Errors not displayed in admin

### ISSUE THREAD

**Issue by Paratron** [strapi/strapi#11235]
## Bug report
I was just pulling my hair out a bit because I was unable to create a new collection in the admin. Whenever I hit "save", the message "An error occured" popped up - seemingly without reason.

Only by opening the browsers network debugger, I was able to figure out where the problem lies: I tried to name the collection "Species". And the API complained `Content Type name `Species` cannot be pluralized. Suggestion: add Item after the name (e.g News -> NewsItem).` Yeaaaah well that was not obvious.

### Describe the bug

The admin interface should display the message of the error instead of "An error occured".

### Steps to reproduce the behavior

Go to content type builder, create a collection that ends with "s" - hit save.

### Expected behavior

Well, I expected to have the collection created but THEN I would have expected a meaningful error message - even more since the server communicated what the real problem was.### System

- Node.js version: 14.17.6
- NPM version: 7.21.1
- Strapi version: 3.6.8
- Database: SQLite
- Operating system: W10

**Comment by kasonde** [comment]
Hi, @Paratron thanks for the information. I'll go ahead and close this so that the conversation can be carried on at #1198 specifically since your particular concern has been raised by the comment [here](https://github.com/strapi/strapi/issues/1198#issuecomment-898331738). By no means is this ending the conversation or labeling it as a duplicate (it technically isn't) I think it'd be useful to make sure people see the information at the referenced issue as well.
