### ISSUE TITLE
Add support mysql2

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#11329]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Needs support [mysql2](https://www.npmjs.com/package/mysql2).

[mysql](https://www.npmjs.com/package/mysql) does not support `caching_sha2_password`.
[mysql2](https://www.npmjs.com/package/mysql2) supports `caching_sha2_password`.

### Why is it needed?

`knex` supports both, but if you use `mysql2`, the keyword search in the admin panel will not work.
However, the rest of the system seems to be working.
Checked with strapi v3.6.8.

### Suggested solution(s)

```json5
// package.json
"dependencies": {
    "knex": "0.21.18",
    "mysql2": "^2.3.2",
    ...
}
```
```javascript
// config/database.js
module.exports = ({ env }) => {
  return {
    defaultConnection: 'default',
    connections: {
      default: {
        connector: 'bookshelf',
        settings: {
          client: 'mysql2', // If you specify 'mysql', it doesn't work now.
          // ...
        },
        options: {
          useNullAsDefault: true,
        },
      },
    },
  };
};
```

I need this setting to work properly.

### Related issue(s)/PR(s)

- https://github.com/strapi/strapi/issues/7930
- https://github.com/strapi/strapi/issues/2782

**Comment by yuku** [comment]
In addition, the following warnings are displayed:

```
Ignoring invalid configuration option passed to Connection: schema. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid timezone passed to Connection: utc. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
```

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/add-support-for-mysql2-mysql-v8-auth-system
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
