### ISSUE TITLE
[FR] [v4] Strapi AuditLog

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11500]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Id love, if strapi would write relevant admin-panel actions to a log file.

### Why is it needed?

As a Project Owner, TeamLead, Strapi Admin etc, id love to see who did what and when.
Id love to see an edit history for a content item, to potentially discover issues later one, or be able to trace unwanted content changes.

Secondly, this audit log would be neseccary when delivering content for specific industries, such as in car software. Those changes need to be traceable and archived for 10 Years, by German law.

### Suggested solution(s)
Log the following actions to a file

1. who logged in
2. who logged out
3. who edited what and when
4. who published / unpublished what and when

etc.

**Comment by derrickmehaffy** [comment]
If/when implemented it most likely wouldn't be to a log-file as that would break our stateless implementation so it would most likely be a plugin or something built into the core that writes this data to the database.

**Comment by LucaNerlich** [comment]
Even better :)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/security/p/audit-logs
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
