### ISSUE TITLE
[V4] Support `findMany()` without providing empty object.

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11537]
### Summary

Currently, without providing empty `{}` to `findMany()` it errors with a ` "message": "Cannot destructure property 'data' of 'postData.params' as it is undefined.",`. It would be nice to be able to not provide the empty object and simply call `findMany()`

So instead of
```js
strapi.db.query('api::post.post').findMany({})
```

```js
strapi.db.query('api::post.post').findMany()
```

### Why is it needed?

Improves the DX.

### Suggested solution(s)

Perhaps, there's a way to intercept this method and provide a default empty object as the first argument.

**Comment by Convly** [comment]
Hello, thanks for opening this issue.

I've updated the title since this is not related to GraphQL but to the query layer.
This error should be fixed by #11553 and released in the next beta. (tested on `releases/v4` and it works)

Closing for now, feel free to reopen if the issue persists after the release of the beta.13.
