### ISSUE TITLE
Support false value for boolean field default value

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1160]
**What is the expected behavior?**
Now **Boolean** field only accept **True** value for default value. I think it's more better if we can set **false** default value as well. Then we can set below value for a boolean field:
* unset
* true
* false

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @mnlbox, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll be glad to count you as one of our contributors! 
Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
@mnlbox correct me if I'm wrong here but I believe by default the value of a boolean on mysql is always false `0` not sure on mongo.

**Comment by lauriejim** [comment]
@derrickmehaffy We did the job to convert 1/0 to true/false for mysql and it's live on npm

**Comment by derrickmehaffy** [comment]
@lauriejim yeah he is talking about defining defaults, AFAIK there is no option in MySQL to define an unset boolean value its either false or true. And by default its false. 

I'm unsure how mongo handles this, if you don't send a false value will it be unset?

**Comment by soupette** [comment]
This has been fixed., boolean values are automatically set to `false` by default
I'm closing the issue.
