### ISSUE TITLE
[FEATURE] Be able to move relational fields to the left or center

### ISSUE THREAD

**Issue by luispuentesvega** [strapi/strapi#11617]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary
It would be great to be able to move the relational fields to the left or center of the screen to improve the User experience.

![image](https://user-images.githubusercontent.com/5620082/142346151-493b17d9-5cee-416a-a663-f2f451a60fbf.png)

### Why is it needed?
It would be great to improve user experience

### Suggested solution(s)
-

### Related issue(s)/PR(s)

- It was created from the next question in the forum : https://forum.strapi.io/t/move-the-relational-fields-to-the-left-or-center/12046/3

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/move-the-relational-fields-to-the-left-or-center/12046/3

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/move-relations-into-the-main-view
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
