### ISSUE TITLE
[v4] strapi-provider-email-sendgrid needs to increase node engine version

### ISSUE THREAD

**Issue by rowild** [strapi/strapi#11646]
When using node16, "strapi-provider-email-sendgrid" cannot be installed because of its node engine restrictions ">12 <14". 
Since the documentation provides an example using it, its version should be increased.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by rowild** [comment]
@derrickmehaffy Thanks for your feedback.

But to be honest: each and every project has so many guidelines, I am no longer willing to follow each single step when a short description suffices. If I had sticked to the template, most of the points would have been useless.

I prefer thinking over useless, way too many times completely idiotic template craziness. My time is too valuable for such a time consuming BS.
If you don't understand what the headline already describes in all detail, and if you do not want to keep YOUR extension in good shape, the template will most definitely NOT help you either. 

This is clearly an example for stubbornness that I will not support.

**Comment by derrickmehaffy** [comment]
We ask for a simple thing, follow the template so we have all the information needed, it clearly states this in our contribution guide.

As to your issue, it's not valid as that package clearly has the proper engines defined: 

https://github.com/strapi/strapi/blob/releases/v4/packages/providers/email-sendgrid/package.json#L42

**Comment by derrickmehaffy** [comment]
If you are referencing the v3, we don't support node 16 in the v3 and a quick search through either our documentation or closed issues would show this. You used the v3 package name but put [v4] in your issue title and didn't follow our template.

**Comment by rowild** [comment]
So you did understand my issue? Obviously because all information is there in my sentence which corresponds to the template's "A clear and precise description of the bug" ? ? ? ? ? ? ?
(Well... I apologise for removing the header...)
What's the whole fuzz about? Had you answered right away, a lot of time could have been saved. ;-)

Anyway, I tested v4 last week, probably via an update of v3 (since there is no official installation guide for v4 out there yet). However, I installed this ext most likely in v4, because I have no v3 running here with this extension installed. Can't check that now, though, because I already deleted those test installations. Maybe I'll try again next weekend.

Keep open minded.

**Comment by derrickmehaffy** [comment]
My response was an automated template, if someone doesn't follow the template, we don't read it, we close it, and ask for an updated issue with the template.

At the bare minimum at least the system block so I know what version you are using, what OS you are on, and what version of node.

"Treat others like you would like to be treated" is the methodology we follow. If you can't spare 5 minutes of your time to read our contribution guide and quickly fill out our template (of which I do myself every single time I open an issue on any repo) then I don't have 5 minutes to read yours.

I have read every single issue on all of Strapis repos long before I worked for them and it's extremely time consuming going back and forth to get the information required when the template isn't followed. Of which we have both wasted far more time talking about this template then if you had just filled out the system block stating it was an old v4 release => issue invalid since it's been fixed since beta.12

---

If you don't have time to follow the templates, then thank you for your limited and precious time, but please avoid filing issues without said template.

If you prefer to assist us and everyone in the community by following the templates then we are eternally grateful for your help in reporting bugs and I look forward to speaking to you more often.

For now I'll lock this issue as no further discussion is required.

Have a fantastic day and I hope you enjoy Strapi v4!
