### ISSUE TITLE
Move Thumbnail resize option to settings

### ISSUE THREAD

**Issue by dsiscout** [strapi/strapi#11698]
### Please describe your feature request

- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

In the file [services/image-manipulation.js](https://github.com/strapi/strapi/blob/45c515c84eccef9ed72849f3f3176efbd4ca694b/packages/strapi-plugin-upload/services/image-manipulation.js#L19) there is a hardcoded configuration for detecting thumbnail generation. Can you make this configurable? This would not only make it available for changing values but also enable us skipping thumbnail generation all together in case we have other solutions in place for it.

### Why is it needed?

Configuration without needing to fork the repo or change the file in node_modules

### Suggested solution(s)

Move to thumbnail resize options to strapi.plugins.upload.services.upload.getSettings()

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/move-thumbnail-resize-option-to-settings
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
