### ISSUE TITLE
Error with the Array field type

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1169]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

I have an `Author` model with an `aliases` array field:

```json
    ...
    "fullName": {
      "type": "string"
    },
    "aliases": {
      "type": "array"
    },
    ...
```

I make a `POST http://localhost:1337/author` with:

```json
{
  "fullName": "Abdón",
  "aliases": [
    "alias one",
    "alias two"
  ]
}
```

And the result is:

```json
{
  "fullName": "Abdón",
  "aliases": [
    ["alias one"],
    ["alias two"]
  ]
}
```

**Steps to reproduce the problem**

Follow the preview step.

**What is the expected behavior?**

Store the right info:

```json
{
  "fullName": "Abdón",
  "aliases": [
    "alias one",
    "alias two"
  ]
}
```

**Suggested solutions**

I have not investigated.

---

- ✅ I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by masnad-law-firm** [comment]
is this problem solved now, I have the same problem
