### ISSUE TITLE
Allow description on component attribute

### ISSUE THREAD

**Issue by bastienterrier** [strapi/strapi#11719]
_Can you please submit your feature request here: https://portal.productboard.com/strapi_: ✅ 

### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Some component's attribute name are not very understandable. Allow adding an optional description would increase user understanding. This description would be displayed next to the attribute name on the administration panel to help user filling the component.

### Why is it needed?

Sometime attribute names are not user friendly and it's hard for marketing/business team to fill the component attributes without additional help.

### Suggested solution(s)

Adding an optional `description` field on the attribute configuration as below:

```json
{
  "collectionName": "my-name",
  "info": {
    "name": "FAQ_Section_Item",
    "icon": "ad"
  },
  "options": {},
  "attributes": {
    ...
    "bike_category_highlighted": {
      "type": "boolean",
      "default": false,
      "description": "should be displayed on the Bike Universe/Categories pages"
    }
  }
}
```

Then add a tooltip on the UI next to the attribute name with the description if exists.

**Comment by iicdii** [comment]
+1
We can add [descriptions](https://stackoverflow.com/a/39963267) inside the GraphQL schema language too with this.

**Comment by bastienterrier** [comment]
Hello, any news about this feature request?
Thanks for your work!

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/allow-description-on-component-attribute
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
