### ISSUE TITLE
V4 Enumeration Bug with Specific Value(Research)

### ISSUE THREAD

**Issue by NovusOpus** [strapi/strapi#11739]
### Describe the bug:

I was making a Little Example Api (Employee Manager) , With the following fields: 

1. Name (Type: Text) .
2. Photo (Type: Media).
3. Department (Type: Enumeration).
4. Fulltime (Type: Boolean).

The problem is with the `Department` Enumeration field, Currently I have this options:

```
Management
Sales
Marketing
Finances
IT
Research
```
All seems fine from the Content-Type Builder, It saves correctly, display the values correctly, But the problem is when trying to select the Research( as for R&D or Research and Development) option, Returns a warning/Error: Bad Request.

It doesn't matter if it's in `lowercase` : research, `First letter uppercase`: Research, or `FULLUPPERCASE`:RESEARCH. As long as the value is: Research, it keeps showing the warning/error and can't save. 

I cant use `R&D` because "The value does not match the regex" or `RandD` for obvious readability issues. 

### Video of the bug in action:
https://user-images.githubusercontent.com/79575415/144184490-693d3b50-9d80-42d0-8685-686b3cfeaf56.mp4

### System

- Node.js version: LTS v16
- NPM version:  8.1.3
- Strapi version: V4
- Database: SQLite --quickstart
- Operating system: Windows 10

**Comment by kasonde** [comment]
@NovusOpus, please share your server-side logs/stack trace with us. I'm unable to reproduce this on my installation of Strapi. Works fine.

**Comment by iicdii** [comment]
I can't reproduce too. By the way special character is not allowed for enum field. I guess it's because using special character can break the program (types in GraphQL or something like that). So it's recommended to use snake_case or etc.

**Comment by Nirlah** [comment]
I’ve also encountered this issue, what ended up solving it for me is changing the enum’s name itself 🤷‍♂️

**Comment by NovusOpus** [comment]
@kasonde Where/How do I find those logs? 

Following @Nirlah approach I renamed my enumeration field from `department` to `team`, and then I can select **Research** and save without problems. Oddly enough I renamed  the field back to `department` after naming it `team` and now Research can also be selected without a problem.

**Comment by supersnager** [comment]
Hi, I have the same problem. During a short investigation, I have found that the issue occurs when a new position is _added_ to _existed_ enumeration.

Enumeration defines a check on the database level and the error comes from this check.
The problem is that check is not updated when enumeration items are changed from the Content-Type builder.

**Comment by derrickmehaffy** [comment]
I can confirm the issue, it has to do with the fact we aren't updating the schema with the new enum values and it appears in v4 we switched from enum just being a string to it being an actual enum type:

![image](https://user-images.githubusercontent.com/8593673/144502916-a7335579-7d3a-49c9-96f4-74191266c1cb.png)

https://github.com/strapi/strapi/blob/11f3519710b77042fc58b787acd46288930b510e/packages/core/database/lib/schema/schema.js#L135-L143

@alexandrebodin is there any reason we are using the native database enum column type instead of just text or varchar? I made the change in v3 back in like 2018 to switch away from this type because it's not nearly as performant to use native enum column types and strings provide much more flexibility.

**Comment by supersnager** [comment]
@derrickmehaffy @alexandrebodin Keep in mind that it's impossible to simply change CHECK in the SQLite database.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy @alexandrebodin Keep in mind that it's impossible to simply change CHECK in the SQLite database.

Indeed, I find it odd we switched back to using native DB enum functions as it's really really not needed.

Text or Varchar is more than fine since we can validate the enum inside of Strapi and there is no need to do this at the database level.

**Comment by alexandrebodin** [comment]
We can revert to a varchar indeed. We just used the default knex enum that seemed very much logic as we rebuilt the entire db layer we just missed it :) 

If you are willing to make a PR for this that would be great.

**Comment by derrickmehaffy** [comment]
> We can revert to a varchar indeed. We just used the default knex enum that seemed very much logic as we rebuilt the entire db layer we just missed it :)
> 
> If you are willing to make a PR for this that would be great.

Sure I'll take a look tmrw when I wake up and get a PR in

**Comment by naumstory** [comment]
As an instant solution to the problem. Change the name of the enumeration to another one, and then back again.

**Comment by ihmpavel** [comment]
Easy fix for PostgreSQL

If you do not know the name, comment ` and conname = 'TYPE CHECK NAME'`
```
SELECT conname, pg_get_constraintdef(oid)
FROM   pg_constraint c
JOIN   pg_attribute  a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
WHERE c.contype = 'c' and conname = 'TYPE CHECK NAME'
```

We need to drop the constraint first. Update table name and type check name
```
ALTER TABLE "TABLE_NAME" DROP CONSTRAINT "TYPE CHECK NAME";
```

Update the desired constraint and check
```
ALTER TABLE "TABLE_NAME" ADD CONSTRAINT "TYPE CHECK NAME" CHECK CHECK_HERE;
```
