### ISSUE TITLE
UID target field validation

### ISSUE THREAD

**Issue by cyruschoi76** [strapi/strapi#11987]
### Steps to reproduce the behavior

1. Create a content-type, add a UID field , and email field . 
2. In the corresponding schema.json file, set the target field of the UID field to the email field above, e.g. 
```
  "email": {
      "type": "email",
      "required": true,
      "unique": true
    },
  "uuid": {
      "type": "uid",
      "targetField": "email",
      "options": {
        "customReplacements": [
          [
            "@",
            "at"
          ]
        ]
      }
    },
```
3. Change this content type again to make the validation logic run  (e.g. adding a new field or change any existing field )  
4. Screen reporting "Warning Alert: An error occurred. and server api return the following error.    
```json
{"error":{"name":"ValidationError","message":"contentType.attributes.uuid.targetField must be one of the following values: lastname, profile_img_base64, mobile, firstname, jobtitle","details":{"errors":[{"path":["contentType","attributes","uuid","targetField"],"message":"contentType.attributes.uuid.targetField must be one of the following values: lastname, profile_img_base64, mobile, firstname, jobtitle","name":"ValidationError"}]}}}
```

### Expected behavior

Email field should be also the valid field as the target field of UID generation. 

### Code snippets

If applicable, add code samples to help explain your problem.

[const VALID_UID_TARGETS = ['string', 'text'];
](https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/content-type-builder/server/controllers/validation/types.js#L68)

https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/content-type-builder/server/controllers/validation/types.js#L68

The VALID_UID_TARGETS only allow string or text type. Email type should be allowed as well. 

### System

- Node.js version: v14 
- NPM version: 
- Strapi version: 4.01 
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/add-email-field-option-for-uid-target
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
