### ISSUE TITLE
Not able to disable hooks

### ISSUE THREAD

**Issue by sdbondi** [strapi/strapi#120]
Seems impossible to disable hooks.

Seems to me, looking at this code:
https://github.com/wistityhq/strapi/blob/master/lib/private/loadHooks.js#L29

``` javascript
 if (strapi.config.hooks[hookPrototype] === false) {
```

should be:

``` javascript
 if (strapi.config.hooks[id] === false) {
```

**Comment by sdbondi** [comment]
Actually I lie, you would have to do it like this:

```javascript 
strapi.config.hooks[strapi.config.hooks.views] = false;
```

Seems unintentional to me.

**Comment by Aurelsicoko** [comment]
@sdbondi: Should we find a solution into the configuration files (in a project) to disable hooks? We could create a new file called `./config/hooks.json`. This file could be also useful to manage the hook load order. What do you think about that?

**Comment by dj-hedgehog** [comment]
I have to chime in here (and hope to not raise the confusion).
In v2's `config/environments/.../server.json` you can disable all hooks by setting their name to false, e.g. `"session": false".
I think this is quite intuitive.

@Aurelsicoko: Can we introduce labels for Strapi v1 and v3 (leave out v2 because you don't support that officially anyways).

**Comment by Aurelsicoko** [comment]
@dj-hedgehog: Good idea! I added the labels. It will be more readable. Thanks for the suggestion.

Yes, this is already possible to disabled hooks in the `/config/environments/.../server.json` file. However, we might create a specific file for it. As you know, it is possible to load external hooks. Sometimes, a hook needs to be loaded after another one. Currently, we added (in the v3) a key called `nextTo` in the package.json but when I think about that, this is maybe not the right way to do it because this is very dynamic. A dedicated file could be a better option. Thanks to this file, you could disabled or enabled hooks, and also manage the load order. With the arrival of plugins, we should face to the same issue... I would apply the same behavior for plugins and hooks.

**Comment by Aurelsicoko** [comment]
@sdbondi @dj-hedgehog so I pushed on a new branch `configHooks` some work. However, I still not comfortable with it.

The file `hook.json` looks like this:
```json
{
  "hooks": {
    "core": {
      "bodyParser": true,
      "cors": true,
      "cron": true,
      "favicon": true,
      "gzip": true,
      "i18n": true,
      "ip": true,
      "logger": true,
      "lusca": true,
      "proxy": true,
      "responses": true,
      "responseTime": true,
      "router": true,
      "session": true,
      "ssl": true,
      "static": true,
      "views": true
    },
    "websockets": {
      "websockets": true
    },
    "external": {
      "mongoose": true
    }
  }
}
```

I would like to be able to manage the hook order in this file too. Currently, this behavior is possible thanks to the `nextTo` key in the package.json. However, this behavior is limited to external hooks. It means that if I want to load the hook `mongoose` before `router`, it is not possible.

What I had in mind is to simplify this `hook.json` again. Then, load the hooks in the order defined in this file. And keep the parts independent (core, dictionary, models, web sockets) by continuing the load of the others parts if a hook crash.
```json
{
  "hooks": {
    "bodyParser": true,
    "cors": true,
    "cron": true,
    "favicon": true,
    "gzip": true,
    "i18n": true,
    "ip": true,
    "logger": true,
    "lusca": true,
    "proxy": true,
    "responses": true,
    "responseTime": true,
    "mongoose": true,
    "router": true,
    "session": true,
    "ssl": true,
    "static": true,
    "views": true,
    "websockets": true
  }
}
```

The business logic behind that is a little bit more complicated and I suppose it will take more time to check if we need to load the hook or not. Despite this, it will be easier to manage for the user.

**Comment by Aurelsicoko** [comment]
I close this issue because the features have been added in the new version. Thanks again for your suggestions, guys!
