### ISSUE TITLE
Speedup Webpack build times and decrease resource footprint

### ISSUE THREAD

**Issue by dejwsz** [strapi/strapi#12095]
Would it be possible to speed up webpack compiling and in general the whole strapi build process? By using such tools like: https://www.npmjs.com/package/parallel-webpack or any other approach? What do you think? Or there are some tips how to do it?

**Comment by derrickmehaffy** [comment]
*Sigh* I'll keep this issue even though it breaks our rules about issue templates.

@dejwsz in the future, please use the feature request template.

---

I agree our webpack builds are both slow (it was improved a bit in v4, and the build size got much better) and our RAM usage has skyrocked in v4 from ~1GB usage to just under 4GB:

v4 admin build: 
![image](https://user-images.githubusercontent.com/8593673/148128079-f9861039-a4f4-421f-a8c7-7b6dd8f15aa8.png)

v3 admin build:
![image](https://user-images.githubusercontent.com/8593673/148128091-639d2299-28e6-4af1-a0c8-35843b666235.png)

**Comment by derrickmehaffy** [comment]
@strapi/product I've set this as both a bug/enhancement and for both core squads because I have no idea what to call this. Once you figure out who is owner and what it is you can adjust the label and project.

For more context see the convo in our internal slack => Engineering channel as we were just talking about this to @soupette

**Comment by soupette** [comment]
@dejwsz thanks for opening this issue.

The compilation time takes some time when you are building your app for production:

- yarn build generates a build that is about 2.2MB but takes some time to compress the app
- yarn build --no-optimisation is way faster but comes with a drawback : the build is twice bigger.

Regarding optimising it I need to make some research but I am not sure yet having multiple entry points will be the best solution we need to explore some other way before.

I'll let this issue open so we can address both the compilation time and the RAM usage soon.


On a side note, the webpack config is fully customisable in your generated app you can refer to our [documentation](https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#webpack-configuration) so even though we don't setup multiple entry points (or other methods) to speed up the build time and RAM usage you can make some experiments on your side and you will still be able to upgrade your app without issue.
I'd suggest that you wait for the 4.0.3 release that should come soon because we have upgraded all the dependencies that we use in our webpack configuration.

**Comment by soupette** [comment]
I have ran a speed check using this [plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin)

And here are the results:


![build-speed](https://user-images.githubusercontent.com/13311463/148193575-5d6ab502-6377-4bad-8990-71b9eb0c25b7.png)

**Comment by derrickmehaffy** [comment]
@soupette I have no idea how webpack works myself but are there alternatives to terser that might be faster?

**Comment by soupette** [comment]
Yes there are some alternatives like this [one](https://github.com/webpack-contrib/closure-webpack-plugin) but since the webpack config is customisable user can do it in their own app.
