### ISSUE TITLE
Configuration of https/ssl for a Strapi app already Deployed online in a docker container 

### ISSUE THREAD

**Issue by makkahwi** [strapi/strapi#12097]
I have deployed a strapi app inside docker container on linux / ubuntu (by followed strapi doc | create docker-compose n create a container to pull strapi/strapi)
I'm trying to fix the app to be https/ssl configured but couldn't do it

Strapi Documentation is very vague about such a case

**Comment by derrickmehaffy** [comment]
> Strapi Documentation is very vague about such a case

This is intentional as we simply don't support SSL certs set at the node level, you need you use a proxy layer for SSL. We have guides here:

https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html#optional-software-guides

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
