### ISSUE TITLE
Strapi v4 UI issue: Highlighted border in Safari on macOS Monterey

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#12118]
### Describe the bug

Highlights border in Safari on macOS Monterey

### Steps to reproduce the behavior

1. Go to 'Conten Manager'
2. Click on 'User'
3. See a highlighted border in Safari on macOS Monterey.
4. Same issue appears when clicks on any table.

### Expected behavior

Chrome has no this highlighted border.

### Screenshots

Safari:

<img width="984" alt="Screen Shot 2022-01-06 at 9 06 38 AM" src="https://user-images.githubusercontent.com/22420/148312464-9655a822-0ba5-4a80-822f-a97166f4a351.png">
<img width="986" alt="Screen Shot 2022-01-06 at 9 14 54 AM" src="https://user-images.githubusercontent.com/22420/148312486-6d3408b8-8c53-41a6-940d-7e97201cdfdc.png">

Chrome:
<img width="983" alt="Screen Shot 2022-01-06 at 9 07 02 AM" src="https://user-images.githubusercontent.com/22420/148312505-82ab6eab-409a-454b-8d02-10593f770cd1.png">

**Comment by nvh95** [comment]
I put here some findings. That weird ring is caused by:
```css
:-internal-direct-focus {
  outline-color: -webkit-focus-ring-color;
  outline-style: auto;
  outline-width: 5px;
}
```
![image](https://user-images.githubusercontent.com/8603085/158023313-d7ea8059-5499-432b-b250-a535cf5460fb.png)

- Related issue: https://github.com/microsoft/fluentui/issues/21296
- Discussion: https://www.mail-archive.com/webkit-changes@lists.webkit.org/msg173737.html
