### ISSUE TITLE
Rebuilding Strapi with `NODE_ENV=production npm run build` causes data within MySQL to be deleted for Content-Type Builder.

### ISSUE THREAD

**Issue by sanjay-io** [strapi/strapi#12124]
### Describe the bug

If I update the app and rebuild via the commands below my Content-Type Builder models are gone, but my API tokens, users, roles are still there. I've confirmed this by looking at my MySQL database that this happens during the build step.

### Steps to reproduce the behavior

```bash
# Note that I select "custom" after the first command and not quickstart.
npx create-strapi-app@4.0.3 strapi --dbclient "mysql" --dbhost "{{ mysql_host }}" --dbport "3306" --dbname "strapi" --dbusername "{{ mysql_login_user }}" --dbpassword "{{ mysql_login_password }}"
# I've confirmed that line causes my Content-Type Builder models and data to be deleted.
NODE_ENV=production npm run build 
```

1. Create a new strapi instance with the commands above.
2. Add a simple model like "Blog Post" with any fields and save that model.
3. Check MySQL to see that the table was successfully made.
4. Run the commands above (let's pretend we're updating Strapi).
5. Content-Type Builder models and data are deleted. 😱 

### Expected behavior

Content-Type Builder models and data are not deleted.

### Code snippets

Code snippet is above.

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: v4.0.3
- Database: MySQL (8.0.27-0ubuntu0.20.04.1)
- Operating system: Ubuntu 20.04

**Comment by sanjay-io** [comment]
This seems pretty critical since it involves potential data loss upon Strapi update. We have backups, so we can restore after updating but that seems less than ideal.

**Comment by derrickmehaffy** [comment]
Did you create a new project and try to attach it to previously created database?

**Comment by derrickmehaffy** [comment]
If you had say a v4.0.2 project with existing models and an existing database and to "upgrade" you created a new project and attached it to the existing database then what has happened is normal because the new Strapi project is not aware of the old models (they don't exist in it's filesystem).

In Strapi v4 if during the bootup process strapi doesn't see the content-types that are in the database those tables and columns are simply purged in relation to #1114 

If you followed this method to upgrade, this is not the correct method, see: https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#update-strapi-version

**Comment by sanjay-io** [comment]
> Did you create a new project and try to attach it to previously created database?

You are correct, this is what I tried.

> In Strapi v4 if during the bootup process strapi doesn't see the content-types that are in the database those tables and columns are simply purged in relation to #1114

Thanks, that's news to me, appreciate the quick response! Doesn't it seem strange that models are stored in the filesystem unless it was some performance-related cache? Shouldn't Strapi be referring to the database for what the models look like? I'm thinking of a case where my file system has some catastrophic failure like a corrupted disk. Are folks expected to be backing up contents (models) that are generated within the filesystem alongside the repo?

**Comment by derrickmehaffy** [comment]
> > Did you create a new project and try to attach it to previously created database?
> 
> You are correct, this is what I tried.
> 
> > In Strapi v4 if during the bootup process strapi doesn't see the content-types that are in the database those tables and columns are simply purged in relation to #1114
> 
> Thanks, that's news to me, appreciate the quick response! Doesn't it seem strange that models are stored in the filesystem unless it was some performance-related cache? Shouldn't Strapi be referring to the database for what the models look like? I'm thinking of a case where my file system has some catastrophic failure like a corrupted disk. Are folks expected to be backing up contents (models) that are generated within the filesystem alongside the repo?

We are not a "one and done" deployment like other frameworks, we assume and expect users to use source control.

see: https://docs.strapi.io/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

The reason why you can't use the content-type builder in production is for the same reason here. You don't create a new project to upgrade, and you can't generate models off of an existing database.

If you want to turn off the autoMigrations system you can do so, but not during project creation: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#settings-configuration-object

---

Closing as a won't fix because the existing logic is intended logic.

**Comment by sanjay-io** [comment]
That documentation is exactly what I've been looking for, thanks for the model schema JSON migration insight! Cheers,
