### ISSUE TITLE
Custom column name view layout a little buggy on Firefox

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1214]
**Informations**
- **Node.js version**:v10.1.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:Mongo
- **Operating system**:Linux

**What is the current behavior?**
custom column name view layout a little buggy on Firefox

**Steps to reproduce the problem**
![strapi3](https://user-images.githubusercontent.com/25859075/40157135-9ff963f8-59b2-11e8-9b85-744869af198a.png)

**What is the expected behavior?**
We need see all part of UI elements :wink: 

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @mnlbox , thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md
