### ISSUE TITLE
Use strapi as resource server when integrating with oauth2

### ISSUE THREAD

**Issue by 9n** [strapi/strapi#12207]
### Please describe your feature request

When integrating with oauth2, I think it's more common to use strapi as resource server instead of client(strapi is headless).  It's the duty of frontend (like nextjs) to get user authenticated and obtain the access token which used in `Authentication` header when access strapi, what strapi should do is validate access token and get user info from it. This make strapi more easy to integrate with other backend.

Is there any plan or chance to provide this feature?

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/security/p/use-strapi-as-resource-server-when-integrating-with-oauth2
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
