### ISSUE TITLE
[v4] Option to change the date format in the admin dashboard

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12216]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Please, give an option to change the date format in the admin dashboard.
Right now it looks like:

<img width="483" alt="Screenshot 2022-01-17 at 12 11 25" src="https://user-images.githubusercontent.com/1007051/149759568-18fbd8a0-fce1-47ef-9993-ce867cd244ed.png">

We wan to change it to just: `2021/10/27`

### Why is it needed?

Better user read.

### Suggested solution(s)

In the v3 we could change it with the:

```javascript
# extensions/content-manager/admin/src/utils/dateFormats.js

import { dateFormats as defaultDateFormats } from 'strapi-helper-plugin';

const dateFormats = {
  ...defaultDateFormats,
  date: 'YYYY/MM/DD',
  datetime: 'YYYY/MM/DD HH:mm',
  timestamp: 'YYYY/MM/DD HH:mm',
};

export default dateFormats;
```

But it would be much better to have the option from the global settings of the admin dashboard.

**Comment by yanniskadiri** [comment]
Thanks @abdonrd, we will discuss it with the team in the coming weeks too :)

**Comment by HaruMiyaGi** [comment]
Would like this feature too!

Additionally it would be nice to add formating preferences for other fields too.
For example an option to keep the 2 decimals at the end of decimal number inputs which don't need it: `1` to `1.00`.

**Comment by ippoippo** [comment]
+1 for me wanting this feature.
Display of all Datetime and Date info needs to be configurable.
So, not just display.
This also includes the Date picker when creating/editing content.

<img width="313" alt="Screen Shot 2022-02-16 at 9 35 07" src="https://user-images.githubusercontent.com/2457566/154173665-af0e18ef-43e8-4876-8851-d2a2b8078f4f.png">

As an example, that `02/27/2022` date format is not suitable for Japan audiences, which require `2022/02/27` or `2022-02-27`.

**Comment by DeltaSignalAB** [comment]
This feature would also be relevant for us.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/option-to-change-the-date-format-in-the-admin-dashboard
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
