### ISSUE TITLE
Separate permissions for draft content

### ISSUE THREAD

**Issue by mkmarkop** [strapi/strapi#12309]
### Summary

Allow customisation of permissions per draft/published state. 

### Why is it needed?

Strapi is lacking a way to further customise role permissions. Currently public users can access both draft and published articles. This makes securing the unpublished articles for content preview (in Next.js preview mode, for example) hard to do.

### Suggested solution(s)

Separate checkbox(es) for actions on draft content in users-permissions plugin page: find, findOne, etc.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/content-versioning
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
