### ISSUE TITLE
Minor UI bug in content manager with date type

### ISSUE THREAD

**Issue by decimoseptimo** [strapi/strapi#1231]
**Informations**
- **Node.js version**:v8.11.2
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:mongodb 3.4.15
- **Operating system**:ubuntu server 16.04

**What is the current behavior?**
In the content manager table, in a given `publishedAt` column of type `date`.
a `{publishedAt: null}` value will be shown as "invalid date"
a `{}` (not set) value will be shown as "2018-05-18 23:18:28" (current date)

**What is the expected behavior?**
Perhaps showing `-` instead. Like with other types.

The error is not present once you enter to edit mode.

---

- [x ] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @decimoseptimo , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md
