### ISSUE TITLE
Permissions have to be defined all together for a subject field or not at all

### ISSUE THREAD

**Issue by tamerkalieh** [strapi/strapi#12383]
### Describe the bug

I have a role of author. This author role should be able to edit specific collection attributes. When I try to edit the author permissions like: Change nothing and press save, or if I change some settings, or just a single thing, I'm getting the error from the screenshot.

### Steps to reproduce the behavior

1. Go to 'Settings -> Roles -> Select a role'
2. Click on 'Select a Collection Types'
3. Go to any collection, change the settings and press save

### Expected behavior

Settings which role can edit which collection items should be saved

### Screenshots

<img width="423" alt="Bildschirmfoto 2022-02-02 um 14 03 15" src="https://user-images.githubusercontent.com/17314534/152159003-38dc7c97-2b83-4c6f-942e-a46d2290de5d.png">

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- Strapi version: 3.6.5

### Additional context

I've checked this issue but still can't make it work.
https://github.com/strapi/strapi/issues/10135
I also have a lot of collections with a lot of attributes and components, which have different attributes.

**Comment by derrickmehaffy** [comment]
We are currently not fixing v3 bugs unless it's critical or security. The easy fix on this one is to purge the admin permissions and restart Strapi and let it regenerate as there is likely some corrupted permissions. This shouldn't be reproducible in v3.6.8 after the cleanup step is done.

**Comment by nd90364** [comment]
@derrickmehaffy  How would one go about purging the admin permissions?  Is it a CLI command, deleting the permissions table, uninstalling and reinstalling the plugin?

**Comment by derrickmehaffy** [comment]
I'm not sure what you mean?

**Comment by derrickmehaffy** [comment]
Those locales look custom? Is your code somewhere public I could look at?

**Comment by nd90364** [comment]
The locales are en and en-US I just changed the labels.  As for the code unfortunately not the client I am working with would not want it shared currently.

**Comment by derrickmehaffy** [comment]
Honestly I can't really point to the cause or how to fix since I'm unable to replicate it myself. If you are able to replicate the problem in a fresh project and send me that I might be able to find the root cause and see if there is a workaround.

**Comment by nd90364** [comment]
I originally migrated from 3.6.5 to 3.6.8 so that may be the issue, it seems like the problems have happened since that migration.  I  was able to fix my immediate problem by modifying every collection type entry inside of strapi_permission in the properties column to add ,"locales":["en","en-US"]} like the Super Admin role had.  It worked, but it doesnt seem like an overall fix as I still receive the error raised in this ticket when making any changes.

**Comment by Krivobarac** [comment]
Maybe this can helps
[](https://github.com/strapi/strapi/issues/10135)

> As the complete permission config has been changed you need to decide for each permission that is displayed as a dash if you want it to be granted or not. Go through all the tabs and check or uncheck accordingly an you should not get an error anymore.

**Comment by nd90364** [comment]
> Maybe this can helps [[After upgrading from 3.5.3 to 3.6, attempts to admin changes to roles throw Error](https://github.com/strapi/strapi/issues/10135#)](#10135)
> 
> > As the complete permission config has been changed you need to decide for each permission that is displayed as a dash if you want it to be granted or not. Go through all the tabs and check or uncheck accordingly an you should not get an error anymore.

I wish I could, the only way I am able to do that is by modifying the dom on inspect element and removing the disabled toggle on the checkboxes.  If I do that I am able to fix the checking of them, but then I end up with "Permissions have to be defined all together for a subject field or not at all" error again.  I think maybe if I didnt have the community edition this may be different because I think I would be able to modify the individual permissions but I think with CE edition that isnt allowed.

**Comment by gustavwennerblom** [comment]
@nd90364 

I had a similar issue where I was prevented from giving the Editor role CRUD+Publish rights on all Collection Types in all locales. I believe the reason could have been that I had fields in the Single Types that had relations to items under Collection Types.

Once I made sure to have a checked box for all CRUDP permissions for the content types under both the Collection Types and Single Types tabs, I could save without getting the "Permissions have to be defined all together for a subject field or not at all" error message.

Haven't done any root cause investigation yet - just thought this observation might help someone with the same issue.

**Comment by robdmoore** [comment]
@derrickmehaffy I'm getting this same error (go to a role in admin, don't change anything and click save) on version 4.

**Comment by mdmajidali** [comment]
> @nd90364
> 
> I had a similar issue where I was prevented from giving the Editor role CRUD+Publish rights on all Collection Types in all locales. I believe the reason could have been that I had fields in the Single Types that had relations to items under Collection Types.
> 
> Once I made sure to have a checked box for all CRUDP permissions for the content types under both the Collection Types and Single Types tabs, I could save without getting the "Permissions have to be defined all together for a subject field or not at all" error message.
> 
> Haven't done any root cause investigation yet - just thought this observation might help someone with the same issue.

Thank you soooooo much!

**Comment by laurenskling** [comment]
Had this too. I first saved the content type with all field selected, then removed checkboxes one by one and ended up with only the single field I wanted checked. 🤷

**Comment by ciriousjoker** [comment]
In our case, the localization plugin seemed to be the issue.
To fix it, I selected the checkbox to the left:
<img width="682" alt="Bildschirm­foto 2023-02-22 um 14 40 35" src="https://user-images.githubusercontent.com/16866223/220636436-1eeee336-7255-4775-9f88-5aebe1c70eda.png">

so it looked like this:
<img width="662" alt="Bildschirm­foto 2023-02-22 um 14 40 22" src="https://user-images.githubusercontent.com/16866223/220636374-435bb002-5084-4159-9e48-4bbafa470291.png">

I had to do this for all the collection and single types and then click save...
