### ISSUE TITLE
Reuse of Strapi generated types is not working in Nexus Graphql extension service

### ISSUE THREAD

**Issue by tilman** [strapi/strapi#12382]
### Describe the bug

It is not possible to use types defined by Strapi in the nexus Graphql extension service. For example the `JSON` type or any autogenerated type of a Component or Collection.

### Steps to reproduce the behavior

use this in `src/index.js`
```
"use strict";

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register({ strapi }) {
    const extensionService = strapi.plugin('graphql').service('extension');
    extensionService.use(({ nexus }) => ({
      typeDefs: /* GraphQL */`
          type Query {
              test: JSON
          }
      `,
      resolvers: {
        Query: {
          test: {
            async resolve() {
              return {'foo':'baz'}
            },
          },
        }
      },
      resolversConfig: {
        'Query.test': {
          auth: false,
        },
      },
    }));
  },

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap(/*{ strapi }*/) { },
};
```

### Expected behavior

Strapi types will become usable in the extension service. I guess it is just the wrong order right now (so strapi extension service get's called before the plugin generates the internal types).

### System

- Node.js version: v14.18.2
- NPM version: yarn 1.22.17
- Strapi version: 4.0.6
- Database: sqlite
- Operating system: mac os

**Comment by Convly** [comment]
Hey, thanks for bringing up this issue, I'll take a look at this and try to reproduce it asap

**Comment by Convly** [comment]
Hello, just wanted to give you a quick update on this.

I didn't notice at first but you're using the `typeDefs` (raw sdl) property to build your types which don't give you access to the types defined elsewhere (nexus + shadow crud). It's thus the intended behavior (due to some initial limitations on how we're actually building & merging all the types).

However, I've played a bit with schemas generation and I believe we might be able to adapt the code to expose the nexus + shadow crud context to the SDL declarations.

I'll put that as a low priority feature request/enhancement since it's the intended behavior + you can still declare your query using the `types` property (see an example below), and I'll work on a PoC quickly. I'll update you as soon as I've made some progress on this.

```javascript
'use strict';

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register({ strapi }) {
    const extensionService = strapi.plugin('graphql').service('extension');
    extensionService.use(({ nexus }) => ({
      types: [
        nexus.extendType({
          type: 'Query',

          definition(t) {
            t.field('test', { type: 'JSON', resolve: () => ({ foo: 'baz' }) });
          },
        }),
      ],
      resolversConfig: {
        'Query.test': {
          auth: false,
        },
      },
    }));
  },

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap(/*{ strapi }*/) {},
};

```

**Comment by Convly** [comment]
Hey @tilman, I've proposed an enhancement that should fix the issue you're facing while adding SDL type definitions to the GraphQL API.

If you have the time, please let me know If it fixes your issue.
