### ISSUE TITLE
'Populate' doesn't work with users. [Strapi v4]

### ISSUE THREAD

**Issue by JakubLog** [strapi/strapi#12415]
### Describe the bug

In user object I have multi component like this:
![image](https://user-images.githubusercontent.com/77537823/152652331-7a53d1c0-9c0c-4b4a-b3ef-4d38a805b6f5.png)

When I’m calling to API with request: http://localhost:1337/api/users/me?populate=*
then I’m getting only non-nested data like primary fields.

Why I’m not getting nested data? Request includes populate parameter (???).

**Comment by NadhirBenLazhar** [comment]
Hi,
It's a problem since Strapi 4.0.0

Your issue is a duplicate of this:
https://github.com/strapi/strapi/pull/11960

It is assigned to many milestones, but without a real solution.

All you have to do now is create tricks to get around this problem.
A. You can create a profile table. and make relation. so you can populate what you want.

B. Or use this solution. but it's bad (my opinion!)
1. Create a file `strapi-server.js` in this path: `/src/extensions/users-permissions/strapi-server.js`
2. Add this content inside,  and change populate to what you want:
using this solution will populate the user relation (you choose) **every time** you make a request. so be careful.

```
module.exports = plugin => {
  const sanitizeOutput = (user) => {
    const {
      password, resetPasswordToken, confirmationToken, ...sanitizedUser
    } = user; // be careful, you need to omit other private attributes yourself
    return sanitizedUser;
  };

  plugin.controllers.user.me = async (ctx) => {
    if (!ctx.state.user) {
      return ctx.unauthorized();
    }
    const user = await strapi.entityService.findOne(
      'plugin::users-permissions.user',
      ctx.state.user.id,
      { populate: ['role', 'profile'] }
    );

    ctx.body = sanitizeOutput(user);
  };

  plugin.controllers.user.find = async (ctx) => {
    const users = await strapi.entityService.findMany(
      'plugin::users-permissions.user',
      { ...ctx.params, populate: ['role', 'profile'] }
    );

    ctx.body = users.map(user => sanitizeOutput(user));
  };

  return plugin;
};
```

**Note: this code is provided by another person. I forgot where is the comment. Thanks to him.**

Happy coding.

**Comment by JakubLog** [comment]
Okay, thank you for your response!
