### ISSUE TITLE
Default menu title "Strapi Dashboard" customisable

### ISSUE THREAD

**Issue by tnguyen-pham** [strapi/strapi#12433]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I want to customize the default menu title and subtitle.

### Why is it needed?

 Now it shows "Strapi Dashboard" and a subtitle "Workplace" because it is hard coded.

### Suggested solution(s)

It should be configurable via a configuration object, e.g. if you change the logo

**Comment by soupette** [comment]
Hi @tnguyen-pham 

It is already doable in Strapi V4, you need to use the translations customisation system in order to change the title, here is the [corresponding translation key](https://github.com/strapi/strapi/blob/12a383ee7d6c4b6c45656a8ddc820983093e0a51/packages/core/admin/admin/src/components/LeftMenu/index.js#L83-L86) and here the documentation on how to extend the [translations](https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options).

I am closing this issue feel free to reopen it.
