### ISSUE TITLE
Change Strapi's Default WYSIWYG to a more feature rich Editor

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#12440]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
  - This is linked to https://portal.productboard.com/strapi/1-roadmap/c/37-wysiwyg-html-editor
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

The current and previous (v3) WYSIWYG editor are more so basic markdown editors and while markdown is awesome (since I'm writing this feature request in markdown :smile: ) I believe there is room for improvement and we could swap the default editor shipped with Strapi for something more feature rich and complete.

There is already community options in both v3 and v4 such as CKEditor 5, React MD, Toast UI, and Editor.js I do think we should ship something more feature complete then forcing everyone to install one of the community options.

If anything we could also make it easier to swap out our editor by standardizing methods to build new editors into the Strapi interface.

### Why is it needed?

Our current editor only supports the bare minimums in terms of markdown support (eg no tables, ect) and support for things like inline youtube video previews, ect are a bit more complex to handle properly.

Likewise not all non-technical content editors are familiar or like markdown. Likewise in many frontend frameworks a library is required to convert markdown to html. I believe it could be possible to handle this type of conversion server side and maybe caching those outputs (or pregenerating them).

### Suggested solution(s)

I don't believe selecting an html specific WYSIWYG editor is a good idea because ideally as not all uses for strapi will support html but I believe the best option is to pick an editor that instead uses a more json backed structure like [Editor.js](https://editorjs.io/) as we could either build in support in SDKs to convert this format to markdown, html, whatever basically and it fits with native strapi implementations (even doing things like lifecycle modifications to the content, ect would be very easy since we could natively interface with specific parts of the content)

Ideally whatever editor we choose should be opensource and preferably have a strong plugin system itself that we could leverage. I'm not saying Editor.js should be our choice but there is **a lot of editors out there** and I think it would be cool to explore this as a community and see what everyone thinks.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/10706
https://github.com/strapi/strapi/issues/9770
https://github.com/strapi/strapi/issues/8662
https://github.com/strapi/strapi/issues/4586
https://github.com/strapi/strapi/issues/3865
https://github.com/strapi/strapi/issues/3114
https://github.com/strapi/strapi/issues/2950
https://github.com/strapi/strapi/issues/1291
https://github.com/strapi/strapi/issues/8004
https://github.com/strapi/strapi/issues/6051
https://github.com/strapi/strapi/issues/2505
https://github.com/strapi/strapi/issues/978
https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5
https://github.com/kwinyyyc/strapi-plugin-wysiwsg-react-md-editor
https://github.com/fagbokforlaget/strapi-plugin-wysiwyg-toastui
https://github.com/melishev/strapi-plugin-react-editorjs

**Comment by derrickmehaffy** [comment]
List of editors I found by googling around that could be good options (will update this as I find more)
- https://quilljs.com/
- https://editorjs.io/
- http://suneditor.com/sample/index.html
- https://appleple.github.io/smartblock/

Awesome list of editors:
https://github.com/JefMari/awesome-wysiwyg

**Comment by gu-stav** [comment]
Thanks a lot for summarizing the feedback, @derrickmehaffy. I personally agree that we should support more use-cases with the editor. However, I would like to put a lot of emphasis on editors, which don't store the content in HTML/ Markdown, but a structured format such as JSON.

It goes very well with any API approach and allows to tailor the rendering of the content to any usecase. I believe these popular approaches currently exist:

## Prosemirror

Very popular. The schema is not 100% customizable (leafes (ex: bold, em ...)) are hard-coded. It can be extended nicely and is [used in newsrooms ](https://open.nytimes.com/building-a-text-editor-for-a-digital-first-newsroom-f1cb8367fc21 ) a lot, because it was started by the NyTimes and then adopted by the guardian and others. Because it is already quite old a very nice ecosystem has evolved around it, such as [tiptap](https://tiptap.dev).

- https://prosemirror.net

## Slate.js

Is newer than Prosemirror but has some advantages (e.g. easier schema, cleaner API (opinionated)). Keystone.js has build the [document field](https://keystonejs.com/docs/guides/document-fields) on top of it, which I believe is very powerful ([Demo here](https://keystonejs.com/docs/guides/document-field-demo)). All you see will be stored in JSON and can therefore be queried. What I do like about their implementation: they even ship a utility to render the JSON into React components.

- https://docs.slatejs.org/

## Portable Text

I don't know much about it, tbh (maybe someone else does?), but I think it is mainly being used by Sanity.io.

https://github.com/portabletext/portabletext

**Comment by derrickmehaffy** [comment]
@gu-stav Yeah I agree, not storing html or markdown would ideally be best

**Comment by BhuvaneshPatil** [comment]
Editor js - https://editorjs.io/

Would be really good. Because - 
 1 ) No need to have the preview.
 2 ) Outputs in JSON. Which can be consumed easily with APIs
 3 ) Easy to handle for Non-Technical folks.

**Comment by derrickmehaffy** [comment]
Was just playing around with this fork for v4 on the toast-ui editor and it's really neat (not quite production ready)

https://github.com/jaskipper/strapi-plugin-react-editorjs/tree/beta-v4
Forked from: https://github.com/melishev/strapi-plugin-react-editorjs

**Comment by kaansan** [comment]
This would be great. I've needed a solution for this and still looking for third party plugins in order to support better utilized editor.
I would be very appreciated if I can see all in one editor in Strapi V4.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/change-strapis-default-wysiwyg-to-a-more-feature-rich-editor
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
