### ISSUE TITLE
User Password doesn't have required mark

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#12455]
### Describe the bug

![password](https://user-images.githubusercontent.com/4951716/153362438-4a34705e-5dfa-4886-ad42-037e69a61222.png)

Password doesn't have a red asterisk mark even though it's required field.

### Steps to reproduce the behavior

1. Go to Content Manager.
2. Click User.
3. Click Create new entry.

### Expected behavior

Password should have a red asterisk mark for displaying it's required.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4.0.7
- Database: SQLite
- Operating system: MacOS M1

**Comment by derrickmehaffy** [comment]
We won't be able to fix this currently, the issue is because we strip the password from being sent to the frontend and thus the frontend doesn't think there is anything in there. 

It's a sanitization issue, aka a chicken and egg problem, if we make it required then every time you update that page (like change a users role) then you have to enter their password and if you don't enter anything then it won't let you save.

We can't fill that field with junk data as it would change the users password.

For now it will need to stay this way.
