### ISSUE TITLE
Media Relation doesn't get saved inside Components

### ISSUE THREAD

**Issue by siamekanto19** [strapi/strapi#12512]
## Bug report

Media Relationship doesn't get saved inside the component if we have nested components crated in the modeling. Not only for the Nested Component itself, Media Relationship fails to get saved in other components too . Uploaded image is shown in the field's image preview as long as we don't save the data, but disappears right after saving the data. Using Local Image Storage for the uploaded media.

### Steps to reproduce the behavior

1. Go to Strapi Dashboard
2. Create some components in Content Type Builder
3. Nest some components inside other components and save the models
4. Go to some collection type and add the available components in a dynamic section
5. Go to Content Editor and choose a component from the dynamic section that has media field. 
6. Try to upload an image and save the data in Content Editor

### Example of the Issue

![ezgif com-gif-maker](https://user-images.githubusercontent.com/71663224/153838476-6ddae85d-5763-46d7-a6f8-3fd77b913b98.gif)

### Expected behavior

Media Relationship gets saved without error like other normal data like Text Fields and Rich Text

### System

- Strapi version: v4.0.7
- Database: SQlite

Reference: #9462

**Comment by siamekanto19** [comment]
@aukgit

**Comment by aukgit** [comment]
Hi @gu-stav,

Do you have any migration or any type of solution to this problem?

**Comment by aukgit** [comment]
@siamekanto19 add gif now, it will help

**Comment by aukgit** [comment]
Hi @gu-stav,

Gif also added for further demonstration.

Thanks

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9308

**Comment by gu-stav** [comment]
@aukgit @siamekanto19 I'm not able to reproduce the issue on 4.0.7. Could you share your model with me or add more detailed steps?

**Comment by siamekanto19** [comment]
Hi @gu-stav ,
Can you please try after making one or two components that has more than 2 levels nested components inside of them? I know it is not possible in normal way, but we could create a component that has more than 2 levels nested components inside of it if we create those deeply nested components inside the creation process of the parent component.

**Comment by derrickmehaffy** [comment]
> Hi @gu-stav , Can you please try after making one or two components that has more than 2 levels nested components inside of them? I know it is not possible in normal way, but we could make it happen if we create those deeply nested components inside the creation process of the parent component.

There are other reasons this is breaking, multiple levels of nesting beyond 2 isn't something that we can fix right now until it's decided if we will even support it. And that issue is here: https://github.com/strapi/strapi/issues/11319

I can't reproduce using components normally (with 2 levels) so the issue is "fixed" with what is currently supported.

**Comment by aukgit** [comment]
> > Hi @gu-stav , Can you please try after making one or two components that has more than 2 levels nested components inside of them? I know it is not possible in normal way, but we could make it happen if we create those deeply nested components inside the creation process of the parent component.
> 
> There are other reasons this is breaking, multiple levels of nesting beyond 2 isn't something that we can fix right now until it's decided if we will even support it. And that issue is here: #11319
> 
> I can't reproduce using components normally (with 2 levels) so the issue is "fixed" with what is currently supported.

Hello @gu-stav @derrickmehaffy,

Strapi is great, we loved the strapi community as it is very responsive and as a product is impressive. It has all the great features that experience developers would love or want. 

We have seen a great number of strapi examples (also this https://strapi.io/demo), we are impressed with what strapi really can do. 

**However,** everything is getting wasted as some of the examples from the demo were not working.

## Here are some of the key points which blocks strapi to become the next market leader:

- Nesting level features shown in the demo ( this https://strapi.io/demo ) but not working buggy. (but false marketed please correct me if I am wrong)
- Data migration support missing ( please correct me if I am wrong )
   -  Let's say I am 5 months in production and I have a large data entry, now I want to modify the data relationship or add a new dynamic zone section, there is a chance of data loss, how to handle it or what is the recommended approach.
   -  Multilevel images are troubling which looks bad in front of top management to represent this product as a hero.
   - Strapi should have staging environment support and data migration auto from one env to another this is kind of the main feature of such a product.
         -  Things will go in 2 levels (1. data models one migration, 2. if stable goes to data migration, 3. Seeding data option 4. data backup option)
         - Data is the king, currently, strapi is treating data as shit.
- Another thing that is bugging me is that issues get closed just because those are duplicates, however, how it should be managed is to label with duplicates and manage in the portal that these many clients has complaints when resolved it should be marked as close not until then.
    - for example when https://github.com/strapi/strapi/issues/12510 one is implemented close this, not until then

CC : @siamekanto19 , @gu-stav , @derrickmehaffy , @lauriejim, @pierreburgy

**Comment by gu-stav** [comment]
@aukgit Thanks a lot for the feedback. We really appreciate it. I have forwarded it to the team. That being said: nesting with more than two levels is something we are already aware of and it's being discussed. That's all I can say for now, because it touches on many parts of Strapi (UI, API, Performance ...).

> Another thing that is bugging me is that issues get closed just because those are duplicates, however, how it should be managed is to label with duplicates and manage in the portal that these many clients has complaints when resolved it should be marked as close not until then.

That's one way of approaching it. We decided to keep the number of issues smaller, but we keep track internally of how often a duplicate is opened so that we can prioritize these issues. For now that system helps us to keep an overview.

**Comment by aukgit** [comment]
> @aukgit Thanks a lot for the feedback. We really appreciate it. I have forwarded it to the team. That being said: nesting with more than two levels is something we are already aware of and it's being discussed. That's all I can say for now, because it touches on many parts of Strapi (UI, API, Performance ...).
> 
> > Another thing that is bugging me is that issues get closed just because those are duplicates, however, how it should be managed is to label with duplicates and manage in the portal that these many clients has complaints when resolved it should be marked as close not until then.
> 
> That's one way of approaching it. We decided to keep the number of issues smaller, but we keep track internally of how often a duplicate is opened so that we can prioritize these issues. For now, that system helps us to keep an overview.

Thank you for your quick response. Hope that the migration issue will be considered a priority otherwise, we cannot use it in production at this moment.

:)

**Comment by aukgit** [comment]
Features and correctness of the program are my priority. As performance can be improved later but also can be improved quickly using a caching mechanism. In most cases, strapi is a kind of alternative to WordPress other cms where data in most cases remains unchanged. This can be a good thing because we can do a cache to improve performance for the time being and in the background, strapi can do research on performance improvements, however, if the main feature doesn't work it can be alarming.

Thank you once again for all the support.

👍

**Comment by aukgit** [comment]
@derrickmehaffy 

For understanding purpose will you please kindly share which one is level 2 and which is level 3 nesting from this 
![image](https://user-images.githubusercontent.com/4561204/154495761-ec758fd7-9dd5-40df-92d7-f1f629af7266.png)

it is from the strapi demo  https://strapi.io/demo


thanks

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy 
> 
> For understanding purpose will you please kindly share which one is level 2 and which is level 3 nesting from this 
> ![image](https://user-images.githubusercontent.com/4561204/154495761-ec758fd7-9dd5-40df-92d7-f1f629af7266.png)
> 
> it is from the strapi demo  https://strapi.io/demo
> 
> 
> thanks

Blocks => Pricing Cards => Perks is 2 levels.

The limitation is on Components, where they can be only two levels deep either on the parent model or inside a dynamic zone. (We don't allow nesting dynamic zones at all and that has a different issue).

All of the examples in those images remain at the 2 levels of nesting.

**Comment by derrickmehaffy** [comment]
> Another thing that is bugging me is that issues get closed just because those are duplicates, however, how it should be managed is to label with duplicates and manage in the portal that these many clients has complaints when resolved it should be marked as close not until then.

Any duplicate closed has to be tied to it's duplicate issue and GitHub automatically shows linked issues on each other.

We can't have 20 issues talking about the exact same thing. GitHub issues are for product and Engineering teams to have information to fix bugs. They are not support tickets for users, our enterprise edition has a support plan for silver and gold customers if that's what you're looking for.

And our contribution guide clearly states our requirements on issues: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

Specifically: 

> You have already searched for related issues, and found none open (if you found a related closed issue, please link to it from your post).
