### ISSUE TITLE
Different user role access for disable Add Components button in Dynamic Zone

### ISSUE THREAD

**Issue by cyt26** [strapi/strapi#12539]
## Feature request

Different user role access for disable Add Components button in Dynamic Zone

<img width="979" alt="Screenshot 2022-02-15 at 6 24 41 PM" src="https://user-images.githubusercontent.com/99750926/154110612-4027ed08-99ef-4a10-ad31-277886dd0ede.png">

**Comment by derrickmehaffy** [comment]
If I understand correctly (the english is a little off)

You want to have RBAC control if a role can add new components from a dynamic zone. Correct me if I'm wrong please.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/permission-control-over-dynamic-zones-and-components-limit-adding-new-components
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
