### ISSUE TITLE
Form labels in Windows Edge are not left-aligned

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#1253]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3 alpha 12.2
- **Database**: MongoDB
- **Operating system**: Win10

**What is the current behavior?**

Form labels in Windows Edge are centered:

![image](https://user-images.githubusercontent.com/83678/40399594-363aad6a-5e0c-11e8-9a87-4d3b14dca983.png)

**What is the expected behavior?**

Left aligned

**Suggested solutions**

I could fix this by adding a `form .row { text-align: left; }` stanza to https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/styles/base/bootstrap-override.scss (if that's the best place for it..)

**Comment by lauriejim** [comment]
Hello @nurikabe , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free to submit a PR with your changes, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md
