### ISSUE TITLE
`json` field invalidates all validation rules for other fields

### ISSUE THREAD

**Issue by dzcpy** [strapi/strapi#12560]
### Describe the bug

When adding a `json` field to any content type, user can always save the content regardless of any validation rules, like leaving some required fields empty.

### Steps to reproduce the behavior

1. Add a `json` field to any content type, and make sure there is a required field in this type.
2. Add a new type of the content, leave all required fields empty.
3. Click save.

### Expected behavior

Stops user from saving the content if there is a validation error.

### Screenshots

![image](https://user-images.githubusercontent.com/203980/154386289-5c3f1e24-b6ac-48f0-99aa-87da66bed3df.png)

### System

- Node.js version: 
- NPM version:
- Strapi version: 4.0.8 
- Database:
- Operating system:

**Comment by petersg83** [comment]
Hello,

I couldn't reproduce the bug.
In your screenshot we see that you saved the entity as a "draft". Some validations are deactivated for drafts (required and min/max) because you may not have the time/the content for everything yet but still want to start to fill your entry. If you try to publish, you will normally get an error.
Maybe it can be better explained in the documentation: poke @strapi/documentation

**Comment by dzcpy** [comment]
Ah, I see, thanks for your response

**Comment by petersg83** [comment]
Thank you for sharing the feedback :)
