### ISSUE TITLE
Right relationship field name should have a search input above the dropdown

### ISSUE THREAD

**Issue by Emyboy** [strapi/strapi#12598]
Do relationships on huge strapi projects can become tiresome when you have a lot of schemas.

It'll be nice if one could search the dropdown when selecting an association.

One would have to scroll through the entire list, to get to the schema of choice.

![image](https://user-images.githubusercontent.com/34845973/154808451-2848ce40-d1c2-4e11-99bc-63f1e197a95d.png)

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

You can see the template guidelines for bug reports and feature requests [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by yanniskadiri** [comment]
Thanks for letting us know @Emyboy 

I'll move your feedback to our feedback database, when we start working on the relationship performance again soon, we'll take it into account.

**Comment by Aurelsicoko** [comment]
**Issue was linked to Harvestr Discovery:**  [Relations performance](https://app.harvestr.io/components/0/list/dWh9s080_)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/right-relationship-field-name-should-have-a-search-input-above-the-dropdown
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
