### ISSUE TITLE
Renaming a field in a content-type will erase the existing data

### ISSUE THREAD

**Issue by paulovieira** [strapi/strapi#12626]
### Describe the bug

If I rename a field in a content-type, and if there is some previous data there (in that field), all the data will be erased. 

Inspecting the database directly (SQLite) I see that
1.  the new column has `<null>` in all rows
2. the old column was deleted

### Steps to reproduce the behavior

1. Create a new content-type (doesn't matter if it's a collection type, single type or component). Example: "restaurant". Add a text field named "something".
2. Inspect the SQLite database. Verify that strapi created a table named `restaurants`, and it has a column named `something`
3. Add some content using the Content Manager.
4. Using the Content-Type Builder, rename the field to `something2`
5. Inspect the database again. I see that a new column named `something2` was added to the `restaurants` table (with `<null>` in all rows) and the column `something` was deleted.

### Expected behavior

I've read in several places that strapi should never deleted data for this kind of operations. 

As a technical user, I expected that the initial `something` column should not be deleted ("never loose data")

As a non-technical user (who doesn't know how to access the data from the database directly), I expected that the `something2` column should be populated with the data from `something` (imagine a content type with 1000's of records...)

### System

- Node.js version: v14
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: Linux

### Additional context

I'm aware that #1114 was used for this kind of issues, but it's closed and this particular thing (renaming a field) doesn't seem to be convered there.

I was surprised to learn about this behaviour. Being able to rename a field is one of the most basic features for a tool like strapi. 

APIs should evolve naturally.  Furthermore, SQLite is the default database system, so I imagine there is a lot of people using it.

**Comment by derrickmehaffy** [comment]
@strapi/content and @strapi/developer-experience I don't know which squad this goes in so I set it in both of your projects.

We have discussed this internally at length before and we already know it requires sending more data to the backend then is currently sent.

---

To users in the meantime, when you are renaming you will need to use something like what is in this repo: https://github.com/derrickmehaffy/strapi-example-v4-custom-db

It won't stop you from losing the data locally (but that should be atomic anyway) but will help with deploying into production. Alternatively you can rename manually via the schema files and build your migration at the same time.

**Comment by apsonandtesla** [comment]
Yeah we have found out the same issue and personally I think it's kind of important. If there is anything we can do for help, we are happy to help. Hope this get fixed as soon as possible.

**Comment by Convly** [comment]
Hello there, this behavior is the intended one (at least for the moment). In V3 we weren't cleaning up the DBs as projects were evolving and it created a lot of friction & resentment from the community. For V4, we decided to tackles this issue and started cleaning up the DB on schema changes (basically a schema/DB sync). However -and you're right- there is no way today for the schema sync to differentiate when a field is renamed from when one is deleted/created. If we want to allow this kind of distinction, it would imply in-depth modification of the content type builder API as well as some behavior in the schemas themselves. As we lack bandwidth for the moment, this is not something that will be handled in the short term.
However, it's true that there is a possible data loss when deploying a field rename from dev to production. Thus, I would advise creating a custom DB migration so that you can transfer the data before the schema sync is done. (more info on Derrick's link)

**Comment by paulovieira** [comment]
Thanks for the detailed response. 

For the short term I would suggest that you make a small change in the admin UI to disallow the possibility of renaming a field (that is, add the `disabled` attribute to the `<input>`, except when the field is being created). This will immediately solve the problem of loss of data. 

And if someone really needs to change the field name, the correct path seems to use the new migrations system.
