### ISSUE TITLE
REST API does not fallback to default locale

### ISSUE THREAD

**Issue by michaelkrone** [strapi/strapi#12799]
## Bug report
The REST API does not return entities with the default locale if a locale is requested for which no localizations exist. 
The documentation (https://docs.strapi.io/developer-docs/latest/plugins/i18n.html#configuration-of-the-default-locale) states, that

> If the database does not contain any locale, and no STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE is set for the environment, all entities of the content types, which have localization enabled, will be automatically migrated to the en locale.

### Describe the bug
If fetching records with the `locale` parameter, the parameter has to be `all` or a locale for which entities exist. All other values return an empty data set (empty Array).
- `http://strapi-host:1337/api/cards?locale=en` returns the localized records
- `http://localhost:1337/api/cards?locale=fr` returns no records (empty array), but should return the default (en) localized records

### Steps to reproduce the behavior

1. Create an enity for the English language
2. Query the entity for any other language
3. The result data is empty

### Expected behavior
The REST API should fallback for the default locale if no data could be found for the requested locale 

### System

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.3
- Database: postgres
- Operating system: Mac OS 12.0.1

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/add-email-field-option-for-uid-target
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
