### ISSUE TITLE
properly log AWS email provider error messages

### ISSUE THREAD

**Issue by moalamri** [strapi/strapi#12867]
# EDIT, see this comment: https://github.com/strapi/strapi/issues/12867#issuecomment-1193601525

### Describe the bug
`@strapi/provider-email-amazon-ses` does not work and produce an error

```
[2022-03-17 05:37:54.039] error: Couldn't send test email: undefined.
Error: Couldn't send test email: undefined.
at Object.test (**\node_modules\@strapi\plugin-email\server\controllers\email.js:56:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async returnBodyMiddleware (**\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
at async policiesMiddleware (**\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
at async **\node_modules\@strapi\strapi\lib\middlewares\body.js:25:7
at async **\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
at async cors (**\node_modules\@koa\cors\index.js:95:16)
at async **\node_modules\@strapi\strapi\lib\middlewares\errors.js:13:7
at async session (**\node_modules\koa-session\index.js:41:7)
at async **\node_modules\@strapi\strapi\lib\services\metrics\middleware.js:29:5
```

### Steps to reproduce the behavior

1 Setup configs
2 The plugin is installed and shows up in the Admin UI
3 Open Settings > Email Plugin > Configuration > Test email delivery > Send test email

### Expected behavior
The email to be sent!

### Screenshots
<img width="752" alt="Screenshot (14)" src="https://user-images.githubusercontent.com/964077/158728936-85fad8c0-3cb4-48e4-be0d-38b2f5c0d7bb.png">

### System

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: 4.1.5
- Database: Pg
- Operating system: Windows 11

### Additional context
`   
@strapi/provider-email-amazon-ses:  4.1.5

@strapi/strapi: 4.1.5
`

**Comment by wfzong** [comment]
I got the same issue.

# Describe the bug

**When I use the "node-ses" send email, it works perfect.** I can sent the test email successful, and the receiver can receive the test email too.
![aaaa](https://user-images.githubusercontent.com/12407298/159216382-8336e7ae-8343-483b-89ad-1c3b47841314.png)
![bbbb](https://user-images.githubusercontent.com/12407298/159216436-c6129fc1-6636-431f-8cd5-70b568952120.png)


## But, when I trying to use Straip to sent the test email, I got a error~

### config in Strapi
![cccc](https://user-images.githubusercontent.com/12407298/159216714-982b6bd9-7ed2-450a-9f05-a8b54139b998.png)
![dddd](https://user-images.githubusercontent.com/12407298/159216798-ca45d8ad-b5d6-45aa-935d-e7cedaec4ec9.png)


### When I send the test email from admin  Dashboard, I got the error message like this:

`
[2022-03-21 14:58:40.141] error: Couldn't send test email: undefined.
Error: Couldn't send test email: undefined.
    at Object.test (D:\works\me\lp4\strapi\node_modules\@strapi\plugin-email\server\controllers\email.js:56:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async returnBodyMiddleware (D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\middlewares\body.js:25:7
    at async D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\middlewares\logger.js:22:5
    at async D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
    at async cors (D:\works\me\lp4\strapi\node_modules\@koa\cors\index.js:95:16)
    at async D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\middlewares\errors.js:13:7
    at async session (D:\works\me\lp4\strapi\node_modules\koa-session\index.js:41:7)
    at async D:\works\me\lp4\strapi\node_modules\@strapi\strapi\lib\services\metrics\middleware.js:29:5
`


### Steps to reproduce the behavior
1 Setup configs
2 The plugin is installed and shows up in the Admin UI
3 Open Settings > Email Plugin > Configuration > Test email delivery > Send test email

## Expected behavior
The email to be sent!

### System
Node.js version: v16.13.2
NPM version: 8.1.2
Strapi version: 4.1.5
Database: sqlite3
Operating system: Windows 11
Additional context
`
@strapi/provider-email-amazon-ses: 4.1.5

@strapi/strapi: 4.1.5

**Comment by moalamri** [comment]
@wfzong Yea I get the email working when I use standalone node-ses or strapi-nodemailer.
Anyways I was able to trace this to get the correct error which was `Connect out`. And for some reason the wrapper tries to connect on port `443` and that's why it fails to send email or get an error message.
I didn't dig more into this, but this is how far I got, I might look into this today...

**Comment by wfzong** [comment]
@moalamri I got some information about the error yesterday. 
The email body field of node-ses is "message", but the default of Strapi send email use the filed "text".

So I created a local provider follow by: https://docs.strapi.io/developer-docs/latest/plugins/email.html#create-new-provider
and send email from the local provider.

The code like this:
- providers\strapi-provider-email-awsmail\index.js
``` javascript
module.exports = {
    init: (providerOptions = {}, settings = {}) => {
        const ses = require('node-ses')
        const client = ses.createClient(providerOptions);

        return {
            send: async options => {
                options.message = options.text // aws SES 的字段为 message

                return await new Promise((resolve, reject) => {
                    client.sendEmail({ ...options, ...settings }, function (err, data, res) {
                        if (data) {
                            return resolve(data)
                        }
                        if (err) {
                            return reject(err)
                        }
                    });
                })
            },
        };
    },
}
```

So I can send email finally...

**Comment by moalamri** [comment]
@wfzong I will try this and let you know :)
Thank you

**Comment by wfzong** [comment]
> @wfzong I will try this and let you know :) Thank you.
> 
> Update: Yes it does work :). But since this solution is done by making a custom provider (using standalone node-ses) it would be considered as a workaround or an extra option beside using the strapi-nodemailer provider which works with amazon-ses. So I will leave this open and give any extra info to solve this.

Super to hear that~

**Comment by moalamri** [comment]
This is the output of the send function.
I don't know why it's trying to connect to port 443
<img width="466" alt="image" src="https://user-images.githubusercontent.com/964077/159782742-b78396b6-9c6f-4835-8062-78ee6cfb1720.png">

**Comment by wfzong** [comment]
Hi @moalamri ,did you have configured a appropriate permission on Amazon SES?

**Comment by moalamri** [comment]
Hey @wfzong yes I did. I can send emails with other a-ses supporting providers.
This error is populated by strapi’s wrapper of koa. I’m not sure if email provider is supposed to send emails through koa. 
I just need extra time to dig into this 🤯

**Comment by derrickmehaffy** [comment]
We don't do anything special here, if there is an issue it's most likely inside the node-ses package: https://github.com/strapi/strapi/blob/master/packages/providers/email-amazon-ses/lib/index.js

If you want to doublecheck you could edit this file in your node_modules and log out the options in the `send` function

**Comment by misterzero** [comment]
Hello, I'm experiencing the same issue. Is there any resolution other than creating a custom provider?

**Comment by moalamri** [comment]
I for awhile thought it was a single user issue, but since some others are experiencing the same, I’ll reopen this issue again in hope someone would find the root cause of this 🤔

**Comment by derrickmehaffy** [comment]
> We don't do anything special here, if there is an issue it's most likely inside the node-ses package: https://github.com/strapi/strapi/blob/master/packages/providers/email-amazon-ses/lib/index.js
> 
> If you want to doublecheck you could edit this file in your node_modules and log out the options in the `send` function

I'll reiterate that I need someone to try logging some information out for me as I cannot reproduce.

**Comment by misterzero** [comment]
> I'll reiterate that I need someone to try logging some information out for me as I cannot reproduce.

Here's the output I got:
```
options = {"to":"xxx@xxx.xxx","subject":"Strapi test mail to: xxx@xxx.xxx","text":"Great! You have correctly configured the Strapi email plugin with the amazon-ses provider. \r\nFor documentation on how to use the email plugin checkout: https://docs.strapi.io/developer-docs/latest/plugins/email.html"}
[2022-05-19 17:03:38.408] error: Couldn't send test email: undefined.
Error: Couldn't send test email: undefined.
    at Object.test (/Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/plugin-email/server/controllers/email.js:56:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async returnBodyMiddleware (/Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/middlewares/body.js:51:9
    at async /Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/Users/chris/projects/personal/yutopya/strapi-api/node_modules/@koa/cors/index.js:95:16)
    at async /Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/Users/chris/projects/personal/yutopya/strapi-api/node_modules/koa-session/index.js:41:7)
    at async /Users/chris/projects/personal/yutopya/strapi-api/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
```

**Comment by misterzero** [comment]
My settings are the same as above, and I confirmed this behavior is consistent across node `v14.19.0` and `v16.14.0`.

**Comment by moalamri** [comment]
> out

That confused me since writing a strapi custom provider to use the same node-ses will work.

@misterzero could you please do the suggested changes as what @derrickmehaffy have said? Just to see if the same error is timeout otherwise this doesn't belong here and I'll close the issue

**Comment by ebengtso** [comment]
Hi,

I have created a new provider. I think this can be useful for some

Plugin email config
'module.exports = ({ env }) => ({
    // ...
    email: {
      config: {
        provider: 'strapi-provider-email-awsmail',
        providerOptions: {
          key: env('EMAIL_SERVER_USER'),
          secret: env('EMAIL_SERVER_PASSWORD'),
          amazon: env('EMAIL_SERVER_HOST'),
          region: env('EMAIL_SERVER_REGION'),
        },
        settings: {
          defaultFrom: env('EMAIL_FROM'),
          defaultReplyTo: env('EMAIL_REPLY_TO'),
        },
      },
    },
    // ...
  });
'

Provider code

`'use strict';

const { SESClient, SendEmailCommand } = require("@aws-sdk/client-ses");
const { removeUndefined } = require('@strapi/utils');

module.exports = {
  init(providerOptions = {}, settings = {}) {
    //var client = nodeSES.createClient({ ...providerOptions });
    var client = new SESClient({ region: providerOptions.region,
        credentials: {
            accessKeyId: providerOptions.key,
            secretAccessKey: providerOptions.secret,
          } });
    

    return {
      send(options) {
       // return new Promise((resolve, reject) => {
          const { from, to, cc, bcc, replyTo, subject, text, html, ...rest } = options;

          let msg = {
            from: from || settings.defaultFrom,
            to,
            cc,
            bcc,
            replyTo: replyTo || settings.defaultReplyTo,
            subject,
            altText: text || '',
            message: html || '',
            ...rest,
          };

            // Set the parameters
            const params = {
                Destination: {
                /* required */
                /*
                BccAddresses: [
                    msg.bcc
                ],
                CcAddresses: [
                    msg.cc
                ],
                */
                ToAddresses: [
                    msg.to
                ],
                },
                Message: {
                /* required */
                Body: {
                    /* required */
                    Html: {
                    Charset: "UTF-8",
                    Data: msg.message,
                    },
                    Text: {
                    Charset: "UTF-8",
                    Data: msg.altText,
                    },
                },
                Subject: {
                    Charset: "UTF-8",
                    Data: msg.subject,
                },
                },
                Source: msg.from, // SENDER_ADDRESS
                ReplyToAddresses: [
                    msg.replyTo
                ],
            };
            var command = new SendEmailCommand(params);
        
            return client.send(command);
            /*.(removeUndefined(msg), function(err) {
            if (err) {
              if (err.Message) {
                reject(`${err.Message} ${err.Detail ? err.Detail : ''}`);
              }
              reject(err);
            } else {
              resolve();
            }
            
          });
          
        });*/
      },
    };
  },
};
`

**Comment by Arpit1989** [comment]
I am adding a note so that anyone who faces similar issue, can debug it easily. 

under the node_modules/@strapi/provider-email-amazon-ses/lib/index.js

add the following line 
process.env.DEBUG='node-ses';

try resending the email using the test and check the response from the AWS SendMail API in logs. 

In case of Access related issues

node-ses received: null 403 "<ErrorResponse xmlns=\"http://ses.amazonaws.com/doc/2010-12-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>SignatureDoesNotMatch</Code>\n    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\n  </Error>\n  <RequestId>64e2dedd-ff87-4bef-9d08-7722280039f1</RequestId>\n</ErrorResponse>\n" +1s
{
  Type: 'Sender',
  Code: 'SignatureDoesNotMatch',
  Message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'
}

Ideally node-ses should throw an error but in this case it didn't. 
https://github.com/aheckmann/node-ses/blob/master/lib/email.js

The node-ses uses a deprecated request package 
<img width="844" alt="Screen Shot 2022-07-25 at 1 21 19 AM" src="https://user-images.githubusercontent.com/2972479/180705020-fca9c9bc-efd1-47a8-a140-5aa5b9bdbb1f.png">

Error Response is thrown by the node-ses when we change original implementation. 
<img width="1011" alt="Screen Shot 2022-07-25 at 1 21 36 AM" src="https://user-images.githubusercontent.com/2972479/180705046-0506fe6e-d4dc-45e6-a479-94a0d7e7e897.png">

**Comment by derrickmehaffy** [comment]
Reopening as a minor bug for us to adjust the provider and log the actual error message.

**Comment by alexandrepaiva-dev** [comment]
This same issue is happening with me too, I haven't found a solution yet.

**Comment by alexandrepaiva-dev** [comment]
This same issue is happening with me too when using Amazon SES, I haven't found a solution yet.

**Comment by OmnomnomTee** [comment]
I had the same problem. In my case, it was a user error, but the error message was unhelpful. If you need to debug your issue go to the following file:

node_modules/@strapi/plugin-email/server/controllers/email.js
At line 50 replace 

```
throw new Error(`Couldn't send test email: ${e.message}.`);
```
with:

```
throw new Error(`Couldn't send test email: ${e}.`);
```

This gives clearer error messages. In my case

```
error: Couldn't send test email: undefined.
```

Is now correctly logged as

```
Couldn't send test email: Error: Invalid URI "email.eu-central-1.amazonaws.com" .
```

For me the correct URL is: https://email.eu-central-1.amazonaws.com

**Comment by alexandrepaiva-dev** [comment]
Thanks @OmnomnomTee! Doing this I was able to debug the error and fix it in Amazon SES. In my case it was related to the policy, I needed to update based on this answer:

https://stackoverflow.com/questions/63725466/aws-ses-user-is-not-authorized-to-perform-sessendemail-on-resource

**Comment by nikosbaltas** [comment]
> I had the same timeout problem, turns out that my aws_ses_host was wrong, I was using the one provided in SES settings, with a "-smtp" suffix.
> 
> Just used the default "https://email.us-east-1.amazonaws.com" and it worked.
> 
> ![image](https://user-images.githubusercontent.com/4723109/170339202-23e6aba9-3c3e-49df-90cd-3cf9aaad3c53.png)

Thanks, this worked for me!

**Comment by NGrPXL** [comment]
> I had the same timeout problem, turns out that my aws_ses_host was wrong, I was using the one provided in SES settings, with a "-smtp" suffix.
>
> Just used the default "https://email.us-east-1.amazonaws.com" and it worked.
> 
> ![image](https://user-images.githubusercontent.com/4723109/170339202-23e6aba9-3c3e-49df-90cd-3cf9aaad3c53.png)

Can confirm this solution worked for me too.

**Comment by derrickmehaffy** [comment]
Confirmed by multiple people to be resolved outside of Strapi, going to mark as closed. Thanks all

**Comment by thiagoandf** [comment]
@derrickmehaffy Sorry to go back to this issue, but I would actually argue that the original issue report was in regard to logging the error message correctly. 

By doing this simple change mentioned [here](https://github.com/strapi/strapi/issues/12867#issuecomment-1232565848) on [this file](https://github.com/strapi/strapi/blob/c0bd11c47bd49b91e9f91689a22558d19257a31a/packages/core/email/server/controllers/email.js#LL50C68-L50C68) we are able to fix the logging to show the actual error, and not `undefined`.

**Comment by anilbhanushali** [comment]
Still facing the issue report by OP.

**Comment by Antvirf** [comment]
Ran into this, leaving a reply in case others find it useful. For me it was a combination of the below items, and the first thing I did was to implement the change from [this reply](https://github.com/strapi/strapi/issues/12867#issuecomment-1232565848) to get useful error messages.

- **I had the wrong SMTP host address:** Using the SMTP address given by AWS SES (i.e. `email-smtp.xxx`), instead of the correct one which is just `email.xxx` without the "-smtp" suffix, as suggested by [this reply](https://github.com/strapi/strapi/issues/12867#issuecomment-1137690973)
- **I was using AWS IAM SMTP credentials**: I was getting `The request signature we calculated does not match the signature you provided` errors similar to [this reply](https://github.com/strapi/strapi/issues/12867#issuecomment-1193601525). Turns out this is because **the plugin uses AWS SES SDK, NOT SMTP directly**. This means that you need to use a regular IAM user/role access key, not the SMTP access key. See [this page](https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-credentials.html) from AWS.
- **I had insufficient IAM Permissions**: My SES user had just `ses:SendRawEmail` permission; Strapi AWS SES plugin also requries `ses:SendEmail`. This was straightforward to resolve as the error messages are clear if you implement the fix from above.

**Comment by palamim** [comment]
> Ran into this, leaving a reply in case others find it useful. For me it was a combination of the below items, and the first thing I did was to implement the change from [this reply](https://github.com/strapi/strapi/issues/12867#issuecomment-1232565848) to get useful error messages.
> 
> * **I had the wrong SMTP host address:** Using the SMTP address given by AWS SES (i.e. `email-smtp.xxx`), instead of the correct one which is just `email.xxx` without the "-smtp" suffix, as suggested by [this reply](https://github.com/strapi/strapi/issues/12867#issuecomment-1137690973)
> * **I was using AWS IAM SMTP credentials**: I was getting `The request signature we calculated does not match the signature you provided` errors similar to [this reply](https://github.com/strapi/strapi/issues/12867#issuecomment-1193601525). Turns out this is because **the plugin uses AWS SES SDK, NOT SMTP directly**. This means that you need to use a regular IAM user/role access key, not the SMTP access key. See [this page](https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-credentials.html) from AWS, and [this GitHub](https://github.com/aws/aws-sdk-js/issues/1443) thread also helped me.
> * **I had insufficient IAM Permissions**: My SES user had just `ses:SendRawEmail` permission; Strapi AWS SES plugin also requries `ses:SendEmail`. This was straightforward to resolve as the error messages are clear if you implement the fix from above.

This last point worked for me. I resolved it by going to the Amazon AWS Console, navigating to IAM, User Groups, and then to IAM SES sending group. I added the ses:SendEmail permission, as shown in the image below.

<img width="407" alt="Screenshot 2024-09-22 at 12 51 47" src="https://github.com/user-attachments/assets/014e9349-a7fe-4ff4-b663-6afd5aa9dd2f">
