### ISSUE TITLE
[V3] Fix CVE-2022-0764 

### ISSUE THREAD

**Issue by timyboy12345** [strapi/strapi#12879]
### Describe the bug

There is a security vulnerability in Strapi that prevents our deployment pipeline from running. There is already a fix implemented for v4.x, but upgrading is not on our short-term road map for now. It seems like the fix from v4 can be copied to v3 1 on 1, but since I've never contributed to this repository I was hoping there was someone willing to back-port the fix to v3. 

### Other information
- Vulnerability on nist.gov: [CVE-2022-0764](https://nvd.nist.gov/vuln/detail/CVE-2022-0764)
- Explanation on huntr.dev: https://huntr.dev/bounties/001d1c29-805a-4035-93bb-71a0e81da3e5/
- Commit to v4 that fixes the issue: https://github.com/strapi/strapi/commit/2a3f5e988be6a2c7dae5ac22b9e86d579b462f4c

**Comment by markkaylor** [comment]
Hi @timyboy12345  sorry I am not able to reproduce the issue described on [huntr](https://huntr.dev/bounties/001d1c29-805a-4035-93bb-71a0e81da3e5/) for Strapi version 3.x.

The security issue was introduced in v4.0.0 when we changed how we create projects with starters and templates via the CLI and fixed in v4.1.1. I believe it only exists between these versions.

Please let me know if I’ve missed something and I will fix it ASAP.

**Comment by timyboy12345** [comment]
I see. The record in the NVD states that all versions before 4.1.0 were impacted, including v3.x.x, meaning it gets flagged in `yarn audit`. 

I've created a ticket with NIST asking them to change this, hopefully resulting in versions greater than 4.0.0-alpha.2 and smaller than 4.1.0 being flagged.
