### ISSUE TITLE
The upload files response from API contains stream object

### ISSUE THREAD

**Issue by nhvu1988** [strapi/strapi#13202]
### Required System information

- Node.js version: 16 LTS
- NPM version: 8.5.0
- Strapi version: 4.1.9
- Database: mysql

### Describe the bug

The upload files response from API contains `stream` object in the `formats` property. It only occurs on the cropped files. And maybe it only occurs on cloud upload providers that require an `async upload` function?

### Steps to reproduce the behavior

1. Upload file in media and crop it
2. Check the API response from `/api/upload/files`
3. See the stream object in every `formats`

```json
{
	"name": "test.jpg",
	"hash": "large_test_0b6a9b4599",
	"ext": ".jpg",
	"mime": "image/jpeg",
	"path": null,
	"width": 1000,
	"height": 562,
	"size": 56,
	"stream": {
		"fd": null,
		"path": "/tmp/strapi-upload-JmlOBd/test_0b6a9b4599",
		"flags": "r",
		"mode": 438,
		"end": null,
		"bytesRead": 0,
		"closed": false,
		"_readableState": {
```

### Expected behavior

It should be cleared and isn't saved to the database.

**Comment by kovinet** [comment]
In my case I have noticed this happens when I use Replace Media function (replace existing image for an object). It happens that after replacing (I am using S3 provider) API starts to return "stream" object for image formats instead of actual url of images, which results in broken frontend.  

Also in many cases 'thumbnail' format is working normally, but not other formats (small, medium, large) - but this it not always same. But when uploading same image directly to Media Library (not using replace for existing) this has never happened so far in my case.

**Comment by derrickmehaffy** [comment]
I've raised this to high but I believe this might have been fixed by https://github.com/strapi/strapi/pull/13370 pending confirmation.

**Comment by nhvu1988** [comment]
Seem it's fixed so I'm closing this issue
