### ISSUE TITLE
Socket error when connection with flutter application server.handleUpgrade()

### ISSUE THREAD

**Issue by oybek1024** [strapi/strapi#13264]
**Socket error when connection with flutter application server.handleUpgrade()**

**Required System information**
- NODE version: v14.15.0
- NPM version: 6.14.8
- Strapi version: 3.6.8
- Socket version: ^4.4.1
- Database: PostgreSQL
- Operating system: Ubuntu 20.04

**Describe the bug**

according to the requirements given in Pub.dev, we are using a beta version. the following information is for an application that is currently being integrated with the socket:

Flutter Sdk version: v2.8.1
Dart Sdk version: v2.16.1
used pub version socket_io_client : v2.0.0-beta.4-nullsafety.0

Error log in terminal:

```
/root/agsat-agromart-admin/node_modules/engine.io/node_modules/ws/lib/websocket-server.js:340
throw new Error(
^

Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
at WebSocketServer.completeUpgrade (/root/agsat-agromart-admin/node_modules/engine.io/node_modules/ws/lib/websocket-server.js:340:13)
at WebSocketServer.handleUpgrade (/root/agsat-agromart-admin/node_modules/engine.io/node_modules/ws/lib/websocket-server.js:316:10)
at /root/agsat-agromart-admin/node_modules/engine.io/build/server.js:397:21
at Server.verify (/root/agsat-agromart-admin/node_modules/engine.io/build/server.js:127:24)
at Server.handleUpgrade (/root/agsat-agromart-admin/node_modules/engine.io/build/server.js:383:14)
at Server. (/root/agsat-agromart-admin/node_modules/engine.io/build/server.js:495:26)
at Server.emit (events.js:327:22)
at onParserExecuteCommon (_http_server.js:695:14)
at onParserExecute (_http_server.js:608:3)
```

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You
