### ISSUE TITLE
Lifecycle update a article

### ISSUE THREAD

**Issue by DCaiena** [strapi/strapi#13284]
### Required System information

- Node.js version:
- 16
- NPM version:
- 1.22.18
- Strapi version:
- 4.1.9
- Database:
- mysql
- Operating system:
- BigSur

### Describe the bug

I’m trying to give a update in the database but i am getting

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
this is a lifecycle file:

module.exports = {
async beforeUpdate(event) {
console.log(“aquiii”)
const entry = await strapi.query(‘api::article.article’).update({id: 4},{title:“cccccc”});
console.log(entry)
},
};

**Comment by WardenCommander** [comment]
Thats because you are using it wrong, you just created loop. This updates entry in collection type and it triggers lifecycle hooks: `strapi.query(‘api::article.article’).update({id: 4},{title:“cccccc”});`

`beforeUpdate(event) {
console.log(event)
event.params.title='ccccc':
} `

Something like this, check console.log output

**Comment by DCaiena** [comment]
it works great! thanks
