### ISSUE TITLE
The `populate=*` query param not working for `/me` endpoint

### ISSUE THREAD

**Issue by dimonenkov** [strapi/strapi#13296]
### Required System information
- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.1.10
- Database: SQLite
- Operating system: Linux

### Describe the bug

The `populate=*` query param for deep nested component fields is not working for `/me` endpoint.
For example, `users/?populate=*` or `users/1?populate=*`  are returning deep nested component relations but `users/me?populate=*` doesn't.

### Steps to reproduce the behavior
n/a

### Expected behavior

The `populate=*` query parameter should work for the `/me` endpoint, just like the other endpoints.

### Screenshots

n/a.

### Code snippets

n/a

### Additional context

n/a

**Comment by Nikoxx99** [comment]
Also noted this. I review the commit tests and see nothing for this endpoint. Maybe it's not planned to support population for it?

**Comment by derrickmehaffy** [comment]
confirmed on v4.1.10

**Comment by martinomg** [comment]
Here are some related threads
https://forum.strapi.io/t/populate-users-permissions-to-get-user-avatar/13701
https://forum.strapi.io/t/how-to-populate-users-strapi-v4/15353

How is severity determined? because this forces either to hard code the **/users/me/** endpoint (is not hard but it adds a different treatment for one specific file and endpoint to the code base) or to expose **/users/1** endpoint which in some designs is not desirable and even insecure. 

Thank you ✌

**Comment by fingeg** [comment]
Related issue with the user object in the response of the authentication process.
The response of `/auth/local` does not populate its content.
Don't want to make an additional request after a successful login, just to get the populated content.

**Comment by fingeg** [comment]
> How is severity determined? because this forces either to hard code the **/users/me/** endpoint (is not hard but it adds a different treatment for one specific file and endpoint to the code base) or to expose **/users/1** endpoint which in some designs is not desirable and even insecure.

I'm looking into fixing this error because I'd really need this to proceed with my project. Right now the `user/me` controller just returns the data of `ctx.state.user`.
1. We could either change the line where the `state.user` object is set, which would enable developers to access the populated data everywhere where the strapi object is available. But that also means that the user will always be populated.
2. Or we could just load the id from `ctx.state.user` and handle it the same way as the `user/:id` controller. (I think will be the cleaner solution, because populating can be controlled via the query attributes).

any thoughts?

**Comment by iamamjad** [comment]
Click on Settings and the User Role & Permission Plugin. Open any role and then click on Users-permissions
 plugin::users-permissions plugin. Go down and click on role check the find checkbox and save. Also, follow up the screenshot for more details.

Log in to the User and save the JWT token and then call the api/users/me?populate=* and put the JWT token in the Authorization tab in postman.

**Comment by iamamjad** [comment]
![image](https://github.com/strapi/strapi/assets/52481682/24e59c43-d585-492d-a0ab-c3c11cd3653f)

**Comment by memcaliber** [comment]
> ![image](https://user-images.githubusercontent.com/52481682/259001078-24e59c43-d585-492d-a0ab-c3c11cd3653f.png)
> 
> ![image](https://user-images.githubusercontent.com/52481682/259001237-544f2954-66d5-414d-9cfa-a0d555bce383.png)

Hi.. thanks for answer..
but this way not working anymore.. response from API not showing role by the user..

**Comment by Sydfg** [comment]
Tim_
