### ISSUE TITLE
BUG: Percona-XtraDB-Cluster requires primary keys

### ISSUE THREAD

**Issue by jonOreillyEasybell** [strapi/strapi#13455]
### Required System information

- Node.js version: v16
- NPM version: 8.5.5
- Strapi version: 4.1.8
- Database: Percona-XtraDB-Cluster
- Operating system: Docker image

### Describe the bug

Strapi v4 components with linked properties (relations) don’t work with Percona.

### Steps to reproduce the behavior

1. Setup strapi with a Percona-XtraDB-Cluster
2. Create a component with a property linked to a collection
3. Try to save a collection/singleton that uses that component
4. Saving fails with a `500 Internal Server Error`. In the logs there'll be an error that says: 
_error: insert into `components_utils_images_image_links` (`image_id`, `inv_image_id`) values (2, 5) - ER_UNKNOWN_ERROR: Percona-XtraDB-Cluster prohibits use of DML command on a table (strapi.components_utils_images_image_links) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER_

### Expected behavior

Saving correct data should not fail.

### Screenshots

<img width="643" alt="Screenshot 2022-06-03 at 13 30 17" src="https://user-images.githubusercontent.com/88373269/171845526-515e72f2-4348-4baf-9b79-353cc196546e.png">

### Additional context

Hi there, I've recently ran into this issue where Strapi and Percona don't work together. Strapi works fine with plain old Mysql servers but, since most of our systems are in Percona, I'd rather have it configured like the other projects. 

The issue seems to be that Percona requires primary keys for every table, and Strapi component-collection relations tables don't seem to have any:

```sh
select * from components_home_usps_image_links;
+--------+----------+
| usp_id | image_id |
+--------+----------+
|      1 |        1 |
|      2 |        1 |
+--------+----------+
```

I believe this could be solved by adding a primary key to these tables:

In [/packages/core/database/lib/metadata/relations.js -> createJoinTable](https://github.com/strapi/strapi/blob/0c14a069798989c4f6cd042806dfa3e8a598c6d2/packages/core/database/lib/metadata/relations.js#L396):

```js
metadata.add({
  ...,
  atributes: {
    id: {
      type: 'increments',
    },
    ...
  }
})
```

Please let me know if I should add more info or could help in any other way. I really like Strapi as our CMS :)

**Comment by derrickmehaffy** [comment]
@alexandrebodin I know you really wanted to avoid having primary keys on these joining tables but I think we might be forced into it, especially given the internal discussion we had the other day about possibly in the future saving some metadata on the relations too :thinking: 

I don't think it should be any breaking changes but we should already try I think, it shouldn't hurt the query logic at all but will stop these databases from complaining.

I believe the main reason the clustered DBs need them is for sync delay EG MariaDB Galera clusters do ID offsets for each node but it requires a primary key also so in a 3 node set:

- Node 1 uses IDs: 1, 4, 7, 10, ect
- Node 2 uses IDs: 2, 5, 8, 11, ect
- Node 3 uses IDs: 3, 6, 9, 12, ect

This way they can get away with multi-master writes without running into conflicts or race conditions because the IDs will never overlap.

**Comment by derrickmehaffy** [comment]
(@marcoautiero if you read this, we need Alex's input here even though it's assign to your squad as it involves the database layer design, it should be easy to implement but Alex would need to sign off on it I think).

**Comment by derrickmehaffy** [comment]
While we don't support Percona natively this will also happen in any "MySQL clone" database since MySQL, MariaDB, and Percona all fall into the same clone family and are drop in replacements for each other. Their clustering mechanism (except Galera) are all pretty much identical.

**Comment by bjoernbg** [comment]
@derrickmehaffy This issue is hitting us quite surprisingly here as well. I can't imagine that it is an actual design decision not to have primary keys on relations tables, so I guess it's more of an oversight at the time of the development. The cleanest solution would be to add primary keys (combined primary key over the foreign keys) to the relation tables. I don't see any drawbacks from this at all and it would enable us to use clustering feature, which is really important for high availability.

I've been looking into Strapi's source code but – lacking a solid understanding of how everything ties together – wouldn't know where to start changing things. It looks like relation `packages/core/database/lib/metadata/relations.js` might be the place, but I'm unsure what side effects to expect from changes there. Could you maybe point us into the right direction?

Thanks in advance!

**Comment by derrickmehaffy** [comment]
> > I've been chatting with the team and I believe we will add the primary keys but we just won't use them for anything. They are basically pointless to us from an application perspective which is why we never added them in the first place.
> 
> Thanks for the quick reply. I think that's a very good decision. Do you have any idea on when that change might make into a release (or at least a pull request that we could use as a patch)?

I don't have any idea, we just got back from a company onsite (since we are remote) in Portugal and quite a few of us got sick in the process so :sweat_smile: I'll have a chat with the team once we are all feeling a bit better to see if we have a timeline.

**Comment by jonOreillyEasybell** [comment]
Hi guys, any news about this issue?

**Comment by alexandrebodin** [comment]
@jonOreillyEasybell We have a fix in the working but still a few things to figure out (on Sqlite only) 

You could you patch-package to apply the fix if you want :)

**Comment by jonOreillyEasybell** [comment]
Sweet!! Thanks for taking care of this issue 😁

**Comment by derrickmehaffy** [comment]
FYI for @marcoautiero / @alexandrebodin we have an EE customer mentioning this also, feel free to ask the support team for more info or see internal TID1774

**Comment by alanko0202** [comment]
Hi all, I have the same issue with the MySQL HA cluster requirement. 
Do you have the target date for this release? or any workaround I could do? Thanks in advance.

**Comment by scottydev** [comment]
Just ran into this issue after upgrading from 4.4.3 -> 4.5.4. Followed the two migration guide callouts which appear to be minor (Favicon updated and the dup relationship fix didn't affect me). Using Digital Ocean managed MySQL instance. Has this issue been reintroduced to anyone else?

> FROM `mycomponent_components` a - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

**Comment by derrickmehaffy** [comment]
That's quite odd as we now create the PK's :thinking: and this was released in v4.3.7

**Comment by fabianmu** [comment]
This seems to be related. https://github.com/strapi/strapi/issues/15329

**Comment by jaccospelt** [comment]
It seems like an update of a record is creating a temp table to be able to set an order (see CREATE TABLE `orderTable_1672770043370_ea6288f21493ed0dd0c9c28764d90b04` in #15329). 
This temp table doesn't have a primary key and is causing the issue.

**Comment by derrickmehaffy** [comment]
> It seems like an update of a record is creating a temp table to be able to set an order (see CREATE TABLE `orderTable_1672770043370_ea6288f21493ed0dd0c9c28764d90b04` in #15329). 
> This temp table doesn't have a primary key and is causing the issue.

Ah ha, can you open a new issue as this is different than the original but indeed I bet that is the case.

**Comment by Marc-Roig** [comment]
@jaccospelt in 4.6.0 we are not creating that temporary table, could it be possible for you to update?

**Comment by jaccospelt** [comment]
Nice, upgrading to 4.6.0 fixes the issue! thanx!
