### ISSUE TITLE
Can't override admin panel pages

### ISSUE THREAD

**Issue by AlexanderPershin** [strapi/strapi#13523]
- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: 4.1.12
- Database: sqlite
- Operating system: ubuntu 21.10

I need to override default React components (pages) for admin panel, however I wasn't able to do that
I created directories structure:
src
│ 
*****
skip
*****
├── extensions
│   ├── admin
│   │   └── admin
│   │       └── src
│   │           └── pages
│   │               └── HomePage
│   │                   ├── ContentBlocks.js
│   │                   ├── HomeHeader.js
│   │                   ├── index.js
│   │                   └── SocialLinks.js
│   └── content-manager
│       └── strapi-server.js
├── index.js
└── plugins
Which should've reflected "strapi/packages/core/admin/admin/src/pages/HomePage/" path in repo
But no changes happened

For content-manager the simillar scheme worked perfectly - I overrode file strapi-server.js and everything worked, but I assume that was just an exception

### Steps to reproduce the behavior

1. Go to strapi repo
2. Copy one of core package's path
3. Create same path in <your project directory>/src/extensions/ directory
4. Copy some files to override from repo and make changes to them
5. Run npm run strapi && npm run strapi watch-admin
6. Observe no changes to components you've just override

### Expected behavior
Files you override should have effect on the project

**Comment by codeblooded47** [comment]
I followed the steps to produce this behavior.
There is no effect on admin panel pages.

I dig a little and found out strapiv4 override files `./src/admin/extension` but this is for logo and asset files.
I changed some of the line in `node_modules/@strapi/admin/admin/index.js` and i am  getting expected behavior.

![screen-capture](https://user-images.githubusercontent.com/71964230/173312971-714664c9-03fe-42ed-835d-e8890e1fae2e.gif)

**Comment by derrickmehaffy** [comment]
This is expected, you will need to use patch-package to modify admin pages in Strapi v4 as we got rid of the v3 extensions system.

**Comment by AlexanderPershin** [comment]
> This is expected, you will need to use patch-package to modify admin pages in Strapi v4 as we got rid of the v3 extensions system.

Hi,
I did as you say:
- modified files in node_modules
- ran `npx patch-package @strapi/admin`
Then I tried to deploy on heroku. In order to apply changes in production, I added `"heroku-cleanup": "npx patch-package"` script into my package.json. But when I'm trying to deploy app on Heroku, no changes are being applyed, though heroku output is:
```
remote: -----> Cleanup
remote:        Running heroku-cleanup
remote:        
remote:        > my-project@0.1.0 heroku-cleanup
remote:        > npx patch-package
remote:        
remote:        patch-package 6.4.7
remote:        Applying patches...
remote:        @strapi/admin@4.1.12 ✔
```
Did I do something wrong, or patch-package just won't work for heroku?

**Comment by derrickmehaffy** [comment]
You need postinstall to apply changes.

**Comment by AlexanderPershin** [comment]
> You need postinstall to apply changes.

That worked

Thank you

**Comment by Jahorse** [comment]
I'll just point out for anybody that comes across this that you can avoid the `patch-package` and `postinstall` dependencies by using yarn v2 or newer that has the `yarn patch` functionality: https://yarnpkg.com/cli/patch

**Comment by derrickmehaffy** [comment]
> 

Thanks for this, wasn't aware (still on yarn v1 like most of the Strapi team)

**Comment by wang00100** [comment]
666

**Comment by huy-lv** [comment]
> https://forum.strapi.io/t/customize-the-dashboard-welcome-page/939/35

why do you guys turn this off, I think this is must-have feature 😄

**Comment by AdrianFahrbach** [comment]
> This is expected, you will need to use patch-package to modify admin pages in Strapi v4 as we got rid of the v3 extensions system.

We're on Strapi v4.15.5-alpha-5 and it seems like this is not possible anymore, since the Strapi admin files are precompiled in the package.
@derrickmehaffy Is there still a recommended way to adjust the admin panel with custom components?

**Comment by dgrebb** [comment]
This was a soul-crushing realization for me as well in ~4.15.x..

**Comment by AdrianFahrbach** [comment]
> I want to change some components in the @strapi/plugin-upload plugin
> 
> 1. `npm i pack-package postinstall-postinstall`
> 2. `"scripts": { "postinstall":  "patch-package", ...   }`
> 3. I make changes to the component I need in `node_modules/@strapi/plugin-upload/admin/src/components`
> 4. `npx pack-package @strapi/plugin-upload` (I get the patches folder with the file @strapi+plugin-upload+4.15.4.patch)
> 5. `npm install npm run build npm run develop`
> 
> After the work done, I do not see any changes in the plugin on the UI

This used to work, but does not work anymore since the Strapi package now only contains [compiled JS](https://i.imgur.com/6VBDUN9.jpg).

---

We solved this problem by creating our own patching script that runs in post install and can be found [here](https://gist.github.com/AdrianFahrbach/c9099d8315085dd43cde6ad894d5aa5a). You can try adding that to your projects, but you will have to adjust the paths. Our setup is an NX monorepo where Strapi is located at `apps/cms` or respectively its dist folder at `apps/cms/dist/apps/cms`.

The script goes through every file in the admin chunks folder and replaces variables named like files in `src/admin/patch` with the default imports of those files. So basically this...

```js
[...]

const LeftMenu = () => {
  [...]
}

[...]
```

...gets replaced with this:

```js
import LeftMenu from `path/to/the/patched/file/LeftMenu`

[...]
```


In our case we replace the [LeftMenu](https://github.com/strapi/strapi/blob/ac7ce4ebf290dd6a6df5a7606f88108c216f4e6a/packages/core/admin/admin/src/components/LeftMenu.tsx#L59) so we got a `LeftMenu.js` in `src/admin/patch` that was modified a bit. Since we replace the variable with an import in a totally different location, all of the relative imports in our `LeftMenu.js` file won't work anymore, but should already be imported in the chunk. To make them work again, you have to combine them in a `CHUNK_IMPORT` import. So in our `LeftMenu` example change this:

```js
import { makeSelectModelLinks } from '../selectors';
import { foo } from '../bar';
```

to this:

```js
import { makeSelectModelLinks, foo } from 'CHUNK_IMPORT';
```

Our script adjusts those imports and creates a new file for each chunk where the variable was found (usually its multiple, don't ask me why) in `apps/cms/.strapi/dist`. The files in there are also the ones that later get imported in the chunk.

---

This is a very very sketchy solution, but we had to update to the latest Strapi version and at the same time have to keep our adjustments to the admin panel.

The obvious solution for this issue would be to not ship the admin panel compiled, so that patch-package will work again.
My preferred solution though would be to overhaul the extension system, since patch-package is a sketchy solution as well. Give us more injection zones and hooks!

**Comment by wkonecny** [comment]
@Jahorse when updating to 4.15.1, it will break. Very weird such a big change is in a `patch` version. It literally breaks a lot.

**Comment by Adaphath** [comment]
Another solution that is somewhat practically is to use patch-package on the files in the '_chunks' folder.
I am currently using it for the upload plugin and it seems to work pretty well.

**Comment by daan-ef2** [comment]
> Another solution that is somewhat practically is to use patch-package on the files in the '_chunks' folder. I am currently using it for the upload plugin and it seems to work pretty well.

Can you show me an example? 

This really sucks, we need some adjustments for a big client, like showing more 'displayed fields' in the relationship (key => value) and there is no way to patch-package this stuff in.

**Comment by Adaphath** [comment]
@daan-ef2 
In `node_modules/@strapi/admin/dist/_chunks` are all .js files for the front end of Strapi.
In `dist/cli.js` and `dist/cli.mjs` are the names for the used index.js files.

For example `index-ea5b8bc5.js`. Then you can edit the according file in `_chunks`.

Afterward you should see your changes in Strapi. Problem is, when updating Strapi your changes will be gone and you have to add them again
