### ISSUE TITLE
Hooks aren't called when uploading a file to an entity through the api

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#13558]
### Required System information

- Node.js version: 16
- NPM version: 8.3.1
- Strapi version:  4.1.12
- Database: mysql
- Operating system: debian

### Describe the bug

When uploading a file to an entity using `api/upload` the lifecycle hook `beforeUpdate` of the entity does not get called.

### Steps to reproduce the behavior

1. Create an entity with a media field
2. Create a beforeUpdate lifecycle for the entity
3. Upload a file using `/api/upload`
4. Hook does not get called

### Expected behavior

Hook should be called when uploading a file through the API.

### Note
The hook does work if uploading  a file through the admin dashboard

**Comment by derrickmehaffy** [comment]
I'll be honest here I don't even believe this is possible as the logic for how files are attached to entities doesn't even touch the entity which is why the lifecycle is never called. Lifecycles wrap the database queries ran not the Strapi model for them. In this case there are two tables for the upload plugin that control the files stored and the relational join table which is what gets updated and the actual entity tables never even get called.

I'll set this as an enhancement but I have a feeling once one of the product managers sees this it will likely get closed with a "won't fix"

**Comment by pcriadoperez** [comment]
Hi, thanks for the response.
The strange thing is it does work when uploading files through the admin dashboard.

Is that because it's using a different API?

**Comment by derrickmehaffy** [comment]
> Hi, thanks for the response. The strange thing is it does work when uploading files through the admin dashboard.
> 
> Is that because it's using a different API?

Yes there are admin specific APIs that involve the content-manager (thus admin-api) that aren't in the content-api (end-user apis).
