### ISSUE TITLE
Duplicate Item does not copy translations

### ISSUE THREAD

**Issue by rallisf1** [strapi/strapi#13584]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.12.1
- Strapi version: 4.2.0
- Database: MariaDB 10.6.8
- Operating system: Ubuntu 20 via WSL2 (Windows 10 x64)

### Describe the bug

When having an i18n enabled collection and you duplicate an item through the Content Manager it only copies the default language's translation.

### Steps to reproduce the behavior

1. Have an i18n enabled collection and multiple languages enabled
2. Create an item with multiple translations
3. Duplicate via the Content Manager list view
4. Save the new Item
5. Change the editing language, there's no data for any of the other languages

### Expected behavior

The purpose of the Duplicate function is to quickly create items that have little differences. In my book that includes translations.

### Additional context

There are 2 reasons this is not implemented:

1. It might not even be a bug, just how most people want it to work.
2. It is really hard to implement

First one can be solved by adding a true/false switch in the View Configuration of each Collection Type "Duplicate item translations".
The second one comes down to [not being able to distinguish a create from a duplicate](https://feedback.strapi.io/feature-requests/p/more-info-on-beforecreate-aftercreate-hooks), else it would be easy to implement using hooks.

**Comment by Matherss** [comment]
@rallisf1 hello, have u got any solution for your problem?

**Comment by rallisf1** [comment]
> @rallisf1 hello, have u got any solution for your problem?

No

**Comment by TofanIulian** [comment]
I ran into the exact same issue. 

Only the default language of the project gets cloned/duplicated

Any news on this?

### Steps to reproduce the behavior (with some pictures)
1. Have an i18n enabled collection and multiple languages enabled
2. Create an item with multiple translations
3. Duplicate via the Content Manager list view
![image](https://user-images.githubusercontent.com/38394308/202855900-1b9a45b7-c9e4-44f2-885c-6a5272b7e91e.png)

4. The clone's fields get populated with the values of the original entry but only for the default language. If we switch the default language to to any other language we would see that what I said holds true.
![image](https://user-images.githubusercontent.com/38394308/202856046-58f1e800-81c8-4359-8cce-a352d648fb75.png)

5. Furthermore if we click on the language selector from the right and select french we get redirected to a url that looks like nonsense to me, because there is no partner with id 3, like in the url to which I get redirected, but I think I digress at this point.
`http://localhost:1337/admin/content-manager/collectionType/api::partner.partner/create/clone/1?plugins[i18n][locale]=en`
![image](https://user-images.githubusercontent.com/38394308/202856323-8540f7c7-9cfe-40dc-ae77-a68a69144438.png)

`http://localhost:1337/admin/content-manager/collectionType/api::partner.partner/3?plugins[i18n][locale]=fr-FR`
![image](https://user-images.githubusercontent.com/38394308/202856367-a7bebb9a-3873-4577-9dd7-14ff5f4f7c5c.png)

Strapi version: 4.5.1

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/duplicate-item-does-not-copy-translations

Thanks!

**Comment by samMeow** [comment]
To who are looking for this feature, there is a temporary solution for that
Background:
Strapi treat different locale as different entity, so there will be N item for N locale for single entity.

To start with:
1. Duplicate the item you want to copy
<img width="1588" alt="Screenshot 2023-02-15 at 1 48 20 PM" src="https://user-images.githubusercontent.com/9334075/218943859-f6c08c05-f3f2-473e-9a59-311c2e3afdbb.png">
<img width="1515" alt="Screenshot 2023-02-15 at 1 47 56 PM" src="https://user-images.githubusercontent.com/9334075/218943876-3d235948-03f9-4d38-843d-abaedf6fdb4d.png">

Notice the path simply using `/create/clone/${id}`

2. Now go to the new created item, and select locale you want to copy
<img width="1515" alt="Screenshot 2023-02-15 at 1 47 56 PM" src="https://user-images.githubusercontent.com/9334075/218944429-c47e1006-33aa-4fbc-a70d-95f086bc53f4.png">

3. Type in the source locale you want to copy in url
in my case, the source entity for locale zhHK is 1728, while the related id for the new entity is 1765, same as above
<img width="1732" alt="Screenshot 2023-02-15 at 1 53 12 PM" src="https://user-images.githubusercontent.com/9334075/218944531-7f14da0e-e763-47ee-b2d0-363e251953ea.png">

This will simply load all data from the source entity and copy them to FE UI, after that you can simply press save
