### ISSUE TITLE
Cannot remove `strapi::public` and `strapi::favicon` middlewares

### ISSUE THREAD

**Issue by Sija** [strapi/strapi#13626]
## Bug report

Hi, I wanted to remove `strapi::public` and `strapi::favicon` middlewares (in production env), but it seems they're for some reason [defined](https://github.com/strapi/strapi/blob/85d79a1584312fdf19f68143bbb7da90691fe976/packages/core/strapi/lib/services/server/register-middlewares.js#L32-L33) as required.

### Expected behavior

I should be able to remove these.

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by Sija** [comment]
I don't know what else you need. Gist of the issue is that I'd like to disable/remove those, since (as far as I understand), they're being used for local uploads and displaying the index page - which we don't need, nor want.

**Comment by derrickmehaffy** [comment]
> I don't know what else you need. Gist of the issue is that I'd like to disable/remove those, since (as far as I understand), they're being used for local uploads and displaying the index page - which we don't need, nor want.

We consider these core and they are hard coded to throw errors if they aren't enabled. Neither of these two will be removed from being core and required as they are part of needed core functionality. You are welcome to use patch-package to modify the check if these are enabled but it's not something we will merge into the main code-base for everyone.

**Comment by Sija** [comment]
@derrickmehaffy I get you, and may I ask _why_ they're considered required?

**Comment by derrickmehaffy** [comment]
Well for public it serves our default landing page and is needed for the upload plugin which we consider core (meaning the plugin can't be uninstalled) thus it makes that middleware required.

Favicon is handles the favicon which throws console errors on some browsers if a favicon isn't set. Removing either of these doesn't really provide any benefit and more likely to just cause issues hence why we set them as required.

**Comment by derrickmehaffy** [comment]
We hardcode the required middlewares here: 

https://github.com/strapi/strapi/blob/d796cf93fae203233df23c870587622daf4cc08d/packages/core/strapi/lib/services/server/register-middlewares.js#L13-L34

**Comment by Sija** [comment]
> Well for public it serves our default landing page and is needed for the upload plugin which we consider core (meaning the plugin can't be uninstalled) thus it makes that middleware required.

Right, but what if we don't use the local uploader and **don't want** to display the landing page - since the installation is meant to an API only (aside of the admin that is)?

> Favicon is handles the favicon which throws console errors on some browsers if a favicon isn't set. Removing either of these doesn't really provide any benefit and more likely to just cause issues hence why we set them as required.

These errors are harmless, so why force the users to keep this middleware as required?

> We hardcode the required middlewares here:

I know, I linked it in the description :)

To be honest, these reasons doesn't sound to me like anything to do with the _core functionality_ - `public` is needed for local file upload and `favicon` is a nice-to-have creature comfort.

**Comment by derrickmehaffy** [comment]
We build Strapi for the main use cases that meet the needs of the vast majority of our users. As the upload plugin is considered core and disabling the public middleware will likely break things in unpredictable ways (such as not being able to serve the admin panel either) and because we don't want to write tests or fix bugs related to those core middlewares missing we consider them required.

As I've already mentioned, please feel free to modify your project as you see fit. Using something like patch-package gives you the ability to modify even deep core parts of Strapi.

We will not take this particular request on because it does not benefit and directly harms the vast majority of use-cases for our users.

Strapi is not an API framework, it's a headless CMS and while it does work as an API framework (I myself use it that way also) it's not what we are building, not where our focus is, and not what we will build features around.
