### ISSUE TITLE
Components part of a DynamicZone not getting assigned a unique id

### ISSUE THREAD

**Issue by MagnusFischer** [strapi/strapi#13679]
### Required System information

Node.js version: 16.15.0
NPM version: 8.5.5
Strapi version: 4.2.0
Database: postgres
Operating system: Ubunto 22.04

### Describe the bug

All of the components part of a DynamicZone gets an id of '1' from GraphQL endpoint

### Steps to reproduce the behavior

1. Make a dynamic zone
2. Add some components
3. Query the components through the GraphQL endpoint

### Expected behavior

Every component gets a unique ID assigned.

### Screenshots

<img width="1470" alt="Screenshot 2022-07-04 at 14 14 17" src="https://user-images.githubusercontent.com/88616365/177152652-26fcaa61-535e-454b-9878-cc399ea0ffd4.png">

**Comment by kasonde** [comment]
Hi @MagnusFischer the reason you see that is because like component records are stored in their own tables separate from the content type they are a child of. In the example you shared, you are querying a DZ which returns a list of unique components all with only 1 record. In the picture I've attached, adding more than 1 of the same component to the DZ, you see the ID increment. 

![image](https://user-images.githubusercontent.com/13610895/178785567-a8c16f3d-1b4e-47f5-917f-ce57dc163882.png)
