### ISSUE TITLE
Unable to add multiple oneWay Relations to the same model

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1374]
**Informations**
- **Node.js version**: v10.4.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: 10.1.29-MariaDB
- **Operating system**: Linux Mint 19 Beta (Ubuntu 18.04)

**What is the current behavior?**

Currently unable to add multiple oneWay Relations to the same model.

**Steps to reproduce the problem**

Create 1 model` `data`
Attempt to create a Model `joindata` with 2 oneWay relations to the model `data` using different "names"

In my example I tried to create 2 oneWay relations `primaryArtifact` and `secondaryArtifact`, the adminui will not let you add 2 oneWay relations as it says it is already in use:

![image](https://user-images.githubusercontent.com/8593673/41348957-2c085dfc-6ec3-11e8-8ac6-49187f64f812.png)

**What is the expected behavior?**

The AdminUI should not check for a "value" of the source of the oneWay relation.

**Suggested solutions**

Unsure.

**Comment by derrickmehaffy** [comment]
Related PR: https://github.com/strapi/strapi/pull/1199

@okaris maybe you can provide some context, I don't believe this is intended. So long as the value of the field name on the left is different between them? Thats where the check should happen as to if the `value` already exists

**Comment by derrickmehaffy** [comment]
Manually adding the oneWay relation to the model settings file did add it, thus the issue is with the adminui:

![image](https://user-images.githubusercontent.com/8593673/41349421-b263ddb2-6ec4-11e8-8c38-3fd2917a07a5.png)

**Comment by okaris** [comment]
The version of strapi where I tested this did not yield any errors like this. Indact I was and am still able to create multiple oneWay relations from admin ui. Maybe this is a check that was introduced later. But I remember checking the part where “-“ registered as a field in target model and disabled that. 

https://github.com/strapi/strapi/blob/ae29802c07e3d8f00bb9849df2cd657caf619cba/packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js around line 216 you should see the conditional. 

I might have overlooked some other place that checks and creates this since I am mot fully experiences on the whole strapi framework.

**Comment by soupette** [comment]
To solve the issue you need to add the following  in this [file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-type-builder/admin/src/containers/Form/utils/attributeValidations.js).

```
const sameParamsKey = filter(this.props.contentTypeData.attributes, (attr) =>
   // add this check
    attr.params.key !== '-' && attr.params.key === this.props.modifiedDataAttribute.params.key && attr.params.target === this.props.modifiedDataAttribute.params.target);
```

Then, it should be working

**Comment by johannpinson** [comment]
and what about a "manyWay" relation type? 😃

**Comment by derrickmehaffy** [comment]
@johannpinson trust me I have a reason 😆 There is a means to my madness.
