### ISSUE TITLE
Types Auto-Generation outputs duplicates in type-names

### ISSUE THREAD

**Issue by FieldMarshallVague** [strapi/strapi#13742]
### Required System information

- Node.js version: 16.14.2
- YARN version: 1.22.0 Yarn
- NPM: 8.7.0 
- Strapi version: 4.3.0.beta-2
- Database: postgres
- Operating system: win 10 64 pro

## Bug report

Regarding the latest 4.3.0.beta-2, specifically this PR: https://github.com/strapi/strapi/pull/13460

I've run the following command to generate types and it successfully generates a schema.

```
yarn  strapi content-types:generate-types --verbose -o ./strapi-types
```

However, the type declaration looks like this, where the name of the type is repeated.  This is the case for all collections and single types (anything with the 'api::' prefix has its name duplicated, but components and built-in plugins do not).

```
export interface ApiWhoWeAreWhoWeAre extends SingleTypeSchema {
  info: {
    singularName: 'who-we-are';
    pluralName: 'who-we-ares';
    displayName: 'Who-we-are';
    name: 'who-we-are';
  };
  options: {
    increments: true;
    timestamps: true;
    draftAndPublish: true;
  };
  attributes: {
    pageBasics: ComponentAttribute<'pages.page-basics'>;
    createdAt: DateTimeAttribute;
    updatedAt: DateTimeAttribute;
    publishedAt: DateTimeAttribute;
    createdBy: RelationAttribute<
      'api::who-we-are.who-we-are',
      'oneToOne',
      'admin::user'
    > &
      PrivateAttribute;
    updatedBy: RelationAttribute<
      'api::who-we-are.who-we-are',
      'oneToOne',
      'admin::user'
    > &
      PrivateAttribute;
  };
}
```

The namespace object looks like this:

```
      'api::article.article': ApiArticleArticle;
      'api::blog.blog': ApiBlogBlog;
      'api::case-study.case-study': ApiCaseStudyCaseStudy;
      'api::category.category': ApiCategoryCategory;
      'api::culture.culture': ApiCultureCulture;
      'api::customer-story.customer-story': ApiCustomerStoryCustomerStory;
      'api::diversity-and-inclusion.diversity-and-inclusion': ApiDiversityAndInclusionDiversityAndInclusion;
      'api::event.event': ApiEventEvent;
      'api::faq.faq': ApiFaqFaq;
      'api::feature.feature': ApiFeatureFeature;
      'api::get-in-touch.get-in-touch': ApiGetInTouchGetInTouch;
      'api::guide.guide': ApiGuideGuide;
```

So, it looks like it's concatenating the values either side of the '.'.  I don't know if my structure here is a special case, but I used the codemods tool to migrate from V3 (latest).

I would expect the output to only contain a single instance of the type name.  but it's possible it's doing its job properly and the names of the types were set up wrong?  

I'm not sure if I can just go through and fix these manually, or if will break the DB in some way (or if this is just the auto-gen having a bug of some king).

If you could give me a steer, that would be great.

**Comment by Convly** [comment]
Hello, thanks for posting this issue :slightly_smiling_face: 

Content types/Schemas are identified by 3 things:
- their "source" (`api`,` plugin`, `strapi`)
- the API's name it's related to (except for those whose source is `strapi`)
- the actual name of the schema

The main thing to note here is that you can have multiple models defined for a single API (`src/api/{api-name}`).
It basically means that for a given `restaurant` API you could have for example 2 models defined: `restaurant` and `menu`.
Their UID would be `api::restaurant.restaurant` and `api::restaurant.menu`.

When creating new content types from the content-type-builder in the admin, it usually creates a dedicated API for each model, hence the repetition in the names.

In the end, what it means is that the behavior you've noted `is` the expected one. While I agree it's not particularly aesthetics to have long names repeated two times, we need this in order to attribute a unique identifier for each type.

One possible solution could be to go from:

`api::restaurant.restaurant` => `ApiRestaurantRestaurant`
`api::restaurant.menu` => `ApiRestaurantMenu`

to

`api::restaurant.restaurant` => `ApiRestaurant`
`api::restaurant.menu` => `ApiRestaurantMenu`

but then we would lose consistency in the type names :confused: 

Please, do not hesitate to share if you've an idea or a take on this :slightly_smiling_face:

**Comment by FieldMarshallVague** [comment]
I see.  Thank you so much for giving a thorough response :)

It's a good question.  I can see the issue, but was unaware that an API could have two models.  Could you possibly give a psuedo code example of the url/query that would request the menu from the restaurant api?

**Comment by FieldMarshallVague** [comment]
Ah, I see.  Thanks for the insight.  I was coming from using 'STS' plugin, which just exported clean TS types ready for consumption, so I guess I had unrealistic expectations :)

OK, I think I see a way forward (even if it's not the one I was hoping for).  do you happen to have a link to usage of the GetAttributeValues?  I can't find anything with google search.

**Comment by FieldMarshallVague** [comment]
Ok, thanks for the heads-up.  I'll factor that into my solution.  It does look like there's no point creating a temporary fix for the complex names/nesting right now, just have to map them in code/service of some kind.

Thanks, that was really good to get a quick and clear response!  Very helpful :)

**Comment by Convly** [comment]
> Ah, I see. Thanks for the insight. I was coming from using 'STS' plugin, which just exported clean TS types ready for consumption, so I guess I had unrealistic expectations :)

It'll be available at one point, interested to look at some of the things you like regarding type generation in order to have more points of comparison.

> OK, I think I see a way forward (even if it's not the one I was hoping for)

Don't hesitate to share your ideas in case other users are looking for that too 

> do you happen to have a link to usage of the GetAttributeValues? I can't find anything with google search or in Discord.

It's unfortunately not documented yet, I'll probably add some documentation for that before the stable release (`4.3.0` late July)

Regarding usage, something like that should do the job
``` typescript
import { GetAttributesValues } from '@strapi/strapi';

type Restaurant = GetAttributesValues<'api::restaurant.restaurant'>;

const restaurant: Restaurant = {
  // ... 
}

```

The last thing I wanted to add to the conversation is that the feature we're releasing is "TypeScript support". The plan is to support users wanting to create projects file and/or plugins in TypeScript and be able to load them into Strapi.
Providing typings for Strapi and for schemas as well as automatically generating them was not planned and it's been some bonus work I've done essentially in my free time, I do know it's not perfect and a lot of our core APIs typings are missing, but it'll come over the releases and we can't wait to work on that with the community's help.

**Comment by Convly** [comment]
Glad I was able to give you some help, good luck with your implementation!

I'll mark this issue as closed as the initial bug is the wanted behavior :slightly_smiling_face: 

Have a nice day!

**Comment by FieldMarshallVague** [comment]
Thanks, that last example is a massive time-saver.  Cheers, I'll feedback how I go.

**Comment by FieldMarshallVague** [comment]
So, I've made a bit of progress, it turns out I was missing '[0]' from the reference.  But now it looks like there is some sort of bug in the type generation.  I'm getting 'never' types for some of my properties in the type returned from GetAttributeValues:

```ts 

import { Strapi4Response } from '@nuxtjs/strapi/dist/runtime/types'
import { GetAttributesValues } from '@strapi/strapi'
import { ApiHomePageHomePage } from 'my-types'

type HomePage = GetAttributesValues<'api::home-page.home-page'>

const { find } = useStrapi4()
const page = await find<Strapi4Response<ApiHomePageHomePage>>('home-page', {
  populate: '*',
})

const attrs: HomePage = (page.data[0] as ApiHomePageHomePage).attributes

const home: HomePage = {
  heroUnit: '[is a never]',   //<-- this property type is 'never, so can't be assigned'
  featuredReviews: [],        //<-- this one isn't and seems to be the type I'd expect.
}
```

The type 'HomePage' is:

``` ts 

type HomePage = {} & {
    heroUnit?: never;
    pageBasics?: never;
    featuredReviews?: GetAttributesValues<"api::review.review">[];
    createdAt?: string;
    updatedAt?: string;
    publishedAt?: string;
    createdBy?: GetAttributesValues<...>;
    updatedBy?: GetAttributesValues<...>;
}

```

**Comment by FieldMarshallVague** [comment]
Just to round-off the thought process in this issue, the outstanding problem of components not being assigned 'never' type was due to the components having no value assigned in their displayName property (in strapi content-type builder).
