### ISSUE TITLE
[BUG] - Local provider does not allow users to login

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#13817]
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: 4.2.3
- Database: PostgreSQL
- Operating system: MacOS Monterey 12.4

### Describe the bug

When users try to log in with the local provider, using email and password information, the login never results in a success and the response does only indicate following error: "Invalid identifier or password, although both parameters are correct.

#### Steps taken before opening this issue

- I have ensured that the saved email matches my input. 
- Created a sample login function which worked just fine
- Created a new user and set a password, then I have copied the encoded password from the database and ran `bcrypt.compare(hash, "CLEAR_PASSWORD")` and it resulted in a truthy value.

### Steps to reproduce the behavior

1. Send a request with the correct login information to `POST /auth/local`
2. Receive above error

### Expected behavior

Users should be able to login, given the fact that both authentication parameters are equal to what is saved in the database.

**Comment by fabio-nettis** [comment]
# Following up on above issue

Login for users using the local provider does still not work. So I have created my own login function that just works completely fine. I still cant explain why the users-permissions plugin wont let login any users.

## Custom Implementation

For anyone encountering the same issue and without any way of resolution, here is an example how you could implement a login function yourself.

```javascript
const { v4 } = require("uuid");

const includes = {
  http: "api::http.http",
  entity: "api::authentication.entity",
  jwt: "plugin::users-permissions.jwt",
  roles: "plugin::users-permissions.role",
  users: "plugin::users-permissions.user",
  passwords: "api::authentication.password",
};

async login(ctx) {
    try {
      const { http, jwt, users, passwords, entity } = includes;
      const { identifier, password } = ctx.request.body;

      if (!identifier || !password) {
        return ctx.unprocessableEntity("Missing identifier or password", {
          type: "auth.error.body.missing",
        });
      }

      const user = await strapi.db.query(users).findOne({
        populate: ["profile", "profile.avatar"],
        where: {
          $or: [{ email: identifier.toLowerCase() }, { username: identifier }],
        },
      });

      if (!user) {
        return ctx.notFound("There is no user with this identifier", {
          type: "auth.error.user.not-found",
        });
      }

      if (!user.profile) {
        return ctx.preconditionFailed("This user is no longer active", {
          type: "auth.error.user.inactive",
        });
      }

      if (!!user.profile.locked) {
        return ctx.unauthorized("No permission to access this resource", {
          type: "auth.error.user.locked",
        });
      }

      if (!user.password) {
        return ctx.preconditionFailed("User is missing a password", {
          type: "auth.error.user.password-missing",
        });
      }

      const valid = await strapi
        .service(passwords)
        .validatePassword(password, user.password);

      if (!valid) {
        return ctx.unauthorized("Invalid password provided", {
          type: "auth.error.user.password",
        });
      }

      ctx.status = 200;
      ctx.body = await strapi.service(http).response(v4(), {
        jwt: strapi.service(jwt).issue({ id: user.id }),
        user: await strapi.service(entity).sanitizeUser(user, ctx),
      });
    } catch (err) {
      return ctx.internalServerError(err.message, {
        type: "auth.error.unknown",
      });
    }
  }
```

**Comment by fabio-nettis** [comment]
@kasonde Yeah sure, here you go:

![Screen Shot 2022-07-21 at 16 26 06](https://user-images.githubusercontent.com/36916632/180238794-bb67b93b-4933-4915-8367-82d198415a58.png)

As I have stated above I have validated that this is really the users password, that the hashed string in the database actually resolves to a truthy value when compared with bcryptjs.

**Comment by fabio-nettis** [comment]
As I cannot reproduce this behaviour anymore after upgrading to v4.3.x I will close this issue for now.

**Comment by Sefibrah** [comment]
Upgraded from Strapi **4.5.3** to **v4.7.0-beta.0**, and the error still persisted...

Hey @fabio-nettis, I've encountered the same issue as you, where my login endpoint simply don't allow me to login, even though I have perfectly provided the identifier and the password.

How I managed to "reproduce" this silly bug is as follows:

In my bootstrap function I wanted to do 4 things:
1. Generate 4 additional roles in ```plugin::users-permissions.role```, such as ADMIN and other roles, in case the roles aren't already generated.
2. Clear all permissions that have been assigned to any and every role, including the Authenticated and Public roles.
3. Re-generate all permissions for each role for every content-type
4. Generate a single ```plugin::users-permissions.user``` and assign it the ADMIN role. Here's how I create him:
```
// src/index.js

const createAdminUser = async (role) => {
  let admin = await strapi
    .query("plugin::users-permissions.user")
    .findOne({ where: { email: { $eq: "admin@strapi.io" } } });
  if (!admin) {
    return await strapi.query("plugin::users-permissions.user").create({
      data: {
        username: "Admin",
        email: "admin@strapi.io",
        confirmed: true,
        provider: "local",
        password: "strapiPassword",
        role,
      },
    });
  }
  return admin;
};

module.exports = {
  //...
  async bootstrap(/*{ strapi }*/) {
    //...
    const admin = await createAdminUser(adminRole.id);
    console.log("admin: ", admin);
  }
}
```

And when I try to login into this user, I get the error. Now you may think that my permissions for the Public role were "accidentally" deleted, but I've regenerated the permissions for every single role, including the necessary permissions for the ```plugin::users-permissions.auth``` methods such as ```connect```, ```callback```, and ```register```.

But even then, it's like my Strapi CMS didn't care...

What was **interesting** is that when I went to the Strapi's Content Manager for the User content-type, and opened the list of users, then went to my admin user (admin@strapi.io), and re-wrote the same password which is "strapiPassword", and Saved him, the **error went away**.

And what is even **more interesting** is that when I changed "admin@strapi.io" to "admin@strapi.ioo", via the Strapi's Content Manager for the User content-type, the **error persisted**.

So maybe the issue is with the password? 

And also @fabio-nettis, I used your code snippet, and it was very very very useful indeed! If you feel like you could share more of your authentication API, it would be of extreme great benefit. If not, you have already helped me a bunch!!!

**Comment by hhmx** [comment]
Hello, I have the same problem again, even with the latest version. 🚨
Is this really a bug? 🤔

https://forum.strapi.io/t/login-api-status-400-user-cannot-be-found/32520
