### ISSUE TITLE
i18n locale option is not working in custom plugin content-types

### ISSUE THREAD

**Issue by saifullahakhtar** [strapi/strapi#13836]
I’m developing a plugin and want i18n locale options enabled in my Plugin content-types. When I try to add the code below to my Custom Plugin content-types schema, I get this error “Cannot read property ‘routes’ of undefined
TypeError: Cannot read property ‘routes’ of undefined”.

“pluginOptions”: {
“i18n”: {
“localized”: false
}
},

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by ReactNativeBlog** [comment]
This the same issue. Starter ist not running with typescript
https://github.com/strapi/starters-and-templates/issues/60

**Comment by webhype** [comment]
It seems like the objective of Strapi contributors here is mainly to just shut down the question rather than helping. Is there a workaround for this? The Starters are kind of the "calling card" of Strapi, and if they don't work, that looks (and is) really bad. I know, everyone is overworked and underpaid but... at least take the problem seriously, please, and don't dismiss it based on formalities. Fact is, the starter, as published, doesn't work for TypeScript.
