### ISSUE TITLE
Add Microsoft to Auth Provider

### ISSUE THREAD

**Issue by brandonbuttars** [strapi/strapi#1385]
**What is the expected behavior?**

It would be good to be able to accept Microsoft as an Auth Provider since Google is accepted.  I'm not sure where to start and am afraid I'd bugger up the code.  Is there anyone else interested in this?  We use Microsoft Office 365 for everything at work, we use to use Google.  I wanted to try and use Strapi for an internal project we're putting together.  I saw the latest Purest package has Microsoft in it's list of providers.

**Comment by lauriejim** [comment]
Hello @brandonbuttars , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

You can check how work `strapi-plugin-users-permissions`. We use `Grant` for authentication.
You can also check how we set actual providers here https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/functions/bootstrap.js

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by synth3tk** [comment]
As soon as #1568 gets fixed I'll work on it, since I was planning on adding another provider anyway.

**Comment by derrickmehaffy** [comment]
@synth3tk I am interested to see how you add one, after you have, I believe I have one to add as well.

**Comment by synth3tk** [comment]
@brandonbuttars PR #1613 has been submitted. While we wait on the Strapi team to give it a glance, could you possibly try it yourself to make sure it works the way you expect it with your org? I used an Office 365 dev instance, but I'm not sure if there's any difference with it.
