### ISSUE TITLE
"Fill in from another locale" is leaving the save button disabled

### ISSUE THREAD

**Issue by nimajneb** [strapi/strapi#13988]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: SQLite
- Operating system: macOS Monterey v12.2

### Describe the bug

Using the "Fill in from another locale" feature leaves the Save button in disabled state, as if the entry was unchanged. The values however are correctly copied.

### Steps to reproduce the behavior

1. Create a localized version of an entry and save it with any values.
2. After saving, click on 'Fill in from another locale' and select the source locale.
3. Try to save the entry.

### Expected behavior

The save button should be enabled.

**Comment by gracebir** [comment]
@nimajneb , is this happen in admin part ?

**Comment by nimajneb** [comment]
@gracebir yes, admin interface, in the content manager to be precise.

**Comment by gracebir** [comment]
@nimajneb , on my hand I am not able to reproduce this issue, could you make a video please?

**Comment by bolg55** [comment]
I'm also not able to reproduce this issue. A video would be most helpful. Thanks!

**Comment by nimajneb** [comment]
@gracebir @bolg55 Sure, here you go!

https://user-images.githubusercontent.com/1129950/184303422-457fe472-864c-41e3-8a56-38adcfc08d03.mov

**Comment by bolg55** [comment]
Ok, thank you @nimajneb this is helpful. So I believe this is due to a UID collision behind the scenes. See my brief video: 

https://user-images.githubusercontent.com/43022248/184404133-5ae706e5-9a47-4d79-8c31-7329819cc7b7.mov

It's also worth noting, that if you just skip the step where you name and save your second entry after switching locales, and go directly to "Fill from another locale", you won't encounter this issue.

**Comment by derrickmehaffy** [comment]
Looks like it doesn't detect that the content was changed. :+1: thanks for the video!

**Comment by Martin-Eckleben** [comment]
Even worse it says updated seconds ago but is not updated.
Reloading the page shows the old entry.

**Comment by ronronscelestes** [comment]
hi @nimajneb thank you for bringing up this issue!
it is caused by the way `i18n` and the `content-manager` work together - the `content-manager` is not supposed to know anything specific about `i18n`.
when we edit an entry localized with _"fill in from another locale"_ the state of the cm is overwritten, which causes the cm to lose its `initialData` making it then impossible to watch for differences with `modifiedData`.
I will open a draft PR with a proposition to temporarily fix this issue and then discuss it with the team :)
