### ISSUE TITLE
Typescript service typing doesn't allow addition of custom services

### ISSUE THREAD

**Issue by Bassel17** [strapi/strapi#14035]
### Required System information

- Strapi version: `4.3.2`

### Describe the bug

Typescript service typing doesn't allow addition of custom services, when adding a new service such as follows:

```ts
import { factories } from '@strapi/strapi'; 

export default factories.createCoreService('api::something.something', ({strapi}) =>  ({
  // Method 1: Creating an entirely custom service
  async exampleService(...args) {
    let response = { okay: true }

    if (response.okay === false) {
      return { response, error: true }
    }

    return response
  },
}));
```
It throws a typing error as follows:

![image](https://user-images.githubusercontent.com/37274596/183643267-573ffddf-432e-4b72-8755-931c99915839.png)

### Expected behavior

Should work and not throw an error

**Comment by emahuni** [comment]
apparently there must have been a regression, this is no longer working.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/7290508/190141525-59f316e2-698d-4dd3-beb4-000422b80cc7.png">

I was on Strapi 4.3.6, and now on 4.3.8 and in both versions it didn't work properly.

This removes that error, but then introduces the another one

<img width="976" alt="image" src="https://user-images.githubusercontent.com/7290508/190141818-5f9e026a-4f32-4e4c-a382-c2c37f562f56.png">

<img width="1827" alt="image" src="https://user-images.githubusercontent.com/7290508/190141927-a73fcff7-3c3e-45d0-8a60-3baaa27097c9.png">

If I change the GenericService type to this it works:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/7290508/190142093-60a582d7-bb3e-4c59-aaab-47c2d18e9de7.png">

from this: 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/7290508/190142203-7afc8461-308e-459c-ac1b-e6784ceca462.png">

notice `any` instead of `T` as the return type

**Comment by emahuni** [comment]
even the code in this issue doesn't work

**Comment by emahuni** [comment]
putting any as the return type completely fixed the issue such that this works without a problem:

```ts

export type GenericService = Partial<Service> & {
  [method: string | number | symbol]: <T = any>(...args: any) => any;
};

export default factories.createCoreService('api::something.something', ({ strapi })  => {
  return {
    // service functions or properties here
    async someFunction (a: number): Promise<number[]> {
      return [1, 2, 3];
    },
  };
});

```

**Comment by saintego** [comment]
@emahuni how did you change GenericService without editing factories in lib? Without it I have error on createCoreService

**Comment by emahuni** [comment]
I created my own typings file then added that type 

```ts
export type GenericService = Partial<Service> & {
  [method: string | number | symbol]: <T = any>(...args: any) => any;
};
```
If you put this directly in the file you're using this it'll still work, putting it into a separate typings file makes it cleaner and reusable.
