### ISSUE TITLE
Api User

### ISSUE THREAD

**Issue by Caravus** [strapi/strapi#141]
In http://studio.strapi.io/#!/api-builder/create-template
Name: User
(Next step, Generate the API)
Error:

> API `User` already exist

But on http://studio.strapi.io/#!/apis

> Your application has no APIs yet!

**Comment by Aurelsicoko** [comment]
Strapi provides a complete user management system by its own. You can't update this default API through the Studio. That's why, you can't see it.

For more details, [check out the documentation](http://strapi.io/documentation/users).

**Comment by Caravus** [comment]
So we have an API and a "default API"? Why?

**Comment by Aurelsicoko** [comment]
Strapi has some "default" APIs (or pre-developed) such as User, Email, Upload. These APIs can be manually removed by deleting them in your app's directory. Without these APIs, the administration panel cannot work. Then, these APIs are very common to each project. That's why we decided to add them automatically when you generate a new project.

**Comment by gonzalomass** [comment]
Explanation sounds logic and fair to me.

I mean, a default user API? Hell yeah! Thanks!

**Comment by Aurelsicoko** [comment]
> Without these APIs, the administration panel cannot work. 

You can't update these API through the Studio to avoid the risk to crash your app or to break the administration. This is a security precaution. We are open to discussing this choice. Should we allow an update to these API, through the Studio? What is your opinion on it?

PS: The Studio will no longer exist, don't forget to take a look at our blog. What we call the "API Builder" will become a plugin which will be hosted on your machine.

**Comment by Caravus** [comment]
I'm sorry that take up your time, but I thought it was strange. We have a special tool for editing API, which ... we can not edit API?
What is the fear to break the system? I can not fix it?
You can add a note that "this API is needed for the administrative part, be careful", but it seems strange to such a limitation of action.

**Comment by Aurelsicoko** [comment]
Don't worry, it is always a pleasure to speak about Strapi!

The reason is pretty simple. Most of our users on the Studio are beginners. They use it to prototype their app without writing any single line of code. That's why, we decided to limit the scope of actions on the "API builder". We don't pretend to have made the right decision on this part. Your feedback is very interesting!

As you said, a visible warning could be a great alternative! @gonzalomass, what is your opinion on this?

**Comment by gonzalomass** [comment]
Yeah, throw a visible and clear warning. 

I have a few months without messing with strapi but, isn't it true the you can edit the user API? I mean, it is not among the APIs that you create but you still can edit it, right?

**Comment by Aurelsicoko** [comment]
@gonzalomass: Yes, you can edit the `user` API by making changes in the `/api/user/**/*.js` files. The Studio does not provide this option but Strapi is just a set of files hosted on your computer.
