### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by hsnbsst** [strapi/strapi#14102]
When you enter two different collections in the admin panel, it gives this error, only 2 of them do it, the others do not have such a problem, they cannot bring the content.

Restarting node js fixes it

TypeError: Cannot read properties of undefined (reading 'reduce')
![Ekran Resmi 2022-08-15 09 36 57](https://user-images.githubusercontent.com/25246736/184588154-8a12671c-8b63-4ff7-beba-e504e2e29a19.png)

- Node.js version: 14.20.0  
- NPM version: 6.14.17
- Strapi version: v3.6.10
- Database: mysql
- Operating system: server

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports for v3 unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You
