### ISSUE TITLE
Crash in the admin panel if the i18n default locale is not set

### ISSUE THREAD

**Issue by fdel-car** [strapi/strapi#14313]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: PostgreSQL 14.3
- Operating system: macOS Big Sur

### Describe the bug

We're getting `TypeError: Cannot read properties of undefined (reading 'code')` on the create or edit content type page, if the default i18n locale is not set.

### Steps to reproduce the behavior

1. Create and launch strapi app
2. Remove the `plugin_i18n_default_locale` row in the `strapi_core_store_settings` table in your database
3. Go to the content manager and try to edit or add any content type
4. See the error mentioned above

### Expected behavior

I would expect strapi to ignore this missing data. Or try to fill this data with `"en"` for instance if it needs it.

### Code snippets

I'm pretty sure that [this kind of access](https://github.com/strapi/strapi/blob/d982d6470e755c37cc49545ea7dce6c2c0fe9f79/packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/index.js#L21) are responsible for the crash, the return value of a `.find` can be undefined.

### Additional context

I did not stumble into this while messing around with the database, I was migrating a project from v3 to v4 and this crash happened. The cause was the absence of the value mentioned above, I'll also create an issue in the [`migration-scripts`](https://github.com/strapi/migration-scripts) repository cause it needs to be fixed here as well.

### Workaround

If it happens to you, it's really easy to fix, just go to `Settings` > `Internationalization`, and from there just set to default the locale you want.

**Comment by ronronscelestes** [comment]
hi @fdel-car 

indeed the front crashing is coming from
```js
const currentLocale = get(query, ‘plugins.i18n.locale’, defaultLocale.code);
```
but a default locale should always be defined, so the front shouldn’t act on it or let a user create an entry without it!
I talked with @petersg83 to understand how the backend works on that side:
In `packages/plugins/i18n/server/services/locales.js` there’s already a default initialisation of a default locale
```js
const initDefaultLocale = async () => {
 const existingLocalesNb = await strapi.query(‘plugin::i18n.locale’).count();
 if (existingLocalesNb === 0) {
  await create(DEFAULT_LOCALE);
  await setDefaultLocale({ code: DEFAULT_LOCALE.code });
 }
};
```
that should make sure there’s always a default locale

since we think we shouldn’t act on a manually created bug (e.g. deleting manually a row in a db table) the only thing we should address is the migration issue
so as you said this seems to be more of a migration script issue that should be handled there 😊

let me know what you think, I'll close this issue after that if that sounds good to you!

**Comment by ronronscelestes** [comment]
closing it now, don't hesitate to reopen it if you think it's needed @fdel-car 👀
