### ISSUE TITLE
Auto generate Field values.

### ISSUE THREAD

**Issue by AxeemHaider** [strapi/strapi#14414]
Sometimes you want to generate auto field values based on other fields value. Here is a great example to generate auto slug for articles. [Auto Generate Slug field value](https://www.youtube.com/watch?v=Vul-0gsmINg)   
But problem with this is it is only generated when you click on save button. Think users wants to see auto generated field value and want some updates init before saving. 

**Use case:**

For example you have to fields, `name` and `slug`. Slug is generated base on name value but user can also edit the slug field. 
![strapi-screenshot-1](https://user-images.githubusercontent.com/27768863/190082908-efabd723-ed27-40d5-a0e2-be7f154a8f6b.png)

Let suppose everytime user want to append some number at the end of slug, lets say at this entry user want to append **1234**  
If you use **lifecycles hooks** `beforeSave()` as described in this [video](https://www.youtube.com/watch?v=Vul-0gsmINg)  

1. You first have to save the entry, it will run the lifecycle hook `beforeSave` and generate slug
2. Then you have to edit this entry and update the slug (assume slug field is writable)

**Problems with this approach**  

1. You have to double work, first you have to save then you have to update.
2. User not able to see what slug was generated until he/she save the entry. Sometimes you want to see the result before saving. 
For example you are entering student marks data and you want calculate Grade based on these marks, but you also want to see what Grade that student got before saving. There is no way you can do that, First you have to save to run the lifecycle hook and then you can see the grade field which value is auto generated by lifecycle hook. 

There are many other cases when you want to set field values based on other field value. And lifecycle hooks not generate values at real time. 

For this I created a **PR**.  
Now you can update fields values based on other field values.  

**How to use**
You have to define the set value method for your field and you can write custom logic in this method to generate field value.

```js
// src/api/content-types/[name]/schema.json

"attributes": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "string",
      "setValue": "values => values.name ? values.name.replaceAll(' ', '-').toLowerCase() : ''"
    }
  }
```

In `setValue` you can write custom login to generate value. Here I'm generate `slug` value based on name (lowercase and replcae space with -) You can write your on logic. And you can see slug generation on as you type.  

**Note: `setValue` take string instead of plain simple method, this is limitation from Strapi**
  

**For Strapi Developer**
I'm taking `setValue` as a string because we can't pass method in it, because we are using redux state to store `content-types` schemas so we can't store method inside redux state.  
The second thing is we are using request method to load content-type schema and then save it in redux state It will not possible to fetch method with request and use it later. 

Right now I'm using `eval` to convert that string into method, which is not a good way I think but this is only way right now. If somehow we are able to access `strapi.getModel()` or directly `content-types` schemas in `admin` it will be great.

**Comment by ronronscelestes** [comment]
hi @AxeemHaider 
let me know if I understood well your use-case but I think what you are looking for is the UID field:

https://user-images.githubusercontent.com/71838159/191458226-f1a4bee9-2c30-44a2-8f06-61e80a4b16c8.mov

after discussing it with the team, I think `beforeSave` and others [lifecycle hooks](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#available-lifecycle-events) are not meant to handle custom UI/state of the content-manager.
maybe the `useCMEditViewDataManager` hook would be a better help to handle some customization of the data before any save/submit event - you can find the documentation [here](https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/admin-panel.html#accessing-data-with-the-usecmeditviewdatamanager-react-hook), wdyt?

I will close #14415 in the meantime as it doesn't seem like an update needed - we could re-open it later if anything change 🙂

**Comment by goodpixels** [comment]
Sorry to hijack this thread, but search results brought me here.

I also have a similar use case, I need to calculate a distance for a city based on user input at runtime.

1. I've got a collection of items where each item has a `location` field, which stores `latitude` and `longitude`.
2. When user makes a request to this collection, they will pass their `latitude` and `longitude` in the query, like so: `http://localhost:1337/api/items?latitude=X&longitude=Y`
3. At this point, I call `strapi.entityService.findMany("api::item.item")` in my controller, then I iterate over the results and append the `distance` attribute, which is calculated dynamically, based on the user input - this does not work as expected, as it only will map the *paginated* results, not the entire collection, resulting in incorrect pagination (that is the next set of results does not take into account the calculated distance, because it's calculated anew)

Question: how can I filter a collection based on a *calculated value*? I looked at "beforeFindMany" and "afterFindMany", but it doesn't really suit my use case. I also cannot calculate a value on item update, because it has to be dynamic, based on user input.

How can I achieve this?

**Comment by goodpixels** [comment]
Okay, so I got it working. The solution is very fragile, but it works for my POC. I wish there was a better way to do this.

Here are the steps, on how I got it working:

1) I've got a collection called `items` and inside it I've added a component called `address` (note that all fields are mandatory, which is not great, but I need those values to be able to query the database):

```
{
  "collectionName": "components_general_addresses",
  "info": {
    "displayName": "Address",
    "description": ""
  },
  "attributes": {   
    "postcode": {
      "type": "string",
      "required": true,      
    },    
    "latitude": {
      "type": "float",
      "private": true,
      "required": true
    },
    "longitude": {
      "type": "float",
      "private": true,
      "required": true
    }
  }
}
```
2) I created a new `location` service, which queries the database via Knex raw query (thanks to [this Stack Overflow answer](https://stackoverflow.com/a/67711005)) to obtain the IDs of the items that are within the search radius, like so:

```
getNearestIDs({ latitude, longitude, maxDistance }) {
  const knex = strapi.db.connection;

  const pointA = `CONCAT('POINT(',components_general_addresses.longitude, ' ',components_general_addresses.latitude,')')`;
  const pointB = `'POINT(${latitude} ${longitude})'`;

  const distanceQuery = `
    ST_DistanceSpheroid(
        ST_GeomFromText(${pointA}),
        ST_GeomFromText(${pointB}),
        'SPHEROID["WGS 84",6378137,298.257223563]'
    )
    `;

  return knex("items_components")
    .join(
      "components_general_addresses", "items_components.component_id", "=", "components_general_addresses.id",
    )
    .where("component_type", "general.address")
    .andWhere(knex.raw(`${distanceQuery} <= ?`, maxDistance))
    .select("items_components.entity_id");
};
```

**Note: I had to install the [PostGIS](https://postgis.net/) PostgreSQL extension, which is also not great, because I do not know if my hosting provider will support it.** Also, please excuse my clumsy SQL, I literally have never used SQL before.

3) Then, in the `items` controller, inside the `find()` function, I query the `location` service, to determine which items should be fetched, and then I add the IDs to the query filters, like so:

```
const { postcode, radius } = ctx.query;

if (postcode || (postcode && radius)) {
    const nearestIDs = await strapi
    .service("api::location.location")
    .getNearestIDs({ postcode, radius });

    ctx.query.filters["$and"]
    .push({
        id: nearestIDs.map(({ entity_id}) => ({ id: entity_id }))
    });
}

return await super.find(ctx);
```
4) Finally, I use the `afterFindMany` hook to append the distance to each result. For this I created another service, which does not rely on database functions, instead I am using a [node module](https://github.com/mapado/haversine). I was struggling to figure out how to get URL query params, but it turned out super easy to do:

```
const url = require("url");

module.exports = {
  async afterFindMany({ result }) {
    const ctx = strapi.requestContext.get();

    const { postcode } = url.parse(ctx.originalUrl, true).query;

    if (postcode) {
      try {
        Promise.all(
          result.map(async (item => {
            const { distance } = await strapi
              .service("api::location.location")
              .calculateDistance({ from: item.postcode, to: postcode });

            location._distance = distance;
          })
        );
      } catch (err) {
        console.log(err);
      }
    }
  },
};
```

So to wrap it up:

1) Use Knex raw queries
2) Pre-fetch a subset of IDs for the items I want to fetch via `super.find()`
3) Add calculated field values to results in `afterFindMany`

I don't quite like this approach, but it seems to be working fine for now. I will now need to add some serious error handling to all of this smoke and mirrors solution.

I really wish there was a better way to achieve this. If anyone know how, please tell me.

**Comment by AxeemHaider** [comment]
> ronronscelestes

First of all thanks for your precious time and consideration. You little bit misunderstood the usecase, definatly this is possible by UID field. But this is just an example case. There are many other cases where you need other fields value to generate another field value. I know there are some flaws in my PR, I will come with some better idea

**Comment by taviroquai** [comment]
Hi,

I also need to compute a field from arbitrary fields and the field type UID is not flexible enough for this.

I'm using lifecycle hooks to generate these computed fields.

**Comment by derrickmehaffy** [comment]
Going to close this in favor of the following feature request: https://feedback.strapi.io/feature-requests/p/field-type-computed
