### ISSUE TITLE
Forbidden access error when using persistedQueries

### ISSUE THREAD

**Issue by iamfaycal** [strapi/strapi#14425]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.3.8
- Database: Postgres
- Operating system: MacOS 12.4

### Describe the bug

When I enable persistedQueries in urql client, I get Forbidden access errors even though the permissions are correctly set up and the query works fine if persistedQueries are disabled

### Steps to reproduce the behavior

1. Install latest strapi version with typescript and postgres
2. Install the strapi graphql plugin
3. Use the default config/plugins.js in the documentation 
3. Create a simple content-type and enable find and findOne rights for unauthenticated users
4. Create a react front-end (Next.js in the repo)
5. Install urql client and enable persistedQueries
6. Write a simple query and try to log the results with and without persistedQueries
7. See that when persistedQueries are enabled the backend returns no data and a Forbidden access error

### Expected behavior

Strapi should not return Forbidden access error when using persistedQueries if the permissions are corectly set up

### Code snippets

Strapi graphql plugin config : 

```
module.exports = {
  graphql: {
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: true,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
};
```

Reproductible repo :
https://github.com/iamfaycal/strapi-persisted-queries

### Additional context

We are upgrading from strapi 4.1.7, and don't have this issue on that version

**Comment by iamfaycal** [comment]
I still have this issue in version 4.4.4

**Comment by kasonde** [comment]
Hi @iamfaycal this seems to be an issue with urql because Strapi, when tested with a client like Postman or your browser, unless otherwise will work as expected each time. I went ahead and cloned your project and yarn both the server and client. I created a new entry with the value test and gave the content-type the right permissions (for public requests) and everything seems to be working fine. I'm closing this since there is no indication of this being a Strapi related issue. I'd recommend you to visit our #frontend-other/#frontend-react channels on [Discord](https://discord.strapi.io) to engage with our community members who could possibly be using the same tools as you on the front-end to consume their Strapi API. 

Also, if you believe this assessment is a mistake/incorrect, please feel free to comment and share more information regarding your experience and we can dig deeper. 

![image](https://user-images.githubusercontent.com/13610895/198673804-53861462-27d2-446e-bb18-e30a4ea8533c.png)
