### ISSUE TITLE
Cannot create new project with 3.0.0-alpha.12.5

### ISSUE THREAD

**Issue by nicolasgalle** [strapi/strapi#1444]
Node.js version:10.5.0
npm version:6.1.0
Strapi version:3.0.0-alpha.12.5
Database:mongodb
Operating system:windows10 64bit

![capture](https://user-images.githubusercontent.com/4417791/41729761-5dffa8c0-757a-11e8-8b6d-16dd11319fd5.PNG)

When trying to create a new project with "strapi new test", the process goes normally till "Database name" question where I cannot enter any info. At this step Strapi creates a "tmp" folder in the project folder and then stops. No project is created.

**Comment by derrickmehaffy** [comment]
Related issues: https://github.com/strapi/strapi/issues/1355 (Closed due to bug template)


Duplicate Issue: https://github.com/strapi/strapi/issues/1281 (recommend closing this one)

@nicolasgalle This is a known issue with windows, please use the Windows WSL (Ubuntu) or a Linux VM for development for now. The Strapi team are working on better windows support. 

You can read about this in their latest blog post: https://blog.strapi.io/roadmap-update-2-stability-tests-experience/

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues.
Please check https://github.com/strapi/strapi/issues/1281

**Comment by corinthian13** [comment]
Please update the Quick Start guide for project creation, i.e.
              https://strapi.io/documentation/getting-started/quick-start.html
to clearly mention the current need for Linux VM  to create a project.

**Comment by lauriejim** [comment]
@corinthian13 can you create a pull request please https://github.com/strapi/strapi/edit/master/docs/3.x.x/en/getting-started/quick-start.md
