### ISSUE TITLE
cannot import css in custom plugin

### ISSUE THREAD

**Issue by macrozone** [strapi/strapi#14484]
### Required System information

- Node.js version: v14.20.1
- NPM version: - 
- Strapi version: 4.3.9
- Database: postgres
- Operating system: macos 

### Describe the bug

In my custom plugin, import a css file using `import "my-module/path/to/file.css` . This worked in strapi 4.0.8. After upgrading to 4.3.9 this css import no longer works. Everything compiles without error, but the styles are not applied.

### Steps to reproduce the behavior

1. use `yarn strapi generate` to create a plugin
2. add a component in the plugin
3. import a css file, e.g. from a npm module in the component using ``import "my-module/path/to/file.css`
4. add the plugin to your project
5. start strapi in dev mode

### Expected behavior

css files are imported in plugins

### Additional context

Might be a change in how strapi uses webpack. Was there any change recently?

**Comment by macrozone** [comment]
as a workaround, i did it a bit funky:

- add `raw-loader` as dev dependency
- `import cssString from "!raw-loader!package/path/to/file.css";`
- then add a `<style>{cssString}</style>` tag to your custom plugin component

**Comment by emilieringwald** [comment]
Hey @macrozone , thanks for the ticket, we added it to our backlog and will review it asap.

**Comment by johncin** [comment]
https://github.com/johncin/strapi-reactpage

Since this is tagged with "pending reproduction", here's a repo of a strapi plugin trying to implement a custom field with the react-page editor, which needs css imports to look right.
Go to components/Editor/index.tsx and change rows 19 and 20 to normal css imports (atm they're attempts at using raw-loader, as macrozone suggested, but I couldn't get it to work, not sure why, I get errors during typescript compilation). Run it, you'll see that the layout for the editor component won't look right...

**Comment by tobiaszkrolak** [comment]
Hi! 
Problem is still existing in 5.10.2

**Comment by Arut0ria** [comment]
We could import style as a module, but we are missing the react-scripts in dependencies.

`
import style from './style.module.css'

// ...

<div className={style.whatever}></div>
`

But adding the react-scripts package gives conflicting deps error.

**Comment by Luderio** [comment]
Hello, this is still an issue on Strapi 5.11.3
