### ISSUE TITLE
Singleton content type

### ISSUE THREAD

**Issue by nicokant** [strapi/strapi#1449]
**What is the expected behavior?**
 Having a singleton content type would allow to store dynamic configurations, some use cases:
- default SEO tags value
- text blocks that are used inside a page
- website/app dynamic configuration

I'm using gatsby to generate a website and I'd like to keep data and templates separated, this would allow to query also for single page content, not only collections of data.

**Comment by lauriejim** [comment]
Hello @nicokant .

You can create a content type with one text attribute and one JSON attribute to have this feature.

**Comment by nicokant** [comment]
Yes, this could work, but a content type is a entries, a configuration should be instead just a single item.
Moreover a json field type require technical knowledge and may be complex for a user

**Comment by nicokant** [comment]
Yes, this is precisely the point

**Comment by Aurelsicoko** [comment]
We have a Core Store API to store any kind of data. It's working like a key/value database. But I guess you're talking about a plugin that could handle Pages for a content management purpose?

**Comment by ajzozakiewicz** [comment]
Pages in a CMS is the use case for sure.

Being able to have a content type of pages and then relate each page to a unique form for each page. The lack of this feature prevents me from being able to implement this in place of other CMS systems.

**Comment by Aurelsicoko** [comment]
We are considering to develop something similar. Please refers to this card (https://portal.productboard.com/strapi/c/9-blocks-manage-static-content) on Product Board.

I'm closing the issue, but feel free to comment or ping me if needed.

**Comment by EloB** [comment]
I'm also missing this. It would be really good for custom configuration. I'm using Strapi to create a simple website for marketing but also a webapp part. Its pretty often you need to fetch config on startup on your webapp. This way you don't need to hardcoded these values and it would be nice to use "content manager" fields instead of the proposed json field on a content type.

The only solution for something like this is to create a content type and only create a single entry and hardcode that id in your app to only fetch that but if you by mistake remove that entry and add another then the id won't work so it's not a stable solution.

**Comment by lauriejim** [comment]
Hello! This feature is under development, will be released at the beginning of 2020.
So stay tuned.

Right now, there is no other way to manage that.
Or you can manage it by creating your own plugin.

**Comment by coupez** [comment]
Is there an issue tracking this implementation?

**Comment by UndarkAido** [comment]
@lauriejim What @coupez said, I'd be very interested in having this.

**Comment by derrickmehaffy** [comment]
@coupez @UndarkAido the feature is currently in testing right now. I would expect to see it released within the next 2 weeks or so (maybe sooner, depends on if Strapi plan to group in the Media Library feature also)

**Comment by lauriejim** [comment]
The feature has been released in the beta.19 version of Strapi
