### ISSUE TITLE
WYSIWYG editor with HTML

### ISSUE THREAD

**Issue by nicokant** [strapi/strapi#1450]
**What is the expected behavior?**
Markdown editor can be difficult for non tech users as its not properly a WYSIWYG editor, they usually e expects to be able to edit contents and preview the result at the same time.

Keeping both markdown and WYSIWYG would be fantastic, a great editor that would allow this is [prose mirror](http://prosemirror.net/), which "converts" markdown syntax to HTML while writing.

**Comment by soupette** [comment]
@nicokant we went for a full markdown support because we store 'stringified markdown' in your database. Having a simple WYSIWYG would mean that we need to store the entire contentState of the WYSIWYG in your database. 

This might not be an issue for the user but it would mean that he has to use [draft-js](https://draftjs.org) editor in his application, with exactly the same configuration has the one used in Strapi. Moreover, drafts is very sensitive to the applied style and not compatible with [mobile](https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#mobile-not-yet-supported) which might be an issue for the end user. 
Thus, leads to another problem if he wants to be mobile compatible : it is very hard to keep the same style applied to the editor when we convert its content in either HTML or Markdown.
 
For all these reasons we chose to go for a full Markdown support:
- Image upload and display
- Video upload and display
- Links
- Code block, quotes
- Other Markdown features...

The editor surely needs to be improved, and support simple creation but it is not in our ROADMAP yet.

**Comment by nicokant** [comment]
> This might not be an issue for the user but it would mean that he has to use draft-js editor in his application, with exactly the same configuration has the one used in Strapi.

I suppose it depends on how the user expects to use Strapi, if he wants to just create/edit data with strapi admin the problem with the configuration doesn't exists. If he wants to edit data in a custom frontend but wants to be still usable in strapi admin, he should produce and save markdown text to be compatible. In the second case the user is probably going to use a text field without WYSIWYG support.

An option could be to have text field, text field markdown and text field html. DraftJS should be able to import/export to both the formats as far as I know.

> Moreover, drafts is very sensitive to the applied style and not compatible with mobile which might be an issue for the end user.

I think that compatibility with strapi admin should be a responsibility of the developer, which given a set of parameters should decide if is something that he needs. As before if the user/developer is going to use strapi admin only, compatibility is ensured, if he modifies data outside strapi admin probably he doesn't use a text field with preview or he is forced to store markdown to have compatibility.

> it is very hard to keep the same style applied to the editor when we convert its content in either HTML or Markdown.

I agree, but I think that saved content shouldn't be interchangable. Strapi admin could provide the ability to edit raw text or preview/edit markdown text or preview/edit html text based on what the developer needs to save

**Comment by nicokant** [comment]
An option could be using the same configuration as in draft js example: https://draftjs.org/

The content could still be exported as markdown, but at the same time user should't be forced to know markdown to write.

**Comment by derrickmehaffy** [comment]
> I think that compatibility with strapi admin should be a responsibility of the developer, which given a set of parameters should decide if is something that he needs. As before if the user/developer is going to use strapi admin only, compatibility is ensured, if he modifies data outside strapi admin probably he doesn't use a text field with preview or he is forced to store markdown to have compatibility.

@nicokant don't forget this is an open source product so if you would like to see a feature modified from the Strapi intended plan, I'm sure the devs would love to see a PR :smiley: Even just as a "proof of concept"

**Comment by nicokant** [comment]
@derrickmehaffy you are right, I'd like to contribute with a PR!

**Comment by malbari** [comment]
Any plan to support WYSIWYG for Vue component also, for example using <a href="https://cinwell.com/vuep/#/">vuep</a> ?
Thanks

**Comment by Aurelsicoko** [comment]
@malbari What do you mean by supporting the WYSIWYG for Vue component?

**Comment by malbari** [comment]
Yes, I mean WYSYWYG for Vue component. If I understand correctly, currently a markdown WYSIWYG editor is supported "out of the box" and the HTML equivalent is proposed as feature request. Both are usefull to display rich static content, and I think that a WYSIWYG editor for Vue coomponent (or ReactJS equivalent) could be usefull for displaying dynamic content as well.

**Comment by sebj54** [comment]
Hi! 

Rather than providing a new way to edit content, why not changing the Markdown plugin?

There are already plugins which provide a way to view content formatted while editing it. Some of these plugins export text as markdown, so it will be transparent for Strapi!

Examples:
https://github.com/nhnent/tui.editor#easy-wysiwyg-mode
http://prosemirror.net/

Actually, it's really hard for non-tech users to understand how pictures or links work. They may also forget to close bold or italic tags.

**Comment by soupette** [comment]
@sebj54 we don't use the markdown plugin because it didn't have all the needed functionalities.
What we might add is an option to have either markdown or HTML.

**cc/ @Aurelsicoko**

**Comment by Aurelsicoko** [comment]
I think we should provide a markdown, HTML and WYSIWYG editor. It should be an option in the `Advanced settings` tab in the Content-Type builder.

**Comment by wyamout** [comment]
Yep my client already complaining about the editor as it's non-tech friendly, I guess they got used to wordpress. I tried iframes they didnt work also. Any idea how to add iframes to posts for example?

**Comment by Aurelsicoko** [comment]
Maybe @soupette can give you some insights?

@wyamout What's the real issue with the current editor? Is this due to markdown? Or something else?

**Comment by wyamout** [comment]
> Maybe @soupette can give you some insights?
> 
> @wyamout What's the real issue with the current editor? Is this due to markdown? Or something else?

@Aurelsicoko Yes the whole bullets, numbering are kinda annoying. Basically all my 17 editors started complaining I gave them a go at froala they liked it so I will replace draft with froala.

Basically as editors they need more flexibility with creating content moving things around etc..

**Comment by Aurelsicoko** [comment]
I created a new card in our public roadmap available on Product Board. Feel free to give me more insights (https://portal.productboard.com/strapi/c/37-wysiwyg-html-editor).

Since we're considering to support HTML in our editor, I'm closing this issue.

**Comment by CMatias** [comment]
@wyamout Did you end up having any success in adding Froala to Strapi? I'm currently trying to do so but I'm facing the following error when building the production assets (everything works on dev mode).

```
Element ref was specified as a string (el) but no owner was set. This could happen for one of the following reasons: 1. You may be adding a ref to a function component 2. You may be adding a ref to a component that was not created inside a component's render method 3. You have multiple copies of React loaded See https://fb.me/react-refs-must-have-owner for more information.
```
