### ISSUE TITLE
With google provider l'm able to create two users with same username and e-mail (nuxt/strapi).

### ISSUE THREAD

**Issue by fskarmeta** [strapi/strapi#14519]
- Node.js version: v18
- NPM version: 8.15.0
- YARN version (used): 1.22.18
- Strapi version: 4.3.9
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

Using strapi/nuxt auth provider with google and register() function I can create users with duplicate e-mail, and even with duplicate e-mail and username.

Unique e-mail address constrain is ON in Advanced Settings.

### Steps to reproduce the behavior

1. Setup google provider auth and also a standard register form (in this case using register() method of strapi/nuxt).
2. Using register() first create a user with username equal to the e-mail string before the `@`. So if email is example@google.com, use `example` as username and `example@google.com` as e-mail. Create a user and then logout.
3. Now login using authProvider of nuxt/strapi with google, using the same e-mail.
4. You will find two users in the DB with unique id's using the same e-mail and username.

### Expected behavior

Callback auth throws some error. 

### Screenshots

![image](https://user-images.githubusercontent.com/69222982/193436528-2ed791db-0d09-47cd-a512-26f1f2223084.png)

**Comment by fskarmeta** [comment]
Ok seems this intentional, the `provider` makes the user unique I guess.

**Comment by mauriciabad** [comment]
@bolg55 why is this the expected behavior? 

It doesn't make sense for me, usernames are usually unique. And this is not mentioned anywhere in the documentation, so many apps are going to have bugs because they expect usernames to be unique.

I can understand that from the developer side, making it non-unique is the default behavior, but that doesn't make it the correct one.
