### ISSUE TITLE
Deleting uploaded file issue with SQL

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1459]
**Informations**
- **Node.js version**: v8.11.2
- **npm version**:5.6.0
- **Strapi version**: v3.0.0-alpha.12.5
- **Database**: pg
- **Operating system**: Red Hat 7.2.1-2 (AWS server)

**What is the current behavior?**
Okay, so problem is that if I uploaded image on server, it occurs an issue: 

- When I try to delete uploaded file via delete button it throws me an error: 
```
{ error: column upload_file.id does not exist
    at Connection.parseE (/home/ec2-user/lacing-lab-api/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/home/ec2-user/lacing-lab-api/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/home/ec2-user/lacing-lab-api/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 174,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "upload_file._id".',
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3293',
  routine: 'errorMissingColumn' }

```
**What is the expected behavior?**

I expect to get an opportunity to see file and delete file via admin panel.

**Suggested solutions**

It seems like there are some problems with bookshelf of uploading, but I don't have any solutions yet.

**Comment by derrickmehaffy** [comment]
Seems related to the discussion of `_id` vs `id` : https://github.com/strapi/strapi/issues/1274

**Comment by MechJosh0** [comment]
I'm getting the same issue but the opposite column names. MySQL has the column name of `.id` and the query it's running is `._id`. See below for my issue template.



**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.5
- **Database**: MySQL
- **Operating system**: Ubuntu


**What is the current behavior?**
When you attempt to delete an image it's running a query where it thinks the image id column is `._id` instead of the correct column name of `.id`.
```
 sql: 'select `upload_file`.* from `upload_file` where `upload_file`.`_id` = \'1\' limit 1' }
```
```
  sqlMessage: 'Unknown column \'upload_file._id\' in \'where clause\'',
```


**Steps to reproduce the problem**
1. Go to `Files Upload` plugin
2. Upload an image
3. Delete the image


**What is the expected behavior?**
Deletes the image and MySQL row.


**Suggested solutions**
Use the correct column name `.id` for MySQL databases.

**Comment by COcisuts** [comment]
Same here... Windows 10 with ubuntu subsystem...

**Comment by franksn** [comment]
this is also the case for postgresql backend.
