### ISSUE TITLE
Browser not reloading after creating/removing a Content Type

### ISSUE THREAD

**Issue by Badestrand** [strapi/strapi#14611]
### Required System information

- Node.js version:  v16.17.1
- NPM version:  8.15.0
- Strapi version:  4.4.3
- Database:  SQLite
- Operating system:  Ubuntu 22.04 LTS

### Describe the bug

The mechanism that detects when the server is up again doesn't work well for me. After changing a content type and waiting for the restart it will wait 1 minute or forever, depending on my nginx configuration.

### Additional context

My browser is the most recent Chrome.

I have Strapi running behind a nginx proxy.

In the browser's network tab I can see that a single "HEAD /_health" request gets sent, should be from [here](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/serverRestartWatcher.js#L13).

This request keeps being "pending" in the network tab. With nginx's default settings this request will timeout after 1 minute, then a new "HEAD /_health" request is sent, immediately returns and the restart is detected successfully. With nginx settings set to allow long running queries (e.g. 1 hour) it will take the full hour to timeout.

I think this would be easily solved if you implement a [timeout](https://stackoverflow.com/a/50101022/3726387) like 5 seconds for the fetch operation linked above.

**Comment by derrickmehaffy** [comment]
> This request keeps being "pending" in the network tab. With nginx's default settings this request will timeout after 1 minute, then a new "HEAD /_health" request is sent, immediately returns and the restart is detected successfully. With nginx settings set to allow long running queries (e.g. 1 hour) it will take the full hour to timeout.

Can I ask why your develop application is running behind Nginx? We don't support running development mode in production and if that is the case here (and the root cause) then there isn't much we can/will do.

**Comment by dionysiusmarquis** [comment]
It's true to never run the develop environment in production, but a staging environment might be running behind nginx in which content changes might also be acceptable. Since there is currently no way to define a frontend `fetch` timeout on strapi side it's still possible to add a route specific timeout to `/_health` in nginx.

**FOR STAGE ONLY** Generic example inside a letsencrypt reverse proxy (`vhost.d/strapi.stage.example.com`):
```
location /_health {
    proxy_pass http://strapi.stage.example.com
    proxy_read_timeout 1s;
}
```

This way the frontent `fetch` on `HEAD /_health` will trigger every second until the strapi server is back up.
