### ISSUE TITLE
Blank Admin page

### ISSUE THREAD

**Issue by lukabanjac** [strapi/strapi#14628]
Hello all.

I've depleted all my resources and came to a conclusion that i should write this issue and see what you guys think.

It happend when I run strapi server. The admin page is blank and shows this error:

![image](https://user-images.githubusercontent.com/33004430/195869375-e848760c-61be-4351-8029-b46d63ad527e.png)

Everything else is functioning fine, including my cron jobs and such.

Tried switching yarn and npm back and fourth and nothing. Tried changing the babel version as said [here](https://github.com/strapi/strapi/issues/9482) but nothing.
Looking forward to some ideas regarding how I could fix this.

My package.json is:
```
...

{
  "dependencies": {
    "@babel/core": "^7.19.3",
    "@babel/runtime": "7.13.2",
    "@buffetjs/styles": "^3.3.8",
    "@strapi/provider-email-sendgrid": "^4.1.8",
    "knex": "0.21.18",
    "koa-body": "^4.2.0",
    "pg": "^8.7.3",
    "puppeteer": "^14.3.0",
    "react-query": "^3.39.1",
    "sqlite3": "5.0.0",
    "strapi": "3.6.9",
    "strapi-admin": "3.6.9",
    "strapi-connector-bookshelf": "3.6.9",
    "strapi-plugin-content-manager": "3.6.9",
    "strapi-plugin-content-type-builder": "3.6.9",
    "strapi-plugin-email": "3.6.9",
    "strapi-plugin-i18n": "3.6.9",
    "strapi-plugin-upload": "3.6.9",
    "strapi-plugin-users-permissions": "3.6.9",
    "strapi-provider-email-sendgrid": "^3.6.8",
    "strapi-provider-upload-do": "^3.6.6",
    "strapi-utils": "3.6.9",
    "uuid": "^8.3.2",
    "video-react": "^0.15.0"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT",
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0"
  }
}
...

```

**Comment by gu-stav** [comment]
Hi @lukabanjac . Thank you for opening the issue. Would it be possible to check if https://github.com/strapi/strapi/pull/14647 fixes your issue? I'm wondering if the blocked tracking domain causes the problem here ...

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports for v3 unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You
