### ISSUE TITLE
Service update throw error

### ISSUE THREAD

**Issue by Melzas** [strapi/strapi#14658]
### Bug report

**Required System information**
Node.js version: 16.17.0
Yarn version: 1.22.19
Strapi version: 4.4.1
Database: MySQL
Operating system: Windows 10

**Describe the bug**
When a "find" query is executed with, in the filters, a "relation" type attribute, and then, on the same table, an "update" query is executed, I believe that strapi keeps in memory the filter applied in the previous query.

**Steps to reproduce the behavior**
In a lifecycles file, copy this code

`
module.exports = {
  beforeUpdate: async (event) => {
    const { params } = event;
    const data = params.data;

    try {
      const { results } = await strapi
        .service("plugin::library.book")
        .find(
          {
            filters: {
              id: {
                $ne: params.where.id,
              },
              default: {
                $eq: true,
              },
              author: {
                id: {
                  $eq: data.author,
                },
              },
            },
          }
        );

      if (data.default && results.length) {
        results.forEach((book) => {
          strapi
            .service("plugin::library.book")
            .update(book.id, { data: { default: false } });
        });
      }
      else if (!data.default && !results.length) {
        event.params.data.default = true;
      }
    } catch (e) {
      console.log("error", e);
    }
  },
};
`
This error appear in the console

`error Error: Undefined binding(s) detected when compiling WHERE.Undefined column(s): [t2.id] query: where`t0`.`id` <> ? and`t0`.`default` = ? and`t2`.`id` = ?
at QueryCompiler_MySQL.toSQL (D:\app\backend\node_modules\knex\lib\query\querycompiler.js:110:13)
at compileCallback (D:\app\backend\node_modules\knex\lib\formatter\formatterUtils.js:13:19)
pp\backend\node_modules\knex\lib\query\querycompiler.js:1ules\knex\lib\formatter\wrappingFormatter.js:225:7)32:16)                                                   khundapp\backend\node_modules\knex\lib\query\querycompiler.js:1084:17)    
    at QueryCompiler_MySQL.toSQL (D:\app\backend\node_modules\knex\lib\query\querycompiler.js:573:34)p\backend\node_modules\knex\lib\query\querycompiler.js:73\lib\query\querycompiler.js:133:40:29)
    at Builder.toSQL (D:\app\backend\nopp\backend\node_modules\knex\lib\query\querycompiler.js:132:16)de_modules\knex\lib\query\querybuilder.js:83:44)`

If you remove
`author: {
    id: {
      $eq: data.author,
    },
  },`

That's works perfectly

**Expected behavior**
Filters should be cleaned after query execution

**Additional context**
For my example, author have many books, and a book have one author

**Comment by derrickmehaffy** [comment]
It's not possible that the filter is kept, this issue is likely a problem with your code. As this isn't likely to be an issue with the Strapi codebase I'm marking as closed, I would recommend you reach out to the community to check on your issue.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
