### ISSUE TITLE
Implement multi-site (multi-tenant) feature

### ISSUE THREAD

**Issue by nicksrandall** [strapi/strapi#1465]
I'm looking for a multi-site feature much like Wordpress and can see that it is on the long-term road map for strapi. I'd like to help get this feature implemented and am looking for some direction from the core maintainers before I begin. 

Has anybody spent the time to consider how this might be accomplished?

For those who are unfamiliar with "multisite" (perhaps a better name would be multi-tenant), I will give a brief explanation. As a user, I'd like to manage multiple clients (front-ends) with one backend installation (sever). The multisite backend will provide a way to manage users as well as give specific users access to specific sites. I would also be able to create and manage sites, each one configured with a specific url namespace. 

For example, Lets say I had two clients; one for my blog and another for my online store. Each site would maintain it's own api which would be prefixed with a configurable value. So, for example, I could access my posts at "site.com/blog/posts" and could access my products at "site.com/store/products". Likewise, I could access the admin for my blog at "site.com/blog/admin" and the admin for my store at "site.com/store/admin". For all intensive purposes, these two sites are completely isolated except for that fact that they run on the same server, the same database, and the same core libraries.

**Comment by Aurelsicoko** [comment]
As you said, it's on the long-term roadmap for Strapi. Currently, I don't think the project is mature and stable enough to handle this use case. So many things are still in work in progress, the plugin implementation isn't finished yet and we're still in alpha. 

However, I would love to know how you would like to implement this feature. We could anticipate some things and make it easier to develop in the future 👍

**Comment by indiecore-fm** [comment]
@nicksrandall @Aurelsicoko What is the idea for this? Core functionality or seperated into a plugin? To add I would prefer subdomains with an option to attach a TLD. I am creating an app where my customer will need their own separated by a subdomain. (business1.site.com, business2.site.com)

**Comment by Aurelsicoko** [comment]
@indiecore-fm For now, it should be a core functionality, but we're working on the plugin architecture and I still don't know if a feature like this could be handled by a plugin. It would make more sense to use a plugin for this but it will impact so many things...

Also, should we generate two projects (one for each subdomain) without the administration and another one with the administration only? With configurations, we could connect them together to the same administration.

Or, we should update the architecture of a current project and split into multiple apps. The plugin will load the files by itself and mount them into the main app. 
```bash
- /admin
- /apps
  - /one
    - /api
    - /config
    - /plugins
    - package.json
  - /two
    - /api
    - /config
    - /plugins
    - package.json
```

There are different approaches to the multisite feature, I don't have enough background to know what's the best way to do it... If you have any thoughts or ideas to share, I would like to hear about them :)

**Comment by vinayagg** [comment]
Another way to do this is to create project / customer folders with base apps linking to common folders like this:

- /superAdminV2.0 (super admin access for all 2.0 apps)
- /superAdminV3.0 (super admin access for all 3.0 apps)
- /adminV2.0
- /adminV3.0
- /pluginsV2.0
- /pluginsV3.0
- /apps
  - /one
    - /admin (links to /adminV2.0, can be upgraded by linking to /adminV3.0)
    - /api
    - /config
    - /plugins (links to /pluginsV2.0, can be upgraded by linking to /pluginsV3.0)
    - /pluginsCustom (Customer / project specific plugins)
    - package.json


This kind of architecture would allow projects be upgraded that have not deviated from base code but also allow customers/projects to maintain their version if they had to customize something specific.

**Comment by bdrtsky** [comment]
Any updates? This feature is very interesting.

**Comment by Vadorequest** [comment]
We also need this feature, here are our current needs:
- Providing a backoffice to our customers, where each user can connect to its own tenant and access its tenant's data only.
- Theming capabilities of the backoffice, per tenant, would nice to have.
- Advanced permissions and roles for internal users, basically need to configure whom can view which tables, or has update/delete permissions on which tables.
- We need an API as well in order to fetch the data from our apps. (GraphQL)
- The backoffice needs to be flexible about UI components/views so that we can create our own workflows, views and components. 
- We plan on building a common base for all, but having the capability to customize a the UI/workflow of a specific customer in a maintainable way would be awesome.

I believe those feature confirm more or less the above design.

**Comment by vinayagg** [comment]
Another requirement can be - groups or organizations
Data can be owned by organization (or group) rather than individual. Individuals join and leave companies, data stays with the company.

**Comment by Goxiaoy** [comment]
This is a really good feature for someone who want to build a Saas platform based on Strapi, or even for Strapi team self (instead of Paas)

I have some experiences on Saas platform and multi-tenant, so here are some of my opinions

- Code base:
   - Every tenant should share the same code. This will apparantly reduce the code maintainance and make features availbale for every tenant once developed. Instead of code structure like `/apps/one` `/apps/two`, it's more reasonable to use the existing plugin like structure `/apps/module1` `/apps/module2`, and by adding a permission module like existing `user-permission` plugin, you can control which tenant can use `module1` or `module2` or both, we can called `tenant-feature`. And even you can add a `role` like feature may called `tenant-edition` to provide editions like `enterprise` `team` . If your tenant wants the source code of modules he want, it's better to create a separate repository or branch
   
    - Customization like themes. This should be available for tenant self. By using module like `tenant-setting`, tenant could update theme settings easily.

    - Host admin and tenant admin.  Host admin should have some module like `tenant-management` to manage tenant. Host admin can have feature like `impersonator` to login in as tenant admin to see information in tenant for customer debugging.

- Data Access
    - Strapi provides powerful `contentType builder` to quickly deliver business models, so if you want to open this feature to your tenant, the best [tenancy model ](https://docs.microsoft.com/en-us/azure/azure-sql/database/saas-tenancy-app-design-patterns) is `database-per-tenant`. You have a  host side database to store models like `tenant`,`tenant-feature`,`tenant-edition`
, and for every tenant , he owns his own database so that he can fully use the power of `contentType builder`. As for the deployment, you can share the same db instace like Amazon RDS but different database. Or even you want to provide SLA for important tenant which may have a large mount of read-write, you can use infrastructure as code to create db instances for this tenant! If you want to deliver the same schema for every tenant, you can totally use `single-tenant app with single-tenant database`


- How to:
    - create global object `tenant` like `User object in Strapi context`
    - use middleware to resolve tenant object. For example like `business1.site.com, business2.site.com`  you can create a `UrlTenantResolver` to resolve tenant object
    - data access. Resolve database config by tenant. determine use host db or tenant db. If you want to use `single-tenant app with single-tenant database`, you should really be care of the data isolation. Some feature like` GlobalDataFilter` should by applied to the whole data access layer to prevent one tenant from seeing data not belongs to this tenant

- Conclusion：
   - plugins to development: `tenant-management`, you may also want `tenant-setting` `tenant-feature` `tenant-edition`,or  `tenant-seeder` to initial database for `database-per-tenant` or create some initial data
   - core code change: data access layer should have some feature like ` GlobalDataFilter` to isolate data. `TenantDatabaseConfigResolver` to resolve tenant db info.
   - development change: use infrastructure as code to create db instances if needed

**Comment by Goxiaoy** [comment]
> Another requirement can be - groups or organizations
> Data can be owned by organization (or group) rather than individual. Individuals join and leave companies, data stays with the company.

organizations  can be built top on tenant with tree structure

**Comment by abdullahe** [comment]
Is this feature implemented?

**Comment by snowyu** [comment]
@Goxiaoy  Organization is not the same the tenant.

Organization means data sharing, and tenant means data isolation.

* user: could have one or more organizations.
* individual: a special organization, anyone should belong to it, and can not leave it.
* public: a special role of individual.

@vinayagg should open a new issue for the feature.

**Comment by virgil9306** [comment]
To tackle this scenario, I am deploying multiple Strapi on multiple VMs but always using the same Docker image I created.

You may want to try using "your" version of a Strapi deployment as a Docker image too, and updating that across many servers (using your favorite CI or something), instead of one deployment for all Tenants.

**Comment by Goxiaoy** [comment]
For those who want use feature like `organizaiton`, I just publish a plugin [strapi-plugin-users-organizationunits](https://github.com/Goxiaoy/strapi-plugin-users-organizationunits#readme). Notice that there are still some issues and may not fully tested.

**Comment by vinayagg** [comment]
> For those who want use feature like `organizaiton`, I just publish a plugin [strapi-plugin-users-organizationunits](https://github.com/Goxiaoy/strapi-plugin-users-organizationunits#readme). Notice that there are still some issues and may not fully tested.

Hi @Goxiaoy , since you did so much work, I want to give you a suggestion.
Your github readme file describes "How to use" but does not tell me what it is and when I should use it.
e.g. is it good for different departments within an organization (soft multi tenancy) or good with SaaS model (different companies, no trust between tenants, hard multi tenancy). 
If you look at the list of requirements compiled by Vadorequest above, which use cases can be solved and how?

**Comment by Goxiaoy** [comment]
> > For those who want use feature like `organizaiton`, I just publish a plugin [strapi-plugin-users-organizationunits](https://github.com/Goxiaoy/strapi-plugin-users-organizationunits#readme). Notice that there are still some issues and may not fully tested.
> 
> Hi @Goxiaoy , since you did so much work, I want to give you a suggestion.
> Your github readme file describes "How to use" but does not tell me what it is and when I should use it.
> e.g. is it good for different departments within an organization (soft multi tenancy) or good with SaaS model (different companies, no trust between tenants, hard multi tenancy).
> If you look at the list of requirements compiled by Vadorequest above, which use cases can be solved and how?

Sorry, my bad.
It only provides function like manage organization units as tree structure and assign users to organizations, has no relationship with Saas or multi-tenancy. So I created a new issue in https://github.com/strapi/strapi/issues/7652

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/multi-tennant-saas/462/1

**Comment by merijnponzo** [comment]
Looking at the wordpress multisite its creating prefixes for each site within the database tables.

I was having a brainfart of doing a similar thing, where strapi is the 'super admin cms'
And site users could login trough a custom made frontend (editor cms) which expose their content.

- I was thinking that users should edit their content in a simple site builder as well :-)

In strapi we create content-types within the same structure per site

-examplesite_posts (page, post or custom post type)
-examplesite_options (may contain the site settings and navigation)
-examplesite_meta (for extra data sets)

-site2 etc. ..

I would customize the routes to example-site/posts/12

Best!

**Comment by ISimplifyComplexity** [comment]
This is a vital feature for what I'm trying to do. Say you have a number of customers and you want them to be able to manage their own content.

**Comment by virgil9306** [comment]
> This is a vital feature for what I'm trying to do. Say you have a number of customers and you want them to be able to manage their own content.

Is it a possible solution for you to spin up a container/environment for each content manager? I am taking that approach.

**Comment by ISimplifyComplexity** [comment]
@virgil9306 Thanks for the suggestion, I just wonder how much resources it's going to take. I've looked into docker a little bit but I'm not totally comfortable with a serverless solution (serverless != Costless)... Could this be hosted inside of docker on a single VM?

**Comment by srchulo** [comment]
@virgil9306 Would you mind sharing how you're doing this? Is it automated?

**Comment by virgil9306** [comment]
Hi @ISimplifyComplexity , @srchulo 

Here's how I do it. But I must warn that this concept has not been tested for large-scale production. I have been using it on a small scale successfully for a few months, but it is probably not the best way.

The idea is:

* Where is it hosted:
  * Single-cluster, multi-node Kubernetes (you may architect this how you wish)
* What is hosted:
  * Each tenant has its own Strapi docker image (you can create a bash script to automate this process)
  * The docker image can be hosted on your own private docker repo
* How to deploy it:
  * Automated deployment system (Jenkins, Drone, etc.) takes a list of tenants for multi-tenancy
  * Then it deploys the correct docker image for the tenant across the nodes
  * Database deployment is also handled here -- each instance needs its own DB. These can be managed by your cloud provider or handled using your usual methods

Unfortunately I can't share the actual details of the deployment system, because it is heavily dependent on my custom infrastructure, among other reasons, but I hope this idea can be useful.

---

Notes:

* This is not simple/beautiful and quite resource-intensive (expensive):
  * Strapi builds require 2GB RAM minimum
  * Still need to host the front end
  * DB hosting too, especially with redundancy and backup
* True "multi-tenancy" would be much cheaper, especially if you have a more traditional hosting model
* Customization of each Strapi image feels redundant but I don't know a better way to do it yet

**Comment by srchulo** [comment]
@virgil9306 thank you for the detailed explanation! I think I will try to do something similar

**Comment by guicara** [comment]
Hello,

Any update on this matter?
Why this issue is closed?

**Comment by vanling** [comment]
@guicara see comment above close message

> I've added a new card in our public roadmap on Product Board (see https://portal.productboard.com/strapi/c/36-multi-tenancy). Don't hesitate to give me insights and share your thoughts. I've referenced this issue in the card.
> 
> Since the needs have been discussed enough, I'm closing the issue.

**Comment by RaphaelDDL** [comment]
I've added my 2cents on the productboard regarding this (tl;dr it's a must!). Nevertheless, I also posted in reddit seeking ideas on what to do since this feature is still missing and on hold since 2018: https://old.reddit.com/r/Strapi/comments/mx62wg/best_workaroundsstrategies_for/

There are 2 main ideas, I'd love some feedback on how any of you are approaching a fake "multi-tenancy" with strapi while this doesn't show up.

**Comment by derrickmehaffy** [comment]
> I've added my 2cents on the productboard regarding this (tl;dr it's a must!). Nevertheless, I also posted in reddit seeking ideas on what to do since this feature is still missing and on hold since 2018: https://old.reddit.com/r/Strapi/comments/mx62wg/best_workaroundsstrategies_for/
> 
> There are 2 main ideas, I'd love some feedback on how any of you are approaching a fake "multi-tenancy" with strapi while this doesn't show up.

Policies, lots and lots of policies. This is a very old example repo I built to show how someone could (poorly) construct some policies to do this.

https://github.com/derrickmehaffy/testing-strapi-policies

You have a core policy(s) that compare an incoming request to validate the user belongs to a tenant and either handle bad requests with an error or you "fix" the request:

 https://github.com/derrickmehaffy/testing-strapi-policies/blob/master/config/policies/isOrgMember.js
 
 Then for each collection-type that needs it (you will almost never use single-types) you apply the policies: https://github.com/derrickmehaffy/testing-strapi-policies/blob/440a226c9d9ba0aa5f7f09575282e8f603b27467/api/post/config/routes.json#L8
 
 This would require some way to track who belongs to what "tenant" or in this example an organization.

**Comment by RaphaelDDL** [comment]
Thank you @derrickmehaffy , I'll take my time to check it out your repo using policies. Might be a better approach than adding a "type" to each and every content type like I was planning.

**Comment by madwyn** [comment]
I don’t think this feature will be available for commercial reasons.

Multi-tenant will enable any company to host services similar to Wix/SquareSpace.

Just like ElasticSearch don’t feel happy with AWS managed version.

**Comment by Vadorequest** [comment]
If that's the case then that's too bad because in the meantime I chose a commercial company (not OSS) instead of Strapi.

**Comment by FacePalmDev** [comment]
I'm looking for a solution, what company did you choose?

**Comment by Vadorequest** [comment]
> I'm looking for a solution, what company did you choose?

I'm using Airtable and [Stacker](https://www.stackerhq.com/), both are no-code tools.
_I provide consulting services if you ever need help with those._

**Comment by derrickmehaffy** [comment]
Hi everyone, I'm going to lock this thread and instead request that everyone continue conversations about multi-tenancy on our dedicated feedback/feature request website: https://feedback.strapi.io/feature-requests/p/multi-tenancy

I would highly advise voting for the feature if it's something you are interested in.
