### ISSUE TITLE
Strapi 3.4.6 connection pool min/max not applying, Strapi falls back to default values 2 & 10

### ISSUE THREAD

**Issue by Mjb141** [strapi/strapi#14682]
### Required System information

- Node.js version: 12.22.12
- NPM version: Yarn Classic (1.22?)
- Strapi version: 3.4.6
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

Changing the connection pool min/max values doesn't appear to change the actual connection pooling limits. I've set the pool to min 0 max 50 but am still only seeing max 10 (default value) per container.

During peak traffic periods this is impacting live service performance.

### Steps to reproduce the behavior

Database config file:

```javascript
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 5432),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', 'strapi'),
        password: env('DATABASE_PASSWORD', 'strapi'),
        ssl: env.bool('DATABASE_SSL', false),
      },
      options: {
        pool: {
          min: 0,
          max: env.int('STRAPI_CONNECTIONS', 10),
          // max: 50,
        }
      }
    },
  },
});
```

The environment variable `STRAPI_CONNECTIONS` has the value `50`. I verified the environment variable was available to Strapi in terminal. Neither option allows Strapi to create more than 10 connections from each container.

### Expected behavior

Each container can scale up to 50 database connections during a load test.

### The ask

Is this a known bug? I've searched through previous issues and while there's other issues with connection pooling I can't find anything on min/max connection pools not working?

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports for v3 unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You
