### ISSUE TITLE
One way relation field disappear from content type

### ISSUE THREAD

**Issue by goras** [strapi/strapi#1477]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.1.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: Mongo v3.4.15
- **Operating system**: macOs, Ubuntu 18.04

**What is the current behavior?**
One way relation fields disappear from content type.

In the example below, the page relation field of the Menu Content Type has been removed. Any menu entries lost their connection to their related page.

**Steps to reproduce the problem**
1a. Create a new content type, name it "Page"
1b. Add a field of type string and save.

2. Add a Page entry.

3a. Create a new content type, name it "Menu"
3b. Add a field of type string.
3c. Add a field of type relation to the menu, select oneWay to Page (description text for the relation field should say "Menu has one Page"), then save.

4. Add an entry for Menu and select a page in the relation field
5. Edit or add any field of the Page Content Type and save.

**What is the expected behavior?**
The Menu Content Type should still have it's page relation field.

PS:
If I recreate the relation field on the Menu Content Type, with the same name as before, all menu entries automatically get their previous values back.

Other types of relation fields seems to work correctly. The one way relation is currently the only one i'm experiencing issues with.

**Comment by guillermodoghel** [comment]
sometimes happens and  its really annoying, I resolved it by remaking the relationship and restarting the server

**Comment by derrickmehaffy** [comment]
I was able to reproduce this by having multiple fields on the "source" of the oneway

`Model 1` (Has many fields) -> `Model 2' (Where the oneway relationship is defined, also has multiple fields)

If the "source" of the oneway only has one field then I never seem to have the issue.

**Comment by derrickmehaffy** [comment]
@guillermodoghel even deleting it and recreating it didn't fix my issue. Its hard to track down the source of this. @lauriejim are there any files that are built when you create a relation that might be caching the relations and not being updated with `oneWay` ? It seems that when this bug happens it always converts oneWay to oneToOne

**Comment by derrickmehaffy** [comment]
FYI this bug has been around since it was introduced (I just kept forgetting to report it :P )

**Comment by derrickmehaffy** [comment]
Speaking with @lauriejim on slack they are working on other stuff at the moment but he mentioned around here is where the relations are defined. The issue likely stems from around here:

mongoose: https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/index.js#L311
bookshelf: https://github.com/strapi/strapi/blob/master/packages/strapi-bookshelf/lib/index.js#L699

Just to clarify this issue is on both MongoDB and MySQL (Likley postgres too) 

First that needs to be checked is to make sure this isn't an issue isn't with the DB connectors, personally I don't think this is an issue with the frontend because defining the relations manually in the model files will result in the same problem.

**Comment by lauriejim** [comment]
I think the issue is coming from model equalizer in content type plugin.
