### ISSUE TITLE
Media Upload errors if file name contains German alphabet symbols: ä, ö or ü

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#14793]
### Required System information

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.4.7
- Database: postgresql
- Operating system: Ubuntu

### Describe the bug

If uploading an image file with a name, which contains `ä`, `ö`, `ü`, then you get an error.

### Steps to reproduce the behavior

Name a file `Apfelkuchen Stück.png` and upload it.

### Expected behavior

Successful upload
### Screenshots

![Screenshot from 2022-11-06 11-25-29](https://user-images.githubusercontent.com/45003352/200165608-fa7195dc-c3b3-445f-8a1f-dfdc3c9c8a6e.png)
![Screenshot from 2022-11-06 11-25-16](https://user-images.githubusercontent.com/45003352/200165609-d337bcb3-fdf0-48c7-9c47-e1796e9fdb08.png)

**Comment by BhuvaneshPatil** [comment]
Hi @baermathias , can you re-confirm if that issue still persists? Because I checked in my local dev env. It seemed to be working fine.
May occur due to database or OS.
DB - default (sqlite)
OS - Windows 11
![image](https://user-images.githubusercontent.com/27822551/206865355-a4620e3b-e7a8-4803-93ef-544fa92bd56d.png)

**Comment by gu-stav** [comment]
Fixed by https://github.com/strapi/strapi/pull/15151
