### ISSUE TITLE
database config connection.timezone doesn't change column type in db

### ISSUE THREAD

**Issue by doums** [strapi/strapi#14799]
### Required System information

- Node.js version: v16.17.1
- NPM version: 8.15.0
- Strapi version: 4.4.6
- Database: Postgres latest (docker image `postgres:alpine`)
- Operating system: Arch Linux

### Describe the bug

I'm not sure if it's a bug or not, but setting `connection.timezone` property in `config/database.ts` doesn't seem to change anything inside the database. I'm using Postgre, and the column type generated for datetime fields (like `{created/updated/published}_at`) are still `timestamp whitout timezone`. And, I was expecting to be set to `timestamp whit timezone`. Even for the default `utc`, I think the column type should be set to `timestamp whit timezone` but it's not. Or maybe I misunderstood the purpose of `connection.timezone` property?

**Comment by natarajanrodrigues** [comment]
Same question here.

**Comment by derrickmehaffy** [comment]
This configuration option is just for the user to tell knex what your database time zone is, you still need to change it and configure it on the database itself.

I would **strongly** recommend that you do not change your database from UTC. Doing so would be extremely anti-pattern and vastly not recommended.

Marking this is closed since it's not a bug but more of a question.
