### ISSUE TITLE
"strapi new X" fails to create database admin/password

### ISSUE THREAD

**Issue by awitherow** [strapi/strapi#1479]
**Informations**
- **Node.js version**: 8.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: Mongodb
- **Operating system**: OS X

**What is the current behavior?**

When attempting to create a new strapi, and I enter a USER and PASSWORD for the database, it fails.

```bash
[conn1] SCRAM-SHA-1 authentication failed for test on strapi from client 127.0.0.1:63724 ; UserNotFound: Could not find user test@strapi
```

**Steps to reproduce the problem**
```bash
strapi new xxx
Database Username: test
Database Password: test
```

**What is the expected behavior?**

to find the user test with password test in the database created

**Suggested solutions**
needs to create the user in the database before attempting to sign into the database

Related to #636, but not sure it should be closed just because entering "" and "" for Username and Password is the "fix"... it should not be in the prompt otherwise?

**Comment by blurdylan** [comment]
I think it'll be great if it asked first.
Because often, new mongo users do not have credentials

**Comment by derrickmehaffy** [comment]
By default mongo does not require authentication, nor will Strapi create a user, this is due to using remote databases as well as local.

Your user should be created on the database by you before attempting to run Strapi. Most software now will not create a new database user for you (because you shouldn't be sending the root user info outside localhost, or you might not have it)

For instance with mlab you are given a username and password.

Please create your user and password and be sure to enable authentication in mongodb before you create your Strapi project.

**Comment by derrickmehaffy** [comment]
It should be noted the blank username and password thing is something related to mongoDB itself. And that by default it only listens on localhost and does not setup authentication.

If you feel that is an issue please notify the mongo devs: https://github.com/mongodb/mongo
