### ISSUE TITLE
Add mongo authentication source params on project creation

### ISSUE THREAD

**Issue by wadamek65** [strapi/strapi#1486]
I would like to be able to specify the authentication source as an argument flag when using strapi new to fully automate my docker image. Couldn't find a workaround and currently have to create the project manually. Without --authenticationDatabase specified authentication through command fails and can't create a new project because it can't estabilish connection with mongo.

**What is the expected behavior?**
Be able to run strapi new with mongo authentication source flag.

**Comment by lauriejim** [comment]
Hello @wadamek65 , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check how new project creation work. https://github.com/strapi/strapi/blob/master/packages/strapi/bin/strapi-new.js#L45
And you will be able to add your params to handle your case.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by Aurelsicoko** [comment]
@wadamek65 Are we sure this is related to the core packages or to strapi-docker? Can you take a look at the issues of the strapi-docker package to see if you can't find a solution? 

https://github.com/strapi/strapi-docker/issues

**Comment by wadamek65** [comment]
@Aurelsicoko This is related to core packages. The problem is that CLI has no flag for defining the authentication database name and resolves to the default ('users' if I remember correctly) whereas setting it up manually through the usual interface it asks you what's the name of the authentication database before it sets it as default. 

I forked and changed the default in the source files to meet my needs but unfortunately I haven't had the time to contribute and create the cli flag.

**Comment by Aurelsicoko** [comment]
It would be great to open a PR if you find the time... it could help other people 👍

**Comment by lauriejim** [comment]
This option exist, user `--dbauth`
Documentation here: https://strapi.io/documentation/3.x.x/cli/CLI.html#strapi-new
