### ISSUE TITLE
Console error when language not exist

### ISSUE THREAD

**Issue by reskwer** [strapi/strapi#1489]
**Informations**
- **Node.js version**: 9.11
- **npm version**: 5.6
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongo
- **Operating system**: windows 10 LTSB

**What is the current behavior?**

language - not work, error in console 
![image](https://user-images.githubusercontent.com/8849299/42117286-6a841348-7c04-11e8-9ae3-45233e79be70.png)

**Steps to reproduce the problem**

`strapai start`

**What is the expected behavior?**

is correct switch language

**Suggested solutions**

**Comment by redni** [comment]
Hmm, file `it.json` not exist in `users-permission` translations directory. Someone created an incomplete translation or "waved" when creating it.

**Comment by lauriejim** [comment]
Please can you give the correct strapi version you are using please.
What is your issue, I don't understand. Please provide steps.
What is not working ?

**Comment by reskwer** [comment]
3.0.0-alpha.12.6

**Comment by derrickmehaffy** [comment]
@lauriejim there is an issue in the users-permission plugin. the `it.json` file doesn't exist.

See an example of my project: https://github.com/canonn-science/CAPIv2-Strapi/tree/development/plugins/users-permissions/admin/src/translations

That was generated new with Strapi 12.6.

@reskwer as for the other bugs, can you elaborate? If the password is saying its wrong its because they are different :stuck_out_tongue:

**Comment by reskwer** [comment]
@lauriejim this error could not be reproduced in 2 days. As soon as I can, I'll get the materials for you to know.
