### ISSUE TITLE
Can't move images to folders

### ISSUE THREAD

**Issue by paddotk** [strapi/strapi#14934]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.12.1
- Strapi version: 4.4.3
- Database: Dunno
- Operating system: Windows 10

### Describe the bug
Images in the media library can't be moved into folders.

### Steps to reproduce the behavior
1. Go to the Media Library
2. Create a folder
3. Select one or more images
4. Click 'Move'
5. Here the dropdown only has the option 'media library', no other folders can be selected. There doesn't seem another way to do this either (e.g. in the 'edit image' dialog)

### Additional info
I'm Super Admin

**Comment by GimpMaster** [comment]
I'm having the same issue. The new folder does is not listed in the Drop down.

**Comment by henriqueranj** [comment]
Hello all, I had the same confusion at the start. Turns out it was just the UI that was not very clear. Can you check if you're not running into the same? In the Dropdown there is a small arrow to the right side of "Media Library". See Screenshot below
![image](https://user-images.githubusercontent.com/35765412/205626678-3258d1c9-7a59-49ac-a800-6a3041168e2e.png)

After you press it you should be able to see other folders and keep digging into them.
![image](https://user-images.githubusercontent.com/35765412/205626823-74154c5f-715a-4f6c-b7f6-917298c1793d.png)

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/make-folder-moving-interface-easier-to-see-nested-folders
