### ISSUE TITLE
Very strange behavior in local development: localhost vs. 127.0.0.1

### ISSUE THREAD

**Issue by KoljaL** [strapi/strapi#15012]
### Required System information

- Node.js version: v16
- NPM version: 18.9
- Strapi version: v4.5.1
- Database: SQlite
- Operating system: MacOS
- Frontend: SvelteKit

### Describe the bug 
I liked to use the route `api/auth/local` to perform a login.

First I tested the route in VSC-Thunder-Client: 
`http://localhost:1337/api/auth/local`-> **works**.

Then from the browser view `+page.svelte`:
```javascript
		let response = await fetch('http://localhost:1337/api/auth/local', {
			...
		});
```
-> **works**.

Then from the server: `+page.server.ts`, 
Code as from the browser -> `fetch failed TypeError: fetch failed`.

Then, just by chance, again from the server: 
```javascript
		let response = await fetch('http://127.0.0.1:1337/api/auth/local', {
			...
		});
````
-> **works**.

What is the difference between `localhost` and `127.0.0.1` for Strapi ?
And is that anywhere in the documentation?
If not PLEASE repost, this very easy to fix bug took me hours to fix.

**Comment by derrickmehaffy** [comment]
Hi @KoljaL I believe the issue here is the odd way that Apple manages their local hosts file. For example on Linux:

![image](https://user-images.githubusercontent.com/8593673/209365400-0d2609a3-0cbc-4cd0-81a8-977e973e5e64.png)

On Linux by default `127.0.0.1` has a static mapping to `localhost` however I believe on most Macs this is actually the IPv6 loopback device `::1`. If you want you can try to verify this by using the same command I did here to look at your hosts file: `cat /etc/hosts`

For now I'll mark this issue as closed as there isn't much we can do from our side since this is more of an OS issue. (though feel free to respond here if you like :) )
