### ISSUE TITLE
AWS Cognito Provider: error=Grant: missing session or misconfigured provider

### ISSUE THREAD

**Issue by snehil2112** [strapi/strapi#15071]
- Node.js version: v16.17.0
- NPM version: 8.18.0
- Strapi version: 4.3.7
- Database: Postgres
- Operating system: Windows

Configured the AWS cognito provider in strapi admin panel following the official documentation (https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers)

After successful login on cognito UI, getting redirect to the http://localhost:1337/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider

**This is my provider config**
![image](https://user-images.githubusercontent.com/57523460/205490484-50918fd1-6999-44ed-afba-465b6685c90e.png)

**This is the server config file as indicated in the document**

`
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('', 'http://localhost:1337'),
  app: {
    keys: env.array('APP_KEYS'),
  }
});
`

I have tried the login in both normal and private tabs but the error is same. I am not using any proxies like ngrok, etc.

**Comment by derrickmehaffy** [comment]
You are missing the session middleware: https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.0.0-to-4.0.6.html#fixing-the-breaking-changes

Marking as closed as this was because we hadn't finished converting the session middleware so initial v4 apps didn't have it.
