### ISSUE TITLE
Missing user role in beforeUpdate lifecycle hook in plugin::users-permissions.user model

### ISSUE THREAD

**Issue by WebShapedBiz** [strapi/strapi#15103]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: SQLite
- Operating system: elementaryOS 6.1 Jólnir (based on Ubuntu 20.04)

### Describe the bug

I'm not 100% sure that this is a bug so please forgive me if that's the case.

Anyhow, I need to get a User role in the `beforeUpdate` lifecycle hook in `plugin::users-permissions.user` model, but I'm getting an empty array.
This is the console log of `event.params.data` in `beforeUpdate` lifecycle hook:
```
{
  id: 62,
  username: 'My Name',
  email: 'my-email@gmail.com',
  confirmed: true,
  blocked: false,
  mailing: false,
  mailing_lista: 'mailinglist@mailgun.org',
  role: { disconnect: [], connect: [] },
  updatedBy: 1,
  updatedAt: 2022-12-07T07:38:19.957Z
}
```

What's puzzling me is that I have no problem getting the User role from the `beforeCreate` lifecycle hook:
```
async beforeCreate(event) {
  const { data, where, select, populate } = event.params;
  // find role name
  const roleId = data.role.connect[0]["id"];
  const getRole = await strapi.db
    .query("plugin::users-permissions.role")
    .findOne({
      where: { id: roleId },
    });
    ...
}
```
Here the `event.params.data` contains `role: { disconnect: [], connect: [ [Object] ] },`

That same code in `beforeUpdate` lifecycle hook returns an error :
```
error: Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
```

**Comment by WebShapedBiz** [comment]
Actually, I didn't solve it because `strapi.entityService.findOne` is fetching stored data which I don't want. I need to have the role of the `beforeUpdate` object

**Comment by WebShapedBiz** [comment]
Update:
The `role` object of `event.params.data` is not populated only if the user changes the Username. I don't know if that's intentional, but apparently, that's the case.

**Comment by derrickmehaffy** [comment]
This is intentional as the lifecycles typically are not aware of relations, the users-permissions is a special case since we set the role during the register phase: 

https://github.com/strapi/strapi/blob/d28ec979176bacb8661f7bbb38fb616f7b530ba1/packages/plugins/users-permissions/server/controllers/auth.js#L289-L291

https://github.com/strapi/strapi/blob/d28ec979176bacb8661f7bbb38fb616f7b530ba1/packages/plugins/users-permissions/server/controllers/auth.js#L326-L334

https://github.com/strapi/strapi/blob/d28ec979176bacb8661f7bbb38fb616f7b530ba1/packages/plugins/users-permissions/server/services/user.js#L37-L42

---

Generally you would have access to the entire request body via the new request context that is mounted globally: https://docs.strapi.io/developer-docs/latest/development/backend-customization/requests-responses.html#accessing-the-request-context-anywhere (basically the koa ctx with our injected custom objects). You should be able to access this from within a lifecycle if needed.

I'll mark this as closed since it's not really a bug but more of a question, but hopefully what I mentioned helps

**Comment by WebShapedBiz** [comment]
Thank you very much @derrickmehaffy for your time and effort in writing this detailed answer.
