### ISSUE TITLE
[Bug] Unable to Customize Strapi the Dashboard

### ISSUE THREAD

**Issue by csharpee** [strapi/strapi#15203]
### Required System information

The Strapi version I am using is : **4.5.4**. 
Yarn version: ` v1.22.11`
Node version: `v14.21.1 `

### Describe the bug

I need to remove all elements on this page.

The documentation is outdated or I am  doing something wrong.

I had this working in June 2022 without any trouble. 

### Steps to reproduce the behavior

1.     Go to 'Admin Dashboard'
2.     Click on 'Stay on the default home page '
3.     Scroll down to 'Scroll down the Dashboard, the two containers have links not removed from the dashboard as well '
4.     See the screenshot

### Expected behavior

I want to remove the default page links and add our custom UI js component according to the product design theme.

### Screenshots

![Screenshot from 2022-12-16 13-36-04](https://user-images.githubusercontent.com/18726788/208195761-635168af-f3d8-477b-a815-216eb04941d3.png)

### Code snippets

This removed notifications and video tutorials from Strapi admin dashboard for me on version 4.11.1
`src/admin/app.js`
```
export default {
  config: {
        // Disable video tutorials
        tutorials: false,
        // Disable notifications about new Strapi releases
        notifications: { releases: false },
...
    }
}
```

### Additional context

Documentation: https://docs.strapi.io/developer-docs/latest/development/admin-customization.html

This is also a duplicate post, but from another time period.

https://github.com/strapi/strapi/issues/13049

**Comment by ronronscelestes** [comment]
hi @csharpee, thank you for sharing this issue 😊
I wouldn't say this is a bug since customizing Strapi homepage is not possible today in v4
there is a Canny feature request existing [here](https://feedback.strapi.io/feature-requests/p/customize-the-admin-dashboard-welcome-page-v4) that you can upvote though!

in the meantime (as the [duplicate](https://github.com/strapi/strapi/issues/13049) issue you mention says) path-package is the only workaround until we implement this feature 👀

>This removed notifications and video tutorials from Strapi admin dashboard for me on version 4.11.1
>src/admin/app.js

those configurations (`tutorials` and release `notifications`) do not concern the homepage customization and are working on my side after testing locally

let me know if there's still something unclear for you 🙂

**Comment by csharpee** [comment]
Hi @ronronscelestes and thank you for your input. 

It is clear that it isn't *possible* in v4. I had this working before, I must have manually changed things in the node_modules. 

There could be an option in the settings that removes the *advertising* and has a clean interface for admins and editors. I understand this *welcome* dashboard is welcoming to newcomers, but it would be great to disable these welcoming features when they become more of a distraction than beneficial to the editor. 

Having lots of things to click on and read is overwhelming and we should have a simple option that at the least hides these nuances; maybe by a simple css `display: none`. 

I have posted my feedback on Canny.
