### ISSUE TITLE
There is no "Add Content Type", I can't add single Type

### ISSUE THREAD

**Issue by Hakiba** [strapi/strapi#15269]
### Required System information

- Node.js version: 16.17.1
- NPM version: 8.15.0
- Strapi version:4
- Database: MySQL

### Describe the bug

This strapi app is deploy on Nodejs server (o2switch) using mysql database. Everything is working but I can't add content type...

I thought I understood that it was necessary to launch it in local, but I can't redeploy it... I very lost, how can I use this CMS with nodejs for a nextjs app please ?

### Expected behavior

I want to add some single page in order to configure it for my client

### Screenshots
<img width="1438" alt="Capture d’écran 2022-12-26 à 17 07 43" src="https://user-images.githubusercontent.com/41543008/209566485-2d595852-2f74-47df-baff-94ba3790d478.png">

**Comment by derrickmehaffy** [comment]
This is either because you are not in the development environment or you aren't using the `yarn develop` / `npm run develop`. We don't allow modifying the content-schema in production as detailed in this FAQ: https://docs.strapi.io/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
