### ISSUE TITLE
 Images uploaded with customized upload service cannot be cropped

### ISSUE THREAD

**Issue by uykalkan** [strapi/strapi#15281]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: sqlite
- Operating system: macos ventura m1 silicone

### Steps to reproduce the behavior

1. Create New Strapi Project
2. Add custom upload provider in project
3. Go Media Library
4. Upload an Image 
5. Edit Assets
6. Click Crop Button

### Screenshots
![image](https://user-images.githubusercontent.com/10650863/209821551-602e4a1d-fb46-4155-9376-7267197fb3e8.png)

**Comment by derrickmehaffy** [comment]
We would need information on the custom provider as there are several community providers that don't have this issue and we can't test something that we don't know how it works.

Closing for now until more information can be provided.

**Comment by jaymcguinness** [comment]
We've replicated this using the s3 upload plugin - the circumstances under which it occurs are quite specific:

* pre-signed URLs are used - so for S3 plugin, that's where the ACL is private
* the URL's are served direct from S3 - eg. *.s3.<region>.amazonaws.com rather than the same domain.

I imagine any provider using signed URLs will be impacted.

The issue is caused by CropperJs adding an additional 'timestamp' parameter to cross-origin image requests.  Adding an additional querystring param to a signed URL will break the hash and in turn, prevent the image from loading.

https://github.com/fengyuanchen/cropperjs/blob/b122bb6769e867e867ee6a913e12231cbcdf5463/src/js/cropper.js#L166

For many users, this won't present an issue if they hosting the images from the same domain.  eg. perhaps they are using Cloudfront CDN or something else to reverse proxy the s3 bucket onto the same domain.

But for the scenario, where the bucket is private and pre-signed URLs are being used on the *.s3.<region>.amazonaws.com domain, the cropper will fail to work.

I'll create a pull request for this in time, but the steps to resolve are:

- Add a CORS policy to s3 bucket which allows GET to your origin (or * if just testing)

The asset preview image tag needs the crossOrigin="anonymous" attribute added.

```js
in \strapi\packages\core\upload\admin\src\components\EditAssetDialog\PreviewBox\AssetPreview.js

From 
return <img ref={ref} src={url} alt={name} {...props} />;

To
return <img ref={ref} src={url} alt={name} {...props} crossOrigin="anonymous" />;
```

**Comment by InSecker** [comment]
Still having this problem. Is there any new open issue on that ?

When I click on crop button the request respond with 403. As I remove the 'timestamp' parameter the request is responding find.

I'm using S3 uploads with pre-signed URLs.
Strapi 4.17.1

**Comment by Adzouz** [comment]
Hi there,
Thanks for reporting the issue 🙏 I know it's a very old one but I just merged a fix with this PR: https://github.com/strapi/strapi/pull/24946 and it will be released next Wednesday (March 11th) in the next Strapi release 🚀
