### ISSUE TITLE
v4.5.5 breaks icons

### ISSUE THREAD

**Issue by xanghyr** [strapi/strapi#15291]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2 (not using it)
- Yarn version: 1.22.19
- Strapi version: 4.5.5
- Database: mysql
- Operating system: Ubuntu 22.04.1

### Describe the bug

Since I updated to Strapi v4.5.5 the icon from my components are "broken" and are all showing the same default box icon in my dynamic zone.

### Steps to reproduce the behavior

1. Update to 4.5.5
2. Create component with an icon
3. Add component to dynamic zone in a collection
4. Open dynamic zone in content manager
5. See error

### Expected behavior

Have the right icon.

### Screenshots
Strapi 4.5.4, just before the update
![before_4 5 5](https://user-images.githubusercontent.com/28865185/209938828-a8d35bca-2730-42a8-bc0a-e6e99b1dbe61.png)

Strapi 4.5.5, right after updating
![after_4 5 5](https://user-images.githubusercontent.com/28865185/209938836-bb3eb978-d678-4755-b66e-9d143cd21b61.png)

**Comment by derrickmehaffy** [comment]
Hi @xanghyr this was an intentional change as we wanted to remove icons from Dynamic Zones and Components to cut down on the admin size by removing font-awesome (was a huge package) and very few people were actually using the icons.

https://github.com/strapi/strapi/pull/15133

I've set this as a discussion to see if we can provide a workaround for those that still do want to set icons (maybe through some override of the content-type schema? 

cc @gu-stav

**Comment by laurenskling** [comment]
I came here because I also saw my icons changed to a default. I would really like to be able to set icons in some way, so if can get a new system in place that would allow it in one way or the other, that would be really awesome.

**Comment by gu-stav** [comment]
@laurenskling Do you mind opening a feature request on https://feedback.strapi.io ?

**Comment by laurenskling** [comment]
https://feedback.strapi.io/customization/p/icons-for-components

**Comment by derrickmehaffy** [comment]
Thanks, will close this in favor of the feature request.
