### ISSUE TITLE
Memory issue with strapi v4.5.3 on image upload

### ISSUE THREAD

**Issue by tvvignesh** [strapi/strapi#15309]
### Required System information

- Node.js version: 18.0
- Strapi version: 4.5.3
- Database: PostgresSQL
- Operating system: Ubuntu 22.04

### Describe the bug

Strapi memory usages spikes during image upload to the media library as seen in the graph below. I tried reuploading after strapi came back up again and it crashed again. In my case, I had set a limit of 500 MB and strapi went way beyond and crashed the kubernetes pod (It went from 280 MB to 500 MB)

![image](https://user-images.githubusercontent.com/1165845/210172896-ca36a5e4-f7df-4396-8ba0-a1e1b95414ce.png)

### Steps to reproduce the behavior

- Try uploading this image using the media library
![logo](https://user-images.githubusercontent.com/1165845/210172902-7f273240-a65a-489a-a253-b86ea1ce7d6d.png)

### Expected behavior

Strapi must not use a large amount of memory during image processing

**Comment by derrickmehaffy** [comment]
This is due to the fact we use buffers so it must temporarily store the image in the node memory before it flushes it to disk and optionally buffer/stream the file to a storage provider.

You are using a deployment that is not supported, we recommend at minimum of 2GB of ram and a recommendation of 4GB of ram for deployments (including production). See the recommended specs here: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html#general-guidelines
