### ISSUE TITLE
Can't get repeatable component value from database in beforeUpdate hook before updating collection record

### ISSUE THREAD

**Issue by Cadary** [strapi/strapi#15304]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.14.0
- Strapi version: 4.5.4
- Database: PostgreSQL
- Operating system: Windows 10

### Describe the bug

Can't get repeatable component value from database in beforeUpdate hook before updating collection record.

### Steps to reproduce the behavior

1. Update collection entry that triggers `beforeUpdate`.
2. Query component data from the database.

### Expected behavior

The query returns the data that was before the record was updated.

### Code snippets
```
// src/api/order/content-types/order/lifecycles.js

module.exports = {
  beforeUpdate: async (event) => {
    const order = await strapi.entityService.findOne('api::order.order', event.params.where.id, {
      populate: {
        products: true, // repeatable component
      },
    });

    console.log(order); // { id: 1, ... , products: [{ id: 1, amount: 2 }] }
  },
};
```

### Additional context

I was trying to get the original data to compare it with the new data. In my case, in order to decide how much to change the products stock on order update.

Order collection schema

```
{
  "kind": "collectionType",
  "collectionName": "orders",
  "info": {
    "singularName": "order",
    "pluralName": "orders",
    "displayName": "Order",
    "description": ""
  },
  ...
  "products": {
    "type": "component",
    "repeatable": true,
    "component": "order.product",
    "min": 1
}
```
Product component schema
```
{
  "collectionName": "components_order_products",
  "info": {
    "displayName": "Product",
  },
  "options": {},
  "attributes": {
    "amount": {
      "type": "integer",
      "min": 1,
      "default": 1,
      "required": true
    },
    "product": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::product.product"
    }
  }
}
```
Product collection schema
```
{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "singularName": "product",
    "pluralName": "products",
    "displayName": "Product",
    "description": ""
  },
  ...
  "stock": {
    "type": "integer",
    "min": 0
  },
```
Issue https://github.com/strapi/strapi/issues/13047 looks similar.

**Comment by derrickmehaffy** [comment]
Hi @Cadary this is well known and currently intended. There is an abstraction layer that handles relationships currently so components, dynamic zones, and media fields are all relations and thus are basically content-types at this layer.

If I take from one of our architecture diagrams: https://miro.com/app/board/o9J_kkD8OK8=/?share_link_id=36896086019

Specifically here:

![image](https://user-images.githubusercontent.com/8593673/210620443-0287a37f-2a63-478b-9feb-e2d87391327d.png)

Since the lifecycles wrap the raw DB queries, they wrap the actual transactions against the SQL database (basically right before they are converted from JS to SQL syntax). Thus there is no data to populate or interact with at this layer. We would like to implement lifecycles for components as well but currently that is considered a feature request here: https://feedback.strapi.io/feature-requests/p/lifecycle-hooks-for-components

For now I'll mark this as closed since it's not a bug but more so a feature request, if you have any questions or concerns please do share them on that feedback page.

**Comment by Cadary** [comment]
Thank you for the explanation.

**Comment by pcriadoperez** [comment]
Is there any work around for this? I though about extending the controller but that doesn't work for both the Rest and graphql
