### ISSUE TITLE
MongoDB connection error with its new driver

### ISSUE THREAD

**Issue by mohamadzali** [strapi/strapi#1532]
**Informations**
- **Node.js version**: 10.5.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: MongoDB (v: 3.6.5)
- **Operating system**: ArchLinux

**What is the current behavior?**
Always got this error when creating new project:
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

**Steps to reproduce the problem**
first step in creating a new project (by running "strapi new pname")

**What is the expected behavior?**

**Suggested solutions**
I found the solution here:
https://www.thanhphu.tech/2018/05/23/about-mongos-usenewurlparser-warning/

he told: 
You can resolve the above warning by changing from "MongoClient.connect("mongodb://localhost:27017")" to "MongoClient.connect("mongodb://localhost:27017", { useNewUrlParser: true })"

**Comment by lauriejim** [comment]
Hello @mohamadzali , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

It's an easy issue to fix. You can update `strapi-mongoose` package.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md
