### ISSUE TITLE
Id column out of range

### ISSUE THREAD

**Issue by j4m3sb0mb** [strapi/strapi#15339]
### Required System information

- Strapi version: 4.5.5
- Database: MySql

### Describe the bug

I think that the default ID type is not enough large, I have this error on the console:

```
ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'id' at row 1
```

### Steps to reproduce the behavior

Try to create an entity with 70000000000 as id

### Expected behavior

It should create entities with very large ids

**Comment by derrickmehaffy** [comment]
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html

> [INT[(M)] [UNSIGNED] [ZEROFILL]](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html)

> A normal-size integer. The signed range is -2147483648 to 2147483647. The unsigned range is 0 to 4294967295.

We have this implemented as an unsigned integer (especially since bigint support in javascript is not great): 

https://github.com/strapi/strapi/blob/08cf81512b421af1da1b3423c729fa88999e6d4f/packages/core/database/lib/schema/schema.js#L35-L42

Making the maximum number of entries in a collection-type to be 4,294,967,295 and considering that ~4.2 billion entries is far more than what most people need it's an extremely arbitrary requirement. If you want to vote for UUIDs as the primary key, please see this feature request: https://feedback.strapi.io/developer-experience/p/allow-customization-of-primary-key-id-type-and-name
