### ISSUE TITLE
Wrong alphabetical order of content types in Content Manager

### ISSUE THREAD

**Issue by radoslavzeman** [strapi/strapi#15342]
### Required System information

- Node.js version: 16.15.0
- NPM version: 7.24.2
- Strapi version: 4.5.5
- Database: postgres
- Operating system: macOS Monterey

### Describe the bug

The order of content types in Content Manager is not alphabetical. It puts special letters like Č, Š, ... at the end. On the other hand, Content type build have correct order. See screenshots.

### Expected behavior

Correct alphabetical order in Content Manager and Content type builder.
Č should go after C and so on for other letters.

### Screenshots

![image](https://user-images.githubusercontent.com/19418224/210523734-4a6687e4-4ff0-419f-a821-afcb0cc8d844.png)
![image](https://user-images.githubusercontent.com/19418224/210523755-3b3ba7da-0551-4c47-9bc4-3b27d6f6a055.png)

### Additional context

It's probably a problem just for slavic languages 🙂

**Comment by derrickmehaffy** [comment]
I was testing in russian and it appears that several languages will just be thrown to the bottom 

It's not based on the response from `strapi.contentTypes` that the CTM uses here:

https://github.com/strapi/strapi/blob/08cf81512b421af1da1b3423c729fa88999e6d4f/packages/core/content-manager/server/services/content-types.js#L24

Because that response does properly put the value in order (ish) since it converts it to english.

![image](https://user-images.githubusercontent.com/8593673/210634098-10114153-1709-4e93-9ebc-996c2e55f826.png)

![image](https://user-images.githubusercontent.com/8593673/210634139-7801e4db-22e1-4f61-ba9e-dfbe689e1327.png)

**Comment by radoslavzeman** [comment]
Thank you for the fix!
