### ISSUE TITLE
Admin Panel turns white when changing locales in admin/app.js

### ISSUE THREAD

**Issue by shuffgy** [strapi/strapi#15345]
### Required System information

- Node.js version: 16.11.1
- NPM version: 8.0.0
- Strapi version: 4.5.5
- Database: postgresql
- Operating system: wsl2/ubuntu

### Describe the bug

![image](https://user-images.githubusercontent.com/17125448/210586191-289d8289-0dad-4578-9941-5462523eb715.png)

I just wanted to change the logos and favicons and discovered, that i can change the locales to german.
After removing `.cache` and `build` folder, the admin screen turnes white with the error 

`TypeError: Cannot convert undefined or null to object`

### Steps to reproduce the behavior

```js
import favicon from './extensions/favicon.png';
import logo from './extensions/Strapi-Backend-Icon.png';

export default {
  config: {
    // locales: ['de'], <-- activating this results in TypeError: Cannot convert undefined or null to object
    auth: {
      logo: logo,
    },
    menu: {
      logo: logo,
    },
    head: {
      favicon: favicon,
    },
  },
  bootstrap(app) {
    console.log({app, favicon, logo});
  },
};
```

### Expected behavior

If i'm right, strapi seems to support german locales with 'de' so i did not expect a white screen and/or errors.

**Comment by betoflakes** [comment]
Same here.

**Comment by BabyDino** [comment]
Same

**Comment by 1612647** [comment]
Facing same issue, any solutions?

**Comment by gu-stav** [comment]
@shuffgy I wasn't able to reproduce the issue. Could you share with me what the code throwing the error is (by clicking on the filename top right corner of your error message)? It is hard to say when it is minified.

**Comment by thijsbrouwers** [comment]
I'm facing the same issue. It happens when adding particular locales to the admin panel in `admin/app.js`. I've tested some and from these the following make the app crash: `ar`, `es`, `nl`, `pt`

The full error message is as follows: 
```
index.js?d59a:2 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at prefixPluginTranslations (index.js?d59a:2:17)
    at eval (index.js?3888:89:43)
    at Array.map (<anonymous>)
    at registerTrads (index.js?3888:87:24)
    at eval (StrapiApp.js?54e4:360:18)
    at Array.map (<anonymous>)
    at StrapiApp.loadTrads (StrapiApp.js?54e4:356:8)
    at async run (index.js?ad03:68:3)
```

Also I verified if the translation files for the above locales are present in `node_modules/@strapi/admin/admin/src/translations` and if the locale codes are exported from `node_modules/@strapi/admin/admin/src/translations/languageNativeNames.js`

**Comment by gu-stav** [comment]
@thijsbrouwers Could you list the steps you do in order to crash the admin app (rebuilding, restarting server ...), so I can try again reproducing the issue?

**Comment by thijsbrouwers** [comment]
It crashes when:
* you have the development server running and update the locales array.
* update locales array, rebuild and restart server.

Both when running with or without the `--watch-admin` flag

**Comment by gu-stav** [comment]
Thank you. I'll re-open and see if I can reproduce it today/ 👍🏼

**Comment by trustos** [comment]
Hello,
I had a similar issue today.
Are you by any chance using the Strapi Comments plugin? [https://market.strapi.io/plugins/strapi-plugin-comments]
My issues was that by adding a custom locale while the plugin is active, the loadTrads method was throwing an error.
This was in my case due to the fact that the plugin only supports the following languages: en, fr, tr and "pt-BR".

I suggest set your custom locale and try to disable the plugin(if you are using it) to test if that might help.

**Comment by LeoMoshko** [comment]
> Hello, I had a similar issue today. Are you by any chance using the Strapi Comments plugin? [https://market.strapi.io/plugins/strapi-plugin-comments] My issues was that by adding a custom locale while the plugin is active, the loadTrads method was throwing an error. This was in my case due to the fact that the plugin only supports the following languages: en, fr, tr and "pt-BR".
> 
> I suggest set your custom locale and try to disable the plugin(if you are using it) to test if that might help.

I had a similar issue with strapi 4.8.2 and Strapi Comments plugin 2.2.9. With version 2.2.3 all work

**Comment by Boegie19** [comment]
Since this seems to be an issue with a strapi plugin please open a issue on that plugins repo.
