### ISSUE TITLE
CLI Generate an API 

### ISSUE THREAD

**Issue by sbacem** [strapi/strapi#154]
How generate api with 2 controller and 2 models like api user 

When generate api by default, i have a join between user and my modele
i think it's better and more logic to make it in option when generate api.
How remove to generate it by default ?

**Comment by Aurelsicoko** [comment]
@sbacem: You can't directly generate an API with 2 controllers and models like the User's API through the CLI. To do that, you have to execute the following command `strapi generate api <YourApiName>` two times. Then, copy/paste the files of the second API into the first one. I know this is not ideal but this is the better solution I have for now.

As you said, the link between the User model and the others should be optional. The link will be removed on the next version because the User's API will not be required.

Currently, we can't generate a controller, model or service into a specific API's folder. This could be very interesting. This is not a priority but this is a very interesting use case. I will add it in the future for sure. So, I put this issue in the v3 milestone. Thanks for your contribution :)

**Comment by sbacem** [comment]
@Aurelsicoko,  thank you for the answer :+1: .
I wait impatiently v3

**Comment by Aurelsicoko** [comment]
You're welcome! We are really excited too. I hope you will enjoy it. Stay tuned!
