### ISSUE TITLE
Strapi default wysiwyg editor cuts preview in expand mode

### ISSUE THREAD

**Issue by Przemek625** [strapi/strapi#15407]
![image](https://user-images.githubusercontent.com/15988345/211787970-13f47792-475c-4afa-bb85-8a4391c3dc9f.png)

In long text the preview cuts content after the header. 

As you can see the "some text that should exist here" is missing. I can't simply scroll to that area. It looks that the height is calculated wrong...

Steps to reproduce:

1. Add long content with multiple headers and paragraphs  inside RichText field
2. Click Expand
3. You will notice that on the right hand side preview miss rendered content

I tested this on both Firefox and Chrome. I use chrome in Version 108.0.5359.124 (Official Build) (64-bit). I use Ubuntu as my operating system.

**Comment by gu-stav** [comment]
@Przemek625 Thank you for opening the issue. The styling looks off indeed, but I was able to scroll the preview panel in each browser. Did you have issues with that too or did you only refer to the rendering of the content?

**Comment by raph941** [comment]
Hello @gu-stav,
Thank you for addressing the styling concerns. However, I've observed that the scrollability issue previously brought to light in this issue is still present.
While the preview panel is scrollable, a portion of the bottom content (equivalent to 3rem based on the header height) is being cut off. Please take a look at a quick demo below.


https://user-images.githubusercontent.com/45232708/214508780-91a6621c-0682-4ac2-9c5c-95312c8a4c6f.mov

Here's a PR to resolve it: #15560. please take a look.

**Comment by raph941** [comment]
Hello @gu-stav,
Thank you for addressing the styling concerns. However, I've observed that the scrollability issue previously brought to light in this issue is still present.
While the preview panel is scrollable, a portion of the bottom content (equivalent to 3rem based on the header height) is being cut off. Please take a look at a quick demo below.


https://user-images.githubusercontent.com/45232708/214508780-91a6621c-0682-4ac2-9c5c-95312c8a4c6f.mov

Working on PR to resolve it.

**Comment by gu-stav** [comment]
@raph941 I've opened a PR as a follow-up for yesterday: https://github.com/strapi/strapi/pull/15563 Would you like to check and verify it is working as expected? 🙏🏼

**Comment by raph941** [comment]
Great, thanks @gu-stav. 
The follow-up PR resolves the highlighted issues and works as expected 🙌.
