### ISSUE TITLE
The DateTimePicker component UI in the design-system referenced by the publisher plug-in in the helper-plugin in the stratpi is not displayed correctly

### ISSUE THREAD

**Issue by guoduhw** [strapi/strapi#15432]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by guoduhw** [comment]
The DateTimePicker component UI in the design-system referenced by the publisher plug-in in the helper-plugin in the stratpi is not displayed correctly
As shown in the figure below:

![image](https://user-images.githubusercontent.com/4437474/212219492-68883c9f-07f8-4b8e-b19e-bc693ac51b18.png)

error code:
\node_modules\@strapi\design-system\dist\DatePicker\DatePickerTh.js

![image](https://user-images.githubusercontent.com/4437474/212219694-8a7c926f-fc23-4e07-8ec9-20d410980ac7.png)


Correct writing:

![image](https://user-images.githubusercontent.com/4437474/212219795-131423f3-11e4-4d7d-bcf1-8759e69943e9.png)

![image](https://user-images.githubusercontent.com/4437474/212219893-0c9ef539-fb3c-4d20-9087-9621321b5c8c.png)

**Comment by guoduhw** [comment]
期待问题能够早日修复，我的联系方式
houwen1@lenovo.com

**Comment by guoduhw** [comment]
I hope the problem can be fixed as soon as possible. My contact information

houwen1@lenovo.com

**Comment by simotae14** [comment]
Hello @guoduhw and sorry for the late response. I saw your problem and I tried to replicate it, the problem is not with the DateTimePicker but, instead with the DatePicker that is used inside it. Basically, to create the calendar we create a Date for every single day of the week and then we format it and show just the first two characters, as you can see in this pic for the 'en' locale
<img width="261" alt="Schermata 2023-02-28 alle 11 01 19" src="https://user-images.githubusercontent.com/2589748/221821475-76300366-8403-4d05-9550-f2b4f8529af1.png">
I think with other alphabets the solution provided doesn't work (as in your case)

**Comment by simotae14** [comment]
Can I ask you your locale just to replicate your same situation?
I don't know if, in your case, showing 3 characters can solve the situation
<img width="266" alt="Schermata 2023-02-28 alle 11 10 42" src="https://user-images.githubusercontent.com/2589748/221823487-8d118aea-74aa-4e72-897c-b205c834a16d.png">
please let me know, have a good day

**Comment by simotae14** [comment]
Hello, @guoduhw I have not received your response and because this issue is related to a specific locale I don't think it is a good idea to add your suggested changes because otherwise, we will have problems in a lot of other locales.
If you want to try the solution with 3 chars just reopen an issue and we can do it.

Thanks again!

**Comment by PearpearS** [comment]
I have encountered the same problem, our region is China
