### ISSUE TITLE
Can’t import react component from @strapi/admin into custom plugin

### ISSUE THREAD

**Issue by boazpoolman** [strapi/strapi#15452]
### Required System information

- Node.js version: 14.19.3
- NPM version: 6.14.17
- Strapi version: 4.5.5
- Database: sqlite
- Operating system: Mac OS 12.6.2

### Describe the bug

**Disclaimer**
I know this is not a documented feature in any way, but I was testing a theory for a new plugin I’m working on and stumbled upon this issue. If this is not the place to ask I will try my luck on the Discord, just let me know.

**The issue**
I’m trying to import a react component from the `@strapi/admin` package into a custom plugin. Like so:

`./src/plugins/test/admin/src/pages/App/index.js`
```
import EditView from '@strapi/admin/admin/src/content-manager/pages/EditView';
```

Though when I do so I will get the following error:
<img width="853" alt="Screenshot 2023-01-14 at 21 35 51" src="https://user-images.githubusercontent.com/9551934/212495690-aae12d75-b609-4e9a-b731-6eb8ddcfc907.png">

And what was especially odd to me was that I am able to import other react components from other strapi packages. For example this one:
```
import Icon from '@strapi/plugin-content-type-builder/admin/src/components/AttributeIcon';
```

So I'm not sure what is the difference between these two components/packages.

### Steps to reproduce the behavior

1. Setup a fresh install of Strapi
2. Create a new custom plugin `yarn strapi generate plugin`
3. Enable the plugin in the `./config/plugins.js` file
4. Import the react component to the `./src/plugins/plugin-name/admin/src/pages/App/index.js` file:
```
import EditView from '@strapi/admin/admin/src/content-manager/pages/EditView';
```
5. Try to build and run Strapi
6. See the error

### Expected behavior

The ability to import this reusable component and use it on a page in a custom plugin.

**Comment by joshuaellis** [comment]
Hey @boazpoolman we don't support _any_ components being used outside of `@strapi/admin` any components that are exported from `@strapi/helper-plugin` or `@strapi/design-system` are available for plugin creators to use. But not from from the `@strapi/admin` package – this is to avoid breaking the ecosystem when we make our own changes to the admin components.

Is there a reason you thought to use a component from there?

**Comment by boazpoolman** [comment]
Thanks for the response @joshuaellis. I completely get that this is a unsupported feature and I'm completely OK with updating my plugin whenever you guys make a change to the component(s). I just don't understand why I'm unable to import this specific component. The error suggests that the file can't be parsed as a react file.

I'm building a rather large plugin that provides multiple content types with it. In an attempt to have all functionality of the plugin be grouped under a single menu item I tried to implement the edit view of these content types on a custom plugin react page and then hiding them from the content manager. That way the plugin functionality won't be scattered across the strapi admin.

It is by no means a requirement for my plugin but it would be really neat to be able to do this.

**Comment by joshuaellis** [comment]
I'll bring this up and debate whether we want to look at supporting this (it would be feature request) – however, IMO it's not something I think we should support currently because your plugin doesn't incl. a specific version of `@strapi/admin` and currently the FE is not bundled, so if we change that component it _could_ break your plugin and I would prefer to avoid this.

I'll keep you updated.

**Comment by joshuaellis** [comment]
I've spoken to the product team & we're not going to support this because it adds a lot of overhead and constrictions to our work – however, IF there is a specific component e.g the table or an input that you want to use that is not available in the `helper-plugin` or `design-system` then please open a specific issue to discuss this :)

**Comment by boazpoolman** [comment]
Thanks for considering this josh 🙌

**Comment by hoang-innomize** [comment]
We also looking for this but maybe in a different way, instead of importing the components, we are looking for a way that we can consolidate and centralize the content managers of collection types that we defined in our plugin without recreating the same functions as the content manager has built. This is to improve the organization and centralization. Make it easy to manage content for a given plugin without back and forth between the plugin and content manager places.

I thought about the iframe, but when embedding the iframe, right now we cannot high the sidebar or content manager left menu. We expect only to embed or show the content manager UIs such as List screen, and CRUD screens.

I appreciate hearing approaches in case someone manages to do the same thing.

**Comment by boazpoolman** [comment]
I was actually trying to achieve the same thing as @hoang-innomize at the time.

Moving the content manager for a specific content type to my plugin interface to properly consolidate it from the "normal" content types, without recreating the entire form. Never made it work though sadly, but it would be amazing if this would still be possible in some way.
