### ISSUE TITLE
Cant build Admin Panel

### ISSUE THREAD

**Issue by BroTrue** [strapi/strapi#1552]
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: MongoDB
- **Operating system**: Debian

**What is the current behavior?**

When I try to build admin panel `npm run setup` got error 
```
MongoError: command listIndexes requires authentication
    at queryCallback (/strapi/packages/strapi-mongoose/node_modules/mongodb-core/lib/cursor.js:247:25)
    at /strapi/packages/strapi-mongoose/node_modules/mongodb-core/lib/connection/pool.js:531:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
...
```

**Steps to reproduce the problem**

1. create database `strapi` in mongoDB with password: `test`, username: `user`
```
use strapi
db.createUser({ user: "user", pwd: "test", roles: [{ role: "dbOwner", db: "strapi" }] })
```

2. Setup Development Environment
```
$ git clone STRAPI_FORK
$ cd strapi && npm run setup
$ mkdir sandbox && cd sandbox
```
3. Create a new project `strapi new myDevelopmentProject --dev.` with options:
```
? Choose your main database: MongoDB (recommended)
? Database name: strapi
? Host: 127.0.0.1
? Port: 27017
? Username: user
? Password: test
? Authentication database: strapi
? Enable SSL connection: false
```

**What is the expected behavior?**

**Suggested solutions**

Thank you for help!

**Comment by derrickmehaffy** [comment]
@BroTrue the documentation is wrong, run `npm run setup` in your project root folder, not the /admin folder. See my pending PR: https://github.com/strapi/strapi/pull/1546

**Comment by soupette** [comment]
@BroTrue since you generated your project with the `--dev` flag your admin is a symlink with the monorepo which means that even if you rebuild the admin you'll need to create a new app in order to push it to production. What you can do however is run `npm run setup:build` at the root of the monorepo. This command will not only build the admin but also all the other plugin. Therefore the modifications you made will be effective in all your new generated apps.

Also, in this particular case the database connection bug will not occur since the command is run from the monorepo instead of your app.

**Comment by BroTrue** [comment]
@soupette Thanks for help, its working!
