### ISSUE TITLE
Enumeration by line

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1561]
**What is the expected behavior?**
I have two suggestion for Enumeration field type:

1. I think it's more better if Enumeration fields support multi value selection too.

2. In some RTL language like Arabic **comma** character code is different with English and It's a little hard to separate Enumeration values with comma (because we forced switch keyboard language to type comma and switch keyboard language again for type next value) I suggest to support **Enter** character as a separator too. It can be useful for someone like me and others still can use comma. :wink:

**Comment by mnlbox** [comment]
@lauriejim Now we can choose one value from Enumeration values. For example I have one Enumeration field called **expertise** and it's values are:
Programming,Designer,UI,UX,...
And I want select multi value for this field. I know that we can do this with relation but I want handle this by Enumeration because it's a static list.

**Comment by lauriejim** [comment]
To this case you will have to use relations. Enum type is not design for your use case.
https://stackoverflow.com/questions/38305154/why-enum-does-not-store-multiple-values-in-mysql

**Comment by derrickmehaffy** [comment]
(Side note @lauriejim Strapi doesn't use the enum type in MySQL, its just a string. I only know this because I specifically did that in the PR that added it :stuck_out_tongue: updating enum values in large databases can take forever and be very damaging to the database)

Realistically @lauriejim they could probably be stored as json and decoded, but that would require quite a bit of rework.

**Comment by derrickmehaffy** [comment]
That being said, this is one of those reasons why a `manyToOneWay` would be a nice add.

(Think oneway but you can select multiple from the source model)

**Comment by Aurelsicoko** [comment]
I found this issue very interesting! As @lauriejim suggested, you can create a new content type called "Expertise" and it will do the job. But, if you've only 4 expertises, I completely understand that you don't want to create a new content-type for a so little number of entries.

IMO, it makes sense to allow multiple values for Enumeration type (without any relation model in mind).

**Comment by derrickmehaffy** [comment]
@Aurelsicoko the question is how do you store the values :stuck_out_tongue:

**Comment by Aurelsicoko** [comment]
A simple JSON array? Of course, we should stringify it for SQL databases which don't support JSON format.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko That was my suggestion as well, but in this case we could also add that option to the `oneWay` relationship to allow selections of multiple oneWays (I'm thinking in terms of being able to update the data while in production without having to modify the model)

Since the purpose of enum and oneWay are very similar in uses cases :smile:

**Comment by derrickmehaffy** [comment]
@lauriejim We can probably close this in support of the two listed options:

Array Type: https://github.com/strapi/strapi/issues/784
&
Relational Array: https://github.com/strapi/strapi/issues/1748

**Comment by mnlbox** [comment]
guys any news about my second suggestion?
 
> In some RTL language like Arabic comma character code is different with English and It's a little hard to separate Enumeration values with comma (because we forced switch keyboard language to type comma and switch keyboard language again for type next value) I suggest to support Enter character as a separator too. It can be useful for someone like me and others still can use comma.

**Comment by Aurelsicoko** [comment]
@mnlbox I agree with this, we should support two separators: comma and new line.

**Comment by mnlbox** [comment]
@Aurelsicoko So we have it now in RoadMap? :thinking:

**Comment by Aurelsicoko** [comment]
@mnlbox Complicated... I'm trying to define the roadmap and identify which are the most important tasks to work on. Currently, we are restructuring our way of working because every one of us (in the core team) is working on too many tasks which means that we're not doing the job as it should be.

Personally, I'm not sharing enough information with you and the community about the next features, the roadmap, etc. For example, we have to update the plugin architecture first (front-end & back-end) to be able to add this kind of feature (enumeration or array fields) easily then.

For now, I would suggest to let the issue open to keep it in mind.

**Comment by mnlbox** [comment]
@Aurelsicoko as you said please keep this issue open to keep it in mind.

@lauriejim please re-open this until comma and new line support in enumeration.

**Comment by mnlbox** [comment]
Thanks @derrickmehaffy 
For example I want add my enumeration values like this:
![enumeration](https://user-images.githubusercontent.com/25859075/51300082-e6dcc280-1a3f-11e9-9555-925dffe8fe86.png)

For me separate by enter is more cleaner.

**Comment by soupette** [comment]
The content-type-builder is going to be updated because the code is way too complex, if @Aurelsicoko agrees with having both inline and separated value I will add it.

**Comment by Aurelsicoko** [comment]
@soupette As we discussed, we will only support one value per line. Also, we will remove the spaces before/after each value.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko is there already a PR for this? Might be best to hold off closing an issue until it's commited into the repo :stuck_out_tongue:

**Comment by Aurelsicoko** [comment]
Not yet but @soupette is working on the content type builder and we talked about this yesterday.

**Comment by lappalj4** [comment]
@soupette Any updates to this? Seems like it wasn't included in the beta release at least?

**Comment by soupette** [comment]
@lappalj4 it has been included! 


![Screenshot enum field](https://user-images.githubusercontent.com/13311463/59756415-f465d500-9289-11e9-82f1-dcf0b8b4dbef.png)
