### ISSUE TITLE
Search input extra scrollbar in Firefox

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1563]
**Informations**
- **Node.js version**: 9.0.0
- **npm version**: 5.1.1
- **Strapi version**: 3.0.0 alpha 12.7
- **Database**: MongoDB
- **Operating system**: Linux

**What is the current behavior?**
Search input not shown well in Firefox.

**Steps to reproduce the problem**
See this image:
![strapi_ui](https://user-images.githubusercontent.com/25859075/42616046-062cd3c2-85c2-11e8-960d-9bb16d00d106.png)

**What is the expected behavior?**
We don't need scrollbar.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @mnlbox , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

And it's an easy css to fix it.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by soupette** [comment]
I'm closing the issue since it has been fixed
