### ISSUE TITLE
strapi import violates up_users_role_links foreign key constraint 

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#15808]
### Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Strapi version: 4.6.1
- Database: PG 14
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Running `strapi export` does not include the `up.users` (by design?), but it does include the roles and permissions:

```sh
│ -- plugin::users-permissions.permission     │    35 │ (     6.4 KB) │
├─────────────────────────────────────────────┼───────┼───────────────┤
│ -- plugin::users-permissions.role           │     2 │ (     466 B ) │
```

This leads to problems when trying to insert the links between the user and roles as the foreign key cannot be satisfied because the user is not inserted. I expect similar behavior with a custom collection that has a required relation with a up user.

Complete error:

```sh
Starting import...
[2023-02-14 07:33:36.616] error: [ERROR] insert into "up_users_role_links" ("role_id", "user_id", "user_order") values ($1, $2, $3) - insert or update on table "up_users_role_links" violates foreign key constraint "up_users_role_links_fk"
Import process failed.
```

### Steps to reproduce the behavior

1. Export `yarn run strapi export --file strapi-export [--only config,content] --key testing`
2. Import `yarn run strapi import --file strapi-export.tar.gz.enc [--only config,content] --key testing`

### Expected behavior

Succesful import of data.

### Possible solutions

(a) Do not import `plugin::users-permissions.role` because it's not possible to satisfy the FK constraint 
(b) Add `up.users` to the `--only`/`--except` flags and also export the user data.

The latter is very useful in CI because I can 'pre-define' user accounts for my tests that get imported before they run.

**Comment by sjoukedv** [comment]
I can also provide the export file.

**Comment by marcoautiero** [comment]
@sjoukedv are you sure you have users in your database? On 4.7.0 everything is working fine

**Comment by marcoautiero** [comment]
Same on 4.6.1, it's working properly, users are correctly exported.

**Comment by sjoukedv** [comment]
I do see entries for now `-- plugin::users-permissions.user`. Don't know what has changed. I am on `4.6.1` at the time of writing.

**Comment by icanhazpython** [comment]
On 4.14.2, I'm seeing a very similar issue which causes my imports to fail during the "link" portion.

Here's the error when using pgsql:
```
error: [ERROR] insert into "public"."up_permissions_role_links" ("permission_id", "permission_order", "role_id") values ($1, $2, $3) - insert or update on table "up_permissions_role_links" violates foreign key constraint "up_permissions_role_links_fk"
```

Here's the error when using MySQL with innodb: 
```
error: [ERROR] insert into `up_permissions_role_links` (`permission_id`, `permission_order`, `role_id`) values (2, 1, 1) - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`strapi`.`up_permissions_role_links`, CONSTRAINT `up_permissions_role_links_fk` FOREIGN KEY (`permission_id`) REFERENCES `up_permissions` (`id`) ON DELETE CASCADE)
```

And MySQL with ARIA storage engine just for fun:
```
error: [ERROR] insert into `up_permissions_role_links` (`permission_id`, `permission_order`, `role_id`) values (2, 1, 1) - ER_DUP_ENTRY: Duplicate entry '2-1' for key 'up_permissions_role_links_unique'
```

I've attempted this on a fresh database and existing database. I have things setup with docker for a repeatable build process. It seems that the error occurs at some point during populating my database via the strapi GUI. I thought that this was due to a "messed up" database from possibly previous buggy versions of the import/export functionality, or from a sqlite to MySQL migration I did before strapi even had import/export/transfer functionality. So I went through on a completely fresh install and spent an hour or so MANUALLY copying and pasting things into the new instance so I could start completely fresh. I tested export/import a few times during the course of this tedious exercise, and things were working until I got to a certain point. I don't know exactly what that point is, as I was not thorough enough with testing after every change. I can say that the issue did not immediately present itself so I can see why it may be difficult for some to reproduce. 

I was able to fix it by patching https://github.com/strapi/strapi/blob/6a2c807a11cff743ff38c7f2388a8d1b876f8ee5/packages/core/data-transfer/src/commands/data-transfer.ts#L119 like so:
```
const DEFAULT_IGNORED_CONTENT_TYPES = [
  'admin::permission',
  'admin::user',
  'admin::role',
  'admin::api-token',
  'admin::api-token-permission',
  'admin::transfer-token',
  'admin::transfer-token-permission',
  'admin::audit-log',
+'plugin::users-permissions.permission',
+'plugin::users-permissions.role',
];
```

Whether this is a good idea or not, I'm not sure.
