### ISSUE TITLE
strapi -v or any strapi not working! but it was working!!

### ISSUE THREAD

**Issue by Ahmedsaber9** [strapi/strapi#1591]
**Informations**
- **Node.js version**:
v10.6.0
- **npm version**:
6.2.0
- **Strapi version**:
Last via : npm install strapi@alpha -g
- **Database**:
MongoDB
- **Operating system**:
Ubuntu 18.04

**What is the current behavior?**
1- I install and run 
`strapi new my-project`
All OK :) 
2- I made some new elements etc and all is perfect 
3- I go to make my API via 
`strapi generate:api saber`
4- I got 
`strapi: command not found`

**Steps to reproduce the problem**
1-reinstall nodejs and npm
2- i try with strapi -v with no luck 
3- i can't make a new project now because 
`strapi: command not found``strapi: command not found`
4- i made the right permissions with npm in home dir and ./profile and npm path.
* I don't won't to restart my laptop. my work will be gone!

**What is the expected behavior?**
`strapi: command got working`

Thanks.

![screenshot_20180718_071346](https://user-images.githubusercontent.com/23035531/42861291-afbfe536-8a5a-11e8-9b27-a09806b83d59.png)
![screenshot_20180718_071418](https://user-images.githubusercontent.com/23035531/42861292-aff622fe-8a5a-11e8-9c66-2ed539b743ff.png)
![screenshot_20180718_071523](https://user-images.githubusercontent.com/23035531/42861293-b01c7cce-8a5a-11e8-9f89-9171810f09de.png)
![screenshot_20180718_072301](https://user-images.githubusercontent.com/23035531/42861492-7b703dc0-8a5b-11e8-9d46-a884cafa5629.png)

**Comment by Ahmedsaber9** [comment]
I Should Run 
`source ~/.profile `
In every new terminal to get it work.
i hope this will help someone else 
also don't miss 
https://docs.npmjs.com/getting-started/fixing-npm-permissions
Thanks.

**Comment by maturano** [comment]
Personal recomendation: use `nvm` or similar: https://github.com/creationix/nvm

**Comment by zcqno1** [comment]
I met `strapi: command not found` too.

First I installed strapi in node v8+, `strapi start` falied. OK, that's because node v10+ is required.
Then I installed node v10+, and used it. 
`strapi start` agian => `strapi: command not found`
The reason is that strapi was installed in node v8+, while migrating to node v10+ there's no strapi installed globally.
Just re-install strapi in node v10+, strapi command comes back.

BTW,
before re-install strapi after using node v10+, the project could be run by `npm start`.
However, new created content type shown on the left menu was empty with no field, just like issue #2213 mentioned.
Finally, use `strapi start` solve this. Because adding new content type requires restart the project that's done by `strapi start`.
