### ISSUE TITLE
Use koa-morgan as default logger

### ISSUE THREAD

**Issue by pierreburgy** [strapi/strapi#160]
**Strapi version**:
v3

What do you think about using koa-morgan as default logger for Strapi v3?

**Comment by fishmacs** [comment]
I think koa-morgan is great, with it we have more options, just a little like customization of Apache log.

**Comment by Aurelsicoko** [comment]
Currently, Strapi is using his own middleware based on top of Winston (https://github.com/strapi/strapi/blob/master/packages/strapi/lib/configuration/hooks/core/logger/index.js).

`koa-morgan` looks great, I really like the predefined format and the fact that we can write logs to a file. Then, it allows using a custom token format which is a great news. I don't think we can keep available all these configurations with JSON configuration files, though.

**Comment by pkoretic** [comment]
winston is really slow, I have some simple benchmarks here https://github.com/pkoretic/polog/tree/master/benchmarks
And we did cpu profiling on our production app that had much lower throughput than expected and it showed winston is the culprit and there was barely any logging being done

this is the difference when using simple console log and winston
![winston is slow](https://cloud.githubusercontent.com/assets/12746445/23083457/0623e7b2-f55e-11e6-8673-d626d6380a11.png)

I can see that you also use it as an access logger that writes a log line twice for each request and using winston most of the time takes more to log that request than to actually process it

I made a logging library just because of that reason ([polog](https://github.com/pkoretic/polog)) and I can only recommend you move away from winston as there is just too much processing for each message being done. I would be happy to help if that would be wanted.

**Comment by Aurelsicoko** [comment]
Thanks, @pkoretic. I will take a look at your library. Are we able to write the logs into a log file?

**Comment by pkoretic** [comment]
@Aurelsicoko No. The fastest way is to write it to the stdout and pipe that into file. IMHO the rest of the stack should handle logs from node apps (docker, supervisor, syslog etc). I understand that might not be wanted so as long as winston is not used you are good to go :) 
We first replaced winston with log4js so this is what I would recommend if more features are needed

**Comment by Aurelsicoko** [comment]
We are using Pino which is one of the fastest logger available on the market. I'm closing the issue because it's not relevant anymore. Thanks again for this discussion, it was very interesting.
