### ISSUE TITLE
Duplicate entry with relational field does not get duplicated to the new entry 

### ISSUE THREAD

**Issue by jastrand** [strapi/strapi#16110]
### Required System information

- Node.js version: 16.13.2
- Strapi version: 4.8.1
- Database: postgres
- Operating system: macOS
- Is your project Javascript or Typescript: javascript

### Describe the bug

Duplicate an collection type entry with dynamic zone. If the component in the dynamic zone holds a one to many relational field the relations will not follow to the new duplicated entry. 

### Steps to reproduce the behavior

1. Create a component with a one to many relation
2. Use that component in dynamic zone for collection type
3. Select a relational field 
4. Duplicate the entry 

### Expected behavior

Expected behavior is that the selected relations should follow to the new entry after duplicating. 

### Screenshots

Entry to duplicate looks like this with a selected relation: 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/57670121/225648409-7364e245-8789-4272-a00a-f4c81729daf4.png">

After duplicating, it is empty:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/57670121/225648750-967df5c6-3593-4dc3-bba7-c2bd2fff02bf.png">

**Comment by Boegie19** [comment]
@jastrand the duplicate steals the relationship of the object you cloned if the clone is on the many side of many to 1 this is done since if it did not do that it would break the relationdship and would be a many to many relationship not many to 1

**Comment by Marc-Roig** [comment]
@Boegie19 I think she/he is referring to the duplication of an entity step, that does not populate the relations in the Admin.

Since 4.6.0 We did a refactor on how we load relations in the Admin, and what you are reporting is a bug we are currently working on :) 

In the effort of centralising the discussion in a single place I will close this issue in favor of https://github.com/strapi/strapi/issues/15093 . We are on the process of providing a solution, any progress we make we will communicate via that github issue.
