### ISSUE TITLE
Unable to get response from google cloud translation

### ISSUE THREAD

**Issue by Ankita1012** [strapi/strapi#16237]
### Required System information

- Node.js version: v16.17.0
- NPM version: 8.15.0
- Strapi version: 4.8.2
- Operating system:  Windows 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have set the translator plugin in the plugins sections of the Strapi. However when I tried to translate the content I'm unable to get response from google cloud translation: unexpected end of JSON input .

![Screenshot (21)](https://user-images.githubusercontent.com/52158098/228443451-d02359a5-3104-45d2-8d10-401e3d2e68ed.png)

### Steps to reproduce the behavior

1. Install Strapi
2. add environment variables in .env file
3. Copy API token in .env file 
4. Go to Config> plugins.js add code snippet 
5. ![Screenshot (23)](https://user-images.githubusercontent.com/52158098/228444721-53e92425-d41c-40c6-aa49-dbfca3f6fdfe.png)
6.  npm run build
7. npm run develop
8. setting -> Translator -> Configuration.
9. save the Translator confiiguration.
10.  on translation error occured .

### Expected behavior

Translator plugin should enables us to translate  Strapi content into any other  languages.

**Comment by Eventyret** [comment]
Thank you for submitting this issue @Ankita1012 🙌
This issue seems to be more about the plugin itself and not Strapi 🚀
So I will close this off, and I do suggest you create a new issue on the author Github Repo for the plugin itself.
Please find their 📚 [Github Repo](https://github.com/manishkatyan/strapi-google-translator)
