### ISSUE TITLE
error with integration i18n plugin with default locale

### ISSUE THREAD

**Issue by rodionks** [strapi/strapi#16301]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 
- Database: mysql8
- Operating system: macos
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Errors at attampts to editing data in Strapi admin interface, when setting plugin_i18n_default_locale not present in database.

### Steps to reproduce the behavior

1. You have well-runed satrapi application, using i18n plugin and using locale not equals to "en".
2. Delete row with key "plugin_i18n_default_locale" from strapi_core_store_settings table in database.
3. Lunch your strapi appication
4. Go to admin interface, content manager. Try to open for edit (or add) row in some entity.
5. See error in admin interface: "Woops! Something went wrong. Please, try again."  If dive deeper you can see in browser console  that error rised on line   "const currentLocale = get_default()(query, "plugins.i18n.locale", defaultLocale.code);" with message TypeError: Cannot read properties of undefined (reading 'code')
    at LocaleListCell (main.92afc095.js:51345:69)
    at Ch (main.92afc095.js:95288:137)
    at ck (main.92afc095.js:95398:460)
    at bk (main.92afc095.js:95381:347)
    at ak (main.92afc095.js:95381:278)
    at Tj (main.92afc095.js:95381:138)
    at Lj (main.92afc095.js:95374:163)
    at main.92afc095.js:95254:115
    at exports.unstable_runWithPriority (main.92afc095.js:108652:343)
    at gg (main.92afc095.js:95253:325)

### Expected behavior

No Errors on editing and adding rows. Strapi should use some default value of locale even it doesn't present in database store. 

### Additional context

The way to reproduce bug looks quite artifitial, but it's really vital when you are recreate database tables and recreate data e. g. for testing purpose.

**Comment by Marc-Roig** [comment]
hello :) 
I understand the use case of this is to test your strapi application. Nevertheless I think it should be expected that strapi requires a minimum database state to be initialised.

The default locale is one of the required elements in DB and deleting can cause unexpected problems like this one, the strapi application always make sure the value is set in the db, and strapi app expects it to be there. 

If there are more  use cases that can impact more people we can reopen this for a debate and see if we can set a "default" value in DB, for now I would say this should be the expected behaviour.
