### ISSUE TITLE
Can't transfer uploads to a k8s instance because of mounted PV

### ISSUE THREAD

**Issue by nagman** [strapi/strapi#16340]
### Required System information

- Node.js version: 18.15.0
- NPM version: 7.20.0
- Strapi version: 4.9.0
- Database: sqlite
- Operating system: MacOS Ventura 13.2.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have a Strapi on k8s with a Persistent Volume on the `uploads` directory in order for its file to be preserved between deployments.

Yet the `strapi transfer --to` command moves the `uploads` folder to `uploads__[timecode]`, so the scripts fails at this point as we cannot move a mounted directory.

### Steps to reproduce the behavior

1. Deploy a Pod with Strapi on it and a PV mounted on `uploads`
2. Run `strapi transfer --to` and point to this deployment
3. Watch it fail

### Expected behavior

Instead of moving the existing `uploads` directory to a backup folder on the destination, it should copy it, remove every file in it, copy the source files into the destination folder, then delete the backup folder.

In brief, this is just a matter of not dealing with the directory but with its content.

For now, I have to mount the PV on the parent directory (`public`) and manually create in it the `robots.txt` file and `uploads` directory on creation (else the strapi instance fails).

I would be pleased to create a PR with those changes in the core transfer script, but I can't find where are the files?

**Comment by christiancp100** [comment]
> Any news? Can I at least know where are the files responsible for transfer, so I can propose a PR?

Hi @nagman, sorry for the delay on the response. We've been handling some issues that didn't have a workaround during these past weeks and couldn't prioritize yours 😢. The backup folder is being created here: https://github.com/strapi/strapi/blob/44411472207a771374de9eae5d06a429bc6d91fe/packages/core/data-transfer/src/strapi/providers/local-destination/index.ts#L181 when the assets provider in the destination is local. However, if you could share your kubernetes configuration and more details about your project setup so that we can replicate it on our side we can prioritize it and fix it on our side.

**Comment by christiancp100** [comment]
Hi there! To bypass the permissions issues that are individual to each project's configuration, we've added a confirmation layer to avoid having an error when the assets backup folder cannot be created during the data transfer process. Now using the --force flag skips that error in case it happens (probably due to permission issues) or otherwise it will pop up a confirmation. I will close this issue but feel free to create a new one if you still have any problems. Thank you very much!

**Comment by SamDelamarter** [comment]
For those still struggling with strapi transfer (or import) on Kubernetes. This works for a brand new instance of strapi. If the instance you are transferring to has existing data, you would need to make some adjustments to preserve it.

1. Edit your deploy: Change the volumeMount from public/uploads/ to public/ and add a sleep command
2. Shell into the container, create public/uploads/ and run strapi transfer
3. Edit your deploy to remove the sleep command

The container will restart and all of your transferred data will be in the persistent volume!

[Example sleep command](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#run-a-command-in-a-shell):
```
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
```
