### ISSUE TITLE
Update sessions documentation - access auth user data

### ISSUE THREAD

**Issue by VictorKolb** [strapi/strapi#1639]
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.12.7
- **Database**: mongoDb
- **Operating system**: macOs

**What is the current behavior?**
If I try to update objects fields with relations many to many via API with:
`strapi.updateEntry("user", "5b5754fcc44d28b594f22f7e", {
      artist: ["5b547c25a6f5f07d30cccf66"],
    });`

I get response with User object, but field "artist" is empty array. 

**Steps to reproduce the problem**
Create content type with field with many-to-many relations and try 

**What is the expected behavior?**
Fields with relations "many-to-many" are updated as well as fields with another relations

**Suggested solutions**
I don't know :(

**Comment by VictorKolb** [comment]
Update:
If i reproduce it with another pair of objects, for example, Events and Artists, then fields updated correctly. From this comes the question: how can authenticated users update their fields?

**Comment by AustinBratcher** [comment]
I've run into a similar issue, but with the creation of a new entry that has a many-to-many relationship. I can create the new entry, but the relationship is not populated. I believe this might have been introduced with 3.0.0-alpha.12.2. In the wiki for the migration from 12.1 to 12.2, there are significant updates to both the add and edit services for api routes. Both utilize the updateRelations method (from the mongoose ORM I believe), which is where the problem comes from. 

I did manage to "patch" my issue with the add service by changing the id field to _id in the return statement: 
```
return Article.updateRelations({ id: entry.id, values: relations });

changed to 

return Article.updateRelations({ _id: entry.id, values: relations });
```

All of my api routes were created with alpha.12.1, however. The issue with the missing underscore (and thus unpopulated relations) might not come with newly generated routes, but I have not tested this yet.

**Comment by lauriejim** [comment]
@AustinBratcher About the issue you got with `_id`, it has been fixed in last version of Strapi.

@VictorKolb Actually this is not developed but you can create your own policies to handle this case. https://strapi.io/documentation/guides/policies.html

**Comment by VictorKolb** [comment]
@lauriejim thanks for your response!

I tried to create policies but I got empty `ctx.session`.

```
module.exports = async (ctx, next) => {
  if (ctx.session.user.role === 'administrator') { //→ ctx.session is empty object
    // Go to next policy or will reach the controller's action.
    return await next();
  }

  ctx.unauthorized(`You're not allowed to perform this action!`);
};
```

My app architecture very similar with https://blog.strapi.io/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-authentication-part-4-7/

**Comment by VictorKolb** [comment]
update: user object is available in `ctx.state.user`. Maybe it may be worth updating the documentation?

**Comment by lauriejim** [comment]
Ho yes you are right !

We did the update in this section of the doc [Authentication](https://strapi.io/documentation/guides/authentication.html#user-object-in-strapi-context) but not in sessions part.

Can you open a pull request with `ctx.state.user` update in session part please.
There is a link for that on top of the page you want update.

**Comment by VictorKolb** [comment]
@lauriejim https://github.com/strapi/strapi/pull/1686 I opened pull request. Please, check whether everything is correct?
