### ISSUE TITLE
Only cookie sessions supported

### ISSUE THREAD

**Issue by musicformellons** [strapi/strapi#164]
In docs I find: "Strapi only supports cookie sessions, for now." My questions:
1) any plans to also provide token based sessions?
2) I see jwt is included so this is jwt with cookies?

**Comment by Aurelsicoko** [comment]
I'm not sure to really understand... Maybe, are you confused between JWT authentication and session? When you are using JWT, you don't need a session store.

However, I worked this morning to change our session management system because it was limited. We switched to koa-generic-session to handle different session store such as Redis, Mongo, PostGreSQL, ... You can check out the commit [here](https://github.com/strapi/strapi/commit/213c82201c6a5a45d7fb1135b5148bfd7bf07e07).

**Comment by Aurelsicoko** [comment]
#176
