### ISSUE TITLE
i18n error with updating strapi version to 4.5.1

### ISSUE THREAD

**Issue by SP12893678** [strapi/strapi#16408]
### Required System information

- Node.js version:14.19.0
- NPM version:6.14.16
- Strapi version:4.5.1
- Database:better-sqlite3
- Operating system:ubuntu 18.04
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After updating the Strapi version from 4.1.0 to 4.5.1, an error occurred when switching language in the editing area. The error message is shown in the following image.

Error Page: http://my-domain/.../create?plugins[i18n][locale]=en&plugins[i18n][relatedEntityId]=1

P.S. The migration instructions provided by Strapi have been followed.

### Expected behavior

can switch to the page in the desired language for editing.

### Screenshots
![image](https://user-images.githubusercontent.com/36910625/232201749-273f1298-2d0c-4a31-8871-954c7d30246a.png)

**Comment by Boegie19** [comment]
@SP12893678 This issue should be fixed in 4.6.0 see forum post 
https://forum.strapi.io/t/usefetchclient-is-not-a-function-axiosinstance-migration/25115

if this does not solve the issue please  try to update to the latest strapi version if that does not solve your issue please tell us in this issue and I will take an other look at it.
