### ISSUE TITLE
strapi transfer command returns unexpected server response: 200

### ISSUE THREAD

**Issue by MarDi66** [strapi/strapi#16425]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.7.1
- Database: postgre
- Operating system: macos
- Is your project Javascript or Typescript: JS

### Describe the bug
 
Running strapi transfer returns a `[FATAL] Unexpected server response: 200. Transfer process failed.`

### Steps to reproduce the behavior

I've created a new database for the same repository (one for production, the other for staging) and I try to transfer the DB content from staging to production by running the following command:
`strapi transfer --to https://my.staging.app/admin --to-token myStagingTransferToken`

### Expected behavior

To have the command working, and staging DB to be transferred/copied to staging DB.

### Screenshots

<img width="525" alt="Screenshot 2023-04-18 at 10 15 53" src="https://user-images.githubusercontent.com/50139430/232715465-d31be6e5-87d7-4386-8185-7cad947e1bb9.png">

**Comment by Convly** [comment]
Hello there, thanks for opening this issue!

In order to troubleshoot your issue, could you answer those questions please:
- Is the data-transfer feature enabled on your remote?
- If you're not sure, could you check the logs when you start the server on your remote? Do you see any warning or error related to data transfer?
- Are your request going through a proxy?
- If they are, do you allow ws upgrade from an http server in your proxy config?

**Comment by MarDi66** [comment]
Hello @Convly !
I've managed to make the transfer "works" by changing my command from `to` to `'from`:
`strapi transfer --from https://my.prod.app.com/admin --from-token myProdTransferToken`

After a certain time, I got this error:
`error: [FATAL] WebSocket is not open: readyState 3 (CLOSED)`

Any idea what's going on? 

<img width="527" alt="Screenshot 2023-04-18 at 11 21 19" src="https://user-images.githubusercontent.com/50139430/232733555-524aa331-7727-48d0-8d46-3e90eb9776db.png">

**Comment by Convly** [comment]
Damn, I went too quickly over your example :man_facepalming: 

Indeed, you should be using --from and --from-token to reference params linked to your data source and --to and --to-token for destination-related params.

Regarding the error you got, it might be something that has been fixed in 4.8.X or 4.9.X. Would it be possible for you to test on those versions? Or are the versions on your project locked to patches only?

Another thing you could try is restart both servers to make sure they're not stuck in a wrong state due to invalid commands (although it shouldn't happen) :thinking: 

Don't hesitate to come back with more information/question in order to troubleshoot this issue and see if necessitates additional work on our end :slightly_smiling_face:

**Comment by Convly** [comment]
Just remembered but data pull from a remote source (--from / --from-token) is a feature introduced in 4.9.0. You might want to upgrade to this version in order to use it

https://github.com/strapi/strapi/releases/tag/v4.9.0

**Comment by MarDi66** [comment]
No problem! Feel free to close this one :)
