### ISSUE TITLE
Cannot edit or create data if there is a relation field in that collection type

### ISSUE THREAD

**Issue by LixinDeng** [strapi/strapi#16579]
### Required System information

- Node.js version: v18.15.0
- NPM version: 9.5.0
- Strapi version: 4.10.1
- Database: postgreQL
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug
In safari:
I cannot add content to my collection when it has a relation field. when I remove that field, I can add content to my collection. but, if I introduce the relation field back new entry cannot be made.

it shows "whoops, something went wrong" on the screen. and on browser console, it shows "TypeError: s.split(".").at is not a function. (In 's.split(".").at(-1)', 's.split(".").at' is undefined)".

It works fine in Chrome

### Steps to reproduce the behavior

1. Build a collection called author 2. Build a collection called articles
3. Make the relation "Author has many Articles"
4. Click on any data or click create new entry 
5. See error

### Expected behavior

Should add or edit data.

### Screenshots
<img width="946" alt="Screen Shot 2023-05-01 at 4 16 31 pm" src="https://user-images.githubusercontent.com/128338734/235418508-d2150dc6-ddbd-4a6a-9737-c019cc3e7bf7.png">

<img width="1424" alt="Screen Shot 2023-05-01 at 4 13 00 pm" src="https://user-images.githubusercontent.com/128338734/235418140-e3c7be5c-8ff8-4835-acc8-cb772950dc9c.png">

### Code snippets

N/A

### Additional context

N/A

**Comment by nevil2** [comment]
I have same issue.

With Safari, if one tries to edit or create a collection with a relation, one gets same error.  Three separate users have tested this.  It works with Chrome or Firefox OK for all users.
This is serious, since it destroys credibility if Safari users have to install alternative browser to use STRAPI.
It worked in the past, so was introduced in one of the more recent releases.  Upgraded to 4.10.5 this morning and problem remains.  (I had problem with sorting by relation in Content Manager with 4.10.4, but this has gone with 4.10.5).

I am running STRAPI in a docker container (node:16-alpine) on Digital Ocean App platform with Digital Ocean Managed Postgres service, and using the following plugins:
 - strapi-provider-upload-dos
 - strapi-plugin-populate-deep
 - @ckeditor/strapi-plugin-ckeditor

This is serious issue, since it destroys credibility if Safari users have to install alternative browser to use STRAPI admin.

**Comment by timmywil** [comment]
I get the same error, but in all browsers. I am also running in docker with postgres, but I'm not using any plugins. I get the error locally whenever I try to add a relation field.

**Comment by timmywil** [comment]
Hmm, nevermind. I kept trying browsers and it worked in Brave, but not Vivaldi? Super weird. I can't imagine what the difference could be.

**Comment by timmywil** [comment]
I updated Vivaldi and the error went away. My guess is the admin UI is using JS only available in the latest browsers.
