### ISSUE TITLE
Navigating Relationships in dynamic zones does not respect Localization context

### ISSUE THREAD

**Issue by shibacomputer** [strapi/strapi#16665]
### Required System information

- Node.js version: v16.20.0
- NPM version: v8.19.4
- Strapi version: v4.10.2
- Database: SQLite
- Operating system: Debian GNU/Linux 10 (buster)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

In fixing #15743, the PR introduces a new bug where clicking a relationship within a dynamic zone will not respect the current localization, and instead switch to the default localization. This means that, while the ID displayed in the CMS URL is in fact the correct one for the localized entry, the rest of the interface presents the default localized entry. So, for example, if you have a relationship to a Chinese entry with an ID of `2`, and the equivalent entry with the default Localization (English) is set to `1` clicking the relationship will take you to ID `2`, but populate the CMS interface with `1`.

The Localization dropdown will be set to the default localization. 

Switching Localization will present the user with a "create new entry" interface, as though the entry does not exist. To fix this, the user must: 
1. switch FROM the default localization TO the localization they were working in.
2. Ignoring the "create new entry" interface, switch BACK to the default localization
3. switch again to their desired localization.
After this, the entry will be populated with the correct data.

Alternatively, the user can refresh, but we have instead observed users either thinking their localized data is lost, or performing the above switching steps.

### Steps to reproduce the behavior

See this WebM screencap for a demonstration.

[Screencast from 2023-05-09 16-27-19.webm](https://github.com/strapi/strapi/assets/737950/79a9388d-7389-4c0c-bb7d-fab8e94b85e4)

1. Go to an item with relationships and localization
2. Switch from the default localization
3. Click the linked relationship label
4. See the wrong information
5. Confirm in the browser address bar that the entry has the ID that matches the desired localization

### Expected behavior

1. The right data to be displayed in the entry with the right localization
2. At a meta / UX level, Strapi's localization should never silently switch unless the user explicitly switches.

**Comment by Boegie19** [comment]
@shibacomputer 
i18n does not check if the relation you are adding is from the same locale.
Aka you can connect English content with Chinese.

The issue you are having is that keywords was created in the wrong locale.

With relations it uses the local you connected in the relation.
aka if I connect Chinese content to an English content type it will respect that and show the Chinese content in English since relations are not i18n aware

This can not be fixed until V5 since this would be a breaking change.

**Comment by rhinodontypicus** [comment]
@Boegie19 this issue happens when you connect same localizations to each other, not different ones.

For example:

We have Page with 2 localizations: EN (id: 1) and DE (id: 2).
Also we have Tag with 2 localizations: EN (id: 1) and DE (id: 2).

In interface we connect DE page (id: 2) to DE tag (id: 2) using the relation. If we try to click on tag relation we will be forwarded to page like: `/admin/content-manager/collectionType/api::tag.tag/2`, but it should be `/admin/content-manager/collectionType/api::tag.tag/2?plugins[i18n][locale]=de` instead. Otherwise interface is glitching and displaying content of the Tag in DE, but Language is set to EN (like on the video) in this issue.
