### ISSUE TITLE
Text Area (Long Text) Doesn't work

### ISSUE THREAD

**Issue by ahmadjoya** [strapi/strapi#16856]
### Required System information

- Node.js version: v18.15.0
- NPM version: 9.5.0
- Strapi version: 4.10.6
- Database: postgreSQL
- Operating system: Windows
- Is your project Javascript or Typescript: JavaScript

# Text Area (Long Text) Doesn't work
When I create a text field and set the long text (text area), I cannot enter text or description inside of that text area.

![image](https://github.com/strapi/strapi/assets/35627961/94972e7f-46fb-42d0-a578-0fa14c4b7353)

![image](https://github.com/strapi/strapi/assets/35627961/c47f8e00-e990-45b3-ae74-26213091c38c)

**Comment by robinsimonklein** [comment]
I am also experiencing this bug since I upgraded to v4.10.6 👀 
Textareas are no longer editable, in both development & production mode. 

Existing text or cursor en empty fields are displayed after an empty line :
![Capture d’écran 2023-05-29 à 19 31 54](https://github.com/strapi/strapi/assets/36634414/864f5a16-39f5-4240-a433-8ea4b4fb87c5)

**Comment by Gerry915** [comment]
[#16830](https://github.com/strapi/strapi/issues/16830) There are some temp solutions for the issue and they gonna release a fix in 4.10.7.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/16830
