### ISSUE TITLE
Question: What are the main pain points you have using Strapi? (Episode 5)

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#16873]
Four years ago the Strapi Chief Product Officer @Aurelsicoko asked the community what their [main pain points](https://github.com/strapi/strapi/issues/3415) were and how critical these issues were to the rest of the community.

Since then, every year ([2022](https://github.com/strapi/strapi/issues/13430), [2021](https://github.com/strapi/strapi/issues/10419), [2020](https://github.com/strapi/strapi/issues/6634), [2019](https://github.com/strapi/strapi/issues/3415)) for the month of June we have asked the same question.

This year is a special one given we have started working on Strapi v5. Once again the Strapi team wish to get the broad community feedback, so the question again this year is: **what are the main pain points you have using Strapi?**

Some Rules for this issue: 
- Please try to be short and to the point and describe your use-case and why you feel this is an important issue. 
- Only one pain point per comment (you can add as many comments as you want, but only one per comment please)
- Be sure to construct pain points respectfully and constructively, following our [Code of Conduct](https://forum.strapi.io/faq)

-----

### Instructions

- Please only post one pain point at a time.
- If your pain point has already been listed, make sure to **upvote it** instead of posting a similar message. A simple :+1:  will suffice.

### Template

- **Issue:** Please describe your issue.
- **Context:** Give more details about the use case.

Copy paste the following markdown template:
```markdown
### Pain point

**Issue:** 
Please describe your issue.

**Context:** 
Give more details about the use case.

**Which version are you on:**
v3 or v4
```

-----

We look forward to reading all your comments. All contributions are welcomed, don't be shy 🙈

**Comment by drizztdourden08** [comment]
Nested components is my main pain point personally. It is supported at the code level at least now, but becomes an issue to maintain for those less knowledgeable with strapi.

supporting real nested component at more than just 2 level would be a major thing as it permit the data to be way more self container and reusable.

**Comment by drizztdourden08** [comment]
Dynamic zone in compponents

**Comment by raykeating** [comment]
A big pain point when building CRUD apps is implementing security policies.  Almost every "create", "delete", or "update" route needs an is-owner policy added to make sure the public endpoint isn't being used to delete entries created by other users.  The middleware is fairly simple, but is tedious to implement for every route, and certainly seems like a security concern to me.  

It would be great if in v5 we had a system that made implementing this additional security layer possible from the admin panel.

**Comment by GLorenz90** [comment]
### Collapsible Menus

**Issue:** 
The admin's left nav is only currently usable on desktop, despite the information side being responsive. This is because the left nav cannot be collapsed to a hamburger button or something similar. If each of the 2 layers could be closed and opened independently it would be much more usable on mobile platforms for quick changes.

**Context:** 
If you have simple data with basic relations, and need to make an adjustment on the road, it is a nightmare to use the admin on a phone currently.

**Which version are you on:**
v4

**Comment by GLorenz90** [comment]
### Content Type Grouping in menu

**Issue:** 
There's no current built in way to group content types to make them collapsable.

**Context:** 
Let's say you have a directory listing, directory contact, a directory category, and directory subcategory type. If you aren't working on the directory, that is 4 items that would be nice to collapse down into a "directory" group or tab of any kind. Let's say you have 5 other sets of items structured similarly, that's more than half of the type options that are just noise.

**Which version are you on:**
v4

**Comment by TRiBotWillB** [comment]
Nested components / dynamic zones in components!

**Comment by GregorSondermeier** [comment]
Issue:
Too many breaking changes between minor and even patch updates and not sticking to semantic versioning.

Context:
It's very tough to upgrade Strapi dependencies and almost impossible to feel confident that stuff continues to work after having upgraded. That's the case even within v4.

v4.5 aimed to prepare the database for the relation sorting, v4.6 brought the relation sorting but it didn't fully work until v4.6.x and even broke some Strapi instances.

Some design system components were refactored from JS to TS, the refactoring was released with v4.10.6, it contained bugs and boom, stuff didn't work anymore after upgrading from v4.10.5 to v4.10.6.

The list could go on but you get the point.

**Comment by icheered** [comment]
**Issue:** 
There is no easy/direct way to have an enumerable field. (It is possible using components and relations but it feels clunky and can't easily be made a 'required' field)

**Context:** 
Multiple times I have had the need for an enumerable field because a text field gives the client too much freedom and is difficult to handle in code.

Examples I have encountered:
- subscriptionState (active, cancelled, inactive)
- menuItemType (hot drink, cold drink, lunch, dinner)
- highlightColor (red, green, blue)

**Which version are you on:**
v4

**Comment by eruiz-impact** [comment]
Issue: 
Not being able to have conditional logic for fields. 

Context:
Being able to display a set of fields if a certain value is selected from a checkbox or a dropdown

**Comment by iquirino** [comment]
Should have Plugins to connect with remote datasources, like postgresql, mongo, dynamodb or even an Api without having to sync it with the Strapi database.
We could create models for remorlte resources and use Strapi as a central Api gateway

**Comment by iquirino** [comment]
Should be able to use services as a datasource, let's say, you implemented a service and then use it as a collection.
Example: A country list from a vendor Api to be used for a select field.

**Comment by GregorSondermeier** [comment]
Issue:
Because a file exists at a certain place and has a certain name, it will be automatically read by Strapi and has a certain meaning.

Context:
Say there is a file `/src/api/restaurant/services/restaurant.js`.
It will be read by Strapi upon startup.
You can call `strapi.service('api::restaurant.restaurant')` because you as a developer know that the function exported by the file has been read by Strapi and is available under that accessor.

But before runtime, nobody (no IDE, no intellisense) can tell you that that service exists, let alone which functions it contains. This is leads to errors and bugs which will only be detected at runtime.

Registering everything in that big `strapi` object and accessing it from there feels obfuscating and patronising. A set of setup functions and more extensive usage of import/export would greatly improve dev experience.

**Comment by icheered** [comment]
Working with multiple people on a single strapi project will result in very inconsistent database behaviour.

When I'm on a separate branch and add a new single/collection type and add some test data, and someone else on another branch without these changes starts Strapi it will wipe all the test data.

I'm not sure if this is even possible to fix but it caused a lot of headaches to figure out why the data sometimes disappeared..

**Comment by drizztdourden08** [comment]
Built in option to modify the API output without doing it through code. Especially the “data” and “attributes” sub fields. 

There are 3 plugins to handle those alone. We didn’t install any because support for plugin is sometimes a gamble and frontend relying on those could be an issue.

so we had to develop the front end with this in mind. While it does work, it is quite a bit of steps more to handles them.

we transform the data and have to account for that absolutely everywhere. It is ugly and could be simplified without that.

**Comment by raykeating** [comment]
I know we shouldn't have duplicates but the issue brought up by @icheered is huge

**Comment by nivla360** [comment]
Should have Apple sign in provider

**Comment by kpegelow** [comment]
### Pain point

**Issue:** 
Looking for passwordless solutions to make logging in easier for end users of my sites.

**Context:** 
I'd like to see more authentication capability than just passwords available out of the box/built-in for front-end authorization such as OTP or Magic Links.  Passwords are highly vulnerable.

**Which version are you on:**
v4

**Comment by everythinginjs** [comment]
- I believe nested sorting must be supported in the API.
- Bulk actions like publishing and drafting a bundle of records, 
- I have no idea about the possibility but I would like to share => multi columns in dynamic zones or a page builder like bakery in Wordpress.
- RTL support to strapi admin panel, right now we make it Arabic but it's left to right.

**Comment by Amaseal** [comment]
### i18n

**Issue:** 
Currently each langauge is stored as a seperate entries with seperete id, or other UID's.

**Context:** 
Having seperate UID for each language makes it hard to query what you want based on that UID. On FE Each time a user changes language and wants to fetch something based on a UID the app needs to use both, UID and language as params, and while the language is usualy available, you not always know all slugs for all localizations for a specific entry, so having the availability to fetch based on a static UID and only changing the language params would simplify my life.

Note that it is possible to create a field that is not localized, and fetch based on that, but then the user has to make sure that the field is unique since aplying unique constraint on a field forces you to localize it and the currently provided UID field by Strapi is always localized.

**Which version are you on:**
v4

**Comment by everythinginjs** [comment]
Pain point
Issue:
handle deep sorting in Strapi API queries.

Context:
sorting on nested and relations entities would be a must although currently it can be handled by Lodash methods but I believe for performance it is better to relay on db.

Which version are you on:
v4.4.3

**Comment by rubek-joshi** [comment]
### Pain point

**Issue:** 
No warning when deleting media that are in use or way of filtering unused media files.

**Context:** 
A portfolio website I help built had lots of images and videos. Client constantly uploaded and changed media for some of the required fields. To preserve space, I have to manually check which images/videos are no longed in use and delete them.

**Which version are you on:**
v4

**Comment by cpaczek** [comment]
Not gonna do a wall of text like I did last year but I think where Strapi could improve the most is the stability of features. I know there have been quite a few issues with DEITS for example. As Strapi grows there are going to be larger and larger projects where migrating is going to be a pita and having a super stable feature set would help with that. I think looking into the approach Rust takes where stable features are supported forever (but maybe not as extreme)

**Comment by JG-devo** [comment]
Multi-Tenancy would be lovely, as per the thread that has been running since 2018:

https://feedback.strapi.io/feature-requests/p/multi-tenancy
https://github.com/strapi/strapi/issues/1465

**Comment by Alexnortung** [comment]
### Pain point

**Issue:** 
Pnpm support

**Context:** 
In our team we use pnpm for a lot of projects, it is nice to use pnpm as it can save a lot of disk space if you have many projects installed and especially with strapi since the node_modules folder can often get very large.

**Which version are you on:**
v4

**Comment by heyjaypray** [comment]
> ### Pain point
> **Issue:** Ability to assign multiple roles to user. For example a user can be an event Manager and a Restaurant Manager. Or Authenticate and Restaurant Manager.
> 
> Was already raised on V5-disussion Discord channel and understood by the Team but raising here to
> 
> **Context:** An event app that has events and restaurants. The app has users, including event managers who can create and manage events, and restaurant managers who can manage their restaurants. You can even be a user, an event manager, and a restaurant manager if you organise events.
> 
> However, this creates a challenge in terms of permissions and roles. You cannot be both an event manager and a restaurant manager at the same time, so I would need to create a new role called "eventAndRestaurantManager." This would introduce more complexity and increase the chances of human error in the permissions system. To provide an example, in platforms like Liferay and Wordpress, it was possible to perform such actions.
> 
> **Which version are you on:** v4

I'm currently dealing with this as well - except my app is a SaaS that needs roles for Companies that sign up, and their Customers.  One way I'm considering dealing with it is to check the relationship through the front ends slug - it checks whether the user is related to the company field or customer field, and then runs through a custom api route to change the role.

The reason for this is that in my app - a user can be both a part of a company account, where they can add and sell products, and also be a customer of another company.  I'm building a pipeline ecosystem so multiple roles are necessary.

**Comment by scco** [comment]
### Pain point

**Issue:** 
Deployment & Setup on a regular Ubuntu 20 VPS with Apache / Ngix

**Context:** 
It was very hard for me to overcome the https proxy thing. When i finaly got it to run with a https modrewrite with help of chatgpt and endless research - accessing the media library chrashed my apache ... it took like 3 nights to find out how to setup all the things like strapi itself + https proxy + pm2 always on thingy .  I was missing a tutorial to do on a virtual server what is NO service what supports strapi with some clicks that explains the https proxy way better and give more examples how to do with apache or ngix the propper way - what was this for me : 

location / {
    proxy_pass http://<ip>:1337;
    proxy_set_header Host $host;
}

btw this was my server crashing mod rewrite when access media library. no idea why ... 

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{HTTP_HOST} ^strapi\.domain\.net$ [NC]
	RewriteRule ^(.*)$ http://11.111.11.11:1337$1 [P]
</IfModule>

**Which version are you on:**
v4

**Comment by saksham295** [comment]
### Strapi removing Mysql index on start up

**Issue:** 
Strapi doesn't provide the functionality to create custom indexes in schema.json and if we create through script it removes them

**Context:** 
This is my github issue - https://github.com/strapi/strapi/issues/16606
When i change something in database schema, strapi deletes the indexes, i have created a bootstrapped script which check and creates indexes if not exists. This seems to work fine.
But, with larger tables it creates problem. recreating index does all the drop and create index process which consumes lot of Compute resources, not to mention will introduce a huge lag in my slave database.

**Which version are you on:**
v4

**Comment by drizztdourden08** [comment]
> ### API Internationalization
> **Issue:** I've installed the i18n plugin, set the `STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE` env param to `fr-FR`, add the `FR` locale as default into the admin settings, but errors from API are still in English.
> 
> **Context:** My frontend is in French, I need error messages in French. In the future, I'll need multi languages, en, fr, de, it.
> 
> **Which version are you on:** v4
> 
> This is literally my second day on Strapi, I saw it could build API without effort. If I need to translate errors into the frontend, it's not really effortless.

I don’t think this belong here. This is not a throw it all buckets for issues. This is long term pain point by users who have intensely used strapi. This should be in another thread if you have an issue right now.

**Comment by JonathanBaudoin** [comment]
> > ### API Internationalization
> > **Issue:** I've installed the i18n plugin, set the `STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE` env param to `fr-FR`, add the `FR` locale as default into the admin settings, but errors from API are still in English.
> > **Context:** My frontend is in French, I need error messages in French. In the future, I'll need multi languages, en, fr, de, it.
> > **Which version are you on:** v4
> > This is literally my second day on Strapi, I saw it could build API without effort. If I need to translate errors into the frontend, it's not really effortless.
> 
> I don’t think this belong here. This is not a throw it all buckets for issues. This is long term pain point by users who have intensely used strapi. This should be in another thread if you have an issue right now.

Well, I found Github issues from 2018 and 2019 with the same problem, the response was: "translate into your frontend". And nothing into the doc about that.

I'm new on Strapi, but it seems I'm not the only one with this problem. So I can open a new thread but if the response was "no" in the past, the new response will probably be the same. For me, this is a pain point. ;)

**Comment by Louai99k** [comment]
### Pain point

**Issue:** 
Can't customize admin panel.

**Context:** 
**Strapi** was always the CMS I chose because of its high customizability but it lacks the ability to customize the admin view of the CMS itself. I know I can create plugins, injection zones and custom components but still there is a lot that Strapi misses that I can't customize. Not like the server side which I can literally edit anything inside it.

**Which version are you on:**
v4

**Comment by Louai99k** [comment]
> ### Pain point
> **Issue:** Deployment & Setup on a regular Ubuntu 20 VPS with Apache / Ngix
> 
> **Context:** It was very hard for me to overcome the https proxy thing. When i finaly got it to run with a https modrewrite with help of chatgpt and endless research - accessing the media library chrashed my apache ... it took like 3 nights to find out how to setup all the things like strapi itself + https proxy + pm2 always on thingy . I was missing a tutorial to do on a virtual server what is NO service what supports strapi with some clicks that explains the https proxy way better and give more examples how to do with apache or ngix the propper way - what was this for me :
> 
> //ngix `location / { proxy_pass http://92.205.25.20:1337; proxy_set_header Host $host; }`
> 
> btw this was my server crashing mod rewrite when access media library. no idea why ...
> 
> //apache `<IfModule mod_rewrite.c> RewriteEngine On RewriteCond %{HTTP_HOST} ^strapi\.nachschlag\.net$ [NC] RewriteRule ^(.*)$ http://92.205.25.20:1337$1 [P] </IfModule>`
> 
> **Which version are you on:** v4

I guess it's all related to the fact that their cloud exists, so they don't want to promote any other thing.

@scco

**Comment by derrickmehaffy** [comment]
Reminder, we love the discussion, but lets try to keep this issue just to the pain points. Our Product and Engineering teams will be going through this towards the end of june and cataloging the feedback and we want to make that process as easy as possible.

Few other reminders, please do look to see if your pain point already exists and vote instead of reposting, likewise, please do use the template as it will make processing the feedback easier for us. 

Thank you!

**Comment by aspheresedge** [comment]
Pain points from a contact: Admin dashboard bugs, adding line breaks to the editor, relations being saved twice and it takes a long time to add new languages if you have many modules/blocks.

**Comment by phmatray** [comment]
### Pain point

**Issue:** 
Compatibility with .NET tools

**Context:** 
StrawberryShake has a bug with parsing dynamic zones. When two different fragments on the same type are present in the query, StrawberryShake fails to parse the response correctly.

NSwag seems to consider that the open-api specs generated by Strapi are incorrect. Although there isn't a specific issue reported on GitHub or other forums, personal experience indicates a compatibility issue between the two.

These issues present significant obstacles in the workflow. As part of the Blazor community, which is a fast-growing framework with a rapidly expanding user base, Strapi's compatibility with .NET tools like StrawberryShake and NSwag is crucial. Resolving these issues would make Strapi more accessible and usable for the larger Blazor community. It is hoped that these compatibility issues can be addressed in the upcoming Strapi v5.

**Which version are you on:**
v4

**Comment by robertherber** [comment]
The GraphQL API:
- It's unnecessarily verbose. This is a major and real pain.
- Missing a typed response on `formats` on uploaded images.

Improve TypeScript support. I'd like to have "everything" TypeScript-supported - right now we're still very dependent on looking at examples and docs to do changes and extensions in the code.

**Comment by Antoine-lb** [comment]
### Memory Leak on Upload

Github issue: 
https://github.com/strapi/strapi/issues/14417
https://github.com/strapi/strapi/issues/6432
https://github.com/strapi/strapi/issues/14576

Forum: 
https://forum.strapi.io/t/upload-memory-leak-issue/20104

And many more issues and posts are around, I just stoped searching.

**Issue:** 
Resizing images has leaks, uploading just 5 images can crash a server on heroku.

**Context:** 
I think this is a bit outside of your control, is why no progress has been made from your side, but still, is a severe pain point to our Strapi experience.

Image resizing on upload is such a cool thing, and one of the reasons we picked Strapi.

The bug is so severe we disabled resizing and started doing it manually.

**Which version are you on:**
v4

**Comment by tilman** [comment]
Data merge capability for Strapi transfer:
Right now strapi transfer can only override the target database completly. It would be great if we can merge data or at least only push a certain collection type entry and not all entries from one collection type.

**Comment by tilman** [comment]
### Proper version pinning and peer dependencies in package.json + pnpm support

**Issue:** 
Lossly coupled dependencies.
No pnpm support.

**Context:** 
I expierenced it multiple times that a strapi installation was working on one dev machine but not the others. After hours of debugging it always has been strapi core or a offical strapi plugin with some loosly couple dependencies (like: `"some-package-a":"3.x" in package.json`) causing this issue. The working installation was usally an older installation which still had some package installed and the other was a fresher installation. Putting more effort into proper dependency management would be a huge quality improvement from my point of view.

**Which version are you on:**
v4

**Comment by tilman** [comment]
### No serverless deployment possible

**Issue:** 
It is not possible to deploy strapi serverless

**Context:** 
Especially for smaller clients wich change their content maybe 3-5 times a year it is a significant overhead to have a full server running with strapi the whole year 24/7. If Strapi would be serverless it could just spin up on usage and would become a better option also for smaller projects with tighter hosting budget.
Best Option for me would be if It would be possible to deploy strapi on vercel with ther serverless platform using there [build output api](https://vercel.com/docs/build-output-api/v3).

**Which version are you on:**
v4

**Comment by GregorSondermeier** [comment]
Issue:
"Closed" community

Context:
This might be strongly dependent on Strapi's business model. 

Strapi has the forum and the discord for community support (and more stuff for their own announcements).

The forum feels almost unmaintained, there are a lot of open questions and there or not a lot of motivation to help out users there.

The discord on the other hand seems to be way more active, but also has its drawbacks: You have to know it's there (so there is a slightly higher hurdle to join), you have to install the client, you cannot do a quick google search to troubleshoot your issues, it's a real pain to find stuff you have read or written in the past for reference.

If Strapi would encourage/embrace community support on established platforms like Stack Overflow instead of in their own little environments, IMO there would be some benefits: General awareness of Strapi would be raised, troubleshooting with a Google seach would lead to a higher chance to find someone else who has experienced a similar issue, and also I believe people would be motivated more to interact and join the discussions to raise their own visibility. For instance, if a potential employer would google my name and see my contributions, replys and solutions, that would also be good for me.

**Comment by antokhio** [comment]
Too long table names.

**Comment by frontBOI** [comment]
### Refresh token

**Issue:** 
Implementing refresh tokens with standard authentication is pretty straightforward (extending the core user-permissions plugin), but I would like to see this functionality implemented natively in Strapi.

**Context:** 
Every user authentication context I guess.

**Which version are you on:**
v4

**Comment by antokhio** [comment]
## Can't access relations in lifecycle

**Comment by frontBOI** [comment]
### JWT tokens in response body

**Issue:** 
For robust web security, a JWT is supposed to be delivered in a httpOnly cookie with CSRF protection. As of now, I managed to implement this by extending the user-permissions core plugin, but this is too much of pain for something that should be considered the standard for web security.

**Context:** 
When authenticating a user via standard method (login/pwd), I expect the JWT cookie to be secure and not easily frontend available.

**Which version are you on:**
v4

**Comment by frontBOI** [comment]
### Bootstrap user permissions

**Issue:** 
For a project, I had the need to boostrap some user permissions for multiple roles but could not achieve this easily, if not ever because of the inconsistent behaviour.

**Context:** 
When mounting the application, there should be a way to assign user permissions easily programatically so that it is coherent from an environment to another. When there is a lot of roles and custom objects, the assignment can be easily forgotten.

**Which version are you on:**
v4

**Comment by antokhio** [comment]
## No CLI or another way to properly reset strapi_core_store

The strapi_core_store table introduces a lot of issues, due to it's nature (json stored in database). Anything using should mandatory provide reset method (like reset view), or way to globally reset without dropping the database.

Other related thoughts is to introduce versioning for that table and apply correct based on version. 

#### This is prolly the most annoying one, due to no way to fix it properly.

**Comment by icheered** [comment]
### Referencing endpoints or files is weird

**Issue:** 
The names of endpoints and files are different from how you call them in the code. 


**Context:** 
*Registering API middleware*
I create the middleware at `api/products/middlewares/itemCounter`. I want to register it in `'config/middlewares.ts'`.
Expected name: `'api::products.itemCounter'`
Actual name: `'api::products.item-counter'`

*Updating item*
In the middleware when I want to update an item. 
Expected: `strapi.entityService.update('api::products'`
Actual: `strapi.entityService.update('api::products.products'`

**Which version are you on:**
v4

**Comment by Renkas** [comment]
It's impossible to populate dynamic zone media objects with deep hierarchies.

**Comment by Renkas** [comment]
PUBLIC_URL is compiled into the source.

This makes it impossible to generate Docker image and run it in different environments (staging, production). We currently need to build different images just for that one setting that should be an ENV variable.

**Comment by Coder-Sakshi** [comment]
When can we expect mongoDB connectivity in strapi v4?
MongoDb is a popular database and is widely used.

**Comment by zapplebee** [comment]
### Modification of the webpack config via plugin

**Issue:** 
Modifying the Webpack configuration from plugins is not a first-class feature.

**Context:** 
It is currently not possible to do easily.

Instead, we have to ask users to modify their `src/admin/webpack.config.js` file

```js
const pluginOverride = require('@our-corp-namespace/strapi-plugin/webpack');

module.exports = (config) => {
  return pluginOverride(config);
};
```

It is not ideal since we are already asking them to the `config/plugins.js` file and the `config/middlewares.js` file.

**Which version are you on:**
v4

**Comment by laurenskling** [comment]
### lifecycles `event` is too dynamic, I would prefer to just get the entr(y/ies) it hit. 

**Issue:** 
I like that fact that in v4, lifecycles were split in `beforeCreate` and `beforeCreateMany`. In v3 you'd get a single entry or an array in the same function, which was weird.
However, not we get the `event` in all the lifecycles. What is inside the event is completely dynamic. It depends on how it is called. Which means, I have no clue in my code how to handle the event. There could be so many things inside the event.
I would much prefer to simply get the data in the lifecycles. Especially in, for example, `afterDeleteMany` right now you only get a `where` in the event. Do I don't know which entries where deleted, only why. Most of my lifecycles are about cleaning up relation on delete event (via `strapi.db.lifecycles.subscribe`), or fetching some remote data on create or update. Right now, I always have to find the entry first (which is impossible in `after`), based on what is in the event. Hoping it is actually there, and the create isn't called a different way.

Another example: 
The UI creates relations by setting: `event.params.data.myRelationField.connect[].id`. But it is also to create a relation, from code or from the API, by using: `event.params.data.myRelationField = id`. So if I create a lifecycle, and i want to read this relation, there are 2 possibilities how it is set.

It would make developing so much easier if lifecycles would simply contain the data it has triggered on, not why it was triggered.

**Which version are you on:**
v4

**Comment by douwepausma** [comment]
**Issue:**
The API routes for collection types created by the Strapi generate command in plugins don't work.

**Context**
https://forum.strapi.io/t/core-api-routes-in-plugin/26396

**Which version are you on**
v4

**Comment by StructuralRealist** [comment]
### Pain point

**Issue:** 
Lack of content versioning.

**Context:** 
Authors make mistakes. They need to be able to revert.

**Which version are you on:**
v4

**Comment by StructuralRealist** [comment]
### Pain point

**Issue:** 
It doesn't seem possible to build Strapi without the admin. 

**Context:** 
This is an issue now that you need to build your project if you use Typescript. Running the build step increases CI times and Docker images because of the unused admin. I rather see the admin completely separated from the API (similar to Sanity Studio and Sanity API).

**Which version are you on:**
v4

**Comment by sanba-anass** [comment]
> ### No serverless deployment possible

what hosting provider do u use?

**Comment by hayedewit** [comment]
### Pain point

**Issue:** 
Content types in plugins cannot use the i18n plugin.

**Context:** 
https://github.com/strapi/strapi/issues/10120

**Which version are you on:**
v4

**Comment by Demacri** [comment]
> Nested components is my main pain point personally. It is supported at the code level at least now, but becomes an issue to maintain for those less knowledgeable with strapi.
> 
> supporting real nested component at more than just 2 level would be a major thing as it permit the data to be way more self container and reusable.

Quoting [drizztdourden08](https://github.com/drizztdourden08)
I'd like to add: improving the usability of components at code level. Like nowadays "updatedAt" and "createdAt" fields are not retrievable and you are not able to handle components fields in lifecycle hooks just like content-types or in the content-types in which they are embedded (if you add a beforeUpdate hook for a content type and try to edit event.params.data.component.fieldName it doesn't work).

**Comment by axelinternet** [comment]
### Pain point

**Issue:** 
GraphQL schema sets all properties as nullable even if they are required properties in Strapi. 
**Context:** 
This makes using typescript with Strapi a huge pain as the schema lies. This has been an issue since 2019 https://github.com/strapi/strapi/issues/4548. Trying to get proper types in your application requires beautiful workarounds such as this when doing a nested graphql query. Even simpler queries requires this nonnullable nestring or transformation of every response as the JsonAPI format adds all these nested levels of nullables.

```type MyType = NonNullable<
  NonNullable<
    NonNullable<
      NonNullable<
        NonNullable<
          NonNullable<
            NonNullable<
              NonNullable<
                NonNullable<
                  NonNullable<
                    NonNullable<
                      NonNullable<
                        NonNullable<Query["entityName"]>["data"]
                      >[0]
                    >["attributes"]
                  >["detail_plan"]
                >["data"]
              >["attributes"]
            >["entityName"]
          >["data"]
        >[0]
      >["attributes"]
    >["entityName2"]
  >["data"]
>[0];```

**Which version are you on:**
v4

**Comment by axelinternet** [comment]
### Pain point

**Issue:** 
Lack of typescript support for EntityService and QueryEngine

**Context:** 
Since v.4.3 Strapi is supposed to have typescript support that was supposed to allow us to "infer variables and return values types.". However the entityService, queryEngine etc doesn't have any typescript support so interacting with your strapi content in a type safe way. Sure it is nice that I can use typescript but the value of that strapi adds here is pretty low. I feel like I'm in a lot of cases is better of just not building within the confines of Strapis backend customization. The graphql API also has issues but at least everything isn't just typed as `any`

**Which version are you on:**
v4

**Comment by drizztdourden08** [comment]
Modifying any schema for data that is already existing doesn’t take the default value into account.

example:
Let say you have a simple component with a text field. You use that text field somewhere in strapi.

then you add a boolean field to that component and set its default to false. The data from earlier will show that new change but the default value will be null, which can break your front-end easily and make thing a lot harder to do changes. If you want to make thing logical and « right », in this example, you’ll have to go to each place qhere you use that component and set it manually. Why would a new change not set the default BY DEFAULT? That would be way easier for anyone using typescript where you want everything to be typesafe and meet the right schematic.

it can lead to taking shortcut way too easily just for a simple data issue.

**Comment by breaker-of-stone** [comment]
### Export + Import is unworkable for automated deployment.

**Issue:** 
Please explain in the Docs the logical model for data management, and good practice for deploying with data.
This material is assumed in almost every Guide and support post, but not apparently explained anywhere in a clear and simple manner.  For example:

- The data in a Strapi instance is inseparable from its schema, which is mainly stored in files and folder structures (src/api ??).  Both must be kept in sync when backing up / exporting and importing.  What is the definitive checklist?

- The Export / Import process does not always work.  Common reasons may include:
  - mismatch of schemas
  - mismatch of database architecture (e.g. sqlite vs MySQL, if not set up _precisely_ as per some invisible spec)

- Is there a 'first principles' process that can be implemented by local CI/CD tooling?  e.g. if we are restricted to a desired-state framework like Ansible, or have written our own in Python :{  Give us a rubric we can adapt and implement.

Happy to correspond for clarification.

**Context:** 
I have never been able to get it to work from a dev Mac to prod Droplet on DO.
When the documented procedures are followed and Import reports 'completed successfully', nothing has been transferred, and there are no logs or diagnostics that can be used for troubleshooting.

The process is too complex and the docs are patchy for this to begin with.

**Which version are you on:**
v4.10 at both ends

**Comment by Boegie19** [comment]
### Pain point

**Plugin development:** 

1.  Lots of stuff is undocumented
Examles:
- helper functions both in @strapi/helper-plugin and @strapi/utils
  - CheckPagePermissions
  - Error catching helpers (most plugins don't have that at all)
  -  fetchclient (we are now all supposed to be using this instead of axios and still no documentation)
  - useRBAC
- how you can support rbac in your plugins
- Not knowing what in utils and helper-plugin is stable to use and what could break 
- entity-service-decorators should be stable at this point atleast for v4 so why is it not documented
2. injection zones 
- we only have 2 documented injection zones in all of strapi. There should be at least 1 injection zone per page for strapi so I can inject stuff where ever I need
3. Have more Available actions for plugins to do strapi for there plugins adds stuff directly into core to make them work examples would be inject stuff into the home page and disable stuff in it.
4  in the plugin space there is not really clear plugin development documentation there is some documentation for plugins devs but is is scattered everywhere. Because of this the quality of plugins is lower and development cost way more time. 

**Context:** 
We need to make strapi plugin development a way better experience if we want more and better plugins

**Which version are you on:**
v4

**Comment by KMcKraken** [comment]
This may be more of a personal preference, but I have never gotten along with the "clicking to edit media" in the media library thing. The way I see it, most of my interactions with items in the media library are going to be selecting, not editing. I think I'd prefer a "click anywhere on the item" to select, and have a small edit button, instead of a small select button and click anywhere to edit.

**Comment by ologbonowiwi** [comment]
**Issue:**
I had a huge pain trying to add raw queries on Strapi services lately.


**Context:**
I needed to query from a JSON, and since Strapi doesn't go well with JSON fields, I would need to inject my query on the Knex query builder (or use the Knex helpers to query the JSON). But here's the issue: if I go and use `strapi.db.entityManager.createQueryBuilder()` to run my query manually, I lose all the pagination/mapping/counting that Strapi does behind the scenes.

**Suggestion of fix:**
We could have a hook to access the Knex query builder and do whatever we want before executing the query on Strapi's internal service.

**Which version are you on:**
v4

**Comment by pablote** [comment]
**Issue:** 
Very slow startup time.

**Context:** 
This usually comes up in the context of being able to run in serverless environments, and the answer usually is that it won't/can't be done, too much of a refactor. It'd would be great if just the startup times could be reconsidered. This is not just a serverless thing, being able to adapt quickly to growing demand is key and a must for any cloud deployed system.

**Which version are you on:**
v4

**Comment by StructuralRealist** [comment]
### Pain point

**Issue:** 
UUID IDs instead of auto-increment integers.

**Context:** 
This might be a personal preference but auto-increment integers feels legacy. They are leaking information about your system (i.e. how many items there are in your db) and they don't match with the type of the URL in which they are often used (string vs. number). It would also be easier to make items have a consistent ID between environments and migrations. Currently, when you migrate your db all your IDs will be changed.

**Which version are you on:**
v4

**Comment by StructuralRealist** [comment]
### Pain point

**Issue:** 
Inconsistent responses.

**Context:** 
These are some of the responses I found, where `Entity` is some object:

`Entity`
`Entity[]`
`{data: Entity}`
`{data: Entity[]}`
`{results: Entity[]}`
`{plugins: Entity[]}`

Also, I've seen relation fields being returned as `{count: 1}` or `Entity` or `{id, name}` depending on the endpoint. 

Booleans are sometimes prefixed with `is` (isEnabled) but often not. Keys are camelCase but not always (apiID, provider_metadata). And there are spelling mistakes (preferedLanguage).

**Which version are you on:**
v4

**Comment by derrickmehaffy** [comment]
Thank you everyone for all of your comments, since June has ended I will go ahead and close and lock this issue and hand it off to our product team to review and take into account.

As a quick summary it appears that a lot of the feedback are already things we have in our minds to work on and several parts of the pain points are already things we are either actively working on or are in the process of writing RFCs for (looking at you typescript users :wink: )

Thanks again everyone!
