### ISSUE TITLE
Unique cannot be unset with Mongoose

### ISSUE THREAD

**Issue by jskorepa** [strapi/strapi#1692]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: mongodb
- **Operating system**: Linux

**What is the current behavior?**
When I create field with unique constraint and then uncheck this checkbox the constraint still exists in the database and therefore it is still effectively unique field.

**Steps to reproduce the problem**
- Check the unique checkbox
- Save
- Uncheck unique checkbox
- Save
- Try to create duplicate record

**What is the expected behavior?**
I should be able to create two entries with same value given that unique is unset

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @jskorepa , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
Likely due to Strapi not modifying the collection, will need to be fixed in the mongoose package.

**Comment by jangroeneveld** [comment]
As a workaround, you can navigate to the collection with the unwanted unique property, and under the indexes tab, you can drop the index in question.
When using the command line you can use `dropIndex`
