### ISSUE TITLE
"private": "true" a really small detail in package.json line #3

### ISSUE THREAD

**Issue by jeanlucaslima** [strapi/strapi#17051]
I know this has zero relevancy, it's just my inner perfectionist. 

The problem is that package.json on Strapi has a property private set to true. 

[The property private should be set to true to avoid accidental publication on npm](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#private). But [Strapi is a public package](https://www.npmjs.com/package/strapi), already published making this not only redundant, but possibly wrong. 

Solutions: 
* Remove line 3 from package.json 

PS: I know this is not important, sorry for wasting time on this issue. I did not send a PR because it is a minor detail.

**Comment by Marc-Roig** [comment]
hello! Thank you for pointing this out in an issue :) Even the little things help here.

Strapi is built as a monorepo, meaning each package of the monorepo is published separately. You can see some examples:
https://github.com/strapi/strapi/blob/main/packages/core/strapi/package.json (the main strapi npm package you mentioned)
https://github.com/strapi/strapi/blob/main/packages/core/database/package.json

Those are the ones we want to publish. The root level package.json is set to private because we don't publish the monorepo itself, but only the inner packages :) I hope this brings light to the question, and if you want to discuss more we can continue the conversation and reopen the ticket!
