### ISSUE TITLE
TypeORM plugin

### ISSUE THREAD

**Issue by brunofigalveskk** [strapi/strapi#1706]
You might consider developing a TypeORM plugin (https://github.com/typeorm/typeorm) or something similar within in Strapi. I really think that could help and it would be a great advantage.

**Comment by Aurelsicoko** [comment]
It seems more powerful than Bookshelf but it seems heavy... I can't really believe that it can really support a lot of SQL databases and also NoSQL databases like MongoDB. There are too many specific features available in MongoDB (and Mongoose the official ORM) to handle them perfectly with TypeORM.

Another ORM tried to do the same, it's called Waterline... It's slow, it doesn't scale very well and it has strange behaviours sometimes.

@brunofigalveskk What could be the advantages of using TypeORM instead of Bookshelf? (except it handles more SQL databases)

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I also find that hard to believe, there is also some pretty in depth features on standard SQL databases too that bookshelf doesn't handle well. But if it does work as expected some testing on it would be great!

**Comment by zengxinle** [comment]
Bookshelf  is out !  Support  Type ORM !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
