### ISSUE TITLE
MongoError: command find requires authentication

### ISSUE THREAD

**Issue by marianomoretti** [strapi/strapi#1707]
**Informations**
- **Node.js version**: 9.8.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: Mongo
- **Operating system**: Linux

**What is the current behavior?**
When I type `strapi start` the next error happens: 
```
error { MongoError: command find requires authentication
    at queryCallback (/cms/node_modules/mongodb-core/lib/cursor.js:247:25)
    at /cms/node_modules/mongodb-core/lib/connection/pool.js:531:18
    at process._tickCallback (internal/process/next_tick.js:112:11)
  name: 'MongoError',
  message: 'command find requires authentication',
  ok: 0,
  errmsg: 'command find requires authentication',
  code: 13,
  codeName: 'Unauthorized',
  [Symbol(mongoErrorContextSymbol)]: {} }
```
**Steps to reproduce the problem**
Create a project from scratch.
Use a dockerized mongo from docker hub.
Start strapi.

**What is the expected behavior?**
Strapi starts without errors.

**Suggested solutions**
It works if I use a native mongodb installed on computer. Also, I tried to make a clean connection using mongoose and it works. 
I just tested using [strapi-docker](https://github.com/strapi/strapi-docker) and it works. For some reason, if I try to run strapi in my computer connecting to a mongo in docker it returns the error. 

Let me know if I can provide any other information to help with this.

**Comment by rickerd** [comment]
Have you checked the public role in strapi and giving it permissions for the specific models

**Comment by marianomoretti** [comment]
Hey @rickerd. Sorry, I'm new on Strapi. Where I can find that or read about that? Thanks!

**Comment by rickerd** [comment]
Login to the admin.
"Roles & Permissions" -> "Public" -> "Permissions" and here you'll see the types you've created.

**Comment by marianomoretti** [comment]
Oh, maybe I wasn't clear, but the app doesn't start. I have that error when I run `strapi start`

**Comment by rickerd** [comment]
I think the auth to the MongoDB server isn't correct than.

**Comment by derrickmehaffy** [comment]
@marianomoretti can you provide more information on how this is setup.

- Are you using a local mongo DB (installed on the same machine as strapi)
- Are you using authentication with mongo
- What OS is strapi/mongo running on
- If you are using a remote mongo instance have you tested enabling SSL in the `database.json`

Just need some additional information as that error doesn't really provide enough to find the root cause.

**Comment by derrickmehaffy** [comment]
Scratch that just noticed you are using docker, are you able to connect to that mongoDB using another client like Studio3T?

**Comment by marianomoretti** [comment]
Strapi is running on my host, and mongo is running on a (docker container)[https://hub.docker.com/_/mongo/]. I could connect to the same mongo using a clean js file with mongoose. 
```var mongoose = require('mongoose');
mongoose.connect('mongodb://0.0.0.0:27017/test');

var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
  console.log('connected')
});
///console.log -> connected```
I pasted you this code just to let you know that I could connect to that mongo.

**Comment by derrickmehaffy** [comment]
@marianomoretti Based on that code you can connect fine but when strapi starts its running a `find` command on something (likely something from the core_store) which makes me think you have a problem with permissions on your mongo docker container.

Hence the reason I suggested using something like Studio3T or some other client to try and manually add data. My guess is, if you tried to manually find something stored in the DB (there isn't likely to be anything there because strapi probably can't write due to permissions) it would fail.

I am by no means good with mongo (mysql user myself) but I'd imagine the permissions are fairly close with regards to `read` and `write` access.

https://docs.mongodb.com/manual/tutorial/manage-users-and-roles/#modify-the-user-s-access

**Comment by marianomoretti** [comment]
Hi @rickerd and @derrickmehaffy .
Well, I was able to start strapi, and the problem wasn't on it. I was using a docker compose that enable auth in mongo passing two env vars. When mongo has enabled the auth, the error that I posted here happens. 
Thanks for your help! I will close this ticket. :)

**Comment by avallete** [comment]
I just ran into the same issue.

So, for future people who will have the same issue, here is the cause of the error, and how to fix it (without disabling the mongo auth):

## Error cause:
When running mongo with a docker image and providing `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` environment variables, it will make mongod running with the `--auth` option. See [mongo official documentation](https://docs.mongodb.com/manual/tutorial/enable-authentication/) to understand how mongo handle authentication.

## Resolution:
So, to make `strapi` work with this option, you must provide the `authenticationDatabase`  information in strapi (default: `admin`). With the mongo username and password.
You can do it either on the strapi initialization when create new project. Or into the file `config > environment > [your env] > database.json`.
