### ISSUE TITLE
[v4] GraphQL create mutation returns `Forbidden access` when using `user-permissions` in a relationship collection

### ISSUE THREAD

**Issue by DeividVeloso** [strapi/strapi#17202]
### Required System information

- Node.js version: v16.18.0
- NPM version: 8.19.2
- Strapi version: 4.11.3
- Database: Postgres
- Operating system: MacOS and Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I created two collections on Strapi they are:
 - Wishlists
 - Games
 
 The `Wishlist` has this structure
 - user --> user-permissions (Wishlist has one User)
 - game --> Game (Wishlist has many Games)

The Wishlist collection is accessed only in an Authenticated Role.
The Game collection can be accessed Public

When I try to create a new Wishlist using the graphql method `createWishlist` mutation it returns a list of errors of `Forbidden access` however entity is properly created.
 

## Wishlist collection:

![image](https://github.com/strapi/strapi/assets/16343871/bef54ca1-77c6-4d27-a266-99d3d86b174f)

## Game collection:

![image](https://github.com/strapi/strapi/assets/16343871/d70eba58-e405-4bc7-b49a-7ecae344a56c)

## User collection: 

![image](https://github.com/strapi/strapi/assets/16343871/f2728bfd-f0b4-4bf2-8461-105536b3402d)

# Permissions on Authenticated Role:

## Wishlist:

![image](https://github.com/strapi/strapi/assets/16343871/c242450f-fcb7-4bb8-ac7a-17612d2a04ff)

## User Permissions:

![image](https://github.com/strapi/strapi/assets/16343871/48ce890e-17d2-41b3-ad5d-3e1353f1c0e7)

I tried to enable `find` on user permissions, but the `Forbidden access` still happens, and I think the `find` should not be used instead we need to use `me` because the Wishlist is for the user that owns the `Authorization Token` and that is creating the whilst and it is personal and private for each user.

I think that a normal user does not have the option to access data from another user of the system, in my opinion, this is a security leak.

## The Error:

![image](https://github.com/strapi/strapi/assets/16343871/24aba3c2-ac86-4a47-b5b5-1ef1c710c95f)

![image](https://user-images.githubusercontent.com/16343871/250995008-c44caea6-f56e-4d8e-9814-b11ebf3ccce4.png)

I am using the bearer token Authorization:

![image](https://github.com/strapi/strapi/assets/16343871/b0f93152-b955-47a6-bafe-2c20c7c2858f)

If I enable the `find` on User Permissions it will start to return the `user` on the `response`, but the error still happens:

![image](https://github.com/strapi/strapi/assets/16343871/6ffe3515-1541-4c2c-b374-354a5204a773)

![image](https://github.com/strapi/strapi/assets/16343871/d8ea03c5-18b9-4729-b79a-1dedaf256d73)

Again, I don't think that `find` should be used on User Permissions for individual users.

My dependencies:

```
  "dependencies": {
    "@strapi/plugin-documentation": "^4.11.3",
    "@strapi/plugin-graphql": "^4.11.3",
    "@strapi/plugin-i18n": "4.11.3",
    "@strapi/plugin-users-permissions": "4.11.3",
    "@strapi/strapi": "4.11.3",
    "better-sqlite3": "8.0.1",
    "jsdom": "^22.1.0",
    "pg": "^8.11.1",
    "slugify": "^1.6.6",
    "strapi-plugin-email-designer": "^2.1.2",
    "strapi-plugin-entity-relationship-chart": "^4.1.0"
  },
```

The result after executing the mutation:

![image](https://github.com/strapi/strapi/assets/16343871/ece43b94-9ee0-4a7e-a5b6-7a3ba7db6679)

Let me know if you need more information.

**Comment by DeividVeloso** [comment]
Using REST API the issue does not happen:

![image](https://github.com/strapi/strapi/assets/16343871/e7691793-b996-4bc4-a4e3-e0c84b10c836)


But as my frontend code is using the Apollo Server it is failing to render my components due to the `Forbidden access`

![image](https://github.com/strapi/strapi/assets/16343871/a9bcce76-04ca-443e-9324-b9b3226ab0b1)

I don't want to refactor my frontend to use REST API and I want to stay using Graphql with Apollo.

# Context

I am migrating the same application that I already have running without any issues from `strapi v3` to `strapi v4`.

**Comment by haZya** [comment]
Did you try enabling findOne as well?

Also, how would Strapi know to use me for accessing the user? The whitelist has a one-to-one relation to users-permissions user but this doesn't necessarily mean it it's the authenticated user, it could be anyone.

AFAIK, under the hood, Strapi calls the controllers for Shadow CRUD and this is the reason why you need to enable permissions to fetch the user. If you don't want to enable find or findOne to get this working, you'll have to extend the query and override the resolver and add your own logic to get the data instead of using the Shadow CRUD.

**Comment by DeividVeloso** [comment]
@haZya thanks to try to help, I tested with all permissions enable just to check:

![image](https://github.com/strapi/strapi/assets/16343871/11265655-e6d9-4891-8c38-ab9306039a98)

The issue still happen with graphql

![image](https://github.com/strapi/strapi/assets/16343871/da8a9de4-d78c-48fc-9c07-0dbd2cd6d67a)

**Comment by haZya** [comment]
Hey @DeividVeloso  Tested and working. Tested on v4.11.2

![image](https://github.com/strapi/strapi/assets/63403456/80ea5512-469d-409c-a4dd-f569c23c8c52)

Only needed to enable `find` in `users-permissions`.

Make sure that you don't have any middleware/policy/lifecycle in front preventing it from fetching. Other than that, can't say anything for sure without being able to reproduce.

**Comment by DeividVeloso** [comment]
@haZya thanks again, but it is not working.

I created a public repository that you can clone if you want and there you will see that the issue still happening.

![image](https://github.com/strapi/strapi/assets/16343871/a1473f7d-62c4-4919-9d63-17b60bf51d7b)

### Repository
https://github.com/DeividVeloso/strapi-v4-user-issue

### Instructions
https://github.com/DeividVeloso/strapi-v4-user-issue/blob/main/INSTRUCTIONS.md

**Comment by haZya** [comment]
Hey again @DeividVeloso

I didn't look into it yet, so I might be wrong. But it seems like you are getting the user data correctly. What you aren't getting is the user role data correct? Did you try enabling the `find` permissions for the role as well?

![image](https://github.com/strapi/strapi/assets/63403456/c945e594-f685-46b5-9eba-9d8a0097dbdf)

**Comment by haZya** [comment]
@DeividVeloso 

I've tested out your repo as well. And with the following permissions it works perfectly.

1. Wishlist `create`
2. Users-permissions.user `find`
3. Users-permissions.role `find`

![image](https://github.com/strapi/strapi/assets/63403456/42c7604c-10b5-4132-8533-98db30bca7fa)

> So, on my mutation I was expecting to return/create just the wishlist to the autenthicated user that is who owns the JWT token.

> I don't want that users have access to another users.

For the above concerns, you can easily fix it by putting a policy in front of the createWishlist mutation/endpoint or using beforeCreate lifecycle hook.
You'll only request the games from the input and add the user id to the args by using ctx.state.user.id;
```
{
  "data": {
    "games": ["1", "2"]
  }
}
```

If you are using a policy
```
policyContext.args = { ...policyContext.args, user: ctx.state.user.id }
```

Or if you are using a lifecycle

```
  beforeCreate(event: Event) {
    const { data } = event.params;
    const ctx = strapi.requestContext.get();
    data.user = ctx.state.user.id;
  },
  ```
  
  Also as a rule of thumb, I always put a default attribute called `author` on every content type that is related to user. This way you don't need the `user` attribute in the Wishlist content-type since it will have `author`. Something like the below in `register()`.
  
```
  register({ strapi }) {
    strapi.contentType("api::wishlist.wishlist").attributes.author = {
      type: "relation",
      relation: "oneToOne",
      target: "plugin::users-permissions.user",
      private: true,
    };
  },
```

This way the author attribute will be available for all user-related content types regardless you want to use it or not and this way it'll be easier in the future if, for instance, you want to use a is-owner policy you can use the attribute to check against the ownership.

When fetching however this will still require you to enable `find` permissions as that is the auth scope being used if you don't want to enable `find` due to security reasons you could put a policy in front to prevent unauthorized access.

```
// is-role-allowed.ts

import { Strapi } from "@strapi/strapi";
import utils from "@strapi/utils";

const { ForbiddenError } = utils.errors;

export interface IIsRoleAllowedPolicyConfig {
  roles: string[];
}

export default (
  policyContext,
  { roles }: IIsRoleAllowedPolicyConfig,
  { strapi }: { strapi: Strapi }
) => {
  if (roles.includes(policyContext.state.user.role.name)) {
    return true; // Go to next policy or will reach the controller's action.
  }

  throw new ForbiddenError();
};
```

The above policy will check for allowed roles for example you can specify a role like `Admin` to have the ability but exclude `Authenticated`

Another rule of thumb is to create a new mutation called `createWishlistMe` or something where it will be separate from the default `createWishlist`. By doing so you can leave the default  `createWishlist` intact for an `Admin` user to use while you create a new mutation for `Authenticated` users called `createWishlistMe`. This also allows you to create custom logic to fetch the data thus not requiring permission to `find` scope.

There are more advanced thing you can do like dynamically creating queries and mutations from existing ones but that requires a lot of additional coding and hacking around to get access to the schema and extending it on server bootstrap. The above-mentioned solutions should be for common issues like the one you are having.

I know this is a pain right now, having to do all this to make a secure robust API with strapi. This is mostly because the users-permissions plugin is salvaged up from the old v3 and hasn't been updated in v4 like the other areas. They are hopefully working on a better users-permissions plugin to allow more granular control and sanitization.

Let me know if you need any help on this!

**Comment by DeividVeloso** [comment]
@haZya thank you so much for your help, I don't know how to use `policy` and `beforeCreate`, but I will search about them on the strapi documentation. Thanks again for the `Author` tip.

About `me` on the strapi v3 is working as expected, I already have this same project running perfectly on Strapi V3 with graphql and now I am trying to migrate to strapi v4.

**Comment by haZya** [comment]
@DeividVeloso Gald I could help!

> About me on the strapi v3 is working as expected, I already have this same project running perfectly on Strapi V3 with graphql and now I am trying to migrate to strapi v4.

Yes, the auth scope usage in v3 is a bit different compared to v4. v4 has a more strict auth scope on relations compared to v3 and also has separated graphql resolvers from controllers. This is not really a bad thing but just makes things harder for the developer experience. This has long been an issue since the v4 release. https://github.com/strapi/strapi/issues/12238

**Comment by DeividVeloso** [comment]
@haZya just to let you know I found this solution here https://dev.to/paratron/limit-access-of-strapi-users-to-their-own-entries-298l I did not try yet, but seems that will work, but again it is more hack/workaround then a solution. I hope strapi teams return with the user `me` and its features method again.

Thank you.

**Comment by haZya** [comment]
@DeividVeloso 

In that article, he's doing the same thing I described except that he has an attribute called `owner` instead of `author`. And he's overriding the controllers check for the ownership. While this works it's better to use a is-owner policy instead since you can reuse it. Also FYI overriding the controller will **NOT** work for graphql since graphql resolvers are separate from the controllers in v4 and you'll have to override the resolvers as well. That's why I suggested you use a policy or lifecycle hooks because they work for both REST and GraphQL.

This is the is-owner policy I use that works for both REST and GQL. You can put this in front of any `findOne` endpoint/query and it'll work as long as you have the `author` attribute.

```
import { Strapi } from "@strapi/strapi";
import { PolicyError } from "@strapi/utils/dist/errors";

export interface IIsOwnerPolicyConfig {
  uid: string;
  roles: string[];
}

export default async (
  policyContext,
  { uid, roles }: IIsOwnerPolicyConfig,
  { strapi }: { strapi: Strapi }
) => {
  const getId = () =>
    policyContext.params?.id ??
    policyContext.args?.id ??
    policyContext.request?.query?.id;
  const userId = policyContext.state.user?.id;

  if (getId() === "me") {
    if (policyContext.params?.id) policyContext.params.id = userId;
    else if (policyContext.args?.id) policyContext.args.id = userId;
    else if (policyContext.request?.query?.id)
      policyContext.request.query.id = userId;
  }

  if (!roles.includes(policyContext.state.user?.role?.name)) {
    return true; // Go to next policy or will reach the controller's action.
  }

  let authorId = getId();
  if (uid !== "plugin::users-permissions.user") {
    const data = await strapi.entityService.findOne(uid, getId(), {
      populate: "author",
    });
    authorId = data?.author?.id;
  }

  if (userId === +authorId) {
    return true; // Go to next policy or will reach the controller's action.
  }

  throw new PolicyError("You are not allowed to perform this action"); // If you return nothing, Strapi considers you didn't want to block the request and will let it pass
};
```

And you can use it like

```
config: {
  policies: [
    {
      name: "plugin::users-permissions.is-owner",
      config: {
        uid: "api::wishlist.wishlist",
        roles: ["Authenticated"],
      } as IIsOwnerPolicyConfig,
    },
  ],
}
```

For mutations like `create` I'd generally create a new mutation called e.g. `createWishlistMe` that doesn't take an id and instead get the id from ctx.state.user.id so you make sure the record is attached to the current authenticated user. You could do the same with a lifecycle beforeCreate as well since it works for both GQL and REST. The thing to note is that overriding controllers/resolvers like in the [article](https://dev.to/paratron/limit-access-of-strapi-users-to-their-own-entries-298l) or using lifecycle hooks both change the default behaviour of the respective endpoint.

At the end of the day, it's up to you which solution you want to use. Just use whichever fits best for your need. It's fine as long as it works.

**Comment by joshuaellis** [comment]
This issue looks like it's resolved? If it's not we can reopen :)

**Comment by DeividVeloso** [comment]
@joshuaellis it was not resolved, just to let you know that the user-permissions `me` method is not working as expected. I think that is an security issue be forced to enable `find` for all users.

If you have chance, try to compare the v3 user-permissions `me` versus v4 user-permissions. In V4 it is not working as expected to return the data from the authenticated user.

**Comment by Boegie19** [comment]
@DeividVeloso This is not a security issue since you can add a policy that just blocks all requests done to the find endpoint. Yes I agree that the find permission needs to be split of from the population but that would be a v5 enhancement. not something fixable in v4 since it would be a breaking change.

**Comment by DeividVeloso** [comment]
@Boegie19 got it, but I tried to use `policy`, but it is not working for ``graphql`` it is just working when you use REST API. For me there are some bugs and security issue, as any ecommerce you have to have a way to access just your own data. Imagine if at amazon.com I could access your data account even though I am not you.

There are a lot of people asking for this issue if you look for it on strapi community and here at github issues.

Like I said before in my opinion this is a basic feature for an api.

And I don't want to be unpolite here (english is not my mother tongue).

 **I am very glad with the work of Strapi team, thank you so much for all that you build it so far.**

But there are some things that should be improved and for me this is something very important.

## Issue with policy
Graphql:

As you can see my logs are not showing on terminal and this means that is never reaching the code  there:

![image](https://github.com/strapi/strapi/assets/16343871/a56a3255-0ced-46a8-bbeb-f378707328af)

REST API:
As you can see when using REST the logs are being printed
![image](https://github.com/strapi/strapi/assets/16343871/368c5189-a68d-4f7c-a4ed-0144ae51bd70)

@haZya do you know how to solve that?

At Strapi documentation they are saying this

https://docs.strapi.io/dev-docs/backend-customization/policies#implementation
`policyContext is a wrapper around the [controller](https://docs.strapi.io/dev-docs/backend-customization/controllers) context. It adds some logic that can be useful to implement a policy for both REST and GraphQL.`

**Comment by Boegie19** [comment]
@DeividVeloso That is correct since GraphQL has its own way of managing the routes. What you just did is block the rest route.
What you should do is in the docs here https://docs.strapi.io/dev-docs/plugins/graphql#policies

**Comment by haZya** [comment]
@DeividVeloso 

I get it man. We have all been there xD. But just like @Boegie19 said this is just how v4 works and any hope of this being changed before v5 is unlikely.

Also like @Boegie19 mentioned GraphQL in v4 is completely separate from REST meaning you need to add the policies/middlewares separately as well. To add a policy to a graphql query/mutation you need to use the `resolversConfig` object.

**Comment by DeividVeloso** [comment]
@Boegie19 and @haZya thank you so much for the tips, I could add the policy for REST and GraphQL, but it was not a good solution because I will need to add it to all mutations/queries and all REST routes that uses/has relationship  with the **users.permissions**

 It worked, but it will be hard to keep it according with the code is growing and adding more collections.
 
 Do you guys know a better approach that I won't need to repeat or add it for each entry these policies? 

So far I just did for whislist and I need to add to 

![image](https://github.com/strapi/strapi/assets/16343871/18c7e882-31c4-4192-a125-cec2b3e5a367)
![image](https://github.com/strapi/strapi/assets/16343871/11b6a250-f99d-4eb7-9129-77210b12bc7d)


But it mutation/endpoint REST will have the own parameters name/data structure and etc.

**Comment by haZya** [comment]
Hey @DeividVeloso 

It's not clear what you are trying to do exactly.

If you want to block `users-permissions.user` `find` endpoint from being exposed you could add a policy in front to block that. (read my previous response on [is-role-allowed](https://github.com/strapi/strapi/issues/17202#issuecomment-1627657745) policy)

If you are trying to make an `is-owner` policy this is what I generally use that works for pretty much all cases as long as you have an attribute called `author` added to the `content-type`.
```
import { Strapi } from "@strapi/strapi";
import { PolicyError } from "@strapi/utils/dist/errors";

export interface IIsOwnerPolicyConfig {
  roles: string[];
}

export default async (
  policyContext,
  { roles }: IIsOwnerPolicyConfig,
  { strapi }: { strapi: Strapi }
) => {
  const getId = () =>
    policyContext.request?.body?.data?.author ??
    policyContext.args?.data?.author;
  const userId = policyContext.state.user?.id;

  if (!getId() || getId() === "me") {
    if (policyContext.request) policyContext.request.body.data.author = userId;
    else if (policyContext.args) policyContext.args.data.author = userId;
  }

  if (!roles.includes(policyContext.state.user?.role?.name)) {
    // No need to check for is-owner (an Admin or something)
    return true; // Go to next policy or will reach the controller's action.
  }

  if (userId === +getId()) {
    return true; // Go to next policy or will reach the controller's action.
  }

  throw new PolicyError("You are not allowed to perform this action");
};
```

Note that you can get the data in REST thru `policyContext.request.body.data` and in GraphQL thru `policyContext.args.data`

So just make sure the policy covers both of those cases. The above `is-owner` policy takes this into account and also allows you to **not include** or put `"me"` in the place of the `author` in which case it defaults to the currently logged-in user's id. You don't have to name it `author` you could call it anything you'd like `owner` or `user` or whatever just make sure it's consistent across all your `content-types` so that you can reuse the policy.

**Comment by Boegie19** [comment]
This is not the right place to ask this question a better place would be the forum or discord
