### ISSUE TITLE
Allow Pascal-Case on Models name

### ISSUE THREAD

**Issue by sdubrez** [strapi/strapi#1736]
**What is the expected behavior?**
Currently, when creating a model named `MyAwesomeModel` it results automatically in creating a model with the name `Myawesomemodel` which is not very practical to read.

It would be great to handle Pascal-Case models name for a better readability of models, for example, in the list on the left of admin panel.

**Comment by derrickmehaffy** [comment]
I agree this is pretty important, at least supporting the usual suspects (and rendering them properly on the adminUI

**Comment by caseyrule** [comment]
This is currently the primary reason I have not yet adopted strapi.  I know this seems somewhat trivial, but it makes a huge difference for the usability of this platform.

**Comment by lauriejim** [comment]
I link this issue to this global issue about models and attibutes format - https://github.com/strapi/strapi/issues/1736

**Comment by mnlbox** [comment]
@lauriejim #1736 is this issue. I think you close both issue man. :wink: 
Please re open one of them.

**Comment by lauriejim** [comment]
Miss Copy and Paste - https://github.com/strapi/strapi/issues/1139

**Comment by dougludlow** [comment]
@laurijim Can this issue be reopened? I followed the issue you you referenced (#1139), which was closed, and the subsequent issue that was referenced (#2097), which deals with an issue unrelated to this request. 

As with @caseyrule, the lack of this feature is a blocker for me from fully embracing strapi because the way models (with multiple words) are displayed in the admin UI won’t ever make sense to the average user. 

Ideally they would display with spacing instead of pascal and camel case, but I could settle with anything that isn’t all lowercase with only the first letter uppercase. 

A concreate example of this is when I create a model a name like MyAwesomeModel and then throughout the entire UI I see either Myawesomemodel or Myawesomemodels, when I would expect to see My Awesome Models or at least MyAwesomeModels.

**Comment by dougludlow** [comment]
Other related issues (closed): #1168, #661

#661 was closed in favor of #1359, which is now complete, but I still don’t see anything to address this issue.

**Comment by derrickmehaffy** [comment]
@dougludlow Please see this in the product board: https://portal.productboard.com/strapi/c/13-administration-menu

Eventually there is plans to roll this out as I have explained to the Strapi team (and they understand) that the AdminUI does not look "clean" enough to offer up as a solution to anyone that isn't technically inclined.

There is nothing in the backend that would support using different case styles as there is no "display" tag on models, fields, ect ect. That will change with the linked feature request. Right now this is not a major priority for them as the strapi team are currently in the process of completely rewriting the plugin framework and also rebuilding the frontend internal API to allow other users to hook into and build plugins that can modify that UI.

The linked issues you mentioned are in some ways directly related to this:

https://github.com/strapi/strapi/issues/1139 - basically the problem was users were creating models/fields/relations using different cases and the backend wasn't converting them to all lower case automatically thus breaking relations and causing incorrect links (will be fixed with the internal UI api changes that Strapi are working on building.

https://github.com/strapi/strapi/issues/2097 - ^^ see above response to the other issue.

**Comment by derrickmehaffy** [comment]
I understand how frustrating the odd view is on the left menu, but there is a lot of "in the background" ground work being worked on within Strapi right now and minor UI "features" can't be worked on until that groundwork is laid down in stone, else they would just have to go back and rewrite everything thus wasting both time and money.

By all means if you wanted to dig into the source yourself and maybe see if you can find some "hack" to allow for differences please do, I'm sure a PR would be great. As of right now it is not their priority and further discussion on building in difference case allotments are redirected to the feature request I linked

**Comment by dougludlow** [comment]
@derrickmehaffy thanks! That makes sense. It’s unfortunate timing for us as we’re in the process of evaluating different headless CMS’s and strapi was one the top of our list, but at this point I can’t recommend it as a solution in its current state. Thanks again for the explanation and refencences!

**Comment by derrickmehaffy** [comment]
No problem, the Strapi team are aware of some "critical" things that need to be done but there is a lot of groundwork being worked on that they had not expected. Growing pains of course, but after the ground work is done it will be much easier and faster to expand Strapi.

I see a really great future, just have to get the hard part done.

**Comment by wenerme** [comment]
This issues is no resolved, please re-open this, so the latter will no need to click every reference issues to find out.  😞

**Comment by wenerme** [comment]
Actually strapi can do this by

1. create a temp name 
![image](https://user-images.githubusercontent.com/1777211/58120095-16424c80-7c37-11e9-9192-db846979f5fb.png)
2. with correct table name
![image](https://user-images.githubusercontent.com/1777211/58120103-1b070080-7c37-11e9-95b6-30abfcd4281d.png)
3. save
![image](https://user-images.githubusercontent.com/1777211/58120142-3245ee00-7c37-11e9-9861-d5675362f20b.png)
4. edit - now can input uppercase name
![image](https://user-images.githubusercontent.com/1777211/58120114-24906880-7c37-11e9-9b4f-be9d704146bb.png)
![image](https://user-images.githubusercontent.com/1777211/58120189-47bb1800-7c37-11e9-9636-cf2dad52628d.png)

😕

**Comment by derrickmehaffy** [comment]
@wenerme the issues are closed because it is on the product board, feature requests aren't tracked here if the Strapi team plans to implement them.

**Comment by MurzNN** [comment]
@derrickmehaffy I can't find any card in https://portal.productboard.com/strapi about adding PascalCase feature to Models name, can you point to right card?

**Comment by Aurelsicoko** [comment]
You can set a custom name for Models (aka Content Types) so if you want to write it using Pascal-Case or even with spaces it is possible :)

**Comment by MurzNN** [comment]
@Aurelsicoko, can you describe how? Strapi admin interface don't allow me to type any other characters in model name, only lower-case letters and numbers! :(
