### ISSUE TITLE
GraphQl nested filters being ignored

### ISSUE THREAD

**Issue by ConorCorp** [strapi/strapi#17386]
### Required System information

- Node.js version: 16.20.1
- NPM version:
- Strapi version: 4.11.3
- Database: postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When making a graphQl call to a nested filter in strapi version `4.11.3` the filter is ignored. This is a regression bug because we recently used strapi `4.2` where the filters worked.

### Steps to reproduce the behavior

1. Make call to GraphQl API with filtering logic:
POST {{ _.baseUrl }}/graphql
```graphql
# Query Variables
{
	"kennelId": 1,
	"breed": "Labrador",
	"locale": "de"
}

# Query
query LoadDog($locale: I18NLocaleCode!, $kennelId: ID!, $breed: String!) {
	kennel(id: $kennelId, locale: $locale) {
		data {
			attributes {
				dog: content(filters: { breed: { eq: $breed } }) {
					dog {
						data {
							id
							attributes {
								name
								breed
							}
						}
					}
				}
			}
		}
	}
}
```
2. See that data is not filtered. Filter should show dogs only with "Labrador" breed, but there is also a dog with "Terrier".
Response:
```json
{
	"data": {
		"kennel": {
			"data": {
				"attributes": {
					"dog": [
						{
							"dog": {
								"data": {
									"id": "1",
									"attributes": {
										"name": "Joe",
										"breed": "Labrador"
									}
								}
							}
						},
                                                  {
							"dog": {
								"data": {
									"id": "2",
									"attributes": {
										"name": "Billy",
										"breed": "Terrier"
									}
								}
							}
						}
					]
				}
			}
		}
	}
}
```
### Expected behavior

Returned data is filtered. Filter is that they only show dog's with a breed "Labrador".
Response
```json
{
	"data": {
		"kennel": {
			"data": {
				"attributes": {
					"dog": [
						{
							"dog": {
								"data": {
									"id": "1",
									"attributes": {
										"name": "Joe",
										"breed": "Labrador"
									}
								}
							}
						}
					]
				}
			}
		}
	}
}
```
### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

[Potentially related issue](https://github.com/strapi/strapi/issues/17132)

**Comment by inumaki** [comment]
Hi @ConorCorp , I am interested to solve this bug if it's still persisting.

**Comment by inanc-g** [comment]
@inumaki it persists 
Having the same issue on Strapi 4.11.5, rolled back to 4.2 for now.

**Comment by ConorCorp** [comment]
Note: Looks like `4.8.2` doesn't have this filtering issue.

**Comment by galago** [comment]
yeah this is very annoying, my whole app is showing faulty data after upgrading. This is an urgent update. I remember it was fixed after I submitted the bug in a previous version but maybe the change was ignored in the new updates.

**Comment by galago** [comment]
Seems to be working fine for me in node 15 but not in node 16 and higher. Could that be a related issue?

**Comment by Halu95** [comment]
I also encountered this behavior and noticed that I am getting GraphQl Validation errors with Version 4.13.1.

The errors looking like this:
```
{
	"message": "Invalid parameter breed",
	"extensions": {
		"error": {
			"name": "ValidationError",
			"message": "Invalid parameter breed",
			"details": {}
		},
		"code": "BAD_USER_INPUT"
	}
}
```
Please notice that when I remove the nested filtering, I am getting the unfiltered response containing the breed field on the dog object, so this doesnt appear to have anything to do with the field being private or not having the find permissions for the dog type.

**Comment by inanc-g** [comment]
I hope that's not intentional - passing filter operators as query variables seems like an anti-pattern. Operators should be part of the query itself. And even so, the resolver should still be able to resolve the same query that was working in previous versions. This seems mostly like an unintentional regression.

**Comment by galago** [comment]
Plus it was working perfectly before

>

**Comment by galago** [comment]
> @Halu95 , the error is because in 4.13.1 graphql is using the same validateQuery as on rest api and (now sure if this is by design or it's a bug) you need to pass the filters like this:
> 
> ```graphql
> # Query
> query LoadDog($locale: I18NLocaleCode!, $kennelId: ID!, $breed: StringFilterInput!) {
> 	kennel(id: $kennelId, locale: $locale) {
> 		data {
> 			attributes {
> 				dog: content(filters: { breed: $breed }) {
> 					dog {
> 						data {
> 							id
> 							attributes {
> 								name
> 								breed
> 							}
> 						}
> 					}
> 				}
> 			}
> 		}
> 	}
> }
> # Query Variables
> {
> 	"kennelId": 1,
> 	"breed": { "eq": "Labrador" },
> 	"locale": "de"
> }
> ```

I tried this way and also doesn't work

**Comment by diacu** [comment]
Hm... for me something similar was working, but I got into other similar queries that didn't work (and I have ~700 queries, I will not refactor this!). After some digging, I found that:
- In this commit (https://github.com/strapi/strapi/commit/6356087a1af04ab637f446c940b3381dc742d8b3) `validate` query was introduced to all graphql queries as well (plus on some other places, like mutations, deletions). Validate does what sanitize does, but instead of removing invalid data, it throws and error (e.g. invalid filters in my case).
- what I don't understand is why we need to validate the query variables if we already have a sanitizer that does that (in my case removes filters such as empty objects, private fields, etc.) . What is the role of calling `validate` before `sanitize`, using the same rules, but thow an error in validate and remove the filter in santize? After all, sanitize is doing nothing. 

For me, the only solution was to patch this and comment out the implementation where an error is thrown for empty objects in filters. But probably the entire validate should be removed, since sanitize does it's job perfectly, removing invalid data.

**Comment by galago** [comment]
After updating to the latest version I have the exact same issue, even my apollo studio says that the query is correct. 

> I also encountered this behavior and noticed that I am getting GraphQl Validation errors with Version 4.13.1.
> 
> The errors looking like this:
> 
> ```
> {
> 	"message": "Invalid parameter breed",
> 	"extensions": {
> 		"error": {
> 			"name": "ValidationError",
> 			"message": "Invalid parameter breed",
> 			"details": {}
> 		},
> 		"code": "BAD_USER_INPUT"
> 	}
> }
> ```
> 
> Please notice that when I remove the nested filtering, I am getting the unfiltered response containing the breed field on the dog object, so this doesn't appear to have anything to do with the field being private or not having the find permissions for the dog type.

**Comment by ChrisCrossCrash** [comment]
I'm also getting a similar issue. This was working with Strapi v4.12.7, but not working after updating to Strapi v4.13.7:

```graphql
query GetMainNavLinks {
  navigation {
    data {
      attributes {
        mainNavLinks {
          # FIXME: Invalid parameter isHidden
          childLinks(filters: {isHidden: {eq: false}}) {
            id
            label
            url
            preload
            isHidden
          }
        }
      }
    }
  }
}
```

**Comment by viclec** [comment]
> Note: Looks like `4.8.2` doesn't have this filtering issue.

I face the same issue, in realease 4.8.2 filters work as expected, but in latest release filters seem to stop working in the same manner and throw BAD_USER_INPUT error.

Query:
`
query localeTexts($locale: StringFilterInput, $fallbackLocale: StringFilterInput) {
  texts {
    data {
      id
      attributes {
        name(filters: { locale: $locale }) {
          content
          locale
        }
        fallbackName: name(filters: { locale: $fallbackLocale }) {
          content
          locale
        }
      }
    }
  }
}
`

Variables:
`
{
  "locale": {
    "eq": "el"
  },
  "fallbackLocale": {
    "eq": "en"
  }
}
`

Is there any way to do this in another way or is there a fix on the horizon?

**Comment by osbornWmy** [comment]
Guys, any update now? Meet same problem after upgrade to 4.15.0 😢

**Comment by D0wn10ad** [comment]
It is kind of show stopper here on one hand strapi has quite a few vulnerabilities that can only be solved with version newer than 4.8.2 (counted no less than 5, at least 1 is critical/high) yet this preventing us to go newer.

**Comment by osbornWmy** [comment]
I think following issues are similar:
[GraphQL filters are not filtering repeatable components #17765 ](https://github.com/strapi/strapi/issues/17765) 
[GraphQL component nested filtering on booleans not working #17421](https://github.com/strapi/strapi/issues/17421)
[Can't sort or filter related media in graphql #17132](https://github.com/strapi/strapi/issues/17132)
[Unpublished entries are being sent in REST & GraphQL API responses #16906 ](https://github.com/strapi/strapi/issues/16906 )

According to the information provided by everyone, V4.11.2 includes the same issue, I'd like to help but progress is slow due to lack of context.
I'd like to help, and already start to exploring source codes, but process is slow due to lack of context,  @bolg55 @innerdvations @kasonde , sorry to bother, I'm very appreciate if you can kindly share some knowledge。

**Comment by alicanso** [comment]
+1

**Comment by osbornWmy** [comment]
Upgrad to 4.15.2 fixed my problem

**Comment by thomas-coldwell** [comment]
I can confirm that updating to at least 4.15.5 and Node 18 LTS solved this in our project. Checked through a number of queries after the update and they all behave correctly now
