### ISSUE TITLE
Cannot duplicate entity in collection

### ISSUE THREAD

**Issue by DawnMD** [strapi/strapi#17399]
### Required System information

- Node.js version: 16.20.1
- NPM version: 8.19.4
- Strapi version: 4.11.7
- Database: postgresql 12.4
- Operating system: Latest MacOS M2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Recently we updated strapi from v4.9.0 to v4.11.7. Previously everything is working except when updated to the latest we are finding issues when trying to duplicate the collection entity. This works completely fine when I do `strapi develop` but after building strapi with `yarn build` then `yarn start` throws the error.

### Steps to reproduce the behavior

1. Go to some collection
2. Click on the duplicate button in the entity
3. Check the network tab from the browser

### Expected behavior

It will clone the data with all the relations and data from the initial entity.

### Screenshots

![image](https://github.com/strapi/strapi/assets/34785917/a54e0070-06d3-4ec3-947b-8d0401c7a642)

### Code snippets

N/A

**Comment by derrickmehaffy** [comment]
I do see the warning (not sure if this should be a warning or not) but I'm guessing if you were not using draft & publish it would just throw the error and not render.

![image](https://github.com/strapi/strapi/assets/8593673/e5a36f3b-014f-421e-85d1-f85f8d1c8bc9)

**Comment by DawnMD** [comment]
I can confirm that we are using draft and publish. Also we don't face the particular issue in the development server but only when it's built and deployed.

**Comment by derrickmehaffy** [comment]
I saw it on both, does it actually prevent you from duplicating or the warning just shows up? If it's just the warning that might be intended but not sure.

**Comment by DawnMD** [comment]
Yes, when we try to duplicate some previous entity in a collection type there is a network error request saying the same. You can check the screenshot I posted in the big description.

**Comment by Arieftj** [comment]
hi @Marc-Roig, any update on this bug?

**Comment by joshuaellis** [comment]
This is not a bug, it's intended, you can't clone an entity with relations because we don't know (at the moment) if those relations will break another entry e.g. one-to-one relations where cloning the entity straight away would change a different entity that you're not aware of. If you manually save the entity when you're on that screen, you should get the behaviour you expect.

**Comment by Arieftj** [comment]
Hi @derrickmehaffy , will it be fixed as per the expected behavior?

**Comment by joshuaellis** [comment]
> Hi @derrickmehaffy , will it be fixed as per the expected behavior?

What difference are you expecting @Arieftj?

**Comment by Arieftj** [comment]
Hi @joshuaellis , 

- v4.3.4: The entity with the relationship is also cloned
- v4.90: The entity is only cloned but not the relations
- v.4.11.5: Not able to clone at all

My expectation clone function is working fine like it was before in v4.3.4

**Comment by Arieftj** [comment]
And, can you elaborate more on this one "If you manually save the entity when you're on that screen, you should get the behaviour you expect."?

**Comment by 100KILOFUNK** [comment]
> Hi @joshuaellis ,
> 
> * v4.3.4: The entity with the relationship is also cloned
> * v4.90: The entity is only cloned but not the relations
> * v.4.11.5: Not able to clone at all
> 
> My expectation clone function is working fine like it was before in v4.3.4

This is my expectation as well, our Editors have reported that the feature used to work but no more. We are running v4.11.5

**Comment by n2o** [comment]
In strapi version 4.13.7 the user is not redirected to the desired page to edit the unique and relational fields. So this function currently does not work and does not clone an entity at all. Event if the Collection Type only exists of a `name` field, which is unique, the cloning process does not proceed and the function is left dead.

In most cases, as also in this clip, we do not use the draft & publish function.

https://github.com/strapi/strapi/assets/1507474/cc2f19be-db0f-402c-9b90-dddd35ba89ab

In my opinion, showing up the cloned entity even with or without the problematic fields could be a solution. Maybe just filter out all relational and unique fields, but not showing a dialog to proceed leaves an apparently working button as a dead button and confuses users.

Leaving the problematic fields empty so that a user must fill them manually could be a working solution. Or, as stated above, copying all relational fields with the warning "This could be wrong, check it manually" is also feasible, although not my preferred solution (too error prone).

Thanks for your work, I think we now implement a workaround to have a custom clone function for our use case in this collection type, but in general this is not a feasible solution 😅

**Comment by ls-ramos** [comment]
Hey @n2o, I was having the exact same issue until I saw this comment: https://github.com/strapi/strapi/issues/17753#issuecomment-1695485847

I noticed I had in my `package.json` `axios` as a dependency, once I removed that dependency, removed the `.cache`, `dist` and `node_modules` folder, I finally got the expected behaviour of being redirected to the page to create an entry, seeing only the warning:
![Screenshot 2023-10-23 at 14 36 01](https://github.com/strapi/strapi/assets/29318376/3a29ce8b-2081-454f-b002-3e74744aa965)

With the `axios` as a dependency I had that issue getting the error in the network and not being redirected.

The versions I am using:

Node.js version: 18.17.0
YARN version: 3.6.1
Strapi version: 4.14.5
Database: mysql
Operating system: Latest MacOS M1
Using Typescript

I am not sure if this is issue for everyone, but I hope it can help

**Comment by Marc-Roig** [comment]
@ls-ramos do you have any unique field in your schema?

**Comment by joshuaellis** [comment]
@n2o thanks for the video and sorry for the late reply – this looks very odd indeed, you should be redirected. Did you try the comment left by @ls-ramos? :)

**Comment by ls-ramos** [comment]
@Marc-Roig Yes I do, I have a schema with a slug unique field, dynamic zone, a few component fields and multiple types of relationships.

I tried creating a strapi project from scratch and I noticed I couldn't reproduce the issue on a clean project. 
Weirdly only following the steps I commented above I could solve the issue, I did not get to bottom of why that fixed the issue yet.

**Comment by Marc-Roig** [comment]
@ls-ramos thats weird, we will investigate about this, but it might be an issue with unique fields, and not getting the proper error if trying to clone an entity when the unique field value is used by another entry.

**Comment by vovapankiw** [comment]
I had the same issue, and the reason in my case was also axios as a standalone dep. Strapi under the hood also using axios and seems like there is some conflict there. Removing axios and use native fetch or node-fetch resolved the issue.
"@strapi/strapi": "4.14.4",
"axios": "1.5.0",

**Comment by bobbylipps** [comment]
Having a similar issue. I try to clone a page and nothing happens on the front end but if I look at the network tab I see.

`Entity could not be cloned as it has unique and/or relational fields. Please edit those fields manually and save to complete the cloning.`

This didnt happen on the previous version of Strapi I was using which was 4.7.1. Soon as I updated to 4.14.0 or greater I can't clone/dup pages and I get this error. Sort of an important feature that we use often.

**Comment by derrickmehaffy** [comment]
elevating issue per escalation policy, related to internal TID5189

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy is there any way to know which PR removed the feature and added the restriction so that we can implement that ourselves if we need it?

You can use the git blame to trace it back but I think it was quite a while ago, most likely around 4.5 or 4.6 if I had to guess.

**Comment by alexdevmotion** [comment]
Any update on this?
It's also impacting our workflow, we've been heavily relying on the duplicate feature, now we'll be wasting serious additional hours copying stuff around.

**Comment by G3orgi0s** [comment]
Come on Strapi-team, we need this EARLIER than later please! Content-moderators are spending TOO much time retyping the same data! Some PRIORITY on this features PLEASE?!

**Comment by ConradP** [comment]
I would also like to chime in that I have some content creators on my team who are eager for this to be addressed.

**Comment by joshuaellis** [comment]
This is being locked. We've said when we aim to do some changes 😊
