### ISSUE TITLE
`@strapi/typescript-utils` pollutes redundant dependencies (Prettier & TypeScript)

### ISSUE THREAD

**Issue by OiYouYeahYou** [strapi/strapi#17448]
### Describe the bug

Prettier and TypeScript are both listed as prod dependencies in `@strapi/typescript-utils`, therefore polluting consuming projects

### Expected behaviour

For these dependencies to either be in `devDependencies` or in the mono repo dependencies

**Comment by joshuaellis** [comment]
It's required because the code we use uses functions from the libraries, I don't think there's anything we're going to action without really good reason – which i can't see here at the moment.

**Comment by cesar3030** [comment]
After I upgraded to the latest Strapi version, my CI started to fail with this error:
>Oops! Something went wrong! :(
>
>ESLint: 7.17.0
>
>ESLint couldn't find the plugin "eslint-plugin-prettier".
>
>(The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory "/home/circleci/busbud-strapi".)
>
>It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
>
>    npm install eslint-plugin-prettier@latest --save-dev
>
>The plugin "eslint-plugin-prettier" was referenced from the config file in ".eslintrc » @busbud/eslint-config".
>
>If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

After further investigation it turns out both our company eslint package and Strapi are using prettier as dependency but not the same versions. This is the reason why the plugin is no longer detected.

I had to add a resolution in package.json to a specific version of prettier to be used by both Strapi and our package to fix the issue.

This is not an ideal solution, it would be nice if you could find a work around to stop shipping Strapi with dependencies that are supposed to be devDeps.
