### ISSUE TITLE
Forgot Password error "Email Invalid" after hitting the send button 3 times.

### ISSUE THREAD

**Issue by chrisdekker1997** [strapi/strapi#1755]
**Informations**
- **Node.js version**: Node 10.7.0
- **npm version**: npm 6.1.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: mongodb
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
Strapi returns a error `{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.form.error.email.invalid"}]}]}`

**Steps to reproduce the problem**
Go to "forgot password" link at the Strapi login screen. Enter your emailaddress and click the button about 3 times fast

**What is the expected behavior?**
Strapi sends the forgot password email

**Suggested solutions**
Stop any calls after the button click or don't process a call with the same 'call id or session id' as the previous one.

**Comment by lauriejim** [comment]
Hello @chrisdekker1997 ! Thank you for reporting this issue.
It's because by default we use `sendmail` provider and in your case, you can't send email.
This is the error https://github.com/strapi/strapi/blob/master/packages/strapi-email-sendmail/lib/index.js#L47
I suggest you to use an other email provider. https://strapi.io/documentation/guides/email.html#install-providers

**Comment by lauriejim** [comment]
And can you please provide a PR to update the error message. By updating translation key and by updating translation values. Will appreciate your contribution on this point.

**Comment by lauriejim** [comment]
@chrisdekker1997 can you give me an update about the PR you speack about. Will appreciate your contribution on this issue.

**Comment by lauriejim** [comment]
Has been fixed in the last release.

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/pull/2060
