### ISSUE TITLE
Create seamless checkout/deployment process.

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1763]
**What is the expected behavior?**

I wouldn't want to check in all the source code for the `/admin` including the `build` folder into git. This seems very very wasteful to me.

The preferred way, would be to check in only the `public`, `config` and `api` folder. Everything else should be able to be generated from simple instructions. This is important both for deployment and working correctly with git.

**Updates of the core strapi version should be handled like a `package.json`**. In fact, I wouldn't mind if the entire `admin` package is part of `node_modules` However, this may conflicts with the philosophy of Strapi to be hackable to the core - even the admin modules, so maybe there could be a way to extend or eject. But for most projects, they would be fine without having the admin in their source code.

There are multiple problems in the way that make this approach impossible right now:
**There is no plugin management:** Plugins from the marketplace are just downloaded, but there is no package.json that takes note which plugins were downloaded. Again: For better extension and changes, it would be nice to be able to change or hook into the plugins without having the entire source code of every single plugin checked into my own git repo.

**There is no deployment mechanism:** The only mechanism right now is "change env to prod". While this is a nice mechanism to control the settings via environment variables, there is no mechanism to build from scratch  (pull in plugins, required admin version) - this would also make the docker containers work better. Right now - I didn't manage to get strapi to work as docker image.

**Strapi is installed as global package:** It is .. nice but not required. Preferrable (look at vuepress, nuxt, gatsby, etc) you would install it locally to better control the dependency. This would also avoid major confusions with users that do `npm i -g strapi` to update from an older version, see the new version with `strapi version` but fail to update the version shown in the dashboard. :|

**Comment by Aurelsicoko** [comment]
Thank you for this issue, I will do my best to answer to every part of it.

- Our philosophy is to make Strapi fully customisable. That's why we made the choice to pick the admin from the `node_modules` and create an `admin` folder inside the project. It let to the user the possibility to hack the administration, it couldn't be possible if the administration was a package. 
However, we could offer both way to associate an administration to the project. By default, it could use the `admin` package available inside the `node_module` except if there is an `admin` folder available in the project. 

- The plugin management is coming and we won't base it on the `package.json`. There will certainly have `strapi.json` file to handle the plugin dependencies, etc. However, we face to the same issue to make every plugin hackable... We need to keep the source inside the project itself.

- I would love to have more insights into the deployment mechanism part... I'm not sure to understand your meanings on that part.

- We suggest to install Strapi (for the ease of use & CLI) as a global package but it also works with local dependency.
