### ISSUE TITLE
View prefix to plugin routes in Roles & Permissions route viewer

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1765]
**What is the expected behavior?**

When I wanted to dive into how to use `/roles` and `/permissions` are used, I had a little of a problem to get started.
The roles and permissions admin panel shows me that I can use `/roles`
So I tried that route:
![image](https://user-images.githubusercontent.com/2950505/44260160-e8e1f180-a213-11e8-91c0-16f31f2822d1.png)

Only when @soupette reached out to me, I found out that actually I need to prefix the route with `/users-permissions` in order to make it work.

So the full route is `http://localhost:1337/users-permissions/permissions`

It would be nice to either:

- document that
- or even better: display the plugin prefix in the route "explorer".

**Comment by soupette** [comment]
@Aurelsicoko & @lauriejim 

> Is there a specific design decision to make /users-permissions/permissions and /users-permissions/roles to be part of the plugin via the Rest API, and /user can be reached without the plugin prefix?

What are your thoughts?

**Comment by Aurelsicoko** [comment]
Yes, there is a simple reason. We are building an ecosystem. Let's take an example, there are two developers which are building separately two plugins A & B. 

The first developer sets a route `GET /reset` in the plugin A. The other developer sets a route `GET /reset` in the plugin B. Both developers don't know each other. They decide to publish the plugin on our marketplace (not at the same time, but it's not so important). 

Now, I'm building my project and I want to use the plugin A and the plugin B. I download them. But one of the plugins doesn't seem to work as excepted when I tried to reset. Why? Oh, the `GET /reset` route of the plugin B overrides the route of the plugin A.

At a large scale, you have to prefix the route to let the freedom to the developers of a plugin to name his routes like he wants. Otherwise, it means it has to check in every others plugins that no one is using this route. It simply doesn't work. 

I know the routes aren't as simple as they could be but this solution works perfectly in any case. However, there is an option in the routes of the plugin to avoid the prefix. You need to set the prefix to empty and the route won't be prefixed.

```json
{
  "routes": [{
      "method": "GET",
      "path": "/user",
      "handler": "User.find",
      "config": {
        "policies": [],
        "prefix": ""
      }
   }]
}
```
