### ISSUE TITLE
Unrecognized sanitizeOutput and transformResponse Functions in Strapi Controller

### ISSUE THREAD

**Issue by ElonMuskOfficial** [strapi/strapi#17784]
### Bug Report

**Required System Information**
- Node.js version: 18.17.0
- NPM version: 9.5.1
- Strapi version: 4.11.7
- Database: PostgreSQL
- Operating system: Windows 11
- Is your project JavaScript or TypeScript?

**Describe the Issue:**
I'm encountering problems with the `sanitizeOutput` and `transformResponse` functions provided by Strapi. These functions are not recognized as properties of the controller object, leading to compilation errors.

**Steps to Reproduce:**
1. Create a controller using the `createCoreController` function.
2. Attempt to use the `sanitizeOutput` and `transformResponse` functions within the controller's methods.
3. Observe errors such as:
   - `Property 'sanitizeOutput' does not exist on type '{ findOne(ctx: any): Promise<any>; }'`
   - `Property 'transformResponse' does not exist on type '{ findOne(ctx: any): Promise<any>; }'`

**Expected Behavior:**
The `sanitizeOutput` and `transformResponse` functions should be accessible and recognized as properties of the controller object when using Strapi's built-in functions.

**Additional Context:**
Steps or code snippets I've already tried:
  ```javascript
  const { createCoreController } = require('@strapi/strapi').factories;

module.exports = createCoreController('api::post.post', ({ strapi }) => ({
    async findOne(ctx) {
        const { slug } = ctx.params;

        const entity = await strapi.db.query('api::post.post').findOne({
            where: { slug }
        });

        const sanitizedEntity = await this.sanitizeOutput(entity);

        return this.transformResponse(sanitizedEntity);
    }
}));

**Comment by EsGeh** [comment]
I'd claim this to be a severe issue, since this is the way to overwrite existing controller functionality suggested by the official developers doc.
And it doesn't work. Copy/pasting the code from the developers doc leads to a runtime error.

I am no Javascript expert, but it seems to have to do with the "setPrototypeOf" not working as expected in [the source code](https://github.com/strapi/strapi/blob/0cc6505a601377247184f9ac74b5edab9e3283fa/packages/core/strapi/lib/factories.js#L33C1-L33C53)

Is there an intermediate fix for this?

By the way: `this.validateQuery` is undefined too...

**Comment by EsGeh** [comment]
Actually, strapi version `4.13.4` fixes this issue for me...
Sorry for complaining

**Comment by derrickmehaffy** [comment]
We'll go ahead and set this closed then
