### ISSUE TITLE
Permissions API is broken - I want to be able to ask who can do what

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1781]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: alpha 13.1
- **Database**: pg
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**

Asking `users-permissions/permissions` does not reflect the state that the guest or authenticated user has set.

![image](https://user-images.githubusercontent.com/2950505/44414877-2e355480-a56f-11e8-9c63-3fd236e5cf25.png)

There is NO single `"enabled": true` in this list!

**Steps to reproduce the problem**

Set a few permissions for guest user, ask http://localhost:1337/users-permissions/permissions

**What is the expected behavior?**

Have enabled set correctly with true or false, not just false for everything.

**Suggested solutions**

Create more API points for permissions, I want to be able to tell my users if they are able to create new events or not from my front-end.

**Comment by avallete** [comment]
Same issue here.

Pretty strange since the route: `users-permissions/roles/:roleId` give me correct infos. (but provide way to many data (like who have the same role, etc...) witch can lead to security issue (cf: [OWASP](https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002))) ).

Maybe, a way to retrieve the user 'role' associations details into the `/me` route could be fine.

**Comment by lauriejim** [comment]
@MartinMuzatko route `users-permissions/permissions` is used to create new role. It doesn't give you roles permissions.
As @avallete said, the correct route to get the info you want is `users-permissions/roles/:roleId`

If you use `/me` route you can get the role id then use the previous route to know what this user can do.
