### ISSUE TITLE
The password requirements are different for different input methods

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1785]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: alpha 13.1
- **Database**: pg
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**

Right now you have the following mechanisms to set a password:

- Initial strapi start - creating a user (no requirements - was able to use 5 characters)
- Reset password (currently failing, see #1784)
- Set password via profile (6 characters required)
- Create new user from admin (6 characters required)

**Steps to reproduce the problem**

**What is the expected behavior?**

Always have the same rules about setting a password

**Suggested solutions**

Use the same mechanism for setting a password in each part of the user interface

**Comment by derrickmehaffy** [comment]
Should be noted these password requirements should also be documented in the Strapi Docs and/or also be configurable.

**Comment by lauriejim** [comment]
Hello @MartinMuzatko , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
Related Branch: https://github.com/strapi/strapi/tree/fix/1785
