### ISSUE TITLE
Posting to /upload and can't find the file in the public/uploads directory

### ISSUE THREAD

**Issue by YouhannaSabry** [strapi/strapi#1790]
**Informations**
- **Node.js v9.5.0**:
- **npm 6.1.0**:
- **Strapi 3.0.0-alpha.13.1**:
- **Database MongoDB**:
- **Ubuntu 18.04 Bionic Beaver**:

**What is the current behavior?**
Whenever I post to /uplaod using postman or angular <image-upload> I can't find the file in the public uploads directory.. it returns a response "true" and the file is not there.
When I curl without @ before file path "curl -X POST -F 'files=Pictures/1.png' http://localhost:5000/upload" same thing happens.. return true and file is not there.
However if I curl with @ before the filepath "curl -X POST -F 'files=@Pictures/1.png' http://localhost:5000/upload" I find the file there..
Also dragging and dropping using the adminAI works..

**Steps to reproduce the problem**
Posting to /uploads using postman or angular2 image-upload component 

**What is the expected behavior?**
Finding the file in the public/uploads directory

**Comment by lauriejim** [comment]
Please check our SDK https://github.com/strapi/strapi-sdk-javascript#files-management 
I think it can help you

**Comment by derrickmehaffy** [comment]
@YouhannaSabry If you are getting that response then your POST request isn't formatted properly.

I have tested this with postman:

![image](https://user-images.githubusercontent.com/8593673/44609133-6032fa80-a7ab-11e8-9254-6018f58921b5.png)

And it works as intended, as @lauriejim said I would look at the SDK and use the functions there to setup your angular frontend, you need to load the SDK as it states in order to use those functions.
