### ISSUE TITLE
"id" field cannot be used in typed filters since v4.13.1

### ISSUE THREAD

**Issue by liarco** [strapi/strapi#17934]
### Required System information

- Node.js version: `v18.17.0`
- NPM version: `9.6.7`
- Strapi version: `4.13.1`
- Database: `SQLite`
- Operating system: `macOS 13.4.1`
- Is your project Javascript or Typescript: Typescript

### Describe the bug

As mentioned in #17906, using the `id` field in filters causes typechecking errors in TS projects when types are generated using `yarn strapi ts:generate-types`.

### Steps to reproduce the behavior

<img width="681" alt="Screenshot 2023-09-04 at 19 22 52" src="https://github.com/strapi/strapi/assets/1532277/5d86da6b-1e02-44f1-904e-14cae7fe4ee5">

Using the `id` field here is pretty useful, especially when other fields are optional.

### Expected behavior

The `id` field should be supported by the nested filter type.

**Comment by Convly** [comment]
I was able to reproduce the issue.

**With generated types**
![image](https://github.com/strapi/strapi/assets/25851739/101f96bd-21d7-4296-9c27-0094733715cd)

**Without generated types**
![image](https://github.com/strapi/strapi/assets/25851739/2b77f165-42a7-4d78-b7d1-2cd5f02a2ef3)

- It works when types are not generated because it cannot determine the possible field names & thus assume all string as valid fields
- It doesn't work when types are generated because we don't explicitly allow ID attributes on top of "real" attributes

Context: https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/services/entity-service/types/params/filters/index.d.ts#L48-L73

**Comment by derrickmehaffy** [comment]
@Convly will this happen with other system types? eg. createdBy, updatedBy, createdAt, updatedAt, publishedAt, ect?

**Comment by Convly** [comment]
creator fields & co are attributes added dynamically to the schemas after startup. ID is not an attribute, just a value present in the actual data

So basically: no we won't have this issue for those fields

**Comment by derrickmehaffy** [comment]
Experimental version: `0.0.0-experimental.5a2b790ac9ad5e7f58450cf0fd20c069e64dbd31` for those that want to test the pending PR

**Comment by liarco** [comment]
Thank you @derrickmehaffy I just tested `0.0.0-experimental.5a2b790ac9ad5e7f58450cf0fd20c069e64dbd31` in my dedicated test-case and the issue seems to be fixed. Couldn't spot any side-effects even though I must say it's a pretty small test project.

Btw, I probably lived under a rock, but it's the first time I see [this pipeline to test PRs](https://github.com/strapi/strapi/actions/runs/6089925181/workflow) in action and I love it. It's extremely simple but great, I spent more time writing this reply than what it took me to test the fix. 🤟
