### ISSUE TITLE
New filter: _notcontains

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1797]
**What is the expected behavior?**

For full-text search, it would be nice to be able to exclude a word.

So I can search for `http://localhost:1337/page/content_notcontains=test`

**Comment by lauriejim** [comment]
Hello @MartinMuzatko , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by Aurelsicoko** [comment]
Let's do it!

**Comment by Aurelsicoko** [comment]
I created a public card on Product Board. I think the feature is pretty simple to understand but if you want to give me more insights, feel free to do it (https://portal.productboard.com/strapi/c/33-add-notcontains-filter).
