### ISSUE TITLE
How to turn NPS Survey off completely

### ISSUE THREAD

**Issue by yyf365** [strapi/strapi#17978]
- Node.js version:16.15
- NPM version:
- Strapi version:4.13.3
- Database:pg
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

How to completely turn them off？

<img width="772" alt="image" src="https://github.com/strapi/strapi/assets/12697067/adbf7dd1-98f0-4579-bc4d-87b980d3df0e">

and

<img width="729" alt="image" src="https://github.com/strapi/strapi/assets/12697067/c256228b-b489-4f1c-a1ff-4c2bd4a2b097">

This method of collecting data also hopes to have a closure method. It is best not to force submission of such things, and to send network requests to external parties multiple times“ https://analytics.strapi.io/api/v2/track I don't want to send requests or collect data to an unknown address when using Stratpi or any of its pages without my knowledge. It's like hanging a Trojan on my site. Please provide a way to completely shut them down

**Comment by yanniskadiri** [comment]
Hey @yyf365, thanks for highlighting this. We don't have the bandwidth currently to address it, but we'll work on something in about 3 weeks.

**Comment by yyf365** [comment]
> Hey @yyf365, thanks for highlighting this. We don't have the bandwidth currently to address it, but we'll work on something in about 3 weeks.

thank you very much for accepting this suggestion

**Comment by remidej** [comment]
Until we decide on a proper solution, running this snippet in your console should permanently disable the feature:

```js
window.localStorage.setItem(
  'STRAPI_NPS_SURVEY_SETTINGS',
  JSON.stringify({ enabled: false })
);

**Comment by yanniskadiri** [comment]
Hey @yyf365, we've discussed your issue in the team.

We run the NPS survey in-app to get feedback from users and learn more about their level of satisfaction when using Strapi. That being said, they don't have to answer the survey if they don't want to. In that case, they just have to close the pop-up and the survey won't appear again before 7 days the first time, and then before 90 days the second time.

Now I'd like to know:
- if this is enough - and maybe we should just let the users know when they close the pop-up that it's how it works
- Or if your issue is that you would like to disable the survey completely. If yes, is @remidej's solution just above enough or would you need us to implement another solution to solve your issue?

**Comment by derrickmehaffy** [comment]
@yanniskadiri / @remidej I would suggest we still allow disabling it completely as we do for all of the other "pop ups":

- Tutorial Videos disable: https://docs.strapi.io/dev-docs/admin-panel-customization#tutorial-videos
- Releases notification: https://docs.strapi.io/dev-docs/admin-panel-customization#releases-notifications

Or we could also check if the user has telemetry enabled or not (https://docs.strapi.io/dev-docs/usage-information#opt-out) since the data is actually making a request to our analytics server as seen in the screenshots.

I do think that a user/customer should be able to turn this off completely as our customers will tend to "white label" and remove all the Strapi references through customization and I believe our users should have a similar freedom.

**Comment by yyf365** [comment]
> Hey @yyf365, we've discussed your issue in the team.
> 
> We run the NPS survey in-app to get feedback from users and learn more about their level of satisfaction when using Strapi. That being said, they don't have to answer the survey if they don't want to. In that case, they just have to close the pop-up and the survey won't appear again before 7 days the first time, and then before 90 days the second time.
> 
> Now I'd like to know:
> 
> * if this is enough - and maybe we should just let the users know when they close the pop-up that it's how it works
> * Or if your issue is that you would like to disable the survey completely. If yes, is @remidej's solution just above enough or would you need us to implement another solution to solve your issue?

First of all, I want to express my sincere gratitude to all of you for your attention to this issue. Now, let me share my thoughts and perspective on the matter. When it comes to gathering opinions and feedback, I believe that most of us are not opposed to it; in fact, many of us are quite supportive of efforts aimed at fostering positive development within the community. However, what I'd like to highlight is that the current approach has some issues and lacks user-friendliness. There are two main reasons for this:

1. Advance Notification Required: Firstly, there should be prior notice before implementing the data collection window and sending the collected data to external servers.

2. Lack of Server-Side Shutdown: Secondly, there is no provision for a server-side shutdown method or switch. In some cases, this can lead administrators to mistakenly believe that the server is infected, causing unnecessary disruptions. We cannot expect everyone to execute code that only works when configured in the browser.

Thank you for taking these concerns into consideration.

**Comment by yyf365** [comment]
> @yanniskadiri / @remidej I would suggest we still allow disabling it completely as we do for all of the other "pop ups":
> 
> * Tutorial Videos disable: https://docs.strapi.io/dev-docs/admin-panel-customization#tutorial-videos
> * Releases notification: https://docs.strapi.io/dev-docs/admin-panel-customization#releases-notifications
> 
> Or we could also check if the user has telemetry enabled or not (https://docs.strapi.io/dev-docs/usage-information#opt-out) since the data is actually making a request to our analytics server as seen in the screenshots.
> 
> I do think that a user/customer should be able to turn this off completely as our customers will tend to "white label" and remove all the Strapi references through customization and I believe our users should have a similar freedom.

That's correct, I completely agree with your point of view.

**Comment by segovia** [comment]
I would also like to be able to disable this survey. It doesn't make sense to have it for my use case.

**Comment by Boegie19** [comment]
see the response from [remidej](https://github.com/remidej) 
> Until we decide on a proper solution, running this snippet in your console should permanently disable the feature:
> 
> ```js
> window.localStorage.setItem(
>   'STRAPI_NPS_SURVEY_SETTINGS',
>   JSON.stringify({ enabled: false })
> );
> ```

**Comment by segovia** [comment]
Yes, while this workaround is useful, it is not a solution. A proper way should exist to disable the survey.

**Comment by Boegie19** [comment]
Looked at the code. some notes.

// Because we only enable the NPS for users who subscribe to the newsletter when signing up

// For users who had created an account before the NPS feature was introduced,
// we assume that they would have enabled the NPS feature if they had the chance.

aka they only enable it if you enabled accepted the news letter or if you used strapi before this feature was implemented,

**Comment by Boegie19** [comment]
In the next strapi feture there is now a way to fully disable it in.

config/admin.js add

```
flags: {
    nps: true,
  },
```

**Comment by derrickmehaffy** [comment]
> In the next strapi feture there is now a way to fully disable it in.
> 
> config/admin.js add
> 
> ```
> flags: {
>     nps: true,
>   },
> ```

Can you do a PR to the docs to add that please?
