### ISSUE TITLE
Question: Moving from 1.5 to 3

### ISSUE THREAD

**Issue by v3yr0n** [strapi/strapi#180]
Hey!

I'm about to start a new project with Strapi (btw, nice project!) but I have a question about moving from v1.5 to 3: Will it be possible? I mean, via some upgrade script or something? Or will they be totally different and impossible to do?

Thanks!

**Comment by pierreburgy** [comment]
Hi @v3yr0n,

It will possible but will require important manual changes.

The files structure will be pretty much the same, but Strapi v3 will use a lot of new patterns (such as ES6, async/await...) that you will have to implement yourself in you project if you migrate from 1.5 to 3. Also, the new dashboard will be completely rebuilt.

Strapi v3 is still not ready for production, so we encourage you to use v1.5 and to plan some days to migrate to v3.

**Comment by v3yr0n** [comment]
Hey @pierreburgy thanks for answering. 
The project i'll start is a long-term project, so maybe i should already start with v3. What do you think?

**Comment by fivepointseven** [comment]
What is the approximate timeline for the production ready v3 release? 
Cause I'm working on a big project right now using v1.5 but I would definitely like to move the whole project to v3 as soon as that becomes possible.

**Comment by Aurelsicoko** [comment]
@v3yr0n You should start your project with the v3, IMO. However, you couldn't use the Studio or the dashboard. Also, breaking changes could happen in the near future but the v3 is more and more stable and the changes are minors.

**Comment by v3yr0n** [comment]
@Aurelsicoko yeah, i agree with you. I can live without studio :) but the dashboard... I really needed it... How much time do you think it'll take?

**Comment by Aurelsicoko** [comment]
@fivepointseven Hi, we just updated the [ROADMAP]( https://github.com/strapi/strapi/blob/master/ROADMAP.md) on `master` . FYI, the migration from v1 to v3 could be difficult in certain cases. The major changes will be:

* New pattern async/await (could cause **major changes** in some cases).
* Mongoose ORM instead of Waterline (could also cause **major changes** but the API is quite similar)
* New way to declare routes (**minor changes**)
* New way to declare databases configurations (**minor changes**)

The others changes are added features so it will break nothing in your current apps. Moreover, I must remind that the v3 doesn't support GraphQL for now. We are focused on the new dashboard and our new plugin-based architecture. We will support GraphQL in the near future but this is not our priority. 

We will write two guides to help you during the migration step:
- From v1 to v3
- From v2 to v3

We also plan to build an example project to make easiest for the community to understand what are the major changes in the new version. This is a big step forward for us, we're trying to do our best!

**Comment by Aurelsicoko** [comment]
@v3yr0n We are working on it! We plan to release a beta version in the early part of April.

**Comment by fivepointseven** [comment]
@Aurelsicoko Thanks for the detailed answer! 
There will be a way to migrate all the associations to Mongoose, right?
Those were like the main reason for choosing Strapi as a framework :D

**Comment by Aurelsicoko** [comment]
@fivepointseven The way to declare your associations will be the same so it will be easy. The most difficult part for you will be the find a way to migrate the data...

**Comment by fivepointseven** [comment]
@Aurelsicoko that one I actually can solve for my particular use case.
I just don't want to mess with all my carefully crafted configs 😄 
Thanks!

**Comment by wahmedswl** [comment]
Hi,
   Its mean that no relational databases support only MongoDB? As, it will limit only to single db rather with waterline, relational databases were also part of the league. Is there any plan to support Waterline also for Relational databases.

Thanks

**Comment by Aurelsicoko** [comment]
It's an old issue, but the interested people, we wrote a [migration guide from v1 to v3](https://strapi.io/documentation/migration/migration-guide.html).
