### ISSUE TITLE
Set, Connect, Disconnect relations with EntityService (TypeScript) not possible

### ISSUE THREAD

**Issue by Adaphath** [strapi/strapi#18106]
### Required System information

- Node.js version: 18.15.0
- NPM version: 9.8.0
- Strapi version: 4.13.6
- Database: MySQL
- Operating system: WSL2 (Windows 11) Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

With the new typescript definitions it is not possible to use connect, disconnect and set for relations with the EntityService.
It always expects an ID.

### Steps to reproduce the behavior
```
await strapi.entityService.update('api::core.subject', subjectResult[0].id, {
          data: {
            studies: {
              connect: [studiesInfo.study.id],
            },
          },
        });
```
Error: `Type '{ connect: (number | `${number}`)[]; }' is not assignable to type 'ID[]'.
  Object literal may only specify known properties, and 'connect' does not exist in type 'ID[]'.`

### Expected behavior

Working objects beside plain IDs

**Comment by woodyjon** [comment]
Yes, that also breaks all my code, where I use objects in nested properties instead of only IDs.

**Comment by Boegie19** [comment]
This is a good first issue for people that are good with typescript

**Comment by woodyjon** [comment]
https://github.com/strapi/strapi/issues/18317

**Comment by Convly** [comment]
As @woodyjon mentioned, this goes on pair with the linked issue (about being able to have `relation: { id: ID }` to set a relation instead of `relation: ID`.

> This is a good first issue for people that are good with typescript

Indeed, this shouldn't be _very very_ hard to fix. It'll just take some time to make sure it's not breaking anything else (the TS test library is till being developed and doesn't cover 100% of the use-cases).

If anyone wants to take a stab at it, I'll be happy to point anyone in the right direction :wave:

**Comment by derrickmehaffy** [comment]
> I would like to work on this issue

We are on a community change freeze, please read the pinned issue
