### ISSUE TITLE
Typescript type autogeneration config is ignored in 4.13.7

### ISSUE THREAD

**Issue by antoine-souesme** [strapi/strapi#18124]
### Required System information

- Node.js version: 18.17.0
- NPM version: 9.6.7
- Strapi version: 4.13.7
- Database: postgres
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After setting the typescript config as below, types are generated and it breaks the typescript compilation (https://github.com/strapi/strapi/issues/18106)

```ts
// config/typescript.ts
export default () => ({
    autogenerate: false,
});
```

### Steps to reproduce the behavior

1. Upgrade to 4.13.7
2. Install and build
3. run `npm run dev`

### Expected behavior

Types are not generated.

**Comment by n2o** [comment]
I am experiencing the same issue, but not in all backends managed by me. Only in one of them. After I figured out why, I'll give more information.

**Comment by svenruegg** [comment]
Also the case in 4.14.0

**Comment by svenruegg** [comment]
> I'd really love to use these models, but I don't know how, the docs don't tell me how to use them properly (or I just can't find it :D).

Anyone had info to that? I would love to used the models of the entityservice instead of disabling all types.

**Comment by Boegie19** [comment]
https://docs.strapi.io/dev-docs/typescript#use-the-strapicompile-function has been updated a bit back. @svenruegg

**Comment by n2o** [comment]
@Boegie19 it might add types to the entity service, but it lacks of the relations and makes it very unusable. 

Small example: Let's assume the User has a relation of `n` other users, which are stored in `likes`. When I want to access this field after the population, TypeScript does not know what to do with it. Says the field is unknown.

<img width="768" alt="image" src="https://github.com/strapi/strapi/assets/1507474/19e8c993-e97f-4016-b8eb-82a7130c7c75">

I experimented today with the latest Strapi version to see if the generated types are somehow usable, but seems to be still stuck or I forgot to include / configure something (could definitely be the case; but I checked the Migration Guides between the versions and applied suggested migrations).

When I manually add the fields to the query of the entity service, it now knows, that there should be field called `likes`, but still does not know what to do with it.

<img width="861" alt="image" src="https://github.com/strapi/strapi/assets/1507474/b17b9187-0bd6-4e76-becd-6d73af32eec3">

So the workaround is to manually extract the populations and cast them to the correct typescript type or disable the generated types in general because of these problems...

Am I doing something wrong? This just appears to be wrong on my side, can't imagine, that the Strapi Devs implement it that way.

**Comment by Convly** [comment]
@n2o would you mind opening a new issue for your use case? 

If there are `likes` in your `up:user `schema, then the entity service should be able to return a fully typed entity based on your populate query.

If that's not the case, it's probably a bug we can fix on our end :slightly_smiling_face:

**Comment by Convly** [comment]
As for the initial issue, the `autogenerate` experimental flag has been removed in a previous version but the documentation has not been updated, sorry for this.

The reason why it has been removed is that we would like to make it part of the common setup of Strapi apps to provide a better DX for both JavaScript and TypeScript users.
However, as it appears we still have some issues around types, we decided to revert its removal.

@innerdvations has opened a PR to add back the option for JS projects only (#19207) (not generating types for TS projects would break other dependencies like the content type builder)
