### ISSUE TITLE
Problem with privileges for accessing "Media Library" files

### ISSUE THREAD

**Issue by hirdegan** [strapi/strapi#18297]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.10.1
- Database: postgres
- Operating system: OS: linux-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I'm having issues accessing files within the "Media Library".

Access privileges to the media library via the "Has the same role as the author" setting do not work

<img width="1781" alt="Screenshot 2023-10-04 alle 16 53 48" src="https://github.com/strapi/strapi/assets/54981388/c5fe1ac6-9cac-4a87-9a17-a9d1afd1849d">

**Comment by amerikan** [comment]
@hirdegan by any chance is it similar to this one?

**Comment by hirdegan** [comment]
> @hirdeganper caso è simile a questo? #17840

No because it refers to the "author" role but in any case the problem is similar but not the same. I tried the advice in the issue anyway but it didn't solve it

**Comment by hirdegan** [comment]
I ran the tests on a clean version of strapi v 

**System information**

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: v4.14.3
- Database: sqlite
- Operating system: darwin-x64
- Is your project Javascript or Typescript: Javascript

**TEST EFFETTUATO:**

Roles added:
ROLE 1 - PLUGINS/UPLOAD added all upload permissions with “Access the Media Library” set to “Has same role as creator”
ROLE 2 - Same characteristics as ROLE 1

<img width="1491" alt="Screenshot 2023-10-05 alle 15 27 24" src="https://github.com/strapi/strapi/assets/54981388/a8e26ef5-b591-48b8-add5-0c2183b4b3c7">


Users created:

ADMIN - Super Admin
USER_1 - ROLE 1
USER_2 - ROLE 1
USER_3 - ROLE 2


Expected behavior

The users: USER 1 and USER 2 in the "Media Library" see the same files and do not see the files uploaded by USER 3

USER 3 does not see the files uploaded by USER 1 and USER 2 because they have a different role

The ADMIN sees all the files uploaded within the "Media Library"


What happens:

When USER 1 or any other of USER 1, USER 2 and USER 3 accesses the "Media Library" it does not load any content

![Screenshot 2023-10-05 alle 15 35 40](https://github.com/strapi/strapi/assets/54981388/eca6ed04-0625-4fc2-a2db-e7cd60dc5311)

<img width="1728" alt="Screenshot 2023-10-05 alle 15 52 02" src="https://github.com/strapi/strapi/assets/54981388/93348941-6a5b-47a3-9bd5-5cc6acb2ef2b">

**Comment by rolangom** [comment]
Hi, I'm new using Strapi, and I'm facing a similar issue `{ status: 400, name: "ValidationError", message: "Invalid parameter roles", … }`

0. Previously, the admin has uploaded some files in the root folder.
1. Then I have created two roles, 'XReader' and 'XWritter' which can access and create(upload, update) in media library respectively with "same role as creator".
2. So, I created 2 users, user 1 which is role 'XWritter' and 'XReader', and user 2 which is just 'XReader'.

Then that error happens here
![Screenshot 2023-10-19 at 19 50 48](https://github.com/strapi/strapi/assets/2136287/a1268727-8342-45ef-bbad-65ed2d60b1d6)
Because for some reason I'm not awared `'roles'` is not in `ADMIN_USER_ALLOWED_FIELDS`

I debugged and realized this solution, which is to add `'roles'` in the `ADMIN_USER_ALLOWED_FIELDS` array at the `strapi/packages/core/admin/server/domain/user.js` file. 
So, I don't know the implication of why it is not included by default.

Please, let me know if I'm wrong with this solution

**Comment by theSdev** [comment]
Running to the same issue. Wondering why this got an "enhancement" label, it is crashing the Media Library so looks like a bug to me.
