### ISSUE TITLE
Dragging and dropping an image into the WYSIWG and hitting save does not save the changes

### ISSUE THREAD

**Issue by dwarcher** [strapi/strapi#1847]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.6.0
- **Strapi version**:3.0.0-alpha.13.1
- **Database**:mongodb
- **Operating system**: Mac OS 10.12.6

**What is the current behavior?**
I am using the WYSIWG on a Text field. I am seeing this if I edit an existing piece of content (not when creating a new piece of content):

When dragging and dropping an image into the WYSIWG, if you make no other edits and click save, the changes are not saved to the DB. If you make any other edits (like adding more text) then clicking save saves the changes.

**Steps to reproduce the problem**
Edit a piece of existing content
Drag and drop any image onto the WYSIWG and click Save without making any other edits.

**What is the expected behavior?**
That the content will be updated with the image that I dragged and dropped.

**Suggested solutions**
I am assuming that there is some kind of variable which indicates that content has been changed that is not getting set when dragging and dropping an image (but that is changed when making normal text edits).

**Comment by lauriejim** [comment]
Hello @dwarcher. Thank you to report this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

You just have to update some text or update to save your upload.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by Tonours** [comment]
Hey 👋 !

This bug is caused by a `setState` with the updated WYSIWYG which is made just before the `sendData` invoke.

And like the state is updated before calling `sendData` method current textarea state is equal to the `editorState` content which is passed in parameter of `sendData` and we are kicked out the method by this if statement https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js#L570

A PR has been created for this ✌️
