### ISSUE TITLE
Not possible to use database connection strings with create-strapi-app

### ISSUE THREAD

**Issue by tpimh** [strapi/strapi#18553]
### Describe the bug

Strapi [supports database connection strings since 4.6.2](https://docs.strapi.io/dev-docs/configurations/database), however it's not possible to use them when creating new projects with `create-strapi-app`.

### Steps to reproduce the behavior

`yarn create strapi-app --db "postgres://postgres:postgres@localhost:5432/postgres?ssl=false" .` wouldn't work, because the parameters `dbclient`, `dbhost`, `dbport`, `dbname`, `dbusername`, `dbpassword`, and `dbssl` must be supplied separately.

### Expected behavior

It would be much nicer if `create-strapi-app` supported database connection strings (e.g. in the format proposed above).

**Comment by tpimh** [comment]
Hi @derrickmehaffy!

I'm not sure whether this should be classified as a feature request or a bug. Database connection string support was added to Strapi 4.6.2, but not to `create-strapi-app`. Since it's a monorepo, I can't submit `create-strapi-app` bugs separately, thus I openned this issue here. I don't think this omision was intentional, just an oversight.

**Comment by derrickmehaffy** [comment]
I do understand your meaning here, while the database config file supports connection strings the CLI does not. It's closer to an enhancement but I know we are going to implement this in v4 so for now probably better to post it on our feature request site so it can be properly tracked.

I certainly would not classify this one as a bug since the logic simply doesn't exist.
