### ISSUE TITLE
create-strapi-app --quickstart fails with unable to resolve dependency tree 

### ISSUE THREAD

**Issue by mirkonasato** [strapi/strapi#18652]
### Required System information

- Node.js version: `v20.9.0`
- NPM version: `10.2.2`
- Strapi version: `4.15.1`
- Database: sqlite
- Operating system: `macOS 14.1`
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Creating a new Strapi project fails due to dependency issues.

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest my-project --quickstart` as per [Quick Start Guide ](https://docs.strapi.io/dev-docs/quick-start)
2. There is no step 2. Step 1 fails with 
```
% npx create-strapi-app@latest my-project --quickstart
Creating a quickstart project.
Creating a new Strapi application at /Users/mirko/Projects/my-project.
Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: styled-components@5.3.3
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"5.3.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.3.6" from @strapi/plugin-cloud@4.15.1
npm ERR! node_modules/@strapi/plugin-cloud
npm ERR!   @strapi/plugin-cloud@"4.15.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected behavior

`npm install` should complete without errors.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by cooperwfloyd** [comment]
getting a similar error right after 4.15.1 dropped, not an issue for me on 4.15.0. can't run an install and build or create a new project anymore without getting this error and I'm not able to force `~14.5.0` anymore for some reason in my package.json. I've added the suggested react and styled components dependencies too. please revert `14.5.1` or correct the dependency issue, all of my strapi projects are unusable currently and this has happened many times where a non-breaking change version introduces breaking changes.
```
Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin (see exports field in ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin/package.json)
```

**Comment by mirkonasato** [comment]
The generated project has `"styled-components": "5.3.3"` in its `dependencies`, but also `"@strapi/plugin-cloud": "4.15.1"` which has `'styled-components': '^5.3.6'` in its `peerDependencies`. 

However, setting `styled-components` to `"5.3.6"` in `package.json` then fails because `@strapi/plugin-users-permissions@4.15.1` expects `styled-components@"5.3.3"`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: styled-components@5.3.6
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"5.3.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"5.3.3" from @strapi/plugin-users-permissions@4.15.1
npm ERR! node_modules/@strapi/plugin-users-permissions
npm ERR!   @strapi/plugin-users-permissions@"4.15.1" from the root project
npm ERR! 
```

So `plugin-cloud` and `plugin-users-permissions` are incompatible with one another, even though they're both `4.15.1`.

A workaround is to remove the `"@strapi/plugin-cloud"` dependency altogether.

**Comment by 7999999166** [comment]
in version 4.15.1 ,  during pg and cloudinary installations , its coming up with errors , i am unable to run commands like 
npm install pg --save
npm install @strapi/provider-upload-cloudinary --save
kindly resolve it .

**Comment by mirkonasato** [comment]
It's not really easy to test, because a `0.0.0-*` version is not compatible with `^4.4.0`.

```
% npx create-strapi-app@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336 my-project --quickstart
Creating a quickstart project.
Creating a new Strapi application at /Users/mirko/Projects/my-project.
Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: @strapi/strapi@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.4.0" from @strapi/plugin-cloud@0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336
npm ERR! node_modules/@strapi/plugin-cloud
npm ERR!   @strapi/plugin-cloud@"0.0.0-experimental.1cec6226fe6c8ca4b8404f1ebac8076d5ee5b336" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by joshuaellis** [comment]
yeah you're right. although those peer dep issues are expected – I don't use `npm`, I assume it would report all issues in one go?

**Comment by mirkonasato** [comment]
Testing is always better than making assumptions.  You could publish a `4.15.2-experimental-*`, maybe to a private npm registry like Verdaccio if you don't want it public, and test it that way.  Ideally automate that as part of the release process.

**Comment by mirkonasato** [comment]
Actually, a `4.15.2-experimental-*` wouldn't help either, because anything with a hyphen is considered a [pre-release](https://semver.org/#spec-item-9) and doesn't satisfy the requirement anyway.
```
> semver.satisfies('4.15.2', '^4.4.0')
true
> semver.satisfies('4.15.2-experimental', '^4.4.0')
false
```
I published the `releases/4.15.2` branch as `4.15.2` to my local registry
```
./node_modules/.bin/lerna publish --no-push --registry http://localhost:4873 --force-publish  --dist-tag latest 4.15.2
```
and can confirm that generating a new project with `create-strapi-app --quickstart --use-npm` now works fine. 👍

**Comment by fifolio** [comment]
I got the same error too, for 4.15.2, and 4.15.1. 👨‍💻
I recommend using: npx create-strapi-app@4.15.0, this will install Strapi normally ✅🌟

![image](https://github.com/strapi/strapi/assets/97522852/659f5cc8-4f56-4730-a54f-4ce0caf41b26)

**Comment by mirkonasato** [comment]
The problem with `4.15.2` is that `@strapi/plugin-users-permissions@4.15.2` requires `@strapi/strapi@"4.0.0"` as peer, i.e. exactly `4.0.0` and not at least `^4.0.0` like [other plugins](https://github.com/strapi/strapi/blob/v4.15.2/packages/plugins/i18n/package.json#L77).

```
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: strapi-app@0.1.0
npm ERR! Found: @strapi/strapi@4.15.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"4.15.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@4.15.2
npm ERR! node_modules/@strapi/plugin-users-permissions
npm ERR!   @strapi/plugin-users-permissions@"4.15.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by derrickmehaffy** [comment]
Should be fixed in v4.15.4 will mark as closed for now

**Comment by bengodev** [comment]
Same issue for `create-strapi-app@4.16.2`

**Comment by workwithraymond** [comment]
Ran into the same issue when running npx create-strapi-app@latest my-project
The workaround that worked for me was npm install.

**Comment by pavlovic-bojan** [comment]
I'm getting similar errors

Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm ERR! code 1
npm ERR! path /Users/user/Desktop/Angular/eCommerce/api/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/user/Desktop/Angular/eCommerce/api/node_modules/esbuild/install.js:133
npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Expected "0.19.11" but got "0.16.17"
npm ERR!     at validateBinaryVersion (/Users/user/Desktop/Angular/eCommerce/api/node_modules/esbuild/install.js:133:11)
npm ERR!     at /Users/user/Desktop/Angular/eCommerce/api/node_modules/esbuild/install.js:286:5
npm ERR! 
npm ERR! Node.js v18.18.0

npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2024-03-03T12_01_50_853Z-debug-0.log
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /Users/user/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/Users/user/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/Users/user/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by adirahul** [comment]
Getting similar errors!
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Expected "0.19.2" but got "0.20.2"
npm ERR!     at validateBinaryVersion 
npm ERR!
npm ERR! Node.js v20.10.0

npm ERR! A complete log of this run can be found in: C:\Users\adity\AppData\Local\npm-cache\_logs\2024-03-30T16_44_06_606Z-debug-0.log
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
   cache\_npx\780177217ba243d1\node_modules\@strapi\generate-new\dist\create-quickstart-project.js:18:3)
