### ISSUE TITLE
Argument of type '"api::COLLECTION.COLLECTION"' is not assignable to parameter of type 'ContentType'

### ISSUE THREAD

**Issue by anthonytison** [strapi/strapi#18664]
### Required System information

- Node.js version: 18.15
- NPM version: 9.5
- Strapi version: 14.15.1
- Database: postgres
- Operating system: mac os
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The following errors appear when saving a new collection on a fresh installation.

```typescript
src/api/challenge/controllers/challenge.ts:7:47 - error TS2345: Argument of type '"api::challenge.challenge"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreController('api::challenge.challenge');
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/api/challenge/routes/challenge.ts:7:43 - error TS2345: Argument of type '"api::challenge.challenge"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreRouter('api::challenge.challenge');
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/api/challenge/services/challenge.ts:7:44 - error TS2345: Argument of type '"api::challenge.challenge"' is not assignable to parameter of type 'ContentType'.

7 export default factories.createCoreService('api::challenge.challenge');
```

### Steps to reproduce the behavior

1. Create a new app on the last version
2. Create a new collection
3. Create a new field
4. Save & the errors appear

**Comment by lacrx** [comment]
I'm building with --ts and I'm getting the exact same error when I try to add to the schema from the admin ui.

**Comment by tpimh** [comment]
I just had exactly the same problem when using TypeScript project. After adding a new content type, the server tried to restart, but never went up again 😢

**Comment by entelostre** [comment]
I am also facing the same problem. 
Running Strapi v4.15.2

**Comment by joshleitzel** [comment]
For some reason it seems the types aren't being generated into the `ContentTypes` interface. I was able to work around this problem by manually running [`yarn strapi ts:generate-types`](https://docs.strapi.io/dev-docs/cli#strapi-tsgenerate-types).

**Comment by alefemafra** [comment]
> For some reason it seems the types aren't being generated into the `ContentTypes` interface. I was able to work around this problem by manually running [`yarn strapi ts:generate-types`](https://docs.strapi.io/dev-docs/cli#strapi-tsgenerate-types).

This worked for me, but every new collection I have to run because the server crashes. :confused:

**Comment by PaulCorbeau** [comment]
> For some reason it seems the types aren't being generated into the `ContentTypes` interface. I was able to work around this problem by manually running [`yarn strapi ts:generate-types`](https://docs.strapi.io/dev-docs/cli#strapi-tsgenerate-types).

Same issue for me, this trick fixed it

**Comment by fmann** [comment]
I ran into the same issue today on Strapi version: 14.15.2. As others have said, `yarn strapi ts:generate-types` worked to get past the error.

**Comment by tpimh** [comment]
Curiously, regenerating types didn't work for me, because of a plugin that I am using. I filed an issue here: https://github.com/bwyx/strapi-jwt-cookies/issues/5

4.14.6 doesn't have this problem and type regeneration is successful.

**Comment by QozbroQqn** [comment]
still present in 4.15.4

**Comment by zynth666** [comment]
I just had the same issue, please consider taking a look into this.
For anyone developing in a devcontainer, I have just added this to my docker-compose file: 

`command: /bin/sh -c "yarn strapi ts:generate-types && yarn develop"`

Hope this helps someone :)

**Comment by derrickmehaffy** [comment]
duplicate https://github.com/strapi/strapi/issues/18738

Should be fixed by: https://github.com/strapi/strapi/pull/18775

**Comment by joebnb** [comment]
it's wired when i delete some components or collections type ,it's still generated in tsfile

**Comment by guerillacodester** [comment]
problem persists into 4.15.5 when I place content types in the extension folder. none of the fixes seem to work.

**Comment by bauerbua** [comment]
I had this issue still on v4.25.7. It occured when creating a single type. My workaroung was to create a minimal content type by myself, and added other fields via the admin-panel after strapi started again. The type was not created in `contentTypes.d.ts`, but running [strapi ts:generate-types](https://docs.strapi.io/dev-docs/cli#strapi-tsgenerate-types) did also not solve it for me since it errored with `Failed to generate types for contentTypes: Debug Failure. Unhandled SyntaxKind: Unknown.. Exiting`

So manually creating the according type did solve it.

**Comment by faileon** [comment]
running into the same issue with `4.25.6`, running strapi via docker compose.

**Comment by yukimasaki** [comment]
The same for `4.25.10`.

**Comment by fmlukaszmatusik** [comment]
Same for 4.25.11

**Comment by nick-ma** [comment]
Same for 5.3.0 
I deleted the type folder and the problem was solved.

**Comment by trofimenk0** [comment]
The same for me
Strapi - 5.4.2
During the installation I selected “use TypeScript”

**Comment by bloomsdev** [comment]
Just to add to this, creating a new content-type with a single “standard” field such as a Text Field works ok. However, creating a new content-type with multiple and custom plugin fields will cause this error. 

Temp solution is to first create the Custom Type with a single standard field, then add the other components afterwards.

**Comment by GamesProSeif** [comment]
Adding more information...
I've started to experience this issue (not being able to create new collections) after I've installed the SEO plugin.
Running `yarn strapi ts:generate-types` errors because the SEO plugin has Opengraph fields named "og:description" and many other fields which include a colon ":" in the name.
While generating types it results in this typescript code:
```ts
attributes: {
  og:description: Schema.Attribute.String & Schema.Attribute.Required & Schema.Attribute.SetMinMaxLength<{
    maxLength: 200;
  }>;
  ...
}
```
where `og:description: Schema...` is a syntax error because of the double colons ":" written.

---

#### Solution for my case
I've uninstalled the SEO plugin using these steps:
- running `yarn remove @strapi/plugin-seo`
- removing the plugin configuration from `config/plugins.ts`
- removing files `seo.json` and `open-graph.json` from `src/components/shared/`
- removing `seo` component from each collection/single schema manually in `src/api/[COLLECTION]/content-types/[COLLECTION]/schema.json`

Removing the plugin solved my problem and I could create collections back again.

---

I know this is a plugin issue, but I wanted to include this here in case anyone else faces the same issue.
Also this could be fixed easily on the plugin's end if they renamed all their open graph fields to be javascript/typescript compliant by replacing the colon with an underscore for example.

**Comment by petrovicdorde** [comment]
Same issue.
Version 5.12.3.

Created Collection type and Strapi app crashes.
Error message: Argument of type '"api::menu-item.menu-item"' is not assignable to parameter of type 'ContentType'.

I tried yarn strapi ts:generate-types and it didn't work for me:
[ERROR] [2025-04-07T19:49:37.481Z] (Typegen) Failed to generate types for components: Debug Failure. Unhandled SyntaxKind: Unknown.. Exiting

**Comment by TiborUdvari** [comment]
> Same issue. Version 5.12.3.
> 
> Created Collection type and Strapi app crashes. Error message: Argument of type '"api::menu-item.menu-item"' is not assignable to parameter of type 'ContentType'.
> 
> I tried yarn strapi ts:generate-types and it didn't work for me: [ERROR] [2025-04-07T19:49:37.481Z] (Typegen) Failed to generate types for components: Debug Failure. Unhandled SyntaxKind: Unknown.. Exiting

I have the same issue in `5.12.5` and `5.12.6`

**Comment by duyzuy** [comment]
> > Same issue. Version 5.12.3.
> > Created Collection type and Strapi app crashes. Error message: Argument of type '"api::menu-item.menu-item"' is not assignable to parameter of type 'ContentType'.
> > I tried yarn strapi ts:generate-types and it didn't work for me: [ERROR] [2025-04-07T19:49:37.481Z] (Typegen) Failed to generate types for components: Debug Failure. Unhandled SyntaxKind: Unknown.. Exiting
> 
> I have the same issue in `5.12.5` and `5.12.6`
> 
> Update: I added `"types/generated/**" // <- this line` like mentioned before and it seems to be working now.

it's work in my case, thanks you @TiborUdvari
