### ISSUE TITLE
ts:generate-types fails when running prettier 3.0 plugins

### ISSUE THREAD

**Issue by minht11** [strapi/strapi#18796]
### Required System information

- Node.js version: 20.6.1
- NPM version: 
- Strapi version: 4.15.4
- Database: Sqlit
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have monorepo and at the top shared prettier config like this:
```ts
module.exports = {
	plugins: [
		'prettier-plugin-astro',
		'@ianvs/prettier-plugin-sort-imports',
		'prettier-plugin-tailwindcss',
	],
}
```
prettier version is ^3.0. When running strapi command `strapi ts:generate-types` this error occurs.
```
[ERROR] [2023-11-14T21:10:23.442Z] (Typegen) Failed to generate types for contentTypes: require() of ES Module /-frontend/node_modules/.pnpm/prettier-plugin-astro@0.12.2/node_modules/prettier-plugin-astro/dist/index.js from /-frontend/node_modules/.pnpm/prettier@2.8.4/node_modules/prettier/index.js not supported.
Instead change the require of /-frontend/node_modules/.pnpm/prettier-plugin-astro@0.12.2/node_modules/prettier-plugin-astro/dist/index.js in /-frontend/node_modules/.pnpm/prettier@2.8.4/node_modules/prettier/index.js to a dynamic import() which is available in all CommonJS modules.. Exiting
```

That is because Strapi pins version of prettier internally instead using one provided by the user, however it still uses plugins provided by the user, which leads to the error like this. Prettier 3 intruduced pseudo breaking with how it loads plugins and modules.

### Steps to reproduce the behavior

1. Use Prettier 3.0 with some plugins which only support ES modules.
2. Run strapi ts:generate-types
3. Wach it fail

### Expected behavior

Use Prettier 3.0 plugins does not crash strapi ts:generate-types command.
Possible solutions:
1. Update Strapi itself to use prettier 3.0
2. Use prettier version provided by the user, if provided.
3. Provide config option to disable prettier formatting when running ts:generate-types

**Comment by illright** [comment]
This issue can be temporarily worked around if you're using pnpm (which is thankfully an option since the latest version of Strapi). Add the following to your package.json (the root one, if using monorepos):
```json
{
  "pnpm": {
    "overrides": {
      "prettier": "3.0.3"
    }
  }
}
```

Run `pnpm i` afterwards. However, doing this will break your build as other packages, not `@strapi/generate-types`, depend on the Prettier 2 API. So remove it after you've successfully generated your types.

---

This is a terrible workaround, of course, so a proper fix to this issue is highly appreciated. Ideally, the Prettier functionality should be opt-outable, since it's certainly not core to the functionality of the type generator.

**Comment by derrickmehaffy** [comment]
We don't support ESM modules and this isn't a direct bug within Strapi itself, for now I'll mark this as closed as we lack both the bandwidth and the time to work on this for now and I would recommend posting this to our feature request/feedback site: https://feedback.strapi.io
