### ISSUE TITLE
DMehaffy's Clean Upgrade Steps

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1880]
*DMehaffy's "Nuke and Rebuild Steps"*
Only use if no major changes have been done to the normal strapi generated files, and you have only modified the *.settings.json files.

Notes:
If you are using MySQL or Postgres you need to do `strapi generate:api -t bookshelf modelname blahblah:string`

Steps:

1. Ensure you have the latest Strapi installed `npm i -g strapi@alpha`
2. Create a new strapi project using the latest release
3. Create a temporary directory somewhere to copy your old model configs `mkdir ~/Desktop/tempdir`
4. Copy those configs to the temp directory `cp path/to/your/old/project/api/*/models/*.settings.json ~/Desktop/tempdir && ls -al ~/Desktop/tempdir`
5. Change over to your new project and use `strapi generate:api modelname blah:string` to create new models for each of your old ones (I have this scripted to do it automatically myself)
6. Then copy over each model.settings.json file from your tempdir to the new project (Also scripted, bit more difficult)
7. Now you should be able to start and have all your models from the old project now on the new one, for any other files/changes I personally recommend using the program Meld if you are on Linux to compare the two and copy files over or merge changes over.

**Comment by derrickmehaffy** [comment]
Closing as I only created this to reference.

**Comment by stiko** [comment]
I have created a script that does the upgrade (for mongo only rn) [you can see it here](https://gitlab.com/stiko_/strapi-upgrade)

**Comment by derrickmehaffy** [comment]
@stiko Cool I'll take a look, if we wanted to offer up a script it should be as backend agnostic as possible

**Comment by derrickmehaffy** [comment]
@stiko As I'm not super great with python. I think it would be nice if you read the database.json file so you can pull the needed data required to create the new strapi project and also you can use that to select which "database" to use in the generation of the new project

If `database.json` has mongoose use: `strapi generate:api -t mongoose` 
else if `database.json` uses bookshelf use: `strapi generate:api -t bookshelf`

**Comment by stiko** [comment]
@derrickmehaffy It's following the guide Strapi provided.
1. Create a new project (in a temp folder)
2. Move necessary files to the new project
3. Check what plugins are installed to reinstall later
4. Move (new project's) admin folder to the current project
5. Move (new project's) plugin folder
6. install any missing plugins

For step 1 it will show the regular `strapi new project_name` where the user can follow the steps and it doesn't matter what DB config will generate as we are interested only in `admin` and `plugins` folders.

I was gonna read `database.json` to finish the steps needed for the DB, but thought will do Mongo first since that's what I'm using, and I'm not sure if regenerating `api` is unnecessary since after testing without that it upgraded just fine.

**Comment by derrickmehaffy** [comment]
@stiko the reason for the `generate:api` bit for universal upgrades. If there are any changes to the config, controllers, or services of the model templates it would be best to quickly update them. By just copying over the model.settings.json files you can do just that.

Obviously for more complex project there is still going to be some manual user modifications but my guide was written to take out most of the "manual" labor needed to quickly upgrade without complex migration guides.

**Comment by derrickmehaffy** [comment]
In the future the specific `-t bookshelf` won't be needed as I'm planning on working a way to merge both the mongoose and bookshelf templates into a single one and let strapi use whatever bits in the templates it needs at run time.

**Comment by eComEvo** [comment]
@derrickmehaffy what is the point of `blah:string` in `strapi generate:api modelname blah:string`? When I tried what you suggested, I was able to migrate using only `strapi generate:api modelname` but I wanted to be sure I didn't miss something critical here.

**Comment by pauldariye** [comment]
Great guide @derrickmehaff ! Any chance you're open to sharing the script?

**Comment by derrickmehaffy** [comment]
@pauldariye I use that script in the comment above yours to generate the models, after that I've just been using meld to copy over files that are needed.

**Comment by derrickmehaffy** [comment]
@eComEvo Yes as noted in the OP, you just need to use `-t bookshelf` when you generate the models. As models (currently) depend on the hook being used (mongoose/bookshelf)

Mongoose: Mongo
Bookshelf: MySQL/Postgres/SQlite (sqlite coming soon)

**Comment by bobaekang** [comment]
Thanks for sharing your upgrading strategy, @derrickmehaffy . Please allow me to ask a few questions to better understand what your method is doing:

* What stops you from simply copying the the entire `/api` directory from the old project rather than using `strapi generate:api` and then copy over the `[model].settings.json` files?
* Are `[model].settings.json` files the only items that I need to copy over to the new app in order to retain the content type settings, including media ?
* Is copying over `/plugins/users-permissions/models/User.settings.json` and `/plugins/users-permissions/config/jwt.json` all that is needed to retain the user permission settings?
* How about uploaded files--is there anything I need to copy over from `/plugins/upload/`?

Thank you in advance for your answers😃

**Comment by derrickmehaffy** [comment]
@bobaekang 

1) If there are any changes made to the files in `config`, `controllers`, or `services` you will have to manually update all those files for each model by hand (It does happen between releases) In my case I have about 80 models, so updating all those files by hand? Heck no :stuck_out_tongue: 

2) Yes for the most part, media relations are a special case but don't require anything to be copied over for that plugin specifically.

3) Yes more or less, if you have any custom config options you may need to carry those over (such as I have a few for the graphQL plugin)

4) Nothing really should be needed for upload unless you messed with the models in that plugin directory.

You best bet is to use a GUI diff tool like meld to figure out what changed and review the changes before you merge them over.

**Comment by derrickmehaffy** [comment]
An example of a change to one of those btw, small in this case (going from v19 to v22) but there have been times where the changes will be much larger. I know a few pending PRs that will be making big changes:

![image](https://user-images.githubusercontent.com/8593673/52273808-33614280-2908-11e9-8739-82758563e541.png)
