### ISSUE TITLE
4.15.4: /provider-upload-aws-s3 generates wrong URLs when uploading media files

### ISSUE THREAD

**Issue by remijnlars** [strapi/strapi#18836]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.15.4
- Database: PostgreSQL
- Operating system: Mac OS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I migrated Strapi from 4.10.4 > 4.15.4
Facing some issues with the File uploads via strapi/provider-upload-aws-s3 now.
When I upload files now the URL is totally different and incorrect

**In 4.15.4 Example:**
https://{bucket_name}.s3.eu-west-3.amazonaws.com/{slug}

**In 4.10.4 Example:**
https://s3.eu-west-3.amazonaws.com/{bucket_name}/{slug}

Now I went back to 4.10.4 and the uploads are working fine....
### Steps to reproduce the behavior

1. Upgrade all @strapi dependencies to: 4.15.4
2. npm install
3. npm run build
4. npm run develop
5. Upload a media file, and look at the URL

### Expected behavior

Same URL structure as before when i upload a file.

### Code snippets

**plugin.js**
```
upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          Bucket: env("AWS_BUCKET"),
          baseUrl: env("AWS_BUCKET_BASE_URL"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
```

**Comment by Boegie19** [comment]
@remijnlars Just to confirm the uploading of images still works?

Also both ways of requesting are allowed by the amazon api.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAPI.html#rest-api-dual-stack
This change has most likely something to do with the that we upgraded from the AWS SDK V2 to V3 in version 4.15.1

**Comment by remijnlars** [comment]
Yes I can upload them in the UI, also see them in mij S3 in AWS.
The problem is that the constructed URL format in 4.15.4 is not working. 
V 4.15.4 (not working):  https://static.aanbiedingcheck.nl.s3.eu-west-3.amazonaws.com/jura_e8_aanbieding_376306db14.jpeg
V 4.10.4 (working): https://s3.eu-west-3.amazonaws.com/static.aanbiedingcheck.nl/jura_e8_aanbieding_376306db14.jpeg

I looked at the documentation, weird that it is not working on my end..

**Comment by Boegie19** [comment]
@remijnlars I am 99% sure this issue is created because your bucket_name has .'s in it

**Comment by remijnlars** [comment]
Will check. But is there a way to get the old situation? 
If it stays like this I need to make some workarounds because I have this S3 as static site to have the files on my own sub domain.

**Comment by derrickmehaffy** [comment]
> Yes I can upload them in the UI, also see them in my S3 in AWS. The problem is that the constructed URL format in 4.15.4 is not working. V 4.15.4 (not working): https://static.aanbiedingcheck.nl.s3.eu-west-3.amazonaws.com/jura_e8_aanbieding_376306db14.jpeg V 4.10.4 (working): https://s3.eu-west-3.amazonaws.com/static.aanbiedingcheck.nl/jura_e8_aanbieding_376306db14.jpeg
> 
> I looked at the documentation, weird that it is not working on my end..

Safest option at the moment is to downgrade to v4.14.6 until the engineering team can take a look at this.

**Comment by christiancp100** [comment]
@remijnlars Sorry for the late reply but we wanted to make sure to test everything right before providing an answer to your issue. What we did in the AWS provider was updating the aws dependency, going from AWS V2 to AWS V3. And this update of version changed the format of the URLs, as you said and it's specified in [this document](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access). TLDR: AWS recommends the new URL format (called virtual-hosted–style URI with the format ), since the Path-style URI is going to be deprecated at some point. [This is another post](https://aws.amazon.com/es/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) that justifies better their decision in case you want to think about migrating your URL format. But if you just want to make it work with 4.15.x versions without migrating anything, you can set a `baseUrl` property in the plugin with your desired URL format, as shown in the example below:
```
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        baseUrl: 'https://s3.{region}.amazonaws.com/{bucket}, // THIS LINE IS THE IMPORTANT ONE
        params: {
          ACL: env('AWS_ACL', 'public-read'),
          signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 15 * 60),
          Bucket: env('AWS_BUCKET'),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
```
