### ISSUE TITLE
Bump koa router to 12.x.x

### ISSUE THREAD

**Issue by naive17** [strapi/strapi#18950]
## Would be possible to update koa router version?

this is a reference to the koa issue that was discovered in the version we are using Right now

https://github.com/koajs/router/pull/173

**Comment by derrickmehaffy** [comment]
We are currently on v10 ATM which when we reviewed isn't subject to that bug so we probably won't upgrade in the v4 lifecycle but will evaluate this for v5 when we do all the other upgrades.

This one is in our radar.

I'll go ahead and close this report since it's not really a bug but we will handle this in v5.

Thanks!
