### ISSUE TITLE
Fail to create new content when its value of 'Name' field contains white-spaces

### ISSUE THREAD

**Issue by fpetrouchka** [strapi/strapi#1897]
**Informations**
- **Node.js version**: 10.9.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongoDB v3.4.16
- **Operating system**: CentOS Linux release 7.5.1804 (on AWS Lightsail) 

**What is the current behavior?**
Once I created content type w/ 'Name' field contains any white-spaces at Content Type Builder, then it freeze completely at loading status when I try to add new content. 

**What is the expected behavior?**
Preferred: Warn 'Name contains invalid character' or something before create the content type at Builder, and fail to create record.

**Suggested solutions**
Insert no spaces when input a name of content type.

**Comment by lauriejim** [comment]
Hello @fpetrouchka what is the name you use.

I tried to create a new content type from the **Content Type Builder** and I set `test article` as name.
And it create my content type successfully.
(Testarticle, cause you can't use white space in content type name)

You create an issue because it automatically lowercase your content type name ?

**Comment by fpetrouchka** [comment]
Thanks for reply @lauriejim , just edited bio.

> I tried to create a new content type from the Content Type Builder and I set test article as name.
> And it create my content type successfully.
> (Testarticle, cause you can't use white space in content type name)

I know, it seems successfully created Content Type at the Content Type Builder w/ automatically lower-cased, but it stops at loading status when I try to create some records from left menu.
(or...Is this issue caused by any other factor?)

**Comment by Tonours** [comment]
Hey @fpetrouchka and @lauriejim 👋 

The error of model name with whitespaces occure when you are submitting your form by hitting `enter` instead of clicking on `save` button.

It's happening because the model name is camelCased only when the `handleBlur` function of the Input (cf: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-type-builder/admin/src/containers/Form/index.js#L379) 

Here is a screenshot of example model name object which is produced when user hit `enter` instead of clicking on `save`

<img width="507" alt="capture d ecran 2018-09-18" src="https://user-images.githubusercontent.com/1331358/45664298-15ba4a80-bad9-11e8-973e-e6d68f41a34a.png">

I've create a PR for this: https://github.com/strapi/strapi/pull/1970

**Comment by lauriejim** [comment]
@Tonours Thank you for your investigation! That's awesome, I ping @soupette to review the PR you made to fix it.

**Comment by fpetrouchka** [comment]
@Tonours @lauriejim Thank you for specify & fix that issue ;)
