### ISSUE TITLE
Overly Permissive Origin Policy In @Koa/Cors

### ISSUE THREAD

**Issue by ankitdn** [strapi/strapi#19048]
### Description
I am currently developing the backend using Strapi and performed a vulnerability scan using Vulert on the manifest file. The scan revealed a vulnerability in the version of @Koa/Cors utilized by Strapi. To address this issue, I propose upgrading the @Koa/Cors version to 5.0.0.

### Details
- **Vulert Scan Report:** [Vulert Report](https://vulert.com/vuln-scan/list/cfffb4a1-08c3-4ca7-9e2a-3abeba16a965)
- **CVE Reference:** [CVE-2023-49803](https://vulert.com/vuln-db/CVE-2023-49803)

### Proposed Solution
Upgrade the @Koa/Cors version to 5.0.0 to mitigate the vulnerability.

**Comment by derrickmehaffy** [comment]
Closing as this violates our security policy.

**Comment by t-fritsch** [comment]
I don't know if this has been closed because of the tool used by OP that is not allowed (please forgive me if I misunderstood), but I've got vulnerabilities reporting after `npm install` in 4.15.5 too. 

`npm audit` gives :
<pre><code>npm audit
# npm audit report

@koa/cors  <5.0.0
Severity: high
Overly permissive origin policy - https://github.com/advisories/GHSA-qxrj-hx23-xp82</code></pre>

<details><summary>
rest of audit :
</summary>
<p>
<pre><code>fix available via `npm audit fix --force`
Will install @strapi/plugin-users-permissions@4.15.0, which is a breaking change
node_modules/@koa/cors
  @strapi/strapi  *
  Depends on vulnerable versions of @koa/cors
  Depends on vulnerable versions of @strapi/admin
  Depends on vulnerable versions of @strapi/data-transfer
  Depends on vulnerable versions of @strapi/pack-up
  Depends on vulnerable versions of @strapi/plugin-content-type-builder
  Depends on vulnerable versions of @strapi/plugin-upload
  Depends on vulnerable versions of @strapi/types
  node_modules/@strapi/strapi
    @strapi/admin  <=0.0.0-next.ff946d2c25a3e577b47132a357cac2932eb8e635 || >=4.3.5
    Depends on vulnerable versions of @strapi/data-transfer
    Depends on vulnerable versions of @strapi/strapi
    Depends on vulnerable versions of @strapi/types
    node_modules/@strapi/admin
    @strapi/data-transfer  *
    Depends on vulnerable versions of @strapi/strapi
    Depends on vulnerable versions of @strapi/types
    node_modules/@strapi/data-transfer
    @strapi/plugin-content-type-builder  <=0.0.0-next.f5b09a8e61e059f02784478e27c310c6290be088 || 4.7.2-exp.175f7ac70ee76d6c825e4429e15fc85ee78d23bb - 4.10.1 || >=4.15.2
    Depends on vulnerable versions of @strapi/strapi
    node_modules/@strapi/plugin-content-type-builder
    @strapi/plugin-i18n  <=0.0.0-next.f5b09a8e61e059f02784478e27c310c6290be088 || >=4.15.2
    Depends on vulnerable versions of @strapi/strapi
    node_modules/@strapi/plugin-i18n
    @strapi/plugin-upload  <=0.0.0-next.f5b09a8e61e059f02784478e27c310c6290be088 || >=4.15.2
    Depends on vulnerable versions of @strapi/strapi
    node_modules/@strapi/plugin-upload
    @strapi/plugin-users-permissions  <=0.0.0-next.f5b09a8e61e059f02784478e27c310c6290be088 || >=4.15.2
    Depends on vulnerable versions of @strapi/strapi
    node_modules/@strapi/plugin-users-permissions
    strapi-plugin-import-export-entries  *
    Depends on vulnerable versions of @strapi/strapi
    node_modules/strapi-plugin-import-export-entries
    strapi-plugin-soft-delete  *
    Depends on vulnerable versions of @strapi/strapi
    node_modules/strapi-plugin-soft-delete
  @strapi/types  <=0.0.0-next.fb3a0b82484ce466b1efb1b28f16fc8ef73aba4a || >=4.14.0
  Depends on vulnerable versions of @koa/cors
  node_modules/@strapi/types

vite  4.4.0 - 4.4.11
Severity: moderate
Vite XSS vulnerability in `server.transformIndexHtml` via URL payload - https://github.com/advisories/GHSA-92r3-m2mg-pj97
fix available via `npm audit fix --force`
Will install @strapi/plugin-users-permissions@4.15.0, which is a breaking change
node_modules/vite
  @strapi/pack-up  *
  Depends on vulnerable versions of vite
  node_modules/@strapi/pack-up

13 vulnerabilities (2 moderate, 11 high)</code></pre>
</p>
</details>

**Comment by derrickmehaffy** [comment]
Please see our security file at the root of the project but we don't consider this a valid vulnerability

**Comment by marketsystems** [comment]
why not fix it and stop all the npm alarm bells when we try and do anything?

**Comment by marketsystems** [comment]
> Please see our security file at the root of the project but we don't consider this a valid vulnerability

maybe not a valid "vulnerability" in relevance to strapi, but is a valid vulnerability.. and npm will warn every single time until the version number is bumped which should be done as a matter of course when there is a new advisory

**Comment by derrickmehaffy** [comment]
We don't just bump packages without considering stability, breaking changes, and potentially introducing more issues just to fix an advisory alert.

If users themselves want to bump it and take the risk you are welcome to do so using and override but we advise against it.

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

We evaluate security advisories ourselves and have a detailed security policy to ensure we remain not only secure but also stable, especially more recently as we focus on stability more and more.

We've already reported this advisory to MITRE as we believe the advisory is inherently wrong and should not exist.

**Comment by marketsystems** [comment]
If you compare the code of 4.3.4 and 5.0.0 there is basically a couple of lines of actual changes, with the default origin. The rest of the diff is updating node versions in package.json and readme changes and additional test code.. so no real ability to "break" strapi. Have used override to 5.0.0 and everything is running normally
