### ISSUE TITLE
Please modify your project schema by renaming the key "inversedBy" to "mappedBy"

### ISSUE THREAD

**Issue by nbro10** [strapi/strapi#19109]
## Bug report

There are several issues/questions here, but they are all related.

### Required System information

- Node.js version: 20.9
- NPM version: 10.1.0
- Strapi version: 4.15.5
- Database: PostgreSQL
- Operating system: MacOS Sonoma
- Is your project Javascript or Typescript: JS

### Describe the bug

I'm getting this warning when executing `npm run develop` (after `npm run build`).

> Loading Strapi(node:69611) Warning: Error on attribute "Name" in model "project" (api::project.project). Please modify your project schema by renaming the key "inversedBy" to "mappedBy". Ex: { "inversedBy": "project" } -> { "mappedBy": "project" }

although the app launches and I can access the Strapi admin interface.

For context, I've 2 collection types, `project` and `worker`, and I've just made a 1-to-1 relationship between these 2. Before, I had `worker` has 1 project, but the project may not be associated with any `worker`. So, after this change, I started to get this error or warning. I don't really know why or what it means.

First of all, what's the difference between `inversedBy` and `mappedBy`?

Second, why am I getting this error? This looks like a bug because I've done the change in the interface.

Why is the app allowed to launch even if there's this error/warning? We should not allow the app to launch in this case, as some relationship is not properly set. In fact, now when I click in the menus to see the data, an error message pops up, and actually no data is actually loaded.

Finally, when I changed the relationship from `has` to `1-to-1`, I had to specify an attribute of `Project`, but there was no list, which means that you had to manually write it down after having looked up the properties of `Project` and how they have been spelled. Maybe this is the reason why I get this error, i.e. I didn't specify the `Project`'s attribute correctly.

### Expected behavior

No warning and everything works as expected

**Comment by Boegie19** [comment]
@nbro10 You have mappedBy on both side of the relationship what strapi is allowing by patching it manualy in V5 this patch will be removed and your strapi instance will stop working if you don't change one of the mappedBy to in inversedBy

**Comment by AlexTechNoir** [comment]
I just got this error, renamed the key as it suggested and the error is gone.

I searched a bit and according to [docs](https://docs.strapi.io/cms/backend-customization/models#relations), in bi-directional relations, these keys are used by both content-types. `inversedBy` is used by owning side and `mappedBy` is used by inversed side. In my case I related users-permissions with custom content-type and the latter is supposed to have `mappedBy` key, meaning users-permissions is an owning side, they can't both be `inversedBy`.

The error might appeared because I created a custom content-type with "has one" relation to users-permissions and then changed it to "has and belongs to one", but it's just my guess
