### ISSUE TITLE
Error using version 15.8.0 of graphql with the @strapi/plugin-graphql extension

### ISSUE THREAD

**Issue by ChristianSantanaLlanes** [strapi/strapi#19101]
I am using the @strapi/plugin-graphql extension in my Strapi 4.16.0 project. When using the version 15.8.0 of graphql installed directly in the root of the project, I get the following error:

Error: Cannot use GraphQLScalarType "Time" from another module or realm.
When uninstalling the @strapi/plugin-graphql extension, the problem is solved.

Request:

Could you please verify if version 15.8.0 of graphql is compatible with the @strapi/plugin-graphql extension? If it is not compatible, could you provide a compatible version?

Additional information:

My development environment is Node.js 20.9.0 and npm 8.13.0.
I have updated the resolution graphql": "16.8.1" in my package.json file, but the problem persists.
My Strapi version is 4.16.0.
Thank you for your attention.

Sincerely,

Christian Santana

**Comment by Zignature** [comment]
Yes, I have the exact same problem...

**Comment by Zignature** [comment]
Fortunately I'm only running a dev server and a production server. I managed to revert to Strapi 4.15.5.

First I uninstalled all of Strapi 4.16.0 items that were in my package.json:
`npm uninstall @strapi/plugin-cloud @strapi/plugin-color-picker @strapi/plugin-i18n @strapi/plugin-users-permissions @strapi/provider-email-nodemailer @strapi/strapi`

After that I reinstalled them all with version 4.15.5:
`npm install @strapi/plugin-cloud@4.15.5 @strapi/plugin-color-picker@4.15.5 @strapi/plugin-i18n@4.15.5 @strapi/plugin-users-permissions@4.15.5 @strapi/provider-email-nodemailer@4.15.5 @strapi/strapi@4.15.5`

and than ran `npm run develop`

It worked for me 😄

**Comment by geniy9** [comment]
Mr. @Zignature thank you, great solution also for me!

**Comment by BorisKamp** [comment]
Since strapi > 4.15 I'm having a lot of issues with my package.json file. This is one of them, another one is the incompatibility around the react & styles packages that are new. 9required for v5.....

I can't be the only one right?

**Comment by xgalen** [comment]
I am having the same issues @BorisKamp :'(

**Comment by BorisKamp** [comment]
I fixed it by running `npm list graphql`. If you get the above mentioned error, the versions are not the same over all list items. For me, one was using v15 something, I then force all the graphql packages to use the same version by adding this to my `package.json`:
```
  "overrides": {
    "graphql": "16.8.1"
  },
```

And run `npm i` again. This should fix it....
After this I was able to run strapi `4.16.2` without problems and could even install the `v5` packages without problems....

I hope you will have the same @xgalen

**Comment by wilonweb** [comment]
@BorisKamp 
Hello 
I try to put it on my `backend\package.json`
```
npm i
npm ERR! code EOVERRIDE
npm ERR! Override for graphql@^16.8.1 conflicts with direct dependency

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wilfr\AppData\Local\npm-cache\_logs\2024-01-08T16_24_33_945Z-debug-0.log
``` 

But when i launch `npm i` the terminal send me that 
```
 npm i 
npm ERR! code EOVERRIDE
npm ERR! Override for graphql@^16.8.1 conflicts with direct dependency

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wilfr\AppData\Local\npm-cache\_logs\2024-01-08T16_26_14_852Z-debug-0.log
```

**Comment by BorisKamp** [comment]
> @BorisKamp Hello I try to put it on my `backend\package.json`
> 
> ```
> "overrides": {
>     "graphql": "16.8.1"
>   },
> ```
> 
> But when i launch `npm i` the terminal send me that
> 
> ```
>  npm i 
> npm ERR! code EOVERRIDE
> npm ERR! Override for graphql@^16.8.1 conflicts with direct dependency
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\wilfr\AppData\Local\npm-cache\_logs\2024-01-08T16_26_14_852Z-debug-0.log
> ```

What output does ‘npm list graphql’ give without the override and a fresh ‘npm i’?

and what does your ‘package.json’ look like?

**Comment by derrickmehaffy** [comment]
We will hopefully have the PR merged to fix this soon but it will roll back the graphql-upload package which is causing the problem.

**Comment by chris-barklem** [comment]
I had the same issue:

 Error: Cannot use GraphQLScalarType "Time" from another module or realm. 
│                                                                                                                                    
│   Ensure that there is only one instance of "graphql" in the node_modules  
│   directory. If different versions of "graphql" are the dependencies of other 
│   relied on modules, use "resolutions" to ensure only one version is installed. 
│                                                                                                                         
│   https://yarnpkg.com/en/docs/selective-version-resolutions 
│                                                                                                        
│   Duplicate "graphql" modules cannot be used at the same time since different
│   versions may have different capabilities and behavior. The data from one
│   version used in the function from another could produce confusing and 
│   spurious results.     

npm list graphql

└─┬ @strapi/plugin-graphql@4.16.2
  ├─┬ @graphql-tools/schema@8.5.1
  │ ├─┬ @graphql-tools/merge@8.3.1
  │ │ ├─┬ @graphql-tools/utils@8.9.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ @graphql-tools/utils@8.9.0
  │ │ └── graphql@16.8.1 deduped
  │ └── graphql@16.8.1
  ├─┬ @graphql-tools/utils@8.13.1
  │ └── graphql@16.8.1 deduped
  ├─┬ apollo-server-core@3.12.1
  │ ├─┬ @apollo/utils.usagereporting@1.0.1
  │ │ ├─┬ @apollo/utils.dropunuseddefinitions@1.1.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.printwithreducedwhitespace@1.1.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.removealiases@1.0.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.sortast@1.1.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.stripsensitiveliterals@1.2.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ @apollographql/apollo-tools@0.5.4
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ @graphql-tools/mock@8.7.20
  │ │ ├─┬ @graphql-tools/schema@9.0.19
  │ │ │ ├─┬ @graphql-tools/merge@8.4.2
  │ │ │ │ └── graphql@16.8.1 deduped
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @graphql-tools/utils@9.2.1
  │ │ │ ├─┬ @graphql-typed-document-node/core@3.2.0
  │ │ │ │ └── graphql@16.8.1 deduped
  │ │ │ └── graphql@16.8.1 deduped
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ apollo-server-errors@3.3.1
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ apollo-server-plugin-base@3.7.2
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ apollo-server-types@3.8.0
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ graphql-tag@2.12.6
  │ │ └── graphql@16.8.1 deduped
  │ └── graphql@16.8.1 deduped
  ├─┬ apollo-server-koa@3.10.0
  │ └── graphql@16.8.1 deduped
  ├─┬ graphql-depth-limit@1.1.0
  │ └── graphql@16.8.1 deduped
  ├─┬ graphql-scalars@1.22.2
  │ └── graphql@16.8.1 deduped
  ├─┬ graphql-upload@15.0.2
  │ └── graphql@16.8.1 deduped
  ├── **graphql@15.8.0**
  └─┬ nexus@1.3.0
    └── graphql@16.8.1 deduped

I then added:
  "overrides": {
    "graphql": "16.8.1"
  },
  
  ran npm i
  
  Then npm list graphql which balanced to graphql@16.8.1
  
  └─┬ @strapi/plugin-graphql@4.16.2
  ├─┬ @graphql-tools/schema@8.5.1
  │ ├─┬ @graphql-tools/merge@8.3.1
  │ │ ├─┬ @graphql-tools/utils@8.9.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ @graphql-tools/utils@8.9.0
  │ │ └── graphql@16.8.1 deduped
  │ └── graphql@16.8.1 deduped
  ├─┬ @graphql-tools/utils@8.13.1
  │ └── graphql@16.8.1 deduped
  ├─┬ apollo-server-core@3.12.1
  │ ├─┬ @apollo/utils.usagereporting@1.0.1
  │ │ ├─┬ @apollo/utils.dropunuseddefinitions@1.1.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.printwithreducedwhitespace@1.1.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.removealiases@1.0.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.sortast@1.1.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @apollo/utils.stripsensitiveliterals@1.2.0
  │ │ │ └── graphql@16.8.1 deduped
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ @apollographql/apollo-tools@0.5.4
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ @graphql-tools/mock@8.7.20
  │ │ ├─┬ @graphql-tools/schema@9.0.19
  │ │ │ ├─┬ @graphql-tools/merge@8.4.2
  │ │ │ │ └── graphql@16.8.1 deduped
  │ │ │ └── graphql@16.8.1 deduped
  │ │ ├─┬ @graphql-tools/utils@9.2.1
  │ │ │ ├─┬ @graphql-typed-document-node/core@3.2.0
  │ │ │ │ └── graphql@16.8.1 deduped
  │ │ │ └── graphql@16.8.1 deduped
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ apollo-server-errors@3.3.1
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ apollo-server-plugin-base@3.7.2
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ apollo-server-types@3.8.0
  │ │ └── graphql@16.8.1 deduped
  │ ├─┬ graphql-tag@2.12.6
  │ │ └── graphql@16.8.1 deduped
  │ └── graphql@16.8.1 deduped
  ├─┬ apollo-server-koa@3.10.0
  │ └── graphql@16.8.1 deduped
  ├─┬ graphql-depth-limit@1.1.0
  │ └── graphql@16.8.1 deduped
  ├─┬ graphql-scalars@1.22.2
  │ └── graphql@16.8.1 deduped
  ├─┬ graphql-upload@15.0.2
  │ └── graphql@16.8.1 deduped
  ├── graphql@16.8.1 overridden
  └─┬ nexus@1.3.0
    └── graphql@16.8.1 deduped
    
    Everything is now working as expected.
