### ISSUE TITLE
Telemetry in admin App.tsx ignore the window.strapi.telemetryDisabled

### ISSUE THREAD

**Issue by AdamSGit** [strapi/strapi#19239]
### Required System information

- Node.js version: 20
- NPM version: 9.7
- Strapi version: 4.17
- Database: Sqlite
- Operating system: Macos
- Is your project Javascript or Typescript: Js

### Describe the bug

In [`packages/core/admin/admin/src/App.tsx`](https://github.com/strapi/strapi/blob/29b5e272e5817f2c985d64587a3e1884164c89f9/packages/core/admin/admin/src/App.tsx#L108C2-L130), There is a telemetry request that send the event `didInitializeAdministration`. This request doesn't respect the telemetry preferences. It got blocked by my adblocker, giving me this nice error on every admin page screenshoted below :

### Steps to reproduce the behavior

1. Go to any admin page with telemetry disabled, open network inspector, see the request.

### Expected behavior

This request respect the telemetry preferences.

### Screenshots

<img width="1044" alt="Screenshot 2024-01-17 at 11 14 08" src="https://github.com/strapi/strapi/assets/6126439/bd27ff14-e84b-4bd8-be54-7411b5b86c43">

**Comment by popovicsandras** [comment]
I've got the exact same issue after upgrading Strapi from `4.16.2` to `4.17.1`, on the environment detailed below, following [this](https://docs.strapi.io/dev-docs/update-version) guide.

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.17.1
- Database: Sqlite
- Operating system: Macos
- Is your project Javascript or Typescript: TS
- Browser: Brave browser

I've tried deleting node_modules and the yarn.lock file, reinstalling all the deps from scratch as well.

One addition to the problem for me the issue only happens when running develop in watch mode.

Hence, this works:
```bash
yarn develop
```

But this doesn't:
```bash
yarn develop --watch-admin
```

**Comment by Eventyret** [comment]
Test Version - v4.20.2
- Blank App
- Telemetery enabled (default)
![image](https://github.com/strapi/strapi/assets/977232/7c1dc932-5692-4131-b15f-01d3a84439f7)
- Telemetry disabled
- 
![image](https://github.com/strapi/strapi/assets/977232/ca6c3c3b-7ad1-436c-a55a-0251efbf6fd6)

Unable to reproduce this on latest version
