### ISSUE TITLE
Thumbnail for a video

### ISSUE THREAD

**Issue by nikhilatkan** [strapi/strapi#19293]
How can I get a thumbnail after uploading a video as we get after uploading an image.

Can someone please help.

**Comment by pragmago** [comment]
@nikhilatkan I could not find any hint that this feature is currently supported inside Strapi. Unless I missed that feature, the best option would be to add a media field to your model. Then you can use one of the lifecycle hooks such as beforeCreate to generate a thumbnail with the ffmpeg bindings and upload the thumbnail model instance you created. 

There were some issues with directly adding the generated thumbnail to the model in the lifecycle hook due to the DB layer implementation of Strapi iirc. So ultimately I opted to add the thumbnail to the instance created via a REST API call. I can see if I find the code I used tomorrow. 

Alternatively you will find some inspiration here: https://github.com/darron1217/strapi-plugin-video-thumbnail

The plugin is outdated but it is easy enough to copy the relevant code to adapt to v4.
