### ISSUE TITLE
Media not removed from AWS when using plugin::upload.file delete

### ISSUE THREAD

**Issue by BorisKamp** [strapi/strapi#19474]
Hi!

Using Strapi `4.20`, Im deleting media attached to a collection type before deleting the collection type itself.

Im using the `beforeDelete` lifecycle hook and in there I have the following piece of code:
```
await strapi.db.query('plugin::upload.file').delete({ where: { id: fileId } })
      .then((res) => {
        console.log('Deleted the collo label!')
      })
```

This removes the file perfectly in Strapi, but the image/media remains in the AWS bucket, this seems like a bug to me?

**Comment by brantje** [comment]
This seems like core functionality to me? So now we get ever growing S3 buckets without the option to delete it? 
It's not even fixed in Strapi v5, this makes me reconcider upgrading / moving to strapi cloud. 
A simple delete method can be implemented in an hour, can you link me the upstream so i can send a PR and get this implemented?

**Comment by CodeToTee** [comment]
I agree this is major missing functionality/. If the S3 objects aren't deleted, they'll simply grow forever, spending unnecessary $$$.
