### ISSUE TITLE
The `Create new entry` button is not shown in the Content Manager unless we reload the page

### ISSUE THREAD

**Issue by nbro10** [strapi/strapi#19542]
### Required System information

- Node.js version: 20.9.0 
- NPM version: 10.1.0
- Strapi version: 4.16.2
- Database: postgres
- Operating system: darwin-arm64 or ubuntu (linux-x64)
- Is your project Javascript or Typescript: JS
- Browser: Chrome (120.0.6099.129 (Official Build) (arm64))

### Describe the bug

The `Create new entry` button is not show in the Content Manager unless we reload the page. This happens almost every time.

### Steps to reproduce the behavior

1. Go to content manager
2. Click on any collection type
3. There's no `Create new entry` button on the top right (unless you reload the page)

### Expected behavior

I always see the `Create new entry` button

### Screenshots

See below

![strapi_bug2](https://github.com/strapi/strapi/assets/106664639/a88ff365-0f79-4984-a9ed-1ee2078e2744)

After I reload I see the button

![strapi_bug2_2](https://github.com/strapi/strapi/assets/106664639/f25668e2-64f7-41ee-b6c1-a7feee729df5)

Clearly, this is highly undesirable. I should not be telling my users to reload to do the most basic operation that a CMS should be able to do.

Note: I cannot update to a newer version because of this bug https://github.com/strapi/strapi/issues/19532. Strapi 4.16.2 is the last version that contains this feature that I strictly need.

**Comment by Eventyret** [comment]
Could you please try upgrade to the latest version and see if this gives the same behvour @nbro10 latest version is 4.20.1

**Comment by joshuaellis** [comment]
Whoops. Sorry I didn't realise it closed it automatically!!

**Comment by joshuaellis** [comment]
The app is an SPA, I think the route you always land on originally is /admin and the client side router mounts after running all the custom bootstrap code etc.

Then the code you have isn't reactive, so it only runs on the one time and the style tag is never removed as a cleanup when the URL changes, since it's an SPA, the HTML outside of the react app won't change really either.

I'm not sure if there's a good way to solve this annoyingly unless you were able to do a really super specific selector of CSS, but because we use styled components you wouldn't be able to use classNames.

Ergo, while I do get its annoying for you, I'm not sure it's a bug 🤔

**Comment by joshuaellis** [comment]
We have this open on Canny – https://strapi.canny.io/feature-requests/p/customize-the-admin-dashboard-welcome-page-v4 which asks for the same things. I can only advise you to up vote and leave your use case on there for visibility 😄

**Comment by derrickmehaffy** [comment]
@nbro10 please avoid tagging people in comments, we are monitoring the comments and it's fine not to tag us as we will see them.
