### ISSUE TITLE
Admin "shouldUpdateStrapi" notification is always present

### ISSUE THREAD

**Issue by matthew-a-thomas** [strapi/strapi#19554]
### Required System information

- OS: win32-x64
- Strapi Version: 4.20.1
- Node/Yarn Version: yarn/1.22.21 npm/? node/v20.11.0 win32 x64
- Edition: Community
- Database: sqlite
- Typescript

### Describe the bug

This notification is always here even though I have the latest released version:
<img width="614" alt="image" src="https://github.com/strapi/strapi/assets/14829821/911a5424-770e-481a-861f-1d6e4f4e8556">

I _think_ that's the upgrade notification? (Sorry I'm new to Strapi)

Perhaps it's because the GitHub tag name starts with the letter "v"?
<img width="569" alt="image" src="https://github.com/strapi/strapi/assets/14829821/0fb95270-f1cc-4744-a162-ffafab02219c">

Which I think would mess up the semver comparison [in the `AuthenticatedApp` component](https://github.com/strapi/strapi/blob/develop/packages/core/admin/admin/src/components/AuthenticatedApp.tsx#L134)?

### Steps to reproduce the behavior

Get Strapi 4.20.1.

`yarn run develop`

### Expected behavior

Notification count should not be "1". Also should not have the notification dot shown above.

**Comment by ztxone** [comment]
Agree ) a bit of anoying since v4.15.x somewhere

**Comment by RBosmansPXL** [comment]
In addition to the update notification we experience that also 'Skip the tour' keeps showing up.
This since we update update from v4.15.x to v4.19.x and now in every minor v4.20.x release.

- OS: win32-x64 (local development) // Ubuntu 22.04.3 LTS (plek VPS)
- Strapi Version: 4.20.x
- Node Version: npm/10.2 & 10.3 node/v20.11.x win32 x64
- Edition: Community
- Database: mySQL
- In development and production

  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.1.1",
    "@strapi/strapi": "^4.20.3",
    "@strapi/plugin-users-permissions": "^4.20.3",
    "@strapi/plugin-i18n": "^4.20.3",
    "@strapi/plugin-graphql": "^4.20.3",
    "@strapi/plugin-seo": "^1.9.8",		
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^5.3.4",
    "styled-components": "^5.3.3",
"mysql2": "^3.9.2"
  },

**Comment by derrickmehaffy** [comment]
Duplicate https://github.com/strapi/strapi/issues/19199
