### ISSUE TITLE
Upgrading from alpha 13.1 to 14 make the fields unviewable

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1978]
**Informations**
- **Node.js version**:  v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: mongodb
- **Operating system**: macOS

**What is the current behavior?**
I visit a specific Content Type in admin panel and click on one row, the page shows 'There are no fields yet' where should has fields.

**Steps to reproduce the problem**
1. I have an existing project with v13.1
2. Upgrade strapi version following migration guide (including delete `plugin_content-manager_schema`).
3. Visit 
`http://localhost:1337/admin/plugins/content-manager/<my_model>/<one_specific_row_like_5b9c4f3eexxxxx>?redirectUrl=/plugins/content-manager/<my_model>?_limit=10&_page=1&_sort=_id&source=content-manager`
4. Showing like the pic.
![wx20180918-101932](https://user-images.githubusercontent.com/3782817/45704661-6313d780-bb2c-11e8-991e-95af6c6ac648.png)

Independent fields are missing, but relations are not affected.

Extra step 5. Click on 'Go to settings page', showing a blank screen and console error, which is related to #1862 

**What is the expected behavior?**
I expect the content manager could view all the existing fields.

**Suggested solutions**
I guess, after deleting `plugin_content-manager_schema`, there is no default settings for Content Types.

**Comment by derrickmehaffy** [comment]
@yummyelin After you delete that table, have you restarted the server. The plugin should fill that back in.

**Comment by jmchza** [comment]
I have the same problem and I have found by cleaning the whole DB with no data in them that the admin console does display them properly and you can even create records from it and it works fine.
I still have to find out what is the root cause for that behaviour but I think it is that the data is not properly validated with its definition (at least in my case).

That is an assumption I took by looking at the code and i can see that everything uses propTypes therefore if the data does not match with the definition on the props  it might become inaccessible. 

It would be nice to have a better reporting in that one that could alert what fields are wrong so we could analyse DB and its data. Maybe there is some way to see this warnings somewhere?? Does anyone know this?

I reported it in this issue: https://github.com/strapi/strapi/issues/1983

**Comment by yummyelin** [comment]
@derrickmehaffy yes, I restarted

**Comment by yummyelin** [comment]
@jmchza For dev environment, cleaning the whole DB is fine. But for prod environment, I can't do that.

This gives me a headache..

**Comment by soupette** [comment]
@yummyelin well the problem is the `plugin_content_manager_schema` which has the wrong data model for the v14 can you delete it and then recreate it?

**Comment by yummyelin** [comment]
@soupette it fixed. Thank you!

For everyone who have the same issue, make sure server is stopped and `plugin_content_manager_schema` is deleted, and then restart server.
