### ISSUE TITLE
Running Strapi in production and version control sync

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#1986]
**Informations**
- **Strapi version**: 14alpha

This is more of a question about best practices for running Strapi in a live environment (yes I know it's alpha, but this will presumably apply to the final release as well).

I noticed that Strapi generates new files when a content type is added. This means that the production environment's files will become out of sync with version control. Is there a recommended deployment process? Am I supposed to commit changes from production to my git repo after making changes in the admin? Is there a recommended way of deploying changes (i.e. should I not be creating new content types in production)?

**Comment by emadicio** [comment]
If you run your app with NODE_ENV=production you'll notice that plugins that actually edit or create files are disabled. So that means you cannot create or edit content types in prod

**Comment by greatwitenorth** [comment]
OK that's good to know. I am still seeing files being changed and generated in production though. Here's what a git status on the server yields:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   admin/package-lock.json
	modified:   package-lock.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	config/locales/de_de.json
	config/locales/en_us.json
	config/locales/es_es.json
	config/locales/fr_fr.json
	config/locales/it_it.json
	config/locales/ja_jp.json
	config/locales/ru_ru.json
	config/locales/tr_tr.json
```

Should I file this as a bug then? Or is this intended behaviour?

**Comment by Downloaddave** [comment]
Hey there! Thanks! This is good to know.

I had deployed Strapi locally then to a Prod environment, and was confused since I didn't see the content-type-builder in the production CMS.

I'm trying to understand the deployment and update process as well...

This is where it seems like it's leading to me:

- Developer sets Strapi up locally
- Creates content-types using the content-type-builder
- Strapi makes updates to the file structure locally and on the local MongoDB
- On production we will have to push both the code and db updates?

I understand that making changes to the content-type-builder reboots the service, and we don't want production to go down during the rebuild, but it seems like data would get really out of sync between production and development.

I'm not sure if that's the correct workflow, if I'm completely misunderstanding, or if that was what was envisioned.

**Comment by Downloaddave** [comment]
Would it make more sense for all plugins to be enabled, but only admin or super admin has the ability to make updates to the content-types (that require a restart) and a warnings that updating them will restart the Service?

**Comment by Aurelsicoko** [comment]
You're right! The Content-Type Builder is a development plugin. His goal is to speed up the development of your project. It should not be used in production. We didn't design this plugin like for this usage.

The real pain is to migrate the development configuration to production, and vice-versa. We plan to offer a new command with the CLI called `strapi migrate` to easily migrate from an environment to another. I can't give you a release date though...

**Comment by cschweda** [comment]
+1 on the ```strapi migrate```.

I'm not entirely clear what the version control process is. One thing I did -- since I use a non-local mongoDB instance is to add 'database.json' in all environments to my ```.gitignore``` file -- and then create these locally once I've cloned the repo.

And do I set up separate databases for each environment? A 'prod' database with the actual data -- and a 'dev' database with test data?

**Comment by Aurelsicoko** [comment]
@cschweda Strapi supports multi-environment configurations, so you can use this feature to easily switch between database. However, the configurations stored in the development DB won't be transfered to the production DB. This is why we need the `strapi migrate` CLI.

If your current workaround works, it's okay. It makes sense to me even if this is definitely not the optimal way to do it...

**Comment by lauriejim** [comment]
Related to this card: https://portal.productboard.com/strapi/c/12-migrate-across-environments

**Comment by maxime1992** [comment]
So how to do it now, until the CLI gets available?

I've been developing locally using strapi and I'm now trying to push to production but I feel completely stuck :man_shrugging: 

> The real pain is to migrate the development configuration to production

Even if it's painful, is there a description of how to do it for now?

**Comment by Aurelsicoko** [comment]
Yes, there are resources available:
- https://strapi.io/documentation/3.x.x/guides/deployment.html
- https://blog.strapi.io/how-to-deploy-a-strapi-application/
- https://blog.strapi.io/deploying-a-strapi-api-on-heroku/

**Comment by ccll** [comment]
@Aurelsicoko I couldn't find any useful answer from those materials (about migrating schemas/content-types between dev/staging/production environments). Am I missing something?

**Comment by Aurelsicoko** [comment]
@ccll If you are using Git, you can easily track the changes in the content-types files. However, it becomes complicated if you have customised the layout of the content type because it means that you have to export your database and import it to the production database. We know that the data might not be synchronised between both environments, so you have to only dump the core_store (where the settings are stored) table and only migrate this table.

**Comment by ccll** [comment]
@Aurelsicoko Thanks, I'll check the core_store table.

Normally in my other apps I migrate DB with tools like `db-migrate`, where DB schema migration actions are scripted in text format and version controlled with Git (then transferred and replayed between multiple dev/staging/production environments), but my first attempt to use db-migrate with Strapi failed due to incompatible format of `database.json` file. Would you please give some suggestions on this respect?

**Comment by rjain15** [comment]
I have similar questions, I am doing local dev (mongodb, docker) and I am deploying in production in kubernetes. What do I need to move from dev to production? What is the migration path? My content writer is writing in production, when I migrate what gets overwritten and what is not?

**Comment by mastix** [comment]
Same thing here. I'm currently evaluating Strapi for my requirments (against other headless CMS) and currently I have problems figuring out how the correct development - production lifecycle looks like. Actually I'm planning to run strapi from within a Docker container, so integrating everything (Docker, git (push hooks), updates,...) is kind of unclear to me.

**Comment by KevinKelbie** [comment]
Here is a workflow I was thinking about using.

- Setup a production server and a development server on a subdomain
- Make changes to Strapi on the development server
- Developer commits changes from the development server to version controll
- Developer pulls changes onto production server

Downside is that you won't be able to see instant changes on the production server and would have to wait for a developer to apply the changes.

**Comment by vishwa-** [comment]
As many of you posted above, I am evaluating strapi and few more tools. One of the important features is migration of content from staging to production. Is `strapi migrate` available?

**Comment by lauriejim** [comment]
Hello this feature is not planned for the beginning of 2020.
Here is the item in the roadmap - https://portal.productboard.com/strapi/1-public-roadmap/c/12-migrate-across-environments

**Comment by sant3001** [comment]
According to the documentation you can use [strapi configuration:dump](https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-configuration-dump-config-dump) and [strapi configuration:restore](https://strapi.io/documentation/v3.x/cli/CLI.html#strapi-configuration-restore-config-restore) accordingly. You would need to commit the `dump.json` file generated and import it in your production site.

**Comment by ciddennis** [comment]
Is there any update on this?    Without strapi migrate or something like that I am finding it hard to figure out how you would keep the work a developer is doing in sync with production.     Content type changes alter the file system and the database, not only does it add/alter tables to store the content but permission tables get updated and the core_store table gets updated.       I can not see how I would know what to keep track of and update on a production deployment.

**Comment by websmith** [comment]
I'm also curious about this. We are considering Strapi for our main website and are running into the issue of development cycles vs ability for our marketing team to make content changes - all without overriding one another. For example, if we have a new content-type being developed in dev while content changes are being made in production, wouldn't releasing our dev changes override the new content changes without a way to specifically only update the relevant tables without touching existing content tables? This might not be related to the migration disucssion and could already be sovled for. If so, could someone please direct me to relevant documentation? 🙏

**Comment by boazpoolman** [comment]
So regarding the `migrate` CLI; I've create a plugin that does exactly that.
It's the [config-sync](https://github.com/boazpoolman/strapi-plugin-config-sync) plugin for Strapi v4.

You can use it to import/export data from the CLI or GUI and migrate them across environments.

The plugin handles data migration, but there is one other step in a successfull development lifecycle; schema migrations.
Strapi handles schema migrations automatically. In v4 there is a way to disable the automatic schema migration so you can manually migrate table structures. Though this is not considered stable and not documented yet.

Follow the progress here: https://forum.strapi.io/t/database-migration-deployment-questions/434/32
