### ISSUE TITLE
Strapi v5 plugin boilerplate generated with errors 

### ISSUE THREAD

**Issue by cyp3rius** [strapi/strapi#19942]
### Required System information

- Node.js version: v20.12.0
- NPM version: 10.5.0
- Strapi version: 5.0.0-beta.0
- Database: SQLite
- Operating system: MacOS 14.2.1 (23C71)
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

The commands `strapi generate plugin` or `strapi plugin:init` does not generate working boilerplate of the plugin.  As error from screenshot occurs. 

### Steps to reproduce the behavior

1. Initialise Strapi in TypeScript
2. Generate the plugin `strapi generate plugin` or `strapi plugin:init` in TypeScript
3. Build the plugin using `build`
4. Build strapi
5. See that error occur

### Expected behavior

Plugin is mounted by default in the sidebar menu without any errors.

### Screenshots

![Screenshot 2024-03-27 at 17 29 21](https://github.com/strapi/strapi/assets/11504214/e16f2620-96b5-4239-8f82-91b83cf65c37)

### Code snippets

The fix is simple in `strapi-admin.js` to change  from generated
```js
module.exports = require('./admin/src').default;
```

to

```js
import admin from './admin/src'

export default admin
```

### Additional context

As well when selecting TypeScript for plugin still there are JS files generated for `strapi-admin.js` and `strapi-server.js`. What might be solved by providing equivalents in TS like:

```typescript
// strapi-admin.ts
"use strict";

import admin from "./admin/src";

export default admin;
```

```typescript
// strapi-server.ts

"use strict";

import server from "./dist/server";

export default server;
```

```json
// tsconfig.mounting.json

{
  "extends": "@strapi/typescript-utils/tsconfigs/server",

  "compilerOptions": {
    "outDir": ".",
    "rootDir": ".",
    "jsx": "react-jsx",
  },

  "include": [
    "strapi-admin.ts",
    "strapi-server.ts"
  ],

  "exclude": [
    "node_modules/",
    "dist/",
    "server/",
    "admin",
    "**/*.test.ts"
  ]
}
```

```json
// package.json

  "scripts": {
    "develop": "tsc -p tsconfig.server.json -w",
    "build": "yarn build:server && yarn build:mounting",
    "build:server": "tsc -p tsconfig.server.json",
    "build:mounting": "tsc -p tsconfig.mounting.json"
  }, 
```

or just allow `.strapi/client/app.js` to import relevant TS files.

**Comment by alexandrebodin** [comment]
Hi will close this in favor of this tracking issue https://github.com/strapi/strapi/issues/20088 :)

**Comment by kevinvugts** [comment]
I think this needs to be re-opened @alexandrebodin 

Currently the commands such as `yarn strapi plugin:init` or `yarn strapi plugin:build` both fail with a deprecration warning in the latest beta release version 14. So basically, the generators don't work at all at the moment. Also, it seems (probably intentional), that the plugin generation command is removed from the "yarn strapi generate" cli command.

Any thoughts on this and a possible fix for the plugin creational commands?

**Comment by kevinvugts** [comment]
> Hi will close this in favor of this tracking issue [strapi/sdk-plugin#1](https://github.com/strapi/sdk-plugin/issues/1) :)

I think the link you a referring too, needs quite some work to be usable. It's full of bugs at the moment. 
A few examples:

- Generating incorrect boilerplate code with issues such as "redeclared block scoped variables"
- Not satisfying to the users CLI config options (for example still generating .ts files even though the JS option is selected by the user)
- v5 project completely broken when a plugin is created and enabled in plugin/config (erroring out with issues to referred fils which do not exist in the /dist folder it suppose
- using commonjs by default iin the package.json "type" property. Even though "module" would be preferred or should be configurable by the user
- Import information such as notifying the user to run "yarn install" in the /[my-plugin] folder in order to make the CLI "work"? 

And that's just the basics I found out. Might worth the try to have a chat about this in your next daily standup!

**Comment by alexandrebodin** [comment]
Hello, please open any issues you encounter on https://github.com/strapi/sdk-plugin so they can be triaged and fixed
