### ISSUE TITLE
Graphql plugin breaking CMS app on v5.0.0-beta-3

### ISSUE THREAD

**Issue by Willibaur** [strapi/strapi#20097]
### Required System information

- Node.js version: 20.11.0
- NPM version: 10.12.24
- Strapi version: 5.0.0-beta-3
- Database: Postgres
- Operating system: darwin-arm64 - iOS Sonoma 14.4.1 (23E224)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

`@strapi/plugin-graphql` break the whole cms app when installed.

### Steps to reproduce the behaviour

1. Install brand new Strapi project with `npx create-strapi-app@beta cms`
2. Select custom the following options

```sh
npx create-strapi-app@beta cms

? Choose your installation type Custom (manual settings)
? Choose your preferred language TypeScript
? Choose your default database client postgres
? Database name: cms
? Host: 127.0.0.1
? Port: 5432
? Username: postgres
? Password: ********
? Enable SSL connection: No
```
4. Spin up the server
5. Open admin panel without problem
6. Install `yarn add @strapi/plugin-graphql`
7. Spin up the server again
8. Try open admin panel and the app crash inmediately

### Expected behaviour

The app should work fine after installing `@strapi/plugin-graphql`

### Screenshots

![CleanShot 2024-04-11 at 6  31 39](https://github.com/strapi/strapi/assets/12820932/fe941526-ab0c-4ee5-b036-d7dbf0d51dfa)

### Code snippets

```
@repo/cms:dev: [2024-04-11 18:08:23.182] info: Strapi started successfully
@repo/cms:dev: [2024-04-11 18:08:30.461] error: Cannot read properties of undefined (reading 'isEnabled')
@repo/cms:dev: TypeError: Cannot read properties of undefined (reading 'isEnabled')
@repo/cms:dev:     at /Users/astro/cms/node_modules/@strapi/core/dist/middlewares/security.js:39:60
@repo/cms:dev:     at dispatch (/Users/astro/cms/node_modules/koa-compose/index.js:42:32)
@repo/cms:dev:     at /Users/astro/cms/node_modules/@strapi/core/dist/middlewares/errors.js:8:13
@repo/cms:dev:     at dispatch (/Users/astro/cms/node_modules/koa-compose/index.js:42:32)
@repo/cms:dev:     at /Users/astro/cms/node_modules/@strapi/core/dist/middlewares/logger.js:6:11
@repo/cms:dev:     at dispatch (/Users/astro/cms/node_modules/koa-compose/index.js:42:32)
@repo/cms:dev:     at session (/Users/astro/cms/node_modules/koa-session/index.js:41:13)
@repo/cms:dev:     at dispatch (/Users/astro/cms/node_modules/koa-compose/index.js:42:32)
@repo/cms:dev:     at middleware (/Users/astro/cms/node_modules/@strapi/core/dist/services/metrics/middleware.js:20:11)
@repo/cms:dev:     at dispatch (/Users/astro/cms/node_modules/koa-compose/index.js:42:32)
```

### Additional context

We tested this issue within a monorepo using (turborepo) and also in a standalone project, both throw the same error.

**Comment by derrickmehaffy** [comment]
Can you please share your package.json as I believe the command you ran would use the v4 latest package, not the beta package.

To properly install the plugin during the beta you would use: `yarn add @strapi/plugin-graphql@beta` or specify the exact version in place of `beta`

**Comment by eugle** [comment]
I have the same issue. I upgraded from 5.0.0 beta. 2 to 5.0.0 beta. 3. 5.0.0 beta. 2 runs normally, but after the upgrade, an error occurred

```
"dependencies": {
    "@strapi/plugin-cloud": "5.0.0-beta.3",
    "@strapi/plugin-graphql": "5.0.0-beta.3",
    "@strapi/plugin-i18n": "5.0.0-beta.3",
    "@strapi/plugin-users-permissions": "5.0.0-beta.3",
    "@strapi/strapi": "5.0.0-beta.3",
    "mup-disk": "^0.2.0",
    "node-fetch": "^3.3.2",
    "pg": "8.8.0",
    "pg-connection-string": "^2.6.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "strapi-provider-upload-oss": "^0.2.0",
    "styled-components": "5.3.3"
  },
```

为什么要升级，因为有两个问题
1，login and me这两个接口返回的字段中没有document_id，而其它表如果关联用户是依赖document_id，在v5中改进了，v4是id，但用户表没有返回document_id，为什么？我很奇怪
2，返回超过10条数据原来有一个meta字段，其中有total，能知道总条数，v5中改进了，使用了pageinfo，遵循和graphql一样的返回格式，改进非常棒，但是，但是，但是，接口没有返回pageinfo这个字段，开发文档中明确列出来了，但接口没有返回，因为graphql接口是内置的，我们只需要在sandbox中，可以一目了解看到，哪些返回字段有，哪些没有，而pageinfo就是没有

基于以上目前两个发现的问题，我选择升级了5.0.0-beta.3，是不是5.0.0-beta.2确实还需要改进，还是我的理解有问题呢，有知道的前辈告诉我一下，感谢，非常期待v5的正式版，我知道需要时间，感谢团队的努力。
为什么要升级，因为有两个问题

1，login and me这两个接口返回的字段中没有document_id，而其它表如果关联用户是依赖document_id，在v5中改进了，v4是id，但用户表没有返回document_id，为什么？我很奇怪

2，返回超过10条数据原来有一个meta字段，其中有total，能知道总条数，v5中改进了，使用了pageinfo，遵循和graphql一样的返回格式，改进非常棒，但是，但是，但是，接口没有返回pageinfo这个字段，开发文档中明确列出来了，但接口没有返回，因为graphql接口是内置的，我们只需要在sandbox中，可以一目了解看到，哪些返回字段有，哪些没有，而pageinfo就是没有

基于以上目前两个发现的问题，我选择升级了5.0.0-beta.3，是不是5.0.0-beta.2确实还需要改进，还是我的理解有问题呢，有知道的前辈告诉我一下，感谢，非常期待v5的正式版，我知道需要时间，感谢团队的努力。

为什么要升级，因为有两个问题

1，login and me这两个接口返回的字段中没有document_id，而其它表如果关联用户是依赖document_id，在v5中改进了，v4是id，但用户表没有返回document_id，为什么？我很奇怪

2，返回超过10条数据原来有一个meta字段，其中有total，能知道总条数，v5中改进了，使用了pageinfo，遵循和graphql一样的返回格式，改进非常棒，但是，但是，但是，接口没有返回pageinfo这个字段，开发文档中明确列出来了，但接口没有返回，因为graphql接口是内置的，我们只需要在sandbox中，可以一目了解看到，哪些返回字段有，哪些没有，而pageinfo就是没有

基于以上目前两个发现的问题，我选择升级了5.0.0-beta.3，是不是5.0.0-beta.2确实还需要改进，还是我的理解有问题呢，有知道的前辈告诉我一下，感谢，非常期待v5的正式版，我知道需要时间，感谢团队的努力。

Why upgrade? There are two issues

1. The fields returned by the login and me interfaces do not have document_id, while other tables that are associated with users that rely on document_id have been improved in v5. v4 is the id, but the user table does not return document_id. Why? I'm very strange

2. Returning more than 10 pieces of data originally had a meta field, including total, which can determine the total number of pieces. In v5, improvements were made by using pageinfo and following the same return format as graphql, which was great. However, the interface did not return the pageinfo field, which was clearly listed in the development documentation, but the interface did not return it because the graphql interface is built-in. We only need to see at a glance in sandbox which return fields are present and which are not, while pageinfo does not


Based on the two issues identified so far, I have chosen to upgrade to 5.0.0 beta. Is it true that 5.0.0 beta. 2 still needs improvement, or is there an issue with my understanding? If anyone knows, please let me know. Thank you and I am looking forward to the official version of v5. I understand that it will take time and appreciate the team's efforts.

Why upgrade? There are two issues

1. The fields returned by the login and me interfaces do not have document_id, while other tables that are associated with users that rely on document_id have been improved in v5. v4 is the id, but the user table does not return document_id. Why? I'm very strange

2. Returning more than 10 pieces of data originally had a meta field, including total, which can determine the total number of pieces. In v5, improvements were made by using pageinfo and following the same return format as graphql, which was great. However, the interface did not return the pageinfo field, which was clearly listed in the development documentation, but the interface did not return it because the graphql interface is built-in. We only need to see at a glance in sandbox which return fields are present and which are not, while pageinfo does not


Based on the two issues identified so far, I have chosen to upgrade to 5.0.0 beta. Is it true that 5.0.0 beta. 2 still needs improvement, or is there an issue with my understanding? If anyone knows, please let me know. Thank you and I am looking forward to the official version of v5. I understand that it will take time and appreciate the team's efforts.

**Comment by derrickmehaffy** [comment]
You should absolutely not be using the Strapi 5 beta for production purposes (or honestly anything other than just testing).

We clearly state that throughout the beta docs, our discord, and our marketing materials.

**Comment by eugle** [comment]
Looking forward to the official version, I really like Stratpi

**Comment by Willibaur** [comment]
> Can you please share your package.json as I believe the command you ran would use the v4 latest package, not the beta package.
> 
> To properly install the plugin during the beta you would use: `yarn add @strapi/plugin-graphql@beta` or specify the exact version in place of `beta`

Apologies for my mistake @derrickmehaffy I've tried installing the plugin as you mentioned and now everything is working fine. 
Thanks

**Comment by derrickmehaffy** [comment]
No problem, this will only ly be required during the beta since the packages aren't tagged as latest.
