### ISSUE TITLE
Strapi import functionality  is very very very slow (max 45KB/s)

### ISSUE THREAD

**Issue by alexbudin** [strapi/strapi#20270]
### Required System information

- Node.js version: 18.20
- NPM version: 10.5
- Strapi version: 4.24.1
- Database: SqlLite
- Operating system: linux-x64

### Describe the bug

An export takes less than a minute, but an strapi import takes hours.
My export file is 180MB, mostly because of images.

When i try an import it it takes ages to do

this is the transfer rate of an import of a file that sits on the same machine that is not even encrypted. The screenshot below is of an in-progress transfer. Teh speeds fluctuate between 20KB to 44.8KB. The funny thing is that it never goes over 44.9KB/s

<img width="537" alt="image" src="https://github.com/strapi/strapi/assets/832030/80b9eaa0-57fb-47f7-a0da-30a27884ac5d">

I thought of trying strapi export / import since the transfer option has never worked. I think most people using Strapi agree that you need a miracle to make a transfer work, but regardless, this is about the import functionality.

I dont understand how it can copy a file at the rate of 44KB/s. What does this import do? How does it work?

npm run strapi import -- -f export_20240506221330.tar.gz

### Steps to reproduce the behavior

Just do an import of a previously exported strapi instace that has assets.

### Expected behavior

An import that does not take 56-67 minutes for 180MB or images.

**Comment by alexbudin** [comment]
This is the total import time

<img width="532" alt="image" src="https://github.com/strapi/strapi/assets/832030/007f3305-f4d3-4872-8ab5-2f6475b6c590">

75minutes (1h 15minutes) - this is crazy

**Comment by alexbudin** [comment]
Also seems the Logos did not import at all :(

<img width="582" alt="image" src="https://github.com/strapi/strapi/assets/832030/06ee53ac-502d-4114-80f9-06c066fbb429">

I swear its better off to copy file manually from one instance to another than use all these tools.

**Comment by alexbudin** [comment]
Any help here please?

**Comment by alexbudin** [comment]
This is not a question. Its a bug

**Comment by alexbudin** [comment]
@derrickmehaffy can you please help. This is not a question.

**Comment by 0xPNG** [comment]
I have the same issue.

@alexbudin I've noticed that if I export with the `--no-compress` option, the import is significantly quicker - although still slow.

**Comment by N-index** [comment]
Same issue, 15.8Kb/s

**Comment by xmak** [comment]
Same issue here. It's astonishing that the import takes extremely more time than downloading the export file.

An alternative to using the --no-compress option, if you want to reduce download time, is to export without the --no-compress option, then on the machine where you're importing uncompress your .tar.gz file into the .tar file, then import from the .tar file. Same effect as --no-compress option, a little bit more manual work, less download time.

**Comment by dxm1244** [comment]
This is absolutely a bug, at the very minimum this tool should be removed and replaced by a documentation outlining an alternate method. I'm trying to import data to a Postgres database in Azure. Total uncompressed export size was 44.7 MB. I let it run for 11 hours and it still didn't finish. My average upload time was <1 KB/s. Practically useless.

**Comment by Radosav** [comment]
+1 this is really a bug, I have a database of >600MB, it's entirely impossible to use this tool

**Comment by KevinKreps** [comment]
Same here, did anyone of you find a solution? @alexbudin @Radosav @xmak 

entities: 112 transfered (size: 121.6 KB) (elapsed: 78032 ms) (1.6 KB/s)
and it gets slower and slower over time

**Comment by Radosav** [comment]
@KevinKreps we ended up writing an internal migration tool that uses the REST api. 
It's a lot faster than the current version of this tool but it's still far from an ideal solution

**Comment by KevinKreps** [comment]
For future readers, that are loosing hope on this, it is possible! Took me 13 hours for the upload of a 600MB export.

```
Starting import...
✔ entities: 2101 transfered (size: 6.8 MB) (elapsed: 23772462 ms) 
✔ assets: 5151 transfered (size: 609.9 MB) (elapsed: 16738410 ms) 
✔ links: 12951 transfered (size: 2.3 MB) (elapsed: 5852155 ms) 
✔ configuration: 79 transfered (size: 155 KB) (elapsed: 108809 ms) 
...
Import process has been completed successfully!
✨  Done in 46543.13s.
```

**Comment by IvanAdmaers** [comment]
2025 and this issue is still actual. First, I got [this](https://github.com/strapi/strapi/issues/19033) mysql error and after I noticed the speed. It's 42.2 KB/s in my case. And I have a 1GB file to import 😁

**Comment by IvanAdmaers** [comment]
After a lot of attempts:

1) 

```
SET GLOBAL innodb_lock_wait_timeout = 9999999;
SET SESSION innodb_lock_wait_timeout = 9999999;
```

2)
`SET foreign_key_checks = 0;` // Do not use

3)
Always use the flag `--no-encrypt` on data export

After the import is complete:

1) `SET GLOBAL innodb_lock_wait_timeout = 50;`
2) `SET SESSION innodb_lock_wait_timeout = 50;`
3) `SET foreign_key_checks = 1;`

Update:
Don't use `SET foreign_key_checks = 0;` because it issues problems after import.

**Comment by Keith-Hon** [comment]
> [@KevinKreps](https://github.com/KevinKreps) we ended up writing an internal migration tool that uses the REST api. It's a lot faster than the current version of this tool but it's still far from an ideal solution

Could you share your tool? I have a export file with >1GB size...

**Comment by maxbraeutigam** [comment]
+1 It’s a bug, not a question. 

And it is making Strapi documentation useless, e.g. this one that I have tried to follow.
https://strapi.io/blog/how-to-migrate-strapi-files-between-providers-local-s3-cloudinary-etc

**Comment by bernhardkelm** [comment]
Same issue here - importing assets from a dump is _insanely_ slow, even on a decent machine.
I'm sitting at around 80-90 KB/s and I have ~1.8Gb to import.
Since this is the way mentioned in the documentation I would also love any resolution for this.

Edit: there is an open PR for exactly this issue https://github.com/strapi/strapi/pull/25268

**Comment by haaswill** [comment]
Having the same issue on version `5.50.1`, but only on a windows dev environment, when I use my mac the import, export and transfer commands are much faster.

Windows specs:
CPU: Ryzen 9 9950X3D
RAM: 48 GB

**Comment by erkandem** [comment]
I am just going to leave this here for us who require a fix.

Maybe I read it somewhere else.
Maybe i discovered it by accident working with Django where there is no other way.

Avoid the strapi export altogether. 
As the saying goes: The backup/export you can't restore [in a timely manner] is not an export/backup but just a big file.

1) Dump the database using a native tool to your database. For Postgres, that would be e.g.`pg_dump`. Zip it if you like.
2) Copy the media root folder however your assets are stored. If it's a local folder it's just a copy. 
3) Create uncompressed zip or tar of both 1) and 2). Because the one is worthless without the other.

You have a backup.
To restore it:

A) Unzip / uncompress / untar database dump  from 1)
B) Use a native tool to restore the database in seconds. In case of Postgres that would be`pg_restore`.
C) Use copy the media files folder.

Do that piping with a bit shell scripting vodoo and you have restored an instance in under a minute at your hardware and network limits. 

Use the same database system at the remote and wherever you develop.
