### ISSUE TITLE
How to create custom configuration (not in core files) ?

### ISSUE THREAD

**Issue by madonzy** [strapi/strapi#2031]
Hi guys, I just did as in PR https://github.com/strapi/strapi/pull/1813, I added custom configuration to Admin Panel and it works, but I'm sure it'll be removed after strapi next update, so, how can I implement this so that after the upgrade I'll still have my configuration fields?

**Comment by derrickmehaffy** [comment]
@madonzy not sure what you mean it will be removed? Since I created that PR I can confirm that adding in the proxy information is written to your config/env*/development (or whatever env) server.js

This file should survive updates without issue, you can follow most typical migration guides or my guide:
https://github.com/strapi/strapi/issues/1880

**Comment by lauriejim** [comment]
It's actually not possible. You will have to update settings-manager plugin.
It's in our roadmap to develop a system that let you customize without updating core files.
