### ISSUE TITLE
Can't edit permission

### ISSUE THREAD

**Issue by Clowning** [strapi/strapi#206]
**Node.js version**: v6.9.1
**npm version**: 4.1.2
**Strapi version**: 1.6.2
**Operating system**: Mac OS 10.12.4

Hi, first of all, thanks a lot ! Your solution is awesome ! 

But i've an issue when i want to set permissions for some routes or other, the page doesn't load ! 

The green indicator is running but nothing happen ! Do you have any idea?

Thanks :)

**Comment by Clowning** [comment]
No news?

**Comment by robertcsapo** [comment]
Same issue here

**Comment by elliottcrush** [comment]
This has been fixed in 1.6.3 @Clowning @robertcsapo

**Comment by pierreburgy** [comment]
@Clowning thanks for this notification. Like @elliottcrush said, this has been fixed in 1.6.3.

If you want to fix the issue in an existing project, replace:
 - `./admin/services/routes.js` by https://github.com/strapi/strapi-generate-admin/blob/master/files/api/admin/services/routes.js (to fix the bug).
 - `./admin/config/routes.json` by https://github.com/strapi/strapi-generate-admin/blob/master/files/api/admin/config/routes.json (for security reasons).
