### ISSUE TITLE
[Main Nav] Random issue on Icons colors

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20602]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL and OS

### Describe the bug

When clicking on Settings > Review Workflows, or Settings > U&P > Roles, the color of Main Nav icons suddenly turn black.

### Steps to reproduce the behavior

1. Check Main Nav icons : they are all OK
2. Click on icons : everything is OK
3. Click on Settings Side bar options : everything is OK until you click on Review Workflows OR Roles
4. Click again on one of these items : icon colors turn back to normal

### Screenshots
[Screencast from 21-06-2024 15_33_55.webm](https://github.com/strapi/strapi/assets/97893822/0c86a626-7e54-4d33-bf64-3a68c5a8cf78)

**Comment by WalkingPizza** [comment]
Seems related to the following blocks, possibly because the ampersand isn't being resolved correctly and the `:focus` and `:hover` styles are applied to all SVGs when hovering or focusing anything.

https://github.com/strapi/strapi/blob/ccb2b38bb429263fcb4f23495b822252f00b51f9/packages/plugins/users-permissions/admin/src/pages/Roles/pages/ListPage/components/TableBody.jsx#L27-L34

https://github.com/strapi/strapi/blob/ccb2b38bb429263fcb4f23495b822252f00b51f9/packages/core/review-workflows/admin/src/routes/settings/index.tsx#L308C3-L313C4

**Comment by lucasboilly** [comment]
Fixed.
