### ISSUE TITLE
"X-Forwarded-Host: strapi" leads to 404

### ISSUE THREAD

**Issue by Lanseuo** [strapi/strapi#2068]
**Informations**
- **Node.js version**: 9.8.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: MongoDB
- **Operating system**: CentOS

**What is the current behavior?**

When I open the admin dashboard, an error occurs. In the browser developer tools I can see that most of the requests succeed, but some fail with a 404.

For example `/admin/users-permissions/main.js` returns 200, but `/settings-manager/autoReload` fails with 404. The difference between those requests is, that those who fail have the following request header set: `x-forwarded-host: strapi`.

I want to host Strapi on a shared hoster. I think Apache tries to match the request to my hosting account using the `x-forwarded-host`-header. If I send exactly the same request without the header, the request succeeds.

**Steps to reproduce the problem**

`config/environments/production/server.json`

```json
{
  "host": "localhost",
  "port": "${process.env.PORT || 61501}",
  "proxy": {
    "enabled": true,
    "host": "mydomain.tld",
    "ssl": true
  },
  ...
}
```

`.htaccess`

```
RewriteEngine On

RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule (.*)$ http://localhost:61501/$1 [P,L]
```

**What is the expected behavior?**

Request should not have or should have correct `x-forwarded-host` header.

**Suggested solutions**

Maybe set header based on configuration.

**Comment by derrickmehaffy** [comment]
@Lanseuo you also need to set the proxy port because right now strapi uses those to construct the URI:

`https://mydomain.tld:443` without the port you are constructing `https://mydomain.tld:` (notice the extra : )

I need to take another look at the proxy code and omit the :443 and :80 for those two ports. Also just as a suggestion, I recommend you use nginx as proxying via nginx is far easier and more "stable". Let me know if you need help setting it up. (And yes you can run nginx and apache on the same server. Digital Ocean has a great guide on this)

**Comment by derrickmehaffy** [comment]
The proxy code is here:

https://github.com/strapi/strapi/blob/98bd2d72de4da96b76362a243526209d76e46343/packages/strapi/lib/core/configurations.js#L322-L345

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
