### ISSUE TITLE
Relation to self loses data of the relation when migrating from v4 to v5

### ISSUE THREAD

**Issue by Bassel17** [strapi/strapi#20948]
### Required System information

- Node.js version: 20.13.1
- NPM version: 10.5.2
- Strapi version: latest V5 (v5/main)
- Database: sqlite
- Operating system: Macos
- Is your project Javascript or Typescript: JS

### Describe the bug

- we lose relation data when we have a contentType with a circular relation to itself, when we migrate from v4 to v5

### Steps to reproduce the behavior

1- On v4 strapi project (or develop branch) add a Many to many relation to contenttype Country to itself
2- populate it with some test data
3- Upgrade to V5 (or switch to v5/main) run the project (migrations will run)
4- if you check the countries contentType the relations are lost

### Expected behavior

- relations should be migrated successfully

### Screenshots

- On V4
<img width="2029" alt="image" src="https://github.com/user-attachments/assets/bfb90845-cd81-47e7-bc6b-81437df0c888">

- After upgrading to V5
<img width="2235" alt="image" src="https://github.com/user-attachments/assets/7ca3ccd3-fd23-4f28-a1c0-12ca1ad4a028">

**Comment by innerdvations** [comment]
After some investigation, we've found this is not self-relations, it is a result of two bugs.

1) The CTB in v4 generates manyToMany self-relations with an `inversedBy` on both attributes, rather than creating one with an `inversedBy` and one with a `mappedBy`  
1) In v4, Strapi generates two tables for the case where two sides of a relation have `inversedBy` rather than both `inversedBy` and `mappedBy` but only uses the first one listed in the schema
1) In v5, Strapi only keeps the last one listed in the Schema, and drops the first one (which is where v4 was storing the relation data)
