### ISSUE TITLE
CORS middleware not working in Strapi 5.0.0-rc.9

### ISSUE THREAD

**Issue by frontBOI** [strapi/strapi#20971]
### Required System information
- Node.js version: 18.19.0
- NPM version: 10.8.2
- Strapi version: 5.0.0-rc.9
- Database: sqlite
- Operating system: macos on M1 chip
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have this custom cors configuration in `/config/middlewares.ts`:
```typescript
{
    name: 'strapi::cors',
    config: {
      headers: ['accept-language', 'Token', 'Content-Type', 'Authorization', 'Accept', 'Origin', 'Response-Type'],
      origin:
        process.env.NODE_ENV === 'production'
          ? [`https://${process.env.DOMAIN}`, `https://${process.env.STRAPI_DOMAIN}`]
          : [
              'http://127.0.0.1:3000',
              'http://127.0.0.1:1337',
              'http://localhost:3000',
              'http://localhost:1337',
              'https://api.traefik.me',
              'https://docker.traefik.me',
            ],
    },
  }
```

In a local environment, I get CORS errors on POST request.
Here is what the preflight request gives me:
```
access-control-allow-headers: content-type
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
access-control-allow-origin: *
```

As you can see, the origin is not correct and I don't get the `access-control-allow-credentials` which is mandatory for my use case. But because it is not set, I get this error:
```
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
````

Why isn't the cors middleware working as expected ? I checked Strapi's source code and the default cors values include this allow credentials header.

### A case where it is working

In a local docker environment it works - the preflight request gives me this:
```
access-control-allow-credentials: true
access-control-allow-headers: X-Requested-With,Accept,Content-Type,Content-Length,Authorization
access-control-allow-methods: GET,POST,PUT,OPTIONS,HEAD,DELETE
access-control-allow-origin: https://docker.traefik.me
```

What is the problem with local environment ?

### Expected behavior

When I declare a cors middleware custom config, I want it to be taken into account.

### Screenshots

The preflight response in localhost that is not working as expected.
<img width="520" alt="Screenshot 2024-08-08 at 11 07 22" src="https://github.com/user-attachments/assets/f329fe5a-eff1-440b-be96-d30f514a0b9f">

**Comment by derrickmehaffy** [comment]
If the browser doesn't send an origin header (which is done automatically) the CORS middleware defaults to `*`. Origin isn't typically sent in samesite requests or in localhost.

https://github.com/strapi/strapi/blob/4f54945deb1266d47424b46aa1462f66e4e32e58/packages/core/core/src/middlewares/cors.ts#L41-L43

There could be many reasons why the origin header isn't sent but this isn't an issue with us. If we have no origin header we have nothing to compare to the whitelist.

**Comment by oloost** [comment]
I believe The origin of this bug starts from the default options of the cors in vite bundler.
I had the same one, and after configuring 'src/admin/vite.configs.ts' as followed, the problem was solved:

// src/admin/vite.configs.ts
import { mergeConfig } from 'vite'

export default (config) => {
  // Important: always return the modified config
  return mergeConfig(config, {
    resolve: {
      alias: {
        '@': '/src',
      },
    },
    server: {
      cors: {
        origin: ['http://localhost:5174', 'set your own white list here'],
        credentials: true,
      },
    },
  })
}

**Comment by BayBreezy** [comment]
I cant get pass this cors issue. Locally, I build my Strapi5 app and run it in production mode. I keep getting this error
```
Access to fetch at 'http://localhost:1337/api/auth/local' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I tried sending the request from safari, chrome and arc but the issue is still there.
I tried configuring the cors middleware but that did not fix the issue.
I tried updating the vite config as well and that changed nothing.

**Comment by julianojstavares** [comment]
> @derrickmehaffy , @frontBOI The origin of this bug starts from the default options of the cors in vite bundler. I had the same one, and after configuring 'src/admin/vite.configs.ts' as follows, the problem was solved:
> 
> ```
> // src/admin/vite.configs.ts
> import { mergeConfig } from 'vite'
> 
> export default (config) => {
>   // Important: always return the modified config
>   return mergeConfig(config, {
>     resolve: {
>       alias: {
>         '@': '/src',
>       },
>     },
>     server: {
>       cors: {
>         origin: ['http://localhost:5174', 'your white list origin'],
>         credentials: true,
>       },
>     },
>   })
> }
> ```

My God in Heaven! 

I was facing the CORS error (The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.) because origin was set to "*", frighteningly ignoring the CORS configuration made in src/middleware.ts

I didn't know what else to do, I had been investigating the problem for over 15 days, I even did several POCs, small projects just to test hypotheses, seeing if the error was on the front or back. I had read this page a few times myself, I had done what was proposed, about creating the Vite configuration file, but I hadn't resolved it.

Only now, reading for the hundredth time, after having tried a million things, almost giving up on using Strapi, I discovered that the suggested name is the wrong name. The post says to create the file "vite.configs.ts".. I only now realized that the correct name is "vite.config.ts" without the "s" in config!

Unbelievable how despair and tiredness affect human cognition. I'm devastated and relieved at the same time.

Honestly, I would like an explanation of why this error was generated by the official Strapi team.

@derrickmehaffy Can you explain to us what happened, or could you point us to someone who can? 


@oloost My friend, how did you discover that the error was related to this file? You are a genius!

**Comment by ParijatSaxena** [comment]
This config fixed it for me:

  {
    name:  "strapi::cors",
     config: {
      origin: [env("FRONTEND_HOST")],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
      headers: ['Content-Type', 'Authorization',"X-Frame-Options",'Origin', 'Accept', "X-Requested-With", "Access-Control-Allow-Headers", 'Strapi-Transformer-Ignore', 'strapi-response-format'],
      credentials: true,
      keepHeaderOnError: true, // Ensure CORS headers are sent even on error responses
    preflightContinue: false, // Ensure preflight requests are handled by Strapi
    optionsSuccessStatus: 204 // Return 204 for OPTIONS requests
    },
  }
