### ISSUE TITLE
Database installation fails

### ISSUE THREAD

**Issue by Jan10** [strapi/strapi#2182]
**Informations**
- **Node.js version**:  v10.7.0
- **npm version**:  6.1.0
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**:  
- **Operating system**:  Windows 10 Enterprise

**What is the current behavior?**
After I have selected the database, nothing happens. I'm not sure if it's a problem with our corporate 
proxy.

<img width="546" alt="2018-10-22-000014" src="https://user-images.githubusercontent.com/192557/47286589-9942ec00-d5ef-11e8-893f-1424ace1ec37.png">

**Steps to reproduce the problem**
- Strapi new newProject
- Select MongoDB

**Suggested solutions**
An error message or debug mode would be cool :)

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/issues/1927

**Comment by entwicklerfr** [comment]
Hallo @Jan10,

Ich hatte das selbe Problem mit meinem Windows Installation. :-)

I don't remember exactly but I believer I had to stop/deactivate the mongo windows service and start mono with "mongod" command instead of.

Hope this helps.

Note that I definitively abandonned ther idea of working with windows with this framework. I have hd so many problems (even with the WSL feature).
