### ISSUE TITLE
Content Manager sends me to blank page

### ISSUE THREAD

**Issue by Matildahermansson** [strapi/strapi#2186]
**Informations**
- **Node.js version**: 
- **npm version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 

**What is the current behavior?**

I'm working with a React + Strapi project and when I ran strapi start in my terminal I get to my admin page. However, when I press Content Manager I am met by Content Manager
Configure the default settings for all your Content types where I can either Save or Cancel. Whichever one I choose sends me to a blank page called http://localhost:1337/admin/plugins/content-manager/ctm-configurations
I cannot see any of my products or pics i uploaded a few weeks ago. 
What can i do? 

**Steps to reproduce the problem**
I have updated my Strapi and restarted my computer but that did not solve the issue. 

**What is the expected behavior?**

I want to be able to see my content manager and all my uploaded data.

**Suggested solutions**
![screen shot 2018-10-23 at 12 19 53](https://user-images.githubusercontent.com/31923706/47354211-76333d80-d6be-11e8-86d3-e79b34b98021.png)

**Comment by jacargentina** [comment]
Looking at #1912 and to this one:in my case the problem is that **i've created a content type with some fields** , then later i've **renamed those fields** like this

## Original content type
```
Blog = {
  titulo: string,
  cuerpo: string
}
```

## Modified content type

```
Blog = {
  title: string,
  text: string
}
```

## The problem

Basically the reason for the blank page is there is now inconsistency between the **editDisplay** and the available fields. Here is the schema on the state for the admin app for my blog content type

![capture](https://user-images.githubusercontent.com/517228/47517642-3b1c4000-d85f-11e8-8552-a17dda9c06a9.png)

For example, `editDisplay.fields.titulo` and `editDisplay.fields.cuerpo` are the old names (should not be there!), as the `editDisplay.availableFields` are the only valid ones.

## Solution

I can make a PR with some guidance from core devs on how they think is best to fix this: 

### Option 1
Try to not reach there, by validating the `editDisplay.fields` when the content type is modified, and some fields are removed on the model.

### Option 2
On the `Edit` component there is `renderAttr` which is not validating that the requested field is valid. A simple validation there can help with avoiding the "white page"

----
My vote is for option 1.

**Comment by jacargentina** [comment]
@soupette I've fixed this already. Sending a PR right now.

**Comment by soupette** [comment]
Thanks @jacargentina I'll test it

**Comment by pauldariye** [comment]
Thanks @jacargentina, just ran into this issue

**Comment by soupette** [comment]
@jacargentina I'm having a hard time reproducing the issue.
I've tried to create a `Blog` content type with `titulo` and `cuerpo`, then I've renamed them to `title` and `text` and the app is still working great. Do you have any `camelCase` content type in your app?

**Comment by jacargentina** [comment]
@soupette  no, no camelCase at all.

Maybe there are some server restarts in between ?

**Comment by soupette** [comment]
Well the servers restart each time you modify a file, so and the `content-type-builder` is blocked when the option is disabled, I did set the `admin: { autoOpen: false } }` in the server config though.

**Comment by gianca970226** [comment]
I found a solution when you get a white screen, or other reasons for the admin.

Whatever you see in the core_store there were inconsistencies, then delete that collection from the mongo db and restart the server he returned to create it full
