### ISSUE TITLE
Group content fields

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2219]
**What is the expected behavior?**
If we want to create an object with big list of fields I think it's better to able to group field in some group. For example:
group of fields called **general info**: 
* name
* family

and another group called **contacts**:
* email
* mobile number
* address

then we can show fields in a **collapse** view (if we set group for field view switch to collapse)

**Comment by Aurelsicoko** [comment]
I already started to work on something similar in the UI. What's the final goal of this? In my understanding, it'll expose a cleaner API. Are there others advantages?

![Uploading Content Type Builder - Content Type view Copy.png…]()

**Comment by mnlbox** [comment]
@Aurelsicoko In my mind It's a simple collapse view and just help to browse content type fields more simpler in admin ui when we have a big content type with so many fields and have not any result in API endpoints.

**Comment by Aurelsicoko** [comment]
Ok, what you're proposing should be only applied on the UI. We could certainly implement that in the future 👍 

I've taken notes of your comment in Product Board. I won't create a public card in the roadmap because it's not a priority for now. I'm closing the issue to keep the repository as clear as possible, however, everyone can still comment on this issue and upvote it.

**Comment by Aurelsicoko** [comment]
@mnlboxAs I said, I won't create a public card in the roadmap because it's not a priority for now.
