### ISSUE TITLE
Use facebook/dataloader to improve GraphQL performance

### ISSUE THREAD

**Issue by beeplin** [strapi/strapi#2228]
**What is the expected behavior?**

The current graphql plugin redundantly fetches data from mongodb and suffers from n+1 problem, which is very common for un-optimized graphql resolvers implementations. Example: 

```graphql 
query { 
  posts { 
    title 
    bins {
       title
    }
  } 
}
```

And the mongodb log:

![image](https://user-images.githubusercontent.com/13058150/47723037-a9616800-dc8e-11e8-9792-b970988be1e5.png)

Notice that different posts may have same bins, which have already been fetched in earlier `find`s for the first `post`, but is being stupidly refetched again and again for the later `post`s.

The common solutoin for this issue is to use https://github.com/facebook/dataloader

**Comment by lauriejim** [comment]
Hello @beeplin , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
