### ISSUE TITLE
Advanced filtering API

### ISSUE THREAD

**Issue by rejifald** [strapi/strapi#2297]
**What is the expected behavior?**
I think will be better to have more complex filtering on generated API. For example `{type:{$in: ['Financial', 'Political']}, status: {$not: 'DEPRECATED'}}`, or `{type:null}`, or `{type:undefined}`.
I am not sure about `undefined`, maybe some special value should be here. Like '$undefined', to preserve this value during sending via HTTP.
I have some experience with query builder that accepts query object like that, this is very very very useful for FrontEnd application. Now, I can't just filter by null field, or by two values. 
WDYT ?
Please, consider this feature.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1944 for the null values

Also @rejifald it is not a good idea to use symbols like that with restAPIs as everything is done via the URI.

From the looks of it you are building filters based on graphQL?

**Comment by rejifald** [comment]
@derrickmehaffy this is not duplicate. Because this feature not about filtering by null value, but more common feature.
I want just filter records via REST, by specifying multiple values, or null values, or exception values.
JSON can be encoded as URI, so, why it is not good idea ? 
Are u mean that i should use GraphQL to more complex filtering ?

**Comment by derrickmehaffy** [comment]
I agree with this `I want just filter records via REST, by specifying multiple values, or null values, or exception values.`

This is absolutely not a good idea: `JSON can be encoded as URI, so, why it is not good idea ?`

you shouldn't be encoding anything for filters, that is just isn't standard practice nor is it even remotely user friendly. 

And no I think that filters should be fairly similar between the rest and graphql but encoded json in a rest URI is not the way to do it. Rest calls should at least follow the openAPI standard as a start.

**Comment by derrickmehaffy** [comment]
an example of industry standards is something like this: https://jsonapi.org/recommendations/#filtering

**Comment by rejifald** [comment]
I am agree with you. Following industry standards is better.
U are agree with feature purpose that i\`ve described. So implementation is another question. I want to add more one example of complex filtering.
Nested fields.
For example:
`{'Book.Author.name': 'Peter'}`

**Comment by derrickmehaffy** [comment]
@rejifald I believe filtering on nested data is already being worked on in a way similar to that.

https://github.com/strapi/strapi/pull/1948

**Comment by rejifald** [comment]
Great !
But, WDYT about this feature ?
What prio it has, by your point of view ?

**Comment by derrickmehaffy** [comment]
@rejifald I'm not a member of the Strapi team myself, but to be frank I think this plays into a few other suggestions for filtering related items listed on the productboard:

https://portal.productboard.com/strapi/c/31-exclude-include-fields-from-query-request
https://portal.productboard.com/strapi/c/33-add-notcontains-filter

Right now it is not in the Strapi Team's high priority, their current focus is on the plugin framework to allow for easier plugin development and 3rd party plugins. This would be at best something they they could do in the future but more than likely should be attempted by a contributor such as what is being done in that PR I linked. 

Because Strapi is open source, anyone can take up development of features like this, personally I don't have the skills required to do something like this and can only offer advice and help track down bugs.

**Comment by Aurelsicoko** [comment]
You should really use GraphQL for that kind of purpose. I'm closing this issue because we won't implement something like that in our generated REST API. Thanks for the proposal though 👍
