### ISSUE TITLE
Bookshelf Date field autofills with current date

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2300]
**Informations**
- **Node.js version**: v10
- **npm version**: v6
- **Strapi version**: 14.5
- **Database**: MySQL (MariaDB 10.2)
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

When using bookshelf with MySQL if you leave a date field empty it will auto-fill with the current date.

**Steps to reproduce the problem**

Create a model with a date field, create an entry and leave the date field empty. The database will auto-fill the date field with the current date/time

**What is the expected behavior?**

Date should remain empty until provided a value

**Suggested solutions**

Modify the creation script to default to null, only created_at and updated_at should auto-fill and updated_at should update when a PUT request is made.

**Comment by derrickmehaffy** [comment]
Related code to issue:
https://github.com/strapi/strapi/blob/042784debd6fa97fd0bff46a5bec0d2633c09bf4/packages/strapi-hook-bookshelf/lib/index.js#L425-L433

**Comment by lauriejim** [comment]
Hello @derrickmehaffy , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/pull/1439
