### ISSUE TITLE
Catch plugin install error / yarn related

### ISSUE THREAD

**Issue by maciekkus** [strapi/strapi#2324]
**Informations**
- **Node.js version**: v11.1.0
- **npm version**: 6.4.1
- **yarn**: 1.12.3
- **Strapi version**: 
- **Database**: MongoDB 4.0.2
- **Operating system**: MacOs mojave

related comment: https://github.com/strapi/strapi/issues/952#issuecomment-438708074
**What is the current behavior?**
```
got those errors when running "strapi new project"
[2018-11-14T15:34:41.550Z] debug Moving the node_modules/strapi-plugin-user-permissions folder to the ./plugins folder.
[2018-11-14T15:34:41.626Z] error An error occurred during plugin installation.

I've checked the content of plugins dir, and this plugin exists, but not all files were copied.
there is no "services" directory.
the same issue is with upload plugin
```

Later I've found out that using yarn is not recommended.
After I switched to npm all installation process went ok.
So maybe treat this issue report as just information for others.

**Comment by derrickmehaffy** [comment]
1. Yarn is not supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#yarn
2. Node 11 is not -yet- supported (There have been other issues related to node 11, such as high CPU usage)

**Comment by wemod123** [comment]
@derrickmehaffy

There was a publish of issue #2194 
What is the actual situation?
Since I run error with plugin installation with yarn also.

**Comment by lauriejim** [comment]
Hello, some yarn bug still exist... we have to work on but it's not one of our priority now.
I suggest you to use npm.

**Comment by wemod123** [comment]
@lauriejim

Thanks for the reply.
One of the **critical reason** of using yarn, is some times npm runs into **fatal error** which will lead to fail to deploy, due to npm cache.
That kind of error similar to:
`npm WARN tar ENOENT: no such file or directory, open '***\node_modules\.staging\***`

Actually I reproduce the npm cache issue on Azure Webapp deployment with strapi-v18, the latest release.
That kind of app deployment was very popular like heroku etc. And in that way you will not have the authority to fully manage the npm cache, that at least a potential fatal issue for real production environment CI/CD.

yarn at least will not have this kind of issue, and is much much faster with production CI/CD.

As you said, some yarn bug still exist, my testing results with strapi-v17 is:
**The bug only appears with plugin-users-permissions and plugin-email.**


Hope this information helps for you, for considering production targeting release.

**Comment by derrickmehaffy** [comment]
@wemod123 add `package-lock.json` to your .gitignore and add the following to `.npmrc` file in your project root:
```
package-lock=false
```

That should stop the cache lock

**Comment by wemod123** [comment]
@derrickmehaffy

Thank you for the solutions, it can be alternative to solve the cache issue.
And at same time lost the **lock feature**, without which probably cause some other unexpected issues due to the unlock-version control, that need be checked carefully in **production environment**, since this project really depends on so many npm packages.

For me I prefer yarn as priority in production environment, but to solve the yarn issue with PR is beyond of me skill, let's see weather there will be some other one to contribute on this.
