### ISSUE TITLE
Getting "TypeError: hook.load(...).generateLookupStage is not a function" error after alpha16 update on find method

### ISSUE THREAD

**Issue by narayanan-git** [strapi/strapi#2438]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 

**What is the current behavior?**

Getting "TypeError: hook.load(...).generateLookupStage is not a function" error though REST API on find method across all content types.

**Steps to reproduce the problem**

Install alpha16 version. create content types, add data, call REST API for find method

**What is the expected behavior?**

**Suggested solutions**

**Comment by cosydney** [comment]
Same here

**Comment by lauriejim** [comment]
Hello @narayanan-git , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.
Thank you.

**Comment by wemod123** [comment]
@narayanan-git:

I guess the cause is: 
You have APIs generated in old Strapi version, then you copy it into your `project_folder/api_folder` , which is generated with Strapi V16, what you mentioned isntall alpha 16 version.

In that case you will get error, because of the core hook function is different, in Strapi alpha16, within the core hook do not use generateLookupStage any more.

So the obvious solution is:
Build every thing with new Strapi version, if you want re-use the old API Model setting, just copy the `Model.settings.json` contents to the one you new build.
