### ISSUE TITLE
Entry with media creation error if upload folder doesn't exist

### ISSUE THREAD

**Issue by flowen** [strapi/strapi#2448]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MongoDB shell version v3.4.18
- **Operating system**: Ubuntu 16.04.5 LTS

**What is the current behavior?**
in development mode I added a content-type called 'event'
added an event through the content-manager, but had a small error for uploading an image. 
the uploads directory did not exist. I created it and voila, the record was created.
Opened content manager, there were now 10 records of the same event. Only the last one containing the image, the rest did not.

**Steps to reproduce the problem**
see above

**What is the expected behavior?**
only 1 record with the image

**Suggested solutions**
I don't know the code, but if there's a warning on 'save' / submit than no record should be created

**Comment by derrickmehaffy** [comment]
@flowen the image is handled by another model with a relation. So it did not create that "entry" in the upload plugin as you suggest however, it still made an attempt to finish the other part of the request. When working with the API itself to do the same thing, you wouldn't be able to send it all in one request.

You would need to create the entry first, then upload the image and attach it in another. Hence the reason the entry was added, then the image failed due to the missing folder. 

This is working as intended, minus the fact the upload folder wasn't created by default. (Most people will be using symlinks to connect to a folder elsewhere, this is the reason it isn't by default I think.)

**Comment by lauriejim** [comment]
Since we add a `.gitkeep` file in the upload folder, when you pull your application the upload folder is cloned. Before is was not the correct behavior.
