### ISSUE TITLE
New fields of an existing content-type are only shown after restarting the service

### ISSUE THREAD

**Issue by flowen** [strapi/strapi#2449]
Informations

Node.js version: 10.14.1
NPM version: 6.4.1
Strapi version: 3.0.0-alpha.16
Database: MongoDB shell version v3.4.18
Operating system: Ubuntu 16.04.5 LTS

**What is the current behavior?**
I have a content-type.
I edit the content-type and add new fields.
Success message shows + field is there.
I refresh, fields disappear.
I restart the service with pm2.
new fields appear now appear in the UI

**Steps to reproduce the problem**
see above.

**What is the expected behavior?**
after submitting new fields, they should appear immediately. 

**Suggested solutions**
Perhaps by hot-reload or at least a warning the service needs a restart.

**Comment by lauriejim** [comment]
Hello @flowen !

Can you tell me how you start your sever with pm2 ? (the command you use)

If you start with `npm start` there is no auto reload feature needed by the content type builder plugin.
You have to start pm2 and disable the auto reload of pm2 and start with `strapi start` command instead of basic `npm start`
`pm2 start 'strapi start' --no-autorestart``

**Comment by flowen** [comment]
hi @lauriejim 

This the pm2 command I use:
`NODE_ENV=production pm2 start server.js --name api` 
from [this tutorial](https://blog.strapi.io/how-to-deploy-a-strapi-application/)

I installed the strapi cli on my server and with your command I've been able to fix this, thanks!

**Comment by lauriejim** [comment]
Ho okay.

It's `deploy` tutorial so normally you don't have to use content type builder in this case.
