### ISSUE TITLE
Upload provider public path not dynamic

### ISSUE THREAD

**Issue by lcherone** [strapi/strapi#2450]
Within the `strapi-provider-upload-local` package it does not take into account if one were to change the public path in `./config/application.json`

**What is the current behavior?**

It uploads to the wrong public directory.

**Steps to reproduce the problem**

 - Change `public.path` in `./config/application.json`
 -  Upload a file
 - Try and access it, you will get a 404, as file is still placed in ./public/uploads

**What is the expected behavior?**

That it takes into account the path and puts the files in the correct place to be served.

**Suggested solutions**

Make use of `strapi.config.public.path` in place of `public` in: https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-local/lib/index.js#L19
And any fluff like checking dir exists etc

**Comment by derrickmehaffy** [comment]
@lcherone in the mean time you can use symlinks (which I think is a bit more clean)

**Comment by lauriejim** [comment]
Hello @lcherone , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
Fixed in this PR https://github.com/strapi/strapi/pull/2966
