### ISSUE TITLE
Field label wont update for relations

### ISSUE THREAD

**Issue by tonyberetini** [strapi/strapi#2490]
**Informations**
• *Node.js version*: 11.4.0
• *NPM version*: 6.4.1
• *Strapi version*: 3.0.0-alpha.16
• *Database*: MySQL 5.7
• *Operating system*: Ubuntu 18.04

**What is the current behavior?**
When I finished content type setup i tried to rename labels used in the content manager forms using Content Manager plugin. All the fields are being updated correctly except for the relational field field "Label".

**Steps to reproduce the problem**
1. Create two content types
2. Relate two created content types via a relational field called "somanybugs"
3. Go to Content Manager Plugin and select one of the created relational fields
4. Try to update a label to "So Many Bug's", then save
5. Go back to the content manager and try adding data to this newly created content type. 
6. You will notice that a label is still being pulled from the content type builder as "somanybugs" instead of the one defined in the manager section.

**What is the expected behavior?**
Label should update with desired label

**Suggested solutions**
Fix a bug :)

**Comment by derrickmehaffy** [comment]
@tonyberetini can you test without the symbol in the label. My guess is that is the cause.

**Comment by tonyberetini** [comment]
Same thing...

**Comment by tonyberetini** [comment]
@derrickmehaffy same...

**Comment by derrickmehaffy** [comment]
I'll test myself after I've had some sleep lol. Just spent like 14 hours on a plane when I wrote that :laughing: 

you can try to purge your core_store table/collection and try again.

**Comment by odelucca** [comment]
Same thing here. Also, if I copy a Content-type that I've created in a different strapi installation, it appears on the sidebar but not inside the Content Manager

**Comment by wosevision** [comment]
Confirmed bug still exists in 3.0.0-alpha.21 – just updated from alpha.19 because I was feeling optimistic!

For troubleshooting purposes, here are the things I've tried so far which have **not** worked:

- Delete/re-add field from Content Type Builder
- Delete/re-add field from Content Manager
- Re-rename field from Content Manager (every variation of field on its own, with other fields to update, etc)
- Remove label completely from Content Manager, save with empty label, add label back, save again

For my own information, does anyone know where that label metadata is being stored? Maybe I didn't look hard enough, but I didn't see anything that referenced the Content Manager labels anywhere in `/api/{modelname}`, `/config`, any database table, etc... Where are those labels getting saved to?
