### ISSUE TITLE
How to use where() in a model query?

### ISSUE THREAD

**Issue by gianniskarmas** [strapi/strapi#2516]
How to use where() programmatically in a model?
What is the correct syntax to query a relational field?
```strapi.models.albumsize.find().where({'productdetails':{'code':'c002'}})```

**Comment by odelucca** [comment]
You need to create a query to do so :)

Check this: https://strapi.io/documentation/3.x.x/plugin-development/backend-development.html#orm-queries

**Comment by gianniskarmas** [comment]
Thank you @odelucca.
So I need to write a plugin with services, controllers etc just to do a simple query?
Isn't there any simpler solution?
My products model has 70 boolean values (size, spreads count and other variables) and each product has different ones selected like c005, c012, c040 etc.
Right now I'm checking in a switch loop what value is enabled and return a dynamic model:
```
module.exports = {
  afterFetchAll: async (model, results) => {
    let c002 = await strapi.models.albumsize.find().where({'productdetails':{'code':'c002'}});
    let c010 = await strapi.models.material.find().populate();
    let c011 = await strapi.models.material.find({materialsubcategory_eq:{face_off : true}});
    results.forEach(function (data) {
      switch (true) {
        case data.c002:
          data.albumSize = c002;
        case data.c010:
          data.materials = c010;
        case data.c011:
          data.materials = c011;
      }
    });
  },
```
my only problem is on how to do specific request queries like the above while keeping it as simple as possible.

**Comment by odelucca** [comment]
You can call the query anywhere in your plugin structure, you just need to call this:
```
/*
 * @modelName: The name of the model that you've created
 * @pluginName: The name of the plugin you're working on (folder name)
 * @queryName: The name of the query that you've created (remove the [] when changing it)
 * @params: The params you want to pass to your query
 */
strapi.query(modelName, pluginName).[queryName]>(params),
```

But, in order to this run, you need to create a query file. Put it on this path: `your_plugin_name/config/queries/`. If you don't have the queries folder, just create it. If you are using MySQL the file needs to be named as `bookshelf.js` and if you`re using MongoDB you name it `mongoose.js`

Inside the file:
```
/*
 * @queryName: The name of the query that you've created (remove the [] when changing it)
 */
module.exports = {
  [queryName]: async function (params){
    // Do the query here
  },
```

If you want a simple MySQL query, that will return all matching params, you can use this one that I named `find`:
```
module.exports = {
  find: async function (params){
    return this
      .query(function(qb) {
        qb
          .where('user', params.user)
          .andWhere('unread', params.unread);
      })
      .fetchAll();
  }
}
```

Hope it helps ;)

**Just one more thing**
Just one advice, don't use switch/case conditions in situations like that, you can get the same result, with better readability and performance just by mapping then into objects, like this: https://codepen.io/odelucca/pen/ZVBggr

**Comment by lauriejim** [comment]
Please check how work generated services.
