### ISSUE TITLE
GraphQL Plugin use routes config policies as default

### ISSUE THREAD

**Issue by conghai** [strapi/strapi#2626]
As document [Policies Usage](https://strapi.io/documentation/3.x.x/guides/policies.html#usage)
```
// Path: ./api/car/routes.json

{
  "routes": [
    {
      "method": "GET",
      "path": "/cars",
      "handler": "Car.find",
      "config": {
        "policies": [
          "global.isAuthenticated"
        ]
      }
    }
  ]
}
```

Why we are not set policies default for Graph same router configs and overwrite by custom?

## Solutions:

add more config to setting
```
// path: ./plugins/graphql/config/settings.json
{
   ...
   "useRoutePolicy": true,
}
```

Set default policies for Query Type if policies is empty
```
// path: ./plugins/graphql/services/Query.js
// add after line 73.
    let policies = _.get(handler, `Query.${queryName}.policies`, []);
    if(strapi.plugins.graphql.config.useRoutePolicy && _.isEmpty(policies)) {
      const action = isSingular ? 'findone' : 'find';
      const route = _.findLast(strapi.config.routes, r => {
        return _.toLower(r.handler) === `${name}.${action}`;
      });

      if(_.isObject(route) && _.has(route, 'config.policies')) {
        policies = route.config.policies;
      }
    }
```

Set default policies for Matution Type if policies is empty
```
// path: ./plugins/graphql/services/Matution.js
// add after line 43.
    let policies = _.get(handler, `Mutation.${queryName}.policies`, []);
    if(strapi.plugins.graphql.config.useRoutePolicy && _.isEmpty(policies)) {
      const route = _.findLast(strapi.config.routes, r => {
        return _.toLower(r.handler) === `${name}.${action}`;
      });

      if(_.isObject(route) && _.has(route, 'config.policies')) {
        policies = route.config.policies;
      }
    }
```

**Comment by lauriejim** [comment]
To add informations, you can find an exemple how implement policy in GraphQL query https://strapi.io/documentation/3.x.x/guides/graphql.html#customise-the-graphql-schema

**Comment by Aurelsicoko** [comment]
You're setting the policies in the router which relates to the REST API. If you want to add policies to a specific GraphQL query, you have to use the `schema.graphql` file (see @lauriejim link above).

**Comment by conghai** [comment]
Hi,

I know we can customize policy of `graphql`. But the default is when graphql generate has no policy applied.
Why we do have to config policies for `graphql` and also config them in `routes.json`

We should get policies from the `routes.json` applied to `graphql`, if the user wants to custom, policies will overwrite with the user configs.

You can review my commit to understand.

**Comment by Aurelsicoko** [comment]
@conghai I disagree with your point of view. The `routes.json` refers to the REST API whereas the `schema.graphql` refers to the GraphQL API. This is the reason that we have two different files and you've to apply the policy on both. In the beginning, we thought it was a good idea to attach policies to the controllers to unify them whatever the endpoint you use (GraphQL or REST). But it happens that sometimes you've to apply a policy for a specific kind of API. 

An example could be a policy which checks the URL parameters' types. It's useful for a REST API but it doesn't make sense for a GraphQL API because there is a schema and the parameters are already typed. So, we've to apply a different stack of policies depending on the endpoint.
