### ISSUE TITLE
Error message is too long

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#2640]
**Informations**
- **Node.js version**: v11.1.0
- **NPM version**: v6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: mongodb
- **Operating system**: ubuntu
- **(Optional) Link to your Project**: 

I am wondering if I am the only one faces the problem. It is not a bug but a little bit bothering me.

**What is the current behavior?**
Once there is an error occurs, the terminal prints a super long error message, which is hard to find the original error.
<img width="875" alt="screen shot 2019-01-16 at 11 32 11 am" src="https://user-images.githubusercontent.com/3782817/51273808-73c14680-1982-11e9-9d96-5a34bda37de4.png">
<img width="877" alt="screen shot 2019-01-16 at 11 28 29 am" src="https://user-images.githubusercontent.com/3782817/51273636-13caa000-1982-11e9-92d8-5342671023c2.png">
<img width="884" alt="screen shot 2019-01-16 at 11 33 32 am" src="https://user-images.githubusercontent.com/3782817/51273990-e03c4580-1982-11e9-8f65-71ec15b55da8.png">

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**
Do not print `model` in the error.

**Comment by lauriejim** [comment]
Hello @yummyelin !

It's caused by Mongoose. It's not due to Strapi.

But in some case in Strapi we manage some errors to make them cleaner and the community told us, the error is not enough explicite. So here you are sure you have the full logs of the error.

In any case I don't think it's a good things to make a wrapper of the ORM.
And errors logs happen only when there is an error. So it doesn't have to happen. Here you are sure you have the full log to be able to fix the issue.

So for now we will don't change logs for that.
Thank you for your feedback!
