### ISSUE TITLE
Changing the users password

### ISSUE THREAD

**Issue by xilliman** [strapi/strapi#2733]
Currently I have to follow these steps to change a users password

- POST Request to /auth/forgot-password
- Receive an E-Mail with a code
- Post Request to /auth/change-password with the new password and the code

Why isn't it possible to change the password right away? 

Its really bad UX, if the user has to click on Forgot Password instead of change it right away in his user profile.

**Comment by lauriejim** [comment]
Hello @xilliman , please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

If you have an error message when you update the user via the content manager, please update to last version of Strapi. This issue is fixed.

Thank you.

> This is a templated message

**Comment by nezzard** [comment]
Have the same erorr, after recieving email, i change password and get error 'wrong code'

**Comment by muhaimincs** [comment]
Yes it’s bad UX to persuade user to click forgot password button even though they don’t forget

**Comment by PedroPini** [comment]
I am with the same problem, but i can`t even received the email

**Comment by muzammil-majeed-viabletree** [comment]
Any update on this ?
