### ISSUE TITLE
Don't show any value (database hash, or otherwise) for password fields

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2769]
# Please see the following comment, the rest of this issue is not relevant: https://github.com/strapi/strapi/issues/2769#issuecomment-548718945

---

**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: v22
- **Database**: Postgres
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: N/A not my project but debugging another users

**What is the current behavior?**

By default when the following entry is created in `core_store > plugin_content-manager_schema` the `password` field is automatically added to the `list view` which should not happen. In doing so it will cause a blank white page when trying to open the users model to add/update/delete users

**Steps to reproduce the problem**

Create a new project in a production type environment (set proxy, configure nginx, ect ect)
Load up the adminUI on whatever port nginx is configured to proxy through
Attempt to edit or create a user

Temporary solution to resolve is to go into the content-manager plugin, and remove `password` from the list view (I also removed provider from the edit view as it shouldn't be there either):

![image](https://user-images.githubusercontent.com/8593673/52323892-2aba4c00-299c-11e9-9cde-3e86970031ea.png)

**What is the expected behavior?**

`Password` should never be added to the list view (you would be rendering a hash from the database`
**IF** password is added to the edit view, it should be empty to allow for manual password changes, and should **NOT** render the hash from the database. It should be considered a "write only" field

`provider` should not appear on the edit view as that is a field set by strapi itself and would never be changed by a user aka a "Read Only" field

**Suggested solutions**

Not a suggested solution but as right now the content-manager schema constantly has to be deleted due to many many other errors, getting these default values is important to fix some of these white screen breaking bugs. It is very confusing for new users/developers that I have been helping to support.

**Comment by soupette** [comment]
Well if the password is not available how do you create a new user?

**Comment by derrickmehaffy** [comment]
@soupette you shouldn't have the password on the `list` view, edit view is fine but it should not pull the hash from the database.

Having it on the list view is what is breaking the adminUI and causing the white screen

**Comment by soupette** [comment]
#3633

**Comment by hkovacs** [comment]
i am unable to log into the admin with my first user i created. i see the password hash is showing as per this issue.

any suggestions for a temporary work around until this issue is resolved?

**Comment by derrickmehaffy** [comment]
@soupette @alexandrebodin I'm going to reopen this until we remove the hash from the password field from showing. Other users have noticed this as well and I don't want to have duplicate issues being made. We can close this once a PR is made to exclude the data from showing on the admin.

**Comment by hkovacs** [comment]
i know it's picking nits, but the title of this issue is not the existing problem. should the title be changed?

i did a test and interestingly the password did not get improperly changed when i saved the edit form. so that's good news.

so the problem is only that the field needs better UX.

in other cms's, the password field is not immediately available, and a link is provided to offer the user the ability to change pw. if clicked, 3 fields get displayed, current pw, new pw, confirm new pw.

i wish i was advanced enough to be able to make this for strapi. hopefully soon.

**Comment by keymandll** [comment]
> in other cms's, the password field is not immediately available, and a link is provided to offer the user the ability to change pw. if clicked, 3 fields get displayed, current pw, new pw, confirm new pw.

I believe it's probably better to have the forgot password mechanism to be used to change passwords due to simplicity. 
This is because if you have a dedicated password change form with the 3 fields you proposed you would have to implement rate limiting on form submission or add a captcha (or the combination of both). This is because the form expects the current password and, if someone got access to the password change page they could attempt to brute-force credentials via the current password field. 
It is probably safer to use password reset as a way to change password as it sends out an email with a code in a link. That code will not be brute-forced for sure (based on current implementation). As long as the user's email account is not compromised things are much safer.

**Comment by derrickmehaffy** [comment]
closing as duplicate to https://github.com/strapi/strapi/issues/4341 please post any related responses on that issue.
