### ISSUE TITLE
Add auto increment option to the model attributes

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2784]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Add auto increment option to the model attributes

**Comment by lauriejim** [comment]
Hi @abdonrd can you give us more details about your need please.

**Comment by abdonrd** [comment]
@lauriejim I mean an integer attribute that auto increment.
Like we have here at GitHub with the issues and the PRs.

**Comment by lauriejim** [comment]
Hum something like that ?

```
{
  ...
  "options": {
    "timestamps": true,
    "increment": "number"
  }
}
```

**Comment by abdonrd** [comment]
Maybe! If we want to replace the current ID.

Or something like this if we want it as another field:

```
"identifier": {
  "type": "numeric",
  "autoIncrement": true
},
```

**Comment by Aurelsicoko** [comment]
@abdonrd can you make a PR for that?

**Comment by abdonrd** [comment]
@Aurelsicoko for now I will not be able to dedicate time. 😕

**Comment by balumuriraj** [comment]
I tried adding these mongoose plugins `mongoose-auto-increment` and `mongoose-sequence` to strapi in `config/functions/mongoose.js`. The counter collections are getting create, but the sequence counts are not getting updated. Is there a way to get these plugins working or is there a way to implement this myself?

**Comment by AakashPat** [comment]
I just found out that this was indeed an option in version 1.x.x of strapi.
Link: https://strapi.io/documentation/1.x.x/models.html#autoincrement

I suppose this is no more a part of the current version.
Any way to add it back?

**Comment by yxwu** [comment]
+1

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/add-auto-increment-option-to-the-model-attributes
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Comment by maccomaccomaccomacco** [comment]
@abdonrd why would it be useful? Can we bring some examples of use cases?
