### ISSUE TITLE
Question: unit tests for strapi-utils

### ISSUE THREAD

**Issue by fdeberle** [strapi/strapi#2804]
I'm currently having an issue with https://github.com/strapi/strapi/blob/master/packages/strapi-utils/lib/templateConfiguration.js when deploying strapi on Pivotal Cloud Foundry (PCF).

Before opening a bug issue I was wondering if there are unit tests so I can investigate my problem on my own?

**Comment by derrickmehaffy** [comment]
@fdeberle I don't believe so but you can have a look through the tests directory here: https://github.com/strapi/strapi/tree/master/test

Can you open a bug report with all the required template information so that it can be looked at. Please include any debug logs you might have from the console. The Strapi Helper plugin is really only used for --dev projects to de-duplicate some node packages used in the build process (such as babel) and you really shouldn't have issues with a deployed project.
