### ISSUE TITLE
An error occurred during content-type-builder plugin installation, folder has space

### ISSUE THREAD

**Issue by doubleUTF** [strapi/strapi#2858]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: MongoDB
- **Operating system**:  Win7
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When I try to create a new strapi app, I get the following error

{ Error: Command failed: node C:\Users\Big D\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js install settings-manager
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Users\Big'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node C:\\Users\\Big D\\AppData\\Roaming\\npm\\node_modules\\strapi\\bin\\strapi.js install settings-manager ' }

**Steps to reproduce the problem**
Trying to create through strapi new strapi-app. I do have a space in my user name folder which may be causing this problem.

**What is the expected behavior?**

No errors

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Due to the fact you are on Windows 7 and thus don't have access to WSL in this case you will have to use an Ubuntu (Or other supported) Linux virtual machine.

As a side note, yes spaces can cause issues, but officially Windows environments are not supported yet, due to this I am marking this as closed however you may continue to update if you are able to troubleshoot this issue. The Strapi team are working on Windows support, however it is not currently up to the level in which issues are actively being looked at. There is currently quite a bit of code that needs to be converted over to OS independent functions.

Thanks
