### ISSUE TITLE
Upload Files size persisted as String not Double

### ISSUE THREAD

**Issue by DaleBeckles** [strapi/strapi#2877]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.21
- **Database**: Mongo
- **Operating system**: Mac osMojave 10.14.2
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When a content type contains a Media field (file upload), the file size is persisted to the database as a String. If GraphQL queries with aggregation are made on the size field it will fail.

**Steps to reproduce the problem**
Add a Media field to a content type, and view the UploadFile schema in the GraphQL playground or view the upload_file collection in the database. Both instances will show that size is being persisted as a String.

**What is the expected behavior?**
upload_file should persist size as a Double.

**Suggested solutions**
Change upload_file size from String to Double.

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
Closing as fixed in https://github.com/strapi/strapi/pull/4351
