### ISSUE TITLE
Write email templates to the file system or read initial state of email templates from file system

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2880]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I want to use git for editing/creating/deleting email-templates, it's more clear and transparent for developers. For it I want to see email templates in file system.

Will be enough read initial state for email templates from file system.
Also, good approach to have another params (like email confirmation) as initial value in file system.

**Comment by Aurelsicoko** [comment]
I completely understand the need here, but our main goal is to manage content (and we have still a lot to do on this part), then we will improve all the secondary things like email templates, multiple authentications, etc. You should edit manually the plugin to fit with your needs. 

With the separation of the core vs custom files, it will be easy to do it in the beta/stable version of Strapi. I'm closing the issue since we don't plan to integrate it in our roadmap for the next 12 months.

However, I would like to thank you for your interest and the idea 👍
