### ISSUE TITLE
Enum doesn't strip string from useless spaces when configuring Content Type

### ISSUE THREAD

**Issue by Vadorequest** [strapi/strapi#2881]
**Informations**
- **Strapi version**: 3.0.0-alpha.24.1

**What is the current behavior?**
When creating a new Content Type, I looked into the generated files and saw the following in `api/organization/models/Organization.settings.json`:

```json
...
"state": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "active",
        " inactive"
      ]
    }
```

Note the extra space in ` inactive`, I believe the data should be sanitized before being stored in the model. I do not know if this issue has any undesirable side effect on the app, just noticed it so reporting it.

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
