### ISSUE TITLE
Allow us to restrict types of files uploaded to desired mime type tags, via admin UI content manager

### ISSUE THREAD

**Issue by kgrosvenor** [strapi/strapi#2887]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

**Comment by Aurelsicoko** [comment]
Thank you @kgrosvenor for submitting this feature request. I've added a new card on our public roadmap https://portal.productboard.com/strapi/c/54-restrict-types-of-files-uploaded.

**Comment by derrickmehaffy** [comment]
Reopening Feature request since the card was deleted on product board

**Comment by Heziode** [comment]
Any progress on this feature ?

It's annoying to have to make hacks for this kind of stuff…

**Comment by derrickmehaffy** [comment]
> Any progress on this feature ?
> 
> It's annoying to have to make hacks for this kind of stuff…

Not currently no, please do feel free to submit an RFC or a PR.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/modify-or-allow-for-privatesecured-files
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
