### ISSUE TITLE
Can't update user info if user signed in with provider

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2963]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: v6.9.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

Can't update user info, if user signed in with provider because the password min length:

<img width="939" alt="Screenshot 2019-03-11 at 17 30 18" src="https://user-images.githubusercontent.com/1007051/54140523-17c7eb00-4424-11e9-91f0-29434b22dbfb.png">

**Steps to reproduce the problem**

1. Sign in user with any provider
2. Try to update any field of the user info

**What is the expected behavior?**

As the password field is not required, having a minimum of characters should not stop the submit.

**Comment by lauriejim** [comment]
Hello @abdonrd !

Thank you for this report!

We have to apply the password validation only if the user use the local login strategy.

**Comment by jklepatch** [comment]
I can have a look. Is this here in this package?
https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin

**Comment by lauriejim** [comment]
It will be in the plugin Users & Permissions

**Comment by codypersinger** [comment]
@lauriejim Please forgive any stupidity on my part, as I'm brand new to trying to contribute. I see that you mentioned the `strapi-plugin-users-permissions` package. However I can see that the validation for the password form field in `/admin/plugins/content-manager/user/:userId` comes from `strapi/packages/strapi-plugin-content-manager/admin/src/components/Edit/index.js:86`. Is this validation somehow driven from within `strapi-plugin-users-permissions`? Would a solution be to update `getInputValidations()` so that we don't include `minLength` if `attr === 'password'`?

**Comment by lauriejim** [comment]
I think the way we can manage this case is - if we are trying to EDIT a user, and the value we receive is empty, we have to be able to send the edit request.

@soupette is the guy you need. I will change the ownership of this issue.

**Comment by abdonrd** [comment]
Any news here? Thanks in advance!

**Comment by derrickmehaffy** [comment]
@ychey when there is an update you will see a response or a PR linked to the issue. No updates yet.
