### ISSUE TITLE
Update existing field name of a table

### ISSUE THREAD

**Issue by scorpionking90** [strapi/strapi#3015]
**Informations**
- **Node.js version**: 10.15.0
- **Strapi version**: alpha 24.1
- **Database**: Postgres
- **Operating system**: Linux

**What is the current behavior?**
I have created tables and corresponding fields. Now when I try to edit the field name it is creating new field instead of updating existing field.

**What is the expected behavior?**
Expected to update field of the table. I have created table "Associates" and field "associateName". Now when I try to edit field name as "associate_name", new field is getting created without altering the existing field.

**Comment by lauriejim** [comment]
Hello @scorpionking90 !
All informations here about this topic http://help.strapi.io/content-type/update-content-type-and-database-schema

**Comment by scorpionking90** [comment]
Thanks @lauriejim. This works for me

**Comment by lauriejim** [comment]
Awesome!

**Comment by doublemarked** [comment]
@lauriejim this URL no longer works

**Comment by lauriejim** [comment]
Yes we deleted this resource to move it in the documentation.

---

By default, Strapi never deletes schema related collections/columns/tables in your database. We always create new schema related collections/columns/tables. This ensures you never lose your data.

**Rename a "content type"**

In this case, Strapi will create a new table/collection with the new name and recreate each column without data migration.

**Rename an attribute**

In this case, Strapi will create a new column.

**Update attribute to required**

If you update an attribute to "required" and you already have entries (in the database) with null/empty value for this attribute, you will have an issue because of the constraint. You will have to update your data to make this constraint (e.g. required) work.

**Data migration**

As we create new tables/collections (as above), you will have to manually migrate your data. We are not managing this part because it's a really complex task.

You are able to create updates from the UI that affect the database in many possible ways, therefore we  are faced with too many possibilities specific to individual projects to enable error managing for this situation.

For now, we have decided to let you control these migration steps yourself, this ensures the migration suites your needs properly.

**Comment by andrewspode** [comment]
@lauriejim I'm assuming the above is still true, and from my own experience I believe it to be so. But to say "You are able to create updates from the UI that affect the database in many possible ways" as a reason for not handling *any* migration at all? There are surely limitations to that.

Renaming a field is a minimal operation that could surely be handled - it's also a very common requirement! I should be able to very easily change my mind about field names. Start with "title" and then later decide to change it to "pageTitle" as part of an iterative development process. Instead, unless I want to start handling data migrations (of which there is no built in system) I need to plan this in advance meticulously before data is added to the CMS. That's a recipe for a lot of stress.

Can this blanket approach please be reconsidered?

**Comment by derrickmehaffy** [comment]
@andrewspode We plan to handle database migrations in Q3, there is a much larger discussion topic on this in #1114

**Comment by andrewspode** [comment]
@derrickmehaffy good to know something is happening. The only thing I would add is that dropping/cleaning up of the DB when you delete content-types (as the discussion in #1114 seems mostly about) is very different to a simple task like renaming a field. The argument is you don't clean the database up because you don't want people to lose data - but in fact, when you rename a field, from a GUI/non-tech perspective you've "lost data". It feels like this is a separate issue?

**Comment by derrickmehaffy** [comment]
Renaming and dropping are both a DB schema change, so in our scope they are the same thing. Renaming is actually more difficult as we have to track a state of changes, or at the very least know what the old name was.

The #1114 issue is a central tracking issue for all DB migrations.

**Comment by andrewspode** [comment]
> Renaming and dropping are both a DB schema change, so in our scope they are the same thing. Renaming is actually more difficult as we have to track a state of changes, or at the very least know what the old name was.
> 
> The #1114 issue is a central tracking issue for all DB migrations.

It's also locked for comments and the last message on there says "We are not actually working on it" which is contrary to your suggestion it's happening in Q3. Perhaps needs an update on there?

**Comment by derrickmehaffy** [comment]
I've unlocked that thread with a note: https://github.com/strapi/strapi/issues/1114#issuecomment-759297723
