### ISSUE TITLE
Strapi start crash when changing database from sqlite to mongodb

### ISSUE THREAD

**Issue by vanpana** [strapi/strapi#3047]
**Informations**
- **Node.js version**: 10.12.0
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: sqlite
- **Operating system**: macos
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Database cannot be changed from sqlite to mongo db if types are already created. Error when starting strapi is `Cannot find module 'strapi-hook-bookshelf/lib/utils/'`.

**Steps to reproduce the problem**
1. Create new strapi project using sqlite db.
2. Create types with relations between them.
3. Change DB to mongodb.

**What is the expected behavior?**
Strapi should start successfully.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@vanpana the controllers and services are different between mongoose and bookshelf databases. See this issue: https://github.com/strapi/strapi/issues/2912

You will need to regenerate all your models, you can use my "upgrade" process to do it: https://github.com/strapi/strapi/issues/1880

**Comment by derrickmehaffy** [comment]
For reference this bug is already known and a Feature request exists to fix it however work has not been started: https://portal.productboard.com/strapi/c/55-merge-mongoose-and-bookshelf-templates

For now I will mark this as closed but you are more than welcome to continue discussion here if you need more information or help. You are also welcome to join the slack: https://slack.strapi.io as well.

**Comment by ans1genie** [comment]
Hello
Any updates for this subject?
