### ISSUE TITLE
Protect API endpoints

### ISSUE THREAD

**Issue by matseriksen** [strapi/strapi#306]
Hello. Great project!
Is there any easy way to protect the api endpoints?

**Comment by Aurelsicoko** [comment]
@matseriksen You can protect the API endpoints defined in the `/api/**/config/routes.json` by applying [policies](https://strapi.io/documentation/guides/policies.html) to the routes. However, we are working hard to secure the API endpoints defined by the plugin themselves. That's why we don't recommend to use the alpha version in production right now.
