### ISSUE TITLE
Role custom field not displayed

### ISSUE THREAD

**Issue by Enhed** [strapi/strapi#3103]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: doesnt matter
- **Operating system**: ubuntu 18.04 lts
- **(Optional) Link to your Project**: 

**What is the current behavior?**
New customs field in Role cant be edited from interface. After creating often crash project with error: 
![image](https://user-images.githubusercontent.com/36981278/55782261-8dbb8280-5ab4-11e9-8421-9782b02a90ee.png)

**Steps to reproduce the problem**
Content Type Builder -> Role -> Add New Field -> String/Enumeration with any name
sometimes created, sometimes crash project
if field created, i cant see them in interface by any created role for edit

new enum field in Role
![image](https://user-images.githubusercontent.com/36981278/55783599-75993280-5ab7-11e9-99f4-6a6265aaf273.png)

configure content manager:
![image](https://user-images.githubusercontent.com/36981278/55783639-8cd82000-5ab7-11e9-98e2-ba30b10bc512.png)
![image](https://user-images.githubusercontent.com/36981278/55783651-92356a80-5ab7-11e9-8675-697c08e825d8.png)

list ignore my view config:
![image](https://user-images.githubusercontent.com/36981278/55783687-a37e7700-5ab7-11e9-9a32-899591748e7d.png)

and editing same:
![image](https://user-images.githubusercontent.com/36981278/55783700-b133fc80-5ab7-11e9-864b-f26d487e79bb.png)

**What is the expected behavior?**
Content Manager has configurable position field and should work by settings

**Suggested solutions**

**Comment by soupette** [comment]
I'm not sure it is a bug properly said, it's just that the UI doesn't render the other added fields, so it's more a missing feature...

I don't mind adding the other fields into the UI but I will need @Aurelsicoko insight how we should display them, especially the relations.

**Comment by Aurelsicoko** [comment]
@Enhed It's not an issue... the Roles & Permissions are specific to Strapi and the level of customisation is very limited. You can add new fields but they won't be displayed in this specific UI (whereas it's the case when the entries are managed through the content manager plugin).

You should edit the Users & Permission plugin UI by yourself to make it visible. I'm closing this issue because we won't fix it or make a change to display the new fields in the coming year. It might happen in the future though... Thank you for raising the issue!
