### ISSUE TITLE
RTL support in Wysiwyg

### ISSUE THREAD

**Issue by amitgur** [strapi/strapi#3114]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I'm using Wysiwyg as editor, but my language (Hebrew) is RTL. Any way to add the `textAlignment:right` to the draft.js component?

**Comment by soupette** [comment]
@amitgur, in order to modify I suggest you to setup the development mode [refer to the CONTRIBUTING guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md), create a dev app (`strapi new my-app --dev`) and customise de WYSIWYG as you need. The current implementation of Draft.js is [here](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg). Once you are finish with your modifications, you will need to manually apply your changes into your other application and then run `npm run setup --plugins` at the root of your project.

**Comment by NagyWesley** [comment]
For with the same issue, a quick solution is to use the .editor class... something like I did here ttps://bit.ly/StrapiRTL

**Comment by a-atalla** [comment]
Draft.js support that by default, but the default [Draft.js Style](https://draftjs.org/docs/advanced-topics-issues-and-pitfalls/#missing-draftcss) is needed for it to work

if you try the demo in [draftjs](https://draftjs.org/) home page if you start the line with an RTL character it will align automatically to the right

**Comment by a-atalla** [comment]
I could make it work by overriding the `WysiwygEditor` component  as follow

1. create `extensions/content-manager/admin/src/components/WysiwygEditor/index.js`
add copy the default content and only import the `Draft.css`
```javascript
import React from 'react';
import { Editor } from 'draft-js';
import 'draft-js/dist/Draft.css';  // only add this line
import PropTypes from 'prop-types';

class WysiwygEditor extends React.Component {
    render() {
        return (
            <Editor {...this.props} ref={this.props.setRef} />
        );
    }
}

WysiwygEditor.defaultProps = {
    setRef: () => { },
};

WysiwygEditor.propTypes = {
    setRef: PropTypes.func,
};

export default WysiwygEditor;
```
2. rebuild with `npx strapi build`


<img width="1522" alt="Screen Shot 2020-05-17 at 5 05 00 PM" src="https://user-images.githubusercontent.com/536140/82152381-0ddc1c00-9861-11ea-9537-89af9ae20cc7.png">

**Comment by Elsayed-Mubarak** [comment]
> For with the same issue, a quick solution is to use the .editor class... something like I did here https://bit.ly/StrapiRTL

why it works for ritch text only ?
