### ISSUE TITLE
REST _limit security limit similar to GraphQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3205]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Related GraphQL security limit: https://github.com/strapi/strapi/pull/2400

Recommended setting location (new) `config/settings.js`

I'm purposing the option to set a maximum limit to the `_limit` filter for security and DDoS prevention. The purpose is to "limit" the maximum entries someone can request from the REST API similar to what is done via the GraphQL. Allowing basically unlimited amount of records to be returned via REST could cause a significant performance degradation to the point where you could effectively denial of service a Strapi deployment.

**Comment by derrickmehaffy** [comment]
(this would go along with implementing the rate limiting here: https://github.com/strapi/strapi/issues/3206 )

These two would provide a very basic but fairly secure option to Strapi deployments

**Comment by lauriejim** [comment]
Thank you for this idea. Can you submit it in ProductBoard please.
We will keep it in PB instead of GitHub.

A policy exist in the users and permission plugin.
Here is how to use it https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/routes.json#L194
Here is the policy https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js

If the config have to be updated, feel free to create a new one based on your need and use this new one in your routes.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy What do you suggest as a maximum limit value? 10,000?

**Comment by derrickmehaffy** [comment]
@Aurelsicoko depending on if a user can configure it a default of 1000 is probably best. 

Anything above that in my testing a very likely to lock up Strapi even with a very powerful database backend.
