### ISSUE TITLE
Configuration not load

### ISSUE THREAD

**Issue by Redni** [strapi/strapi#327]
**Node.js version**: 8.8.1
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.6.4
**Operating system**: Arch Linux

Configuration files do not load. The host remains on localhost despite the change in config / environments / **/server.json, this causes an error when loading modules in the admin panel on the server with its own domain. Is:

Not Found: http://localhost:1337/settings-manager/autoReload
instead
Found: http://mydomain.com:1337/settings-manager/autoReload

Custom set ENV also not work:

```
process.env.HOST = 'mydomain.com';
process.env.HOSTNAME='mydomain.com';
```

**Comment by Aurelsicoko** [comment]
@Redni It's a known issue on our side. That's why we are saying that you shouldn't put in production a project using the `alpha` version. A lot of fixes will be released this week but not the good ones in your case. A pull request has been opened https://github.com/strapi/strapi/pull/325 to detach the admin panel from the core framework.

**Comment by Aurelsicoko** [comment]
This issue has been fixed https://github.com/strapi/strapi/pull/325. It will be released in the next release `alpha.7` in December.
