### ISSUE TITLE
Constant "File changed, server restarting" in Dropbox folder

### ISSUE THREAD

**Issue by rouxfeur** [strapi/strapi#3315]
**Informations**
- **Node.js version**:  10.15.1
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.26.2
- **Database**: default
- **Operating system**: macOS Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When I start Strapi from inside my Dropbox folder, it constantly restarts because a file has changed, even though no file has changed. When I move it somewhere else, I can start normally.

**Steps to reproduce the problem**
CLI quickstart a Strapi project inside Dropbox folder on Mac.

**What is the expected behavior?**
Strapi starts and restarts only when a file has been changed.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello!

I'm not sure it's a good idea to have your application in a Dropbox folder.
Dropbox sync and update files anytime to you will not be able to start your app with `strapi start` you will have to use `npm start` and in this case you will have to restart manually your app every time you update e configuration or if you create a content type from the admin.

I suggest you to use GitHub to host your code instead of Dropbox.
