### ISSUE TITLE
Installing GraphQLError - Strapi v3.0.0-beta.8

### ISSUE THREAD

**Issue by rrubio** [strapi/strapi#3591]
Installing GraphQL via Marketplace or command line, the following error occurs:

`
debug ⛔️ Server wasn't able to start properly.
`
`
error GraphQLError: Syntax Error: Unexpected single quote character ('), did you mean to use a double quote (")?
`

**Comment by rrubio** [comment]
Update - i'm getting the same error using Strapi v3.0.0-beta.10.

**Comment by derrickmehaffy** [comment]
@rrubio Please update your original issue following the bug report template, I have included a copy of it below.

In order to keep the github issues clear and concise with required information for troubleshooting and reproducing these templates are required. For now I will mark this as closed, after you have edited your original post to follow the template this issue can be reopened.

Thank you

Template: ```


**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
