### ISSUE TITLE
Rerender problem edit component in content manager

### ISSUE THREAD

**Issue by ozanmanav** [strapi/strapi#3593]
**Describe the bug**
Re-rendering content manager edit component three times.

**Steps to reproduce the behavior**
Create new content type and put console log to strapi-plugin-content-manager/admin/src/components/edit/renderAttr

It's rendering three times every page loading.

**Expected behavior**
Only one render  when page is loading

**Screenshots**
![image](https://user-images.githubusercontent.com/19241756/60954717-2528af80-a308-11e9-8330-52e5944a4dc2.png)
 
**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.9
- Database: SQLite
- Operating system: MacOS

**Comment by lauriejim** [comment]
@soupette is the guy for your!

**Comment by soupette** [comment]
@ozanmanav I am currently aware of the issue and it's actually due to the `strapi-admin/admin/src/containers/admin` component. I have a HoC there: `injectHooks` that is causing this container to be rendered 2 times... Therefore it impacts all the children. I am planning to improve the `strapi-admin` package in order to get rid of these rerender problems.
