### ISSUE TITLE
Unable to set zh_Hans language as default value

### ISSUE THREAD

**Issue by fouber** [strapi/strapi#3596]
**Describe the bug**
Unable to set zh_Hans  language

**Steps to reproduce the behavior**
1. ![WX20190710-160304](https://user-images.githubusercontent.com/536297/60973543-115a6900-a35b-11e9-9643-c68a426d597a.png)
2. ![WX20190710-160242](https://user-images.githubusercontent.com/536297/60973568-19b2a400-a35b-11e9-8b10-054224a6edba.png)
3. ![WX20190710-160207](https://user-images.githubusercontent.com/536297/60973599-27682980-a35b-11e9-8747-be1b2b994530.png)
4. ![WX20190710-160148](https://user-images.githubusercontent.com/536297/60973617-2e8f3780-a35b-11e9-8f1c-91225cfa334c.png)

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.9
- Operating system: Mac OS

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

You will have to investigate on the plugin `settings-manager`.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
