### ISSUE TITLE
Customize admin panel on beta version

### ISSUE THREAD

**Issue by bntnam** [strapi/strapi#3604]
**Describe the topic**
Hello, I would like to customize the logo of Strapi and its background color. In the beta version, we do not have the `admin` folder anymore. As I read in the documentation, I can replace the logo image by passing the new one in this path `./admin/src/assets/images/logo-strapi.png`. However, I don't see a way to change its color background. Does anyone have an idea? Thanks in advance!

**Your suggestions for this topic**
Would you mind if I make a PR to update the documentation for beta version when I have a solution? So it would help beginners really much.

**Comment by derrickmehaffy** [comment]
@bntnam In the future please use the bug report or direct questions like this to the slack but since you offered to update the documentation related to modifying the adminUI you can see an example where I did just that in my own project: https://github.com/canonn-science/CAPIv2-Strapi/blob/development/admin/src/components/LeftMenuHeader/styles.scss

and the example image: 
![image](https://user-images.githubusercontent.com/8593673/61062661-7a6dcb00-a3b3-11e9-9ac3-6ed0b861cdc2.png)

When you want to modify a file you can just follow the same structure as you saw in the docs here: https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#logo

In that you are replacing the files that would normally be in `node_modules/strapi-admin/admin/src` and directing them to `admin/src/some/file/path`

**Comment by bntnam** [comment]
> @bntnam In the future please use the bug report or direct questions like this to the slack but since you offered to update the documentation related to modifying the adminUI you can see an example where I did just that in my own project: https://github.com/canonn-science/CAPIv2-Strapi/blob/development/admin/src/components/LeftMenuHeader/styles.scss
> 
> and the example image:
> ![image](https://user-images.githubusercontent.com/8593673/61062661-7a6dcb00-a3b3-11e9-9ac3-6ed0b861cdc2.png)
> 
> When you want to modify a file you can just follow the same structure as you saw in the docs here: https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#logo
> 
> In that you are replacing the files that would normally be in `node_modules/strapi-admin/admin/src` and directing them to `admin/src/some/file/path`

Thank you! :)
