### ISSUE TITLE
Extend the Social Auth Providers API for React Native

### ISSUE THREAD

**Issue by isabellachen** [strapi/strapi#3636]
**Describe the topic**
I'm trying to achieve authorization with Strapi with Facebook login in React Native. Using the FB login with fbsdk, I  get the user to log in, and on success, pass the credentials to my app. The problem I have now is storing this credentials with Strapi. I could [manually register](https://strapi.io/documentation/3.0.0-beta.x/guides/authentication.html#registration) users with the Strapi API, but then I would have to make up a password for each user and deal with two tokens, one from Facebook and one from Strapi.

**Your suggestions for this topic**
I would like to know if there is a way of extending the current Providers API so I can store the user information from Facebook in Strapi directly without going through this extra step of registering users manually? 

**Additional context**
I would also like to know if there is recommended way of achieving authentication with Facebook in React Native with Strapi...

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

---

In additional note this question has to be post on StackOverflow instead of GitHub.
We are trying to keep GitHub issues for Issues mainly and some Feature Request.
Use the tag `strapi` in your StackOverflow question, it will ping on the community Slack.
And please reference the strapi version you use.
