### ISSUE TITLE
Edit Strapi Title Tag Text in beta

### ISSUE THREAD

**Issue by humbertoT2** [strapi/strapi#3642]
In alpha versions there used to be a file in .admin/src/containers/PluginPage/index.js

In this file, on line 49 and 50, there was this variable for the page title

```
<Helmet
         title={`Strapi - ${pluginName}`} />
```

I edited this file to look like this:

```
<Helmet
         title={`Custom Site Name - ${pluginName}`} />
```

How can I acheive this edit in beta versions to change the the title? Here is a screengrab to show what I mean:

![Image of Strapi title](https://i.ibb.co/nLh0PNN/Screen-Shot-2019-07-18-at-5-33-38-PM.png)

**Comment by soupette** [comment]
@humbertoT2 in order to apply the same modifications as in the alpha, follow these steps:

1. copy and place the content of the [HomePage](https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src/containers/HomePage) in `my-app/admin/src/containers/HomePage/index.js` and change this [line](https://github.com/strapi/strapi/blob/117656c05f93f1d6d3bde868e149465136a680cb/packages/strapi-admin/admin/src/containers/HomePage/index.js#L188) to `<Helmet title="My Custom Page " />`.

2. Copy and place the the content of the [PluginDispatcher](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/PluginDispatcher/index.js) in
`my-app/admin/src/containers/PluginDispatcher/index.js` and change this [line](https://github.com/strapi/strapi/blob/117656c05f93f1d6d3bde868e149465136a680cb/packages/strapi-admin/admin/src/containers/PluginDispatcher/index.js#L47)  to
```
<Helmet title={`My Custom Site - ${name}`} /> 
```

**Comment by humbertoT2** [comment]
@soupette Thank you, this works! Is there a similar solution to override "strapi-plugins" like users-permissions, namely the assets, for the logo in AuthPage container? I'd like to override the strapi logo when a user or admin goes to login.

**Comment by soupette** [comment]
Well currently you can override any file that is the **`./admin`** folder so changing the logo of the AuthContainer will be difficult. The only way I see to do that is to change the login page to another container that will be located inside the admin. In order to do that you will need to add a new route in the Admin container with the same URL as the login page. 

Since the `Switch` component matches the first the container it will override the current one.
