### ISSUE TITLE
npm outdated not working correctly with strapi

### ISSUE THREAD

**Issue by dominikg** [strapi/strapi#3645]
**Describe the bug**
latest tag in npm regsitry is not consistent accross strapi packages and does not point to current beta.
```
 npm outdated
Package                                   Current         Wanted           Latest  
strapi                              3.0.0-beta.13  3.0.0-beta.13            1.6.4  
strapi-admin                        3.0.0-beta.13  3.0.0-beta.13  3.0.0-alpha.4.3  
strapi-hook-mongoose                3.0.0-beta.13  3.0.0-beta.13   3.0.0-alpha.13  
strapi-plugin-content-manager       3.0.0-beta.13  3.0.0-beta.13  3.0.0-alpha.4.3  
strapi-plugin-content-type-builder  3.0.0-beta.13  3.0.0-beta.13    3.0.0-alpha.6  
strapi-plugin-email                 3.0.0-beta.13  3.0.0-beta.13            0.0.0  
strapi-plugin-settings-manager      3.0.0-beta.13  3.0.0-beta.13    3.0.0-alpha.5  
strapi-plugin-upload                3.0.0-beta.13  3.0.0-beta.13            0.0.0  
strapi-plugin-users-permissions     3.0.0-beta.13  3.0.0-beta.13    3.0.0-alpha.7  
strapi-utils                        3.0.0-beta.13  3.0.0-beta.13            2.0.0  
```

**Steps to reproduce the behavior**
run `npm outdated`

**Expected behavior**
As of writing, beta.13 should be recognized as latest version and packages with that version not show up in output of `npm outdated`

After release of beta.14 the outdated packages should be recognized and show up with beta.14 as latest available version

**Comment by derrickmehaffy** [comment]
@dominikg I believe right now latest is not used until strapi goes into a stable release, for now you will need to add in the `@beta` on all packages (not that npm audit can typically give you the wrong releases also such as `@next` which should not be used.)

**Comment by derrickmehaffy** [comment]
@dominikg I've talked with the Strapi team related to this:

1) Those plugins should have had a `0.0.0` release made into latest instead of the version when they were created
2) There is still a stable version of Strapi (although no longer maintained) that is still in use aka Strapi v1 hence why the packages are not pushed into latest as the Strapi v3 versions are not "stable" in the way that most developers think of the latest tag as being stable releases.

Until Strapi releases a stable build there is no plans to push versions into that tag, for now I am marking this one as closed.
