### ISSUE TITLE
No option to hide content types in admin

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#3678]
**Describe the bug**
There is no option to hide the content types in admin panel in latest version of strapi. It was in alpha and i have choosed content types which i want to show and write them in layout.js file but now there is nothing like it and i cannot do it.

**Steps to reproduce the behavior**
Open strapi and you can see all content types

**Expected behavior**
I expected a layout file or some option in admin in which i can choose content types which i want to show in admin.

**Screenshots**
  NONE

**Code snippets**
 NONE

**System**
- Node.js version: v10.15.3
- NPM version: 6.10.1
- Strapi version: 3.0.0-beta.13
- Database: MongoDB
- Operating system: Ubuntu 17.04

**Comment by lauriejim** [comment]
@Aurelsicoko and @soupette can you give me an insight into that. I have some doubts.

**Comment by soupette** [comment]
@lauriejim in the alpha it used to be a `layout.js` file in which you could define the content types to be displayed. This option was removed in the `beta`. In order to achieve the same version with the beta you will need to modify the following [file](https://github.com/strapi/strapi/blob/53d0014dc29adea54d7d33cb74d2e4184c0cb230/packages/strapi-plugin-content-manager/controllers/ContentTypes.js#L9-L47) if it's extendable (@alexandrebodin) to manually set the displayed content types.

Although, I do not recommend this method.

**Comment by lauriejim** [comment]
@soupette The code you send will be available after the merge of `develop` branch.
For the current version of strapi you will have to update [this function](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/controllers/ContentManager.js#L10)
So create `extensions/content-manager/controllers/ContentManager.js` file and in this files add the following code.
```js
'use strict';

module.exports = {
  models: async ctx => {
    const pluginsStore = strapi.store({
      environment: '',
      type: 'plugin',
      name: 'content-manager',
    });

    const models = await pluginsStore.get({ key: 'schema' });

    // here is to delete the product API
    delete models.models.product;

    ctx.body = {
      models,
    };
  },
};
```
