### ISSUE TITLE
Can't add new entries for the new deployed types

### ISSUE THREAD

**Issue by yassinebridi** [strapi/strapi#3683]
**Describe the bug**
After updating the deployed version with new types. i can access the other types, but can't access the new added ones

**Expected behavior**
To be able to create content for the new added types

**Screenshots**
the entry page just keep loading:
https://storage.googleapis.com/openscreenshot/r/G/u/Bkb3ZWuGr.png

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.10
- Database: Postgres
- Operating system: Kubuntu 18:10

**Additional context**
- Deployed to Heroku

**Comment by derrickmehaffy** [comment]
@yassinebridi please delete the key `plugin_content-manager_schema` in the table/collection called `core_store` in your database manually and "restart" the Strapi server. It is a well known issue and a fix is being worked on that will be released with the repeat fields feature.

This is a temporary work around until the fix is released. Likewise you can delete that entry and export/import that key from your local development database also.
