### ISSUE TITLE
Can't override plugin's lifeCycle functions

### ISSUE THREAD

**Issue by nealrs** [strapi/strapi#3693]
**Describe the bug**

After creating a new user via the content-manager, the `afterCreate` hook fails to execute. (Other hooks fail as well)

**Steps to reproduce the behavior**

1. Create a new, confirmed user from [content manager](http://localhost:1337/admin/plugins/content-manager/user?_limit=10&_page=1&_sort=_id&source=users-permissions)
2. Look for console output confirm hook ran / didn't run: `console.log('afterCreate hook, user: ${model}')`

**Expected behavior**

After creating a new user, strapi should execute the afterCreate hook, enabling us to send welcome emails & to complete other _new user_  provisioning tasks.

**Code snippets**

path: `extensions/users-permissions/models/User.js`

```
'use strict';

module.exports = {
  afterCreate: async (model, result) => {
    console.info(`afterCreate hook, user: ${model}`);
    // send welcome email using user's email address
  },
  afterSave: async (model, result) => {
    console.info(`afterSave hook`);
  },
  afterUpdate: async (model, result) => {
    console.info(`afterUpdate hook`);
  }
};
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.2
- Database: MongoDB via Atlas
- Operating system: MacOS High Sierra, 10.13.6

**Additional context**

This routine / approach worked with a previous (1.X) version of strapi. We followed the [plugin migration guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html#migrating-plugins) and are able to create new users, but these hooks never fire.

**Comment by lauriejim** [comment]
Hello @nealrs!
Thank you for reporting this issue.
I updated the title to match with the exact issue we are facing.

If you create a file `extensions/users-permissions/models/User.js` it completely overrides the **User** model definition and you will lose your attributes and will not be able to start the server.

If you have `extensions/users-permissions/models/User.settings.json` it will override the model definition (that's good) but it also overrides the `extensions/users-permissions/models/User.js` content.

So you can't have these 2 files at the same time.
We have to fix it to merge these two files instead of overriding them.

The workaround is when you have finished update the **User** model (and the relation creation) you can copy all the `extensions/users-permissions/models/User.settings.json` keys in `extensions/users-permissions/models/User.js`. You manually merge stuff and then remove `extensions/users-permissions/models/User.settings.json` file.
But be careful, if you update the **User** model via the content type builder, it will create an `extensions/users-permissions/models/User.seetings.json` file and it will re-override your `extensions/users-permissions/models/User.js` file that contains your lifeCycle function.

**Comment by nealrs** [comment]
Thanks @lauriejim, can you show me a simple example of this approach? 

I understand that I need to merge the entire JSON settings object from the extension file `/User.settings.json` into my `/Users.js` -- but I don't understand how, since one is a simple object, and the other is purely function definitions.

Should it be within the `module.exports` as a new function or generally as a new `const settings = {}` outside of the export.  Is there some other settings / type definition I need to import?

**Comment by nealrs** [comment]
Thanks @lauriejim, I think I've got this working on my end now.

**Comment by derrickmehaffy** [comment]
Closing this and linking it to the master Review Lifecycles Issue: https://github.com/strapi/strapi/issues/1443

It will be reviewed with all the rest of the Lifecycle issues. Thank you!
