### ISSUE TITLE
strapi generate:model creates extra model folder

### ISSUE THREAD

**Issue by mtmsuhail** [strapi/strapi#3694]
**Describe the bug**
while running CLI command "strapi generate:model category --api product" it generate model folder inside api/product/model

**Steps to reproduce the behavior**
1. Go to strapi CLI 
2. Run strapi generate:model category --api product to generate new model inside existing product api

**Expected behavior**
ignore creating new model folder if existing already

**System**
- Node.js version: v10.15.3
- NPM version:6.4.1
- Strapi version: 3.0.0-beta.14
- Database: MongoDB
- Operating system: Windows 10

**Additional context**

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue.
Can you please investigate this issue and submit a PR to fix it.
Will appreciate your contribution!

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

The code that generates models is here: https://github.com/strapi/strapi/tree/master/packages/strapi-generate-model

**Comment by shabab477** [comment]
Can confirm this issue exists. When using the command `strapi generate:model category --api product` two model folders are created. This bug exists only when creating using the `api` option but otherwise doesn't create two `model` folders.

![strapi-with-bug](https://user-images.githubusercontent.com/16679067/64165354-bd559780-ce66-11e9-893f-46209e70bdf6.png)
