### ISSUE TITLE
Can not create role named "server"

### ISSUE THREAD

**Issue by daksamit** [strapi/strapi#3725]
**Describe the bug**
When we add user with strapi admin dashboard 

**Steps to reproduce the behavior**
1. Add new user, name it "server"
2. Add new role, name it also "server"
3. server role disappears.

**Expected behavior**
I'm not sure if it problem with "server" name or if we have user and role with the same name

**Screenshots**
I have 6 roles (3 are hidden [1 is named server and 2 are created with different name but I renamed id to server and dissapeared])
On the list we can see only 3

![image](https://user-images.githubusercontent.com/7165997/62427088-cd564c00-b6ed-11e9-9321-89f471284078.png)

when we add user we have many roles with the same name

![image](https://user-images.githubusercontent.com/7165997/62427109-26be7b00-b6ee-11e9-810f-3ad5875cae07.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.15.1
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.14
- Database: mongodb
- Operating system: linux mint 18.2 cinnamon

**Comment by daksamit** [comment]
I tested it on beta.13 with sqlite, and problem occurs at least with "server" role

**Comment by lauriejim** [comment]
Hello @daksamit !
Thank you for reporting this issue.

This issue is caused by this line of code:
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/admin/src/components/List/index.js#L100

I think it's an easy thing to fix.
I suggest @soupette to guide you to fix it by submitting a PR.
