### ISSUE TITLE
Register This username is already taken

### ISSUE THREAD

**Issue by cayrescript** [strapi/strapi#3757]
**Describe the bug**
Hey, I'm using users-permissions plugin and I rewrite my User model on extensions to remove `username` attribute, because I have no interest in this. I can create a first user with success, but from the second, i get error 'This username is already taken', The same happens at UI.
 

**Steps to reproduce the behavior**
POST /auth/local/register HTTP/1.1
Host: localhost:1337
Content-Type: application/json

{ "email": "foo@bar", "password": "blablalbal231sad" }

**Expected behavior**
Create a user.

**Screenshots**
![Captura de Tela 2019-08-09 às 15 58 38](https://user-images.githubusercontent.com/34864164/62802592-9d78c100-babe-11e9-997b-80eaa1801e31.png)

**Code snippets**
```
    { error: "Bad Request", message: "This username is already taken",  statusCode: 400 }
```

**System**
- Node.js version: ">= 10.0.0"
- NPM version: ">= 6.0.0"
- Strapi version: 3.0.0-beta.13
- Database: mongo
- Operating system: MacOS High Sierra

**Comment by lauriejim** [comment]
Hello! It's not so easy to remove this field.
The easier way if you don't need the username is to hide it instead of removing it. 

1. Go in the `content manager` in the left menu
2. Click on the `User` content type
3. Remove the `Username` from the List and the Edit view.

Then you will have to update the content type model to remove constraints from the `username` field

Please for that you will have to check how the **extensions** folder work.
**📚Documentation here:** https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions

And after you will have to find the path of the file you want to update.
It will be this one https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/models/User.settings.json
So you will have to copy this file at the same path in the extension folder.
It will be `./extensions/users-permissions/models/User.settings.json`
```
...
"attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "configurable": false
    },
    "email": {
...
```

In this file, you will have to remove `unique` and `required` constraints.

**Comment by m-emre-yalcin** [comment]
I solved this with overwriting register function in users-permissions/controllers/Auth.js
![image](https://user-images.githubusercontent.com/61562772/106359510-591d5880-6324-11eb-9268-b82673364660.png)
I generated unique username when user registered.
You can hide generated username for API responses in model json.
![image](https://user-images.githubusercontent.com/61562772/106359643-098b5c80-6325-11eb-89a8-7aded7405af7.png)

**Comment by AliMahmoud80** [comment]
For anyone who needs a solution to this issue and @m-emre-yalcin solution didn't work for him here is it.

you have to override the default **create()** action of the user controller (create one if you don't have)  which creates a new user,
and copy the whole **register()** function from `PROJECT_PATH/node_modules/users-permissions/controllers/Auth.js`
then paste it in the **user.js** controller as **create()** action and then we have to override the **username** value that comes from the request to a random unique string like @m-emre-yalcin solution but by adding this line of code straight before creating 
**parmas const**

like this

`
    // Override username with dummy random string for every new user. 
    ctx.request.body.username = Date.now() + crypto.randomBytes(8).toString('hex')

    const params = {
      ..._.omit(ctx.request.body, ['confirmed', 'confirmationToken', 'resetPasswordToken']),
      provider: 'local',
    };
    ......
`

so your PROJECT_PATH/extensions/users-permissions/controllers/user.js file should look like this.

https://gist.github.com/AliMahmoud80/297fbdfaf9a44f7abbfeaaca7a1ec7a6

**Comment by lorenz068** [comment]
Beware because there is a false error message. If username is required but not unique.
```
"unique": false,
"required": true
```
The error message is the same 
>"message": "Username already taken"
It should be username is required...?

**Comment by Quaice** [comment]
Even after removing the `unique` and `required` constraints I still get `username.notNull` error when trying to save changes for a user. Obviously hiding the field doesn't fix that issue.

**Comment by lack-of-gravitas** [comment]
Why the hell is this not in the official documentation and having to trawl through old Discord messages to find this issue?

**Comment by georgeiliadis91** [comment]
This issue is definitely still there.

**Comment by lack-of-gravitas** [comment]
bud there are massive concurrency management issues with Strapi frontend and the database writes that it performs. Given this + the lack of back support for older versions, we've switched away from recommending strapi to anyone... maybe in time it will mature

**Comment by sjoukedv** [comment]
I was also getting the `ApplicationError: username already exsists`. For me it had nothing to do with the username. Maybe this helps someone:

1. Enable debug in `database.js`

```
module.exports = ({ env }) => ({
    connection: {
      client: 'postgres',
      connection: {
        ...
      },
      debug: true,
    },
  });
   
   ```
   2. Hit the endpoint and manually execute the queries (the ones on the `up_users` table) to see which one fails.
 
 In my case the issue was the `up_users_id_seq` sequence which tried to insert an entry with an ID that already exists (due to importing rows). Updating the index `ALTER SEQUENCE up_users_id_seq RESTART with new_index;` fixed the issue
