### ISSUE TITLE
BuildMail package is unmaintained (To change ?)

### ISSUE THREAD

**Issue by t1gu1** [strapi/strapi#3761]
**Describe the topic**
As you can see BuildMail package is unmaintained
https://www.npmjs.com/package/buildmail

But that project seems used in strapi

**Your suggestions for this topic**
- Use an other library
- Fork the currect library and update packages 

**Additional context**
You can see it you you make a  `strapi new my-project`

**Comment by lauriejim** [comment]
Helo!
Thank you for reporting this.
This is due to `strapi-provider-email-sendmail` > `sendmail` > `mailcomposer` > `buildmail`
But form now it's not critical, there is other email provider you can use. And I suggest you to use an other one to let you connect to an email provider to send emails.
I close the issue, we will not manage all dep deps since it's not a first level dependency.

**Comment by t1gu1** [comment]
Just keep in mind that old or deprecated package, in a project, could cause some security issues. 👨🏿‍💻
