### ISSUE TITLE
Link to plugin documentation not translatable

### ISSUE THREAD

**Issue by chiliec** [strapi/strapi#3774]
**Describe the bug**
Link to plugin documentation settings not translatable.

**Steps to reproduce the behavior**
1. Go to admin
2. Change to random language
3. See that link to **Documentation** not changed

**Expected behavior**
Link must be translated to selected language.

**Screenshots**
<img width="219" alt="Screenshot 2019-08-12 at 00 55 27" src="https://user-images.githubusercontent.com/982358/62893921-0e410700-bd65-11e9-9505-adc09f4086c6.png">

**System**
- Node.js version: v12.7.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.15
- Database: SQLite
- Operating system: macOS Mojave 10.14.6

**Comment by lauriejim** [comment]
Thank you for reporting this point.
For now some plugin's name translations are managed in `strapi-admin`
We have to make sure all translation are well separate and well managed.

@soupette is the guy to contact if you want to work on a fix for this issue.
We will not work on this point right now. It's a low priority.

Feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by chiliec** [comment]
@soupette can you show some link(s) related to this issue? I want to resolve this, but don't know how to start :)

**Comment by soupette** [comment]
@chiliec you need to submit a PR with your language and the translations updated.

Here's the [CONTRIBUTING GUIDE](https://github.com/strapi/strapi) to get started. In order to add a new language (or edit one) you need to translate all the `en.json` files located in all the packages that have an admin folder.

Here are the path of those packages
- `./strapi/packages/strapi-admin/admin/src/translations/en.json`
- `./strapi/packages/strapi-plugin-<plugin-name>/admin/src/translations/en.json`

If you are adding a new language you need to modify all the plugin's `translations/index.js` files as well as the [i18n one](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/i18n.js).

Good luck!
