### ISSUE TITLE
Unable to edit Strapi favicon or titles

### ISSUE THREAD

**Issue by DanWebb** [strapi/strapi#3813]
**Describe the bug**
It's not possible to edit favicon or meta titles.

**Steps to reproduce the behavior**
1. Change the favicon path settings at `/config/application.json` like suggested here https://strapi.io/documentation/3.0.0-beta.x/configurations/configurations.html#application
2. Watch nothing change

OR

1. Replace the favicon.ico in any folder
2. Watch nothing change

**Expected behavior**
It to be possible to override favicon and titles globally

**System**
- Node.js version: 12.6.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.14
- Database: Postgres
- Operating system: MacOS Mojave 10.14.5

**Additional context**

I’ve tried...
- adding a favicon to the root, public and admin directories and modified the config at /config/application.json.
- Completely rebuilding strapi (deleting .cache and build folders)
- Refreshing cache, trying incognito
- Editing the favicon settings in middleware.json instead of application.json
- Trying to override the favicon middleware with a custom middleware

The thing won't budge 😅

**Comment by soupette** [comment]
Well the custom process of the administration is a bite complex I have to agree, but what is currently possible is to replace any file located in the admin folder. With this in mind, if you take a look at the files architecture of the [strapi-admin](https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src) you will be able to change the favicon by adding yours in **`./my-app/admin/src/<my-favico>`**

Then you can just run `strapi build` and the favicon will be changed.

Regarding the titles it is a bit more complex since it is handled in multiple different files. It is handled by the [PluginDispatcher](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/PluginDispatcher/index.js) and the [HomePage](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/HomePage/index.js). The homepage has been updated so I suggest you to wait for the groups and repeatable fields release before modifying this specific component.

**Comment by DanWebb** [comment]
Thanks for your reply @soupette and the extra info on titles.

Unfortunately, adding the favicon to that directory isn't working either, I mentioned I tried adding it to the root, public and admin directories.

Does adding a custom favicon to the admin/src directory work for you?

**Comment by soupette** [comment]
Delete your build folder and your .cache one and restart your app. Make sure to put your icon in this 

folder : `./my-app/admin/src/<my-favico>`

**Comment by DanWebb** [comment]
I also mentioned deleting those folders in my original post.

Does following those steps work for you? I'm asking so I can narrow it down to a specific issue with something in my environment or build, rather than simply an issue with Strapi.

**Comment by soupette** [comment]
You are right it wasn't working in fact the favicon is injected by webpack the only workaround I found was to directly replace the file in the `./build` folder. 


<img width="246" alt="Screenshot 2019-08-22 at 14 57 39" src="https://user-images.githubusercontent.com/13311463/63516458-33fca780-c4ed-11e9-8ff9-318d7f1f2285.png">
