### ISSUE TITLE
Is it possible to set connection in a hook?

### ISSUE THREAD

**Issue by chris-makaio** [strapi/strapi#3816]
**Describe the topic**
In our use case we want to share the same model based on an attribute (say, "site") across multiple databases. Because we're using SQLite this allows us to use git to deploy the site-specific data independently from the "central" database.
I think something similar is described in #3147

**Your suggestions for this topic**
The doc says

> The connection value can be changed whenever you want, but you should be aware that there is no automatic data migration process. Also if the new connection doesn't use the same ORM you will have to rewrite your queries.

So this sounds good. But where's the place to change the connection in a "per REST request" manner?
And I think we might run into trouble when directly changing the model's connection as it is not really "thread safe" like

get /specificData/siteA
specificData's .connection is now siteAconnection
data is read async
but now another get for a different site comes in, thus changing the model's connection while it is still in use by the first request

I should add that we'll have 50+ sites, so having a model like siteA-specificData, siteB-specificData is not really smart ;)

Urgh, hopefully this is understandable

**Comment by derrickmehaffy** [comment]
I understand what you are trying to do and no it's not a good idea to switch that connection. Your best bet would be to do as you mentioned and run each site separately. The feature you are looking is called multi-tenant and it hasn't been added yet

I would also like to mention that SQLite is not really for production usage. I'm mentioning this as a warning and I would suggest you migrate to a real database such as MySQL or Postgres.

On this note however this issue isn't really a bug report or feature request and discussion topic is more geared towards collaboration prior to an RFC being written on a feature or change.

Due to the previous statement I'm marking this issue as closed.
