### ISSUE TITLE
Getting stuck 

### ISSUE THREAD

**Issue by sinh117801** [strapi/strapi#3827]
**Describe the bug**
Getting stuck when create data to content

**Steps to reproduce the behavior**
1. Go to Any content type like the screenshoot 'Categories'
2. Click on 'Add Category'
4. And the spinner is stuck like that.

**Screenshots**
![Screen Shot 2019-08-23 at 1 58 01 PM](https://user-images.githubusercontent.com/43696715/63572940-47237c00-c5ae-11e9-9cb3-2ada29b23cbf.png)

**System**
- Node.js version: 10.16.2 LTS
- NPM version:
- Strapi version:  Strapi v3.0.0-beta.15
- Database: MongoDB
- Operating system: Heroku

**Comment by derrickmehaffy** [comment]
Delete the following key: `plugin_content-manager_schema` in the table/collection `core_store` in your database and restart the server. It's a known issue with a fix that will be released in beta.16.

I'm marking this issue as closed as it will be fixed with this PR: https://github.com/strapi/strapi/pull/3664

**Comment by sinh117801** [comment]
ok thanks
