### ISSUE TITLE
a problem about Multiple types

### ISSUE THREAD

**Issue by Taffyw** [strapi/strapi#383]
Hello, I would like to ask if we support the multilevel type type>child. In addition, in the management background, the prompt information is English, can it be modified to English, is it locales or JSON react component tag text? Thank you!

**Node.js version**: 8.2.0
**npm version**: 5.3.0
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: osx 10.13.1

**Comment by soupette** [comment]
Hello @Taffyw!

If your question refers to the admin languages we actually use `react-intl` to handle internationalization : https://github.com/yahoo/react-intl. 
The way it works is that every plugin (including the admin) has a `translations` folder located in `/admin/src/translations` each folder currently contains two languages `en.json` `fr.json` and the front-end uses `FormattedMessage` (https://github.com/yahoo/react-intl/wiki/Components#formattedmessage) to which we give the translation key.

So, in order to add a new language to your app you'll need to :

1. Add the new language locale : 
 For example if you'd like to add german as another language
 **Path -** `my-app/admin/src/config/languages.json`
 ```
 {
   "languages": ["en", "fr", "de"]
 }
 ```
2. Create the `de.json` file in each plugin that contains the exact same keys located in `en.json` with the translated text.

3. Manually rebuild each plugin (for example: `cd plugins/settings-manager && npm run build` ) and also the admin.

Also I don't completely understand what you mean by "if we support the multilevel type type>child.", could you be more specific?

Thanks
