### ISSUE TITLE
Policies not executed in admin panel.

### ISSUE THREAD

**Issue by kuccilim** [strapi/strapi#3853]
**Describe the bug**
When add new content in admin panel, policies are not executed.

**Steps to reproduce the behavior**
1. Create a new Content Type "book".
2. Add new policies `isExecuted.js` to path `api/book/config/policies`
```javascript
'use strict';
module.exports = async (ctx, next) => {
  console.log('In policy.');
  await next();
};
```
3. Update `api/book/config/routes.json`
```json
{
      "method": "POST",
      "path": "/books",
      "handler": "Book.create",
      "config": {
        "policies": [
          "isExecuted"
         ]
      }
}
```
2. Add new "book" in admin panel.
3. Policies `isExecuted` not executed.

**Expected behavior**
It should log `In policy`.

**System**
- Node.js version: v10.16.3
- NPM version: v6.9.0
- Strapi version: 3.0.0-beta.15
- Database: postgre
- Operating system: MAC OS

**Additional context**
The policies is working when using api `http://localhost:1337/books` with Postman.

**Comment by soupette** [comment]
@kuccilim the content manager uses custom endpoints instead of the generated apis' ones.

So in order to executed a policy in this plugin you need:

## 1. Create a policy, it can be a global one using the cli:

```
strapi generate:policy isExecuted
```
The generated policy would be the following:

```
'use strict';

/**
 * `isExecuted` policy.
 */

module.exports = async (ctx, next) => {
  // Add your own logic here.
  console.log('In isExecuted policy.');

  await next();
};
```

## 2. Extend the content manager plugin:

- Inside the extension folder create the `./my-app/extensions/content-manager/config/routes.json` file and copy the content of this [file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/config/routes.json)
- Then apply the `isExecuted` policy to the `/explorer/:model` endpoint:
```
// ...
{
  "method": "POST",
  "path": "/explorer/:model",
  "handler": "ContentManager.create",
  "config": {
    "policies": ["routing", "global.isExecuted"]
  }
},
// ...
```

It should then be working.

**Comment by kuccilim** [comment]
I had successfully executed the `isExecuted` policy, but it is apply to all model right now, can it assign to desire model/route only?

For example, only apply to content type `Book` and in the `PUT`,`POST` method.

Or I have to get the `ctx.params.model == 'book'` and apply the logic?

Thanks.

**Comment by soupette** [comment]
Yes apply the Logic for the book params

**Comment by kuccilim** [comment]
Thanks, I will close this issue now.
