### ISSUE TITLE
WYSIWYG field type

### ISSUE THREAD

**Issue by gluxon** [strapi/strapi#396]
Is there interest from the maintainers for a WYSIWYG field type? We have the text field type at the moment, but it doesn't provide rich text capabilities. A WYSIWYG would be helpful for content editors on my team.

As far as implementation goes, CKEditor 5 might be an easy way to integrate this. https://ckeditor.com/ckeditor-5-builds/#classic

I can work on this a bit if the maintainers think this would be a good addition.

**Comment by Aurelsicoko** [comment]
Sure, we would love to add a WYSIWYG in the Edit view. However, we didn't consider it as a proper type but more like an option to check in the Advanced Settings of the Text type.

If you want to work on this part, can you join the [Slack](https://slack.strapi.io/) and ping me (@aureliengeorget) in DM. I have screens to share with you.

**Comment by gluxon** [comment]
Glad to hear. That sounds like a better idea that making WYSIWYG its own type. I'll reach out on Slack.

**Comment by erwstout** [comment]
Hey gang, whats the status on this? This would be the one thing keeping me from pitching this to my boss as one of our new CMS systems as we are looking to switch to something headless. Appreciate the work - been playing around and I love it so far .

**Comment by Aurelsicoko** [comment]
@erwstout We are working with @gluxon on it! Then, it will be one of our priority in the next weeks. I can give you a date but it should be available in March/April. We need to develop the Upload feature first and make the project more stable first. Feel free to vote on the [Community page](https://strapi.io/vote)!

I'm closing this issue because we're already considering it and it's one of our top priority.

**Comment by gauravarora91** [comment]
Why adding wysiwyg is such a big task ? Anyone able to figure out how to do it ? I think it's the first thing a CMS should have support for.

**Comment by Aurelsicoko** [comment]
@gauravarora91 We are not a CMS. We want to create an ecosystem to build any kinds of APIs (Content, Product, Service, Real-time, ...). So, you can use Strapi as an headless-CMS or as a Node.js framework with a dashboard, etc.

It's not such a big task but right now we are focusing our effort on the Upload feature and fixing the issues. The rich text editor support is our next step.

Don't forget it's an open-source project and we are giving 100% of our time to the community. I know that many people are waiting for the WYSIWYG support but please don't tell us what we should do and how to do it...

**Comment by gauravarora91** [comment]
@Aurelsicoko I don't want to argue with you, it's open source work, thanks for your time and contributions. Take this as a feedback if you guys can.

WSYWIG should not be a shipped feature as people would want to use their own stuff, people working with React.JS want their own WSYWIG, while jQuery people need something else or some might be familiar with TinyMCE or similar.

Problem is I spent lot of time figuring out how one can customise admin interface or add custom field to Strapi by creating a new plugin, which seems like a impossible task. Everyone is looking for a Wordpress/PHP alternative for Node.js, maybe that's not your goal, you want this to be more of framework rather than a CMS, but these are basic things, one example in documentation is more than enough. People will start creating their own plugins and publishing stuff. 

Thanks!

**Comment by Aurelsicoko** [comment]
> Everyone is looking for a Wordpress/PHP alternative for Node.js [...]

You've perfectly defined our vision. We know that and I will publish a blog post this week to explain our way of thinking and what's coming next. You've highlighted an important point, it's too complicated to create a plugin right now and the current plugins (we could name them the "core plugins") are not extensible enough. However, we're still in alpha and we can still change many things to improve the product.

Thank you for your feedback, I really appreciate when the discussion is constructive 👍

**Comment by paulintrognon** [comment]
> @gauravarora91 We are not a CMS.

I don't really get how you want to become the Wordpress alternative for Node.js while not being a CMS, isn't Wordpress a CMS?

The absence of the wysiwyg is a no-go for me right now, but I love what you have done so far, and can't wait for the stable release :slightly_smiling_face:

**Comment by lauriejim** [comment]
This PR will be merge in few days https://github.com/strapi/strapi/pull/831

**Comment by Aurelsicoko** [comment]
@paulintrognon CMS means Content Management System. We don't like the word **Content** and **System** because it means that you stuck in a **system** and you can only manage **content**. 

We have a different approach. We are designing Strapi as an ecosystem based on a **framework** to manage **data**. It means that we're returning raw data (JSON) and you can customise the backend as you want. Almost everything can be disabled or customised.

You can use Strapi as a CMS but it's only a way to use it. There are different usages. You can also use Strapi as an API to serve a mobile app, etc.

When we started developing Strapi, we were looking for a simple way to create API (whatever the usage) with an administration panel in JavaScript. Something like WordPress without the imposed content-type (Articles, Comments, Pages, Tags, etc) which only return data not pages.

Btw, the WYSIWIG is going to be released!

**Comment by paulintrognon** [comment]
OK thanks a lot for that clarification, can't wait for that next release ;)

**Comment by matiasbenedetto** [comment]
Hello, any news about the WYSIWYG editor? Im not sure if the editor is ready. I installed Strapi 3.0.0-Alpha14 and the rich text editor is nowhere.

**Comment by soupette** [comment]
@matiasbenedetto you need to go in the advanced tab of the text field in the `content-type-builder` plugin

**Comment by Knovour** [comment]
Is it possible to have a rich text editor version?

**Comment by Aurelsicoko** [comment]
@Knovour Please give us more insight on our public roadmap (https://portal.productboard.com/strapi/c/37-wysiwyg-html-editor)
