### ISSUE TITLE
How does strapi run in cluster mode?

### ISSUE THREAD

**Issue by fouber** [strapi/strapi#3976]
I did not find any explanation of cluster mode in the documentation and code, and I also reported an error when starting multiple instances using pm2, I did not know how to run a strapi instance of cluster mode. I wonder if strapi can run multiple processes based on the number of cpus

**Comment by kindziora** [comment]
Hi @fouber maybe this way: http://pm2.keymetrics.io/docs/usage/cluster-mode/

**Comment by fouber** [comment]
@kindziora strapi startup by ``npm run start``. it can not be started by pm2 cluster mode

**Comment by derrickmehaffy** [comment]
Create a server.js file:
```
#!/usr/bin/env node
'use strict';

// Start Strapi
const strapi = require('strapi');
strapi().start();
```

Run in cluster mode: `pm2 start --name="mystrapiapp" server.js -i 2`

You can change the `-i` to the number of instances (CPU cores you have on the machine is usually the safest bet in which case `-i max`)

**Comment by derrickmehaffy** [comment]
Marking this issue as closed as clustering does work and is fairly simple to implement (I've been doing it for the better part of a year and a half now). If you have questions please do feel free to ask.

**Comment by derrickmehaffy** [comment]
@fouber I disagree simply because Strapi's documentation really can't handle every possible way to run the application. There are at least 4 or 5 ways to run as a PM2 cluster (some without a server.js) and the pm2 documentation as well as their github contains a lot of useful information.

Overloading the documentation is almost as bad as not having enough information. For every part of the documentation that is added, it must also be maintained. And parts that are not under Strapi's control and development shouldn't be their responsibility to keep up to date. There are a few cases especially related to AWS related stuff and I have already seen this issue come up (heck even 2 weeks after the docs were added on it).

I personally believe promoting users to search for themselves (just as I did for pm2 docs).

**Comment by stanleyyuenyiu** [comment]
@derrickmehaffy In cluster mode

im facing the same issue for many people,

strapi needed to deploy docker/kubernetes,

there is no persistent storage at all, everything will be reset to docker image default when restart

so when user create a new content type,

it will generate code for the API,

but if somehow we restart the docker, everything are gone,

how do we solve?

**Comment by derrickmehaffy** [comment]
@stanleyyuenyiu open up an issue on the [docker repo](https://github.com/strapi/strapi-docker)

**Comment by markotitel** [comment]
Sorry for reviving the thread.
Running in cluster mode makes hard for Strapi to do database migrations because multiple processes are running at the same time leading to race conditions and errors.

Any advice on how to solve this?

**Comment by derrickmehaffy** [comment]
> Sorry for reviving the thread. Running in cluster mode makes hard for Strapi to do database migrations because multiple processes are running at the same time leading to race conditions and errors.
> 
> Any advice on how to solve this?

Start one node to let it run the migrations, then start the others
