### ISSUE TITLE
Groups relation field selected is not displayed in the Admin UI

### ISSUE THREAD

**Issue by rmaroun** [strapi/strapi#3999]
**Describe the bug**

**Steps to reproduce the behavior**
1. Create a group with a number field and a relation field
2. Add this newly created group as a repeatable group to a content type
3. Go to this content type page and create a new item
4. Fill in the content type fields and add multiple group items (add a number and select in the drop down a value for the relation)
5. Save the entry
6. You go back to the list view, click on the newly created item to go to the details page
7. go to the repeatable group and you will see that the number field has a value but that the relation field does not show up
8. go to http://localhost:1337/graphql and create a query to check if the data was saved
9. you will see that the value you selected in your relation field in persister in the db but just not visible in the admin UI

**Expected behavior**
The selected value in the repeatable group relation field should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/4890827/64914038-516b0d00-d74b-11e9-895a-85a85497c3e2.png)

**System**
- Node.js version: v12
- Strapi version: beta.16.3

**Comment by rmaroun** [comment]
When inspecting we can see that the data is retrieved but it seems that the dropdown field is not able to find it in the pre-loaded list of values that it fetches

![image](https://user-images.githubusercontent.com/4890827/64917344-9153e380-d78f-11e9-915b-76434c924585.png)

**Comment by derrickmehaffy** [comment]
@rmaroun can you please fill out the description and update the issue? Thank you 😃 

```
Describe the bug
A clear and concise description of what the bug is.
```

**Comment by soupette** [comment]
@rmaroun can you also specify your database?

**Comment by ralphMevision** [comment]
@soupette 
Bug description:
When selecting a value from a drop down for a relation field in a repeatable group and saving it then the selected value gets persisted but when we open the repeatable group the value that was selected is not visible in the dropdown. I can see that the selected value id is retrieved from the database but the dropdown value is empty. This is a critical bug as we cannot use repeatable groups that contain relation fields because we cannot see what we selected after we saved it.

Database: Mongodb 4.0.6
