### ISSUE TITLE
Modal UI should not close if mouseUp event outside of modal dialog

### ISSUE THREAD

**Issue by ceefour** [strapi/strapi#4000]
**Describe the bug**
Modal UI should not close if mouseUp event outside of modal dialog

**Steps to reproduce the behavior**
1. Go to Configurations > Environments > Database > edit a database
2. Hold/drag mouse from inside modal dialog
3. Move the mouse to outside modal and release

Modal dialog closes.

**Expected behavior**
Nothing happens, because it is not a click (i.e. a click means mouse is clicked outside of modal)

**System**
- Node.js version: 10.16.3
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.16.3
- Database: SQLite
- Operating system: Windows 10 1903

**Comment by lauriejim** [comment]
Hello, thank you for reporting this. We are currently on another feature and bug fix. 
Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

And I agree, this is frustrating when it happens.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by justinmeid** [comment]
Is this fixed? I am currently having the same issue

**Comment by kuczaQ** [comment]
This is absolutely INFURIATING!
Please fix this ridiculous behaviour!!! I am going absolutely mental trying to create content types!!!

And there is no apparent way to fix it myself without forking the repo! Please, get your stuff together...

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
