### ISSUE TITLE
Boolean field should set default as specified: null, false, or true

### ISSUE THREAD

**Issue by ceefour** [strapi/strapi#4059]
**Describe the bug**
strapi-plugin-content-manager: boolean field should set default (to false)

**Steps to reproduce the behavior**
1. Create content type with boolean field, set required to true, and default value is false
2. Create new content then save
3. See error: "field is required".
4. You can click false/off -- which is already default -- to save it properly

**Expected behavior**

Default is false, as intended by content type, so can immediately save.

**System**
- Node.js version: v10.16.3 
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.16.5 
- Database: MongoDB
- Operating system: Windows 10 1903

**Comment by websocket98765** [comment]
I disagree with the premise of this issue. Valid values in a database for boolean are `null` (unspecified), `false`, & `true`.  If a value is unspecified, it should correctly be `null` in the database. Only if the user sets the default as `false`, then Strapi should set its value to `false`. 

(Boolean as seen in Postico for Postgres.)
<img width="88" alt="bool" src="https://user-images.githubusercontent.com/41795874/65643287-dfaf8080-dfe0-11e9-95f8-d6dcf42463a9.png">

The real problem to be addressed is that the UI needs to be updated to properly show all possible states of a boolean in a database: `null` (unspecified), `false`, `true`. 

![boolean-states-dont-show-null](https://user-images.githubusercontent.com/41795874/65643772-23ef5080-dfe2-11e9-9c88-887da482b3f4.png)
(Strapi v3.0.0-beta.16.5 )

(Let me know if you want a new Github issue for this.)

**Comment by ceefour** [comment]
@websocket98765 I agree with you.

**Comment by derrickmehaffy** [comment]
I agree that it should be false by default. Null should not be a valid option as a Boolean is a binary value either 0 or 1. Once it crosses into the tri-state (null, false, true) it's no longer a true Boolean and is more in line with an enumeration value.

**Comment by talentedunicorn** [comment]
> @websocket98765 I agree with you.

Why do you agree with @websocket98765 on this?
In my experience boolean has always been a dual-state data type, i.e. either true/false, 0/1 etc... why introduce a third state? What is the advantage of breaking boolean field types here?

**Comment by websocket98765** [comment]
@talentedunicorn The point is to be able to accurately show the state of the field in the database and it is possible for it to be unspecified.

**Comment by talentedunicorn** [comment]
@websocket98765 when you define a field on Strapi as a boolean the description does not mention a `null` value. 
![image](https://user-images.githubusercontent.com/904501/65942178-558f6e00-e45f-11e9-8f29-9dedf9ead3c2.png)
What exactly is the need for a null value on a boolean field? I understand different databases have possibilities to allow null / UNKNOWN values but still what is the usecase for needing this kind of implementation?

**Comment by ceefour** [comment]
@talentedunicorn yes I agree this isn't the place to discuss pros & cons of null.

boolean can be true or false. A **nullable database column/field** though, may contain either null or a specific type. That's why you also have NULL vs empty string.

There are several cases where tri-state is useful, for example you want to store IoT lamp state, it can be on/true, off/false, or null, meaning perhaps you lost contact with the lamp. It *could* be off, but you're not sure, maybe the lamp is on but network is disconnected.

Either way, the decision to use null or not for a particular property is on the content type creator, not strapi's.

**Comment by derrickmehaffy** [comment]
@ceefour But in the example you listed enumeration is exactly what that is for:
on
off
unknown

But the link that @talentedunicorn gave is exactly my thoughts also. There is a lot wrong with storing null in a database (even if it supports it).

**Comment by ceefour** [comment]
@derrickmehaffy yes, there is that choice. and even so, enumeration can be not null or null. If we follow the logic that boolean property must not be null, then enumeration should be forced not null also, since if someone wants null in an enum, they can put "null" or "unknown" or "empty" as valid enum value.

Anyway, I agree that null has pros and cons but that depends on the creator, not strapi.

One downside of using enum (when stored as string) compared to boolean, is more data storage, which means more storage and cost for indexes, etc. Note: I am **not** advocating for nulls, I am just saying it's the creator's decision and that strapi just provide tool for it.

**Comment by derrickmehaffy** [comment]
As @websocket98765 pointed out to me previously null on enums does make sense (for a while I did think the same thing) So allowing null on what is effectively a string field with limited choices, it makes sense. (UI is a whole other thing there and how to properly handle it, and there is an issue open about it)

Data storage, yes you are right. But the choices made here do effect Strapi, as when validation becomes a thing (validation layer) Strapi will also have to handle this (not to mention basically designing a custom boolean UI element that doesn't follow what most people believe a boolean to be) and making sure 3rd party plugin developers are aware and use this element. 

I largely disagree that booleans should have the option for null values, if a user wanted that they would be more than welcome to fork the plugins and add that ability themselves, it's not something that Strapi should do imo.

**Comment by websocket98765** [comment]
It's possible to make everyone happy.

**Example UI below allows:**

1. Those who want it to default to `false` and require a value (`false`/`true`), can do so.
2. Those who expect Strapi to accurately show all possible DB states (null/false/true) + anyone who may want to allow a field to remain unset during initial entry, such as by a data entry person who needs to skip a field because they don't yet know the value, also can do so.

**Example UI:** 

![boolean-proposal](https://user-images.githubusercontent.com/41795874/66061759-9bb40280-e52f-11e9-918e-caf04633b539.png)

UI toggle is easy enough to create. I can update it when the new admin contribution code is available, as it will be quicker for me to do at that time.

**Behavior:** 

Click `false` or `true` and that value is selected, deselecting the opposite. Click on an already-selected value and it unselects.

**Content Type Builder:**

![set-default-as-smaller](https://user-images.githubusercontent.com/41795874/66061780-a5d60100-e52f-11e9-8488-98b7e8c03930.png)
(Note the default value dropdown is disabled unless 'set default as' is checked, but disabling it is a 'nice to have', not a 'must have'.)

or 

![default-to-smaller](https://user-images.githubusercontent.com/41795874/66061795-ad95a580-e52f-11e9-8f42-92eff4d6ee7e.png)


- For those want the #1 behavior listed at the top of this comment, simply set `default as false` and `is required`. 
- For those who want the #2 behavior, don't set a default and don't set as required.
- In both cases, Strapi can now accurately display all possible DB values.

**Comment by Aurelsicoko** [comment]
@websocket98765 I agree with you. Having a null value is not the right definition. It's more like an initialization state.  And your proposal introduces it really well. 

- By default, a boolean field could have a default value set to **true**, **false** or **none-initialized** (which means null).
- Once, you interact with the field, you **can only select true or false**, and **you cannot reset the field to a null value** because it doesn't make sense. It's a boolean. If you need to have 3 states, you need to use the enumeration field, not the boolean.

I would love to see your proposal implemented, can you make a PR?

**Comment by lauriejim** [comment]
Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by websocket98765** [comment]
@Aurelsicoko I'll PR the InputToggle. But I'm not familiar with Content Type Builder, will let someone more familiar with it add that.

**Comment by soupette** [comment]
@Aurelsicoko @websocket98765 this option has been added in the content type builder with the `beta.18` release.

![Screenshot 2019-12-19 at 16 05 18](https://user-images.githubusercontent.com/13311463/71184047-68088f00-2279-11ea-836d-5dd35b0fb26b.png)


So can close this issue?

**Comment by websocket98765** [comment]
@soupette I can't test this yet, until I get past [my beta 18.2 errors](https://github.com/strapi/strapi/issues/4780). The thing I want to confirm is if the UI boolean element still shows 'false' when the value coming from the DB is actually null. 

(Regarding the screenshot, I don't know if you'd be opposed to it, but I think a select option / downdown might be a more clear UX: 1.) (empty value), 2.) false, 3.) true. Just IMO on that though.)

**Comment by rodrigofeijao** [comment]
I've got the same issue as @blaasvaer but found out that it only happens on SQLite, if you use a Mysql/MariaDB instance, it will default to `false`. It looks like the default values don't work properly.

**Comment by davidwebster48** [comment]
This issue was also discussed [here](https://github.com/strapi/strapi/issues/13731), and a decision was made to treat it as a feature request.
