### ISSUE TITLE
create new project with mysql connection args

### ISSUE THREAD

**Issue by BrotherSymeon** [strapi/strapi#4074]
**Describe the bug**
I created a new strapi project using this command
`npx create-strapi-app inventory_api2 --dbclient=mysql --dbhost=127.0.0.1 --dbport=3306 --dbname=inventory --dbusername=root --dbpassword=password
`
but when i start it I cant get to the admin page. when i hit the admin url it just loads the index.html page

I tried it with
`yarn start`

and with
`npx strapi start`

what do you think? can you think of anything i might be doing wrong?

here is some output when i run it:

_[inventory_api2] npx strapi start                                                                                                                             13:22:24  ☁  master ☂ ⚡ ✭
[2019-09-22T17:22:40.590Z] info Time: Sun Sep 22 2019 13:22:40 GMT-0400 (Eastern Daylight Time)
[2019-09-22T17:22:40.593Z] info Launched in: 5582 ms
[2019-09-22T17:22:40.594Z] info Environment: development
[2019-09-22T17:22:40.594Z] info Process PID: 18618
[2019-09-22T17:22:40.594Z] info Version: 3.0.0-beta.16.5 (node v10.15.3)
[2019-09-22T17:22:40.595Z] info To shut down your server, press <CTRL> + C at any time_

Im sure its something i am doing but I just dont know what

**Comment by lauriejim** [comment]
Hello @BrotherSymeon !
When you create an application the admin panel is not built.
The displayed log say to run `yarn develop`.
This command start your application and build your admin panel if needed.
So I suggest you to run `yarn develop` instead of `yarn start`
You can read the command line interface documentation [here 📚 ](https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-new)
