### ISSUE TITLE
How to look up documents by a field other than _id?

### ISSUE THREAD

**Issue by amitschandillia** [strapi/strapi#4093]
I have simple table of posts with fields like `title`, `slug`, `body`, `excerpt`, etc. and relations such as `author`, `category`, `tags`, etc. I'm connecting to my Strapi documents via an Apollo Client that uses GraphQL to query the database.

Currently, I'm able to look up posts only by their `id`, whereas I wish to be able to do so by their `slug` (which I've defined as a unique field). Is there any way to achieve this? The Swagger document does offer an endpoint that does this:

`/posts/{slug}`

But I don't see `slug` as an available argument in the `post`/`posts` schemas.

**Describe the topic**
Database lookup by custom fields

**Your suggestions for this topic**
Give option to make a field searchable in Content Manager

**Screenshots**
![schema](https://user-images.githubusercontent.com/42805381/65575182-da284b00-df8c-11e9-8eb5-44cfd5df1caf.jpg)
![swagger](https://user-images.githubusercontent.com/42805381/65575268-0e037080-df8d-11e9-9773-99f099870526.jpg)

**Code snippets**
So, to illustrate further, this works:

```
{
  post(id: "5d8768ff3664b921043f1358"){
    title
  }
}
```
But this doesn't:

```
{
  post(slug: "first-post"){
    title
  }
}
```
But this endpoint works:

`https://dev.schandillia.com/posts/first-post`

**Comment by derrickmehaffy** [comment]
```
{
  posts(slug: "first-post"){
    title
  }
}
```

**Comment by derrickmehaffy** [comment]
https://dev.schandillia.com/posts?slug=first-post

**Comment by amitschandillia** [comment]
> ```
> {
>   posts(slug: "first-post"){
>     title
>   }
> }
> ```

Please read the question again. I've clearly said this doesn't work since `slug` isn't a valid argument in the schema generated by Strapi.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/65583887-e1236f00-df34-11e9-9164-80e9c59b2f8d.png)

your `post` is the same as doing https://dev.schandillia.com/posts/$ID which is using the `findOne` service and only accepts the ID. If you have created a custom option to allow for a slug instead of an ID then you need to modify the schema to do so on GraphQL else you need to use `posts` and not `post`

https://strapi.io/documentation/3.0.0-beta.x/guides/graphql.html#customise-the-graphql-schema

I'm marking this as closed as it is not an issue with Strapi itself and typically only bug reports, feature requests, and technical discussion prior to making an RFC is done via github issues. For other related questions please use [Slack](https://slack.strapi.io) or Stack Overflow

**Comment by derrickmehaffy** [comment]
(I've also tweaked the graphql query in https://github.com/strapi/strapi/issues/4093#issuecomment-534909014 which will work

**Comment by amitschandillia** [comment]
> (I've also tweaked the graphql query in [#4093 (comment)](https://github.com/strapi/strapi/issues/4093#issuecomment-534909014) which will work

Thank you. This is what I was looking for.

**Comment by derrickmehaffy** [comment]
For reference: https://strapi.io/documentation/3.0.0-beta.x/guides/graphql.html#configurations

**Comment by derrickmehaffy** [comment]
Scroll down a bit and you will see the `where: {}` stuff
