### ISSUE TITLE
Content type builder always remove "autoPopulate" options in models

### ISSUE THREAD

**Issue by karnadii** [strapi/strapi#4150]
**Describe the bug**
Content type builder always remove "autoPopulate" options in models

**Steps to reproduce the behavior**
1. create many to many relationship with 2 models
2. edit model setting to disable autoPopulate by adding `"autoPopulate": false`
3. add some field in one of model using content type builder. and save it.
4. see the different using `git diff`
```
-    "chapters": {
-      "collection": "chapter",
-      "via": "novel",
-      "autoPopulate": false
-    },


+    "chapters": {
+      "collection": "chapter",
+      "via": "novel"
+    },

```

**Expected behavior**
dont remove edited custom model while using content type builder

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.9.1
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.16.1 
- Database: mongodb
- Operating system: ubuntu

**Additional context**

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

I suggest you check how the plugin `content-type-builder` work to let you fix this issue.
Thank you for your time.

**Comment by meinvolk** [comment]
I will look into this one.
