### ISSUE TITLE
Enumerables don't allow list items with non-alphanumeric characters

### ISSUE THREAD

**Issue by kylestephens** [strapi/strapi#4250]
**Describe the bug**
Enumerables don't allow list items with non-alphanumeric characters.
Perhaps this is the desired behavior? If it is, the error label needs to be updated as it currently states:
### Values should not start with a number or a special character.

**Steps to reproduce the behavior**
1. Go to 'Content Type Builder'
2. Click on 'a content Type'
3. Click on 'Add Another Field'
4. Click 'Enumeration'
5. Add a value with a hypen ('-') to the values with field, e.g. "kebab-case"
6. Click done
7. See error

**Expected behavior**
String with hyphen should be accepted if the string doesn't begin with the hyphen OR
Error should indicate to user that hyphen is not an acceptable character.

**Screenshots**
![Strapi-Issue](https://user-images.githubusercontent.com/5707924/66766327-bf6b3700-eea5-11e9-9d7c-397cb1387cd0.png)

**Comment by derrickmehaffy** [comment]
@kylestephens please include the required part of the bug report template:

```
**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:
```

**Comment by derrickmehaffy** [comment]
However in this case you are correct that special characters are not supported in an enum mainly due to graphql not supporting them.

https://graphql.github.io/graphql-spec/June2018/#sec-Punctuators
https://graphql.github.io/graphql-spec/June2018/#sec-Names

Specifically: `/[_A-Za-z][_0-9A-Za-z]*/`

In your case you should use `user_clock`, `graduation_cap`, and `calendar_alt`

Closing as this is an upstream package issue that cannot be directly resolved by Strapi, these limits are put in place due to GraphQL even if you aren't using GraphQL to ensure there are no issues if you choose to install the GraphQL plugin.

**Comment by derrickmehaffy** [comment]
I've submitted a PR to clarify the message provided in the admin

**Comment by kylestephens** [comment]
> I've submitted a PR to clarify the message provided in the admin

This seems like the best resolution for now, given the upstream limitations. Thanks! :)
