### ISSUE TITLE
Filtering on polymorphic relations

### ISSUE THREAD

**Issue by Bienio** [strapi/strapi#4254]
**Describe the bug**
I can’t filter records by the available media. Have error.
`Error: ER_BAD_FIELD_ERROR: Unknown column 'upload_file_1.related' in 'on clause'`

**Expected behavior**
i wan't get records with media

**Code snippets**
_Model posts_
```
{
    "connection": "default",
    "collectionName": "posts",
    "info": {
        "name": "posts",
        "description": ""
    },
    "options": {
        "increments": true,
        "timestamps": [
            "created_at",
            "updated_at"
        ],
        "comment": ""
    },
    "attributes": {
        "title": {
            "type": "string"
        },
        "gallery": {
            "collection": "file",
            "via": "related",
            "plugin": "upload"
        }

    }
}
```
_Example request_
```
getPostsWithGallery: async ()=>{
    return await strapi.services.posts.find({'gallery_null': false});
}
```

**System**
- Node.js version: v10.16.1
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.16.8 
- Database: mysql
- Operating system: MacOS

**Comment by lauriejim** [comment]
Hello @Bienio !
The `media` type is a polymorphic relation.
This type of relationship does not allow deep filtering with this kind of relation.

It will be the same with groups. You will not be able to find an entry that has a specific group value.

**Comment by AntoninBeaufort** [comment]
I think it's an important feature since Strapi add groups and repeatables fields, Strapi's team should add a sentence like "Be careful, actually Strapi can't let you use filter on groups and repeatable fields".

My only workaround for now and to be futurproof when Strapi will support this feature is the pure SQL solution with LEFT OUTER JOIN etc... With this solution I don't have to change my data model (content type, groups, etc...)

Same problem here : [https://github.com/strapi/strapi/issues/4254](https://github.com/strapi/strapi/issues/4254)

**Comment by alastair-todd** [comment]
@lauriejim is a dynamic zone also a polymorphic relation so I cannot oob search content in there?

**Comment by derrickmehaffy** [comment]
We currently do not plan to add native support for this at this time.

Marking as closed as discussed with @Aurelsicoko
