### ISSUE TITLE
Add basic password strength requirements to endpoints

### ISSUE THREAD

**Issue by Palgie** [strapi/strapi#4304]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I think it would be sensible to add basic password strength checks to the default user creation endpoints and / or allow this to be configurable.

Users on my platform would currently be able to register their accounts with a password of one character with no minimum requirements.

Looking at previous issues (https://github.com/strapi/strapi/issues/1785) password length seems to have previously existed but currently not seeing this behaviour in 3.0.0-beta.16.8.

**Comment by lauriejim** [comment]
Hello @Palgie !
Thank you for this issue.

In fact, the password min length is configurable by using the [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html).
By updating the [User model](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/models/User.settings.json#L29). 
You will be able to configure the `minLength` of the password.

But this will impact the admin panel only. We still need to review the validation layout on the back end.

I created the issue that explains the issue here https://github.com/strapi/strapi/issues/4324

I will close this issue cause related to this issue.

Thank you.
