### ISSUE TITLE
jwt.json in .gitignore ?

### ISSUE THREAD

**Issue by kolomu** [strapi/strapi#4375]
**Describe the topic**
Hello I just started a new strapi project. I wanted to use versioning on github for this project.
I looked over every file strapi-cli created and there was a "jwt.json" file in extensions/users-permissions/config

Is it safe to commit this file? There is a `jwtSecret` and I am not sure if this should be public.

**Your suggestions for this topic**
Add jwt.json to the gitignore file.

**Comment by derrickmehaffy** [comment]
@kolomu generally you would need to restrict access to this as your own level just like the database.json such as setting it via an environment variable:

```
{
  "jwtSecret": "${process.env.JWT_SECRET}"
}
```

As this file is needed for Strapi to work (and the code shouldn't be changed as it will fail to validate any existing JWT due to the encryption key no longer working) adding it to the .gitignore may mean that some users will lose their key each time they redeploy. If a user wanted to add it to their gitignore themselves then no problem but Strapi itself shouldn't dictate that.

For now marking this as closed, but if you think it should be reopened for any reason let me know.
