### ISSUE TITLE
Debugging strapi plugins and admin ui

### ISSUE THREAD

**Issue by dakuenjery** [strapi/strapi#445]
How can I debug strapi plugin and admin ui? Is it possible? I tried insert '--inspect-brk' in npm start command. I catch init breakpoint, but I cannot debug after the app starts up.

p.s. Now the start command looks like this: "start": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node --inspect-brk ./node_modules/strapi-helper-plugin/lib/server",

**Comment by soupette** [comment]
Hi @dakuenjery! To debug the admin you need to start your project in development mode. You should check out the [Contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) for informations.

**Comment by dakuenjery** [comment]
Yes. But I cannot set breakpoints. It's inactive and not working. (In vs code if this is important)

**Comment by soupette** [comment]
Are you sure you're on http://localhost:4000/admin/ ? I tried with the `debugger` and it seems to be working.

**Comment by dakuenjery** [comment]
Yes. I use http://localhost:4000/admin/ . Vs code version is 1.19.2

**Comment by monico-moreno** [comment]
Just curious as to why this was set to `status:wontfix` ??? 

Was this ever resolved? 

I am currently trying to step into the strapi/strapi-admin code and it just seems to hang.  

Any insight is greatly appreciated.

**Comment by jmchza** [comment]
Yes it will be really great to get this cleared out as people can contribute to the admin panel too.
A guide matching the beta version might well be needed.

**Comment by soupette** [comment]
@jmchza currently debugging the `strapi-helper-plugin` from a generated project is not possible... However if I find some time I can check what we could do about it but we are in process of deprecating most of the components from this package by replacing them with [Buffet.js](https://buffetjs.io/storybook/?path=/story/get-started--welcome) our new components library designed essentially for Strapi's administration panel. Most of the plugins have already been migrated to this new lib and the future of the `helper-plugin` package will simply be a bridge between the plugins as it is the only "to make a plugin communicate with another one" (for instance the `GlobalContext`) is set in this `node_module` so all plugins can access the main `context`. 
So all this text to explain that in a short term the module will only be composed of `context`s and utils that are really targeted for the administration panel. I think that adding a debugging mode to the plugin with better error logs would be a great addition and we will make sure to catch the errors properly and display send to the console the full logs. 

On the other hand debugging this package is possible while developing with the [CONTRIBUTING](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) setup.

Until we tackle the debugging mode of the front-end here's how I would try to debug the errors coming from this particular package (I reckon that the process is not the most "friendly one..."):

1. Fork and clone the [strapi monorepo](https://github.com/strapi/strapi) 
2. Install all the dependencies `yarn setup`
3. Link all the dependencies of the monorepo `node scripts/link`
4. Activate the monorepo's watch mode `yarn watch`
> At this point any modifications made to the `strapi-helper-plugin` will be caused to plugin to be built.
5. Link the `strapi-helper-plugin` in your application:
```bash
$ cd my-app && yarn link strapi-helper-plugin
```
> Now you will be able to debug the package. 
6. Start your app with the front-end development command:
```bash
$ yarn develop --watch-admin
```

**Note 1**:
I highly suggest to avoid making modifications to the `node_modules` as you will to install the one from your `fork` because they will impact the other plugins.

**Note 2**:
If you really need to customise one of the file of this package I strongly suggest to make a copy of the component/util that you want to edit in your application and change the import directly in your plugin's file.

**Comment by jmchza** [comment]
For those who are after the info in this ticket @soupette is right, you can debug it in this way, you only need to run a backend/API in a separate instance and from the strapi-admin from the strapi repo, you can debug the the admin code.

Thanks.
I will close this now.
