### ISSUE TITLE
Permission - How can we configure to secure data better with API Key and API Secret? 

### ISSUE THREAD

**Issue by thanhzusu** [strapi/strapi#4523]
**Describe the topic**
I'm currently using Strapi as my API server to manage my data. I also have three other parts which access to this server to get data such as a website, android app and ios app. There are some public data and some private data in my API server. For the private data, I can secure it by user-permission plugin. But I am wondering about my public data. I don't want who is outside of 3 parts website, android and ios app can access it. It means this public data can be accessed within my 3 parts.

**Your suggestions for this topic**
I tried to create a new role in user-permission plugin via admin website but I is still need an authentication mechanism.
I'm familiar with  AWS or other data-as-a-service. They are using API key and API secret to secure the data. I'm wondering whether we can do the same in Strapi?

**Screenshots**
![Untitled Diagram](https://user-images.githubusercontent.com/3895199/68825491-dbdcd800-06cc-11ea-87b4-1896dba09636.png)

**Comment by derrickmehaffy** [comment]
@thanhzusu you can modify the endpoints to be looking for specific keys passed in the request. Although this isn't exactly "secure" as anyone who can reverse engineer the app can extract those keys.

If the data is public I'm not sure what it matters on how it's accessed.

The above being said questions about usage of Strapi should be done on slack or asked in Stack overflow, due to that I'm going to go ahead and close this issue but you are welcome to keep up the discussion.

API keys is already a requested feature and is planned.

**Comment by derrickmehaffy** [comment]
https://portal.productboard.com/strapi/1-public-roadmap/c/40-api-access-token-with-permissions
