### ISSUE TITLE
roles.json

### ISSUE THREAD

**Issue by Amurmurmur** [strapi/strapi#455]
**Node.js version**:
**npm version**:
**Strapi version**: 3.7.3
**Operating system**: MacOSX High Sierra

Why do you store all the permissions in the roles.json file ? Is it safe from a security prospective?
Why not storing it in the MongoDB?

**Comment by lauriejim** [comment]
Hello @Amurmurmur thank you for this issue. 
We are actually moving it on MongoDB, it's will be available in few weeks.

**Comment by Aurelsicoko** [comment]
@Amurmurmur As Jim said, we are moving them in the database. It's not related to security issue but to scaling issue. We are iterating on the product and it was the easiest way to implement quickly the permissions system at first. Now, we are having enough feedback from the community, we figured out that it won't scale on large projects. 

We are trying to store the configurations as much as we can on JSON files in the server instead of the databases to remove unnecessary requests to the database. But sometimes, we have to go back and put some of them in the database.
