### ISSUE TITLE
Wrong error in startup when no database is running

### ISSUE THREAD

**Issue by SinoBoeckmann** [strapi/strapi#4589]
**Describe the bug**
When you want to start the app by "yarn strapi dev" the console says that some model is unable to register. But thats "somehow" not true in this case.
Because this appears (for me) when the database is not running and I try to start the app.

**Steps to reproduce the behavior**
1. Create a working strapi app (or starter app + postgres)
2. Create a Model (if no starter app)
3. Stop the app
4. Stop the postgres server
5. Try to start the app with "yarn strapi dev"

**Expected behavior**
A error message that says that the database server is may not running in this particular case.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: postgres
- Operating system: mac os 10.14.6

**Comment by lauriejim** [comment]
Hello @SinoBoeckmann! 
Thank you for reporting this point.

In fact, we only test the connection work on application creation.
If it fails at this time, we will display a message like "The database connection failed"

After that, you try to start your server and the app crash because Strapi can't register the [...] model.

We are not testing the connection to start your app faster.

We are displaying this `Error: connect ECONNREFUSED 127.0.0.1:5432` that tell your database connection doesn't work.

@Aurelsicoko and @alexandrebodin feedback is welcome.
