### ISSUE TITLE
Error: Cannot find module 'whatwg-fetch'

### ISSUE THREAD

**Issue by PaulMaly** [strapi/strapi#4681]
**Describe the bug**
`npx create-strapi-app my-project --quickstart` is completing with an error:

```
> strapi build "--no-optimization"
internal/modules/cjs/loader.js:626
    throw err;
    ^
Error: Cannot find module 'whatwg-fetch'
Require stack:
- /.../node_modules/strapi-admin/webpack.alias.js
- /.../node_modules/strapi-admin/webpack.config.js
- /.../node_modules/strapi-admin/index.js
- /.../node_modules/strapi/lib/commands/build.js
- /.../node_modules/strapi/bin/strapi.js
```

**Steps to reproduce the behavior**
1. Run `npx create-strapi-app my-project --quickstart` command

**Expected behavior**
Install Strapi and create a new project

**Screenshots**
**Code snippets**

**System**
- Node.js version: 12.4.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.8
- Database: sqlite3
- Operating system: MacOS 10.14.6

**Additional context**
Almost the same error was described in #3643

**Comment by lauriejim** [comment]
Hello! I just tried [(here a video)](https://www.loom.com/share/1ff83bcbecfa4efb8bff4ad5a288f4ed) and it works well.
Did you check on Google if the issue can come from a missing package in your computer.

**Comment by soupette** [comment]
@lauriejim should we close this issue?

**Comment by gustawdaniel** [comment]
I experienced the same issue during update strapi to version 

![Screenshot from 2021-03-15 21-58-14](https://user-images.githubusercontent.com/16663028/111220333-55464c80-85d9-11eb-9f13-f5755390b08f.png)


# Short answer

Check list of libraries:

https://github.com/strapi/strapi/blob/master/packages/strapi-admin/package.json

and remove these that you are using in new version and strapi in old. In my case:

```
yarn remove react
```

# Long logs from debug



How to fix:

```
rm -rf node_modules 
rm package-lock.json 
```

Check if all strapi versions are the same:

Then I experienced this error:

![Screenshot from 2021-03-15 21-59-38](https://user-images.githubusercontent.com/16663028/111220510-8f175300-85d9-11eb-8cf3-80a61251c440.png)

I checked

```
npm i --force
```

This provide to error:

```
Error: Module not found: Error: Can't resolve '@buffetjs/styles/webfonts/Lato-Black.woff2' in '/media/nvme/pro/ce/backend/.cache/admin/src/components/Fonts'
```

Finally even

```
git reset --hard
```

did not help me.

I have also other error:

```
Error: [BABEL]: Cannot find module 'babel-plugin-polyfill-corejs2'
```

when I installed I see

```
Error: [BABEL]: Cannot find module 'babel-plugin-polyfill-corejs3'
```

now there is no `babel-plugin-polyfill-regenerator`

then problem with `dom-helper`

https://github.com/doczjs/docz/issues/1102


Again:

```
rm -rf node_modules
rm package-lock.json
npm i
```

There is connected issue:

https://github.com/strapi/strapi/issues/9079

I checked if yarn instead of npm works and have error

![Screenshot from 2021-03-15 22-23-21](https://user-images.githubusercontent.com/16663028/111223032-e2d76b80-85dc-11eb-843b-fce8578c7914.png)

I installed `@fortawesome/react-fontawesome`, `draft-js`, and a lot of packages with problesm

Finally I found:

> https://github.com/strapi/strapi/blob/master/packages/strapi-admin/package.json

There is React 16, but I have react 17, I removed it and everytihg works again.
