### ISSUE TITLE
Handle mobile auth (Firebase, Apple sign in)

### ISSUE THREAD

**Issue by MarcWadai** [strapi/strapi#4719]
- [x] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
I want to handle mobile auth generating my own refresh and JWT token using Strapi. What is the best way to proceed to be well integrated in Strapi? 

**Your suggestions for this topic**

My workflow :
- User register using mobile sms auth on firebase, that return a token.
- The mobile send to strapi the token and we verify using Firebase API the integrity of this token.
- Once the integrity is verified. I want to generate a jwt and refresh token.
- After that the mobile will only be authenticated using the JWT token (that can be regenerated using the refresh token)
- Almost same process is done for apple sign in.

Is it possible to do this only with what strapi provide ? (users-permission plugin). Or should I integrate and make my own middleware/function to create this refresh token ?

Thanks in advance for your answer 💃

**Comment by taj-meltedmoon** [comment]
Is there any update regarding?

**Comment by derrickmehaffy** [comment]
Hello,

There is no update about this topic currently, we have a small team and other issues and features are currently a higher priority for us at the moment. When work starts on this issue or feature request you will see an update provided or a pull request linked to this thread.

Thank you and have a good day!

**Comment by groteck** [comment]
Maybe this will help to as an alternative solution for now or create a plugin.

https://medium.com/@lambrohan/integrating-firebase-auth-into-strapi-9ed106ce8dee
https://medium.com/@lambrohan/strapi-with-firebase-auth-owners-policy-f346a0457ffb
https://github.com/lambrohan/strapi-firebase-auth

**Comment by amogh-jrules** [comment]
> Maybe this will help to as an alternative solution for now or create a plugin.
> 
> https://medium.com/@lambrohan/integrating-firebase-auth-into-strapi-9ed106ce8dee
> https://medium.com/@lambrohan/strapi-with-firebase-auth-owners-policy-f346a0457ffb
> https://github.com/lambrohan/strapi-firebase-auth

@groteck, Thanks for the links, have you tried doing this method? I dont see how we will able to protect certain endpoints because this article doesnt ask for creation of "firebase user" role in the user-permissions plugin. Have you been able to do that?

**Comment by groteck** [comment]
No I didn't try, but I assume that this uses the external token auth so if login with a new one. It creates a new user?, not sure about how this work 100%, but I assume that since you use admin sdk you can just call https://firebase.google.com/docs/auth/admin/manage-users#create_a_user and create users on strapi sign up.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/refresh-token
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
