### ISSUE TITLE
Allow to pick date with 00 value

### ISSUE THREAD

**Issue by MartinPL** [strapi/strapi#4794]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Allow to pick date with 00 value. I have field with album released date, some don't have specific day or month.

**Comment by derrickmehaffy** [comment]
https://dev.mysql.com/doc/refman/8.0/en/datetime.html
https://www.postgresql.org/docs/9.1/datatype-datetime.html
https://docs.mongodb.com/manual/reference/method/Date/

Full zeroed dates is not something that most Databases support. Since you have created the request on the product board I will go ahead and close this.

Though in my opinion, it may be better for you to leave a null value instead of zero'ing out the date.

**Comment by MartinPL** [comment]
I mean something like DATE MySQL format (2016-00-00 or 2016-05-00)

**Comment by derrickmehaffy** [comment]
To MySQL those aren't valid dates and it would throw an error. (00 month doesn't exist, and 00 day also doesn't exist)

**Comment by derrickmehaffy** [comment]
As I mentioned your best bet is a NULL value (as in don't enter anything and don't mark it as required)
