### ISSUE TITLE
Cannot add new Content Types when in production environment

### ISSUE THREAD

**Issue by boberbober** [strapi/strapi#4798]
**Describe the bug**
Fresh strapi install using sqlite for the database. When running "yarn develop" or "yarn start" everything works fine. But when I try running with NODE_ENV=production there is no option to create new Content Types in the Content Type Builder section.

**Steps to reproduce the behavior**
1. Install strapi
2. Run with NODE_ENV=production
3. Create admin account
4. Try creating new Content Type

**Expected behavior**
There should be a button to create new Content Type but there isn't one.

**Screenshots**
<img width="1195" alt="Screen Shot 2019-12-23 at 14 37 14" src="https://user-images.githubusercontent.com/1340952/71340420-bbd4ea00-2591-11ea-89d2-2b0ddac31211.png">

**System**
- Node.js version: 10.16
- yarn version: 1.19
- Strapi version: 3.0.0-beta.18.2
- Database: sqlite
- Operating system: macOS Catalina and Ubuntu 18.04 same thing

**Comment by derrickmehaffy** [comment]
This is not a bug and is intended, as the CTB (Content-Type builder) saves model configurations to files doing so in production would require Strapi to restart and thus could potentially knock your production API offline. Along with the previous reason, strapi is also very much pushed as a scale able application which would mean these changes would not be replicated across any clustered configurations.

There is no current plans to allow for this, as well as no plans to move these model definitions into the database. The enforcement of using the proper environment for the proper task (Production, Staging, and Development) is something that has been pushed from day 1.

Due to the reasons I explained above I am going to mark this as closed but please do feel free to discuss.

**Comment by UnbrandedTech** [comment]
I just spent 3 days looking into why the stupid button wasn't showing up. you should add this to the docs somewhere!

**Comment by boyfunky** [comment]
currently facing this issue as well. How do i solve this?

**Comment by lauriejim** [comment]
If you run `NODE_ENV=production yarn develop` or `NODE_ENV=production yarn start` will not allow you to edit Content Types.
`yarn start` will not restart your app on Content Type update but you can update them
Run your application with `yarn develop` to have full access to the Conte Type Builder
