### ISSUE TITLE
Date set the previous day

### ISSUE THREAD

**Issue by piLeoni** [strapi/strapi#4844]
Sorry i reported this already but was close because i had not the last version.
Even by upgrading the problem persisted:

If i set a date, let's say April 1 2020, seems to be correctly set.
However, i open that content again, and it say march 31.
Seems to be always one day behind.

If that can be a timezone problem, I'm in Cambridge, Massachusetts.

Expected behavior
Getting the date set correctly.

System

Node.js version: v10.14.0
NPM version: 6.4.1
Strapi version: beta18.3
Database: sqlite
Operating system: Ubuntu 14.04.4 LTS
Additional context

**Comment by lauriejim** [comment]
Hello! I was not able to reproduce.
📺[here](https://www.loom.com/share/bae21aebdeae4350a85865c81561a70e) is a record of what I did.
And it works well.
I think, as you said, it can come from your database/computer timezone configuration.

**Comment by vks-pthibeault** [comment]
Experiencing the exact same behaviour with a mySQL database. Also using the latest version of Strapi. I'm in Montreal, Quebec, Canada (EST).

**Comment by lauriejim** [comment]
Can you please check the date that is sent in the request from the Admin Panel.
And log the SQL request that creates your entry.

**Comment by piLeoni** [comment]
Hi, I was asking for april 1th 2020, was correctly set.
But then from the content list i was reading march 31 and then opening the content again still march 31.
Where the logs are stored?
I can repeat.

**Comment by vks-pthibeault** [comment]
So creating a test post with today's date (2019-12-31), here's what I can find:

The form data attached to the PUT request is the following:
```
data: {"Status":"Published","Title":"TEST","Subtitle":"TEST","Content":"TEST","Link":"TEST","Date":"2019-12-31T17:00:00.000Z","Logo":null}
```

Enabling debugging in the database.json, I get the following logs in bash:
```
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'TEST',
    '2019-12-31',
    'TEST',
    'Published',
    'TEST',
    'TEST',
    2019-12-31T17:43:49.043Z,
    2019-12-31T17:43:49.043Z
  ],
  __knexQueryUid: '45181706-c19a-419d-ba97-bd1360747734',
  sql: 'insert into 'events' (`Content`, `Date`, `Link`, `Status`, `Subtitle`, `Title`, `created_at`, `updated_at`) values (?, ?, ?, ?, ?, ?, ?, ?)'
}
```

Finally, when checking in the database, the date that is inserted is 2019-12-31

However, contrary to @piLeoni, the date goes back by 1 day every time I access the post.

**Comment by vks-pthibeault** [comment]
I do believe it seems to have something to do with timezone. Running tests with a datetime field, I've noticed that saving the field with any time between 00:00 and 18:30 saves the correct date, whereas saving with 19:00 or later saves it with tomorrow's date.

Again, this seems to be taking place only in the Strapi UI, all the logs and the database keeping the correct date. Is there anywhere we can modify what timezone is being considered?

**Comment by derrickmehaffy** [comment]
@vks-pthibeault Strapi backend (and the database) deal strictly in UTC. The admin AFAIK uses whatever timezone is being provided from the browser (as it should)

**Comment by derrickmehaffy** [comment]
So I was attempting to test this between my local machine (Windows 10, UTC -7) and a remote MySQL database on my lan (which is set to UTC) using Chrome and Postman:

What I entered `2020/1/3 01:00:00`:
![test1](https://user-images.githubusercontent.com/8593673/71678787-40b6c500-2d43-11ea-88f5-8d05aafb365c.PNG)

What the database saves: `2020/1/3 08:00:00`:
![test2](https://user-images.githubusercontent.com/8593673/71678829-562bef00-2d43-11ea-8657-4a20af5d9b46.PNG)

Confirming my original set date is still correct:
![test3](https://user-images.githubusercontent.com/8593673/71678855-6217b100-2d43-11ea-8cc5-48c5a36be467.PNG)

As expected the REST API response is still +7 hours (Since I am -7 UTC):
![image (1)](https://user-images.githubusercontent.com/8593673/71678898-7d82bc00-2d43-11ea-8bdd-c4947ac2b2ad.png)

All of this is working exactly as intended, the adminUI does all the conversion from the users (client aka chrome) timezone to UTC which Strapi's backend handles only UTC as does the database. When you request the data it is still UTC and the client (AdminUI) converts it back to the users timezone.

**Comment by derrickmehaffy** [comment]
Do note that if you are working locally (say MySQL install on the same machine as you are working on Strapi) MySQL by default takes the system timezone (which is why you never ever ever change a servers timezone that is hosting a database, any DBA would smack you if you did 😆 ) You will need to change the setting in the database.json to reflect this as Strapi expects the database to respond in UTC.

https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#database
`timezone (string): Set the default behavior for local time. Default value: utc.`

Example from my own local lan MariaDB server:

![image (2)](https://user-images.githubusercontent.com/8593673/71679734-7fe61580-2d45-11ea-914a-aeb2cd97dbe9.png)

**Comment by piLeoni** [comment]
Actually the server i'm running strapi on is in the same room where i am, set on the same local zone as my computer.
The system time is "America/New_York".

Should I insert it in the database configurations like this?
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "sqlite",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",   
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",  
        "username": "${process.env.DATABASE_USERNAME || ''}",    
        "password": "${process.env.DATABASE_PASSWORD || ''}",    
        **"timezone":"America/New_York"**
},
      "options": {}
    }
  }
}

**Comment by vks-pthibeault** [comment]
So for me, the following seems to have fixed the problem with the date field. Note however that it creates an issue with the datetime field always saving 5 more hours into the future.

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 3306}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "timezone": "utc-5"
      },
      "options": {
        "useNullAsDefault": true,
        "debug": true
      }
    }
  }
}
```

**Comment by codeitbhanu** [comment]
Hi There,

Is there any options for Mongoose (MongoDB) timezone settings as well? So I can change the default utc to utc-2.

**Comment by abdonrd** [comment]
Any news here?

**Comment by lauriejim** [comment]
Based on [this comment](https://github.com/strapi/strapi/issues/4844#issuecomment-570263343) - it works as expected.

Should be a matted of configurations.
