### ISSUE TITLE
Simple SSL server to Strapi

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#4884]
**Describe the topic**
Strapi's core principles are just second to none, but it develops very very slowly. This simple thing like securing the server with SSL is just mundane but cause headaches when working with it. Since there are reasons why certain things are done, I'd suggest putting workarounds in documentation. Here is my discussion around this for those that may end up trying to do this.

**Your suggestions for this topic**
Make `SSL` work in a very simple way using a hook. This probably works on **Heroku** etc since it uses _koa-sslify_, that works with **Heroku**. 

**Code snippets**
 I wish this could just be documented in the docs for easier usage's sake. 

```js
const https = require('https');
const { readFileSync, existsSync } = require('fs');

const { default: enforceHttps } = require('koa-sslify');

module.exports = strapi => {
  const hook = {
    /**
     * Default options
     */

    defaults: {
      // config object
    },

    /**
     * Initialize the hook
     */

    async initialize () {
      const port = strapi.config.environments[strapi.config.environment].server.sslport || 1447;

      // Force HTTPS on all page
      strapi.app.use(enforceHttps({
        trustProtoHeader: true,
        port,
      }));

      // check if SSL certificate and key exists
      if (!existsSync('ssl/cert.crt')) {
        throw new Error(`Mendatory SSL certificate NOT FOUND! in "ssl/cert.crt"`);
      }

      if (!existsSync('ssl/cert.key')) {
        throw new Error(`Mendatory SSL certificate key NOT FOUND! in "ssl/cert.key"`);
      }

      const options = {
        key:  readFileSync('ssl/cert.key'),
        cert: readFileSync('ssl/cert.crt'),
      };

      strapi.server.ssl = https.createServer(options, strapi.app.callback()).listen(port, () => {
        console.info(`HTTPS Server at port: %o`, port);
      });
    },
  };

  return hook;
};

```

I saved the `ssl` server in server because I wanted to use it in graphql for `wss` subscriptions in strapi-plugin-graphql, where subscription server is created in index.js file as follows:

```js
      SubscriptionServer.create(
        {
            // ...
        },
        {
          server: strapi.server.ssl || strapi.server,
          path: strapi.plugins.graphql.config.endpoint,
        }
      );
```

I know Strapi team is saying they don't want ssl in Strapi coz of HTTP/2 blah blah, but I think at least documenting the workaround is something that needs to be done.

Hope this helps someone...

**Comment by emahuni** [comment]
Help yourselves if ended up in any of those issues
#4534 
#171
#1102

**Comment by derrickmehaffy** [comment]
@emahuni generally speaking the universal answer for Strapi is it doesn't handle SSL and expects you to offload that to something like Apache or Nginx (mainly for scaling out)

**Comment by emahuni** [comment]
@derrickmehaffy Yes I got that, but the problem is when trying to just do it without using a proxy. I know what you mean and have seen the discussion around it. I have no problem with what was said. Just that sometimes, people are getting into all sorts of issues just trying to implement simple SSL for situations where it's not possible to use any of that. I am in such a situation as well and thought this could help someone.

**Comment by emahuni** [comment]
You explained here https://github.com/strapi/strapi/issues/1102#issuecomment-431583629 quite well. The problem is a simple example and approach to the alternative, besides the fact that it's not a universal solution eg: #171, which is where I expanded from. The problem is it was locked out so had to create another issue.

**Comment by derrickmehaffy** [comment]
The general problem though is security risks in directly exposing node.js to the public internet (especially if someone inexperienced is running said node.js application as a root user) which is why it's typically frowned on. By all means I'm not against someone doing what you are now, but to be frank it doesn't scale and in my own personal opinion it's "the lazy mans" way of doing it. With the example of heroku, I honestly would never directly expose a heroku server to internet traffic and would throw it behind something else (I would never use heroku but that's besides the point).

In the case of docker, Traefik
In a typical VPS, Nginx
In some other container cloud serverless solution, I'm sure there are options to run some kind of proxy solution as well. (Apache, Nginx, HAProxy, Traefik, insert the literally hundreds of proxy applications)

The gains from using a proxy are simple scaling, in a VPS based solution you can run literally thousands of applications on a single server with a single proxy. I've also written 3 guides on how to very quickly and easily setup nginx.

As a side note, nginx on heroku is a thing (as it is on just about every major cloud): https://blog.codeship.com/how-to-deploy-nginx-on-heroku/

**Comment by emahuni** [comment]
>  I've also written 3 guides on how to very quickly and easily setup nginx.

can you put all links here for posterity

**Comment by derrickmehaffy** [comment]
Older Alpha Nginx guide (config should still be valid though removing the workaround for the admin security header): medium.com/@derrickmehaffy/using-strapi-in-production-with-https-717af82d1445

I've started writing part 2 of my guide on my blog (updated for the beta) but haven't published it yet, once I do finish it, I'll have it on my blog (part 1 is there): https://derrickmehaffy.com

The 3rd is my general sepal that I copy paste into the Strapi slack anytime someone asks about it generally I tweak the config based on the user's preferences but roughly this:
```
server {
# Listen HTTP
    listen 80;
    server_name api.domain.com;

# Else Redirect to HTTPS // API
    location / {
      return 301 https://$host$request_uri;
    }
}

server {
# Listen HTTPS
    listen 443 ssl;
    server_name api.domain.com;

# SSL Config
    ssl_certificate /path/to/your/ssl/cert
    ssl_certificate_key /path/to/your/ssl/key

# Proxy Config
    location / {
        proxy_pass http://localhost:1337;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
```

**Comment by derrickmehaffy** [comment]
To preface the above ^^^ I've been working with nginx at my day job for the better part of the past 7 years and in my hobbiest stuff for the past 10 years.

I've also been doing contract based work to help people deploy Strapi for the past year (~80 or so deployments outside my own)

**Comment by emahuni** [comment]
That's nice and helpful of you thanks Derrick (not a Strapi employee), you are a superstar!

**Comment by emahuni** [comment]
Can write one that's just simple without other things like 'MySQL', etc included. Something like I posted above. Just to make the server secure through a Nginx proxy.

**Comment by derrickmehaffy** [comment]
I mean on a VPS it's seriously just as simple as install'ing nginx, and adding a virtual host config like the one I posted above (would not be my recommended way of doing it but if you strip out the cloud and database specific stuff from my medium guide the rest still applies to just about any setup, likewise for just about any application that you need to proxy)

**Comment by derrickmehaffy** [comment]
That being said as well, if you google "nginx proxy node.js" you will get millions of responses, likewise for just about any proxy based application (traefik, Apache, Nginx, HAProxy, gobetween, speedify, envoy, goproxy, snapt, KEMP, Titanium, ect) 

The reason why you generally won't see these snippets in the docs is quite simply they aren't based on Strapi's source code, it's the same reason you don't see setup guides for install MySQL/PostgreSQL on the docs. Everyone's environment is different, their usecase different. Strapi doesn't want to "pick a way" to do things as to cut out any sort of "recommended" solution that they would have to support because it's in the docs.

This is exactly the same neutral policy that applies to frontend solutions, Strapi doesn't "pick sides" so to speak.

**Comment by emahuni** [comment]
yah I understand, just trim the unnecessary tid-bits for one you did already.

**Comment by derrickmehaffy** [comment]
I'll add that to my to-do list and try to create a proxy only based guide (which honestly part 2 on my blog is mainly going to be anyway, it's the reason I split it into 2 parts)

**Comment by derrickmehaffy** [comment]
I'm going to mark this one as closed as I have started to cover proxying in the documentation ( https://github.com/strapi/strapi/pull/5571 )

And more proxy based documentation is coming here shortly

**Comment by sandwitcherz** [comment]
Hello, to have SSL whith Strapi and Apache2, i have write a solution for who whants to do it here : [](https://forum.strapi.io/t/how-to-make-an-ssl-proxy-on-apache-server/2504/2
)
