### ISSUE TITLE
User Permission Plugin for MySQL

### ISSUE THREAD

**Issue by Mikeez** [strapi/strapi#4885]
**Describe the bug**
User Permission Plugin with MySQL fails to install or to install properly. 
First I get an error, but running npm develop seems to fix the problem until you get to the admin panel and the user role: Public 
has no Auth and the other plugins are not there...

**Steps to reproduce the behavior**
1. npx create-strapi-app my-project
2. Select and Complete Setting MySQL
3. npm develop
*ERROR *
`error Bootstrap function in plugin "users-permissions" failed`
3. npm develop

**Expected behavior**
Runs well on a different computer with the same settings. So I expect it to work... The user public should have all the permission categories.. but it is not there. Check the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/26636051/71706149-24517180-2db1-11ea-841b-5e1aecaf4725.png)

![image](https://user-images.githubusercontent.com/26636051/71706517-595ec380-2db3-11ea-9811-2ff26245c0f9.png)

**System**
- Node.js version: 13.5.0
- NPM version: 
- Strapi version: 3.0.0beta18.3
- Database: MySQL 8.0 with Native Password
- Operating system: Windows 10

**Extra**
I ran the same exact way with the same exact setting on my personal computer and it worked fine. There is legit no difference hence I am so confused.

**Comment by derrickmehaffy** [comment]
Nodejs 13 isn't supported as it is not an LTS version. You should either be using Node 10 or Node 12

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/71708424-878dd480-2dae-11ea-9f3e-e2bade613989.png)

https://nodejs.org/en/about/releases/

**Comment by Mikeez** [comment]
> ![image](https://user-images.githubusercontent.com/8593673/71708424-878dd480-2dae-11ea-9f3e-e2bade613989.png)
> 
> https://nodejs.org/en/about/releases/

I think the problem is with MySQL pool? And I ran it on my PC with version 13 and it worked well

**Comment by Mikeez** [comment]
I used a dump sql in the working laptop and imported it in the server running strapi and it works... however, I am getting lots of error when searching through members (I have 200)

**Comment by derrickmehaffy** [comment]
Duplicate issue, please see the fix in this comment: https://github.com/strapi/strapi/issues/2790#issuecomment-528955740

Typically you will see Tarn (Knex.js connection pool package) timeout errors when working with a very slow remote database or one setup with very aggressive connection timeouts.

**Comment by Mikeez** [comment]
What shall I do in this case?

**Comment by derrickmehaffy** [comment]
@Mikeez the comment I linked shows a possible fix (or that whole issue thread should provide you with more information)

I did however just spin up a Windows 10 Virtual Machine and tested all 3 of the major databases (MongoDB, MariaDB, and PostgreSQL) and could not reproduce the error. Either the issue is your MySQL server is setup with some very aggressive settings, your latency to the database is too high, or there is an issue with Knex and MySQL 8 which should be directed to Knex.js.

If you have the option, you could consider using MariaDB 10.4 stable in place of MySQL 8 as it is a drop in replacement.

**Comment by derrickmehaffy** [comment]
For reference Strapi performs automated testing on all commits and PRs however it uses TravisCI's default settings for mysql:

https://docs.travis-ci.com/user/database-setup/#mysql
https://github.com/strapi/strapi/blob/4f39e56152adda40026624d06e608796eca36874/.travis.yml#L3

Which in this case is MySQL 5.7

**Comment by santicros** [comment]
Hello. I had the same problem creating a new strapi app from scratch and also cloning an existing app. In a local environment I had no problem but in a DO droplet with Ubuntu + Node LTS + MySQL 8 always crashed after the start. 

The problem was that the rows of user-permissions_permissisions weren't created. I had to insert them from my development server and then everything worked.

Didn't see the fix @derrickmehaffy was saying. Will check that.

**Comment by derrickmehaffy** [comment]
@santicros most of the time I see this problem when it relates to MySQL 8 Specifically (in my case I tend to use MariaDB 10.4 which is a drop in replacement and is based on MySQL 8)

There have quite a few issues since version 8 was released and it's possible there could be some lingering issues relating to the knex ORM. However since we haven't found a solid way to reproduce this, we can't be sure exactly where the problem is.
