### ISSUE TITLE
Allow to create linked items on the fly

### ISSUE THREAD

**Issue by gastonbesada** [strapi/strapi#4948]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
It would be nice if you could create a linked item entry within the same item entry that contains a linked field, adding a button (+) to create a new linked item entry on the fly.

![image](https://user-images.githubusercontent.com/884940/71995777-d9ed4c00-3219-11ea-8e24-49bd280a3dd1.png)

1 - Add new linked entry item button. Autosave as a draft on click if some changes were made to the content or this is a new entry.

![image](https://user-images.githubusercontent.com/884940/71996005-3c464c80-321a-11ea-8ec1-f09d488846d7.png)

2 - Auto select the parent linked item
3 - First level only (?)
4 - Create a new entry
5 - Save to back to the parent item

![image](https://user-images.githubusercontent.com/884940/71996640-4f0d5100-321b-11ea-9316-e95bd1a9f8b4.png)

6 - Added the children linked item to the parent

I think this functionality depends on [Draft/publish state](https://portal.productboard.com/strapi/1-public-roadmap/c/60-draft-publish-state) supposing that you have changed some value of some field or it's a new item entry. The app should be able to autosave as a draft the content changed before allowing to exit the parent item entry edition to create a new children linked item. In the current approach, when you try to exit from a modified item, an alert message with "Are you sure you want to leave this page? All your modifications will be lost" appears. 

When back from the children linked to the parent item entry, the children linked item should be added to the parent item entry and autosave this as a draft item.

**Comment by lauriejim** [comment]
Hello @gastonbesada !
Thank you for all these details, it's appreciated.

I ping @Aurelsicoko about your feature request.

**Comment by Aurelsicoko** [comment]
Hey @gastonbesada,

Thank you for sharing this with us! I really like the idea, we definitely want to move in this direction too. Could you please open a new RFC on the [dedicated repository](https://github.com/strapi/rfcs)?

It will be easier for us to share our thoughts with you and the community.  

You're right on a point, is that we need to implement the Draft/Archive feature before doing it that way. We could also do it within a modal. It will avoid the user to move to another page and the context will stay the same. Going to another page also means that we need to inform the user what's the current context of that new sub-entry (e.g. category) creation because when it clicks on the Save button, the behavior will be different.

Whatever the UX solution, there is a common issue called the inception. You certainly know the movie, and it's exactly the same problem here. What happens if the user wants to create a new category on the fly, and the category itself has a relation with a tag that you can also create on the fly? This is the reason why we have to show to the user where it is?

Anyway, I more than open to talk about that topic. It's fascinating!

**Comment by lauriejim** [comment]
Thank you for your feedback. I let @gastonbesada open an RFC to talk about this topic and I close this issue.

**Comment by gastonbesada** [comment]
Thanks @lauriejim and @Aurelsicoko, I'm agree with you about the modal UX and inception issue. I'll create a new RFC soon.

**Comment by lauriejim** [comment]
Cool tanks!

**Comment by Gusterson** [comment]
Confusing to me that this issues is closed... I don't see how it is possible in Strapi right now? So is this issue not still open? Desperately need implementation on my project.

**Comment by kristijorgji** [comment]
Why is this closed? If it is fixed somewhere else please forward me the solution

**Comment by kristijorgji** [comment]
@gastonbesada What plugin are you using to see the category tree on the right side? I am interesting in adapting Strapi for blog cms as well please reply
