### ISSUE TITLE
Strapi server doesn't restart automatically after saving Content Type

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#4982]
I follow the instruction https://strapi.io/blog/building-a-static-website-using-gatsby-and-strapi/ and videos inside. 

**What is expected**

Video 3 about Content Types shows process:
- Create a Content Type, for example, _article_
- Add some Field to article
- Save Content Type.

After saving Strapi server will restart by itself, and we can see changes at the same moment.

**What I have in reality**

Version 1.

- Create a Content Type, for example, _article_
- Add several Fields to article: title, cover image, author
- Save Content Type.

After saving there is error message: smth was wrong.
Page reloading shows there is no new field added.

Version 2.

I add one field, save Content Type, reload page. 
There is no error message, but also there is no the field.

**What helped**

I add one field, save Content Type.
Go to terminal: restart server manually.
Reload admin page: the field is added to Content Type.
Now I can add second field. And restart server manually again.

=======

Strapi version: 3.0.0-beta.18.4 (node v12.14.0)

**Comment by mdledoux** [comment]
I just tried out Strapi for the first time last night (so also 3.0.0-beta.18.4, though I'm running on node v10.15.3), and have this same problem.
It seems that if I add a new content-type, that saves fine - all the fields show up immediately.
If I go back to add more fields later, they disappear as soon as I press the save button - but they do get added to the model (e.g., restaurant.settings.json), and when I restart the server, it updates the DB schema in my SQLite db, and they show up under Content-Types.

IT MAY BE THE CASE that this only happens when I've created a new content type, added content, and then later return to add more fields.  I'll have to test this theory out further later on today, but that should be enough details for insight into this problem.

**Comment by jbty** [comment]
I have the same issue with Strapi version: 3.0.0-beta.18.4 (node v10.18.1)

**Comment by jbty** [comment]
> I follow the instruction https://strapi.io/blog/building-a-static-website-using-gatsby-and-strapi/ and videos inside.
> 
> **What is expected**
> 
> Video 3 about Content Types shows process:
> 
> * Create a Content Type, for example, _article_
> * Add some Field to article
> * Save Content Type.
> 
> After saving Strapi server will restart by itself, and we can see changes at the same moment.
> 
> **What I have in reality**
> 
> Version 1.
> 
> * Create a Content Type, for example, _article_
> * Add several Fields to article: title, cover image, author
> * Save Content Type.
> 
> After saving there is error message: smth was wrong.
> Page reloading shows there is no new field added.
> 
> Version 2.
> 
> I add one field, save Content Type, reload page.
> There is no error message, but also there is no the field.
> 
> **What helped**
> 
> I add one field, save Content Type.
> Go to terminal: restart server manually.
> Reload admin page: the field is added to Content Type.
> Now I can add second field. And restart server manually again.
> 
> =======
> 
> Strapi version: 3.0.0-beta.18.4 (node v12.14.0)

After some researching on issues, I have found a temporary fix

In your package.json :

- "develop": "strapi develop", // delete this
+ "develop": "strapi develop --watch-admin", // replace with --watch-admin flags

**Comment by mdledoux** [comment]
@jbty  - thanks, that seemed to fix my issue for now.  Hopefully this will be properly @fixed in the final release.   I was actually using "yarn strapi start", and never even tried "...develop".  But after making that simple edit, it works fine using "yarn strapi develop".
  I do find it strange that the system needs to restart itself for schema changes like that,  but otherwise, I think strapi seems like a great tool to integrate any front-end technology.

**Comment by derrickmehaffy** [comment]
@mdledoux the `start` vs `develop` is intentional. Strapi saves model configurations in files which with node in order for those changes to be reflected in the running application node has to restart. Using the start command doesn't automatically restart (as doing so in a production or staging setting could cause downtime or an outage if something goes wrong). The `develop` command is the only one that allows for hot-reloading when certain files change.

I'm going to mark this issue as closed, do feel free to continue the discussion.

**Comment by mdledoux** [comment]
Hi @derrickmehaffy, thanks for the info.  I'm a bit confused though - based on what you're saying, that makes me think that Strapi would be a bad choice to use going forward, but maybe I need to think about this more.  Here's what I'm hearing:
1) I disocvered all of the model files last night - I'm following you so far.
2) I understand that you wouldn't want node restarting in production - makes perfect sense.
I guess what I'm getting caught up on is what sounds like a design choice - why is it the case that "node has to restart"?  Well....I'm sure there's a good reason and I don't need to know that.

But design aside, from a practical standpoint, it seems that what you are saying is that if Strapi is running in production, schemas can't be changed without a something kicking off a restart (presumably a manual restart).  Having experience with Drupal in a business and a university, the appeal of a CMS is that office staff and various non-technical people (non software/IT people) can make changes to content, and if granted permission, even create or modify content types - without getting developers involved.
So I guess what you're is that "office staff" can edit content all they want, but IT needs to get involved for adding new content types or modifying existing ones.  Am I right?

**Comment by mdledoux** [comment]
@derrickmehaffy - I think I'm all-in with Strapi!
As I was writing that last comment, I was reconsidering my initial thought that maybe I just wouldn't be able to use Strapi because of this.    "office staff" can still add or edit content - that is critical.  Now that I think of it, part of the appeal of Strapi is that all schema can easily be stored in code, unlike many other CMSes where schema is stored in databases (e.g., Drupal, WordPress, Joomla...).  This sounds like a hybrid between a typical CMS and a framework with a fancy ORM, where schema and schema changes are stored in code (like migrations in Django), which can be checked into a repo and applied.  The more I think of this, it almost sounds like a CMS I looked at which was a module for Django - it probably worked similarly.
I think I can get behind this idea - the more I think about it, it means content-type changes are managed by developers (the content-types are owned by the developer and not by the content managers), and I can make those changes all I want on my dev-server, and apply to production via a build system or some sort of CI/CD pipeline.  This way the schema of the production database is never different than what is on a developer's system.  I like this.  This is way simpler than Drupal.
