### ISSUE TITLE
Cannot create Content Type named Order with SQLite

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#4983]
**Describe the bug**
[sorry] –– unaware at which point and the cause, but the below error has started popping up with each server start. No context is provided. Perhaps someone knows how to dig deeper into this case?

**Screenshot**
![image](https://user-images.githubusercontent.com/11737572/72228966-2b2e7000-3579-11ea-92ef-a3daeda2abe5.png)

**Code snippets**
`package.json``
```javascript
  "dependencies": {
    "knex": "^0.20.7",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.18.4",
    "strapi-admin": "3.0.0-beta.18.4",
    "strapi-connector-bookshelf": "3.0.0-beta.18.4",
    "strapi-plugin-content-manager": "3.0.0-beta.18.4",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.4",
    "strapi-plugin-email": "3.0.0-beta.18.4",
    "strapi-plugin-graphql": "3.0.0-beta.18.4",
    "strapi-plugin-upload": "3.0.0-beta.18.4",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.4",
    "strapi-utils": "3.0.0-beta.18.4"
  },
```
**System**
- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: 18.4
- Database: Postgres
- Operating system: MacOS

**Comment by nCore** [comment]
@ScottAgirs I have the same problem right now. This is because 'order' word is SQL Syntax reserved word and probably you have it in one of your models. Please take a look. 

I did not fix my issue yet, but will try to update the status after that.

**Comment by ScottAgirs** [comment]
> @ScottAgirs I have the same problem right now. This is because 'order' word is SQL Syntax reserved word and probably you have it in one of your models. Please take a look.
> 
> I did not fix my issue yet, but will try to update the status after that.
> 
> EDIT: I just switched to MySQL DB and the problem is gone. This must be SQLite specific.

That explains it thank you.

@derrickmehaffy thank you for the link

**Comment by derrickmehaffy** [comment]
@ScottAgirs I'd recommend you stick to the "two word" naming system so something like `productOrders` or something like that. The new CTM does allow for spaces which would turn `Product Orders` into `product-orders` in the backend.

**Comment by lauriejim** [comment]
Thank you @ScottAgirs for reporting this issue.
Thanks @derrickmehaffy for opening the PR, I let you manage that with Alex.

**Comment by alexandrebodin** [comment]
Hi @ScottAgirs We made some changes recently and I am not able to reproduce it. Can you share or model json ?

**Comment by ScottAgirs** [comment]
@alexandrebodin I have updated as well - doesn't seem to be broken now. I believe this is resolved with the updates. Thanks! 🎉

**Comment by pablosichert** [comment]
Hey there, I just ran into the same issue. Upgrading to 3.0.0-beta.19.5 did not help.

<img width="697" alt="grafik" src="https://user-images.githubusercontent.com/4450694/78370736-57311e80-75c7-11ea-8607-df61e6197977.png">

Could you reopen this?

**Comment by alexandrebodin** [comment]
@pablosichert Can you add the `debug`: true option to the `database.default.options` config  and showw which SQL query provokes the error ?

**Comment by pablosichert** [comment]
Sure, the query in question is:

```SQL
INSERT INTO `action_actions` (id, action, order, created_at, updated_at) select `id`, `action`, `order`, `created_at`, `updated_at` from `tmp_action_actions`
```

**Comment by lauriejim** [comment]
Hello! I just tried to reproduce and I'm not able.
Fresh new app with `3.0.0-beta.19.5`
Here is what I did - https://www.loom.com/share/4cebaccdf156434aa33bba624e01c9e0

**Comment by pablosichert** [comment]
Thank you for the screencap! The bug occurs when a field name is changed to `order`, not when the collection is called `order`.

Some steps to reproduce:

<img width="746" alt="Bildschirmfoto 2020-04-08 um 16 15 24" src="https://user-images.githubusercontent.com/4450694/78795595-76f48800-79b5-11ea-8253-6a6ac8277ea9.png">

<img width="1354" alt="Bildschirmfoto 2020-04-08 um 16 19 39" src="https://user-images.githubusercontent.com/4450694/78795630-81168680-79b5-11ea-97bb-9c2626bce5c6.png">

<img width="1354" alt="Bildschirmfoto 2020-04-08 um 16 20 38" src="https://user-images.githubusercontent.com/4450694/78795696-94c1ed00-79b5-11ea-972a-dd49dab22507.png">

Save & restart server manually (otherwise the collection doesn't appear for me. Seems to be an unrelated bug).

<img width="1354" alt="Bildschirmfoto 2020-04-08 um 16 22 18" src="https://user-images.githubusercontent.com/4450694/78795653-870c6780-79b5-11ea-8569-a849bd36182b.png">

Save & observe server log:

<img width="746" alt="Bildschirmfoto 2020-04-08 um 16 23 12" src="https://user-images.githubusercontent.com/4450694/78795797-b7ec9c80-79b5-11ea-9370-1542de7dffef.png">

**Comment by alexandrebodin** [comment]
Hi indeed I think I know what the issue is. Going to create a fix for it right now ;)

**Comment by lauriejim** [comment]
Great thank you @alexandrebodin for the fix.
