### ISSUE TITLE
"Date" type picker doesn't let you pick year/decade

### ISSUE THREAD

**Issue by tannuxie** [strapi/strapi#4986]
**Describe the bug**
With the old datetime data type, the date picker let you "zoom out" from the "month/day" picker to pick year or even decade, which is very useful for the project I'm working on. Having to click dozens or hundreds of times to scroll back to a certain date is a pretty major inconvenience.

**Steps to reproduce the behavior**
Using latest version of strapi, add a date type field.

**Expected behavior**
I expected the date data type to have the same type of date picker as the old datetime data type picker.

**System**
- Node.js version: 10.18
- NPM version: 6.13.4
- Yarn version: 1.21.1
- Strapi version: 18.3
- Database: Postgres
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@tannuxie the previous date input type had quite a few issues, the new one was created in buffetjs.io to be more standard like. You can also just type in a different value instead of using the picker itself:

![image](https://user-images.githubusercontent.com/8593673/72324688-b9cdea80-3668-11ea-8704-13e5bb40d4ae.png)

**Comment by soupette** [comment]
I'm closing this issue as it related with [Buffet.js](https://github.com/strapi/buffet)
