### ISSUE TITLE
Field name inconsistencies and not updating correctly

### ISSUE THREAD

**Issue by niallobrien** [strapi/strapi#508]
Node.js version: 8.9.0
npm version: 5.5.1
Strapi version: 3.0.0-alpha.8.3
Operating system: Windows 7 (Enterprise)

Hi, I created a Post content type and added a String field with a name of "Title". There are inconsistencies as to how this is then used and displayed. For example, the key is stored as "Title" in MongoDB and the API also returns this capitalised key. I believe that the case of all field names should be adjusted to lowercase before storing in Mongo and simply capitalise these strings when rendering in the UI.

Also, once I realised this, I edited the field name to change it lowercase and now my collection in Mongo contains two "title" ("Title" and "title") fields which is incorrect, it should have updated the existing key.

![image](https://user-images.githubusercontent.com/1525669/35330675-3bbcd6f4-00fc-11e8-9ee0-ffa2f3012bcb.png)

Thanks.

**Comment by lauriejim** [comment]
Hello @niallobrien Can you give me the process you did to have this issue (be more precise as you can please)

**Comment by derrickmehaffy** [comment]
@lauriejim I have noticed the same issue.

- Create a content type that contains a string with the name `Title`
- Note that strapi by default did not change "Title" to "title" when storing in the database
- Change the string in the content builder from "Title" to "title"
- Update the record via the admin UI
- Note that the database now contains two values "Title" and "title" instead of updating the key it created a new one and did not remove the old one.

though if I have described this wrong, I'm sure @niallobrien can correct me.

**Comment by derrickmehaffy** [comment]
I believe this issue is also partially related to https://github.com/strapi/strapi/issues/661 as the user in this case wished to have the string name "Title" appear but store it in the database as "title".

The issue of displaying values on the admin UI and how they are stored/shown on the endpoints is a common issue. Although changing content field names doesn't appear to update in the database (the same applies to changing the entire content name. Say in this case "title" is contained in "Posts" where as it should be stored in the database as "posts".

I'd imagine changing this value manually would not update the database but instead create a new entry "posts"

**Comment by niallobrien** [comment]
@derrickmehaffy Perfect explanation, thank you. Yes, this is correct.

**Comment by lauriejim** [comment]
Okay I understand your needs. I close this issue but still #661 open.
