### ISSUE TITLE
The ability to deep filter on component objects in GraphQL and REST

### ISSUE THREAD

**Issue by roelbeerens** [strapi/strapi#5124]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Hi!

Recently I tried to limit the amount of items that are in the object of a repeatable component. I'm not 100% sure this should be done with a custom query, but it would be nice to have the ability to limit/start or use a where query on repeatable component objects in GraphQL. One-to-many relations have the ability to set a query for a nested field. Components however, do not.

If I've missed any possible solution digging through the existing issues, please let know.

**Edit by** @derrickmehaffy 

Filtering with GraphQL and REST on the polymorphic components

**Comment by roelbeerens** [comment]
For some reason I overlooked this one, oops...

https://github.com/strapi/strapi/issues/5089

**Comment by mtrabelsi** [comment]
this is a game changer to be able to use Graphql in its full power

**Comment by derrickmehaffy** [comment]
This will likely go hand in hand with filtering via REST as well

**Comment by iserifith** [comment]
is there any plan for this in the near future

**Comment by lauriejim** [comment]
@alexandrebodin or @JabStrapi will be able to answer to this question

**Comment by alexandrebodin** [comment]
Hi, This is not planned in the near future as we see components has being embeded in en entry. 

You should avoid using components if the real modeling is a relation. I know it really is practical to be able to add entries directly in the admin panel though. 

@JabStrapi  @Aurelsicoko  I think we shoul offer support for creating relation entries directly inside the Content Manager creation view at some point so the user don't start overusing componnets instead of relations

**Comment by derrickmehaffy** [comment]
> Hi, This is not planned in the near future as we see components has being embeded in en entry.
> 
> You should avoid using components if the real modeling is a relation. I know it really is practical to be able to add entries directly in the admin panel though.
> 
> @JabStrapi @Aurelsicoko I think we shoul offer support for creating relation entries directly inside the Content Manager creation view at some point so the user don't start overusing componnets instead of relations

I also 2nd this, it's something I see often

**Comment by mtrabelsi** [comment]
you can just use raw REST queries for now, it works just fine...

**Comment by exeg** [comment]
> you can just use raw REST queries for now, it works just fine...

If you have complex dataset it is not fine because it limits the use of strapi

**Comment by iserifith** [comment]
> you can just use raw REST queries for now, it works just fine...

what i was hoping to do was ability to deep filter on the component

something like `?component.name=something`

**Comment by lichaar** [comment]
> Hi, This is not planned in the near future as we see components has being embeded in en entry.
> 
> You should avoid using components if the real modeling is a relation. I know it really is practical to be able to add entries directly in the admin panel though.
> 
> @JabStrapi @Aurelsicoko I think we shoul offer support for creating relation entries directly inside the Content Manager creation view at some point so the user don't start overusing componnets instead of relations


But even relation entries does not cover all the typical cases, Example: Product specific variants (like Colors, Physical Properties, Spec) 😢

**Comment by alexandrebodin** [comment]
@lichaar Can you explain why you think that the relation don't cover the cases you mentionned ? 
thanks !

**Comment by lichaar** [comment]
@alexandrebodin Let's imagine a Product content type, This Product have different variations, For example 10 Colors, And each Color may have its own price, stock... (component).

You can imagine something similar for Physical properties as well which the values can be quite different on each product.

Unfortunately with the current limitation you can not **query** and **filter** based on those repeatable fields. For example you can not query only the Products with the color red and stock below certain number.

**Comment by alexandrebodin** [comment]
@lichaar The kind of thing you want to achieve should be done with relations not components :) You will need to model a more complexe schema to match your needs. A good example can be this discussion on stackoverflow: https://stackoverflow.com/questions/24923469/modeling-product-variants

**Comment by adamkhan** [comment]
It would seem to me that filtering on components is more basic and fundamental functionality than filtering on relations. A component is for considering these fields to be a part of our entity. Without being able to filter on them, we are creating a set of dud fields. I didn't know about this limitation and have abstracted out some pretty important fields to components. Bummer!

**Comment by chris-r-hudson** [comment]
This sucks, I've just spent ages building a model with components as it seems really neat and re-usable, only its not, and I cant filter on a simple component.

**Comment by lodisy** [comment]
That being said, I have to create post tags first and then assign them to the posts (relations). 

Otherwise, I am only allowed to select the exisiting ones in the post creating page.

It will be much easier and if I create tags as component in the post creating page. 

But in this case, it is impossible to filter tags-based posts.

**Comment by cipiasentini** [comment]
I can't believe the time wasted on coding everything thinking that this simple filter was achievable via the API, but it isn't...

**Comment by callingshotgun** [comment]
@alexandrebodin I'll provide another example where (at least from my understanding) the relation isn't quite a fit.
Let's say I want a cookbook app, and for a "Recipe" page, I have:
-Name
-Description
-Recipe

Where "Recipe" is a set of 1+ ingredients and their quantities.  I naturally want to do this with components, so each row is
(quantity) (unit) (ingredient) e.g  8 oz ground beef.

But I also get that what I'm really asking for is a many-to-many relation -- In terms of functionality, I want to be able to click on "ground beef" and perform a search of all recipes that have ground beef in the ingredient list.  

Relation doesn't *quite* work because:
-  I don't want to query for other recipes with "8 oz ground beef", just "ground beef".  The ingredient needs to be separate from other things in the row. 

- If you try to create a component where one field is the relation to an ingredients table, there's no way to just "type in" ingredients as you go if you're using a relation.  It'll make you add ingredient names in a separate table and drop-down select them for each ingredient you want to add, which for a complex recipe full of ingredients your database hasn't seen before can get tedious AF.  Not sure how it affects search, I rage-quit this idea when I realized what it was like to enter a recipe :D

**Comment by luisjuniorj** [comment]
There is no point of having a field that cannot be searchable, just so much time spent on creating everything to discard because i cant search a field.

**Comment by alexandrebodin** [comment]
Thanks for all your comments and use cases. We have all the info we need to try to propose solutions for this. I'm locking the conversation for now. Please use the +1 on the description so we can see how popular this is.

**Comment by VadSiam** [comment]
nice to have +1

**Comment by rakanus** [comment]
we need this at least to mention this in the documentation that you can not do deep filtering on repeatable component

**Comment by exeg** [comment]
@rakanus You can write your own query with strapi.query("Your model name").model.aggregate([])

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/best-approach-for-nested-data/942/9

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/why-does-deep-filtering-by-url-no-longer-work/996/4

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/graphql-dynamic-zone-union-query-does-not-filter-or-sort-data/1149/7

**Comment by blukasho** [comment]
+1

**Comment by codeashian** [comment]
+ 1

**Comment by yhetman** [comment]
+1

**Comment by acidin** [comment]
+1

**Comment by zyakita** [comment]
++1

**Comment by sunnysonx** [comment]
+1

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/how-to-find-with-a-component/1856/2

**Comment by hammadyounas** [comment]
+1

**Comment by shtaimoortariq** [comment]
+1

**Comment by MohsinGhani** [comment]
+1

**Comment by mshayanabbasi** [comment]
+1

**Comment by rijojoy** [comment]
+++++1

**Comment by mohito12** [comment]
+1

**Comment by derrickmehaffy** [comment]
Thank you everyone for the feedback, no new information is being added so I'm going to lock this thread for now.

**Comment by ngjoni** [comment]
Maybe this could help: https://www.npmjs.com/package/strapi-deepsearch-service

**Comment by benderillo** [comment]
> Hi, This is not planned in the near future as we see components has being embeded in en entry.
> 
> You should avoid using components if the real modeling is a relation. I know it really is practical to be able to add entries directly in the admin panel though.
> 
> @JabStrapi @Aurelsicoko I think we shoul offer support for creating relation entries directly inside the Content Manager creation view at some point so the user don't start overusing componnets instead of relations

Regardless of the future of the current feature request, I am very keen to see the @alexandrebodin's proposal implemented @JabStrapi and @Aurelsicoko :) is there a feature request for it? 
I feel that it really will reduce the number of cases ppl went with components where normal relations fit better. I know I would.
Because at the moment, UX with relations for whoever populates the content on the backend is plain bad.
There should be way of creating relational entries within one editor. Otherwise one have to define the content in somewhat backward way (bottom - up) which for non-technical person make little sense.

**Comment by Ulibka68** [comment]
+1

**Comment by derrickmehaffy** [comment]
Relocking thread as we already see the support for the request, +1s aren't needed but thank you.

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
