### ISSUE TITLE
globalId field is removed on Content Type update via the admin panel

### ISSUE THREAD

**Issue by iedmrc** [strapi/strapi#5245]
**Describe the bug**
Hi,
If you try to modify a content-type through the admin panel, then the `gloalId` property will be removed from the model.settings.json file.

**Steps to reproduce the behavior**
1. Create a content type through admin panel 
2. Add some fields and save the content type
3. Go `model.settings.json` file and add `globalId` property
4. Go content-type builder, add a new field to the content-type and save.
5. See `model.settings.json` file doesn't have `globalId` property anymore.

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.13.0
- NPM version:6.4.1
- Strapi version: 3.0.0-beta.18.7 (node v10.13.0)  
- Database: postgresql
- Operating system: macos catalina

**Additional context**

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.

Could be also be related to this issue - https://github.com/strapi/strapi/issues/5122

**Comment by Kyle772** [comment]
Hi @lauriejim you had previously touched on this issue and followed up in another thread when the fix was pushed out. I think that the problem was maybe fixed with collections but is still present with components. I've seen this issue on previous versions of strapi but the files in the error log are not what I typically see as it's not a db reference error it's a strapi['component'] error. 

After adding a brand new component to a collection I'm having issues with mismatches between my server environment and my dev environment but ONLY on the _other_ environment from the one where I built the components.

This is the error I'm receiving which I believe to be directly in-line to this initial bug report
```
Starting your app...
strapi           | [2021-08-20T00:29:58.729Z] debug ⛔️ Server wasn't able to start properly.
strapi           | [2021-08-20T00:29:58.730Z] error TypeError: Cannot read property 'globalId' of undefined
strapi           |     at Object.convertType (/srv/app/node_modules/strapi-plugin-graphql/services/type-builder.js:88:53)
strapi           |     at /srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:114:38
strapi           |     at Array.forEach (<anonymous>)
strapi           |     at buildTypeDefObj (/srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:111:6)
strapi           |     at buildModelDefinition (/srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:356:22)
strapi           |     at buildCollectionType (/srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:458:23)
strapi           |     at /srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:348:16
strapi           |     at Array.map (<anonymous>)
strapi           |     at buildModels (/srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:337:17)
strapi           |     at buildShadowCrud (/srv/app/node_modules/strapi-plugin-graphql/services/shadow-crud.js:51:22)
strapi           |     at Object.generateSchema (/srv/app/node_modules/strapi-plugin-graphql/services/schema-generator.js:37:42)
strapi           |     at Object.initialize (/srv/app/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:76:74)
strapi           |     at /srv/app/node_modules/strapi/lib/hooks/index.js:37:28
strapi exited with code 1
```

When digging through the plugin cache I can see that this has something to do with a missing globalID but the section the error points to is specific to components which could potentially be the source with this inconsistency? 

```
 if (attribute.type === 'component') {
      const { required, repeatable, component } = attribute;

      const globalId = strapi.components[component].globalId; < --- Error line 88

      let typeName = required === true ? `${globalId}` : globalId;

      if (rootType === 'mutation') {
        typeName =
          action === 'update'
            ? `edit${_.upperFirst(toSingular(globalId))}Input`
            : `${_.upperFirst(toSingular(globalId))}Input${required ? '!' : ''}`;
      }

      if (repeatable === true) {
        return `[${typeName}]`;
      }
      return `${typeName}`;
    }
```

For context I had this error on my server so I scrapped my last commit and rebuilt the component on my prod server instead of doing it locally and pushing the schemas up to my server. This fixed the problem on the server but once I had pulled those changes back to my dev environment my dev environment was now shooting out the same error my prod environment had previously. 


Any idea to a solution?

**Comment by derrickmehaffy** [comment]
should be fixed in v4, closing
