### ISSUE TITLE
Support for teardown.js function the opposite of bootstrap.js

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#5253]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

The functionality of the bootstrap.js file is great, however, I think its opposite is missing. Many times we need to teardown connections and gracefully announce that we are tearing down the server. This way when running strapi develop you can be assured that there are no lingering connections during server restart. For instance I have a SIP switch socket connect that is created at startup. Then when doing any changes to the api, the develop watcher kicks in and restarts the server as expected. However, the connection is not closed and a second one is created. The parameters used to create this socket are dependant on startup variables and it cannot be reused. There is no way of warning the  socket that we are stopping the server and restarting, except if you hack into Strapi. If there is a way then either it should be documented or support for config/functions/teardown.js should be implemented.

**Comment by lauriejim** [comment]
Thank you for this feature request.
I ping @Aurelsicoko and @alexandrebodin about that.

**Comment by evanrittenhouse** [comment]
Hey @derrickmehaffy I can try to take this on, if it's still open!

**Comment by derrickmehaffy** [comment]
I believe we actually have this now :thinking: at least in plugins or the `destroy` may be the opposite of `register`

Either way these I believe are defined here: https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/core/domain/module/index.js#L35-L55

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/support-for-teardown-function-the-opposite-of-bootstrap
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
