### ISSUE TITLE
Support to Upload files with base64 instead of form-data buffer

### ISSUE THREAD

**Issue by ningacoding** [strapi/strapi#5297]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

In some platforms like React Native, is not posible to upload files vía Buffer and form-data, please add support to base64 string vía post json.

**Comment by lauriejim** [comment]
Hello! Thank you for this insight, I really appreciate!
Ping @alexandrebodin  - That is one kind of use case I was talking about.

**Comment by bacarybruno** [comment]
Hi @ningacoding. To upload a file to strapi using react-native, you can use RNFetchBlob package, which has the capability to send multipart/form-data files.
You can find below the code snippet I use to upload files :

`const postData = {
    name: 'data',
    data: JSON.stringify({ content, author }),
  }
  const fileData = {
    name: 'files.fieldNane',                            // audio reprends your field name
    filename: file.name,                                 // the file name + extension
    type: file.mimeType,                                // the mime type of the file, based on mime-db
    data: RNFetchBlob.wrap(audio.uri),        // the uri of the file on the mobile device
  }

RNFetchBlob.fetch('POST', 'localhost:1337/posts', {
    'Content-Type': 'multipart/form-data',
  }, [postData, fileData])
`
But yes, it would be interesting to be able to send files without having to install a package.

**Comment by ningacoding** [comment]
@bacarybruno the package you shared, is not compatible with Expo, so it's not totally supported by React Native standar/popular development environments. Basically a package is not a warranty to works for a framework, remember that React Native alwo works on Windows, Mac, Browser, Android, iOS, etc. so i can imagine the package you shared you did not test for everyone, only with your experience, Opening a Backend support, it's a better idea.

**Comment by bacarybruno** [comment]
@ningacoding You are right. I fully understand the feature request. I should have mentioned that I don't use expo and that I only target Android and iOS devices.

**Comment by OscarGBeta-Gif** [comment]
El mismo problema se da en Angular, dado que no deja cargar archivos en datos de formulario. Si alguien tiene la solución por favor compartirla. Gracias.

**Comment by pvk2410** [comment]
@lauriejim We have a requirement to upload the base64 encoded content to Strapi as an asset to be listed in the 'Media library'. 

We are getting this base64 encoded content of the document (as a response from their REST end point) from a different system which we want to upload directly into strapi.
As i understand the files upload directive ( POST  /upload) accepts only buffer or streams.

Any suggestions on how to achieve this?

**Comment by alexandrebodin** [comment]
Hi @pvk2410 you can create a custom route that will use the upload service to implement it on your side if you need to.

**Comment by ningacoding** [comment]
> Hi @pvk2410 you can create a custom route that will use the upload service to implement it on your side if you need to.

i think "gallery" or "media" or "files", does not have a "good practices" documentation to do that.

The integration sould to be clean, plus, a custom service does not warranty the gallery plugins functionallity.

**Comment by cmosboss** [comment]
Just incase anyone is wondering, for EXPO and React Native you can indeed upload images to STRAPI although it requires a few key ingredients that are hard to find online. 
`const uri = 'localfileURI';
const CMSEndpoint = 'https://localhost:1337';
const formData = new FormData();
formData.append(
  'files',
  { uri, name: 'image.jpg', type: 'image/jpeg' },
);

try {
  const response = await axios
    .post(`${CMSEndpoint}/auth/local`, {
      identifier: 'username',
      password: 'password',
    });
  const { jwt } = response.data;
  if (jwt) {
    const imageResponse = await axios.post(`${CMSEndpoint}/upload`, formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
        Authorization: `Bearer ${jwt}`,
      },
    });
    console.log(imageResponse.data);
  }
} catch (error) {
  console.log('File Upload Error', error);
}`

You need to install[ form-data ](https://www.npmjs.com/package/form-data)package and [axios](https://www.npmjs.com/package/axios) make sure to import them both 
`import axios from 'axios';
import FormData from 'form-data';`

Very important that you include content type headers, include the formData.append with specifically key `files` no other key will work here. Also make sure that you have a user created, and that under the Roles and Permissions inside of STRAPI you have UPLOAD options checked for that user so that you do not get error 403 on upload.

**Comment by thamanchand** [comment]
@cmosboss i tried to upload pictures from **React-native** application using `expo-image-picker` as you suggested, no luck so far! Have you tested above code?


```

import FormData from "form-data";


const uploadPictures = (medias, id) => {
  console.log("medias", medias);
  medias.map((image, index) => {
    const localFileURI = image.uri;
    console.log(localFileURI) // output ->  file:///Users/superman/Library/Developer/CoreSimulator/Devices/3A57E016-A26D-4355-AD64-D751D185B7BC/data/Containers/Data/Application/FE660101-D017-458D-B2AA-4EE6D5C7C14A/Library/Caches/ExponentExperienceData/%2540anonymous%252Fdudu-65662709-3286-4774-a399-b8a22a1c2a5a/ImagePicker/1334CD24-2A7C-44B7-99FA-E918C8348BB0.jpg
    const fileName = image.uri.split("/").pop();  // output ->  1334CD24-2A7C-44B7-99FA-E918C8348BB0.jpg
    const filePath = image.uri.split("///").pop(); // output ->   /Users/superman/Library/Developer/CoreSimulator/Devices/3A57E016-A26D-4355-AD64-D751D185B7BC/data/Containers/Data/Application/FE660101-D017-458D-B2AA-4EE6D5C7C14A/Library/Caches/ExponentExperienceData/%2540anonymous%252Fdudu-65662709-3286-4774-a399-b8a22a1c2a5a/ImagePicker/1334CD24-2A7C-44B7-99FA-E918C8348BB0.jpg
    const match = /\.(\w+)$/.exec(fileName); 
    const contentType = match ? `image/${match[1]}` : `image`;
    console.log(contentType) // output -> image/jpg

    let formData = new FormData();
    formData.append("files", file);
    formData.append("refId", id);
    formData.append("ref", "listing");
    formData.append("field", "media");

    return client.post(uploadEndpoint, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    });
  });
};
```

**I get error** 

`{"statusCode":400,"error":"Bad Request","message":"Bad Request","data":{"errors":[{"id":"Upload.status.empty","message":"Files are empty"}]}}`


**Here is payload**

```
------WebKitFormBoundaryABkWUWVWbwwAX46m
Content-Disposition: form-data; name="files"

file:///Users/superman/Library/Developer/CoreSimulator/Devices/3A57E016-A26D-4355-AD64-D751D185B7BC/data/Containers/Data/Application/FE660101-D017-458D-B2AA-4EE6D5C7C14A/Library/Caches/ExponentExperienceData/%2540anonymous%252Fdudu-65662709-3286-4774-a399-b8a22a1c2a5a/ImagePicker/37A42BF5-6FC0-4B47-B9A0-A6489DA1B717.jpg
------WebKitFormBoundaryABkWUWVWbwwAX46m
Content-Disposition: form-data; name="refId"

226
------WebKitFormBoundaryABkWUWVWbwwAX46m
Content-Disposition: form-data; name="ref"

listing
------WebKitFormBoundaryABkWUWVWbwwAX46m
Content-Disposition: form-data; name="field"

media
------WebKitFormBoundaryABkWUWVWbwwAX46m--
```

Can you give a pointer what am I missing or doing wrong?

**Comment by BobbyCarelse** [comment]
> Just incase anyone is wondering, for EXPO and React Native you can indeed upload images to STRAPI although it requires a few key ingredients that are hard to find online.
> 
> ```js
> const uri = 'localfileURI';
> const CMSEndpoint = 'https://localhost:1337';
> const formData = new FormData();
> formData.append(
>   'files',
>   { uri, name: 'image.jpg', type: 'image/jpeg' },
> );
> 
> try {
>   const response = await axios
>     .post(`${CMSEndpoint}/auth/local`, {
>       identifier: 'username',
>       password: 'password',
>     });
>   const { jwt } = response.data;
>   if (jwt) {
>     const imageResponse = await axios.post(`${CMSEndpoint}/upload`, formData, {
>       headers: {
>         'Content-Type': 'multipart/form-data',
>         Authorization: `Bearer ${jwt}`,
>       },
>     });
>     console.log(imageResponse.data);
>   }
> } catch (error) {
>   console.log('File Upload Error', error);
> }
> ```
> 
> You need to install[ form-data ](https://www.npmjs.com/package/form-data)package and [axios](https://www.npmjs.com/package/axios) make sure to import them both
> 
> ```js
> import axios from 'axios';
> import FormData from 'form-data';
> ```
> 
> Very important that you include content type headers, include the formData.append with specifically key `files` no other key will work here. Also make sure that you have a user created, and that under the Roles and Permissions inside of STRAPI you have UPLOAD options checked for that user so that you do not get error 403 on upload.

My request keeps failing with 401

**Comment by BobbyCarelse** [comment]
Using the above method I am getting `Request failed with status code 401`

**Comment by shtaimoortariq** [comment]
> Hi @ningacoding. To upload a file to strapi using react-native, you can use [RNFetchBlob](https://github.com/joltup/rn-fetch-blob) package, which has the capability to [upload multipart/form-data files](https://github.com/joltup/rn-fetch-blob#multipartform-data-example-post-form-data-with-file-and-data).
> You can find below the code snippet I use to upload files :
> 
> ```js
> const postData = {
>   name: 'data',
>   data: JSON.stringify({ content, author }),
> }
> 
> const fileData = {
>   name: 'files.fieldName',                  // your strapi field name
>   filename: file.name,                      // the file name + extension
>   type: file.mimeType,                      // the mime type of the file, based on mime-db
>   data: RNFetchBlob.wrap(file.uri),         // the uri of the file on the mobile device
> }
> 
> RNFetchBlob.fetch('POST', 'localhost:1337/posts', {
>   'Content-Type': 'multipart/form-data',
> }, [postData, fileData])
> ```
> 
> But yes, it would be interesting to be able to send files without having to install a package.



> Hi @ningacoding. To upload a file to strapi using react-native, you can use [RNFetchBlob](https://github.com/joltup/rn-fetch-blob) package, which has the capability to [upload multipart/form-data files](https://github.com/joltup/rn-fetch-blob#multipartform-data-example-post-form-data-with-file-and-data).
> You can find below the code snippet I use to upload files :
> 
> ```js
> const postData = {
>   name: 'data',
>   data: JSON.stringify({ content, author }),
> }
> 
> const fileData = {
>   name: 'files.fieldName',                  // your strapi field name
>   filename: file.name,                      // the file name + extension
>   type: file.mimeType,                      // the mime type of the file, based on mime-db
>   data: RNFetchBlob.wrap(file.uri),         // the uri of the file on the mobile device
> }
> 
> RNFetchBlob.fetch('POST', 'localhost:1337/posts', {
>   'Content-Type': 'multipart/form-data',
> }, [postData, fileData])
> ```
> 
> But yes, it would be interesting to be able to send files without having to install a package.

i am unable to upload with this method i have base64 and i have blob too doing everything and i am stuck for a week 
tried Blob / File , Uri method with wrapping to RNFetchBlob.wrap and base64 failed in all of method... would any one please help me 
and my image is coming from ImagePicker Library 
 `const source = {path: 'data:image/jpeg;base64,' + response.data};
        const profileImage = [
          {
            data: source.path,
            type: response.type,
            ext: response.type,
            filename: response.fileName,
            source: response.data,
            uri: response.uri,
            size: response.fileSize,
            path: response.path,
            width: response.width,
            path: response.path,
            lastModified: response.timestamp,
          },
        ];
`
`export const uploadImage = (ImageUri, authToken) => {
  return new Promise(async (resolve, reject) => {
    const Blob = RNFetchBlob.polyfill.Blob;
    const fs = RNFetchBlob.fs;
    window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest;
    window.Blob = Blob;

    let images = {};
    ImageUri.map((file) => {
      console.log(file)
      let newPath =
        Platform.OS === 'ios' ? file.path.replace('file://', '') : file.path;

      images = {
        name: `${file.filename}`,
        filename: file.filename,
        type: file.type,
        data: file.source,
        size:file.size,
        ext:file.ext,
        lastModified:file.lastModified,

      };
    });

    RNFetchBlob.fetch(
      'POST',
      'http://192.168.18.148:1337/upload',
      {
        Authorization: `Bearer ${authToken}`,
        'Content-Type': 'multiparts/form-data',
      },
      [images],
    )
      .then(async (data) => {
        return data.json();
      })
      .then(([data]) => {

        resolve(data);
      });`

would any one please Help me resolve this issue

**Comment by baermathias** [comment]
Upload and **store** `base64` strings inside the database would also be one solution to Strapis problem of not being able to protect files or provide access control to files in general (see issue https://github.com/strapi/strapi/issues/8623). This way files could be stored inside the database as strings and would be protected by Strapis users and permissions plugin, which provides full authentication process based on JWT and also ACL strategy.

**Comment by ckyleda** [comment]
The way Strapi deals with file uploads (especially images) is archaic. Images should be able to be sent as base64, then decoded and stored on disk as currently happens with the upload plugin.

Being forced into using formdata is ridiculous, especially as the majority of API calls function via a simple JSON Payload.

**Comment by derrickmehaffy** [comment]
> The way Strapi deals with file uploads (especially images) is archaic. Images should be able to be sent as base64, then decoded and stored on disk as currently happens with the upload plugin.
> 
> Being forced into using formdata is ridiculous, especially as the majority of API calls function via a simple JSON Payload.

I certainly don't disagree, there are other use-cases where using streams instead of buffers internally could certainly help (I'm not sold on storing binary files in a database but still could be handled better internally).

For example, as an Idea, for better AWS-S3 storage we could do something like this flow (assuming the Strapi backend is basically functioning as a file proxy for both upload and fetch).

![image](https://user-images.githubusercontent.com/8593673/124990582-6cc89b80-dff5-11eb-968c-4d3f8d86b302.png)

**Comment by mateussmohamed** [comment]
> Just incase anyone is wondering, for EXPO and React Native you can indeed upload images to STRAPI although it requires a few key ingredients that are hard to find online.
> 
> ```js
> const uri = 'localfileURI';
> const CMSEndpoint = 'https://localhost:1337';
> const formData = new FormData();
> formData.append(
>   'files',
>   { uri, name: 'image.jpg', type: 'image/jpeg' },
> );
> 
> try {
>   const response = await axios
>     .post(`${CMSEndpoint}/auth/local`, {
>       identifier: 'username',
>       password: 'password',
>     });
>   const { jwt } = response.data;
>   if (jwt) {
>     const imageResponse = await axios.post(`${CMSEndpoint}/upload`, formData, {
>       headers: {
>         'Content-Type': 'multipart/form-data',
>         Authorization: `Bearer ${jwt}`,
>       },
>     });
>     console.log(imageResponse.data);
>   }
> } catch (error) {
>   console.log('File Upload Error', error);
> }
> ```
> 
> You need to install[ form-data ](https://www.npmjs.com/package/form-data)package and [axios](https://www.npmjs.com/package/axios) make sure to import them both
> 
> ```js
> import axios from 'axios';
> import FormData from 'form-data';
> ```
> 
> Very important that you include content type headers, include the formData.append with specifically key `files` no other key will work here. Also make sure that you have a user created, and that under the Roles and Permissions inside of STRAPI you have UPLOAD options checked for that user so that you do not get error 403 on upload.

worked for me, thanks.

**Comment by exotexot** [comment]
Hello,

this issue seems to be old, however I also want to mention, that a way for Strapi's media library to deal with base64 encoded images would be really handy. 

My use case: I create a new route (endpoint) in Strapi, where I receive a base64 encoded image, which I attach using strapis email plugin. It would be nice to store this image in Strapi's media library as a binary file. Ideally I could upload to the media library (local) from the controller - does anybody know if this is possible with strapi 4.5.x?

**Comment by Cpaczek** [comment]
@joshuaellis Is Strapi open to adding a new function to the upload service to support this functionality? If so I could open a PR.

**Comment by joshuaellis** [comment]
Hi all,

We've looked into the enhancement propositions form the associated PRs and we've decided to not implement buffer or base64 upload for the moment.

Our understanding is that the HTTP content-type `formData` is suited to both send text data (like filename, mime type) and a binary file. Whereas the HTTP content-type “application/json” is only suited for text (JSON more precisely of course). In order to upload a file using JSON, the hack is to encode the file into a string that can be in the JSON (could be base64, or buffer):

```ts
console.log(JSON.stringify(Buffer.from('hello'))) // result: {"type":"Buffer","data":[104,101,108,108,111]}
console.log(JSON.stringify(Buffer.from('hello').toString('base64'))) // result: "aGVsbG8="
```

However it doesn’t seem to be considered as a best practice as it’s consuming resources to code/decode & increases the file size by 33% as it was never meant to be used this way.

In order to enforce best practices, and since it seems that a reasonable amount of libraries exist that help using formData in node & react-native, we would prefer not to support file serialising upload in a JSON payload for the moment. We are open to continue the discussion of course.

*If* you do feel compelled to handle this in your applications immediately, https://github.com/strapi/strapi/pull/15755 displays a simple service that can be used – you would need to write the controller however.

**Comment by Cpaczek** [comment]
@joshuaellis I agree that base64 and buffer uploads are probably not the best practice when it comes to uploading images over http but the reason why I started my PR and what @derrickmehaffy mentioned having the ability to upload a buffer using the upload service is needed/wanted feature which is why my original PR didn't allow buffers over HTTP (https://github.com/strapi/strapi/pull/15755).

Here is an example of my use case. I am using puppeteer to dynamically generate open graph preview images for Strapi based on content type data. Currently, the only way for me to upload that image is for me to copy all of this [code](https://github.com/strapi/strapi/pull/15755/files#diff-3c0f1c68e7bcad4702d7bd9600b9ca459715158a9451da2ae05454d163cada16R184-R229) which also requires me to copy and paste a lot of the non exported functions that are in the upload service. This means that if you change something about the upload service it could break the code as we are reusing code from the service.

I think adding the ability to upload buffers only through the `strapi` object would be the best of both worlds while still following best practices.

If Strapi decides that this is still not the best practice I think there should be documentation on how to do this. 

P.S your competitors offer/document this feature.

**Comment by petersg83** [comment]
Hello @Cpaczek :) Yes there is confusion here. This issue is about base64/buffer over HTTP while the issue/need you want to address (I think) is different, it's to make the upload service accept a buffer internally only which seems legit to me.
What do you think of creating another issue for that need? So we avoid the confusion. And we will close this issue as we concluded base64 over http is not something we want to implement for the moment.

**Comment by Cpaczek** [comment]
@petersg83 I had this issue but I can make a new one if needed https://github.com/strapi/strapi/issues/15524

**Comment by petersg83** [comment]
Oh I didn't know this one. Sorry for all the mix up, I'll reopen it :)
