### ISSUE TITLE
Plugins configuration location

### ISSUE THREAD

**Issue by dakuenjery** [strapi/strapi#533]
I noticed when I add content types the 'plugins/users-permissions/config/roles.json' file is changing. I think it's very uncomfortable. For example during the update plugin I must copy this file and restore it. Are you going to take the configuration files to a separate folder? Is it possible?

**Comment by Aurelsicoko** [comment]
@dakuenjery We already moved these configurations into the database in the latest version `alpha@9`. [Check out the migration guide](https://strapi.io/documentation/migration/migration-guide-alpha-8-to-alpha-9.html) and the problem will disappear.

I'm closing this issue because it was a known problem and the latest version fixed it. Feel free to reopen if the issue is still here.
