### ISSUE TITLE
Enum with multiple times the same value breaks

### ISSUE THREAD

**Issue by maevalienard** [strapi/strapi#5343]
**Describe the bug**
When I create an enum with some values being the same the server cannot restart.

**Example**
Enum:
```
ff
other
ff
```

**Expected behavior**
I should be able to create an enum with multiple times the same value

**System**
- Node.js version: 10
- NPM version: 6
- Strapi version: beta.18.8
- Database: sqlite
- Operating system: debian

**Comment by derrickmehaffy** [comment]
@maevalienard this is a limitation of enumeration in general, they need to be unique values.

https://en.wikipedia.org/wiki/Enumerated_type

The problem here is even if the frontend supports it the backend databases won't, enumeration is in itself a type of constraint. Typically in a backend database enumeration values are mapped and stored as integers with a map index that points the value to the integer. When matching the value coming from the frontend the database will throw an error (that's if the database will even allow duplicate enumeration values to begin with, in the case of most SQL databases they wont).

**Comment by derrickmehaffy** [comment]
A reference as to why I figured storing as varchar instead of enum: http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/
