### ISSUE TITLE
Should be able to pass database connector object directly without any Strapi prefix

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5433]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I am using `Strapi-Beta` V `3.0.0-beta.18.4`, I want to use Redis for session storage with a connector. 

Currently for Redis we only have `strapi-hook-redis` connector/NPM package but in the `Strapi` `V3` code, here: https://github.com/strapi/strapi/blob/master/packages/strapi-database/lib/require-connector.js#L19 & https://github.com/strapi/strapi/blob/master/packages/strapi-database/lib/require-connector.js#L29 it is prefixed with `strapi-connector-`, so we had to use `strapi-connector-mongoose`:  connector for `Mongo` db which we have an NPM package for it, here: https://www.npmjs.com/package/strapi-connector-mongoose  but since we don't have `strapi-connector-redis` connector/NPM package, we are not able to use `Redis` db in `V3`.

It will be good if we can remove this prefix: `strapi-connector-` in the `strapi` v3 code so we can pass in Redis database connector object directly.

**`NOTE:`** I have used `strapi-hook-redis`:  https://www.npmjs.com/package/strapi-hook-redis connector/npm package in `Strapi` `Alpha` code, it worked fine.

**Comment by lauriejim** [comment]
Hello! Thank you for this issue.
The `hook` system is no longer used for database connector.
We use `strapi-connector` for previous hooks used for database stuff.
We are no supporting the Redis connection that is the reason why `strapi-connection-redis` doesn't exist.
We will not allow specifying prefixes because we will lose the module name consistency.
Connectors have to be named `strapi-connectors`, plugins `strapi-plugin`, etc...
In any case, thank you for this message!
