### ISSUE TITLE
Specify relation column as required

### ISSUE THREAD

**Issue by harshilsharma2** [strapi/strapi#557]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.9

**Operating system**: Ubuntu 16.04 x64

Additional details -

 **Database being used**: PostgreSQL 9.5.10

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
There is no way to specify a relation column as required.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Create a new model in Strapi.
1. Create a relation attribute in this model. Notice that there is no option for marking this column as required in advanced settings.

**What is the expected behavior?**
Relation columns should allow to be marked as required.

**Comment by harshilsharma63** [comment]
This may solve #556

**Comment by derrickmehaffy** [comment]
Can confirm, relations should have a required function.

**Comment by derrickmehaffy** [comment]
It should be noted that in some cases the required attribute may be only one-sided (thinking Many to One relationship)

Manufacturer may have multiple models, but you shouldn't need to specify a model when adding a manufacturer, however you should need to specify a manufacturer when adding a model if that makes any sense.

**Comment by alexDrinkwater** [comment]
@derrickmehaffy I agree. Anyone working on this?

**Comment by derrickmehaffy** [comment]
Not yet @alexDrinkwater, if you wanted to take it up and submit a PR that would be awesome. It is above my skill level.

**Comment by farzer** [comment]
marked

**Comment by raza2022** [comment]
@lauriejim any update on it

**Comment by ningacoding** [comment]
any update?

**Comment by EricCBonet** [comment]
This would be nice to have.

**Comment by derrickmehaffy** [comment]
There is no update to this yet, the new database layer has been added but work has not started on this yet. When it is you will see a PR linked to this issue.

**Comment by DekiGk** [comment]
@derrickmehaffy Thanks for sharing the current state and sorry for reopening the discussion here, but I would like to know if we could track the progress on this somehow? I looked at the roadmap and I do not see the new DB layer integration there. Since this is set as low priority is there any possible ETA someone can give us for this one?

**Comment by derrickmehaffy** [comment]
Currently there is no ETA that I am aware of for this unless @alexandrebodin / @Aurelsicoko have updated information.

**Comment by alexandrebodin** [comment]
Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.

This however doesn't check if the id is valid to avoid any perf impact for now. We will soon be reviewing all the attribute options in the content-type-builder to clean them up

**Comment by DekiGk** [comment]
> Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.

Where can I set this? In `[content-type].settings.json`?

**Comment by Arman-AP** [comment]
Does not work when required is set to true in `[content-type].settings.json`. 
I get Error: SQLITE_CONSTRAINT: NOT NUL
L constraint failed:

**Comment by alexandrebodin** [comment]
Yep you are right. right now this will break. because of the way we create the data in DB. We will be fixing this during Q2 2020

**Comment by abdonrd** [comment]
Any news here? I have the same issue with the components: #5862

**Comment by abdonrd** [comment]
And maybe related with this: https://github.com/strapi/strapi/issues/5418#issuecomment-615850721

**Comment by alexandrebodin** [comment]
Hi, This issue hasn't been addressed yet

**Comment by fastengineer** [comment]
Important feature!

**Comment by oestrada1001** [comment]
I would like to contribute to this. I haven't contributed to anything before, can someone give me a little guidance on how to do it? I'll research in the meantime.

**Comment by fastengineer** [comment]
It is very difficult to face this problem as non-strapi-crew-developer.

**Comment by hkovacs** [comment]
> Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.
> 
> This however doesn't check if the id is valid to avoid any perf impact for now. We will soon be reviewing all the attribute options in the content-type-builder to clean them up

why does there need to be a check for valid id? if i have a `user` relation field one to one, then i should be able to require a user from a select list and that's all that is needed. 

i agree that other relationships are more complex, but i dont see why simple relationships need to be made over complicated.

thank you!

**Comment by alexandrebodin** [comment]
> > Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.
> > This however doesn't check if the id is valid to avoid any perf impact for now. We will soon be reviewing all the attribute options in the content-type-builder to clean them up
> 
> why does there need to be a check for valid id? if i have a `user` relation field one to one, then i should be able to require a user from a select list and that's all that is needed.
> 
> i agree that other relationships are more complex, but i dont see why simple relationships need to be made over complicated.
> 
> thank you!

Not in the case when calling the APIs. Right now you can send an invalid id in a relation. Making them required would require to verify those to avoid breaking constraints with invalid relations.

**Comment by hkovacs** [comment]
> > > Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.
> > > This however doesn't check if the id is valid to avoid any perf impact for now. We will soon be reviewing all the attribute options in the content-type-builder to clean them up
> > 
> > 
> > why does there need to be a check for valid id? if i have a `user` relation field one to one, then i should be able to require a user from a select list and that's all that is needed.
> > i agree that other relationships are more complex, but i dont see why simple relationships need to be made over complicated.
> > thank you!
> 
> Not in the case when calling the APIs. Right now you can send an invalid id in a relation. Making them required would require to verify those to avoid breaking constraints with invalid relations.

ok. thank you

**Comment by Morantron** [comment]
> Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.
> 
> This however doesn't check if the id is valid to avoid any perf impact for now. We will soon be reviewing all the attribute options in the content-type-builder to clean them up

Is there a way to show a better validation error when following this workaround?

Right now i'm getting this

![image](https://user-images.githubusercontent.com/3304507/87344157-3a08d600-c54e-11ea-8559-9f92609c065b.png)

**Comment by ikkev** [comment]
> Right now you can set "required": true for a relation attribute so the validation layer requires an id to be passed for the relation.
> 
> This however doesn't check if the id is valid to avoid any perf impact for now. We will soon be reviewing all the attribute options in the content-type-builder to clean them up

This workaround breaks the delete functionality for me.

**Comment by ByungJun25** [comment]
@Morantron Well, In my case, I created custom code for checking the relation entity in service layer and used it in model lifecycles.  if there is no value then I throw the Error object. Then it will show the error message like below. 

![image](https://user-images.githubusercontent.com/10557621/88900016-14b6e000-d24f-11ea-8a34-fb2597a3a2fb.png)

I hope my solution help to you.

Here is Sample code.(case: onetoone)
1. service
```
const _ = require('lodash');

hasChild: async (parent) => {
  if(_.isNil(parent.child)) {
    return false;
  }
  return true;
}
```

2. model
```
const _ = require('lodash');

async beforeCreate(data) {
  if(!await strapi.services.test.hasChild(data)) {
    throw new Error('Entity is required!');
  }
}
```

**Comment by Morantron** [comment]
thanks @ByungJun25 !

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/required-relation-field/624/2

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/test-topic-please-ignore-me/943/3

**Comment by bglidwell** [comment]
Some interesting things to note.

If you go into the model for a collection type and add 
```
required: true
```

It will seem to work on sqlite. Relationship data will be required on requests both in REST and GraphQL endpoints.

However, there is an issue with Postgres (and perhaps others) related to how records are actually inserted. 
Users will see a strange GraphQL error (or REST) where insert into the collection type failed because null value violates not-null constant. 

Closer inspection to what's going on under the hood reveals strapi is first inserting a record to the database with all non-relationship fields filled out, then running an update operation to add the relationship data itself. So a "POST" action is really two independent executions to PG

This is the biggest current hurdle to implementing this, because when the first record is inserted (missing all relationship data), it will violate the not null constraints on graphql (because required is set to true and it is inheriting that config correctly) and throw an error, never actually adding the record in the database. 

Test:

1. Setup collection type with relationship
2. Go into collection type model settings.json config and set the relationship field option "required: true" 
3. using sqlite, attempt to post a new record to this collection type
   - with relationship field set to null, get error
   - with relationship field set to a value, it posts correctly 
4. using postgres, attempt to post a new record to this collection type
   - with relationship field set to null, get graphql error
   - with relationship field set to a value, get graphql error
   - set database to debug: true in options and look at queries when performing post. Notice separate insert/update actions

**Comment by derrickmehaffy** [comment]
Relocking, thanks @bglidwell

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/required-relation-field/624/4

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/required-field-option-not-working-on-media-fields/4070/2

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/specify-relation-column-as-required
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
