### ISSUE TITLE
Failure to start Strapi when trying to use Azure CosmosDB - MongoDB API

### ISSUE THREAD

**Issue by kjng** [strapi/strapi#5590]
**Describe the bug**
When trying to use Strapi with the mongoose connector and Azure CosmosDB (MongoDB API 3.6), Strapi crashes with an error. The collections `core_store`, `strapi_administrator`, `users-permissions_role`, and `users-permissions_user` do get created, but are not populated.

My Strapi instance in Azure connects to and uses MongoDB Atlas just fine.

When trying to debug locally using `strapi develop` pointed to an empty CosmosDB instance, I'm receiving the following error:

```
[2020-03-24T19:06:55.036Z] error Bootstrap function in plugin "users-permissions" failed
[2020-03-24T19:06:55.037Z] error MongoError: Error=16500, Details='
    at Connection.<anonymous> (...\node_modules\mongodb\lib\core\connection\pool.js:460:61)
    at Connection.emit (events.js:193:13)
    at processMessage (...\node_modules\mongodb\lib\core\connection\connection.js:368:10)
    at TLSSocket.<anonymous> (...\node_modules\mongodb\lib\core\connection\connection.js:537:15)
    at TLSSocket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:231:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:154:17)
```

My `database.json` is set up as follows:

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "mongoose",
      "settings": {
        "database": "strapi",
        "uri": "mongodb://..."
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**Steps to reproduce the behavior**
1. Set up Azure CosmosDB - MongoDB API resource
2. Add connection string to `development/database.json`
3. Run `strapi develop`
4. See error above

**Expected behavior**
I expect Strapi to work with CosmosDB similarly to a MongoDB Atlas instance.

**System**
- Node.js version: 10.19.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database: Azure CosmosDB with MongoDB API
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
Technically CosmosDB is not entirely MongoDB (even with the API implemented) It's not on the list of supported databases, and may not fully work with the ORM being used (mongoose).

Likewise when it comes to bookshelf (SQL ORM) and other databases besides PostgreSQL, MySQL, MariaDB, and SQLite are all supported by Strapi but SQL server is not. Strapi only includes support for widely used and common databases, others may not work, and are not supported currently.

**Comment by derrickmehaffy** [comment]
I'm marking this issue as closed as Strapi have stated they don't plan to support any additional databases and CosmosDB is not on the list of supported databases. If you feel this was closed in error please do reply back.

**Comment by stephenstroud** [comment]
@kjng Did you get this resolved, I'm also exploring Strapi with Cosmos Db and running into basic connection problems. I see others have had success connecting.

**Comment by kjng** [comment]
@stephenstroud No, I ended up switching to using Azure Database for PostgreSQL server.

**Comment by michallaskowski** [comment]
@stephenstroud can you link some sources? I was thinking about using Cosmos Db, but I am considering Postgres.
Deployment options doc mentions Cosmos, so is there some combination (using bookshelf?) that it may work? https://strapi.io/documentation/v3.x/deployment/azure.html

**Comment by stephenstroud** [comment]
@michallaskowski I also saw in the docs when I went through the deployment process. On the deployment process It's shame that the Web App in Azure isn't recommend. It was a lot of work to go through setting the deployment up which felt unnecessary. I went to Postgres in the end, however, wanted Cosmos DB for the new serverless pricing model. I've put a feature request in for CosmosDb if you could upvote it! I did think it would be a lot of work to get it working. 

I initially used this source to try out Cosmos Db https://www.cicoria.com/strapi-open-source-api-cms-using-cosmosdb-emulator/ 

however, the boilerplate has changed slightly since the publication.

**Comment by michallaskowski** [comment]
@stephenstroud 
> I've put a feature request in for CosmosDb if you could upvote it! 
Can you link it here? I am happy to upvote.

**Comment by derrickmehaffy** [comment]
> @stephenstroud
> 
> > I've put a feature request in for CosmosDb if you could upvote it!
> 
> Can you link it here? I am happy to upvote.

It would need to be approved by @Aurelsicoko on the product board (not all requests are added, they have to be approved and added manually)

**Comment by rfamans** [comment]
I got Strapi to work perfectly  with MongoDB driver and localhost CosmosDB Emulator. I also had problems with initial Strapi schema creation of permission collections. It turned out that creation of these collections takes more than 400 RU. Once this limit is reached, the Strapi schema building process is aborted. After starting CosmosDB emulator with the /DisableRateLimiting option, the Strapi schema creation just went like a charm. Everything works. I suspect that if you are using Cloud based Azure CosmosDB, it will also work just fine if you ensure that the default resource unit limitation for new containers is increased to a higher default. 

Pity that the Strapi team thinks that CosmosDB is not important enough to support officially. Everything seems to work just fine so why not support it officially? Larger companies that may become their paying customers and that have a policy that keeps them confined within the Azure ecosystem will have no other choice than to look for other options.

**Comment by derrickmehaffy** [comment]
> Pity that the Strapi team thinks that CosmosDB is not important enough to support officially. Everything seems to work just fine so why not support it officially right away?

The short answer to this @rfamans is not that we do not deem it important enough but simply that we cannot reliably automate the testing process and we prefer to only support similar open source databases. While it may work, and the user could use it if they wish we simply do not personnel bandwidth and developer time to manage every proprietary database a cloud provider may offer.

For example MongoDB Atlas already has a fully managed solution on Azure for those that need to remain within the Azure ecossytem, while also using one of our officially supported databases. https://www.mongodb.com/cloud/atlas/azure-mongodb

The example you provided above about resource limitations causing the query to abort is quite simply one of the various issues that we do not wish to incur the time required to debug and split our code base to handle.

---

As mentioned above, at this time we have no plans to support the Azure CosmosDB as there are alternatives for using MongoDB proper as well as various SQL databases on Azure. Thank you for the feedback.
