### ISSUE TITLE
Deploy Strapi build folder to heroku/other hosting as static artifact

### ISSUE THREAD

**Issue by asherccohen** [strapi/strapi#5634]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Is it possible to deploy a Strapi application to Heroku after it's been built on CI/locally? What I expect is to deploy the build folder and let heroku/other hosting platform handle everything.

**Your suggestions for this topic**
strapi build should make a deploy-able folder that can be hosted statically on heroku.

**Additional context**
The main reason for this is to make Strapi part of a monorepo, like NX (i'm writing a plugin for this to be possible) and simplify deployment where no build step is done on Heroku. The concept is that nx dev uses builders and handles creating the bundle artifacts to be pushed to the server.

**Comment by derrickmehaffy** [comment]
This is not currently possible as the backend isn't "built" and has no plans to be. It needs to be ran as it's own service.

The admin panel can be built and "hosted" by the Strapi backend, or somewhere else.

**Comment by asherccohen** [comment]
Thank for the answer. So, what is the 'built' admin panel?does it make any difference to build that locally and host it on an already installed strapi backend?
When I make a change to the develop version this needs other folders, not only the build folder, right? So I can't have a strapi instance installed on heroku and only push the built admin panel folder, if I'm correct.

**Comment by derrickmehaffy** [comment]
`does it make any difference to build that locally and host it on an already installed strapi backend?`

Nope you could build that locally and push the build folder into Git.

`When I make a change to the develop version this needs other folders, not only the build folder, right?`

Yes exactly.

`So I can't have a strapi instance installed on heroku and only push the built admin panel folder, if I'm correct.`

Yes because models are stored in files (specifically the api folder) and Strapi needs to restart to see these.

**Comment by asherccohen** [comment]
Thanks. I might come back to this once I've explored a bit more. Great job!
