### ISSUE TITLE
Migration from version 3.0.0-beta.18.7 to 3.0.0-beta.19

### ISSUE THREAD

**Issue by UmairAshrf** [strapi/strapi#5686]
**After upgrading to latest strapi beta version from 3.0.0-beta.18.7, login credentials for all users stopped working. **

**System**
- Node.js version: 
- NPM version: 6.4.1
- Strapi version: 
- Database: mysql
- Operating system: windows

**Additional context**
I was using 

> strapi\node_modules\strapi-plugin-users-permissions\controllers\Auth.js

 for authenticating my users before in version 3.0.0-beta.18.7. It was working fine. But when I upgraded to latest version suddenly users couldn't log in using their credentials. 

I thought may be the issue was coming because of jwt tokens but when I investigated further, code in **strapi\node_modules\strapi-plugin-users-permissions\controllers\Auth.js**  had changed. 

to be specific this line was changed. 
`const query = {};`
to 
`const query = {
        provider,
      };
`
I was able to fix the issue by adding provider in my users-permission_user table. But I couldn't see that information in the migration guide.

**Comment by alexandrebodin** [comment]
Hi @UmairAshrf 
The provider property is a field that is here by default. If you didn't have it in your DB it certainly is because you removed it from the model at some point ? 

You should always avoid removing fields from plugins or internal models to avoid breaking some internal behaviors. This change was not a breaking change when we tested it on existing apps.
