### ISSUE TITLE
Add align Text Buttons into WysiwygBottomControls 

### ISSUE THREAD

**Issue by aasyria** [strapi/strapi#5823]
in some languages like Arabic, you need to right text from right to left and there is no text-align button to manage that. 

here some information :
strapi uses draftjs for rich text.
https://draftjs.org/docs/advanced-topics-text-direction/#text-alignment

**Comment by lauriejim** [comment]
Hello @aasyria 
Can you please submit a PR to fix this issue. 
Thank you.

**Comment by Cr0s4k** [comment]
Started this in https://github.com/strapi/strapi/pull/7736 !, but no finished

**Comment by tanmoyopenroot** [comment]
Hey @lauriejim ,
Currently we are using `draft-js` in `Rich Text Editor` which  we export  as `markdown` [Line](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js#L627).

But `markdown` does not support text-align `center` or `right` and `text direction (rtl)`.
One way is to export it as `html` and save it in the database rather than saving it as `markdown`.
But this might lead to `break-in change`

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?

**Comment by derrickmehaffy** [comment]
should be fixed in the v4

**Comment by bondai-fahad** [comment]
Not fixed in the v4

**Comment by derrickmehaffy** [comment]
> Not fixed in the v4

Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
