### ISSUE TITLE
Enumeration fields can't support Unicode

### ISSUE THREAD

**Issue by TechQuery** [strapi/strapi#5909]
## Describe the bug

**Enumeration fields** only accept English characters, not Chinese or other **non-ASCII characters**.

## Expected behavior

We can input any **Unicode characters** in Enumeration fields configuration.

## Screenshots

![image](https://user-images.githubusercontent.com/19969570/80012545-0e062780-8500-11ea-9f09-a744aff88999.png)

## System

- Node.js version: 12.16.1
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.19.5
- Database: SQLite
- Operating system: Windows 10 Pro 1909

**Comment by derrickmehaffy** [comment]
Please see this discussion (restricted by regex due to graphql) https://github.com/strapi/strapi/discussions/4780

**Comment by pjoshi-dev** [comment]
Hi @derrickmehaffy could you please share the correct link for #4780 above. Link seems broken. 

And the issue is still faced by me while saving unicode characters... do we have any workaround for this at this moment? 
Please note that unicodes can be saved in Short/Long Text fields but only Enumeration field type give error. 
![Screenshot 2023-01-05 at 8 37 39 AM](https://user-images.githubusercontent.com/111184329/210692661-4591b9ba-2acf-4891-a736-421fe6657103.png)

**Comment by derrickmehaffy** [comment]
I can't find the new reference but it relates to https://github.com/strapi/strapi/issues/7904. We do plan to have a label/value system eventually similar to this plugin: https://market.strapi.io/plugins/strapi-plugin-multi-select
