### ISSUE TITLE
Add Brotli compression

### ISSUE THREAD

**Issue by Heziode** [strapi/strapi#5910]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

Currently, Strapi only supports gzip compression. [Brotli](https://github.com/google/brotli) give more lighter data.

This should already be supported by [koa-compress](https://github.com/koajs/compress), because it uses [zlib](https://nodejs.org/api/zlib.html#zlib_options).

**Comment by lauriejim** [comment]
Hello @Heziode!
Thank you for this insight.
I ping @alexandrebodin to have his point of view on this.

**Comment by alexandrebodin** [comment]
Yes the compress strapi middleware doesn't take any config but it would be really easy to add. This could be a great first pr ;)

**Comment by diogotcorreia** [comment]
Just want to point out that if you're using a reverse proxy like Nginx, it might be better to use compression there than on node due to performance reasons.  
Check you this [excellent resource](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/production/delegatetoproxy.md) by the `nodebestpractices` repository.

With that said, go ahead and add it. It might fit someone's needs perfectly ;)

**Comment by derrickmehaffy** [comment]
Closed as PR above added it
