### ISSUE TITLE
Deploying Postgresql Issue Digital Ocean

### ISSUE THREAD

**Issue by stiveurkel** [strapi/strapi#5956]
EDIT: I know there are issues on this already but I've read them all and none of them actually helped solving this issue.

Hi there,

**Describe the bug**
I have deployed my full stack application on digital ocean.
Font end -> NextJs
Back end -> Strapi

I have done all the configurations. Whenever I run `npm run develop` on my digital ocean droplet I can see my admin panel with my development database. However wheneve I run my pm2 start and try to reach my website backend url it shows a 502 error.

I have tried everything so far, modifying the pg_hba.conf file, adding ssl: true in strapi settings and/or in strapi options in the database.json config... nothing works.

I use letsencrypt to create a ssl certificate for my website.
Here are the error logs:
![image](https://user-images.githubusercontent.com/42664988/80309142-4db86200-87d3-11ea-8f81-b016a60d2a46.png)
 

Here are my configurations:
production/database.json
![image](https://user-images.githubusercontent.com/42664988/80308461-7f2f2e80-87cf-11ea-8483-8de1b358bdb4.png)

pm2 ecosystem.config.js
![image](https://user-images.githubusercontent.com/42664988/80308499-b69ddb00-87cf-11ea-94e3-76935e71f6a1.png)

**System**

- Node.js version: 12.16.2
- NPM version: 6.14.4
- Strapi version: v3.0.0-beta.20
- Database: postgresql
- Operating system: linux amd 64

**Comment by derrickmehaffy** [comment]
Please clarify which version not just "latest" `Strapi version: latest`

**Comment by stiveurkel** [comment]
> Please clarify which version not just "latest" `Strapi version: latest`

I have the v3.0.0-beta.20

**Comment by stiveurkel** [comment]
Whenever I try to log in on my droplet it works fine
![image](https://user-images.githubusercontent.com/42664988/80348680-73df1000-886e-11ea-9971-22bd66d57d1c.png)

But again as soon as I run in prod it shows the error about pg_hba.conf (which I have changed to allow all users, all DB, on port 0.0.0.0/0 md5 for testing purpose

**Comment by RNCTX** [comment]
Are you using DigitalOcean's managed database service? It looks like you might be from the screenshots. I'm not a Strapi dev but google put me here when I was looking for settings guidance, so having been a DigitalOcean customer I'll help ;).

**If you are using DigitalOcean's managed database service:**

The "doadmin" account that DigitalOcean provides is like the "postgres" user on a bare-metal server install.  It's the main database admin account that owns the default "postgres" database and has global "all" permissions.  

You should make another database for your app, and make another database user that owns it, because you cannot modify the "doadmin" account.  Note that under one of the tabs you can also make a pool and a user that owns the pool, if you choose, which gives you some additional connection optimization choices.

DigitalOcean provides a public hostname for the database that SSL is required to connect to, and a private network between your droplet and your database that does not require SSL.  You should use the private network that does not require SSL, there's no reason to go out to the internet over SSL and then back in to your database.

It sounds like you may have installed postgres on your droplet as well.  If so that has nothing to do with the DigitalOcean managed database service connection details, which you can only change by adding a pool connection and/or adding a new user.

**Comment by derrickmehaffy** [comment]
Please see: https://github.com/strapi/strapi/issues/5696 and likewise the PR to the docs: https://github.com/strapi/strapi/pull/6050/files

I'm marking this as closed, if the above does not solve your error then please let me know and I'll reopen this.
