### ISSUE TITLE
How to change tableHeaders in a table of a model?

### ISSUE THREAD

**Issue by MateusSilveira98** [strapi/strapi#597]
**Node.js version**:  9.4.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.9

**Operating system**: Windows10

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
The strapi not allow me to change the tablesHeaders of a model. I can't find where to add or change tableHeaders. Right now it displays the first five in order of adition

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**
Be able to which data is displayed at the Table.

**Comment by soupette** [comment]
Hi @MateusSilveira98 .

In order to modify the admin you have to start your project in dev mode [see the CONTRIBUTING guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md).

Once you started your project in `dev mode`go to `my-project/plugin/content-manager/admin/src/containers/List/index.js`.

In the `render` function you have a `const tableHeaders` that sets the `Table` headers (indeed) so if you want to display custom fields just modify this line of code.

Good luck!

**Comment by soupette** [comment]
I'm closing the issue feel free to reopen it if needed
