### ISSUE TITLE
Nested lists in Rich text field (markdown) doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#6051]
**Describe the bug**

Nested lists in Rich text field (markdown) doesn't work

**Steps to reproduce the behavior**

1. Create a rich text field
2. Create a nested list
3. The markdown preview show just one list, without nested

<img width="1010" alt="Screenshot 2020-05-04 at 18 26 37" src="https://user-images.githubusercontent.com/1007051/80989356-20a02b00-8e35-11ea-8f28-1b5dd11c3a03.png">

**Expected behavior**

Show the nested lists:

<img width="1013" alt="Screenshot 2020-05-05 at 09 53 22" src="https://user-images.githubusercontent.com/1007051/81045341-4a4d6680-8eb6-11ea-98e7-c58b495b3337.png">

**System**

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.0.0-beta.20.1
- Database: MongoDB
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
@soupette I think this falls into the feature Request area yeah?

**Comment by abdonrd** [comment]
@derrickmehaffy @soupette I think this is a bug, since it is not showing the expected behavior.

In fact if I use a markdown previewer ([markedjs/marked](https://github.com/markedjs/marked)) on my website, it shows the nested lists with this Strapi field.

**Comment by soupette** [comment]
I think we could change the parsing compiler that we currently use. @abdonrd do you feel like making a PR?

**Comment by derrickmehaffy** [comment]
> I think we could change the parsing compiler that we currently use. @abdonrd do you feel like making a PR?

If that's the case I wouldn't mind seeing tables as well :p

**Comment by abdonrd** [comment]
> I think we could change the parsing compiler that we currently use. @abdonrd do you feel like making a PR?

Could you help me? I am not very familiar with React.

**Comment by abdonrd** [comment]
I understand that you use Draft.js, and the nested lists works in the [homepage](https://draftjs.org):

<img width="701" alt="Screenshot 2020-05-06 at 08 35 58" src="https://user-images.githubusercontent.com/1007051/81144559-9fe84880-8f74-11ea-9fe9-0532457fa881.png">

**Comment by abdonrd** [comment]
Also just found docs about nested lists in Draft.js:

https://draftjs.org/docs/advanced-topics-nested-lists

**Comment by apppel** [comment]
> 
> If that's the case I wouldn't mind seeing tables as well :p

We would also be interested in this!

**Comment by filipesmedeiros** [comment]
I'm checking this, and it seems the setup is Draft.js for the editor, but Showdown for the display and parsing, so I think the issue is with Showdown actually (check [this file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/converter.js)). Strange thing is: tables is activated (although they don't seem to work)

**Comment by filipesmedeiros** [comment]
After investigating for a bit, it seems that the issue is actually in Showdown itself, I think. In [this file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/previewWysiwyg.js), on line 184 we create the DOM "string" and then convert it back to an object format on line 196. Issue seems to be that nested lists and tables are not reconverted correctly, although the HTML is fine. See this picture (console.logs I added to that file)

![image](https://user-images.githubusercontent.com/26208850/81516696-b3a6fc80-9330-11ea-8669-181e4265fb4b.png)

I assume that at the top of this file we should also have styling specifically for the list depths and tables? But I'm not sure about this.

**Comment by joeczar** [comment]
Howdy, I'm also having a problem with lists in Rich Text. When I create a list it looks great in Strapi but the output has the list numbers directly next to the linebreak "\n1." causing the markdown and the linebreaks not to render.

`body: "I'd like to document my learning goals and I thought creating an app would be a cool way to do it. I read about Strapi.io and thought it could be a good tool to get me up and going quickly.\n\nSteps\n1.  Get Strapi running in a moderately secure environment\n2. Create the goal API in Strapi\n3. Learn Next.js to build a Front End\n4. Build and deploy Front End"`

Where could I find an overview of where this is taking place. From this issue, it sounds like it's in Draft.js. I'll have a look through, but if someone could point me in a better direction, I'd really appreciate it.

 ![strapi rich-text list problem](https://user-images.githubusercontent.com/28707072/83125895-679ddb00-a0d8-11ea-8bfd-b894f8d65903.png)
![Next js goaltracker list proble,](https://user-images.githubusercontent.com/28707072/83125941-74baca00-a0d8-11ea-9d4b-2005f454fe0c.png)
![Nextjs goaltracker list problem](https://user-images.githubusercontent.com/28707072/83125997-87cd9a00-a0d8-11ea-8a87-15b4f33166f2.png)


`

**Comment by soupette** [comment]
@filipesmedeiros honestly I don't know I have done a bit of digging too and showdown gives us the correct html. But I some point the conversion is not kept.

**Comment by iapain** [comment]
@soupette This is a regression in draft-js v0.11.x. You might want to track this: https://github.com/facebook/draft-js/pull/2460

**Comment by soupette** [comment]
Thanks a lot @iapain I'll upgrade draft-js when the release is made!

**Comment by tmalaher** [comment]
I've run into several similar/related markdown preview issues:

- tables render with just the cell text all slammed together as a single paragraph. The cell markers ("|" and "| ---- |") are gone and just the cell contents remains (but otherwise marked up inline as expected: bold/italic/etc.)
- tasklists display as normal bulleted lists (the checkboxes are MIA)
- inline code (backticks) just displays as normal text. The HTML shows that the span has a `class="code"` but it has no effect. This could just be a CSS problem.

When I publish my content and use showdown to render the markdown, using the same settings as found in strapi itself:

```javascript
{
                backslashEscapesHTMLTags: true,
                parseImgDimensions: true,
                simpleLineBreaks: true,
                simplifiedAutoLink: true,
                smoothLivePreview: true,
                splitAdjacentBlockquotes: false,
                strikethrough: true,
                tables: true,
                tasklists: true,
                underline: true,
                emoji: true
}
```

... the results are as expected.

So if there are two markdown parsers involved, or a round trip from MD->HTML->MD->HTML... then that's probably the explanation.

Note that the HTML that results from raw showdown is VERY different from the HTML displayed in the rich text *Preview* mode.

I would expect that the markdown rendering in the editor should be as close as possible to the finished product (modulo any CSS customizations made when displaying the published content). So if showdown is being used internally, just use the showdown output.
