### ISSUE TITLE
npx create-strapi-app behind a corporate proxy throws a 407 status code error

### ISSUE THREAD

**Issue by ramzizelfani** [strapi/strapi#6190]
Trying to create a strapi-app behind a corporate proxy using npx, I encoutered this Error while installing project dependencies
```
ERR! sharp tunneling socket could not be established, statusCode=407
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
../src/common.cc:25:10: fatal error: vips/vips8: Aucun fichier ou dossier de ce type
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/my-project/node_modules/sharp
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.24.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.24.1 install script.
```
As it is mentionned in the error log, it is clear that this is related to installing sharp package using node-gyp but there is nothing mentioned on the documentation on how to setup/configure create-strapi-app CLI behind corporate proxy to deal with this issue.
**PS:**  Behind Corporate proxy configuration is included in _~/.npmrc_ config file and npx works without any problems for other projects

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
I don't believe this is an issue with Strapi directly, I've seen some node-gyp errors before but it usually relates to an odd local user environment.

**Comment by carlsborg** [comment]
To add some color to this. I see the exact same error even when running the docker container, again in the corporate network. The issue seems to be that sharp module install first tries to download and install a pre-built libvips and if that fails it tries to build it and this build fails.

Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /srv/app/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.0/libvips-8.9.0-linux-x64.tar.gz
ERR! sharp self signed certificate in certificate chain

Now I suspect that though mine is failing because of a self signed cert in the chain OPs download is probably failing because of a corporate firewall or proxy setup. Either way, the sharp install tries to build vips..  and this invariably fails .. because libvips-dev isnt installed on his system (vips/vips.h not found), nor the docker container. 

Now you can install libvips-devel in a Dockerfile using strapi/strapi as a base image, or on your system natively and its STILL likely going to fail ... because the vips that comes with your distribution is old (it tries to include glib-object.h) and that thats why they created the prebuilt binary from what I can tell anyway.

So OP you need to either build libvips from source or download and install the prebuild manually. Or just use a cloud machine to do this build and hopefully that has a less restrictive internet connection. 

HTH.
