### ISSUE TITLE
Entity name plural instead of eg. Focuses/Focus > Foci

### ISSUE THREAD

**Issue by andylacko** [strapi/strapi#6300]
**Describe the bug**
Error in entity name, plural from `Focuses/Focus` to `Foci`
When setting table name LpSectorFocus it generates `LpSectorFoci`

**Steps to reproduce the behavior**

1. create entity in content editor
2. view name of entity

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7139923/82485178-54d54600-9adb-11ea-8f82-5ce1c500219b.png)

**Code snippets**
not needed

**System**

- Node.js version: 14.2.0
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database: sqlite
- Operating system: MacOs (hate windows)

**Comment by Brad-Christie** [comment]
Strapi [uses another library](https://github.com/strapi/strapi/blob/4b7fbadef506e0ae29b7d481a5685de1a9e10a42/packages/strapi-plugin-graphql/services/naming.js#L6) called [pluralize](https://npmjs.org/package/pluralize). And, if you can believe it, this was an [intentional pluralization](https://github.com/blakeembrey/pluralize/blob/master/test.js#L537).

And, for what it's worth, it appears foci is the [correct plural form](https://www.merriam-webster.com/dictionary/focus). ;-)

**Comment by derrickmehaffy** [comment]
(I also quite dislike the automated pluralize but yeah it is intentional)

**Comment by andylacko** [comment]
haha, thanks for teaching me english 😁
