### ISSUE TITLE
Admin Login Page - Changing Title

### ISSUE THREAD

**Issue by lpanjwani** [strapi/strapi#6364]
**Describe the bug**
Trying to change the admin login page's title. However, it is not working after adding custom `index.html` with new title in `myApp/admin/src`,

**Steps to reproduce the behavior**

1. Go to `myApp/admin/src`
2. Place new `index.html` with new title

**Expected behavior**
Title is supposed to change

**Screenshots**
![image](https://user-images.githubusercontent.com/10087186/82937876-f52adf00-9fa1-11ea-97f6-8c4a4e4c174c.png)

**Code snippets**
`index.html`:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- The first thing in any HTML file should be the charset -->
		<meta charset="utf-8" />
		<!-- Make the page mobile compatible -->
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="mobile-web-app-capable" content="yes" />
		<title>CMS</title>
	</head>
	<body>
		<!-- The app hooks into this div -->
		<div id="app"></div>
		<!-- A lot of magic happens in this file. HtmlWebpackPlugin automatically includes all assets (e.g. bundle.js, main.css) with the correct HTML tags, which is why they are missing in this HTML file. Don't add any assets here! (Check out webpackconfig.js if you want to know more) -->
	</body>
</html>
```
**System**
- Node.js version: v12.x
- NPM version: 6.14.4
- Strapi version: 3.0.0
- Database: Mangoose
- Operating system: Ubuntu 18.04 LTS

**Additional context**
None

**Comment by nicolashmln** [comment]
Is it working without any changes? I try to launch the `strapi develop --watch-admin` from the default 3.0.0 version and I have the same screen as you.
In the browser logs I have `[HMR] Waiting for update signal from WDS...` and that's it.

**Comment by cyp3rius** [comment]
Same as @nicolashmln. I've asked this question already on Strapi slack help channel.

**Comment by soupette** [comment]
Hello @cyp3rius @nicolashmln!
First of all you are facing two different issues:
1. When in development mode the admin panel does not request the correct backend URL
2. You are not looking at the right file in order to change to the page title.

Regarding the first point we will fix it very soon (@petersg83) is looking at it in the mean time, in order for you to keep developing you can change this [line](https://github.com/strapi/strapi/blob/123ce203e54e4faeb83807355257c9e2dc95fa39/packages/strapi-admin/admin/src/app.js#L137) to `backendURL: 'http://localhost:1337'` using the common customisation system. Once your developments are finished you will need to delete the customised `admin/src/app.js` file in your app will work just fine.

---

For the second point you need to customise the following files in the `./admin/src/containers/` folder:

- AuthPage
- HomePage
- MarketPlacePage
- PluginDispatcher


I hope it helps

**Comment by cyp3rius** [comment]
@soupette thanks for the workaround. Works now!

**Comment by nicolashmln** [comment]
Working for me as well, thanks @soupette !

**Comment by petersg83** [comment]
I'll look at it soon :)

**Comment by soupette** [comment]
I am closing this issue as #6398 has been opened and describes the bug more properly.

**Comment by lpanjwani** [comment]
Hi @soupette, The title tag is set in `index.html` in two places. However customization on either does not get picked up. The locations are under strapi-admin package with 
1) Root Index.html
2) admin/src/index.html
```
<title>Strapi Admin</title>
```

**Comment by seloner** [comment]
> Hello @cyp3rius @nicolashmln!
> First of all you are facing two different issues:
> 
> 1. When in development mode the admin panel does not request the correct backend URL
> 2. You are not looking at the right file in order to change to the page title.
> 
> Regarding the first point we will fix it very soon (@petersg83) is looking at it in the mean time, in order for you to keep developing you can change this [line](https://github.com/strapi/strapi/blob/123ce203e54e4faeb83807355257c9e2dc95fa39/packages/strapi-admin/admin/src/app.js#L137) to `backendURL: 'http://localhost:1337'` using the common customisation system. Once your developments are finished you will need to delete the customised `admin/src/app.js` file in your app will work just fine.
> 
> For the second point you need to customise the following files in the `./admin/src/containers/` folder:
> 
> * AuthPage
> * HomePage
> * MarketPlacePage
> * PluginDispatcher
> 
> I hope it helps

I am having the issue 1 . I tried to change the file you suggested in the  node modules but the problem still exists.
