### ISSUE TITLE
Rich Text no longer supports image upload

### ISSUE THREAD

**Issue by MRDRMUFN** [strapi/strapi#6520]
**Describe the bug**
The rich text editor used to support the following functionality that no longer available.

1. Insert Image button takes you to a modal to select from the media gallery but does not offer a way to upload an image from the modal. The modal doesn't support drop events. 
2. The editor itself no longer supports drop events.
3. Copy and paste image into editor does nothing. 

**System**
(used the quickstart template)
- Node.js version: v10.19.0
- NPM version: 6.13.4
- Strapi version: 3.0.1 (Stable) 
- Upload Config: Local File
- Database: Sqlite
- Operating system: Windows 10 (WSL 2)

~~Could be related to this [Commit #72c0a0](https://github.com/strapi/strapi/commit/e32dbdfa5952e8690f86f47c2314fc351a72c0a0) from a month ago.~~

**Comment by lauriejim** [comment]
Hello! Thank you for this report.
I think because of issues we have on this, these features have been removed.
I ping @soupette to answer this question.

**Comment by soupette** [comment]
We decided to remove the upload feature for the wysiwyg. But I'll try to see if I can enable it back.

**Comment by freddysu** [comment]
Hi,

1. The editor itself no longer supports drop events.
2. Copy and paste image into editor does nothing.
3. The editor itself no longer supports Markdown.

Has these 3 features been removed?
It's really inconvenient to use after upgrade.
I tried to replace current WYSIWYG with CKEditor but still it seems not supporting these 3 features.
https://strapi.io/documentation/3.0.0-beta.x/guides/registering-a-field-in-admin.html#setup

If I need these 3 features how should I do?

Thanks!

**Comment by soupette** [comment]
> Hi,
> 
> 1. The editor itself no longer supports drop events.

Since the editor does not support image upload directly it does not support drop events indeed
> 2. Copy and paste image into editor does nothing.

For the same reason explained in 1.

> 3. The editor itself no longer supports Markdown.
The editor still supports markdown and the preview has even been improved.

> Has these 3 features been removed?

These 3 features have not been removed in fact the upload has been replaced by the media library. So if you click on the image icon in the navbar of the wysiwyg you will see that the media library will open so you can choose a file amongst all your medias which is even more powerful, you will be able to also crop your assets.

> It's really inconvenient to use after upgrade.


> I tried to replace current WYSIWYG with CKEditor but still it seems not supporting these 3 features.

With CKEditor you'll need to configure the upload, take a look at our documentation you will find a guide which explain how to use the media library with CKEditor.

> https://strapi.io/documentation/3.0.0-beta.x/guides/registering-a-field-in-admin.html#setup
> 
> If I need these 3 features how should I do?
> 
> Thanks!
