### ISSUE TITLE
 Accessing non-existent property warnings after updating to Node v14.4.0 from 13.x

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#6526]
**Describe the bug**
Getting following warnings after upgrading NodeJS to `14.4.0`
```
(node:24385) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24385) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:24385) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:24385) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
```

**Steps to reproduce the behavior**

1. Update NodeJS to `14.4.0` 
2. Run `yarn develop`
3. See warnings

**Expected behavior**
It should not show warnings

**System**

- Node.js version: 14.4.0
- NPM version: NA
- Strapi version: 3.0.1
- Database: Mongo
- Operating system: MacOS

**Additional context**
May be related to this: https://developer.mongodb.com/community/forums/t/warning-accessing-non-existent-property-count-of-module-exports-inside-circular-dependency/3183

**Comment by derrickmehaffy** [comment]
Both node v13 and v14 are not supported by Strapi (yet) as Strapi only supports LTS versions and per [the Node website](https://nodejs.org/en/about/releases/)

![Selection_924](https://user-images.githubusercontent.com/8593673/83629239-98559880-a54e-11ea-8027-b3c831890434.png)

v13 (or any odd version of node) will never be LTS and thus will never be supported, whereas v14 isn't due to go into LTS until October of 2020, support for v14 will likely come a little closer to that time.

For now I'm marking this issue as closed.

**Comment by derrickmehaffy** [comment]
@kingIZZZY there is a PR to address this: https://github.com/strapi/strapi/pull/7409
