### ISSUE TITLE
Hidden field in component is displayed after restart server

### ISSUE THREAD

**Issue by yaroslavyal** [strapi/strapi#6547]
**Describe the bug**
The content manager plugin works incorrectly when I try to hide a field in a component. After restart server force to display hidden field.

**Steps to reproduce the behavior**
1. Install the new default Strapi project:
    ```
    yarn create strapi-app my-project --quickstart
    ```
2. Create a component with one field
3. Click 'Configure the view' in component
4. Remove field in the section 'Displayed Fields'
5. Save changes
6. Restart server

**Expected behavior**
The section 'Displayed Fields' in content manager does not display hidden field

**System**

- Node.js version: 12.13.1
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: SQLite
- Operating system: Linux

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
Can you please give me your use case. 
Quite not usual to have this.

**Comment by lauriejim** [comment]
Ping @soupette about this behaviour.

**Comment by soupette** [comment]
It's more a backend issue I think @Convly @petersg83 can you check?

**Comment by petersg83** [comment]
Hi :)
It's an expected behavior as we don't see the use case for this. Today if all fields are hidden and you want to create/edit an entry, you would see something empty like in the screenshots:


*before clicking the + button*

![before clicking the + button](https://user-images.githubusercontent.com/11708220/87671694-0a3a1800-c772-11ea-87a6-4abe1d4aa360.png)


*after clicking the + button*

![Capture d’écran 2020-07-16 à 14 38 12](https://user-images.githubusercontent.com/11708220/87671698-0c9c7200-c772-11ea-99eb-82789554de0f.png)

Can you explain more precisely what is your use-case please? How do you think it should be handled?

**Comment by sam-pires** [comment]
up 
@yaroslavyal is this issue still impacting you?

**Comment by antalex** [comment]
up
@sam-pires This issue affects me)

**Comment by derrickmehaffy** [comment]
can't reproduce on v4
