### ISSUE TITLE
Side menu does not scroll or expand with large numbers of Content Types

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#660]
**Node.js version**:
v9.4.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.10.1
**Operating system**:
Ubuntu 16.04 LTS

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
At 15 or more defined content types, the bottom of the admin menu on the left starts to become cut off and does not scroll or expand to show all menu items.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Create a new strapi project and add 15 or more different content types. Tested on the following browsers:

Chrome - v64.0.3282.167
Firefox - Quantum v58.0.2
Edge - v41.16299.15.0

![strapi-menu-cutoff](https://user-images.githubusercontent.com/8593673/36321802-5626cd06-1308-11e8-8d6c-2a047dc81cb1.PNG)

**What is the expected behavior?**

The left menu should either resize itself to fix all the items or scroll itself.

**Comment by derrickmehaffy** [comment]
Another possible solution as well Content Types should have the ability to be nested as well. IE you should be able to collapse the parent groups:

- Content Types
- Plugins
- General
- Ect

As well as possibly adding additional sub-parent groups under content types.

**Comment by redni** [comment]
I think it is worth considering "inheritance" in models. In my project I divide models into groups. Something like:

linguistics.sigh
linguistics.word

Unfortunately, Strapi turns it into very uncluttered names in the admin panel as well as in the GET itself, because it looks like this in the admin menu:

linguisticssigh
linguisticsword

and in GET:

GET localhost/linguisticssigh
GET localhost /linguisticsword

So I think that the system should group models that start with the same word. What in fact would look like this:

in the admin panel - collapse

Linguistics
  - Sigh
  - Word

In the link:

GET localhost /linguistics/sigh
GET localhost /linguistics/word

**Comment by derrickmehaffy** [comment]
I agree something like this would work in my case as well.
