### ISSUE TITLE
👉 Question: what are the main pain points you have using Strapi?

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#6634]
As of a year ago the Strapi Chief Product Officer @Aurelsicoko asked the community what their [main pain points](https://github.com/strapi/strapi/issues/3415) were and how critical these issues were to the rest of the community.

Once again the Strapi team wish to get the broad community feedback, so the question again this year is: **what are the main pain points you have using Strapi?**

Please try to be short and to the point and describe your use-case and why you feel this is an important issue. 

-----

### Instructions

- Please only post one pain point at a time.
- If your pain point has already been listed, make sure to **upvote it** instead of posting a similar message. A simple :+1:  will suffice.

### Template

- **Issue:** Please describe your issue.
- **Context:** Give more details about the use case.

Copy paste the following markdown template:
```markdown
### Pain point

**Issue:** 
Please describe your issue.

**Context:** 
Give more details about the use case.
```

-----

We look forward to reading all your comments. All contributions are welcomed, don't be shy 🙈

**Comment by marefati110** [comment]
### Not being optimal

**Issue:** 
Inadequacy of queries in relational databases

**Context:** 
The lack of optimization of queries causes high processing costs
This is especially true on the admin dashboard
The use of bookshelf also reduces software development

**Comment by iicdii** [comment]
### `strapi.query` is restricted

**Issue:** 
You can't freely use `and`/`or` when querying data, and you can't place polymorphic fields such as components on a conditional clause.

**Context:** 
When you find data by a default controller or default query in GraphQL you can't neither filter on polymorphic fields nor filter with mixed `and`/`or` operator.
So you need to generate custom controller, and build a custom query.
When you build a custom query, for example with mongoose, you need to build an aggregate every relations and components yourself.
This overshadows the advantage of a generic controller or the shadow CRUD feature in GraphQL.

**Comment by iapain** [comment]
### Better documentation

**Issue:**
It's quite often that documentation is either not up to date or lacks proper information.

**Context:**
Documentation.

**Comment by derrickmehaffy** [comment]
(This is a copy from the previous pain point issue)

### Split auth providers into plugins

**Issue:** 
Split and simplify adding additional 3rd party providers

**Context:** 
Make it easier to add new providers by splitting providers into their own packages as well as supporting alternative auth methods such as api keys, refresh tokens. I believe the plan would be to use passport.js and I think this should quickly be moved up in the list of "to-dos" for v4

**Comment by derrickmehaffy** [comment]
(This is a copy from the previous pain point issue)

### Ease non-technical user interaction with the database

**Issue:** 
Model/Field renaming doesn't rename the related table/column in the database, and likewise deleting a field or model doesn't clean up the database

**Context:** 
Instead it creates a new one and leaves the old one, instead of just simply renaming the old one to match. Strapi doesn't "clean" the database when fields are removed, related to #1114

**Comment by nkmnz** [comment]
### Internal API for AdminUI not documented – suggestion to go fully headless

**Issue:** 
The AdminUI uses an API that is different from that generated for consuming the content. This API has no (public) documentation, which makes it harder to contribute or develop. 
Even if it were documented, we would have thee exact same situation that led to the decoupling of the customer facing frontend in the first place, e.g. creating dependencies on a certain frontend framework, on a design systems and other highly opinionated stuff. 

**Context:** 
The Strapi Community is growing and people invest heavily in building client side applications for their endusers (simple blogs up to complex applications with a lot of business logic and interactivity). The Strapi Ecosystem could benefit a lot more from it's community, if it were easier to implement functionalities within the adminUI. Thus, decoupling the view layer from the functionality of the adminAPI could lead the same benefits for the ecosystem that the decoupling of the user-facing frontend generated for the users of strapi.

**Comment by aqaddoumi** [comment]
**Media Upload is Restrictive** 

**Issue**
Uploading a .glb model using the media upload generates a .bin file, which makes it unusable. After having a quick look through the code, it seems that the Upload plugin is modifying the files based on the MIME type. This is restricting strapi from being a CMS for files where other media files than the general images, videos are required to be uploaded by clients.

Uploading a file, should have a tick option to upload the file as is without modification.

**Context:**
Creating a WebXR CMS framework using strapi to provide the client with a configurable experience is being limited and needs work around because the client can not upload 3D models such as glb, usdz, etc. Which are essential for future VR/AR experiences.

**Comment by brasofilo** [comment]
### Import Export capabilities

**Issue:**  
There's no simple way to re-use content-type structures on another Strapi instance.  
Also, user generated content is not easy to backup.

**Context:**  
All contexts. Daily, weekly, monthly backups. Every time some major change is about to happen.

**Comment by bubsly** [comment]
Issue:
api.example.com/admin takes forever to load.

Context:
context is as above. its a ball ache.

**Comment by deadnight7** [comment]
### Document GraphQL Authentication flows
**Issue:**
I found it hard to understand the initial bit of login and registering users with GraphQL mutation and passing bearer tokens in GraphQL for subsequent forbidden/authenticated routes 

**Context:**

Have to look through Github issues for finding my answers on how do we use login mutation using GraphQL Plugin - 
- For login mutation - https://github.com/strapi/strapi/issues/5304#issuecomment-590308817
- For passing bearer token - https://github.com/strapi/strapi/issues/3530#issuecomment-506877633

Could have been better and saved my time a lot, if we could have added it in GraphQL Plugin Docs on stapi.io https://strapi.io/documentation/v3.x/plugins/graphql.html

**Comment by sam-cross** [comment]
### Admin interface responsive design/mobile view

**Issue:** 
Strapi's Admin interface is built for desktop and does not scale down.

**Context:** 
I'm planning to use Strapi for client's websites but some of them may be using a mobile device as their main platform. I would like the Strapi admin interface to be responsive so that I can hand off websites to clients without telling them they have to use a desktop to edit content effectively.

**Comment by sam-cross** [comment]
@bubsly I don't have your issue. Strapi has been very fast for me. Maybe it's your server provider?

**Comment by Gusterson** [comment]
### Self-referencing relations

**Issue:** 
Adding a many-to-many self-related reference requires 2 new fields in the collection, and confusion as to which should be used in the admin.

**Context:** 
Would be extremely helpful to have one field on my "Articles" type that allows me to relate to other "Articles"

**Comment by Gusterson** [comment]
### Can't add related items from another collection

**Issue:** 
No ability to create related items when adding an entry.

**Context:**
 Say, for example, a Tags item related to an article. Not being able to create new tags on the fly (from the Article entry) makes it a no-go for my clients.

**Comment by Md-Mudassir** [comment]
### Not able to access basic user details (email, name, image) in Google Auth after successful login

**Issue:** 
in response, it provides only``id_token``

**Context:** 
Once the user logs in using Gmail, I cant display his name or email in its profile section in my website.

**Comment by DebarunMitra** [comment]
>### **Provider Login not giving the user credentials (Like: name, email image)after successful login**
**Issue:**
- Successful login returns only access token in callback URL.
- In Strapi admin panel user registration data also not visible.

**Context:**
- After successfull login with google oAuth2, only getting the user access token with callback redirect. 
- And the user registration details are also not visible in the strapi cms.

**Comment by aksdevac** [comment]
###  No Proper Typescript Support

**Issue:**

- Poor intellisense
- Can't specify types, can't use optional chaining etc.

**Context**

- It will give better intellisense, & we can use all typescript features which are missing or upcoming in Javascript.

Consider adding Typescript support also provide guide & if possible, Library rewrite in Typescript.

**Comment by SuddenDev** [comment]
### Customization / Plugin Development is too complicated

**Issue:** 
One of the main things, that made Wordpress so big and successfull, was the ability for the community to acually extend the functionality quite easily. Don't get me wrong; I wouldn't want to see such a wild west situation as with WP where plugins just make a installation sluggish and almost unusable, but it helps to get more functions quicker. It would also lift some burden of the Strapi team.

**Context:** 
Also the "Marketplace" is quite unusable atm imo, since it just has the six core plugins.

**Comment by daxyonis** [comment]
### Admin UI does not protect data model from non-tech users errors

**Issue:** 
Currently if you give access to the admin panel to non-tech users, they could very well mess up your API

**Context:** 
The admin UI should have superusers (the devs) and normal admin users with lesser permissions. For instance, they could only create new entries of each content type and not change nor delete the content types...

**Comment by nkmnz** [comment]
### Relationships should be able to hold properties

**Issue:** 
Relationships cannot hold hold properties. Instead, they have to be stored and accessed via a separate content-type.


**Context:** 
If you have a complex relationship between two entities, you have to create additional content-types that store the properties of those relationships, just like you would have to create a new table in SQL a database. But the UI-logic of a (headless) CMS should not follow the logic of relational databases, but the logic that is expected by the user or that facilitates the use. 

The adminUI get's less overseeable, and non-technical editors and administrators cannot easily follow the logic behind a content-type, that has no meaning for itself, but only connects to other content-types – e.g.: a User has to be connected to a Course by a content-type CourseMembership in order to store information about the terms of the membership, such as the period of validity. It's also getting less clear for developers how to structure the code – should the business logic be handled by customized controllers of the User-, the Course- or the CourseMembership-content-type?

This is very simple example, but it get's pretty messy pretty fast if you just think about relationships that could have a relationship as a property... 

I know that, in the context of this issue, discussions about SQL vs. NoSQL could arise, and how Strapi handles the latter similarly to the former, but I'd like to emphasize that this issue is more about the usability of Strapi for more than simple blogs. Low-tech-users won't care about the underlying technology as long as they can create the a model in a way that fits their understanding of the real world and that leads to a good usability of the adminUI.

**Comment by derrickmehaffy** [comment]
### Standardize Parameters

**Issue:** 
Currently Strapi is not using any known/recognized standard for parameters/filtering (on REST, GraphQL is a bit more open ended)

**Context:** 
Much of the context is included in my discussion: https://github.com/strapi/strapi/discussions/4906 but in summery of that wall of text:

Strapi doesn't have a good means of choosing between $and and $or based filtering, which is by far the largest issue that I see most commonly asked on both Github and Slack. Among that, the swagger docs plugin doesn't even entirely work properly due to how filtering is handled using a suffix filtering system concatenated onto the field name IE `date_gte=whatever` meaning we would need to populate the entire list of field with all possible filters for each CRUD operation in the swagger spec and this just doesn't make sense.

I think we need to handle what I know will be a massive rewrite and restructuring of the parameter system in v4, as I do believe that maybe it wasn't a good fit in the v3 (too much to do in a short amount of time), however with the release of the stable version and a "no due date" for v4 means it leaves us in the perfect time to start making breaking changes again without affecting users in production.

**Comment by michisp** [comment]
### No conditional logic for fields

**Issue:** 
Currently it isn't possible to show certain fields if another field matches a specific value.

**Context:** 
Sometimes it's necessary to show certain fields dynamically to hide fields that will not be available on the frontend. E.g. an enumeration-field with the values "text" and "image" should show different fields.

**Comment by dhazeley** [comment]
### Media Library has no folder/directory structure

**Issue:** 
Files uploaded to the media library cannot be sorted into folder or directories and are all saved directly on the top level. This makes it very hard (impossible,  really) to use for large amounts of data assets.

**Context:** 
I am using Strapi to organize a database of over 700 products. Each product can have 5 to 20 images associated with it. Having this many images on the top level is absolutely unusable and makes it extremely hard to organize my assets.
On top of that, I also have a blog. I want to store blog assets in the media library as well, but since I have those 7000+ images without any directory structure, the blog assets get completely lost in the media library.

**Comment by JKortmann** [comment]
### Missing relations between `components` and `single types`

**Issue:**
ATM it is not possible to create a component that is relating to a single type.

**Context:** 
This would be very handy when e.g. creating dynamic navigations or footer. When having a collection type (e.g. Navigation Categories) that withholds categories for a navigation that uses components for storing links to other pages. I only got it working by manually typing in the URL of the single type.

**Comment by derrickmehaffy** [comment]
I am going to close and lock this issue as we have passed the timeframe for requesting responses. This will give the Strapi team time to review and make plans for the v4.

Thank you to everyone you posted your response, and thank you to those to added your votes.
