### ISSUE TITLE
SDK JS with GraphQL support - addon comments

### ISSUE THREAD

**Issue by lordzpipo** [strapi/strapi#6644]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

This is addon message for `SDK JS with GraphQL support`
In general usage, strapi api is good enough ( permission usage, api, etc)
but during development,  it's nightmare to intergrade the api for actual usage 

i am trying to use swagger ( documentation plugin ) - `full_documentation.json` to generate standard sdk using `nswag` / `swagger-codegen` / `openapi-generator`

basically it's almost there, but for `eq` request, will generate something like 
```
...
@param {number} [start] Skip a specific number of entries (especially useful for pagination)
@param {string} [] Get entries that matches exactly your input
@param {string} [ne] Get records that are not equals to something
...
```

see line 2 `[] Get Entries that matches...`
`=` or `eq` request will missing in doc
and also in actual function:
will got a part of code like:
```
if ( !== undefined) {
    localVarQueryParameter['&#x3D;'] = ;
 }
```
if should be `if (eq !== undefined)` (eq = variables name i think)
and `&#x3D;` in html is `=` symbol .

**Conclusion:**
Compare with boiler-plate in .net-core angular bundle, they offer a very good option to using nswag generate a complete js /ts sdk. 
This is a reason i wish to have this. 

Thanks for reading my request

**Comment by lauriejim** [comment]
Thank you for your message, I ping @alexandrebodin and @Aurelsicoko about this.

**Comment by denimamab** [comment]
Hello @lordzpipo @derrickmehaffy 
I came across the same problem and the reason of having openapi generator generating this javascript error
```
if ( !== undefined) {
    localVarQueryParameter['&#x3D;'] = ;
 }
```
is because this param name is dynamic and matches the fields name of your SingleType or your collection type. 

### Example : 
Collection type name : **events** _(Fields : slug : "String", points: "Number")_ 

So the field name can be either slug or points like that : 
**http://localhost:1337/events?slug=black-friday**
**http://localhost:1337/events?points=1000**
_________
The openapi generator converter tries to do that using the partial application proposal [ https://github.com/tc39/proposal-partial-application]( https://github.com/tc39/proposal-partial-application) and generates this definition for your GET endpoint : 
```
eventsGet: async (limit?: number, sort?: string, start?: number, ?: string, ne?: string, lt?: string, lte?: string, gt?: string, gte?: string, contains?: string, containss?: string, _in?: Array<string>, nin?: Array<string>, options: any = {}): Promise<RequestArgs>
```
The fourth arguments is representing what is going wrong on this conversion and generate on the query params mapping a javascript error like that 
```
if ( !== undefined) {
    localVarQueryParameter['&#x3D;'] = ;
 }
```

There is a workaround for that, on Strapi you can use the _where filter, that means you can remove from the definition the parameter and instead of having a url like : **http://localhost:1337/events?slug=black-friday** you will have a url like **http://localhost:1337/events?_where[slug_eq]=black-friday**
The only problem with that is the Strapi documentation plugin is not exposing the _where parameter on the swagger documentation. On the other hand, this workaround is a bit manual, so human intervention is mandatory unless someone pushes a modifications to the converter or the strapi documentation plugin. 

Hope it was clear

**Comment by derrickmehaffy** [comment]
Hello all, just going to drop this here: 

https://forum.strapi.io/t/discussion-for-filtering-sorting-paging-and-general-parameters-rewrite/43

Note that after I18N is released in a stable format in the next few weeks we will begin our v4 development phase, this is when we make breaking changes. Part of those breaking changes is completely refactoring our database  layer, specifically the filters system.

See: https://portal.productboard.com/strapi/1-roadmap/c/73-database-layer-v4

In our current v3 iteration we don't comply with the open-api spec, I can't make any promises that we will in v4 but it's certainly being taken under consideration. We have neglected our SDKs and we know it's a problem, we didn't see value in rebuilding all of the SDKs when we have extremely fundamental changes coming. 

All I ask is please give us some time, we are doing things slowly intentionally so that we can consider all possible variables. 

Cc @sam-pires / @JabStrapi / @alexandrebodin

**Comment by derrickmehaffy** [comment]
Current SDK is based on REST, this SDK isn't maintained by us but we recommend REST for the bulk of use-cases. Closing as outside our scope.
