### ISSUE TITLE
Load dot env before utils, allow setting STRAPI_LOG_LEVEL in env file

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#6693]
**Describe the bug**
If I set `STRAPI_LOG_LEVEL` variable in .env file it does not work because log utils are loaded before dotenv

**Steps to reproduce the behavior**

1. Set `STRAPI_LOG_LEVEL` in env file & see if it works

**Expected behavior**
Env vars from `.env` file should be loaded before starpi-utils logger

**System**

- Node.js version: 12.18.0 
- NPM version: Yarn 1.22.x
- Strapi version: 3.0.2 
- Database: Mongo
- Operating system: MacOS 10.15.5

**Comment by lauriejim** [comment]
Hello! thank you for reporting that, can you please submit a PR.
I will appreciate your contribution on this point.
Thank you.

**Comment by akhilmhdh** [comment]
@lauriejim @aksdevac STRAPI_LOG_LEVEL does work finely inside the logger of strapi. Checked the outputs. The logs is getting printed due to logger middleware which has default value as debug. To change the level in create/existing config/middleware.js add like this.
`module.exports = {
    //...
    settings: {
      logger: {
        level: "error"
      },
    },
  };`

 It can be also env.
Doc link:
https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations)

If you want I can submit a PR that checks for the process.env.STRAPI_LOG_LEVEL and take that as log level.

**Comment by aksdevac** [comment]
@lauriejim Hi, submitted PR #6701 but it might not fix issue, as middleware is overriding default log level as mentioned in PR &  by @akhilmhdh, but can be used for `STRAPI_LOG_TIMESTAMP`, `STRAPI_LOG_PRETTY_PRINT` etc

**Comment by rylax** [comment]
There is another way of making this work. Export your `middleware.js` with the **env** object and pass it a default. This way you can make sure your process.env will override it:

```
module.exports = ({ env }) => ({
    settings: {
        logger: {
            level: env('STRAPI_LOG_LEVEL', 'debug')
        }
    }
})
```

**Comment by derrickmehaffy** [comment]
> There is another way of making this work. Export your `middleware.js` with the **env** object and pass it a default. This way you can make sure your process.env will override it:
> 
> ```
> module.exports = ({ env }) => ({
>     settings: {
>         logger: {
>             level: env('STRAPI_LOG_LEVEL', 'debug')
>         }
>     }
> })
> ```

This is the correct method

**Comment by derrickmehaffy** [comment]
fixed in v4
