### ISSUE TITLE
Prompt on untouched Single Type edit form with datetime field.

### ISSUE THREAD

**Issue by ghoshSomoto** [strapi/strapi#6749]
**Describe the bug**
A prompt("You will lose all changes") pops up when navigating away from untouched Single Type with a set datetime field.
Extra info: if the field is not set the prompt does not pop up.
**Steps to reproduce the behavior**
0. Enter Admin panel
1. Enter content builder. Create Single Type with a datetime field. Save.
2. Click on the created Single Type in left menu and then navigate away to any collection type (no problem here).
3. Click on Single type in left menu again. Set the datetime value. Save.
4. Navigate anywhere, then back to Single Type and anywhere else again.

**Expected behavior**
No prompt when form is unchanged.

**System**
- Node.js version: node v12.10.0
- NPM version:
- Strapi version: 3.0.0 stable
- Database: 
- Operating system: Ubuntu 18
- Browser: Chrome Version 83.0.4103.97 (Official Build) (64-bit)

Tested in incongnito

**Comment by derrickmehaffy** [comment]
Please test with node version v12 or v10 as node version v14 is not supported: `Node.js version: 14`

**Comment by derrickmehaffy** [comment]
@ghoshSomoto I assume node v14 was the problem?

**Comment by ghoshSomoto** [comment]
@derrickmehaffy tbh I just didn't have the time to test it. When I get to it, if the problem persists I'll reopen.

**Comment by derrickmehaffy** [comment]
Sounds good, thanks!

**Comment by ghoshSomoto** [comment]
Same issue with node v12.10.0

**Comment by lauriejim** [comment]
Hello! Can you please record a short video of what you are doing.
This will help me to follow / understand each steps.
Thank you.

**Comment by derrickmehaffy** [comment]
Hello!
As we have not received any new or updated information in over 7 days we are marking this issue/discussion as closed. Should you have new information please feel free to respond and we can consider reopening it.

For others finding this closed issue and you have updated information, please open up a new bug report and simply reference this closed bug report so that we can get any new information you may have. If you have questions please refer to the [contributor's guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue) on opening issues.

Thank you and have a great day!
