### ISSUE TITLE
Updated heroku documentation

### ISSUE THREAD

**Issue by ericwindmill** [strapi/strapi#6880]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I haven't actually done those things above. 

It doesn't take much time in the Slack channel or here in the github issues to see that there are a lot of questions about deploying to Heroku (both with Mongodb and postgres). The documentation is not up to date AFAIK. The following things aren't covered:

- buildpacks. Do we need to use the node build pack? 
- procfiles. It seems that heroku is looking for a process called 'web', but there is no indication of what needs to be executed in the procfile under the web command
- debugging common problems (I've seen the h10 and h14 errors being discussed a lot on Stackoverflow and in the Slack channel)
- current documentation references files that are different / in different locations (specifically the `config` directory. file referenced in docs `"./config/environments/production/database.json"` doesn't exist)

This seems like a pretty big barrier to entry on an otherwise simple-enough product to grok that could be relatively easily solved.

**Comment by derrickmehaffy** [comment]
@ericwindmill Do you mind doing a PR?

Related to your points

- Not that I'm aware of
- Never seen the proc either
- This is normally because the user is starting the process on localhost and not using `0.0.0.0` most of these issues are because older users did not read the migration guide: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.19.4.html#listened-host-changed
- This guide is out of date, I had intended on submitting a PR for it but got busy (and I'm really familiar with Heroku in general, nor is it something I generally recommend for production usage)

**Comment by ericwindmill** [comment]
@derrickmehaffy As I read this, I did finally manage to get Strapi deployed to heroku. I had to use both the node build pack and a procfile. 

I don't mind putting in a PR, but I have some general questions that I need to solidify before I do so, because I don't want to put in the wrong information. I will follow up either here or with a PR when I have time.

**Comment by derrickmehaffy** [comment]
Absolutely I completely understand, honestly some of the best documentation I've seen is written by those learning it as they go. And if you have questions they can certainly be addressed in the PR too. By all means you are welcome to poke me on the Strapi slack as well.

**Comment by derrickmehaffy** [comment]
Most of this has been rewritten and this issue can be closed.
