### ISSUE TITLE
Uploading media not updating updated_at

### ISSUE THREAD

**Issue by monkeymosher** [strapi/strapi#6932]
**Describe the bug**
 When I update a record by uploading an image, it doesn't seem to trigger an update of the updated_at timestamp of that record.

**Steps to reproduce the behavior**

1. Edit any record from the admin section
2. Upload and add media to the record
3. Save the record
4. Image is added to the record but updated_at date is not updated

**Expected behavior**
Updating the content (including the adding of an image) of a record should update the updated_at timestamp.

**Screenshots**

Screenshots from a test run done on July 2, before and after uploading the image:

![Screen Shot 2020-07-02 at 1 25 42 PM](https://user-images.githubusercontent.com/4013355/86391529-f1a50a80-bc67-11ea-88c3-b77b29d84073.png)
-
![Screen Shot 2020-07-02 at 1 26 22 PM](https://user-images.githubusercontent.com/4013355/86391523-f073dd80-bc67-11ea-9664-7bd37a0d95ab.png)

**Code snippets**
N/A

**System**

- Node.js version: v13.12.0
- NPM version: 6.13.4
- Strapi version: 3.0.0
- Database: MySQL
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
This is because the actual model that has a relation to the media wasn't updated, the media entry itself was. Strapi doesn't control the updated_at/created_at they are automatically generated by the database itself, so if nothing on that table was updated then the date won't change.

You should have a field in the relation for the media file that also includes an `updated_at`. Marking as closed as this isn't a bug.

**Comment by monkeymosher** [comment]
Oh, makes sense. Thanks!
