### ISSUE TITLE
404 for  /users-permissions/init after upgrading to 3.1.0

### ISSUE THREAD

**Issue by jankallewulf** [strapi/strapi#7104]
I've updated my Strapi installation by changing all dependencies in the package.json from 3.0.4 to 3.1.0 and running nom install afterwards.

Installation has not thrown errors. But once I try to open my admin panel I receive a 404 in the debug mode:

[2020-07-21T19:34:35.751Z] debug GET /users-permissions/init (5 ms) 404

config/server.js does not include any fancy info:

module.exports = ({ env }) => ({
  host: env('HOST', '116.XX.239.31'),
  port: env.int('PORT', 1338),
});

Is this a known problem or have I done sth wrong while upgrading?

**Comment by derrickmehaffy** [comment]
Hi @jankallewulf,

The v3.1.0 release isn't quite ready for usage yet, there will be a migration guide posted and a release announced on the [Github releases](https://github.com/strapi/strapi/releases) page once it's ready to be used.

In the mean time I would suggest you stay on your current version, or you can upgrade to the current latest release v3.0.6, but since v3.1.0 isn't quite ready yet I'm going to mark this issue as closed.

Should you have any issues once the release is ready then please feel free to open an issue then.

**Comment by alexandrebodin** [comment]
@jankallewulf You can check this https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html to help :)

**Comment by jankallewulf** [comment]
@derrickmehaffy  @alexandrebodin you guys are amazing - thanks a lot for the fast replies :)
