### ISSUE TITLE
Enumerated values with "/" character break the graphql plugin

### ISSUE THREAD

**Issue by mattschlitz** [strapi/strapi#7234]
I'm using an enumerated value for timezone in one of my models like the following:

```"timezone": {
      "type": "enumeration",
      "enum": [
        "Africa/Algiers",
        "Africa/Bangui",
        "Africa/Cairo",
        "Africa/Casablanca",
        "Africa/Djibouti",
        "Africa/Harare",
        "Africa/Johannesburg",
        "Africa/Khartoum",
        "Africa/Mogadishu",
        "Africa/Nairobi",
        "Africa/Nouakchott",
        "Africa/Tripoli",
        "Africa/Tunis",
        "America/Anchorage",
        "America/Araguaina",
        "America/Argentina/Buenos_Aires",
        "America/Bogota",
       ...
      ]
    }```

When trying to start the server with the graphql plugin enabled, it breaks on the "/" character of the enum (and crashes).

**Comment by derrickmehaffy** [comment]
Yes this is indeed the case, and if you try to set these types of values within the Admin panel it would reject them due to the use of symbols. Currently GraphQL doesn't support various symbols within enum values and in your case it would probably be better to use a `oneWay` relation instead of an enum.

GraphQL uses the following regex to validate the enumeration values: `/^[_A-Za-z][_0-9A-Za-z]*$/` and anything outside of that is going to throw an error. Likewise Strapi doesn't support it either due to that limit. You can read more about this here: https://github.com/strapi/strapi/discussions/4780

For now I'm going to mark this as closed and refer you to that discussion.
