### ISSUE TITLE
[Roles & Permissions Plugin] OAuth2 Compatible Login

### ISSUE THREAD

**Issue by acomagu** [strapi/strapi#7348]
I request a OAuth2 compatible login way to API. It's useful when I use Postman or any other API tester because it can fetch JWT Token automatically before calling API if the service uses OAuth2.

**Comment by derrickmehaffy** [comment]
Hi @acomagu I will be marking this request as a duplicate as it relates to the following issue: https://github.com/strapi/strapi/issues/1819

We already have plans to eventually move to a provider system instead of grant/purest for 3rd party authentication and this request is already on our roadmap [ProductBoard](https://portal.productboard.com/strapi/1-public-roadmap/c/61-authentication-providers-sso). Thank you for making the request!
