### ISSUE TITLE
server.js url is hardcoded in the admin build and that is confusing

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#7419]
I am using this `server.js`:
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('URL', 'http://0.0.0.0:1337'),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET'),
    },
  },
});
```

In production, I am using a env value URL=example.com

this will make Strapi run on example.com and example.com/admin

But loading the admin panel will fail because:

```Mixed Content: The page at 'https://example.com/admin/login' was loaded over HTTPS, but requested an insecure resource 'http://0.0.0.0:1337/admin/init'. This request has been blocked; the content must be served over HTTPS.```

This happens because the admin panel has the URL built in in _build time_, where I wasn't using this env value.

Sure you could say that's the reason and my fix; but it's confusing that you can change the URL with an env value, but you can't really because it is hardcoded in the admin JS bundle.

**Comment by derrickmehaffy** [comment]
@laurenskling I can certainly understand the frustration. Let me try to explain how that key is used.

There are multiple parts of the application that use that specific key:
- The admin for connecting to the Strapi backend (since react is CSR)
- Upload plugin for references in absolute URL scenarios 
- Users-permissions plugin for 3rd party authentication 
- Email plugin for sending absolute URL links to users

When you start the Strapi backend and pass in the URL key it is used for those last 3 I mentioned above, and no matter what environment you are using the Strapi admin is never rebuilt (unless you are specifically in the `development` environment **AND** the admin `build` folder doesn't exist)

Similarly during the build process you also need to send that URL key as the admin is statically built and simply served as such, in order to allow for users to disable serving the admin from the Strapi backend and say for example serve the admin panel from something like netlify or some other CDN-like service it **has** to know where it's going to connect and without any access to the backend files, the only way to do that is to include the URL into the build.

If Strapi was using a SSR admin panel it would make sense to just load it from the config file during boot, but in the case of the current React CSR it needs to be built in, as in large scale cluster situations the chances of someone actually running 12+ instances of the build command and serving the admin from 12+ instances of the Strapi backend is very low. We have opted to make it easier to scale out Strapi and allow offloading the admin to a CDN and serving the admin panel from the backend as just an option (though default, to make it easier on local development)

**Comment by lauriejim** [comment]
Here is also a video about the process to work on the admin and backend deployment in 2 different servers.
This will also help to understand the process.
https://www.youtube.com/watch?v=cokPsdyFpTU&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=2&t=0s

**Comment by laurenskling** [comment]
Thanks for the extensive response. I've given it some good thought the last couple of days. The `url` key is just not made to accept a `env()` and the documentation doesn't say you should do that either. So it's just my over-enving that caught up with me ;) 

Keep up the great work!

**Comment by derrickmehaffy** [comment]
> Thanks for the extensive response. I've given it some good thought the last couple of days. The `url` key is just not made to accept a `env()` and the documentation doesn't say you should do that either. So it's just my over-enving that caught up with me ;)
> 
> Keep up the great work!

No problem, we know it's a bit confusing but over the next several months we will be doing a complete overhaul of the documentation so we will keep an eye out for anything like this that isn't described well :wink:

**Comment by mysterybear** [comment]
I'm just working on deploying a Strapi application into production. I saw this and a mental alarm bell went off. Is this `ADMIN_JWT_SECRET` safe to be exposed in the source repository?

For other secrets like database credentials, I'm using Google Cloud Build builders to inject a `.env` file from a secret from Secret Manager.

Thanks for all your hard work, Strapi's awesome! :))

**Comment by laurenskling** [comment]
That's the fallback. You could leave it out of your code when you know you are going to use the ENV var

**Comment by derrickmehaffy** [comment]
Indeed, it's randomly generated during initial project creation to prevent users from hitting an issue if they aren't familiar with the .env (just so they can register/login their first admin).

If you understand how to set your own, you can remove it and just keep the `env('ADMIN_JWT_SECRET')` which will have no fallback

**Comment by mysterybear** [comment]
@laurenskling @derrickmehaffy 

But why would we need control of this? It seems to make no difference whatever I use as the key here, so why not just generate a new key each time the service is spun up and then we don't have to worry about it?

I suspect I may be missing something obvious, so sorry about that in advance!

**Comment by derrickmehaffy** [comment]
@mysterybear if it was randomly generated everytime the application restarts it means when you go to create a content type, the cached JWT in your browser for the Admin would be invalidated and you would have to login every time you change a model.
