### ISSUE TITLE
[Webhook] Accept body content

### ISSUE THREAD

**Issue by raulfdm** [strapi/strapi#7567]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

## Request

Hello there.

So, I'm trying to setup a webhook using Github API to every Strapi update it calls the my actions workflow to rebuild my site.

After some investigation on github API, I've realized that the end-point used to dispatch events needs to accept not only headers but also a body with `ref: <branch-name>`:

```shell
curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/octocat/hello-world/actions/workflows/42/dispatches \
  -d '{"ref":"ref"}'
```

> Docs: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

In other words, I need to send the ref (branch, tag or commit SHA) I want to do that.

I tried this workflow and it works as expected. However I noticed that Strapi webhook **does not** allow me to add body content, only headers.

![Screenshot 2020-08-23 at 11 29 49](https://user-images.githubusercontent.com/12464600/90975387-faadac00-e533-11ea-9fb7-d99e420f4f81.png)

I'm not that familiar with webhooks, so I'm not sure if it's a pattern not being able to pass body but I didn't find any way to easily do that. Most of articles only shows Netlify or Gatsby cloud connections.

I realized that if I want to do that I'll need to create a tiny server (kinda middleware) which has this requested configured and register it in Strapi webhook but it seems weird having a third service to make it work.

## Ideas

I'm not sure about implementation but it might be ideal having this on the Webhook admin page or maybe a config in `./config/server.js`.

**Comment by derrickmehaffy** [comment]
Let me ping @Aurelsicoko and @JabStrapi as I do think we plan on doing a Webhooks v2 to add some additional features. :)

**Comment by anh-dang** [comment]
I really need this feature to trigger my CircleCI pipeline on a branch that is different from `master` branch

**Comment by raulfdm** [comment]
> 
> 
> I really need this feature to trigger my CircleCI pipeline on a branch that is different from `master` branch

As an workaround I create a bare minimum node server which accept only a request from my strapi server and proper trigger my GH actions, something like:

```
Strapi -> Tiny node server -> GH Actions
```

But it would be nice to having everything built in

**Comment by anh-dang** [comment]
> > I really need this feature to trigger my CircleCI pipeline on a branch that is different from `master` branch
> 
> As an workaround I create a bare minimum node server which accept only a request from my strapi server and proper trigger my GH actions, something like:
> 
> ```
> Strapi -> Tiny node server -> GH Actions
> ```
> 
> But it would be nice to having everything built in

Yea man I'm thinking about cheating with Google Cloud Function to do the work for me haha

**Comment by jessjohn** [comment]
Additionally it'd be great if we could choose to send _no_ body in the request too. 

Use case is that I'm trying to hit an external endpoint to redeploy a container using a Strapi web hook, and that endpoint is refusing the request because it contains a body. :)

Ideal use case (as mentioned above) would be similar to editing `./config/server.js` for custom headers.

```
module.exports = {
  webhooks: {
    defaultHeaders: {
      ...
    },
    defaultBody: null 
  },
};
```

**Comment by SuiOni** [comment]
Bump

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/customize-webhook-body
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
