### ISSUE TITLE
Display names for content manager layouts don't work for filters

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#7591]
**Describe the bug**
When changing display name in "Configure the view" tab, filters names don't change.

**Steps to reproduce the behavior**

1. Create content type with some fields
2. Go to "Configure the view" page
3. Change values of display names
4. Go to Content manager and try to set filters - display names do not change.

**Expected behavior**
It's expected that filters display names match values in whole view.

**Screenshots**
![image](https://user-images.githubusercontent.com/20924122/91159297-8e1be400-e6d0-11ea-8d9f-f9ef6a6acfe4.png)
![image](https://user-images.githubusercontent.com/20924122/91159327-98d67900-e6d0-11ea-8914-0eabac8814bb.png)

**System**

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: PostgreSQL
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
@soupette added it as a feature request unless you classify this as a bug, from the slack convo.

**Comment by soupette** [comment]
I agree it's more a feature request.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/use-ctm-display-names-for-filters
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
