### ISSUE TITLE
Create Components inside of reusable plugin

### ISSUE THREAD

**Issue by Svehla** [strapi/strapi#7640]
**Describe the bug**

First of all, thanks to your hard work and for such a good product like the Strapi is!

I want to create an open-source plugin that includes components in the database model but I'm not able to create `/components/{name}/{component name.js}` inside of my `/plugins/my-custom-plugin` folder. 

If you want to create some database relation inside of your plugin, you have to set `plugin` key like this one:

```javascript
// someModel.json
  "attributes": {
    "attr1": {
      "plugin": "my-plugin", // connection to the plugin
      "model": "my-model"
    },
```

But I'm not able to create some database relation with components (which are editable via content-type-builder)

```javascript
    "attr1": {
      "plugin": "my-plugin", // now it does not work  
      "type": "component",
      "repeatable": true,
      "component": "newsletter.newsletter-free-messages"
    }
```

**Expected behavior**
I'm able to create components inside of my reusable plugin.

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.7
- Strapi version: 3.1.3
- Database: sqlite  
- Operating system: MacOS

Thank you 🙏

**Comment by derrickmehaffy** [comment]
Hello @Svehla I've checked with our backend engineering teams and currently this is not possible, and for now we don't have any plans to add it. In this case it would be better to use a relation.

**Comment by derrickmehaffy** [comment]
Reopening as a feature request.

**Comment by jaszczw** [comment]
Hey @derrickmehaffy, could someone from maintainers take a look into #12965 - It's attempt to at least partially resolve the issue.

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy, could someone from maintainers take a look into #12965 - It's attempt to at least partially resolve the issue.

They should be reviewing some more PRs here shortly I think.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/components-inside-of-plugins
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
