### ISSUE TITLE
Components and dynamicZone are populated although the autoPopulate attribute is set to false

### ISSUE THREAD

**Issue by lnetanel** [strapi/strapi#7676]
**Describe the bug**
When setting the **autoPopulate** property in a dynamicZone / component the components are still being populated which causes the search to fail in case there are deeply-nested entities.

**Steps to reproduce the behavior**

1. Create an entity which holds a dynamic-zone attribute
2. Set the autoPopulate to false in that attribute
3. Click on the Entity name in the content-manager
4. Check the response from the API - It will also have the full entity of the dynamic-zone attribute

**Expected behavior**
The behavior should be to return only the "ref" objects and not the full populated object when the autoPopulate is set to false

**System**

- Node.js version: 12.18.3
- Strapi version: 3.1.4
- Database: mongodb

**Comment by derrickmehaffy** [comment]
Hello, as discussed on slack I'll ping a few people from our backend engineering for suggestions, they may need more information from you. @petersg83 @alexandrebodin @lauriejim if you have any suggestions.

For reference, I discussed with this user on our Slack and this relates to search time-outs due to the deep population. In his case he is intending to decrease this search timeout (populating too many relations). I assume in this case he can just override the controller and cut all population, but if there is a case where he needs to populate a specific component and not another it brings into question the related issue: 

https://github.com/strapi/strapi/issues/7454
https://github.com/strapi/strapi/issues/7360

I did suggest, where possible, to avoid using components and stick to just normal relations but in his case this isn't entirely possible.

**Comment by derrickmehaffy** [comment]
@lnetanel if possible, can you link your project repo on Github or pass it to me in a zip on slack?

**Comment by lnetanel** [comment]
@derrickmehaffy for more context, below is the model I'm using.
Where searching this model in the content-manager, the "context" attribute will always be populated and all it's nested entities of the specific component will be populated as well which dramatically decreases the performance of the search query.

{
"connection": "default",
  "collectionName": "steps",
  "info": {
    "name": "steps"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "context": {
      "autoPopulate" : false,
      "type": "dynamiczone",
      "components": [
        "activity.message",
        "activity.action"
      ]
    }
  }
}

**Comment by alexandrebodin** [comment]
Hello, Right now the autoPopulate is only for relations, interestign feature request though.

**Comment by lnetanel** [comment]
Thanks @alexandrebodin.
So what are my options? 
In short, I would like my entities not be populated when doing find/search request and fully populated when fetching a single item (e.g. in the content-manager item view)

**Comment by alexandrebodin** [comment]
The only current way to bypass this is to use the underlying mongo driver. useing something like this:

```js
const queries = strapi.query('modelName');
const mongooseModel = queries.model;
const mongoCollection = mongooseModel.collection;

// here you can run any mongo driver query.
mongoCollection.find({});

```

I hope this helps. We are going to review a lot of the db layer up to the end of this year to hopefully address a lot of the issues we have on that side

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
