### ISSUE TITLE
When entering slightly long descriptions for fields, they show up ellipsized and unreadable

### ISSUE THREAD

**Issue by Duckers** [strapi/strapi#7683]
**Describe the bug** 

When entering slightly long descriptions for fields, they show up ellipsized and unreadable

**Steps to reproduce the behavior**

Entering a slightly long descriptions for fields using "Configure the view" -> "Edit the field" -> Change "Description"

Go back to the editing view. The description shows up ellipsized and unreadable.

**Screenshots If applicable, add screenshots to help explain your problem.**

![image (1)](https://user-images.githubusercontent.com/664425/91909270-2efc3780-ecad-11ea-874f-4577b4d71b5f.png)

**System**

Single-click DigitalOcean droplet created today

**Comment by Cr0s4k** [comment]
![Screenshot 2020-09-02 at 16 22 36](https://user-images.githubusercontent.com/19715428/91996490-51d42d80-ed39-11ea-9497-d99f75ad5bd7.png)

That occurs since each different type of field has a size. In "configure the view" you can see those fields with different sizes.
In each row there's space for 12 units of size. And since you are using a row with IsTroubleshooterStart (that occupies 4), thats why it looks like text it is cut, its not expanded to 12, its done in this way for allow the admin to insert for fields in the same row in "configure the view" in a WYSIWYG way.

I dont really know how this can be improved, maybe multiline ellipsis? or allow admin to expand fields in the "configure the view" so it can take more space than is designed?

**Comment by maevalienard** [comment]
Thanks for letting us know. I guess being able to have multiline would be nice. I'll have a conversation with @JabStrapi to know when we can make a change for that bug :)

**Comment by HichamELBSI** [comment]
Hello, I'll close this issue since it has been fixed in the v4.
