### ISSUE TITLE
Ability to search with several independant words

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#7849]
**Please describe your feature request:**
In the Content Manager, when I use the search bar, I would like my words to be used separatetly.

**Actual behavior**
Content: "I love the ocean"
Search: "love ocean"
Search results: none

**Wanted behavior**
I want my content "I love the ocean" to be in the results

**Comment by derrickmehaffy** [comment]
Something, something "Meta" :stuck_out_tongue_closed_eyes:

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed.

**Comment by petersg83** [comment]
Are you sure @derrickmehaffy? I just tried and it doesn't seem to work

**Comment by derrickmehaffy** [comment]
Ah Aurelien and I were testing it yesterday and it was working

**Comment by benderillo** [comment]
@petersg83 @derrickmehaffy how do I even use the search? no matter what I type, it does not do a thing with my list view.
Which fields does it search in?

I have like a bunch of entries with text fields title and email field. I type an email address into the search, it sends the http request to content-manager with "_q=john.doe@void.com" but the listview is the same. I'd expect it would filter it or do anything at least. Tried title, same thing - nothing.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy As you mentioned, we tested it and it worked like a charm, could we close the issue?

**Comment by derrickmehaffy** [comment]
I believe what @petersg83 is referring to @Aurelsicoko is full text searching with multiple options. ATM we don't have a full text search option (`_q` isn't documented and not sure it will work properly on the content-apis)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/ability-to-search-with-several-independent-words
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
