### ISSUE TITLE
Number Object Id (Editable)

### ISSUE THREAD

**Issue by honey93** [strapi/strapi#7861]
Strapi MongoDB setup, can't customize (_id)objectId to numbers. Any workaround? It's a problem for importing Data. 
In Model Lifecycle hooks tried it, but it throws the error and wants the hexadecimal field only.

**Comment by derrickmehaffy** [comment]
At this time no, we do not support alternative `id`/`_id` names or data types, it is something we will look at in the future. See this FAQ entry: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#does-strapi-allow-me-to-change-the-default-id-type-or-name

I will be marking this issue as closed due to it not following our requirements to use a template, and currently the option isn't supported.

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
