### ISSUE TITLE
One on one relation allows new creation of entry

### ISSUE THREAD

**Issue by Ant-V** [strapi/strapi#7918]
**Describe the bug**
If you have a collection with a 'has one and belongs to one' relation to the users table, (even if you set the connection field as unique, even on both sides) if a user posts a new entry for that collection, instead of a duplicate key error, the entry gets added and the old connection is removed and only the new one is kept.

**Steps to reproduce the behavior**
Create collection with one field being a one on one relation to Users, and select Unique Key (or don't, theoretically one on one should make it unique by default)
Add an entry for a user
Add another entry for the same user
Add as many entries as you want to the same user, it's not like strapi is gonna stop you...

**Expected behavior**
Some sort of error to be thrown, instead of allowing this to happen

**System**

- Node.js version: 13.12.0
- NPM version: 6.14.7
- Strapi version: 3.1.4
- Database: MySQL
- Operating system: MacOS 10.15.6

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/disallow-changing-a-onetoone-relation-without-removing-the-relation-first
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
