### ISSUE TITLE
Tracking issue - Any issues related to the use of Node v14

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#7921]
# Node v14 tracking issue

This issue will be used to note any issues related to supporting the next LTS version for node. If you notice anything please post it here. Any other issues created will be closed, locked, and linked to this issue.

**Please note that Node v14 will not be supported until it's actual LTS release date** which you can find on: https://nodejs.org/en/about/releases/

![image](https://user-images.githubusercontent.com/8593673/93346171-88ee1880-f7e8-11ea-9f13-f5bff1f2b988.png)

## Template for reporting a bug

Please copy and paste the following markdown template, and fill it out.

```
- OS: 
- Node Version: 
- NPM Version: 
- Yarn (optional): 

### When did you encounter the issue

Example: during project creation, build process, when I uploaded a file, ect

### Link to issue project on GitHub or exact steps to reproduce

Where possible please test in fresh projects, and push those projects to a temporary GitHub repo.

**Comment by aksdevac** [comment]
- OS: MAC 10.15.6
- Node Version: 14.6.0
- NPM Version: NA
- Yarn (optional): 1.22.5
- Database (added) : MongoDB (as this is related to mongodb driver)

### When did you encounter the issue

Just start project using `yarn develop` & see warnings as shown below:
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53784) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:53784) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:53784) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency

### Context

Its due to bug in mongodb driver see: https://jira.mongodb.org/browse/NODE-2536
This is already fixed in version mongodb version `3.5.7+`, but strapi has locked mongoose version to `5.8.0` which depends on older mongodb driver (3.3.5), I have made pull request for updating mongoose but tests are failing
See pull: https://github.com/strapi/strapi/pull/7859, another pull from bot: https://github.com/strapi/strapi/pull/7916
tests are failing because blank username is not allowed now (error  Invalid empty username provided) See this mongoose issue: https://github.com/Automattic/mongoose/issues/8640

**Comment by aksdevac** [comment]
- OS: Mac 10.15.6
- Node Version: 12.18.4/14.6.0
- NPM Version: 
- Yarn (optional): 1.22.5
- Strapi: 3.1.5

### When did you encounter the issue

Got following warnings while installing/updating (yarn install) strapi using Node 12.8.4, it seems to be related to Node 14
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on `node v14+`. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on `node v14+` and could be using insecure binaries. Upgrade to fsevents 2.

**Comment by derrickmehaffy** [comment]
# DMehaffy's Node v14 checking of tests:

## Linux Desktop

Using:
- Linux Mint 20

### Tests

- [ ] SQLite
- [ ] MySQL 8
- [ ] MariaDB 10.5
- [ ] PostgreSQL 13
- [ ] MongoDB 4.4

## Linux Server

Using:
- Ubuntu Server 20.04
- Ubuntu Server 18.04
- CentOS 8
- RHEL 8.2

### Tests

- [ ] SQLite
- [ ] MySQL 8
- [ ] MariaDB 10.5
- [ ] PostgreSQL 13
- [ ] MongoDB 4.4

## Windows

Using:
- Windows 10
- Windows Server 2019

### Tests

- [ ] SQLite
- [ ] MySQL 8
- [ ] MariaDB 10.5
- [ ] PostgreSQL 13
- [ ] MongoDB 4.4

## MacOS

Using:
- MacOS Catalina 

### Tests

- [ ] SQLite
- [ ] MySQL 8
- [ ] MariaDB 10.5
- [ ] PostgreSQL 13
- [ ] MongoDB 4.4

# Notes

To be added later, as needed.

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/first-installation-issues/364/2

**Comment by derrickmehaffy** [comment]
@alexandrebodin @Convly @petersg83 

As Soupette has confirmed the frontend side, do you feel we need anything else from this?

**Comment by derrickmehaffy** [comment]
Safe to say v14 is LTS and no new issues have come up about this. Marking as closed.
