### ISSUE TITLE
Be able to use Sendgrid in Sandbox mode

### ISSUE THREAD

**Issue by gulipad** [strapi/strapi#7948]
Currently, if you want to use **Sendgrid** in Sandbox mode, you have to indicate so in every single email you send within Strapi, which feels a bit odd. The sandbox mode is an option that can be added in the `mail_settings` parameter when sending an email. It feels like it would be relatively simple to add this feature to the `strapi-provider-email-sendgrid`.

**Comment by derrickmehaffy** [comment]
Per the kitchen sink example from sendgrid's github:

https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/kitchen-sink.md

```
  mailSettings: {
    sandboxMode: {
      enable: true,
    },
  },
```

You should be able to customize the https://github.com/strapi/strapi/blob/master/packages/strapi-provider-email-sendgrid/lib/index.js file and add it in if you would like. I'm not sure if we can load this from the `./config/plugins.js` but you can give it a shot and see if it works for you :wink:

**Comment by gulipad** [comment]
> Per the kitchen sink example from sendgrid's github:
> 
> https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/kitchen-sink.md
> 
> ```
>   mailSettings: {
>     sandboxMode: {
>       enable: true,
>     },
>   },
> ```
> 
> You should be able to customize the https://github.com/strapi/strapi/blob/master/packages/strapi-provider-email-sendgrid/lib/index.js file and add it in if you would like. I'm not sure if we can load this from the `./config/plugins.js` but you can give it a shot and see if it works for you 😉

Thanks @derrickmehaffy, I was thinking of doing that, but I'd prefer not to modify the package so when updates come along we don't suffer issues. It's why I was thinking if it could be included as a feature.

**Comment by derrickmehaffy** [comment]
Please feel free to test and submit a PR :smiley:

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/be-able-to-use-sendgrid-in-sandbox-mode
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
