### ISSUE TITLE
Policies for custom api not being respected.

### ISSUE THREAD

**Issue by Daniloxax** [strapi/strapi#7970]
**Describe the bug**
Policies doesn't seems to be hit/triggered.

**Steps to reproduce the behavior**
1. Generate a controller with `strapi generate:controller otp` 
2. Generate a service with `strapi generate:service otp`.
3. Create folder `config` in otp directory and a file routes.json.
4. otp>config>routes.json 
```
{
  "routes": [
    {
      "method": "POST",
      "path": "/sendOtp",
      "handler": "Otp.sendOtp",
      "config": {
        "policies": ["isAuthenticated"]
      }
    },
    {
      "method": "POST",
      "path": "/verifyOtp",
      "handler": "Otp.verifyOtp",
      "config": {
        "policies": ["isAuthenticated"]
      }
    }
  ]
}
 ```
4.  In the terminal execute this line `strapi generate:policy isAuthenticated` .
5. In .api > config > policies> isAuthenticated.js
```
"use strict";

/**
 * `isAuthenticated` policy.
 */

module.exports = async (ctx, next) => {
  console.log("test");
  if (ctx.state.user) {
    return await next();
  }

  ctx.unauthorized(`You're not logged in!`);
};
```
6. Now run `strapi develop` 
7. In roles and permission for role `Authenticated` check  both `sendOtp` and `verifyOtp` and for `Public` uncheck  `sendOtp` and `verifyOtp` routes.

8. Use postman to send post request to these specific route mentioned above (assumed that you already logged in and token is set )

**Current behavior**
Always returning 403 error even if user is authenticated  and roles added for the routes.

**Expected behavior**
If user is authenticated should hit api with no 403 error and `test` should be printed in the terminal (in isAuthenticated.js )
else return 403 error.

**System**
- NPM version: 6.14.8
- Strapi version: 3.0.0-alpha.26.2

**Comment by derrickmehaffy** [comment]
Alright so a few things:

- `Strapi version: 3.0.0-alpha.26.2` currently the alpha is no longer supported (nor is the beta, only the stable release)
- policies do not take the place of permissions, by default every route will need to have it's permissions set first, which is why you are getting a 403, permissions aren't set.
- policies are an "add-on" to the basic permissions system, where you need more advanced checks and not just a simple "access or not". Checking for things like is a user allowed to update a record that isn't theirs ect.

For now I'm going to close this as it's based on a version we don't support, but I'd be happy to provide you with an updated sample project on the latest release if you need one?
