### ISSUE TITLE
CORS error when downloading media

### ISSUE THREAD

**Issue by lambrohan** [strapi/strapi#8055]
**Describe the bug**
Media Library download asset button not working with `strapi-provider-google-cloud-storage` because of CORS issue.

**Steps to reproduce the behavior**

1. Go to Strapi Admin
2. Open Media Library
3. Click on any image
4. Click download button

**Expected behavior**
Download action by browser.

**Screenshots**
https://storage.googleapis.com/juvel-15c67.appspot.com/strapi/Capture_a7b194cfd7/Capture.PNG_Capture_a7b194cfd7.png

**System**

- Node.js version: 12.17.0
- NPM version: 6.14.4
- Strapi version: 3.1.4
- Database: MongoDB (atlas)
- Operating system: Windows 10 v1909

**Comment by derrickmehaffy** [comment]
Hi,

As this issue is with a provider not build or managed by Strapi, you will want to contact the author.
See:
- https://www.npmjs.com/package/strapi-provider-upload-google-cloud-storage
- https://github.com/Lith/strapi-provider-upload-google-cloud-storage

For now I'm marking this issue as closed, but please feel free to let us know if the issue is on our side.
Thanks
