### ISSUE TITLE
Create the Token Content Type : error "This value is already used"

### ISSUE THREAD

**Issue by ThibaultWalterspieler** [strapi/strapi#8135]
**Describe the bug**

When I try to create a new relation between Token and User, following this documentation : [https://strapi.io/documentation/v3.x/guides/api-token.html](url), I get "This value is already used." for the user field. 

**Steps to reproduce the behavior**

1. Create a new Content Type named token
2. Add a string attribute named token
3. And add a relation attribute Token (user) - Token has and belongs to one User - User (token)

**Expected behavior**
Create relation

**Screenshots**

![Screenshot 2020-10-01 at 19 13 31](https://user-images.githubusercontent.com/15186627/94841372-392f6400-041a-11eb-8519-69ec08b0e7bc.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v12.18.3
- NPM version: v6.14.8
- Strapi version v3.1.1
- Database: MariaDB (MySql)
- Operating system: macOS Catalina v10.15.6

**Comment by alex-mngt** [comment]
+1

**Comment by derrickmehaffy** [comment]
I can confirm this on v3.2.5, to reproduce:

- Create a new `token` model
- Add a text field called `token` to store the API token
- Try to create a one to one relation between users-permissions_user and the new token model
- See error on the user model side of duplicate name

There should be no duplicate field as the `token` in the relation is on the users-permissions side.

**Comment by MattieBelt** [comment]
Digging into the code it seems that the `targetAttribute` value (in the example: `'token'`) can't be the same as a name of an attribute on the currentSchema (the one that is to be created/edited).  


https://github.com/strapi/strapi/blob/717a834a045bb2cbae54526fcd429546f5b53642/packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js#L97-L110
https://github.com/strapi/strapi/blob/717a834a045bb2cbae54526fcd429546f5b53642/packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js#L308-L314

Because in the example `targetAttributeAlreadyTakenValue` is the array `['token', 'user']`, the form will throw an unique-error on line 309.

---

So it can happen with any name for an attribute.

**Steps to reproduce the behavior:**

1. Create a new Content Type
2. Add any attribute
3. Add any two-way relation and set the target field name to the name of the attribute from step 2.
4. See error
