### ISSUE TITLE
Redirect to /admin instead of  strapi.config.admin.url

### ISSUE THREAD

**Issue by muellercornelius** [strapi/strapi#8151]
Hi Guys ;)

Its not a real feature... Its just a very small improvement. And very easy to fix.

I am using Strapi Docker on a custom domain in Dev Mode. Everytime when i go to my Domain i click the link to go to the admin page. The Problem is: The `strapi.config.admin.url` points to localhost and not to my domain. So I get redirected to my localhost... 

Now I am thinking about changing this simply to `/admin`. This should work for all environments. Because beeing on this site already means, that you are using the correct url or am I wrong? I already thought about opening a pull request. But I wasnt sure if I missed something... ;)

You can find the code here: packages/strapi/lib/middlewares/public/index.html
Thats how the link looks:
 ```
<a class="cta cta-primary" href="<%= strapi.config.admin.url %>" target="_blank" title="Click to open the administration" ><i class="fas fa-external-link-alt"></i>Open the administration</a><% } %>
```
Line Numbers: 30,38

**Comment by derrickmehaffy** [comment]
You will need to set the `url` key to the address you "access" the admin at (if it's public whatever your public domain is), this `url` key is used during the build so if you change it, you need to rebuild the admin.

See the server.js documentation here: https://strapi.io/documentation/v3.x/concepts/configurations.html#server

(That `url` key is used in other places, and is used to construct that `strapi.config.admin.url` along with the `admin.url` in the same file)

I'm marking as closed for now since the issue doesn't follow one of our required templates and I don't believe this to be a bug, but more of a question. In the future can you please ask questions on our [forum](https://forum.strapi.io/)

**Comment by muellercornelius** [comment]
No its not a Bug. And yes I know that `strapi.config.admin.url` is used elsewhere.

I run strapi in Docker Compose and I pull it directly from Docker Hub. This way I dont have access to change it, because there isnt an environment varible available. So I cant set the `url` key to match my public domain.

I just thought swapping out that link to `/admin` would work in all environments without any configuration.

Feel free to close it. Its ok. I just wanted to make my point clear. Becaus I think there was a small misunderstanding.

**Comment by derrickmehaffy** [comment]
Yeah that makes sense, our docker-hub images are more for testing, and in a real world production usage, you should really construct your own.

**Comment by muellercornelius** [comment]
Ahh ok, thank you ;)

**Comment by Sathyanarayanan-Dhanuskodi** [comment]
Hi, 
I am working on a new initiative. This project will have a UI that has all the applications in our organization. We have two application that uses Strapi cms. 

Now if the user clicks the icon or application in the new application, it will then redirect the user to the application that he clicked. But the requirement is he **should not** log in using credentials in the landed application instead the user must be authenticated directly. But in Strapi I don't know whether it is possible or not. 

The requirement will be like below
1. User clicks the icon in the new application
2. New application must redirect him directly to the Strapi admin homepage without the login credentials (All the necessary validation must be done in the new application and must redirect with token or something so that Stapi can authenticate the user)

I have done some research. Now I even don't know whether that is possible.

Can somebody help?
