### ISSUE TITLE
Editing locally after deploying to Heroku gives me errors

### ISSUE THREAD

**Issue by angelod1as** [strapi/strapi#8164]
**Describe the bug**
I'm trying to deploy Strapi on Heroku following [this guide](https://strapi.io/documentation/v3.x/deployment/heroku.html).

Everything apparently goes well. When I get to the [Project Updates](https://strapi.io/documentation/v3.x/deployment/heroku.html#project-updates) part, It gets confusing.

I run `yarn develop` locally and it gives me an erro — see below.

**Steps to reproduce the behavior**

1. Follow the steps of [this guide](https://strapi.io/documentation/v3.x/deployment/heroku.html)
2. See the application correctly deployed
3. Run `yarn develop` to develop locally and to create `content-types`
4. See error:

```bash
Error while running command develop: Could not load js config file /Users/angelodias/GIT/freelas/fegomes/back/config/database.js: Cannot read property 'charAt' of undefined
```

**Expected behavior**

Strapi should run locally so I can create the content-types, upload it to heroku and see the changes in production — at least that's what the guide tells me to do.

**System**

- Node.js version: 12.14.1
- NPM version: 6.13.4
- Yarn version: 1.22.5
- Strapi version: 3.1.7
- Database: Postgres on Heroku, SQLite on local (as the guide tells)
- Operating system: macOS Catalina 10.15.7

**Additional context**

I might be doing something wrong but I'm following the guide step-by-step. It's my third attempt.

**Comment by derrickmehaffy** [comment]
The issue in this case is one I accidentally created with my PR: https://github.com/strapi/strapi/pull/7661

What you need to do in this case to solve your issue (and I need to make a new PR to clarify):
- Move your existing `./config/database.js` to `./config/env/producution/database.js`
- Create a new `./config/database.js` based off of the SQLite config [here](https://strapi.io/documentation/v3.x/concepts/configurations.html#example) (Make sure you select the SQLite tab)

The issue is when you run locally your database.js file is trying to connect to a PG database assuming there is a `DATABASE_URL` environment variable.

**Comment by angelod1as** [comment]
I'll do this in a few moments, but a question was raised here: will the changes I make locally be reflected when I upload to heroku? And will the changes the user made in heroku be reflected if needed to develop locally? How can I make things "look alike"? (I'm not back-end fluent so I'm kinda lost here)

**Comment by cbandara** [comment]
I'm also having the same issue. I created the strapi app and then deployed to heroku using the database.js file and postgres. I logged into the admin dashboard and when I attempt to create a new content type the button to create a new type isn't there.

So to combat this I tried to run the strapi app locally using strapi develop and npm run develop but I am getting the same error as above

**Comment by angelod1as** [comment]
@derrickmehaffy done that and admin panel is now working in localhost. The issue I posted afterwards happens, though. How can I pull the data I set on heroku (using pg) into my SQLite install locally? How will I create new content types locally?

**Comment by cbandara** [comment]
I seem to have got a fix going. but the databases are separate. 

I have saved both versions of the database.js file and I change it whenever I push to heroku.
When I am working locally my database.js file looks like this: 
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL)

```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'sqlite',
        filename: env('DATABASE_FILENAME', '.tmp/data.db'),
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});
```

When I am pushing to heroku my database.js looks like this: 
```
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL)

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: config.host,
        port: config.port,
        database: config.database,
        username: config.user,
        password: config.password,
      },
      options: {
        ssl: false,
      },
    },
  },
});
```

I can add content types while working locally and then add the actual content itself after I've deployed to heroku.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy done that and admin panel is now working in localhost. The issue I posted afterwards happens, though. How can I pull the data I set on heroku (using pg) into my SQLite install locally? How will I create new content types locally?
> 
> @cbandara [see this, it works](https://github.com/strapi/strapi/issues/8164#issuecomment-702946926).

We do not have a method for pulling data down from the Heroku database, our [FAQ states](https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#does-strapi-handle-deploying-or-migrating-of-content) that for the moment we don't have any migration tools other than the core_store CLI one, but I don't believe you could get that to work on Heroku as it requires SSH access.

However since content types are stored in files, if you add it locally and push to Heroku, Strapi will create the new content type when it reboots (IE when you push)

> I'm also having the same issue. I created the strapi app and then deployed to heroku using the database.js file and postgres. I logged into the admin dashboard and when I attempt to create a new content type the button to create a new type isn't there.
> 
> So to combat this I tried to run the strapi app locally using strapi develop and npm run develop but I am getting the same error as above

You can't create content types on Heroku due to how the file system works (basically read-only, technically you can write to it but Heroku just destroys the local file system when your app sleeps or is redeployed).

See: 
- https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
- https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

The 2nd reason is the same reason why file uploads require a 3rd party provider, SQLite doesn't work, and why you can't create content types on Heroku (even if you force it into the development environment)

---

This issue specifically is about using SQLite locally and PG in Heroku in which I've updated the documentation in the linked PR for other issues please use the [forums](https://forum.strapi.io/)

**Comment by angelod1as** [comment]
This worked, @derrickmehaffy 
I'm still working on the database stuff, though. Anyways, feel free to close the issue. Thanks.
