### ISSUE TITLE
Manually insert rows before adding others in Strapi admin

### ISSUE THREAD

**Issue by octoduchilli** [strapi/strapi#8204]
**Describe the bug**
I have a database that I need to migrate to Strapi.
I created a "Post" model on the Strapi admin.
I created a script which inserts some existing data rows to the "posts" table which was generated by Strapi.

![image](https://user-images.githubusercontent.com/38497518/95196003-ae62b680-07d7-11eb-9d50-4531ec699023.png)

My two rows are integrated with IDs 1 and 2
But now I am not able to create "posts" from the Strapi admin.

![image](https://user-images.githubusercontent.com/38497518/95196151-f4b81580-07d7-11eb-88ae-30d3b253d00a.png)

I need to click on the "validate" button 3 times for my new "post" to be validated.
The number of clicks required to add a new "post" will depend on the number of data rows I inserted with my script.

In total I have 460 rows inserted thanks to my script. So I need to click 460 times on the "validate" button for my new "post" to be validated.

**Steps to reproduce the behavior**

Install strapi quickstart
npx create-strapi-app my-project --quickstart

Go to
[The Strapi Admin](http://localhost:1337/admin/plugins/content-type-builder/content-types/plugins::users-permissions.user?modalType=contentType&kind=collectionType&actionType=create&settingType=base&forTarget=contentType&headerId=content-type-builder.modalForm.contentType.header-create&header_icon_isCustom_1=false&header_icon_name_1=contentType&header_label_1=null)

Create a new Model "Post"

Manually add some rows in your "posts" table : `INSERT INTO "posts" (id) VALUES (1), (2), (3)`

Now go to
["Post" collection](http://localhost:1337/admin/plugins/content-manager/collectionType/application::post.post)

Check that the three rows are present

Finally go to
[Add "Post"](http://localhost:1337/admin/plugins/content-manager/collectionType/application::post.post/create)

And try to create a new "Post"

**System**

Node.js version: 12.18.4
yarn version: 1.22.5
Strapi version: 3.1.5
Database: Postgres
Operating system: MacOS

**Package.json**

```
{
  "name": "dressing-solidaire-backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "NODE_ENV=development strapi develop",
    "start": "NODE_ENV=production strapi start",
    "build": "NODE_ENV=production strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "fs": "^0.0.1-security",
    "knex": "<0.20.0",
    "pg": "^8.3.3",
    "sqlite3": "latest",
    "strapi": "3.1.5",
    "strapi-admin": "3.1.5",
    "strapi-connector-bookshelf": "3.1.5",
    "strapi-plugin-content-manager": "3.1.5",
    "strapi-plugin-content-type-builder": "3.1.5",
    "strapi-plugin-email": "3.1.5",
    "strapi-plugin-upload": "3.1.5",
    "strapi-plugin-users-permissions": "3.1.5",
    "strapi-provider-email-nodemailer": "^3.0.0",
    "strapi-provider-upload-aws-s3": "^3.1.5",
    "strapi-utils": "3.1.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "b4e385ab-d01f-4a77-9650-10997ed87247"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

Thanks !

**Comment by hadynz** [comment]
I don't believe this is a bug with Strapi. This is an issue with the state of your database after your migration.

Postgres, like many relational databases, can have tables with have identity columns that auto-increment. This is often done by creating a [sequence][3] behind the scenes that keeps track of what the next ID to use for a new record needs to be. PostgreSQL (and as such, Strapi) uses a [SERIAL][1] pseudo-type to define auto-increment columns in tables.

Your issue is that your sequence index is not in sync with the data that you have populated in your database table. You simply need to [reset the sequence][2] to the correct next auto-increment ID and you will walk away laughing. 

[1]: https://www.postgresqltutorial.com/postgresql-serial
[2]: https://gist.github.com/henriquemenezes/962829815e8e7875f5f4376133b2f209
[3]: https://www.postgresqltutorial.com/postgresql-sequences/

**Comment by octoduchilli** [comment]
@hadynz I see ! Thanks for sharing the documentation !
