### ISSUE TITLE
Require an user approval to publish a draft version

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#8269]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Use case:

1. I have a a post published.
2. An editor makes changes to the post from the admin panel. Those changes are not published yet.
3. An administrator can see the changes made, and execute the approval/publication of those new changes.

**Comment by harrykc** [comment]
This is about versioning which i also want this feature. For the existing draft-publish, its useless for me to be honest.
anyway, strapi mentioned in the forum they will not do this at the moment.
[https://forum.strapi.io/t/strapi-v3-2-0-beta-0-draft-and-publish-testing/123/14](https://forum.strapi.io/t/strapi-v3-2-0-beta-0-draft-and-publish-testing/123/14)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/content-versioning
Also possibly related is: https://feedback.strapi.io/customization/p/publication-workflow
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
