### ISSUE TITLE
lifecycle hooks not working in Collections with draft/publish-System

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#8329]
**Describe the bug**
I am using lifecycle hooks in models to update fields and create the content for my own slug fields. This works, if the draft-System is off. But when I activate the draft system, data.fieldname is undefined.

**Steps to reproduce the behavior**

1. Turn off the draft-system for a collection
2. Change data and save them
3. The lifecacle hooks beforeUpdate and beforeCreate are working as expected
4. Turn on the draft-system for the collection
5. unpublish or edtit fields
6. The field are not changed correctly by lifecycle hook, but getting undefined.

**Code snippets**
/api/product/models/product.js 
```
'use strict';
const slugify = require('slugify');

const mySlugify = (slug) => { 
  return (
    slugify(slug, { 
      remove:/[*+~.(){}\[\]\\/'"!:@,]/g, 
      lower:true 
    })
  );
};

/**
 * Lifecycle callbacks for the `product` model.
 */

module.exports = {

  lifecycles: {
    async beforeCreate(data) {
 
      if (!data.name_en) {
        data.name_en = data.name_de;
      }
      data.slug_de = mySlugify(data.name_de + '-' + data.orderno);
      data.slug_en = mySlugify(data.name_en + '-' + data.orderno);

    },

    async beforeUpdate (params,data) {
      console.log(data);

      if (!data.name_en) {
        data.name_en = data.name_de;
      }
      data.slug_de = mySlugify(data.name_de + '-' + data.orderno);
      data.slug_en = mySlugify(data.name_en + '-' + data.orderno);
      
    }
  }
};
```

without draft-system:
![without_draftsystem](https://user-images.githubusercontent.com/8960545/95978441-792f1780-0e1a-11eb-85fa-c567a5454a31.png)

with daft-system:
![with-draft-system](https://user-images.githubusercontent.com/8960545/95978469-851ad980-0e1a-11eb-83a3-4b738bdcc097.png)

In another collection doing the same, data.name_de is logged as undefined, but there is a string in that field. 

**System**

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2.3
- Database: sqlite
- Operating system: Windows 10 Pro

**Comment by pointout** [comment]
If I empty the name_en and save, the data is correct (name_de in name_en field and Slug-fields created) after refreshing the page. 
If I unpublish the Slug-fields get "undefined-undefined". That is not changing after publishing and/or refreshing the page.

**Comment by derrickmehaffy** [comment]
I believe I see the problem, during an update not all the data is sent, only what has changed.

In the case of publish/unpublish all that is changing is the `published_at` your code is making the assumption that if a field is not in the data object it's injecting something (not sure why that is undefined).

This code here:

```
if (!data.name_en) {
        data.name_en = data.name_de;
      }
```

If all you do is unpublish something, then both `data.name_en` and `data.name_de` are undefined because only the published_at is changed. Effectively whats being done here is the equivalent of a REST PATCH request and not a PUT request.

The difference between the two is a PATCH only includes what's changed where as a PUT would typically include everything.

![image](https://user-images.githubusercontent.com/8593673/96023879-eab19a80-0e07-11eb-9df7-d07ccf311f04.png)

Breaking down this image
1. I created a new article
2. I published that article
3. I edited the title
4. I unpublished that article

Each of the changes made in 2 through 4 are effective PATCH requests (Strapi doesn't have a PATCH method, and the PUT method acts like it). I don't have a good solution to your case unless you know one of the fields will always have a value, and in that case you can pull the ID from the `beforeUpdate` params option and run a `strapi.query('product').findOne({ id: params.id })` and adjust the data from there.

![image](https://user-images.githubusercontent.com/8593673/96024570-c1ddd500-0e08-11eb-92e1-3ac071d77baa.png)

Something like this, where in this case I unpublished the article but was still able to fetch the data

**Comment by derrickmehaffy** [comment]
As a side point while this looks like a bug, in this case it's not and is intended. So I'm going to mark this as closed though I do encourage you to respond if you need more information. In the future if possible can you open up a discussion on our [Forum](https://forum.strapi.io/) if you aren't sure if it's a bug? This makes it easier to handle issues that are generally questions. Thank you!

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/reload-data-after-saving-update/548/1
