### ISSUE TITLE
"In pending" publication status

### ISSUE THREAD

**Issue by pierredarrieutort** [strapi/strapi#8344]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

We are not able to toggle as "_pending_" any new article to request a validation before his publication.

_Closest feature request : https://portal.productboard.com/strapi/1-roadmap/c/14-validations_

**EDIT :**
It might be a good point to also get "_archived_" as status.
For example : in a blog old articles can be archived to hide them from the articles list but keep them in database.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/publication-workflow
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
