### ISSUE TITLE
Add option to disable "upload from url" in upload plugin

### ISSUE THREAD

**Issue by carlsborg** [strapi/strapi#8357]
### Please describe your feature request

- [] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary
"Upload from URL"  introduces security risks. 

### Why is it needed?
User can enter an arbitrary url 

### Suggested solution(s)

add a config option to disable "upload from url"

**Comment by gu-stav** [comment]
@carlsborg We changed the feature in a way, that the server doesn't download the file anymore. It's done purely on the client side. Could you elaborate more on why you think it is a security issue, in case it still is for you?

Pinging @alexandrebodin and @derrickmehaffy too: do you think this issue is still relevant?

**Comment by derrickmehaffy** [comment]
> @carlsborg We changed the feature in a way, that the server doesn't download the file anymore. It's done purely on the client side. Could you elaborate more on why you think it is a security issue, in case it still is for you?
> 
> Pinging @alexandrebodin and @derrickmehaffy too: do you think this issue is still relevant?

I believe this more so related to the old option that you used to be able to use on the client-side APIs. We removed that as it was a security issue. I'll close this given it's issue I believe it's already been solved and we forgot to clean this issue up.
