### ISSUE TITLE
UI issues around datetime manual entry

### ISSUE THREAD

**Issue by shanejdonnelly** [strapi/strapi#8407]
1. Create collection that uses datetime
2. Create new collection entry
3. Attempt to type date

I was trying to create a datetime entry from 40 years ago and there is no way to move back in time easily in the UI. Typing in the text field is allowed, but there appears to be some javascript that is trying to autocomplete the date. This leads to screwy dates.

Using Firefox 81.0 (64 bit) on Ubuntu

![Screenshot at 2020-10-20 11-58-30](https://user-images.githubusercontent.com/1114645/96612328-9efd6600-12cb-11eb-8c20-4645a8c4da16.png)

**Comment by shanejdonnelly** [comment]
Workaround is to copy/paste in the completed, correctly formatted date. So, in my case, I needed to paste in 08/01/1980 into the text field and the component allowed that. But typing the date into the text field directly is still a bug.

**Comment by derrickmehaffy** [comment]
Hi @shanejdonnelly while largely unnecessary, can you please follow our bug report template. The templates are required for bug reports so that we can validate the environment to ensure external factors are not at play with the bug.

I'm going to close this for now, but once you update the original post following the template please do reply back and we will reopen the issue. Thank you! 

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by soupette** [comment]
@derrickmehaffy I also believe that this kind of issue should be opened in the [Buffet.js repository](https://github.com/strapi/buffet) instead

**Comment by abdonrd** [comment]
Related: https://github.com/strapi/buffet/issues/104
