### ISSUE TITLE
Lost data when deploying to Heroku

### ISSUE THREAD

**Issue by tommypratama** [strapi/strapi#8580]
# Bug report 

### Describe the bug

Database is always empty when re-deploying to Heroku.

I followed the instructions in this tutorial:

- https://strapi.io/documentation/v3.x/deployment/heroku.html

In the hobbby-dev version of heroku, strapi doesn't allow to use `Content-Builder`, so every time I want to add or update `Content-Builder` I have to use local development then publish it to Github > Heroku.

How to solve this?

### System

- Node.js version: 12
- NPM version: 6.14.6
- Strapi version: 3.2.5
- Database: postgres
- Operating system: MacOS Catalina

**Comment by Sqveeze** [comment]
Its not about Heroku. Strapi itself disabling to edit content types in prod / staging because strapi stores the schema in json files. That way if you could edit in prod then how you sync that back to git? If you need changes: Modify -> Push -> Deploy like in any normal development environment.

Are you sure you using postgres in stage / prod envs? Because if heroku reset itself on every deploy that could because you forgot to change sqlite to postgres in stage / prod envs, that way strapi remain to use sqlite and on every heroku deploy the database loses.

**Comment by tommypratama** [comment]
Thanks @Sqveeze, I made a configuration error in the environment because I switched to the tutorial:

- From: https://strapi.io/documentation/v3.x/deployment/heroku.html
- to: https://strapi.io/documentation/3.0.0-beta.x/

So that heroku can't connect to postgres. It makes sense that my data is lost.

Is there a way to integrate heroku (postgres) into local development?

**Comment by Sqveeze** [comment]
> Thanks @Sqveeze, I made a configuration error in the environment because I switched to the tutorial:
> 
> 
> 
> - From: https://strapi.io/documentation/v3.x/deployment/heroku.html
> 
> - to: https://strapi.io/documentation/3.0.0-beta.x/
> 
> 
> 
> So that heroku can't connect to postgres. It makes sense that my data is lost.
> 
> 
> 
> Is there a way to integrate heroku (postgres) into local development?

There is, but it it really not recommended. Use seeders if you need dummy data at every deploy for example.

You can configure different seeders for dev, staging but for production, you should not because that db should remain as is. With real costumers data for example.

Check out how to create seeders with knex (strapi uses knex under the hood) and if you dont want to use knex for this you can always use strapi database operations to seed the db, however that will takes more time if you have many relations in a content type

**Comment by derrickmehaffy** [comment]
I believe the issue in your case was you created the project initially with `--quickstart` which uses SQLite and when deploying to Heroku it wasn't actually using the PG database but was running with SQLite (thus losing data when the dyno went to sleep).

As a point to trying to enable the CTB (Content-types builder) on Heroku, technically you could force it but when the dyno sleeps any changes where not pushed into git will be lost entirely.

See: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

Also see: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

And yes you are correct that you should be following the v3 tutorial not the v3-beta one. This is the correct and up to date one: https://strapi.io/documentation/v3.x/deployment/heroku.html

We plan to remove the beta documentation. I'm going to mark this as closed as it's not so much a bug with Strapi but just an issue in deployment. For future stuff like this, please use our forum instead: https://forum.strapi.io/
