### ISSUE TITLE
Copy post feature

### ISSUE THREAD

**Issue by hg-pyun** [strapi/strapi#8645]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Hello, I'm currently using Strapy very hard. Among the needs of the users, there were many opinions that it would be nice to have the ability to copy posts that have already been written. How about adding this feature to the Content Manager plug-in?

### Why is it needed?

If the content is similar, it is hard to copy.

### Suggested solution(s)
- https://stackoverflow.com/questions/60522438/how-to-duplicate-clone-a-record-in-strapi

### Related issue(s)/PR(s)
- None

**Comment by v4dkou** [comment]
On `strapi-plugin-content-manager@3.1.3` we've been using a patch based on this answer from StackOverflow https://stackoverflow.com/a/62288754/8121754

When 3.2 landed, a bunch of things changed internally to accommodate "publish/unpublish" feature and we'll have to figure out the new way to do this. 

Personally, I would love having a better way to extend default plugins, rather than having to copy files from node_modules, so that any custom extensions could be reused from version to version without much hassle.

**Comment by finex** [comment]
Hi, cloning a post (or any other collection) would be very useful. Think about a product catalogue with similar items for example.

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
