### ISSUE TITLE
Duplicate validation is failing and returning a 500 error instead of 400

### ISSUE THREAD

**Issue by kieron** [strapi/strapi#8664]
## Bug report

Duplicate validation is failing and returning a 500 error instead of 400

### Steps to reproduce the behaviour

1. Submit duplicate data

### Expected behaviour

Should return 400 error

### System

- Node.js version: v12.17.0
- NPM version: 6.14.4
- Strapi version: v3.1.7
- Database: MySQL + bookshelf
- Operating system: Centos

**Comment by derrickmehaffy** [comment]
I was able to reproduce this on v3.3.3.

To reproduce
- Download the sample project
- Install/build/run
- Default admin login is `test@test.com` and `Test1234!`
- See existing entry in `test` model with a value of `https://gleam.io/sometesturl`
- Try to send a POST request with:

```json
{
    "gleam_url": "https://gleam.io/sometesturl"
}
```

- Notice 500 error instead of 400, the duplicate validation is failing and returning a 500 error that the user can't see why. Tested on both SQLite (test project) and MariaDB 10.5

SQLite error:

```
[2020-11-16T21:35:20.748Z] error Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: tests.gleam_url
    at Client_SQLite3._query (/home/dmehaffy/Development/testDup/node_modules/knex/lib/dialects/sqlite3/index.js:99:12)
    at Client_SQLite3.query (/home/dmehaffy/Development/testDup/node_modules/knex/lib/client.js:158:17)
    at /home/dmehaffy/Development/testDup/node_modules/knex/lib/transaction.js:331:24
From previous event:
    at Client_SQLite3.trxClient.query (/home/dmehaffy/Development/testDup/node_modules/knex/lib/transaction.js:326:12)
    at Runner.query (/home/dmehaffy/Development/testDup/node_modules/knex/lib/runner.js:135:36)
    at /home/dmehaffy/Development/testDup/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/home/dmehaffy/Development/testDup/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/home/dmehaffy/Development/testDup/node_modules/knex/lib/interface.js:14:43)
    at Child.<anonymous> (/home/dmehaffy/Development/testDup/node_modules/bookshelf/lib/model.js:1160:42)
From previous event:
    at Child.<anonymous> (/home/dmehaffy/Development/testDup/node_modules/bookshelf/lib/model.js:1159:14)
From previous event:
    at Child.<anonymous> (/home/dmehaffy/Development/testDup/node_modules/bookshelf/lib/model.js:1060:10)
From previous event:
    at runCreate (/home/dmehaffy/Development/testDup/node_modules/strapi-connector-bookshelf/lib/queries.js:98:45)
    at /home/dmehaffy/Development/testDup/node_modules/strapi-connector-bookshelf/lib/queries.js:46:34
    at /home/dmehaffy/Development/testDup/node_modules/knex/lib/transaction.js:91:24
From previous event:
    at /home/dmehaffy/Development/testDup/node_modules/knex/lib/transaction.js:77:12
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at new Transaction (/home/dmehaffy/Development/testDup/node_modules/knex/lib/transaction.js:57:30)
    at Client_SQLite3.transaction (/home/dmehaffy/Development/testDup/node_modules/knex/lib/client.js:114:12)
    at Function.transaction (/home/dmehaffy/Development/testDup/node_modules/knex/lib/util/make-knex.js:40:31)
    at wrapTransaction (/home/dmehaffy/Development/testDup/node_modules/strapi-connector-bookshelf/lib/queries.js:46:15)
    at Object.create (/home/dmehaffy/Development/testDup/node_modules/strapi-connector-bookshelf/lib/queries.js:105:12)
    at fn (/home/dmehaffy/Development/testDup/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.create (/home/dmehaffy/Development/testDup/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at async Object.create (/home/dmehaffy/Development/testDup/node_modules/strapi/lib/services/entity-service.js:75:17)
    at async Object.create (/home/dmehaffy/Development/testDup/node_modules/strapi/lib/core-api/controller.js:123:18)
    at async /home/dmehaffy/Development/testDup/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async module.exports (/home/dmehaffy/Development/testDup/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:86:3)
    at async /home/dmehaffy/Development/testDup/node_modules/strapi-utils/lib/policy.js:68:5
    at async /home/dmehaffy/Development/testDup/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /home/dmehaffy/Development/testDup/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2020-11-16T21:35:20.749Z] debug POST /tests (31 ms) 500
```


Test project: 
[test8664.zip](https://github.com/strapi/strapi/files/5549905/test8664.zip)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/could-the-duplicate-entry-error-be-sent-back-in-the-web-request/1069/3

**Comment by derrickmehaffy** [comment]
@kieronbos do you want to try and apply this fix manually? (I plan to do some testing also)

https://github.com/strapi/strapi/pull/8367

**Comment by AlphaMoonbaseBerlin** [comment]
It is a simple hack for now, but putting the service call in a try/catch block and returning the error as the message gives a more friendly warning (only works when you setup your own endpoints

```
catch (e) {
            entity = {  statusCode: 400,
                        error :   "Bad Request",
                        message :   e};
            ctx.response.status = 400;
        }
```

**Comment by derrickmehaffy** [comment]
Additional information since this is throwing 500 errors to REST/GraphQL clients:

Original PR that fixed it in the Admin: https://github.com/strapi/strapi/pull/8367

Related code that is throwing the errors:

## MongoDB (Mongoose)

https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi-connector-mongoose/lib/utils/errors.js#L7-L13

https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi-connector-mongoose/lib/queries.js#L62-L68

## SQL (Bookshelf)

https://github.com/strapi/strapi/blob/7271c1a8536862258b5164090450c7ab5f0c4b49/packages/strapi-connector-bookshelf/lib/utils/errors.js#L22-L28

https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi-connector-bookshelf/lib/queries.js#L54-L60

**Comment by derrickmehaffy** [comment]
The above code doesn't return a proper error to the user (400 status code + proper error)

**Comment by ChristherLenander** [comment]
Same problem with the MySQL. And still not fixed.

**Comment by lack-of-gravitas** [comment]
Still not fixed

**Comment by rowild** [comment]
Tuning in and reporting that I have the same problem with 3.6.8. 

As already mentioned above this happens when a table is set to unique. That is very important, e.g. for email field in registration, or invite codes in shops. Strapi itself does throw a correct error message: `Error: Duplicate key` and `warn Duplicate entry Error: insert into [...] - SQLITE_CONSTRAINT: UNIQUE constraint failed: pilot_participants.email`. Would b great to have that error msg in the return value.

**Comment by lack-of-gravitas** [comment]
I've raised a similar / possibly related bug on this here https://github.com/strapi/strapi/issues/12022. So hopefully it can be looked into -- 

In the end, I just gave up and used next-auth, prisma pointed to a separate mysql backend to the strapi mysql I have for this client.

**Comment by rowild** [comment]
@lack-of-gravitas Thank you! _ I found this comment here, which basically says that there won't be any fixes anymore for strapi v3.x:
https://giters.com/strapi/strapi/issues/11636

But it seems to be fixed in v4. (Haven't tested that yet.)

**Comment by kieron** [comment]
@derrickmehaffy - is this the case, that this will not be fixed?

Just so I know if I can wait or if I need to upgrade. Thanks!

**Comment by lack-of-gravitas** [comment]
Well that sucks -- my issue is most of the plugins that my clients rely on are not yet ported to work on v4 so I'm now left in the lurch with unclear and confusing documentation and now regression of the previous version for reasons.

major sad face

**Comment by rowild** [comment]
@lack-of-gravitas I am not too happy about that, too. However, I tried to integrate my own fix with each controller, where a unique field comes into play. If you are interested, here is what I do:

- "un-click" (is that a word?) the "unique" checkbox, so that the table field in question is actually NOT a unique field.
- then, in the controller of the component in question, I integrate my own check:

```js
module.exports = {
  [...]
  async create(ctx) {
    const emailExists = await strapi.query('participant').findOne({ email: ctx.request.body.email })

    if (emailExists) {
      console.log('EMAIL FOUND!');

      ctx.send({
        message: 'This email address already exists!'
      }, 422)
    }

    [...]

  }
}
```

Somewhere in the www I found people saying that 422 is a fitting return code for situations like this.

Maybe that helps. Good luck and may your sad face become a happy one soon again! :-)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy - is this the case, that this will not be fixed?
> 
> Just so I know if I can wait or if I need to upgrade. Thanks!

If the issue still exists in v4 (I haven't checked) it will be fixed in v4. We aren't backporting fixes to v3 unless they are deemed critical (by our definition of critical) or are security related in nature.

**Comment by rowild** [comment]
@derrickmehaffy If I may add my 2 cents to the update politics of software: It has proven that "dropping support" for one version because the next one was just released, is a bad, for the software itself as well as for businesses and users who use the software. (More on that, if you are interested.) Therefore version plans now tend to overlap. A very good and incredibly reliable OSS CMS that has adopted to this idea and from which many should take an example from, is TYPO3 (typo3.org). They release an LTS version every 18 months, which is then supported for 3 years. After that a paid plan is available from typo3.com (which is especially useful for institutions like universities). 
I would love to see this strategy implemented in strapi's (OSS) publication philosophy. My background knowledge of the business side of strapi is, of course, way too little to be able to make any estimations, but since you have a paid plan I think this release strategy should be adoptable. 
Would love to hear/read, what you think about that. (Maybe in a different place, since this does not really belong to this issue; but I wouldn't know, where. On Discord everything gets lost soon, maybe a dedicated Forum topic should be opened ...)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy If I may add my 2 cents to the update politics of software: It has proven that "dropping support" for one version because the next one was just released, is a bad, for the software itself as well as for businesses and users who use the software. (More on that, if you are interested.) Therefore version plans now tend to overlap. A very good and incredibly reliable OSS CMS that has adopted to this idea and from which many should take an example from, is TYPO3 (typo3.org). They release an LTS version every 18 months, which is then supported for 3 years. After that a paid plan is available from typo3.com (which is especially useful for institutions like universities). I would love to see this strategy implemented in strapi's (OSS) publication philosophy. My background knowledge of the business side of strapi is, of course, way too little to be able to make any estimations, but since you have a paid plan I think this release strategy should be adoptable. Would love to hear/read, what you think about that. (Maybe in a different place, since this does not really belong to this issue; but I wouldn't know, where. On Discord everything gets lost soon, maybe a dedicated Forum topic should be opened ...)

I agree with you honestly and I believe that's the intend with v4 but v3 is so fundamentally different that we could not split our focus between v3 and v4. Now that we have successfully made the breaking changes in v4 I believe we can look farther ahead in terms of LTS but it just was not possible with v3 due to what we have planned this year and the next few years.

Simply put we lack the number of people (and it's not without trying, we are hiring like crazy right now)

**Comment by rowild** [comment]
I understand! Thanks for the feedback!
I love Strapi – if I were any good at React, I totally would apply :-)

**Comment by derrickmehaffy** [comment]
Fixed on v4: 
![image](https://user-images.githubusercontent.com/8593673/178833827-e6b04b51-452e-4c66-9d6d-f6db7a1af593.png)
