### ISSUE TITLE
Trend-Metric components on model

### ISSUE THREAD

**Issue by tecnolive** [strapi/strapi#8692]
It would be nice to be able to insert graphical statistics widgets in each model, such as laravel nova.
Possibility therefore to insert the type of Widget, the date range and the field to be considered (and the relative REST API to GET results, grouped per hour, day, moth, year)

Something like that:
![immagine](https://user-images.githubusercontent.com/226723/99595953-c7c16a00-29f5-11eb-849c-59b118966bf4.png)

Sorry for my bad english but i'm italian.

**Comment by derrickmehaffy** [comment]
This would be awesome to have but I think it would be better suited as a community plugin for anyone interested in building one and submitting it to: https://github.com/strapi/awesome-strapi

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/graphs-and-charts-within-the-admin-list-view-landing-page-ect
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
