### ISSUE TITLE
Impossible to change admin rights for components and fields in dynamic zones

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#8745]
### Describe the bug

When a dynamic zone is created, it is impossible to change admin rights for components and fields in dynamic zones. 

### Steps to reproduce the behavior

1. Go to Content-Type builder, create a Content Type with a dynamic zone.
2. Go to the Settings -> Administration Panel -> Roles. Open "Edit a role" for any role
3. Scroll down to the created on step 1 Content Type and try to change permissions for dynamic zones.
4. Here is the error - you can not set granular rights for the fields.

### Expected behavior

It is expected for me that a user should be able to change rights for each field in a Dynamic Zone of a Content Type.

### Screenshots

Here is granularity for simple components.
![image](https://user-images.githubusercontent.com/20924122/100285937-dcb47500-2f82-11eb-9190-d2ac80702982.png)

'Payment' is a dynamic zone. No granularity.
![image](https://user-images.githubusercontent.com/20924122/100285967-f05fdb80-2f82-11eb-8822-924082da347a.png)

### System

- Node.js version: v12.18.3
- NPM version:
- Strapi version: v3.3.4 EE
- Database: PostgreSQL
- Operating system: Ubuntu 18.04

### Additional context

As I think, an admin should be able to:
a) Edit rights for each dynamic zone like for a component, or
b) Edit rights for any component on a separate tab.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/permission-control-over-dynamic-zones-and-components-limit-adding-new-components
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
