### ISSUE TITLE
Equal letters "ё" and "е" for cyrillic search

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#8762]
### Please describe your feature request

- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

In Russian, often letters "е" and "ё" in written speech are equal and pronounced based on context of a sentence. I've personally faced a little problem with strapi.query('model).search functionality.

1) I'm making a request to Google Maps API to fetch what neighborhood the address in.
2) I'm taking a neighborhood from Google Maps API and make query for districts in my database.
3) Google responds with, for example, "Теплый Стан", where the "e" letter is pronounced as "ё" in speech.
4) My database contains official names for districts, where a district is called "Тёплый стан".
5) Strapi tries to make a query for "Теплый стан" and, obviously, cannot find it because it's called differently. Then it fails and so isn't able to read properties.

### Why is it needed?

I'll let myself quote [an answer ](https://www.quora.com/What-is-the-difference-between-letters-%D1%91-and-e-in-Russian-language)from Quora:

> The symbol “ё” is always stressed in native Russian words that’s why it is often perceived by native speakers not as a separate letter but as a diacritic specifying the peculiarity of just another pronunciation of the letter “е” in specific word and context. For example:
> 
> Мы узна́ем тебя: we will recognize you/get to know you.
> Мы узнаём тебя: we are recognizing you/getting you to know.
> Note that in both sentences I have used diacritics to emphasize what I really meant: in the first case it was “а́” and in the second - “ё”.
> 
> Normally, you’ll see this sentence without any diacritics as the implied meaning is deduced from the context.

### Suggested solution(s)

I suggest to equal letters "е" and "ё" for strapi search controller.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/handle-cyrillic-search
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
