### ISSUE TITLE
show git SHA in root page

### ISSUE THREAD

**Issue by hadifarnoud** [strapi/strapi#8769]
It would be useful to see a git SHA hash (or auto increment number as a version) in root page. This is a useful feature to see what version is live on server. Git SHA hash is more useful I think

**Comment by derrickmehaffy** [comment]
For reference I believe the user means: 

![image](https://user-images.githubusercontent.com/8593673/100635890-ea9d2980-32e5-11eb-93ae-01a925402be9.png)

**Comment by hadifarnoud** [comment]
I actually meant but that would be also useful
<img width="925" alt="Screen Shot 1399-09-12 at 17 52 45" src="https://user-images.githubusercontent.com/589808/100884945-54285e00-34c7-11eb-8c8b-e0c7627ab320.png">

**Comment by derrickmehaffy** [comment]
> I actually meant this but that would be also useful
> <img alt="Screen Shot 1399-09-12 at 17 52 45" width="925" src="https://user-images.githubusercontent.com/589808/100884945-54285e00-34c7-11eb-8c8b-e0c7627ab320.png">

This isn't something we would do as it would be a security risk in my mind. Anything that gives attackers a method to dig into vulnerabilities is not a good idea.

**Comment by hadifarnoud** [comment]
having my own git commit SHA would mean nothing to others. I don't think this is a security risk. Can I do this on my own?

**Comment by derrickmehaffy** [comment]
Sure, you can find the index.html in the public middleware and either disable our public middleware and add your own or just take the index.html out of that and put it in your public directory at the project root.

https://github.com/strapi/strapi/tree/master/packages/strapi/lib/middlewares/public

Just keep in mind that in the public directory you won't be able to access the variables like we do in the middleware.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/show-git-sha-in-root-page
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
