### ISSUE TITLE
Add automatic data migration support

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#884]
Hi guys. I think if we have a authomatic migration approach (for example like migration with *.js approach in [rocketchat](https://github.com/RocketChat/Rocket.Chat/tree/develop/server/startup/migrations) app) we can use Strapi more easy in production.

**Comment by lauriejim** [comment]
Lets discuss about this on this issue https://github.com/strapi/strapi/issues/884

**Comment by abdonrd** [comment]
@lauriejim you link to the same issue. 😅

**Comment by artem-korolev** [comment]
Hi. That is interesting topic.
Strapi already have a very well model to support it.
But i'm not totally sure, that this process can be really automated

Yesterday I was trying to rename one model. I can do it easily I guess, if I do not rename collection name. But if collection name is already initialized, then editing it force a bug after Strapi restart. It is actually a bug, that should be fixed. Let's not allow to rename collection, when its already initialized.

About migrations. I do not see this topic like something easy and straightforward.
Updating live database can be almost impossible, especially when you have zero downtime and data is constantly coming in.

If migration can be automated, then we need to define first what "migration" is. what is the scope of migration.

If you want migration as something universal, that magically happens, then I can give you a few examples, when this process will be impossible to implement.

And what if something gets wrong in the middle of huge migration?

I will rather think about "deprecation" process. This maybe can we can achieve more easily?

I think, that such things, like migration/deprecation should be atomic process. This need to be something very simple and atomic. So that you cannot migrate bunch of things. But you can migrate/deprecate only something very simple. Like one field. Or one table. Just imagine, if you rename 10 table, remove 5 tables, rename 15 fields, which are used in relationships with existing tables.
I cannot imagine how to make it happen in once even if I make it manually. Haha :)

So I rather will think about atomic deprecation flow. So that system will not allow to me to make a lot of changes in the model, which already runs in production.
When everything is migrated, then system can inform you, that migration/deprecation process is finished (on staging/production). And you can manually clean tables (or this already can be automated, if we define this in the scope).

Or maybe even without any deprecation - just create your new api from scratch and thats it. and support backward compatibility. Easy. Right? :))

Thanks for this topic. As I said its really interesting. Will be happy if somebody will correct me, if I'm saying something wrong. Like "hey man, its not so bad like you thinking about it, everything is much easier". If you know a way, then please tell me about it.

**Comment by Aurelsicoko** [comment]
@artem-korolev Thank you for sharing your thoughts on this feature! We already made progress on this one, you should read the proposal I made [here](https://github.com/strapi/strapi/issues/672#issuecomment-381662918).

It's a very complicated feature because we want to keep Strapi very easy to use. This kind of functionality is powerful but also difficult to understand for beginners...

**Comment by derrickmehaffy** [comment]
@Aurelsicoko can probably close this issue in favor of https://portal.productboard.com/strapi/c/12-migrate-across-environments
