### ISSUE TITLE
Author role can edit published content

### ISSUE THREAD

**Issue by Dineshk77** [strapi/strapi#8851]
### Description

I noticed that author can actually edit the published content, which defies the idea of Author role who can't publish.

### Steps to reproduce the behaviour

1. Create a content type
2. Use Author to create a content
3. Use Editor to publish the content
4. After publish, Use author to edit the published content

### Expected behaviour

Author shouldn't publish content, updating the content should un publish or notify editor with update available for republish of that content

### System
- Strapi version: 3.3.3

**Comment by Phasor1** [comment]
Is there any news on this issue?

**Comment by lucasR23** [comment]
Is there any news about that feature ? 

I am currently using Strapi in a project but that problem is blocking me from keep using Strapi, and apparently even on the enterprise version I can not solve this problem.

**Comment by derrickmehaffy** [comment]
> Is there any news about that feature ?
> 
> I am currently using Strapi in a project but that problem is blocking me from keep using Strapi, and apparently even on the enterprise version I can not solve this problem.

Not currently no. You could use our RBAC Conditionals I believe but the API is unstable (and they can only be used with an enterprise edition): https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/rbac.html#declaring-new-conditions

**Comment by apatel369** [comment]
@derrickmehaffy Can you show example of preventing publish using https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/rbac.html#declaring-new-conditions?

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/content-versioning
Also possibly related is: https://feedback.strapi.io/customization/p/publication-workflow
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
