### ISSUE TITLE
Using npm instead of yarn breaks the admin panel

### ISSUE THREAD

**Issue by haschu** [strapi/strapi#8963]
### Describe the bug

The strapi admin panel throws the following error in the browser console, when using `npm` instead of `yarn`:

```
Uncaught TypeError: Invalid Version: function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
    at Function.SemVer (main.5c36beab.chunk.js:227192)
    at main.5c36beab.chunk.js:228110
    at Object.<anonymous> (main.5c36beab.chunk.js:228114)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
    at Object.<anonymous> (main.5c36beab.chunk.js:226922)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
    at Object.<anonymous> (main.5c36beab.chunk.js:34209)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
    at Object.<anonymous> (main.5c36beab.chunk.js:225973)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
```

I'm not sure whether this bug only occurs in the latest 3.4.0 update (See #8934).

### Steps to reproduce the behavior

1. Set up a new strapi project with `yarn create strapi-app my-project --quickstart`
2. Remove `yarn.lock` `./build` and `./node_modules`
3. Run `npm install`
4. Run `npm run develop`
5. Go to `http://localhost:1337/admin` 

### System

- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.4.0
- Database: PG 12.3
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
Make sure you delete the `.cache` also.

**Comment by broncha** [comment]
I just encountered this while upgrading from 3.3.4 to 3.4.1

**Comment by derrickmehaffy** [comment]
I still cannot reproduce this issue, here is what I did:

- Create new Strapi v3.3.4 application `npx create-strapi-app@3.3.4 --quickstart`
- Let application build and start
- Create first admin, added a handful of models with some data
- Kill running server
- Follow our [update guide](https://strapi.io/documentation/developer-docs/latest/guides/update-version.html#upgrade-your-dependencies) to push to v3.4.1
- Delete the following folders/files
  - `build`
  - `.cache`
  - `node_modules`
  - `package-lock.json`
- Reinstall modules with `npm i`
- Rebuild admin with `npm run build`
- Run server with `npm run develop`

No issues, I'm marking this issue as closed unless steps to reproduce are provided. Once it can be reproduced we can reopen and take a look again. If you have links to your projects that I can clone locally and test please do provide them.

The issue is likely either:
- Environment specific (not something we, the Strapi team, can fix)
- Project Specific due to some extensions the user created, in which case: https://strapi.io/documentation/developer-docs/latest/guides/update-version.html#extensions

**Comment by mnelemans** [comment]
This just happened for me on 3.4.2 as well. It **is** an older repo that has undergone many changes and migrations, but it was still kind of frustrating. I ended up "fixing" it by just changing the CI to `yarn install && yarn build`. Note that the `yarn install` was crucial, probably due to one of the admin panel dependencies requiring this.

Sorry I cannot be of help but thought it would be useful to +1 the issue..

**Comment by cronin4392** [comment]
Getting this issue as well when using NPM. Tried removing .cache, build, node_modules and even installing on a fresh computer and get errors with semver.

**Comment by Sejori** [comment]
Having this issue as well. My business partner and I had a working admin panel and were working separately when all of a sudden we both got white screens. Weird.

I rolled back to Strapi version 3.3.3 for all Strapi dependencies and it was resolved.

**Comment by Sejori** [comment]
Had this issue too. Rolled back all Strapi package versions to 3.3.3 and that seems to have fixed up.

**Comment by derrickmehaffy** [comment]
Can any of you add some environmental information as I've tested this on now 8 different windows machines (physical and virtual) and have never been able to reproduce the issue.

**Comment by AkshayMAnvekar** [comment]
> 
> 
> I still cannot reproduce this issue, here is what I did:
> 
>     * Create new Strapi v3.3.4 application `npx create-strapi-app@3.3.4 --quickstart`
> 
>     * Let application build and start
> 
>     * Create first admin, added a handful of models with some data
> 
>     * Kill running server
> 
>     * Follow our [update guide](https://strapi.io/documentation/developer-docs/latest/guides/update-version.html#upgrade-your-dependencies) to push to v3.4.1
> 
>     * Delete the following folders/files
>       
>       * `build`
>       * `.cache`
>       * `node_modules`
>       * `package-lock.json`
> 
>     * Reinstall modules with `npm i`
> 
>     * Rebuild admin with `npm run build`
> 
>     * Run server with `npm run develop`
> 
> 
> No issues, I'm marking this issue as closed unless steps to reproduce are provided. Once it can be reproduced we can reopen and take a look again. If you have links to your projects that I can clone locally and test please do provide them.
> 
> The issue is likely either:
> 
>     * Environment specific (not something we, the Strapi team, can fix)
> 
>     * Project Specific due to some extensions the user created, in which case: https://strapi.io/documentation/developer-docs/latest/guides/update-version.html#extensions

I have 2 projects running Strapi. Facing this issue in one project. Another project has no issues. Tried the above steps still it fails. Environment variables are only URL, Sendgrid Keys, and Database connection. 

Tried this is 2 machines 
1. 
   - Node.js version: v14.15.1
   - NPM version: 6.14.8
   - Strapi version: 3.4.6
   - Database: Postgres
   - Operating system: Win 10
2.
   - Node.js version: v12.19.1
   - NPM version: 6.14.8
   - Strapi version: 3.4.6
   - Database: Postgres
   - Operating system: Ubuntu
   - Strapi runs in docker.

**Comment by derrickmehaffy** [comment]
@AkshayMAnvekar can you provide any steps to reproduce because I've tried on every possible combination of operating system and versions and was never able to reproduce it myself.

**Comment by AkshayMAnvekar** [comment]
> @AkshayMAnvekar can you provide any steps to reproduce because I've tried on every possible combination of operating system and versions and was never able to reproduce it myself.

I'll see if I can create a similar test project with the issue and share

**Comment by joshjung** [comment]
Just ran into this myself, using Strapi 3.5.3. Fresh install of Strapi trying both **npm install** and **yarn install**. The problem occurs with both for me. Webpack 4.44.2.

**Comment by Edsonzhu** [comment]
Still getting the same problem when I tried to update ours

**Comment by AkshayMAnvekar** [comment]
> 
> 
> > @AkshayMAnvekar can you provide any steps to reproduce because I've tried on every possible combination of operating system and versions and was never able to reproduce it myself.
> 
> I'll see if I can create a similar test project with the issue and share

I created a new strapi setup (v3.6.2) and migrated the models and custom api's. 

The old setup the files names for api was following the collection name. But in new setup it replaced all underscore '_" with hyphen '-' 
Also, the relations and route controller in model the same had to be updated. I had model names with double underscores in few cases they were replaced with single hypen. This was the changes i had to do to update strapi from 3.3.4 to 3.6.2

**Comment by broncha** [comment]
Finally fixed this! This definitely had something to do with webpack not being compatible with semver and passing `__webpack_require__ ` as version argument when loading semver.

The issue here led me to the right path https://github.com/log4js-node/log4js-node/issues/391

`npm ls semver` showed `eslint-plugin-import` was dependent on semver 4.
Updating all devDependencies fixed it all for me
