### ISSUE TITLE
ECONNRESET strapi fresh install

### ISSUE THREAD

**Issue by Oldwo1f** [strapi/strapi#8998]
## Bug report
I cant get strapi working on a fresh installed server

### Describe the bug

I go through all installation steps of strapi but when i run it and go to the createFirstAdmin page, i have this error 

```
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)

```

### Steps to reproduce the behavior

1. Install a brand new server on my hoster ( gandi.net ) OS ubuntu 20.04
2. Install node.js version 12
3. Install yarn  `npm i -g yarn`
4. Install a brand new strapi project   `yarn create strapi-app my-project --quickstart `
5. Go to the administration page --> click on Create first administrator button.

### Expected behavior

At this point i expect a working strapi project but i get this `ECONNRESET `error

I tryed the same recipe on 2 brand new server from gandi.net
one with ubuntu 20.04 and one with ubuntu 18.04

### System

- Node.js version: 12.20.0
- NPM version: 6.14.8
- Strapi version: 3.4.1
- Database: sqlite3:"latest"
- Operating system: ubuntu 20.04

### Additional context

The same step works perfectly on my own computer running on ubuntu POP-OS 20.04

**Comment by derrickmehaffy** [comment]
The issue appears to be with your host, we need exact steps to reproduce if you believe it's a code error on our side.

For issues with your host, please contact them as there isn't much we can do.

**Comment by phamthainb** [comment]
@Oldwo1f I have got a same error here. Do you remember how to fix them?. Pls let me know

**Comment by DmitryKvant** [comment]
Same error

**Comment by yokotak0527** [comment]
I encountered the same error. I'm using nginx as proxy server, and changing the proxy settings resolved the error.

```nginx
# nginx.conf

server {
  # When set to "on", whiteout occurs.
  sendfile off;
  ...
  proxy_buffering off;
  ...
}
```

When sendfile is turned on, the screen will white out. The error message will also change as follows.

```bash
  Error: write ECONNRESET
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:798:11)
      at Socket._write (net.js:810:8)
      at doWrite (internal/streams/writable.js:377:12)
      at clearBuffer (internal/streams/writable.js:529:7)
      at Socket.Writable.uncork (internal/streams/writable.js:317:7)
      at connectionCorkNT (_http_outgoing.js:759:8)
      at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Also, I access it directly without nginx, no error will occur.

can't explain why this happens.
I'm looking into it now. I'm tired.

**Comment by yokotak0527** [comment]
I found the cause of the problem, so I'll write it down even though it's not a strapi problem.

> This issue isn't with Nginx, it's with your database. ECONNRESET is a database error

No, it was still a problem with Nginx in my environment.

The cause is that the permission to temporary files under `/var/lib/nginx/` was lost because the user who runs Nginx was changed.

> I encountered the same error. I'm using nginx as proxy server, and changing the proxy settings resolved the error.
> ```
> # nginx.conf
> 
> server {
>   # When set to "on", whiteout occurs.
>   sendfile off;
>   ...
>   proxy_buffering off;
>   ...
> }
> ```

This means that buffering was turned off, so there was no access to the temporary file, and it worked fine.

**Comment by 1saifj** [comment]
thanks @yokotak0527 it is work for me!

**Comment by 0speedy** [comment]
In my case, the issue was an insufficient disk capacity. Once cleaned it all worked fine again.

**Comment by remrcll** [comment]
Hey @yokotak0527 !

So, it turns out the problem wasn't actually with the database like we thought. It was actually an issue with Nginx and its temporary files directory permissions.

Basically, the directory where Nginx stores temporary files (`/var/lib/nginx/`) didn't have the right permissions for Nginx to do its thing properly. At least in my case it was set up to only allow root access, which meant Nginx couldn't write temporary files like it needed to.

To fix it, I did a couple of things:
1. I changed the ownership of the directory and everything inside it to the `www-data` user and group. That way, Nginx could access it without any issues. I did this with the command:
   ```
   sudo chown -R www-data:www-data /var/lib/nginx/
   ```

2. Then, I made sure that the `www-data` user and group had the right permissions to read, write, and execute files in the directory. This was done with the command:
   ```
   sudo chmod -R 770 /var/lib/nginx/
   ```

After making these changes, I restarted Nginx to apply the changes:
```
sudo systemctl restart nginx
```

After that, Nginx could create and manipulate temporary files in the directory without any problems, and the ECONNRESET errors went away.

So yeah, that's basically what happened! Just had to tweak some permissions, restart Nginx, and now everything's running smoothly again, without using ```sendfile off;```and ```proxy_buffering off;```

Your solution to change the Nginx proxy settings (sendfile off and proxy_buffering off) is effective in certain scenarios, particularly when dealing with issues related to file buffering and transmission. However, in my case, addressing the permissions on the temporary files directory proved to be the more appropriate solution.

Hope that helps!
