### ISSUE TITLE
Instagram OAuth provider is broken

### ISSUE THREAD

**Issue by baptisteArno** [strapi/strapi#9036]
### Describe the bug

Instagram OAuth provider doesn't work anymore.

`{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}` when calling `{{STRAPI_BASE_URL}}/connect/instagram`

### Steps to reproduce the behavior

1. Follow [the official procedure](https://strapi.io/documentation/developer-docs/latest/plugins/users-permissions.html#providers)
2. Call `STRAPI_BASE_URL/connect/instagram`

### Expected behavior

Redirect to Instagram authorization page

### System

- Node.js version: 14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.0

### Additional context

Now the Instagram API [requires the `scope` param](https://developers.facebook.com/docs/instagram-basic-display-api/reference/oauth-authorize#reading). 

I tried to override the grant config by creating a `bootstrap.js` file in `/extensions/users-permissions/config/functions/`
with this:
```js
instagram: {
      enabled: false,
      icon: "instagram",
      key: "",
      secret: "",
      callback: `${strapi.config.server.url}/auth/instagram/callback`,
      scope: ["user_profile"],
    }
```

But it still doesn't add the scope param in the url. I don't understand why.

**Comment by baptisteArno** [comment]
> I tried to override the grant config by creating a bootstrap.js file in /extensions/users-permissions/config/functions/
> with this:
> 
> instagram: {
>       enabled: false,
>       icon: "instagram",
>       key: "",
>       secret: "",
>       callback: `${strapi.config.server.url}/auth/instagram/callback`,
>       scope: ["user_profile"],
>     }
> But it still doesn't add the scope param in the url. I don't understand why.

I want to investigate further but I don't understand why this 👆👆 doesn't add a `scope=user_profile` to the instagram authorize URL. It is a valid grant config, it is supposed to work.

Do you have an idea @derrickmehaffy?

**Comment by petersg83** [comment]
Hi,

I investigated and I think it's because they changed their whole API : https://www.instagram.com/developer/

As you said, I think we need to update the scope + we need to modify purest (https://github.com/simov/purest) config or wait for it to be updated.

PS: I think your override doesn't work because you changed the initial config only. To modify the actual config you can modify the raw with key `plugin_users-permissions_grant` in the table `core_store` in your database (or delete it and it will be re-created but you'll lose all the providers config (client_id, client_secret etc.) )
