### ISSUE TITLE
Error when launching Strapi in workspaces

### ISSUE THREAD

**Issue by bulby97** [strapi/strapi#9079]
## Bug report

When building Strapi in workspace via yarn, the following error occurs: 
```
Error: Module not found: Error: Can't resolve '@buffetjs/styles/webfonts/Lato-Black.woff2' in '.cache/admin/src/components/Fonts
```

### Steps to reproduce the behavior

1. Create workspace packages/strapi
2. Start strapi project
3. See error

### Expected behavior

Build should work

### Workaround

Add no hoist to `packages/strapi/package.json`

```
"workspaces": {
    "nohoist": [
      "**"
    ]
  }
```

### System

- Strapi version: 3.4.1
- Operating system: OSX

**Comment by derrickmehaffy** [comment]
We don't currently support the workspaces system, what you would need to do is run the `yarn && yarn setup` in the mono-repo, then run the node script located here: https://github.com/strapi/strapi/blob/master/scripts/link.js

This will dump all the package changes and symlink them into your global yarn, from there, create a new project and run the `yarn link pastePackageNamesHere`

This will force that project to run the symlinked packages from the global yarn. Marking as closed.

**Comment by james2mid** [comment]
**Updated workaround**

This can be fixed by setting `nmHoistingLimits: 'workspaces'` in the `.yarnrc.yml` file at the root of your workspace. See more about this option [here](https://yarnpkg.com/configuration/yarnrc#nmHoistingLimits).

This is an up-to-date equivalent of the workaround provided above by @bulby97. `nohoist` has since been deprecated.
