### ISSUE TITLE
strapi not installing with yarn create strapi-app my-project --quickstart

### ISSUE THREAD

**Issue by massimovassalli** [strapi/strapi#9120]
### Describe the bug

Hi, I cannot install strapi at all, either using yarn or npx
I get errors installing dependencies but I don't know how to address this. It seems to me at some point (sqlite3) it executes a Python2 script, while my systems runs on Python3, but I've no idea (I'm new to th eecosystem as well)

### Steps to reproduce the behavior

execute
yarn create strapi-app my-project --quickstart
at the CLI

### Screenshots

See errors below

### System

- Node.js version: 14.15.4
- NPM version: 6.14.10
- Strapi version: n/a
- Database: n/a
- Operating system: Windows 10

### Additional context

Creating a quickstart project.
Creating files.
Error while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > koa-ip > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > chokidar > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
warning strapi-admin > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning strapi-admin > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > react-intl > @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
warning strapi-admin > react-intl > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > react-intl > intl-messageformat > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning strapi-admin > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning strapi-plugin-users-permissions > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning strapi-plugin-users-permissions > request > har-validator@5.1.5: this library is no longer supported
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning knex > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning "strapi-admin > bootstrap@4.5.3" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.5.3" has unmet peer dependency "popper.js@^1.16.1".
warning "strapi-admin > @buffetjs/styles > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
warning "strapi-plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning " > strapi-connector-bookshelf@3.4.2" has incorrect peer dependency "knex@^0.20.0".
error C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.15.4 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\mv68b\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)

 Keep trying!

**Comment by JOEMN96** [comment]
same here man

**Comment by JOEMN96** [comment]
Did you find any way  to install strapi ?

**Comment by JOEMN96** [comment]
just got fixed ! 

change the sqlite3 version to 5.0.0  in package.json

let me know if it works for u

**Comment by ant-lkett** [comment]
same here

**Comment by massimovassalli** [comment]
Hi,
fixed here as well, but I still get an error at the end (no longer from sqlite3, see below).
Any suggestion on this?
Thanks

[4/5] Linking dependencies...
warning "strapi-admin > bootstrap@4.5.3" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.5.3" has unmet peer dependency "popper.js@^1.16.1".
warning "strapi-plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning " > strapi-connector-bookshelf@3.4.2" has incorrect peer dependency "knex@^0.20.0".
error An unexpected error occurred: "UNKNOWN: unknown error, lstat 'C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\strapi-plugin-upload\\admin\\src\\components\\CardControl'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by JOEMN96** [comment]
try clean install

**Comment by derrickmehaffy** [comment]
When you installed Node.js did you also install the build tools?

On Windows when you install Node you will get a step like this:

![image](https://user-images.githubusercontent.com/8593673/104763970-f15fee80-5723-11eb-8913-300aa5e27b63.png)

Which after install Node will bring up a command prompt window like this to install those tools:

![image](https://user-images.githubusercontent.com/8593673/104764037-0c326300-5724-11eb-9e63-e4c6193bfc29.png)

---

Or you can visit: https://github.com/nodejs/node-gyp#on-windows
OR
You can use something like this: https://www.npmjs.com/package/windows-build-tools

**Comment by derrickmehaffy** [comment]
Looks like there may be an issue with SQLite 5.0.1 on Windows, pending confirmation: https://github.com/mapbox/node-sqlite3/issues/1424

**Comment by derrickmehaffy** [comment]
I am unable to reproduce on my own machine:

OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

**Comment by derrickmehaffy** [comment]
Users having this issue, can you please navigate to your new project and modify the package.json to set the `sqlite3` package from `^5.0.0` to just `5.0.0`

**Comment by massimovassalli** [comment]
Hi,
thanks for your suggestions.

I tried to install buildtools from Nodejs (either using the suggested npm line or using the provided script) but it installs Python2.7 and this is messing up my environment which is based on Python 3.9 ... I think the problem is here, not in strapi itself but upstream, but I don't know how to convince buildtools/nodejs to use the existing Python (which is included in the PATH) and not overwrite ( = destroy) it.

**Comment by Prashant4900** [comment]
Did the issue is resolved

**Comment by burhanaf** [comment]
same problem
in my case
change the "sqlite3": "lastest" to "sqlite3": "5.0.0" in package.json

**Comment by Prashant4900** [comment]
> same problem
> in my case
> change the "sqlite3": "lastest" to "sqlite3": "5.0.0" in package.json

So now it's worked ?

**Comment by burhanaf** [comment]
> > same problem
> > in my case
> > change the "sqlite3": "lastest" to "sqlite3": "5.0.0" in package.json
> 
> So now it's worked ?

yes

**Comment by Prashant4900** [comment]
> > > same problem
> > > in my case
> > > change the "sqlite3": "lastest" to "sqlite3": "5.0.0" in package.json
> > 
> > 
> > So now it's worked ?
> 
> yes

**********************************************************************************************************************
i do similar thing but not worked for me it's give different error not

**Step-1**

**i run the command:** npx create-strapi-app test-project-1 --quickstart

but it's give me the error link above:-
***********************************************************

PS C:\Users\prash\OneDrive\Desktop\root> npx create-strapi-app test-project-1 --quickstart
npx: installed 92 in 40.544s
Creating a new Strapi application at C:\Users\prash\OneDrive\Desktop\root\test-project-1.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated @babel/polyfill@7.12.1: �🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See 
e @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
info sharp Using cached C:\Users\prash\AppData\Roaming\npm-cache\_libvips\libvips-8.10.0-win32-x64.tar.br
info sharp Creating C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sharp\vendor\8.10.0\lib to C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sharp\build\Release
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\prash\\OneDrive\\Desktop\\root\\test-project-1\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\prash\\OneDrive\\Desktop\\root\\test-project-1\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sqlite3
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\prash\\OneDrive\\Desktop\\root\\test-project-1\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\prash\OneDrive\Desktop\root\test-project-1\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})        
npm WARN strapi-connector-bookshelf@3.4.3 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @buffetjs/utils@3.3.3-next.2 requires a peer of yup@^0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prash\AppData\Roaming\npm-cache\_logs\2021-01-16T08_19_00_793Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd C:\Users\prash\OneDrive\Desktop\root\test-project-1 && npm install

**********************************************************************************************************************





**then i changed sqlite3 version** 

![image](https://user-images.githubusercontent.com/62440911/104807231-72da7e00-5803-11eb-95c8-919df840b9e6.png)

to 

![image](https://user-images.githubusercontent.com/62440911/104807235-81289a00-5803-11eb-9bfa-62ec4ddc3790.png)


**********************************************************************************************************************


**and run the command _npm install_  inside project folder** 

![image](https://user-images.githubusercontent.com/62440911/104807285-e41a3100-5803-11eb-945c-1a35c2241385.png)


**********************************************************************************************************************


**but when i run the project it's give the error like this**

![image](https://user-images.githubusercontent.com/62440911/104807314-175cc000-5804-11eb-850c-ce5913d51542.png)

![image](https://user-images.githubusercontent.com/62440911/104807327-32c7cb00-5804-11eb-9c5b-a10090a7b0f6.png)

**********************************************************************************************************************

and also its does not create any index.html file or build folder 

this is folder structure
![image](https://user-images.githubusercontent.com/62440911/104807346-5ee34c00-5804-11eb-936a-a4127a78577e.png)
![image](https://user-images.githubusercontent.com/62440911/104807353-78849380-5804-11eb-86b8-3273cb1b9234.png)

**Comment by kimsehwan96** [comment]
> ![image](https://user-images.githubusercontent.com/62440911/104807327-32c7cb00-5804-11eb-9c5b-a10090a7b0f6.png)
> 
> and also its does not create any index.html file or build folder
> 
> this is folder structure

@Prashant4900 

It's my case. 

try `npm run-script build`

My case was same as you. I did it and success.

**Comment by Prashant4900** [comment]
> 
> > ![image](https://user-images.githubusercontent.com/62440911/104807327-32c7cb00-5804-11eb-9c5b-a10090a7b0f6.png)
> > 
> > and also its does not create any index.html file or build folder
> > 
> > this is folder structure
> 
> @Prashant4900 
> 
> It's my case. 
> 
> try `npm run-script build`
> 
> My case was same as you. I did it and success.
> 

@kimsehwan96 

but what if I want to debugging the project

Isn't this command directly build the project for production use ?

**Comment by kimsehwan96** [comment]
@Prashant4900 

I thought like you :)

But It was builded for developement version when I used that command !

After build you should use `npm run-script strapi develop`

**Comment by msarelo** [comment]
I applied tips in this thread but I'm still getting issue with sqlite3 and python path

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/cannot-create-new-strapi-project-mac/2104/5

**Comment by derrickmehaffy** [comment]
If you have depends issues:

Windows => https://github.com/strapi/strapi/issues/9120#issuecomment-761106368
Mac => Make sure you have XCode and the XCode build tools

If you have an issues with building SQLite, see: https://github.com/strapi/strapi/issues/9120#issuecomment-761115362

---

Locking thread as no new info, will unlock if we need more info.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/error-while-doing-npm-install-i-tried-with-node-12-14-as-well/2880/2
