### ISSUE TITLE
Cross linking(relationships) collection types within the dynamic zone blocks breaks Strapi and corrupts database

### ISSUE THREAD

**Issue by bskuratov** [strapi/strapi#9132]
## Bug report

Strapi goes into infinite loop, after restart you can't access collection type

### Describe the bug

When you are trying to link one collection type item to another and do the same in reverse within the dynamic content zone, Strapi goes into infinite. It happens both for items within one collection type or different collection types. 

### Steps to reproduce the behavior

1. Create a collection type "Post" with the dynamic zone.
2. Create block within the dynamic zone(i.e. Related Posts) with relationship field. 
2. Create a post "A" and post "B"
3. Add Related Posts block to post "A", select post "B"
4. Add Related Posts block to post "B", select post "A". When you will click save, Strapi will go into an infinite loop.
5. Restart server, navigate to Posts collection type, they won't be shown and you will see infinite loader until you manually delete one of the Related Posts blocks from db.

OR

1. Create collection types "Page" and "Post" with dynamic zones.
2. Create 2 blocks within dynamic zones(i.e. Related) with relationship field. For Page - it will allow linking to Post, for Post - it will allow linking to Page. 
2. Create page "A" and post "B"
3. Add Related block to page "A", select post "B"
4. Add Related block to post "B", select page "A". When you will click save, Strapi will go into infinite loop.
5. Restart server, navigate to Posts or Pages collection types, they won't be shown and you will see infinite loader until you manually delete one of the Related blocks from db.

### Expected behavior

Prevent infinite loop and breaking of the server, either by fixing it or just not allowing to save the second item. 

### System

- Node.js version: 14.15.4
- NPM version: 6.14.10
- Strapi version: 3.3.4, 3.4.1
- Database:  MongoDB Atlas 4.2.11
- Operating system: MacOS Big Sur 11.1, Heroku Stack heroku-20

### Additional context

I have tried to recreate the issue with a new clean environment. With MongoDB Atlas it happens immediately, while with SQLite everything worked fine, so it seems that problem related exactly to MongoDB Atlas.

**Comment by derrickmehaffy** [comment]
I am able to reproduce on v3.4.5 with the follow error:

```
[2021-02-02T15:48:19.478Z] error CastError: Cast to ObjectId failed for value "1" at path "_id" for model "post"
    at model.Query.exec (/home/dmehaffy/Development/test9132/node_modules/mongoose/lib/query.js:4371:21)
    at model.Query.Query.then (/home/dmehaffy/Development/test9132/node_modules/mongoose/lib/query.js:4463:15)
    at find (/home/dmehaffy/Development/test9132/node_modules/strapi-connector-mongoose/lib/queries.js:434:8)
    at Object.findOne (/home/dmehaffy/Development/test9132/node_modules/strapi-connector-mongoose/lib/queries.js:438:27)
    at fn (/home/dmehaffy/Development/test9132/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.findOne (/home/dmehaffy/Development/test9132/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.findOne (/home/dmehaffy/Development/test9132/node_modules/strapi/lib/core-api/controller.js:95:22)
    at async /home/dmehaffy/Development/test9132/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async module.exports (/home/dmehaffy/Development/test9132/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:88:3)
    at async /home/dmehaffy/Development/test9132/node_modules/strapi-utils/lib/policy.js:68:5
    at async serve (/home/dmehaffy/Development/test9132/node_modules/koa-static/index.js:59:5)
    at async /home/dmehaffy/Development/test9132/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /home/dmehaffy/Development/test9132/node_modules/strapi/lib/middlewares/xss/index.js:26:9
```

[test9132.zip](https://github.com/strapi/strapi/files/5912448/test9132.zip)

**Comment by danielgriese** [comment]
Hi all,

We are currently facing the same issue and unfortunately it's a **showstopper** for us and our use case as we need this kind of cross-referencing.

I followed down the rabbit whole a bit and the provided sample from @derrickmehaffy does indeed cause the described problem. Thanks @derrickmehaffy for providing it! But I am not sure if we are talking about the same "root cause" & effect.

I do not have a solution at this point, below is just a more detailed description of what is actually happening and a tentative assumption of a way to fix this.

So far, I do not see any kind of database corruption as you have mentioned Derrick. The database and collections/documents are fine and probably work as intended. But requesting a (cross-referencing) post (either via REST, via GQL or even via query(...).find(...)) causes an **endless relational population** and thus finally a crash with **JavaScript heap out of Memory**. 💥 💥 💥  

And I think this is what @bskuratov was describing with "blocks strapi" and "infinite loop".

### Problematic Setup

Using the provided test-setup, I've created 2 posts.
`A. _id: ObjectId("6020f2f70b19b6251ea89e66")`
`B. _id: ObjectId("6020f2fe0b19b6251ea89e67")`

and then linked each other in their dynamic zones, resulting in a DB structure like this.
So saving/creating the references is indeed fine. But the UI hangs as it requests the resource after saving, and then the issue hits.

`A. testdz: 
[
    {
        "_id" : ObjectId("6020f9c50b19b6251ea89e6b"),
        "kind" : "ComponentBlahLinky",
        "ref" : ObjectId("6020f9c50b19b6251ea89e6a")
    }
]`

`A. components_blah_linkies:
{
    "_id" : ObjectId("6020f9c50b19b6251ea89e6a"),
    "__v" : 0,
    "post" : ObjectId("6020f2fe0b19b6251ea89e67")
}`

`B. testdz: 
[
    {
        "_id" : ObjectId("6020f3060b19b6251ea89e69"),
        "kind" : "ComponentBlahLinky",
        "ref" : ObjectId("6020f3060b19b6251ea89e68")
    }
]`

`B. components_blah_linkies:
{
    "_id" : ObjectId("6020f3060b19b6251ea89e68"),
    "__v" : 0,
    "post" : ObjectId("6020f2f70b19b6251ea89e66")
}`

So, with **posts** and _components_blah_linkies_ we have this linking:
**6020f2f70b19b6251ea89e66** -> _6020f9c50b19b6251ea89e6a_ -> **6020f2fe0b19b6251ea89e67**
**6020f2fe0b19b6251ea89e67** -> _6020f3060b19b6251ea89e68_ -> **6020f2f70b19b6251ea89e66**

### Issue: Endless relational population

If you stop the server and restart it, everything is fine (no corruption), but requesting one of the posts hit this endless loop again. You can see this pretty clearly when starting mongoose in debug mode. Requesting the posts will bring 🔥  to the console.

> [...]
> 
> Mongoose: posts.find({ '$and': [ { _id: ObjectId("6020f2f70b19b6251ea89e66") } ], published_at: { '$ne': null, '$exists': true }}, { publicationState: 'live', session: null, skip: 0, limit: 1, projection: {}})
> [...]
> 
> Mongoose: components_blah_linkies.find({ _id: { '$in': [ ObjectId("6020f9c50b19b6251ea89e6a") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: posts.find({ published_at: { '$ne': null, '$exists': true }, _id: { '$in': [ ObjectId("6020f2fe0b19b6251ea89e67") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: components_blah_linkies.find({ _id: { '$in': [ ObjectId("6020f3060b19b6251ea89e68") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: posts.find({ published_at: { '$ne': null, '$exists': true }, _id: { '$in': [ ObjectId("6020f2f70b19b6251ea89e66") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: components_blah_linkies.find({ _id: { '$in': [ ObjectId("6020f9c50b19b6251ea89e6a") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: posts.find({ published_at: { '$ne': null, '$exists': true }, _id: { '$in': [ ObjectId("6020f2fe0b19b6251ea89e67") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: components_blah_linkies.find({ _id: { '$in': [ ObjectId("6020f3060b19b6251ea89e68") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: posts.find({ published_at: { '$ne': null, '$exists': true }, _id: { '$in': [ ObjectId("6020f2f70b19b6251ea89e66") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: components_blah_linkies.find({ _id: { '$in': [ ObjectId("6020f9c50b19b6251ea89e6a") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> Mongoose: posts.find({ published_at: { '$ne': null, '$exists': true }, _id: { '$in': [ ObjectId("6020f2fe0b19b6251ea89e67") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, publicationState: 'live', projection: {}})
> 
> [...]


and so on, until memory limit hits and crashes.

### Probable Solutions
So far I have none. I forked the repo and will dig a little deeper.
I assume the problem to be somehow related to the "auto-population" of dynamic zones and components in the mongoose wrapper. I understand that this is per se intended as it's an implementation detail of the DB layer to split this into different collections. 

We can prevent the issue by setting `autoPopulate: false` in the configuration of our component (linky), but then we loose the ability to see the referenced elements in the admin UI (so that would be merely fixing a symptom and not the cause).

@bskuratov mentioned a possible workaround of detecting the cross-reference and prevent saving (e.g. could be done in beforeCreate), but this is actually not that easy to detect as this even happens if we are cross-referencing indirectly.
So A -> B; B -> C; C -> A would cause the same problem!

And at the end, this would not solve the underlying problem.

### Flawed population
I'm afraid the implementation itself is a bit flawed.

When using the `find()` method and explicitly passing `[]` as an empty population, it will still resolve all "embedded components"... Fine, as mentioned above, to the application it shall appear as a single nested document (and we cannot easily access the component-collection directly).
But then the population logic will go ahead and still auto-populate all the relations (!) in the resolved component too! And this is not what I would assume if I pass `[]` to the query. As I explicitly tell the application not to resolve any (collection type) relations (not on the first level, but also not on any deeper level).
But our component->relation logic seems to have it's own way and does not care about the passed population params of the original query.

This will in the end cause a lot of relations to be resolved (and thus a lot of over-fetching and a poor performance) if we have a deeply nested relation/component structure (e.g. with media-fields). If we were to add a `picture` field to our post collection, this would also expand/resolve all picture on any of the calls and on any depth-level, (even though we are only interested about the first level of depth!)

As to sum up this text (being way too long already), my approach would be to look at the auto-popuation of dynamic zones/components and why it does not respect the "only auto-populate the first level" rule that is to applied to regular collections. If that would be solved, we could probably solve both issues at once:

1. Endless cross-resolving and heap crash
2. Overfetching unneeded depths / relations

But I just started to get to know the code/implementation and don't feel comfortable messing with the underlying assumptions. Maybe whoever wrote that part could chime in ;)
As a first part, I might try to detect the cross-population first, to stop the crash from happening. The overfetching part is just a general optimisation, which would be nice to solve at once.

I'll see how far I'll get on my own. Maybe I can submit a solution to this.
Going to keep you posted, if I find anything.
Kind regards,
Daniel

**Comment by danielgriese** [comment]
So far I have tracked this down to the following piece in `mount-models.js`

Each mongoose schema (so also components), register a `pre` middleware for find* functions in order to pre-populate subfields.

At line 345 this middleware handles population of component associations, where we also see that `autoPopulate` would be respected (but as mentioned above it does not necessarily help in regards to admin UI).

In my opinion this code block should respect the depth of the current population tree and not populate the relations if we aren't at the first depth level.

I am still clueless how we can know the current depth (while debugging I do not see any useful indication). Also not sure how the "session" parameter of a query could be used for this. Still searching.

So if we could establish some sort of object (like the session) that would be passed through to all layers of following population we could solve this.
Either by entirely cutting of component-population on deeper levels (but I am not sure about the implications/side effects) or at least try to detect circular references.

**Comment by danielgriese** [comment]
This ticket can be closed as it was fixed by @alexandrebodin in https://github.com/strapi/strapi/pull/9367 and has been released with v.3.5.0

Looks like this ticket has been a duplicate all along.

I can confirm that the issue described here is in fact solved by the fix. And I'm glad to see that it also solves the "deep overfetching" issue! Thanks!
