### ISSUE TITLE
Ability to manage content manager views for different roles

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#9140]
### Please describe your feature request

- [] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

In production, it would be very useful to be able to manage views in Content Manager for different admin roles. 
For example, I don't have an ability to hide fields, so if I don't want users with some role to even about existence of some field in admin panel, I have to configure the view for everybody, not for only admin role.

### Why is it needed?

It will provide better experience for enterprise users and higher manageability of whole framework.

### Suggested solution(s)

It may look this way:

![image](https://user-images.githubusercontent.com/20924122/104749588-0c525300-5764-11eb-80d2-6a1267acf7b7.png)

And also this way:

![image](https://user-images.githubusercontent.com/20924122/104749836-52a7b200-5764-11eb-951f-daf98bd3fa16.png)

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
We were just talking about this the other day @sam-pires :laughing: 

Thank you @eriskhan for the feature request!

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/allow-for-different-views-listedit-based-on-admin-role
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
