### ISSUE TITLE
Content Type Builder Buttom is Not Showing

### ISSUE THREAD

**Issue by Prashant4900** [strapi/strapi#9148]
First I will face this issue but after the solving (#9120 )

https://github.com/strapi/strapi/issues/9120

my project is build successfully but when i login and try to build the content type the button is not showing

![image](https://user-images.githubusercontent.com/62440911/104818639-db9b1800-584e-11eb-881c-21c65b10cf57.png)

**Comment by derrickmehaffy** [comment]
You are either:

- In production mode, in which case this is intended: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
- Using the `start` command instead of `dev` or `develop`

Marking as closed as this is intended.
