### ISSUE TITLE
How to connect to MongoDB on AWS using x.509 authentication

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#9215]
**Description:**  How to connect to MongoDB on AWS using `x.509` authentication

We are on Strapi `v3.0.6`. We are going to use Mongo `x.509` authentication to connect to MongoDB running on AWS.
What are the changes we need to make on the Strapi to connect to it?

Below is the code we currently have but this is with out using `x.509` authentication:

```js
 module.exports = env => {
   return {
     defaultConnection: 'default',
     connections: {
       default: {
         connector: 'mongoose',
         settings: {
           client: 'mongo',
           uri: env('MONGO_URI'),
           username: env('MONGO_USERNAME'),
           password: env('MONGO_PASSWORD')
         },
         options: {
           useNullAsDefault: true,
           debug: true
         }
       }
     }
   };
 };
```

**Please let us know what are the code changes we need to make on Strapi to connect to MongoDB on AWS using `x.509` authentication.**

**System**

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo
- Operating system: MAC

**Additional context**

> 

>

**Comment by derrickmehaffy** [comment]
At the moment we are not currently checking for the connection options required to use x.509 certificates per:

https://github.com/strapi/strapi/blob/3f1fa39ccb1c296e0170ef6424018fec748b8657/packages/strapi-connector-mongoose/lib/index.js#L82-L101

These are the options that the MongoDB driver used by Mongoose accept: http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html

Specifically we would need to add something like:

```js
// Read the cert and key
let cert = fs.readFileSync(__dirname + "/path/to/x509/client.pem");
let key = fs.readFileSync(__dirname + "/path/to/x509/client.pem");

connectOptions.sslCert = cert
connectOptions.sslKey = key
```

@vinod77 you can have your team test out options like this by directly modifying the node_modules however in order to have full support it will almost certainly require a pull request. I'm not sure how quickly we (the strapi team) can implement this with proper testing so if you or your team are willing to contribute a PR that would be great.

---

Alternatively if there is anyone in the community willing to assist please let us know.

**Comment by vinod77** [comment]
Hi @derrickmehaffy Thank you for the detailed response.

As you suggested, we tried to use above changes on `strapi-connector-mongoose` package.. but our Strapi app is still not connecting to the DB.

Could you please let us know what changes we need to make on `database.js`? (Please see our current `database.js` for `user/pwd` based basic Authentication above)

We have below details:
1. key.pem
2. chain.pem
3. Mongo URI (with DB host, port, DBName & ReplicaSet)
4. Mongo x509 user

**Note:**
I am able to connect to our mongoDB from terminal using below command:
`mongo hostname:port --ssl --sslPEMKeyFile <path to key.pem File> --sslCAFile <path to chain.pem File> --sslAllowInvalidCertificates --verbose`

and can run Mongo queries after running this cmd:
`db.getSiblingDB("$external").auth( { mechanism: "MONGODB-X509", user: " " })`

**Comment by derrickmehaffy** [comment]
> Could you please let us know what changes we need to make on database.js? (Please see our current database.js for user/pwd based basic Authentication above in the Description)

Currently it's not a database.js issue but a package issue, we don't have the options currently to support x.509 auth (and it's quite difficult to find the proper documentation with mongoose to even use the method).

While I do understand your local CLI client works, the issue here is not with the driver but how to pass the information onto mongoose which itself uses the driver (for node).

At the moment we have this marked as a feature request as it's not directly an auth method we support, and I don't currently have an ETA for this auth method.

**Comment by vinod77** [comment]
We are able to fix this issue overriding `strapi-connector-mongoose` plugin. Now we are not able to connect to MongoDB using X509 certificate based authentication.
I can put a PR soon for this.
Thank you @derrickmehaffy for your support, help on this. Closing this issue.

Thanks!
