### ISSUE TITLE
Adding a Logout Route to Strapi

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#930]
**Informations**
- **Node.js version**:
 v9.11.1
- **npm version**:  
5.6.0
- **Strapi version**:
v3.0.0-alpha 11.3
- **Database**:
MySQL Database
- **Operating system**:
Windows 10

**What is the expected behavior?**

Feature request to add a log-out Route to Strapi. Currently we have to delete the jwt from the session but a dedicated url for logging out could prove very useful! Has been referenced before at #702 as a question but not as a feature request. 

- [ x ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hi @piere129, on login route we don't store the JWT in session.

An explication about the issue you linked. Your ctx.session is on a server instance. If you have multiple servers with a load balancer, your user requests will not hit the same server each time. So you don't have to store the JWT in session if you want a logout function. Refer to my comment on the issue.

**Comment by piere129** [comment]
thank you, figured it out!

**Comment by n8tb1t** [comment]
@piere129  so what's the solution?

**Comment by EAdeveloper** [comment]
> figured it out!

What was your solution?

**Comment by derrickmehaffy** [comment]
@EAdeveloper just delete the token from storage (client side), there is no method to deauth a JWT on the server side without changing the JWT secret and deauthing everyone.

**Comment by EAdeveloper** [comment]
> @EAdeveloper just delete the token from storage (client side), there is no method to deauth a JWT on the server side without changing the JWT secret and deauthing everyone.

@derrickmehaffy 
I understand that you can remove the token from client storage, but my clients (non-technical people) are using shared devices and someone could easily trick them into stealing the client-side token and since the token does not expire in a short time, the malicious hacker could do a lot of damage over a long period of time with this token and there is no mechanism built into @strapi to stop them.

Also, we use third-party providers like Microsoft to authenticate and even if you remove the token from the client's storage, the user still logged in, so this might not be feasible when the staff is using shared PCs to collect sensitive data.

According to the following there some ways you can help mitigate the issue mentioned below.

https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens

**Comment by derrickmehaffy** [comment]
It requires Strapi to store some kind of state, and at the moment we don't. Either that be a "blacklist" of used/expired keys (ugly and not feasible) or a "whitelist" of active keys.

The whitelist of keys is doable but in a clustered state you need some kind of central storage (database/ect) and for the moment we don't have the bandwidth to construct this solution. Moving forward when we add in the API key feature, the users-permissions plugin will become optional and not installed by default.

We also plan to do a massive rewrite of the users-permissions plugin and move over to passport.js, at that time users will be able to customize the providers, including the JWT one, so we will leave the option open to handle it then.
