### ISSUE TITLE
CTB - Mark custom field as unavailable and still allow for regular fields to be edited

### ISSUE THREAD

**Issue by Norbz** [strapi/strapi#9346]
## Bug report
Not much of a bug, per say, but not really a feature request either.

### Describe the bug

Accessing the content type builder when using a custom field (such as the Color Picker fields from the [well know tutorial](https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms) ) results in errors and the Content-Type not being editable.

As I understand that the custom field API is only supported by the CTM right now, maybe until we got the plugin API V4 we should have custom fields marked as unknown and unavailable, leaving the possibility to edit regular fields within the CTB.

### Steps to reproduce the behavior
in dev mode :
1. Edit a content-type model so it makes use of a custom fields
2. Go to content-type builder, and select the edited content-type

### Expected behavior
I would expect to be able to see my content-type without any error, with my custom field greyed out, and other fields still editable

### Screenshots

Error when accessing the CT with a "puid" custom type
<img width="1002" alt="error" src="https://user-images.githubusercontent.com/6388929/107237721-54912800-6a27-11eb-886c-8ef17c42b197.png">

improved  behavior (example) :
![result](https://user-images.githubusercontent.com/6388929/107237809-6e326f80-6a27-11eb-9952-3f46479bad61.jpg)

### Code snippets
None right now

### System

- Node.js version: 12.X
- NPM version: npm 6.x
- Strapi version: 3.4.6
- Database: Not DB related (tested on PostGreSQL and Mongo though)
- Operating system: MacOS

### Additional context

Should be done in a fast and temporary measure only, if possible.

**Comment by derrickmehaffy** [comment]
Hi @Norbz 

Currently we don't entirely support custom fields yet, the current solution is a bit hacky and as you have figured out it breaks the CTB for the Model.

Also going to link this to: https://portal.productboard.com/strapi/1-roadmap/c/10-custom-fields

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/custom-fields
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
