### ISSUE TITLE
"Invalid Input Data Please Verify Unique Constraints " after migrating from OneClick to AWS

### ISSUE THREAD

**Issue by Tej-Bains** [strapi/strapi#9371]
Bug report
Describe the bug

Moved my strapi build from digitaloceans one click service to aws self-installed strapi on ubuntu 18. with postgres rds.

Database was migrated using aws datamigration service. Content was successfully migrated. There were some initial errors, but repeat of the process with truncate enabled allowed the database to be moved successfully.

Strapi is showing the data, but when trying to edit the migrated content you get met with the error "Invalid Input Data Please Verify Unique Constraints ".
Steps to reproduce the behaviour

    Open a digitalocean one click strapi app add some content.
    Set up aws strapi server and database and s3 bucket and steps.
    move database from digitalocean to aws.
    try to change content after logging in.

Expected behavior

No error and successful edit of the fields.
System

    Node.js version: 10.19.0
    NPM version: 6.14.4
    Strapi version: 3.46
    Server: AWS EC2 Ubuntu 18
    Database: postgres on aws rds
    Operating system: windows os

Additional context

from the backside the postgres database is giving a 400 error. But if i were to add a item to the collection content, then that item works fine. I just cant edit or change SOME fields in the cms for content that was migrated over.

Ive tried with node_env to both dev and production.

ive tried strapi development mode.

ive tried strapi production.

ive tried updating all the npm packages and updating to latest strapi build.

still getting the same error.

is this issue related to security groups on aws? or the s3 bucket for file uploads?

any help is appreciated.

**Comment by Yumiwork** [comment]
I'm having a similar issue. 

Created a Strapi Project configured to mongoDB Atlas, where I had an existing database. In the admin panel I designed a content-type matching the headers of the existing collection. Everything went fine and strapi recognised the pre-existing content. 

But now I can only publish/unpublish these items, I cannot modify and save, as I get the same error message as specified above. 

I have created a new item from inside the admin panel, then copy/pasted and saved all fields one by one to find if there was one causing the issue. Nothing came up, and I can save this new item with the exact same content without getting this error message.

**Comment by Yumiwork** [comment]
I have had the same error message in a similar situation, in my case it was an issue with the type of some of the data.

I built a Strapi project and connected it to an existing MongoDB Atlas, by creating a content-type in Strapi that matched the ones in my collection in Atlas. I could create/save new items but had the same error as you when trying to modify the existing content.

The issue was a difference between the type of a field declared in Strapi vs MongoDB. 

In my case I had a `boolean` (Strapi) that was matched to a `string` (Mongo) and other similar cases. I reviewed all my fields to make them match each other (you can change either the Strapi field type or the one in the database) and when done I could now modify and save the pre-existing content.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9369
