### ISSUE TITLE
Aggregate graphql query for mongodb does not ignore start and limit values

### ISSUE THREAD

**Issue by JeetChaudhari** [strapi/strapi#9391]
### Describe the bug

Aggregate graphql query for mongodb does not ignore start and limit values.

### Expected behavior

Aggregate graphql query should ignore start and limit values just like count.

### Screenshots
With Start and Limit
![image](https://user-images.githubusercontent.com/5988124/107738437-ab02ad00-6d2c-11eb-9788-2ea526a24282.png)

Without Start and Limit
![image](https://user-images.githubusercontent.com/5988124/107738520-db4a4b80-6d2c-11eb-8186-ec8e13cde921.png)

Notice how the sum for premium changes, in previous versions it used to be same but not anymore. It changes for every pagination query.

### System

- Node.js version: 14.15.5 
- NPM version: 6.14.11
- Strapi version: 3.4.6
- Database: MongoDB
- Operating system: Ubuntu Docker Container

**Comment by jonashaefele** [comment]
Found this through https://github.com/strapi/strapi/issues/8574 and struggling with the same concepts.

I thought this might be a different bug, but the comment there was to add info to this issue...

The GraphQL allows for `publicationState` and other filters for "direct queries" of `content-types` in strapi, but ignores it for its connections/aggregations.

e.g. I can query
```
{
  posts(
      publicationState: LIVE
    ) {
      title
    }
}
```
but I can't do:
```
{
    postsConnection (
      publicationState: LIVE
    ) {
      aggregate {
        count
        totalCount
      }
    }
}
```

Which makes it super hard to build any kind of pagination, since the count always includes drafts as well. 

Any hints on how to achieve that would be amazing, or confirmation that it's currently not implemented/possible.

**Comment by derrickmehaffy** [comment]
Basically fixed on v4 because we no longer support mongo and graphql was rewritten without aggregations for now.

**Comment by aceonics-team** [comment]
> Basically fixed on v4 because we no longer support mongo and graphql was rewritten without aggregations for now.

Its not basically fixed, but basically avoided or skipped.
