### ISSUE TITLE
Duplicate a content-type

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#9429]

**Comment by spss20** [comment]
Is there any update on this feature?

**Comment by soupette** [comment]
Hello!

It is not currently planned on our ROADMAP, however until we consider adding such feature you can use the files to duplicate your content type

**Comment by rohitashwabgp** [comment]
@derrickmehaffy  @soupette  i came across this link . But , i was not able to figure out the solution. If this feature is not going to be added can you please tell which api or how to add a clone button component(marked cross in image below)

![image](https://user-images.githubusercontent.com/23148341/161901757-47b57ec6-b92c-4128-ae75-99552a315923.png)


bootstrap(app) {
    const ctbPlugin = app.getPlugin("content-type-builder");
    if (ctbPlugin) {
      const ctbFormsAPI = ctbPlugin.apis.forms;

}
}

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/duplicate-a-content-type
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Comment by eanappi** [comment]
Make a component, is a reusable fields group
