### ISSUE TITLE
Disable plural

### ISSUE THREAD

**Issue by ulaDEVEL** [strapi/strapi#943]
Hi

Can I disable plurals in the admin panel?

**Comment by lauriejim** [comment]
Hello @ulaDEVEL can you be more explicit on your question please.

**Comment by storm1er** [comment]
Hi,

Exemple: In french, I wish to name a content type "voiture" (car) and link it with another content type "conducteur" (driver).
I create a field in "voiture": "chauffeur attitré" (recognized driver)

In English, plural would be "recognized driverS", no prob.
In French, plural would be "chauffeurS attitréS", but your system provide "chauffeur attitréS".

Either strapi has to provide a way to set our own plural names, or @ulaDEVEL must use English name only.

I didn't open an issue because I choose the "Everything must be in English" solution _(Which is probably the best answer as we write code in english anyway ...)_.

**Comment by ulaDEVEL** [comment]
@storm1er That's exactly what I meant

**Comment by lauriejim** [comment]
@ulaDEVEL Can you update your issue with the issue template please. Are you using SQL database ? What is the Strapi version you use ?

Can you be more precise on where you set your field "chauffeur attitré". I don't see where you are in the admin interface.
Your field is a relation ? You are talking about attributes name or table/collection name ?

Actually I don't really understand the issue.

**Comment by ulaDEVEL** [comment]
> Are you using SQL database ? What is the Strapi version you use ?

No i use Mongo

> What is the Strapi version you use ?

v3.0.0-alpha.11.3

Example:
I have model called "Samochod" which means "Car" in english. In stapi admin on left menu my model display like this "Samochod**s**" and I do not want to have this extra **s**.

**Comment by derrickmehaffy** [comment]
@lauriejim this is likely related to my old issue here: https://github.com/strapi/strapi/issues/661

The user wants to disable the plural functionality completely though it would play into my suggestion.

**Comment by lauriejim** [comment]
Plural of this link is set here https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/containers/App/sagas.js#L33

There is no option to disable it. If you want you can update this file and rebuild your admin.
