### ISSUE TITLE
Cron in plugins

### ISSUE THREAD

**Issue by boazpoolman** [strapi/strapi#9437]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Ability for cron tasks to be written in a plugin.

### Why is it needed?

Say you have a twitter or instagram feed plugin, it would be handy to add a cron task directly in the plugin to fetch the feed every x hours e.g. Also I think it will open up room for more enhanced plugins to be written.

### Suggested solution(s)

Use the same naming convention as the normal cron in the plugin.
So you would add a file: `/plugin-name/config/functions/cron.js`.
Then we could read from these files in the cron middleware, see PR below.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/pull/9436

**Comment by derrickmehaffy** [comment]
@Lith we were just talking about this in a Slack PM :laughing:

**Comment by boazpoolman** [comment]
:crystal_ball:

**Comment by derrickmehaffy** [comment]
Like I'm not joking @boazpoolman it's scary how close this time was, we were just talking about work arounds when you posted this :rofl: :heart:

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/plugin-requests/p/cron-in-plugins
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
