### ISSUE TITLE
Photo Crop tool update

### ISSUE THREAD

**Issue by jonm01** [strapi/strapi#9467]
## Feature request

- ### Please describe your feature request
 - option to manually enter dimensions in the crop tool
- as of now crop tool is hard to find for a new user
- option to preset image dimensions(template) for a photo field so that cropping can be a part of content entry workflow. (in short image validation)

- [*] **I have created my request on the Product Board before I submitted this issue**
- [*] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary
photo crop tool missing feature

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/add-option-to-manually-specify-dimensions-in-the-crop-tool
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
