### ISSUE TITLE
Enable Deployment in AWS EC2 t2.micro

### ISSUE THREAD

**Issue by aditya-mitra** [strapi/strapi#9491]
## Feature request

A possible way to build and deploy on AWS EC2 t2.micro instance which gives 1 GB RAM.

### Please describe your feature request

AWS EC2 t2.micro is free for a year and provides 1GB. But *`npm run build`ing* strapi fails due to **not sufficient ram**.

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

*Brief History*
I really like Strapi. I really like the quickstart it provides.
We started using it to manage our backend.
We then liked it's admin interface- the roles, the permissions, setting of auth providers, and managing webhooks. All of this powers given in 3 custom role levels.
We then started to customize some of our apis to suite our custom purpose which strapi handled very nicely.
All of this setup worked fantastic in our local setup and we were ready to deploy.

*Present*

We created a docker-compose with our custom stapi Dockerfile and a postgres image. We started an **AWS ec2 t2.micro** instance and docker started building our containers. The problem was during `strapi build`, js threw **heap memory out** error indicating that there was not sufficient ram for build. So, during `npm start` we found out that the admin and some routes were not working.

### Why is it needed?

AWS EC2 T2.Micro is free to use. We are trying to run our backend on minimum costs.

### Suggested solution(s)

Strapi can build and run in 1GB Ram.

### Related issue(s)/PR(s)

None

**Comment by derrickmehaffy** [comment]
There are work arounds to run it on an instance with less than 2gb of ram but it's not supported. 

While we plan to try and decrease the ram required, we won't set a limit below 2gb as there are various other reasons you need more ram (like the operating system).

Marking as closed because, while this would be nice to have, it's not realistic. 

AWS EC2 is free, but it's not designed to handle an application like Strapi in a production setting. 

(If you want to hear the work arounds, please open a thread on our forum)

**Comment by aditya-mitra** [comment]
@derrickmehaffy I will open a thread on the forum
But can you please tell me all the possible options to launch the strapi application on **free basis on any platform**?

**Comment by derrickmehaffy** [comment]
Generally speaking, they involve building and committing your build folder into your source control.
