### ISSUE TITLE
Filter & Search based on createdBy 

### ISSUE THREAD

**Issue by sercanov** [strapi/strapi#9509]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Filtering records based on `createdBy` would be useful and easy to implement as it's already exist on API.

![image](https://user-images.githubusercontent.com/10291644/108993489-b69a9000-76ab-11eb-9972-3d5621df15cb.png)

### Why is it needed?

We have lot of Authors using the same collection, let's say Posts. As an admin user, I'd like to see all the posts created by one Author.

### Suggested solution(s)

Adding ability to `createdBy` condition to filters dropbox.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by zany88** [comment]
Same problem，i need this key。 I can not find

**Comment by soupette** [comment]
The displayed filters are based on both the user's permissions and also on the content type's attributes. Since the `createdBy` field is missing in both the permissions view and the content type's attributes this is why you cannot find it in the select options.

**cc/** @alexandrebodin @sam-pires

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/filter-and-search-on-created-by-in-the-admin
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
