### ISSUE TITLE
Add mutation to graphql for send-email-confirmation

### ISSUE THREAD

**Issue by DennieMello** [strapi/strapi#9555]
### Describe the bug

Previously, a functionality was implemented to send additional confirmation by email https://github.com/strapi/strapi/pull/4270

But with using graphql, it is not possible to send email. Can you add a mutation for grapql?

### Expected behavior

Ability to request to send email via graphql mutation.

### System

- Node.js version: 14.15.4
- NPM version: 7.5.4
- Strapi version: 3.5.1
- Database: postgresql 12.2
- Operating system: Mac OS 10.15.7

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/add-mutation-to-graphql-for-send-email-confirmation
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
