### ISSUE TITLE
Media files can be downloaded by non authenticated users

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#9572]
## Bug report
After uploading a file (connected to a collection type), the collection resource itself can be protected either by role configuration or more specific by a policy, but the url, which the collection type contains can still be accessed by anybody, even non authenticated users. I couldn't find a way to configure this. **What is the way to solve this problem**?  

### Describe the bug

Create a new collection type with a media field. Create a new record and upload a file. Configure the resource to be available only to users, which belong to the authenticated role. Then `GET` the resource as an authenticated user, so you will receive a valid response from the api, e.g.:
```json
{
  "id": 1,
  "invoice_number": "12345",
  "published_at": "2021-03-02T14:37:59.446Z",
  "created_at": "2021-03-02T14:29:39.204Z",
  "updated_at": "2021-03-02T14:37:59.460Z",
  "invoice_as_pdf": {
    "id": 2,
    "name": "invoice_12345.pdf",
    "alternativeText": "",
    "caption": "",
    "width": null,
    "height": null,
    "formats": null,
    "hash": "invoice_12345_b34614cb5c",
    "ext": ".pdf",
    "mime": "application/pdf",
    "size": 184.29,
    "url": "/uploads/invoice_12345_b34614cb5c.pdf",
    "previewUrl": null,
    "provider": "local",
    "provider_metadata": null,
    "created_at": "2021-03-02T14:29:35.191Z",
    "updated_at": "2021-03-02T14:29:35.201Z"
  }
}
```

Now use the url from above (provided by the secured api endpoint):
`"url": "/uploads/invoice_12345_b34614cb5c.pdf"`

**As a non authenticated user - you can still download the file!** 

### Steps to reproduce the behavior

See above

### Expected behavior

Content should only be accessible to authenticated users(?)

### Screenshots

See above

### Additional information

The folder itself is not accessible, but the files it contains.
![Screenshot from 2021-03-02 15-54-29](https://user-images.githubusercontent.com/45003352/109667134-1f807d00-7b70-11eb-88a2-1640dc87b82b.png)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8623

**Comment by baermathias** [comment]
@derrickmehaffy So there is currently no way to protect the content from being accessed by the general public?
Any known work arrounds? Isn't that a sensitive security issue?

**Comment by derrickmehaffy** [comment]
Not currently no, and based on the general use-case it's not directly a security issue but a security enhancement request.

**Comment by baermathias** [comment]
Is there something in the pipeline? My use-case is providing an invoice (as PDF) to the user, which is a general use-case IMO. But I also need to provide other contractual documents. So I somehow need to find a solution here.

**Comment by derrickmehaffy** [comment]
Not currently, there might be a custom community provider but outside of building your own provider we don't have an ETA.

**Comment by v1talii-dev** [comment]
Is it possible to somehow set up private files for a local provider? So that certain files along the /uploads route can be checked for compliance with the user role. For example, open a file only if the user is authorized.

**Comment by 5Gears0Chill** [comment]
so i have found a way around this.

**Disclaimer: This is by no means a perfect solution. Use with caution**


### Build a policy context.

Strapi allows you to build policies for routes. this includes the upload folder.
here is mine.
```
const koaStatic = require("koa-static");
const { defaultsDeep } = require("lodash/fp");
const defaults = {
    maxAge: 60000,
    defaultIndex: true,
};
module.exports = (plugin, config) => {
    const { defaultIndex, maxAge } = defaultsDeep(defaults, config);

    strapi.server.routes([
        {
            method: "GET",
            path: "/uploads/(.*)",
            handler: koaStatic(strapi.dirs.static.public, {
                maxage: maxAge,
                defer: true,
            }),
            config: {
                auth: false,
                policies: [
                    async (policyContext, config, { strapi }) => {
                        const userId = policyContext.request.headers['user-Id'];
                        const fileName= policyContext.request.headers['file-name'];
                        if (!fileName|| !userId) {
                            return false;
                        }
                        const entry = await strapi.query('api::app-file-mappings.file-mapping').findOne({
                            where: {
                                fileName: fileName,
                                userId: userId,
                            }
                        });
                        if (entry') {
                            return true;
                        } else {
                            return false;
                        }
                    },
                ],
            },
        },
    ]);
    return plugin;
};
```
lets dissect.

the main area of interest is the `policies` array.

i expect all incoming media requests to have a specific header signature. in this context `file-name` and `user-id`

if it does not. the policy returns `false` and the client will get a 403. 

next thing i do is i query a table of mappings to see if the user has access to this file. if they do then great return true (200) if not false which is (403)

Honestly the logic you implement inside the policy is irrelevant. you can get whichever values you need to from the header and do whatever you from a querying level to ensure the file is being requested by the correct source.

you can even get the referer from `policyContext.request.header.referer` to ensure the correct domains are reached. however this is better to allow for in the config section of strapi using the cors guidelines. for example. in my case, strapi is just my cms, and my backend is .net core and frontend is angular. so my cors policy looks like this for dev.

```
  {
    name: 'strapi::cors',
    config: {
      enabled: true,
      headers: '*',
      origin: ['http://localhost:4200','http://localhost:1337']
    }
  },
```

### Client integration. 

Assuming you are on web and not integrating from a mobile perspective. links can be handled with a `fileDownloadService`.

I am using angular for this post but i guess you can do it in any framework. 

```
import { HttpClient, HttpHeaders } from '@angular/common/http';

import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class FileDownloadService {
    constructor(private _httpClient: HttpClient) {
    }


    beginDownload(url) {
        this.#getFiles(url).subscribe((response: any) => {
            this.#downloadFile(response, url);
        });
    }

    #getFiles(url) {
        let headers = new HttpHeaders();
        headers.set('file-name','some random file name.pdf'); //file name
        headers.set('user-id','12345'); // user id
        return this._httpClient.get(url, {headers: headers, responseType: "blob", });
    }

    #downloadFile(response, requestUrl) {
        const parts = requestUrl.split('.');
        let e = '';
        if (parts.length > 1) {
            e = parts[parts.length - 1].toLowerCase();
        }


        const blob = new Blob([response], { type: this.#createFileType(e) });
        const url = window.URL.createObjectURL(blob);

        // Create an anchor element to trigger the download
        const a = document.createElement('a');
        a.href = url;
        document.body.appendChild(a);

        // Programmatically trigger the download
        a.click();

        // Clean up the temporary URL and anchor element
        window.URL.revokeObjectURL(url);
        a.remove();
    }

    #createFileType(e): string {
        let fileType: string = "";
        if (e == 'pdf' || e == 'csv') {
            fileType = `application/${e}`;
        }
        else if (e == 'jpeg' || e == 'jpg' || e == 'png') {
            fileType = `image/${e}`;
        }
        else if (e == 'txt') {
            fileType = 'text/plain';
        }

        else if (e == 'ppt' || e == 'pot' || e == 'pps' || e == 'ppa') {
            fileType = 'application/vnd.ms-powerpoint';
        }
        else if (e == 'pptx') {
            fileType = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
        }
        else if (e == 'doc' || e == 'dot') {
            fileType = 'application/msword';
        }
        else if (e == 'docx') {
            fileType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        }
        else if (e == 'xls' || e == 'xlt' || e == 'xla') {
            fileType = 'application/vnd.ms-excel';
        }
        else if (e == 'xlsx') {
            fileType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
        }

        return fileType;
    }
}

```

concept is simple. instead of linking it directly in an a tag. add a button with a click method.

the click method passes the url you were gonna easily link into you a tag (sorry told you this is not perfect).

call the download service and boom bam bomb. its done. if the user is allowed to download. yayy it will open in a new window. if they are not. show some sort of error because the `httpclient` will throw a 403 and guess what. you can actually handle that because you're a grown up (its late and im typing this apologies).


i guess it works the same way in flutter from a mobile experience. 

i created a widget that does this stuff for me


```
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
// ignore: depend_on_referenced_packages
import 'package:http/http.dart' as http;

class AuthenticatedNetworkImage
    extends ImageProvider<AuthenticatedNetworkImage> {
  AuthenticatedNetworkImage(
    this.url,
  );
  final String url;

  @override
  Future<AuthenticatedNetworkImage> obtainKey(
    ImageConfiguration configuration,
  ) {
    return SynchronousFuture<AuthenticatedNetworkImage>(this);
  }

  @override
  ImageStreamCompleter loadBuffer(
    AuthenticatedNetworkImage key,
    DecoderBufferCallback decode,
  ) {
    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: 1.0,
      informationCollector: () sync* {
        yield ErrorDescription('Image URL: $url');
      },
    );
  }

  Future<ui.Codec> _loadAsync(AuthenticatedNetworkImage key) async {
    assert(key == this);

    final Uri resolved = Uri.base.resolve(key.url);
    final http.Response response = await http.get(
      resolved,
      headers: {
        'file-name: 'some-random-filename.pdf',
        'user-id': '12345'
      },
    );

    if (response.statusCode == 200) {
      final Uint8List bytes = response.bodyBytes;
      if (bytes.lengthInBytes == 0) {
        final defaultImageBytes =
            await rootBundle.load(ImageAssets.icons.ic_no_photo);
        return await ui.instantiateImageCodec(
          defaultImageBytes.buffer.asUint8List(),
        );
      }
      return await ui.instantiateImageCodec(bytes);
    } else {
      final defaultImageBytes =
          await rootBundle.load('assets/images/no-photo.png');
      return await ui.instantiateImageCodec(
        defaultImageBytes.buffer.asUint8List(),
      );
    }
  }
}
```

understandable this is for viewing pictures but the concept is the same.

I dont know if this helps anyone but i did spend a heck of a lot of time figuring this out. so i hope this makes strapi media somewhat authenticatable.

oh and if anyone is wondering on performance, in my personal capacity i havent noticed any latency on small files. however if the file passes 50mb, i have noticed a bit of buffer (mainly mp4's) but not to worry, im sure we can ignore that, right??

anyway hope this helps. 

**flies off**
