### ISSUE TITLE
Can't install GraphQL plugin

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#962]
**Informations**
- **Node.js version**: v9.10.0
- **npm version**: v5.8.0
- **Strapi version**: 3.0.0-alpha.12
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

<img width="545" alt="screen shot 2018-04-18 at 13 39 43" src="https://user-images.githubusercontent.com/1007051/38930222-6fedd93c-430f-11e8-8464-f3bd53536841.png">

Maybe related with #709, because the folder has spaces and the CLI only show the first word.

**Steps to reproduce the problem**

Click the download button from GraphQL plugin on `/admin/install-plugin`.

**What is the expected behavior?**

Install the plugin.

**Suggested solutions**

Maybe related with #709.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hey @abdonrd, probably yes ! Can you test with it in folder with no space please.

**Comment by soupette** [comment]
@abdonrd, you're seeing the download option in the marketplace because the admin uses the `context` where all the plugins with an Admin are set. Since this [commit](https://github.com/strapi/strapi/commit/0f2ebfa997c99137b3753c55caaa1babb40aa0c2) a plugin can be installed without the Admin folder, therefore it's not injected into the admin panel.

In this way the previous logic that checks if whether or not a plugin is mounted into the `context` is outdated.

***How can we fix it?***

We need to change the logic which is based on the `context` api and :
- create an `endpoint` in the `strapi-admin` plugin that simply returns the installed plugins (file located in `packages/strapi-admin/admin/src/config/plugins.json`)
- Get the info when the `InstallPluginPage` is mounted and base the logic on the data received previously

**Comment by Aurelsicoko** [comment]
The issue has been fixed (https://github.com/strapi/strapi/pull/982). The other solution is to run this command at the root of your project to remove the symlink of the `node_modules/strapi` folder.

```bash
cd /path/to/your/project
npm install strapi@alpha
```

**Comment by abdonrd** [comment]
Sorry, @Aurelsicoko, maybe you write in the wrong issue?
I think #973 has fixed this issue.
