### ISSUE TITLE
Video dimensions for video upload

### ISSUE THREAD

**Issue by kgnfth** [strapi/strapi#9677]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

The uploaded videos has width & height off null.
it would be useful if it had the dimensions. 

Currently i'm trying to map it with ffprobe but because i have no experience in js i keep failing creating it.

_`api/albums/controllers/album.js`_
```js
"use strict";

const { sanitizeEntity } = require("strapi-utils");
const path = require("path");
const getDimensions = require("get-video-dimensions");

module.exports = {
  async find(ctx) {
    let entities;
    if (ctx.query._q) {
      entities = await strapi.services.albums.search(ctx.query);
    } else {
      entities = await strapi.services.albums.find(ctx.query);
    }

    return entities.map((entity) => {
      const albums = sanitizeEntity(entity, {
        model: strapi.models.albums,
      });

      albums.media = albums.media.map(function (video) {
        if (video.width === null || video.height === null) {
          const videoFile = path.resolve(
            __dirname,
            "../../../public" + video.url
          );

          getDimensions(videoFile).then(function (dimensions) {
            video.width = dimensions.width;
            video.height = dimensions.height;
            console.log(video) // this works because its inside getDimensions() ?
          });
        }
        return video; // this does not
      });
      return albums;
    });
  },
};
```

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/video-dimensions-for-video-upload
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
