### ISSUE TITLE
_where is not working as expected

### ISSUE THREAD

**Issue by seloner** [strapi/strapi#9748]
- Node.js version: 14
- NPM version:
- Strapi version: 3.5.3
- Database: postgre
- Operating system:Macos

In my model I have a product with many to many relation with the product attribute .
I want to get the products that have product attributes with id 3 AND id 8

I would expect something like to work but it does not.

``` js
const query = await strapi.query("product").find({
      _where: [
        {
          productAttributes: "8",
        },
        {
          productAttributes: "3",
        },
      ],
    });
```

The thing that I found it works is this
```js
const query = await strapi.query("product").find({
      _where: [
        {
          productAttributes: "8",
          productAttributes: "3",
        },
      ],
    });
```
This is a turnaround but in graphql if you try to do something like the above solution you will get an error There can be only one input field named \"productAttributes\".

**Comment by LeBenLeBen** [comment]
I have a similar issue where I want to find all the Recipes that have the Tags A and B, not A or B. It seems to be the same issue that was reported in #4680 a while back.

Here’s my Recipe model, shortened:

```json
{
  "kind": "collectionType",
  "collectionName": "recipes",
  "info": {
    "name": "Recipes",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "tags": {
      "collection": "tags",
      "via": "recipes",
      "dominant": true
    },
  }
}
```

And my Tag model:

```json
{
  "kind": "collectionType",
  "collectionName": "tags",
  "info": {
    "name": "Tags",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "recipes": {
      "via": "tags",
      "collection": "recipe"
    },
  }
}
```

I started by doing the following query:

```
{
	"where": {
		"tags_in": [
			"203",
			"206"
		]
	}
}
```

It return both tags recipes, which is correct due to the implicit OR, but not what I want. So I dug a bit in the docs and found that using `_where` with an Array of filters would make them additive. So I tried the following:

```json
{
	"where": {
		"_where": [
			{
				"tags": "203"
			},
			{
				"tags": "206"
			}
		]
	}
}
```

But it returns no results despite having Recipes with both tags 206 and 203 in the DB. The request works fine with one tag but not with multiple. It produce the following query:

```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '206', '203', 20 ],
  __knexQueryUid: 'Lf4sz8tzREyZgqb9t2dxD',
  sql: 'select distinct `recipes`.*, `recipes`.`created_at` as `_strapi_tmp_recipes_created_at` from `recipes` left join `main`.`recipes_tags__tags_recipes` as `recipes_tags__tags_recipes_1` on `recipes_tags__tags_recipes_1`.`recipe_id` = `recipes`.`id` left join `main`.`tags` as `tags_1` on `recipes_tags__tags_recipes_1`.`tag_id` = `tags_1`.`id` where ((`tags_1`.`id` = ?)) and ((`tags_1`.`id` = ?)) and (`recipes`.`published_at` is not null) order by `_strapi_tmp_recipes_created_at` asc limit ?'
}
```

@seloner When you say your first query doesn’t work, does it also return no results at all?

**Comment by seloner** [comment]
Yes I mean that it does not return any data

**Comment by wintercounter** [comment]
Seems like I've bumped into the same issue, I already had this forum thread open, maybe it helps in something: https://forum.strapi.io/t/how-to-filter-with-and-logic-with-has-many-relation/3676

**Comment by wintercounter** [comment]
I dove deep into the details because this is a blocking issue for us now. I've found the problem, and I know how it can be solved at SQL level. To fix this inside Strapi, we would need some help from someone with experience on the codebase.

Due to how `has many` relations are solved, the query Strapi is building will never work.

Relations are stored in a separate table and each relation stored in a separate row (and that's perfectly fine).

```
Table: articles__keywords

article_id   keyword_id
1               22
1               23
```

When we run a query as:
```
_where: [
     { keywords: { title: 'sports' }},
     { keywords: { title: 'business' }}
]
```
it'll generate the SQL query as such (oversimplified version):
```
SELECT id FROM articles__keywords WHERE keyword_id = 22 AND keyword_id = 23
```

It's easy to see why the above will never work and why it returns empty results.

Queries need to be adjusted based on the type of relationship. In my case for `hasMany` the query should look like:

```
SELECT `article_id` FROM `articles__keywords` WHERE `keyword_id` IN (136, 138) GROUP BY content_id HAVING COUNT(DISTINCT keyword_id) = 2
```

This will make sure to get distinct IDs which are having the specified keywords.

I have no expertise in Strapi's core, would be nice if an experienced developer would take a look at how much effort this would need to be fixed.

**Comment by wintercounter** [comment]
I'd like to share my use case where I found some further problems.

The previously mentioned solution only works in case you're using an exact match. In my case this is different, I'm also using `_contains` in my filter which complicates the necessary query further.

Example filter:
```
_where: [
    { Keyword: 'car' },
    { Keyword_contains: 'bmw' },
    { Keyword_contains: 'ford' }
]
```

In that case, I cannot simply use `IN(x,y,z)` in my query, as it needs `LIKE`.

For now, I'm solving these with custom knex queries and decided to have a solution where there is 1 "hard keyword" (the one that must equal), the rest are "soft".

The final query of my previous comment becomes like (after I manually collected all the keyword IDs):
```sql
SELECT `article_id`
FROM `articles__keywords`
WHERE `keyword_id` IN (136, 138, 140)
GROUP BY `content_id`
HAVING COUNT(DISTINCT keyword_id) = 3
#  must include "hard" keyword
AND sum(keyword_id = 136) > 0
```

Unfortunately, this is only one case and this can get much more complicated with a different mix of filters.

From my past experiences using many small queries than less big ones is a more performant approach. I optimized many systems with such changes before. Small queries are more performant, more cachable and it needs less logic because it can be handled at the end at JS level. Maybe that's something to consider for a more flexible system.

Hope this post will help during the refact later for v4.

**Comment by derrickmehaffy** [comment]
shouldn't be an issue in v4 with the new filter logic at multiple levels

**Comment by icopp** [comment]
Is there really no chance of this getting backported to v3? This leaves those of us who are still running v3 out in the cold in this problem.

**Comment by derrickmehaffy** [comment]
> Is there really no chance of this getting backported to v3? This leaves those of us who are still running v3 out in the cold in this problem.

We completely rewrote both the database query layer and the entityService layer which make it completely impossible to backport back to v3 and we are no longer working on the v3 code base and instead building on v4.
