### ISSUE TITLE
URL Parameter only applies during build

### ISSUE THREAD

**Issue by tjrexer** [strapi/strapi#9786]
### Describe the bug

The url & admin url of the app is only modifiable during build.  This is a problem when trying to dockerize strapi & use in a CI/CD environment.

### Steps to reproduce the behavior

1. Create a strapi app
2. Add a the server config.
3. Build the project
4. Build your container
5. On another host, start container & provide any URL other than `localhost` ex: `docker run -p 1337:1337 -ti --env URL=https://site`
6. Watch the logs & see the url doesn't change.
7. Attempt to connect to new container's admin.

If you are not running strapi locally, it will fail because it try and get `/admin/init/` from `localhost:1337` instead of `https://site/admin/init`.  This is also valid if you provide an admin url at runtime.

### Expected behavior

URL should be modifiable like any other config options, database, email, upload plugins, etc.  This allows you to properly dockerize the application.  Without it being configured properly, your containers are no-longer stateless & you have to build a custom image for each environment.

### Code snippets

Sample config:
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('URL', 'https://localhost:1337'),
  //...
});
```

Sample Dockerfile:
```
FROM strapi/base as base

# Add args for ENV variables

WORKDIR /srapi-app
COPY package*.json/ ./
COPY yarn.lock ./
RUN yarn install
COPY ./build/ ./build/
```

### System

- Node.js version: 12.20.1
- NPM version: any
- Strapi version: 3.5
- Database: postgres
- Operating system: Mac (Doesn't matter since it's a containerized app)

### Additional context
Forum discussion on the issue.  Helped provide additional context & troubleshooting.
[URL parameter for Server not working (for Nginx proxy) #7310](https://forum.strapi.io/t/url-parameter-for-server-not-working-for-nginx-proxy-7310/1752)

**Comment by derrickmehaffy** [comment]
We are aware of this however it won't change in the v3 as it's considered a breaking change.

**Comment by enote-kane** [comment]
This issue still persists in v4. Are there any actual plans to address this in "some" future major version upgrade or not.

In addition, there are no docs about which environment variables may be changed without rebuild and which need a rebuild to be applied correctly. The docs as of now (https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables) pretend that all environment variables can be set without a rebuild.

This is obviously not true and as a result, this issue could be seen as a bug, rather than a feature/change request.

I wonder why this should be considered a "breaking" change, though. What would "break" if properly supporting what the docs are claiming?

What's actually worse is the fact the during startup, Strapi advertises the currently configured `url` in the terminal, so even the code backs the claim from the docs. Nevertheless, it's not working. Hence, this really is a bug from my perspective.
