### ISSUE TITLE
Thumbnail preview for the uploaded files such as pdf, docx. etc

### ISSUE THREAD

**Issue by old-software-engineer** [strapi/strapi#9797]
## Feature request

Show the thumbnail preview for the files apart from just images such pdf or docx

### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Currently thumbnails are only present for medial files such as images. A general improvement would be to have thumbnails showing first page of common files such as PDFs, DOCXs, etc. 

### Why is it needed?

Since the user(content manager) needs to download the file every time in order to see the content of the attachment. So the file preview thumbnail will help to have a basic preview of the uploaded file and will make it look more interactive.

### Suggested solution(s)

Currently not have any.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/thumbnail-preview-for-the-uploaded-files-such-as-pdf-docx-etc
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
