### ISSUE TITLE
Modifying filters in admin panel

### ISSUE THREAD

**Issue by old-software-engineer** [strapi/strapi#9798]
## Feature request

Altering the options inside the filters.

### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Currently the filters values cannot be change or alter without changing the actual field values. A general improvement would be to provide a way to edit(rename) the options inside the filter without changing its field value.

### Why is it needed?

Since the filter options are based on the field values and **cannot be changed separately** this creates an problem such as if user wants to rename some of the filter options to their translated version it cannot be done without changing the original value and renaming the values from Database can be messy as it cannot be randomly change.

### Suggested solution(s)

Currently not have any.

### Related issue(s)/PR(s)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/modifying-filters-in-admin-panel
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
