### ISSUE TITLE
[cloudinary plugin] Use thumbnail version on strapi backend

### ISSUE THREAD

**Issue by finex** [strapi/strapi#9803]
## Describe the bug

Media image field preview use full image instead of thumbnail from Cloudinary (I've not checked Strapi without Cloudinary plugin)

## Steps to reproduce the behavior

1. Create a "post" content type with an image field
2. Enable and configure strapi-provider-upload-cloudinary plugin
3. Create a post and add an image
4. the image field preview will load the full image instead of the thumbnail version

## Expected behavior

Use the thumbnail to avoid unnecessary data transfer (Cloudinary does have bandwidth limits) .

## Additional info

You have the same behaviour on the "edit" popup clicking on the following icon:

![image](https://user-images.githubusercontent.com/287009/112021194-eb71f980-8b28-11eb-84e7-08432ed27bcb.png)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/use-thumbnail-version-on-strapi-backend
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
