### ISSUE TITLE
WYSIWYG cursor going at the end of the text area

### ISSUE THREAD

**Issue by pierreburgy** [strapi/strapi#985]
**Informations**
- **Node.js version**: 9.5.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12
- **Database**: MongoDB
- **Operating system**: MacOS 10.12.4
- **Web Browser**: Safari 10.1

**What is the current behavior?**
On Safari (10.1), when using the controls of the Rich Text Editor, the cursor is going at the end of the text area.

![strapi-safari-bug](https://user-images.githubusercontent.com/5550462/39050531-0b9b4c38-44a6-11e8-9a0f-81b5cc273266.gif)

**Steps to reproduce the problem**
 - Create a Strapi project
 - Create a Content Type with a field using the WYSIWYG
 - Edit content using control buttons

**What is the expected behavior?**
The cursor should not go at the end of the text area.

**Suggested solutions**
Check web browser compatibility and Webpack build configuration.

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by derrickmehaffy** [comment]
@pierreburgy (can't believe I'm typing this lol) does this still happen on the latest version? Checking to see if we can close out some old issues.

**Comment by soupette** [comment]
@derrickmehaffy it's still happening 😖 😖 but I don't have the time to fix it for the moment...

**Comment by derrickmehaffy** [comment]
Ha no big @soupette just wanted to check. I haven't noticed it on Chrome >.> It certainly is an odd issue though.

**Comment by Tonours** [comment]
Hey 👋 !
 
After doing some tests i was able to reproduce this bug in Chrome, Firefox, Safari and Opera.

When selecting a text and choosing `Header`, `bold`, `italic`, or `line-through`, focus going at the end of the textarea.

This is caused by the `moveFocusToEnd`in `addContent` (and `addBlock`) method https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js#L178 

Documentation for this method could be found in Draftjs codebase comment: https://github.com/facebook/draft-js/blob/master/src/model/immutable/EditorState.js#L328

The solution to this, it to replace `editorState: EditorState.moveFocusToEnd(newEditorState)` by `newEditorState` when adding bold, italic or line-through.

**Comment by vasusuccessive** [comment]
Can anyone please tell me the solution for this, I am facing the same issue. Thanks in advance.

**Comment by derrickmehaffy** [comment]
@vasusuccessive this issue should have been fixed years ago (the issue is 3 years old). Can you open up a new bug report and provide more updated information?

**Comment by derrickmehaffy** [comment]
@vasusuccessive open a new issue please.
